ocaml/xapi/console.ml
Xenopsd no longer manages dom0 and so Xapi cannot ask it for the address of
dom0's console. Instead it should use the information it has in the database.
Incidentally, this information was no longer correct. Dom0 has had its console
on 5901 for a while it seems but the database used to get updated correctly
when Xenopsd managed dom0.
=> CA-141580: Fix dom0 console handler

ocaml/xapi/xapi_vbd.ml, ocaml/xapi/xapi_vdi_helpers.ml
=> Allow ISO VBDs to be made from any SR

ocaml/xapi/xapi_pool_patch.ml
=> CA-153556: Perform sanity check and lowercase for hotfix UUIDs

ocaml/xapi/xapi_globs.ml
=> Migrate_send wasn't a Miami operation

Makefile, xapi.spec.in
=> Add dependencies to spec file

ocaml/lvhdrt/lvhdrt-helper, ocaml/multipathrt/multipathrt-helper
=> CA-152196: Fix some paths in lvhdrt and multipathrt

ocaml/xapi/xapi_pgpu.ml
The PGPU will be created with an empty list of supported_VGPU_types for
now.
=> CP-10126: Create a PGPU for the system display device

scripts/OMakefile, scripts/plugins/install-supp-pack, xapi.spec.in
=> CP-10774: Add an 'install-supp-pack' plugin

ocaml/xapi/importexport.ml
spawn a cached stunnel instance to transmit xml format vm
metadata information, avoid partial xml transmission
Signed-off-by: Chunjie Zhu <chunjie.zhu@citrix.com>
=> CA-154009: Failure("int_of_string") raised by assert_can_migrate

scripts/OMakefile, scripts/xe-install-supplemental-pack, xapi.spec.in
Add the xe-install-supplemental-pack script to xapi, and modify it to be suitable to install from a VDI.
=> CP-10773 - move xe-install-supplemental-pack into xen-api.git and expand it slightly

ocaml/idl/datamodel.ml, ocaml/idl/datamodel_types.ml
Define creedence_cream in datamodel, and change augusta to dundee.
Update last_release_schema_(major|minor)_version in datamodel.
=> Define cream in trunk

ocaml/idl/ocaml_backend/taskHelper.ml, ocaml/idl/ocaml_backend/taskHelper.mli, ocaml/xapi/cli_operations.ml, ocaml/xapi/stream_vdi.ml, ocaml/xapi/xapi_templates_install.ml, ocaml/xapi/xapi_vm_clone.ml, ocaml/xapi/xapi_vm_migrate.ml, ocaml/xapi/xapi_vm_snapshot.ml
Also use TaskHelpers.exn_if_cancelling wherever possible.
=> Make sure we return the task ref when raising task_cancelled

ocaml/idl/datamodel.ml, ocaml/xapi/cli_frontend.ml, ocaml/xapi/cli_operations.ml, ocaml/xapi/message_forwarding.ml, ocaml/xapi/xapi_vm.ml, ocaml/xapi/xapi_vm.mli, ocaml/xapi/xapi_vm_lifecycle.ml, ocaml/xapi/xapi_xenops.ml, ocaml/xenops/xenops_interface.ml, ocaml/xenops/xenops_server.ml, ocaml/xenops/xenops_server_plugin.ml, ocaml/xenops/xenops_server_simulator.ml, ocaml/xenops/xenops_server_xen.ml
This commit is to port the code of CP-10203 (https://github.com/xapi-project/xen-api/pull/2042) from master to feature branch.
=> CP-10823: XenAPI: api call for RDP on/off request

ocaml/xapi/xapi_vm.ml
This is to port code change of CP-10954 from creendence-sp.
Thanks.
=> CP-10996: Use feature-ts2 as RDP feature indicator.

ocaml/xapi/xapi_hooks.ml
=> Remove VM hooks which are now handled by xenopsd

ocaml/xapi/xapi_globs.ml, ocaml/xapi/xapi_xenops.ml
Add the PCI device if VM.platform.pci_pv is set to true.
Signed-off-by: Kaifeng Zhu <kaifeng.zhu@citrix.com>
=> CP-10533: Add an PCI device to VM if specified

scripts/OMakefile, scripts/plugins/install-supp-pack, scripts/xe-install-supplemental-pack, xapi.spec.in
This has both PR 2080 and 2081 backported.
=> [Cream] CP-10872: Port supp pack work to cream.

ocaml/xapi/export.ml
Instead of having the tar library stream the metadata directly to the remote
location, we now stream it through a pipe into a string. This lets us
read length of the tar data, and use this as the content-length supplied
in the HTTP response.
This allows the sender to use a cached stunnel; without sending the
content-length the receiver would wait forever as it couldn't determine
that all data had been sent.
We now also respond with HTTP 500 if anything goes wrong with the
metadata export; previously we would just write the tar footer and
continue as normal.
=> CA-157775: Send content-length when exporting metadata

ocaml/xenops/squeeze_xen.ml
Cleanup disappear domains in domain make to avoid dirty domain cache
=> CA-155178: Remove squeeze_xen cache if domain disappear

ocaml/xapi/sm.ml, ocaml/xapi/sm_exec.ml, ocaml/xapi/smint.ml, ocaml/xapi/storage_access.ml, ocaml/xapi/storage_impl_test.ml, ocaml/xapi/storage_interface.ml, ocaml/xapi/xapi_globs.ml, ocaml/xenops/xenops_server_xen.ml
Backport of the following upstream pull requests:
* https://github.com/xapi-project/xen-api/pull/2125
* https://github.com/xapi-project/xcp-idl/pull/49
* https://github.com/xapi-project/xenopsd/pull/165
=> CP-10770: API to query whether read caching is enabled/disabled for a VDI

ocaml/xapi/storage_access.ml
=> CP-10770: Don't duplicate read_caching key in sm_config

ocaml/xapi/xapi_vm_snapshot.ml
This fix also includes the rebased fix of CP-10974
=> CP-11007: Update VDI.snapshot_of links after VM.revert

ocaml/xenops/updates.ml, ocaml/xenops/xenops_client.ml
Each barrier injected among the xenops events now holds a snapshot of
the event id counter as well as the set of events. The get function uses
this to select only the barriers newer than the "from" parameter, and
returns it as the "id of latest thing found" if it is newer than all the
events. If there are no barriers or events to return then the function
waits: this behaviour is unchanged, but now there will be no barriers to
return if there are barriers but they are all too old to be of interest
to the caller.
This means a client no longer keeps calling repeatedly with the same
"from" and getting back the same result (one or more barriers, no events
and the same next-id as the "from" param).
Because each barrier has an extra int associated with it, the formats
for RPC and Dump have …
=> [Caboodle/HFX-1297] CA-134972: fix a tight loop getting xenops updates

ocaml/xenops/squeeze_xen.ml
Cleanup disappear domains in domain make to avoid dirty domain cache
=> [Caboodle/HFX-1304] CA-155178: Remove squeeze_xen cache if domain disappear

ocaml/xapi/xapi_vm_snapshot.ml
Instead of ignoring the snapshot's CD VBDs, we clone them as normal to
the new VM. However, we still disregard the CD VBDs when fixing up the
snapshot_of links.
=> CA-160970: Recreate CD VBDs after a revert to snapshot

ocaml/xapi/xapi_pgpu.ml
=> CP-10877: Access of PGPUs to dom0 using xen-cmdline

ocaml/idl/api_errors.ml, ocaml/idl/datamodel.ml, ocaml/xapi/xapi_pool_patch.ml
Forward port of https://github.com/xapi-project/xen-api/pull/2166.
=> CP-11182: Create API error for PATCH_PRECHECK_OUT_OF_SPACE

ocaml/idl/datamodel.ml, ocaml/idl/datamodel_types.ml
This defines the Cream release in the creedence-bugfix branch.
=> (creedence-bugfix branch) define cream

ocaml/xapi/xapi_fist.ml, ocaml/xapi/xapi_vgpu_type.ml
=> Create a dummy vGPU type

ocaml/xapi/storage_access.ml
=> CA-162736: Protect VDI.sm_config.read_caching_enabled with a mutex

ocaml/idl/datamodel.ml, ocaml/idl/datamodel_types.ml, ocaml/idl/datamodel_utils.ml
=> doc: add a Memory documentation tag.

ocaml/xapi/xapi_pool_patch.ml
=> CA-163770: Hotfixes require three times their space to install

ocaml/xapi/sm.ml, ocaml/xapi/sm_exec.ml, ocaml/xapi/smint.ml, ocaml/xapi/storage_access.ml, ocaml/xapi/storage_impl_test.ml, ocaml/xapi/xapi_globs.ml
Note, this depends on https://github.com/xapi-project/xcp-idl/pull/49.
=> Forward port read caching API

ocaml/database/master_connection.ml, ocaml/xapi/helpers.ml, ocaml/xapi/xapi_xenops.ml
Fix for CA-161590, CA-160978, CA-146164 ... forward porting xenserver/xen-api#11.
=> CA-161590 etc

ocaml/xapi/xapi_db_upgrade.ml
This is sourced from creedence commit
2e1dd480666e228c48c84b39986a60e9488e5395
=> CA-167506: Remove editions upgrade code, which is no longer needed

ocaml/test/suite.ml
=> The unit tests should not try to use the message-switch

ocaml/xapi/xapi_db_upgrade.ml
The patch adds an upgrade rule that modifies the VM.recommendations field when
upgrading from pre-Cream to Cream. For all VMs that have allow-gpu-passthrough
set to 0, the rule sets allow-gpu-passthrough to 1 and additionally adds
allow-vgpu and sets this to 0. The assumption is that the only pre-Cream VMs
that have allow-gpu-passthrough = 0 are HVM Linux VMs.
The reason for doing this is that HVM Linux guests gained the ability to use
GPU passthrough in Cream, but this won't be automatically reflected in the
VM.recommendations (used by e.g. XenCenter to determine whether the
functionality is allowed). For the future, we should find a better way of
upgrading this field.
=> CA-164806: Upgrade allow-gpu-passthrough recommendations

scripts/xn_diagnostics
This avoids having to modify the script if the mode changes in future.
=> xn_diagnostics: support switch and non-switch mode

ocaml/xapi/xapi_services.ml
=> When forwarding to a remote xenvmd, append the session_id

.travis.yml
=> Enable travis notifications in Slack

scripts/mail-alarm
This patch converts the xml formatted body of the message to a more readable format
=> CA-156826: Making Alert messages more readable

ocaml/auth/extauth_plugin_ADpbis.ml
During AD auth login to xenserver, some pbis command will be called twice(e.g. find-by-sid/list-groups-for-user)
To improve its performance, we need add common cache for the pbis_common function in extauth_plugin_ADpbis.ml
=> CP-12169: Add common cache to xapi/exauth for PBIS CLI output

scripts/mail-alarm
=> CA-172676: Putting the missing % from commit b7ceddd

ocaml/xapi/xapi_sr.ml
=> CA-173410: When creating a shared SR, plug the master's PBD first

scripts/mail-alarm
=> CA-172992: Replacing "Message" with "Body" in alert mails

ocaml/xapi/OMakefile, ocaml/xapi/xapi.ml, ocaml/xapi/xapi_globs.ml, ocaml/xapi/xapi_pool_transition.ml, ocaml/xapi/xapi_services.ml, ocaml/xapi/xapi_xenvmd.ml
Mostly this code is disabled by default for now.
=> CP-12513: Give xapi the ability to manage xenvm daemons

ocaml/idl/datamodel.ml, ocaml/xapi/cli_frontend.ml, ocaml/xapi/cli_operations.ml, ocaml/xapi/message_forwarding.ml, ocaml/xapi/xapi_pool.ml, ocaml/xapi/xapi_pool.mli
and corresponding CLI commands.
=> CP-12897 Pool APIs (en|dis)able_ssl_legacy

ocaml/idl/datamodel.ml, ocaml/xapi/cli_frontend.ml, ocaml/xapi/cli_operations.ml, ocaml/xapi/import.ml, ocaml/xapi/importexport.ml, ocaml/xapi/message_forwarding.ml, ocaml/xapi/storage_access.ml, ocaml/xapi/storage_access.mli, ocaml/xapi/xapi_ha_vm_failover.ml, ocaml/xapi/xapi_network_attach_helpers.ml, ocaml/xapi/xapi_pool.ml, ocaml/xapi/xapi_vm.ml, ocaml/xapi/xapi_vm_helpers.ml, ocaml/xapi/xapi_vm_lifecycle.ml, ocaml/xapi/xapi_vm_migrate.ml
For review, don't merge yet until QA has set to integrate their part.
Passed Dundee Ring3 BST (testrun=36934) and Dundee SXM suite w/ updates (testrun=36917).
=> CAR-483: Remove Storage XenMotion Constraints

scripts/mail-alarm
=> CA-173714: Body text in alert mail must be tab separated

opam
=> Add opam constraints on xapi-idl and xapi-stdext

ocaml/idl/datamodel.ml, ocaml/xapi/cli_frontend.ml, ocaml/xapi/cli_operations.ml, ocaml/xapi/message_forwarding.ml, ocaml/xapi/xapi_ha.ml, ocaml/xapi/xapi_pool.ml, ocaml/xapi/xapi_pool.mli
New parameter cluster_stack added to Pool.enable_ha XAPI and cli
=> CP-12915: Add parameter 'cluster_stack' to Pool.enable_ha

ocaml/client_records/records.ml, ocaml/idl/datamodel.ml, ocaml/test/test_common.ml, ocaml/xapi/dbsync_master.ml
Add RO field Pool.ha_cluster_stack with default value 'xhad'
Verification Logs:
[root@x2 ~]# xe pool-param-get param-name=ha-cluster-stack uuid=5ff8dca2-885f-8ff8-5c29-7456b66a8ef4
xhad
=> CP-12914: Add the field 'Pool.ha_cluster_stack'

ocaml/xapi/storage_impl.ml
=> CA-176934: Fix race in DP.destroy

scripts/perfmon
=> CP-12640: Generate alert when log partition is full

ocaml/xapi/xapi_vm.ml
Call `Db.VM.set_ha_always_run` is very silent, Adding logs can help to identify the state of `ha_always_run` on a vm.
=> Adding debug logs on setting ha_always_run flag on vm

ocaml/xapi/xapi_xenvmd.ml
=> CA-178081: Check that xenvmd is running before killing it

ocaml/xapi/cancel_tasks.ml
Otherwise the list is empty after upgrade.
=> CA-178386: Update pool.allowed_operations on startup

ocaml/xapi/xapi.ml
When performing a bond/VLAN resync we need the ability to call the
xenopsd VIF.move API to move the backend device onto the right
bridge or switch. Previously these attempts would block because
the events from xenopsd thread wasn't running. To start the
events from xenopsd thread we need to have resynchronised the VM
state, which also requires the storage to be online.
Note this makes the case where a resync is done after a `service
xapi restart` on a live system, with plugged storage and running
VMs, more similar to the case where a resync is done after a
reboot.
=> RFC, Untested: CA-175353: resync networking after VMs have been resynced

ocaml/client_records/record_util.ml, ocaml/idl/datamodel.ml, ocaml/xapi/message_forwarding.ml, ocaml/xapi/smint.ml, ocaml/xapi/xapi_vdi.ml, ocaml/xapi/xapi_vdi_helpers.ml
=> CP-13257: Create rrd stats vdi on pbd plug

scripts/examples/python/OMakefile, xapi.spec.in
Install /opt/xensource/bin/xva-rewrite-scsiid
This comes from scripts/examples/python/xva.py
=> CAR-2031: DR via array replication using the raw LUN per VDI RawHBA adapter

ocaml/xapi/xapi_pool_transition.ml
It's possible that `become_another_masters_slave` can also be executed on
a host that is already a slave. In this case the current host
a. Doesn't need to kill any xenvmd instances since there are none; and
b. Can't because this involves talking to the host it thinks is the master.
Consider the three host example: A, B and C where A is the pool master.
1. Host A dies;
2. Pool.emergency_transition_to_master is called on host B;
3. Pool.recover_slaves is called on host B.
In this scenario, host B calls Pool.emergency_reset_master to host C. Host C is
already a slave and is remaining a slave but acknowledging B as the new master.
It therefore cannot make use of any functions that required (what it thinks is)
the master (host A) since these will hang.
Worse still, if host A were to come alive …
=> CA-178692: Only kill xenvmd(s) when becoming a slave

ocaml/xapi/OMakefile, ocaml/xapi/cluster_stack_constraints.ml, ocaml/xapi/xapi_ha.ml, ocaml/xapi/xapi_host.ml, ocaml/xapi/xha_scripts.ml
Replaces a stub now that SMAPIv3 has the necessary support to express cluster stack requirements.
=> HA: obtain cluster stack constraints and use them

ocaml/xapi/storage_access.ml, ocaml/xapi/storage_impl_test.ml, ocaml/xapi/xapi_globs.ml
Needs to be merged at the same time as [xapi-project/xcp-idl#89]
=> Change queue prefix from org.xen.xcp to org.xen.xapi

ocaml/xapi/storage_access.ml
We can extract the encoded backtrace information and rethrow the exception.
=> CP-13837: transform Backend_error_with_backtrace into Backend_error

OMakefile, configure.ml, ocaml/idl/datamodel.ml, ocaml/idl/datamodel_types.ml, ocaml/idl/datamodel_utils.ml, ocaml/idl/ocaml_backend/OMakefile, ocaml/idl/ocaml_backend/gen_empty_custom.ml, ocaml/idl/ocaml_backend/gen_server.ml, ocaml/idl/ocaml_backend/server_helpers.ml, ocaml/xapi/api_server.ml, ocaml/xapi/cli_frontend.ml, ocaml/xapi/cli_operations.ml, ocaml/xapi/message_forwarding.ml, ocaml/xapi/xapi_extensions.ml, ocaml/xapi/xapi_extensions.mli, ocaml/xapi/xapi_globs.ml, ocaml/xapi/xapi_host.ml, ocaml/xapi/xapi_pool.ml, ocaml/xapi/xapi_pool.mli, scripts/OMakefile, scripts/extensions/Test.test, xapi.spec.in
This is a port of [xapi-project/xen-api#2354]
=> CP-12901: add thin-provisioning upgrade

ocaml/xapi/storage_impl.ml, ocaml/xapi/xapi_sr.ml
With these changes, first boot is happy again.
=> CP-13874: fix 2 deadlocks and 1 infinite loop

ocaml/client_records/records.ml, ocaml/idl/api_errors.ml, ocaml/idl/datamodel.ml, ocaml/test/test_common.ml, ocaml/xapi/xapi_globs.ml, ocaml/xapi/xapi_host_helpers.ml, ocaml/xapi/xapi_pbd.ml, ocaml/xapi/xapi_sr.ml, ocaml/xapi/xapi_sr_operations.ml
This implements step 3 of the design at http://xapi-project.github.io/features/futures/aggr-storage-reboots.html, and includes a few fixes.
=> Block host reboot/shutdown if clustered SR is "degraded"

ocaml/xapi/helpers.ml, ocaml/xapi/message_forwarding.ml, ocaml/xapi/xapi_host_helpers.ml, ocaml/xapi/xapi_sr.ml, ocaml/xapi/xapi_sr_operations.ml
This implements step 4 of the design at http://xapi-project.github.io/features/futures/aggr-storage-reboots.html.
=> Update host allowed_operations based on clustered SR state

scripts/xe-toolstack-restart
Signed-off-by: Robert Breker <robert.breker@citrix.com>
=> CP-13884: Restart xapi-storage-script as part of xe-toolstack-restart

ocaml/test/test_platformdata.ml, ocaml/xapi/xapi_xenops.ml
Add proper error message while attempting to start a HVM domain with
invalid configuration of VCPUs
=> CP-13878: Improve error message when attempting to start VM with invalid configuration of VCPUs

ocaml/xapi/xapi_vbd.ml, ocaml/xapi/xapi_vdi.ml
1) New API write_rrd: will write the RRDs to the rrd-stats VDI
2) New API read_rrd: will read the RRDs from the rrd-stats VDI
Its duplicate of https://github.com/xapi-project/xen-api/pull/2338, This PR is already reviewed.
=> CP-13491: Read-Write RRDs into the RRD VDI

ocaml/client_records/record_util.ml, ocaml/idl/api_errors.ml, ocaml/idl/datamodel.ml, ocaml/xapi/cli_frontend.ml, ocaml/xapi/helpers.ml, ocaml/xapi/message_forwarding.ml, ocaml/xapi/xapi_globs.ml, ocaml/xapi/xapi_vm.ml, ocaml/xapi/xapi_vm_helpers.ml, ocaml/xapi/xapi_xenops.ml, ocaml/xe-cli/newcli.ml
This pull req implements a vm plugin to run in-guest scripts provided by users. See REQ-103 (ScaleXtreme PR) for the actual requirements.
=> CAR-1744: add support for running in-guest user scripts

ocaml/xapi/xapi_pool_patch.ml
Tests done:
* run all the patching related sequences in nightly to verify there is no regression
* manually created several scenarios where concurrency is an issue and verified the change can fix these
=> XOP-681: Fix some concurrency issue on host patching

ocaml/test/test_common.ml
=> Fix unit tests due to new cpu_info field

scripts/plugins/install-supp-pack, scripts/xe-install-supplemental-pack
Adding support to upgrade a supp pack using toolstack plugin
from XenCenter
=> CA-173711: Added option to upgrade supp packs during install

.travis.yml
=> travis: Pin xcp-idl to feature branch when testing trunk-level

ocaml/xapi/xapi_pool.ml
From now on, we'll allow in hosts with different CPU features. The pool
CPU feature level will be automatically adjusted, if needed.
=> Update pool join checks: only match on CPU vendor

ocaml/test/OMakefile, ocaml/test/suite.ml, ocaml/test/test_cpuid_helpers.ml, ocaml/test/test_printers.ml
=> CP-14265: Add unit tests for CPU feature string parsing

ocaml/test/test_cpuid_helpers.ml, ocaml/xapi/cpuid_helpers.ml, ocaml/xapi/cpuid_helpers.mli
=> CP-14265: Add zero_extend function for CPU feature flags

ocaml/test/test_printers.ml
=> Test_printers: Add tuple3, tuple4 and tuple5 combinators

ocaml/xapi/message_forwarding.ml
Setting ssl_legacy now resets the master connection (see commit 9a5edf8)
so the master now expects the slaves to disconnect and polls until the
database reports that the slave has ssl_legacy set to the correct value.
=> CA-185997: Tolerate connection loss when setting ssl_legacy

ocaml/xapi/xapi_sr.ml
Note, this depends on https://github.com/xapi-project/xcp-idl/pull/100.
=> CA-185923: Use new SR Rrd_interface and handle errors

ocaml/xapi/xapi_dr_task.ml, ocaml/xapi/xapi_sr.ml
=> Ensure master PBD is unplugged last in more places

ocaml/xapi/storage_impl.ml
=> CA-187261: Don't log the password during SR attach

ocaml/xapi/xapi_session.ml
Before xapi_session.do_external_auth, we should check the external auth service status at first.
=> CA-185733: RPU XenCenter stuck on upgrade screen if connected as XS Pool Admin

ocaml/idl/api_messages.ml, ocaml/xapi/create_misc.ml
=> Create separate API messages for the pool/host CPU level up/down cases

ocaml/test/test_cpuid_helpers.ml
This test seems to have fallen out of the test suite at some
point.
=> test_cpuid_helpers: Run feature string to string roundtrip test

ocaml/idl/api_messages.ml
=> FIXUP message names

ocaml/xapi/storage_access.ml, ocaml/xapi/storage_access.mli, ocaml/xapi/xapi_sr.ml, ocaml/xapi/xapi_sr_operations.ml
=> CA-187730: Ignore stats VDI when checking safe to destroy SR

ocaml/xapi/xapi_host.ml
=> CA-188458: Recalculate pool CPU level after host-forget.

ocaml/test/test_cpuid_helpers.ml, ocaml/xapi/cpuid_helpers.ml
=> Put back call to upgrade_features in assert_vm_is_compatible

ocaml/xapi/dbsync_slave.ml, ocaml/xapi/monitor_master.ml, ocaml/xapi/rrdd_proxy.ml, ocaml/xapi/xapi_ha.ml, ocaml/xapi/xapi_host.ml, ocaml/xapi/xapi_vm.ml, ocaml/xapi/xapi_vm_lifecycle.ml
Now that the WLB tests are passing, I think this is good to go in.
=> CP-12141: Remove master/slave knowledge from RRDD

ocaml/xapi/xapi_vm_helpers.ml
=> CA-189154: Check featureset when selecting a host for a VM

ocaml/xapi/xapi_vm_migrate.ml
=> CA-189767: Use Smint Vdi_snapshot type capability rather than string

ocaml/idl/datamodel.ml, ocaml/test/test_common.ml, ocaml/xapi/cli_operations.ml, ocaml/xapi/create_misc.ml, ocaml/xapi/import_xva.ml, ocaml/xapi/xapi_vm.ml, ocaml/xapi/xapi_vm.mli, ocaml/xapi/xapi_vm_clone.ml, ocaml/xapi/xapi_vm_helpers.ml
A new VM field intended to replace auto_update_drivers.
This commit is the first stage, adding the new field so that new
code can refer to it immediately and existing code can be changed to
refer to it, and then it will be possible to remove the old field.
=> CP-15105: VM.has_vendor_device

ocaml/xapi/xapi_sm.ml
This original issue only manifested in trunk-btrfs-3. RobertB suggested to upstream via trunk-ring3 as it won't do any harm here and we'll eventually need it.
=> CA-178645: serialize SM plugin registration

ocaml/auth/extauth_plugin_ADpbis.ml, ocaml/idl/datamodel.ml, ocaml/idl/datamodel_types.ml, ocaml/idl/datamodel_utils.ml, ocaml/idl/ocaml_backend/gen_empty_custom.ml, ocaml/idl/ocaml_backend/gen_server.ml, ocaml/test/OMakefile, ocaml/test/suite.ml, ocaml/test/test_datamodel_utils.ml, ocaml/test/test_pool_license.ml, ocaml/xapi/cli_frontend.ml, ocaml/xapi/cli_operations.ml, ocaml/xapi/cli_operations_geneva.ml, ocaml/xapi/dbsync_slave.ml, ocaml/xapi/features.ml, ocaml/xapi/features.mli, ocaml/xapi/license_check.ml, ocaml/xapi/license_check.mli, ocaml/xapi/message_forwarding.ml, ocaml/xapi/xapi_host.ml, ocaml/xapi/xapi_host.mli, ocaml/xapi/xapi_pool.ml, ocaml/xapi/xapi_pool_license.ml, ocaml/xapi/xapi_vm_migrate.ml, ocaml/xe-cli/bash-completion, ocaml/xe-cli/newcli.ml
This is a forward port of https://github.com/xenserver/xen-api/pull/54, leaving out the patches that were already applied, plus the patches about the OEM keys.
=> Host.license_add and related

ocaml/xapi/create_misc.ml
=> CA-194079: Handle host featureset increases correctly

ocaml/xapi/xapi_vm_migrate.ml
=> CA-194323: Upgrade CPU featureset in Boston migration handler

ocaml/idl/api_errors.ml, ocaml/idl/datamodel.ml, ocaml/xapi/xapi_vm_migrate.ml
This pull request needs to be on-hold until QA update their test cases. It is also more lenient w.r.t. intra-pool migration.
=> Reinstate CA-187693: Handle unmapped VIFs and VDIs correctly

ocaml/xapi/quicktest.ml
=> CP-14531: Set outgoing ciphersuites in quicktest.

ocaml/xapi/xapi_xenops.ml
Also remove event suppression from 'start_on' - the VM shouldn't
be resident_on at this point, hence there's no need to suppress
the events.
=> CA-197801: Resync with xenopsd when setting resident_on

ocaml/xapi/dbsync_master.ml, ocaml/xapi/xapi_globs.ml
=> CP-15893: Use branding in Tools SR name/description

.gitignore
=> gitignore: Ignore daily-license-check binary output

ocaml/xapi/storage_migrate.ml, ocaml/xapi/xapi_vm_migrate.ml
=> Tidy and document the SXM code.

ocaml/xapi/cli_operations.ml
=> CA-106123: Show sockets in xe host-license-view

scripts/mail-alarm
=> CA-202289: mail-alarm: Get PRODUCT_BRAND from branding module

ocaml/xapi/export.ml, ocaml/xapi/message_forwarding.ml, ocaml/xapi/xapi_vm.ml, ocaml/xapi/xapi_vm_helpers.ml, ocaml/xapi/xapi_vm_lifecycle.ml
* Add force flag to with_vm_operation
* Pass force flag in pool_migrate
=> CA-202419: Make vm-migrate --force override tools check for HVM guests

ocaml/idl/datamodel.ml
=> CA-204237: Add default for configure_ipv4 and configure_ipv6

ocaml/xapi/cli_operations.ml
=> CA-204240: Add more vif-configure-ip command paramters check

ocaml/idl/datamodel.ml
=> CA-206592: Change RBAC of vif-config-ipv* to _R_VM_OP

scripts/license-check
=> CA-207440: Stop daily-license-check cron spamming dead.letter

ocaml/xapi/message_forwarding.ml, ocaml/xapi/xapi_vm.ml, ocaml/xapi/xapi_xenops.ml
We need task cancellation of vm lifecycle operation in
message_forwarding in order to aquire lock on VBDs and VIFs
for hard_reboot and hard_shutdown operations.
And exception raised during shutdown and reboot must
wait for the event thread to sync on slave before returning
in order to update the state of VM on slave.
=> CA-206753: Move task cancellation to message_forwarding

.travis.yml, deploy.sh
=> travis/deploy: add the container name to the global env

deploy.sh
=> travis/deploy: fix path in container

deploy.sh
=> travis/deploy: fix another path

deploy.sh
=> travis/deploy: safety improvements

ocaml/xapi/features.ml, ocaml/xapi/features.mli
This is just a flag; no restrictions enforced.
=> CA-207609: Add AD feature flag

ocaml/idl/datamodel.ml
=> Undeprecate VM.create

deploy.sh
The intention was to redirect both stdout and stderr to /dev/null.
=> travis/deploy: fix redirection

ocaml/idl/json_backend/main.ml
=> json/doc: split out StaticRO and DynamicRO

deploy.sh
=> deploy: Print more debug output, redacting token

xapi.spec.in
=> Add dependency on xapi-test-utils in spec file

xapi.spec.in
=> CA-211264: Re-run chkconfig on upgrade to pickup ordering changes

ocaml/idl/datamodel_types.ml
=> CP-15884: Add an Ely release to datamodel

ocaml/idl/datamodel.ml, ocaml/idl/datamodel_types.ml
=> Defined the dundee-plus release

ocaml/xapi/xapi_xenops.ml
When Xapi starts it synchronises VM power states with Xenopsd (see
Xapi_xenops.on_xapi_restart. For VMs in Xapi's database that it (Xapi)
thinks are not running but actually are running, Xapi will update the
VM's power_state and resident_on fields accordingly.
However, the consoles are not updated (along with anything else that
would normally be driven by the Events_from_xenopsd thread.
An additional Xapi restart will cause these consoles to re-appear but
that's a bit of a niggle.
Xapi should call Xapi_xenops.refresh_vm for such VMs which will inject
a barrier and the event thread will then synchronise all remaining state
into Xapi's database.
=> CA-214717: Xapi_xenops: Call refresh_vm after resetting power state on startup

scripts/OMakefile
=> CA-209071: Remove executable bit from cdrommon@.service

ocaml/idl/datamodel.ml
=> CA-202267: Clarify error message for Pool.join

.travis.yml, Makefile, ocaml/test/suite.ml, ocaml/util/version.mli, ocaml/xapi/db_gc.ml, ocaml/xapi/helpers.ml, ocaml/xapi/xapi_config.ml, ocaml/xapi/xapi_globs.ml
=> version: Lookup platform_version and platform_name in the Inventory

ocaml/xapi/features.ml, ocaml/xapi/features.mli
Add a feature to indicate the availability of this functionality.
(cherry picked from commit faf9340a2e7086406a55707202de9f5d898e59f5)
=> CA-213035: feature-flag for ssl_legacy control switch

ocaml/xapi/features.ml
=> CA-213035: Rename disable_ssl_legacy_switch to restrict_ssl_legacy_switch

ocaml/doc/branding.js, ocaml/doc/xenserver/branding.js
Also removed unreachable breaks.
=> CA-215078: Added branding for the publicly available post-creedence releases.

ocaml/test/OMakefile, ocaml/test/suite.ml, ocaml/test/test_xapi_xenops.ml, ocaml/xapi/features.ml, ocaml/xapi/features.mli, ocaml/xapi/helpers.ml, ocaml/xapi/xapi_vm.ml, ocaml/xapi/xapi_xenops.ml
License is only checked on VM start.
=> CP-18172: Add license checks for nested-virt

ocaml/xapi/network.ml, ocaml/xapi/xapi_pif.ml
=> PAR-164: Validate DNS addresses in PIF.reconfigure_ip(v6)

ocaml/xapi/cli_operations.ml
=> CA-216405: Corrected warning for xe host-declare-dead

ocaml/xapi/create_misc.ml, ocaml/xapi/xapi_globs.ml
=> CP-18010: Fix typo of setting xapi.conf

scripts/xapi-wait-init-complete
=> CA-214080: Log if xapi-wait-init-complete times out

ocaml/client_records/records.ml, ocaml/idl/datamodel.ml, ocaml/xapi/cli_frontend.ml, ocaml/xapi/cli_operations.ml, ocaml/xapi/create_misc.ml, ocaml/xapi/message_forwarding.ml, ocaml/xapi/xapi_globs.ml, ocaml/xapi/xapi_host_helpers.ml, ocaml/xapi/xapi_vm.ml, ocaml/xapi/xapi_vm.mli, ocaml/xapi/xapi_vm_clone.ml, ocaml/xapi/xapi_vm_lifecycle.ml, ocaml/xapi/xapi_vm_memory_constraints.ml, scripts/xapi.conf
Previously submitted and reviewed on xenserver/xen-api#125.
=> Memory setting for control domains

ocaml/xapi/cli_frontend.ml
=> Put back `xe vm-memory-limits-set` :|

ocaml/idl/datamodel.ml, ocaml/xapi/xapi_vm_migrate.ml
=> CA-217301: Block SXM when SR doesn't have VDI_MIRROR capability

ocaml/xapi/storage_migrate.ml
When SXM copies a VDI across, it first tries to find a pair of VDIs with
identical contents on both sender and receiver sides as base copies. And the
content of the pair should also be close enough to the content of source VDI.
This way, we can simply make a clone (VHD child) of the base copy on the
reciver side, which will then become the destination VDI. We then only need to
copy into it the small differences between the source VDI and the base copy on the
sender side.
In some cases, despite the similarity, base copies might have a size different
from the source VDI's. This is usually true when there was a resize operation
in the history of VHD chain. In these cases, the destination VDI (as the result
of direct cloning the base copy on the reciever side) will have a size
initially …
=> CA-218221: make sure SXM destination VDI has the same size as the source

ocaml/xapi/cli_operations.ml, ocaml/xapi/xapi_vm_lifecycle.ml
However, do not allow this via the CLI.
=> CA-216745: Allow the API to destroy control domains other than dom0.

ocaml/xapi/xapi_vm_migrate.ml
VM with raw iSCSI SR cannot live migrate as there are more strict
checks on the supported operations, this fix will check config
item relax_xsm_sr_check, if it's true, check source and destination
SR's uuid, if they are the same, mark it as support live migrate.
Signed-off-by: Huan Xie <huan.xie@citrix.com>
=> CA-219436: Fix raw iscsi sr live-migrate

ocaml/xapi/xapi_vm_migrate.ml
Reverts xapi-project/xen-api#2741
We are currently investigating a problem and can't merge. Will merge it again later.
=> Revert "CA-219436: Fix raw iscsi sr live-migrate"

scripts/xapi.service
Signed-off-by: Jonathan Davies <jonathan.davies@citrix.com>
=> CA-219717: make xapi require xcp-rrdd

scripts/xe-toolstack-restart
=> CA-219714: Fix xe-toolstack-restart for mpathalert

ocaml/xapi/xapi_vm_lifecycle.ml
=> CA-220614: Fix an issue where VM_metrics were assumed to exist

ocaml/xapi/xapi_vm.ml, ocaml/xapi/xapi_vm.mli, ocaml/xapi/xapi_xenops.ml
=> CP-18404: Thread through boolean force operation on VM.start

ocaml/xapi/xapi_pif.ml
=> CA-220514: Protect PIF.scan with a mutex to avoid duplicate PIFs

scripts/0001-Workaround-for-NVIDIA-330.patch
=> Rebase the NVIDIA-330 patch following reindenting

ocaml/xapi/db_gc.ml, ocaml/xapi/xapi_hooks.ml, scripts/10resetvdis
=> CA-215175: Don't ever execute hooks when we only _assume_ failures.

ocaml/xapi/monitor_dbcalls.ml
Avoids polluting logs with backtraces of the form
```
Sep 13 18:31:36 localhost xapi: [error|xrtuk-12-07|41 |monitor_dbcalls D:b4c2c5f55125|backtrace] updating VM_metrics.memory_actual fields and PIFs D:d6c899d0f582 failed with exception Db_exn.Read_missing_uuid("VM", "", "deadbeef-dead-beef-dead-beef00000015")
Sep 13 18:31:36 localhost xapi: [error|xrtuk-12-07|41 |monitor_dbcalls D:b4c2c5f55125|backtrace] Raised Db_exn.Read_missing_uuid("VM", "", "deadbeef-dead-beef-dead-beef00000015")
[...]
Sep 13 18:31:36 localhost xapi: [debug|xrtuk-12-07|41 |monitor_dbcalls D:b4c2c5f55125|monitor_dbcalls] monitor_dbcall_thread would have died from: UUID_INVALID: [ VM; deadbeef-dead-beef-dead-beef00000015 ]; restarting in 30s.
```
and a non-necessary 30s delay in the monitor dbcall thread. …
=> Ignore memory and pif update for transient uuids

xapi.spec.in
=> xapi.spec: Update version number to 1.10.0

Makefile
=> Fix hardcoded version in Makefile after bumping xapi.spec.in

Makefile
=> Makefile: Restore accidentally deleted JQuery definitions

Makefile
=> Makefile: Try updating git archive version to 1.10.0 again

ocaml/xapi/import.ml
Without the patch, the feeder side won't close the pipe's entrance when all the
data has been streamed in. It relies on the consumer to do that eventually. So
in case when the feeder encounters a premature EOF in its own input stream (say
the link breaks), that EOF effect won't be passed through the pipe as a result.
So that the consumer side will be waiting forever for the data yet to come, and
the whole import process will stall.
=> CA-206623: close the input end of the pipe when data feeding is complete

ocaml/xapi/storage_access.ml
Previous behaviour was to wait for a storage backend of the named type
to be registered.
=> CA-182929: Raise an error if the storage backend type is unknown.

ocaml/client_records/records.ml, ocaml/idl/datamodel.ml, ocaml/test/test_common.ml, ocaml/xapi/cli_operations.ml, ocaml/xapi/create_misc.ml, ocaml/xapi/import_xva.ml, ocaml/xapi/xapi_vm.ml, ocaml/xapi/xapi_vm.mli, ocaml/xapi/xapi_vm_clone.ml
=> CP-18521: Added new field reference_label to the VM class.

scripts/examples/python/OMakefile
=> python/OMakefile: Ensure that /opt/xensource/bin exists

scripts/examples/python/XenAPI.py, scripts/examples/python/fixpbds.py, scripts/examples/python/install.py, scripts/examples/python/inventory.py, scripts/examples/python/license.py, scripts/examples/python/permute.py, scripts/examples/python/powercycle.py, scripts/examples/python/shutdown.py, scripts/examples/python/vm_start_async.py, scripts/examples/python/watch-all-event-contents.py, scripts/examples/python/watch-all-events.py, scripts/scalability-tests/event-count.py, scripts/time-vm-boots.py
Also, some changes in the scripts published as part of the SDK, mostly with regards to error handling and compliance with PEP 8.
=> CP-5898: Re-wrote python examples to use event_from instead of event

ocaml/xapi/xapi_pool_update.ml
=> CA-226241:Stop pool_update.introduce if free disk space not enough

ocaml/xapi/xapi_vm_migrate.ml
This commit hooks Network.detach_for_vm() into
VM.atomic_set_resident_on() to ensure that a VM's network is detached
when a VM is migrating away from a host.
=> CA-223505 detach a VM's network (PVS) when migrating away from a host

ocaml/xapi/cli_operations.ml
=> CA-227142: Print update precheck result in CLI

ocaml/xapi/xapi_pool_update.ml
=> CA-228606: Clear installonlypkgs when generate update yum.conf

ocaml/idl/datamodel.ml, scripts/extensions/pool_update.apply, scripts/extensions/pool_update.precheck
1. Parse the error output to give the user friendly message including:
update_precheck_failed_conflict_present
update_precheck_failed_wrong_server_version
update_precheck_failed_prerequisite_missing
2. Set default locale for yum command environment.
=> CA-227716: Refine the error messages.

ocaml/xapi/xapi_pool_patch.ml, ocaml/xapi/xapi_pool_update.ml
Catch the exception and make it an "invalid_update" exception, to notify user.
Signed-off-by: kun ma <kun.ma@citrix.com>
=> CA-227807: Internal Error on uploading unsigned Dundee hotfix

ocaml/idl/datamodel.ml, ocaml/xapi/cli_frontend.ml, ocaml/xapi/cli_operations.ml
=> CA-228035: Export update-resync-host and deprecate refresh_pack_info

scripts/import-update-key
Catch keyfiles that have multiple keys present, terminate when usage
is displayed.
=> CA-229031: improve error handling

scripts/extensions/pool_update.apply, scripts/extensions/pool_update.precheck
Catch the unexpected failure and return detailed error message.
=> CA-228756: Provide more error details for precheck and apply.

ocaml/xapi/message_forwarding.ml
Return a more helpful error message when trying to migrate a VM that is
not resident on any host because it is not running.
The error message previously just complained about an invalid host
object reference, because `Db.VM.get_resident_on` returned `Ref.null`.
The new error message looks like this:
```
$ xe vm-migrate vm=f4af24ed-8c18-6938-9536-4f1e25c56fb6 host=dt14
The specified VM is not currently resident on any host.
vm: f4af24ed-8c18-6938-9536-4f1e25c56fb6 (vm-1)
```
Another option could be to check the `power_state` of the VM instead of
checking whether the host reference returned by `get_resident_on` is null.
=> CA-227285 Better error when migrating non-resident VM

scripts/extensions/pool_update.apply, scripts/extensions/pool_update.precheck
To simplify hotfix dependency handling the 'update-' prefix has been
removed. Use of a group insulates the extension code from any further
changes.
=> CA-229070: switch to @update group

ocaml/idl/api_errors.ml, ocaml/idl/api_messages.ml, ocaml/xapi/helpers.ml, ocaml/xapi/pvs_proxy_control.ml
=> CA-228780: PVS Proxy: Add clear error message for when no PVS servers are defined

ocaml/xapi/xapi_pool_update.ml
=> CA-231357: Don't remove old pool_patch records until after RPU

ocaml/idl/api_messages.ml, ocaml/xapi/pvs_proxy_control.ml
=> CA-230464: Improve error message when not enough memory for PVS cache

ocaml/idl/datamodel.ml, ocaml/test/test_common.ml, ocaml/xapi/xapi_pool_update.ml
pool_patch has this field and updates are still versioned.
=> CA-234358: add version to pool_update

ocaml/client_records/records.ml, ocaml/xapi/cli_operations.ml
=> CA-235986: Add Pool_update.version to the CLI

scripts/extensions/pool_update.apply
=> CA-237415: remove update group from yum by conf file

ocaml/doc/OMakefile, xapi.spec.in
=> Fix docs build

ocaml/xapi/workload_balancing.ml
shutdown/reboot and send an empty email (alarm)
=> CA-236444: WLB consult error when host entry maintenance mode or host

ocaml/OMakefile, ocaml/client_records/OMakefile, ocaml/perftest/OMakefile, ocaml/xapi/cli_operations.ml
This is a leftover from the repo reorganization, the actual source files
have been moved into ocaml/xapi by commit d230450
=> Remove empty client_records directory

ocaml/xapi-consts/OMakefile
=> xapi-consts: ensure install dir exists

ocaml/idl/coversheet.tex, ocaml/idl/xenenterpriseapi-coversheet.tex
=> Update version number on API docs PDF

ocaml/xapi/xapi_event.ml
CVE ID: CVE-2017-5572
Security Bulletin: CTX220112
=> CA-229340: Ensure ref is valid before injecting update

ocaml/idl/datamodel.ml
=> CP-20725: hide `is_default_template` from the public API

ocaml/xapi/cli_operations.ml
Chooses SXM if any SXM-specific arguments were supplied, and then warn
the user about any missing required parameters.
This could help users who accidentally left out any of the required
remote-master, remote-username, and remote-password fields. However,
this commit does not fix the general issue, that we do not detect and
warn the user about unrecognized superfluous command-line parameters at
the moment.
Old behavior:
```
[root@xrtuk-11-27 bin]# xe vm-migrate vm=71b5c809-282d-9191-1839-867e354dea7d host=xrtuk-11-28 vdi:fdsfdsa=fsa
Error: Unknown field 'vdi:fdsfdsa'
```
New behavior:
```
[root@xrtuk-11-27 bin]# xe vm-migrate vm=71b5c809-282d-9191-1839-867e354dea7d host=xrtuk-11-28 vdi:fdsfdsa=fsa
Performing a Storage XenMotion migration. Your VM's VDIs will be migrated with the VM. …
```
=> CA-237993 xe vm-migrate: guess when user wants SXM

ocaml/xapi/xapi_vm_migrate.ml
... as there will be destructive changes since then, which would make a clean
way back difficult.
=> CA-229351: disable task cancelling at certain points of SXM

ocaml/xapi/xapi_message.ml
=> Print xml message

ocaml/xapi/xapi_globs.ml, ocaml/xapi/xapi_vgpu_type.ml
=> Expose MxGPU scheduling slice in VGPU_types

ocaml/xapi/test_data/mxgpu-whitelist-1234, ocaml/xapi/test_data/mxgpu-whitelist-mixed, ocaml/xapi/test_vgpu_type.ml
=> CP-20430: Add VGPU_type unit tests for MxGPU

ocaml/xapi/xapi_xenops.ml
Implement Xapi_xenops.MD.of_mxgpu_vgpu so that MxGPU details
will be passed down to xenopsd.
=> CP-20431: MxGPU: create xenopsd record from DB record

ocaml/xapi/import_raw_vdi.ml
=> CA-229028: Check VDI size is valid in vdi-import

README.markdown
=> Update maintainers list

ocaml/xapi/test_ca121350.ml
=> CP-20287: Updated test to reflect changes in the V6_interface.

ocaml/xapi/storage_impl.ml
The reason that VM shutdown was very slow with many VDIs is because the destroy_sr code becomes slow with a large number of VDIs attached : for every VDI it attempts to lock it, then it checks if it has the datapath being removed. In practice this is unnecessary, and on this basis we can drastically improve the performance. This code makes 2 assumptions, which it verifies - raising an exception if they become untrue.
1)  A datapath is only ever on zero or one VDIs. 
2) The VDIs containing a datapath aren't changed by another thread while the destroy_sr call works.
Assumption 2 means that we don't need to lock every VDI to check if it has the datapath, we can just do the check at the beginning - checking without locking is very cheap, it's the lock contention that causes poor performance. …
=> [CA 203227] VM shutdown is very slow with many VDIs

scripts/OMakefile, scripts/plugins/firewall-port
=> CP-20992: add "firewall-port" script to open/close a tcp port

ocaml/xapi/vgpuops.ml, ocaml/xapi/xapi_pgpu.ml, ocaml/xapi/xapi_vgpu_type.ml
Fix two bugs and revert the default heads change (since XenCenter is now fixed)
Signed-off-by: Bob Ball <bob.ball@citrix.com>
=> Mxgpu bug fixes

ocaml/xe-cli/bash-completion
=> CA-247342: Add auto-complete for sdn-controller CLI commands.

ocaml/xe-cli/bash-completion
=> CA-247372: set correct protocol options for sdn-controller CLI

ocaml/xapi/OMakefile, ocaml/xapi/suite.ml, ocaml/xapi/test_sdn_controller.ml, ocaml/xapi/xapi_sdn_controller.ml
=> CP-21211: Implement unit test for SDN_controller APIs

ocaml/xapi/import_raw_vdi.ml
This reverts commit a2927df1fd0a890269cecaf9cadef32ddf14787e.
=> CA-247694: Revert "CA-229028: Check VDI size is valid in vdi-import"

ocaml/xapi/test_data/mxgpu-whitelist-1234, ocaml/xapi/test_data/mxgpu-whitelist-mixed, ocaml/xapi/test_vgpu_type.ml, ocaml/xapi/xapi_vgpu_type.ml
=> CP-21107: MxGPU: remove `sched` parameter from whitelist file

scripts/Makefile
=> Export variables used by install.sh

ocaml/xapi/db_gc.ml
This prevents us getting into the situation described in CA-247700,
that we had 2 datapaths to the VM for xvda for different VDIs. The
scenario was that a VHD file was removed from the SR somehow (out
of band), which caused the SR-scan to remove it from xapi's db,
which then caused the VBD to be reaped by the GC. A subsequent VBD
was created for the same device and then plugged. Let's not even
have that a possibility - keep the attached VBD around until the
VM is shut down, at which point it will be GC'd.
=> CA-247700: Don't GC VBDs that are currently attached

ocaml/xapi/xapi_vm_lifecycle.ml
Signed-off-by: sharad yadav <sharad.yadav@citrix.com>
=> CA-247695: VM part of snapshot schedule can't be converted into template

scripts/extensions/pool_update.precheck
Forward port of some fixes that happened in the late XS 7.1 timeframe.
=> CA-243824 for 1.30-lcm

scripts/extensions/pool_update.precheck
Forward port of a fix done late in the XS 7.1 timeframe.
=> CA-243824 for master

ocaml/xapi/cli_operations.ml
=> CA-248775: Set the name of VDIs associated with patches/updates

ocaml/.merlin
=> Update merlin file

ocaml/xapi/xapi_xenops.ml
Cherry-picks of commits on master:
6e705d370d0347fe46c09e2cb70c1a86fc2a3b7c
3b7c96b8996c8d11066fd4e7ea88df41181e2879
=> XOP-830 for 1.30-lcm branch

ocaml/idl/datamodel.ml, ocaml/xapi/xapi_globs.ml
=> Bumped API version to 2.7.

ocaml/idl/ocaml_backend/gen_db_actions.ml, ocaml/xapi/import.ml, ocaml/xapi/importexport.ml, ocaml/xapi/xapi_pool.ml
=> CA-249786: removed build number comparison from pool join rules.

ocaml/xapi/xapi_vm_migrate.ml
=> CA-250143: Stat the mirror _before_ removing it

scripts/plugins/firewall-port
=> CA-250376: Add protocol option in firewall-port script

scripts/Makefile, scripts/mail-alarm, scripts/mail-languages/en-US.json, scripts/mail-languages/ja-JP.json, scripts/mail-languages/zh-CN.json
1. Add 'mail-languages' processing in mail-alarm script
2. Introduce 3 JSON files for mail language resource
=> CP-19454: Support Chinese and Janpanese mail alert 

scripts/mail-languages/ja-JP.json, scripts/mail-languages/zh-CN.json
Updated 2 mail language pack files:
zh-CN.json
ja-JP.json
=> CP-19454: Replace zh-CN & ja-JP language pack with translated file

ocaml/xapi/xapi_pool_update.ml
=> CA-251251: Use /var/update/applied/uuid mtime for patch apply time

ocaml/idl/datamodel.ml, ocaml/idl/datamodel_types.ml, ocaml/xapi/OMakefile, ocaml/xapi/test_common.ml, ocaml/xapi/xapi_gpumon.ml, ocaml/xapi/xapi_gpumon.mli, ocaml/xapi/xapi_pci.mli, ocaml/xapi/xapi_pgpu.ml
A new field in the datamodel, and code to populate it.
=> CP-20679: PGPU.compatibility metadata

ocaml/idl/datamodel.ml, ocaml/xapi-consts/api_errors.ml, ocaml/xapi/xapi_fist.ml, ocaml/xapi/xapi_gpumon.ml, ocaml/xapi/xapi_gpumon.mli, ocaml/xapi/xapi_vm_lifecycle.ml, ocaml/xapi/xapi_vm_migrate.ml
Preliminary implementation, do not merge.
There are a few things I am not convinced of and I would like to have your opinion, I will add inline comments.
=> CP-20681: Implement vGPU migratability checks for in-pool migration

scripts/mail-alarm
=> CP-19454: Fix syntax error in mail-alarm

ocaml/xapi/xapi_pool.ml
If joining Host management vlan bridge name doesn't match with
Pool master management bridge name then we need to create
the new vlan bridge same as Pool master.
For example:
If joining Host management is on vlan bridge xapi1 and
pool management vlan bridge is on xapi0.
Then joining host xapi1 management bridge need to be destroyed
and xapi0 bridge need to be created along with updating the inventory.
=> CP-22201: Fix inventory during Pool.join on vlan network.

ocaml/xapi/record_util.ml
Commit 363d622 removed the last usages of this function.
=> Record_util: Remove unused string_to_vdi_type fn

ocaml/xapi/suite.ml, ocaml/xapi/test_vlan.ml
=> CP-22202: Add unit tests for VLANs

ocaml/xapi/xapi_gpumon.ml, ocaml/xapi/xapi_gpumon.mli, ocaml/xapi/xapi_pgpu_helpers.ml, ocaml/xapi/xapi_pgpu_helpers.mli, ocaml/xapi/xapi_vm_migrate.ml
Implement changes to allow cross pool vgpu-pgpu compatibilty checks.
Also includes a fix for CA-254415.
=> CP-20682: Implement vGPU migration checks for cross-pool migration

ocaml/xapi/import.ml
We do this in the VGPU import handler when the `live` flag is set. The VM
import handler is called on the receiving host of a cross-pool migration, by
both VM.assert_can_migrate (as a dry-run) and VM.migrate_send (for real).
=> CP-20682: Assert free vGPU capacity on receiving host for cross-pool SXM

.travis-opam-coverage.sh
By adding a "sudo apt-get update" step.
=> Travis: fix OPAM coverage job

ocaml/xapi/xapi_vdi.ml, ocaml/xapi/xapi_vdi.mli
This is in preparation for CP-22009: changes needed in this area
to support changed block tracking.
=> Refactor Xapi_vdi.check_operation_error

ocaml/xapi/xapi_ha.ml, ocaml/xapi/xapi_ha.mli
This mli file is useful, as it will hide quite a few functions in the .ml file.
=> Add an .mli interface for xapi_ha.ml

ocaml/xapi/helpers.ml, ocaml/xapi/xapi.ml, ocaml/xapi/xapi_mgmt_iface.ml
\+ add a "warning" comment to the code about the issue to avoid future bugs
=> CA-242706 backport for Honolulu

ocaml/auth/extauth_plugin_ADpbis.ml, ocaml/idl/api_errors.ml, ocaml/idl/datamodel.ml, ocaml/test/OMakefile, ocaml/test/suite.ml, ocaml/test/test_extauth_plugin_ADpbis.ml, ocaml/xapi/create_misc.ml, ocaml/xapi/monitor_dbcalls.ml, ocaml/xapi/monitor_dbcalls_cache.ml, ocaml/xapi/monitor_pvs_proxy.ml, ocaml/xapi/storage_migrate.ml, ocaml/xapi/xapi_globs.ml, ocaml/xapi/xapi_pool.ml, ocaml/xapi/xapi_pool_update.ml, ocaml/xapi/xapi_vm_migrate.ml
This includes:
* CA-252876
* CA-250757
* CA-251251
* CA-247399
* CA-247452
* CA-245389
=> Backport fixes for UPD-64 hotfix

scripts/mail-alarm, scripts/mail-languages/en-US.json, scripts/mail-languages/ja-JP.json, scripts/mail-languages/zh-CN.json
=> CA-253935: Add sr_io_throughput alert

.travis-xenserver-build-env.sh
Correct the syntax used for string comparison.
=> build-env Travis job: fix doc uploading

deploy.sh
Update the path of the generated json files that we copy out of the container.
=> Fix documentation uploading

ocaml/xapi/helpers.ml, ocaml/xapi/xapi.ml, ocaml/xapi/xapi_mgmt_iface.ml
I think we'll need to rebase the `1.14-ppx` branch on top of `1.14-lcm` after this is merged.
=> Backport CA-242706

scripts/mail-alarm, scripts/test_mail-alarm.py
=> CP-22525: Add test_mail-alarm.py

scripts/extensions/pool_update.precheck
Parse and handle the errorcode and values from the output.
=> CA-255509: Failures in precheck scripts are not reported correctly.

scripts/Makefile, scripts/mail-alarm, scripts/mail-languages/en-US.json, scripts/mail-languages/ja-JP.json, scripts/mail-languages/zh-CN.json, scripts/test_mail-alarm.py
Dev completed. Merging to master.
=> Feature "REQ-378: Support Chinese Language E-mail Performance Alerts"

ocaml/idl/api_errors.ml, ocaml/idl/datamodel.ml, ocaml/xapi/create_misc.ml, ocaml/xapi/xapi_globs.ml, ocaml/xapi/xapi_pool.ml
This reverts commit d6530ca0809479b8a27216a9aefac35827dcbacd that has been removed from the hotfix.
=> Revert "New pool join rules to reflect ely changes in the updates."

ocaml/idl/datamodel.ml, ocaml/xapi-consts/api_errors.ml, ocaml/xapi/cli_frontend.ml, ocaml/xapi/cli_operations.ml, ocaml/xapi/debug_populate.ml, ocaml/xapi/message_forwarding.ml, ocaml/xapi/record_util.ml, ocaml/xapi/records.ml, ocaml/xapi/sm.ml, ocaml/xapi/smint.ml, ocaml/xapi/static_vdis.ml, ocaml/xapi/storage_access.ml, ocaml/xapi/storage_impl.ml, ocaml/xapi/storage_impl_test.ml, ocaml/xapi/storage_mux.ml, ocaml/xapi/test_common.ml, ocaml/xapi/test_sm_features.ml, ocaml/xapi/xapi_ha.ml, ocaml/xapi/xapi_host.ml, ocaml/xapi/xapi_pool.ml, ocaml/xapi/xapi_sr.ml, ocaml/xapi/xapi_sr_operations.ml, ocaml/xapi/xapi_vdi.ml, ocaml/xapi/xapi_vdi.mli, ocaml/xapi/xapi_vm.ml, ocaml/xapi/xapi_vm_lifecycle.ml, ocaml/xapi/xapi_vm_migrate.ml, ocaml/xapi/xapi_vm_snapshot.ml
This PR depends on https://github.com/xapi-project/xcp-idl/pull/162
=> [merge xcp-idl#162 first] Merge first part of CBT feature branch into master

ocaml/xapi/test_common.ml, ocaml/xapi/test_vdi_allowed_operations.ml
=> Test_vdi_allowed_operations: add CBT tests

scripts/examples/python/XenAPI.py
Changed syntax to work with multiple versions.
Leveraged six.
=> support python 3 too

ocaml/xe-cli/newcli.ml, ocaml/xe-cli/options.ml
Please let me know if I removed something that's needed.
=> Remove dead code from ocaml/xe-cli

ocaml/idl/datamodel.ml
This commit corrects some errors of (v) GPU related.
Signed-off-by:Min Li <min.li1@citrix.com>
=> CA-244865: Datamodel: errors from copy/paste in (v)GPU-related descriptions

Makefile
=> Install.sh does not work with whole directories.

ocaml/xapi/sm.ml, ocaml/xapi/sm_exec.ml, ocaml/xapi/sm_fs_ops.ml, ocaml/xapi/sm_fs_ops.mli, ocaml/xapi/smint.ml
Please let me know if I removed something that's needed.
=> Remove dead code from ocaml/xapi/sm*

ocaml/doc/wire-protocol.md, ocaml/idl/markdown_backend.ml
=> Markdown: tweak representation of session refs

ocaml/xapi/import_raw_vdi.ml, ocaml/xapi/xapi_http.ml
CA-226886: VDI import: handle exn if SR is unavailable for any host.
This commit adds proper handling in VDI import for exceptions raised
when the SR is not accessible by any host.  For example, this can
happen during an update-upload operation when trying to use the
default SR but it was down.
The exception handler marks the relevant task as failed, and returns
an appropriate http error code to the client.
=> CA-226886: VDI import: handle exn if SR is unavailable for any host

ocaml/xapi/cli_frontend.ml, ocaml/xapi/cli_operations.ml, ocaml/xapi/import_raw_vdi.ml, ocaml/xapi/xapi_http.ml
I've run `make test` on `release/honolulu/staging` and it succeeded. Relevant issues are CA-226886, CA-253489, CA-226886. MRs: CA-259594, CA-259595.
=> Backport CA-253489 and CA-226886 to Honolulu

ocaml/doc/doc-convert.sh, ocaml/doc/templates/cover.mustache
=> CP-22381: use png instead of pdf to avoid conversion from eps.

ocaml/xapi/test_vdi_cbt.ml
=> Test that VDI.set_metadata_of_pool doesn't accept cbt_metadata VDI

ocaml/xapi/test_vdi_cbt.ml
=> VDI.snapshot,clone: test that VDI.cbt_enabled is correctly set

ocaml/client_records/records.ml, ocaml/idl/datamodel.ml, ocaml/xapi/message_forwarding.ml, ocaml/xapi/xapi_pool.ml, ocaml/xapi/xapi_pool_update.ml
With an ugly, dirty hack. I feel bad.
=> CA-260352: Fix upgrade from 1.14-ppx to 1.30

ocaml/xapi/nm.ml
=> CP-23093: Fill new field 'igmp_snooping' with default value

ocaml/xapi-types/features.ml, ocaml/xapi-types/features.mli
=> CP-23781: Add IGMP Snooping feature flag.

ocaml/xapi/quicktest.ml, ocaml/xapi/quicktest_common.ml, ocaml/xapi/quicktest_import_raw_vdi.ml, ocaml/xapi/quicktest_vdi_copy.ml
This is a quicktest for import raw vdi when no host is available for the SR.
=> Test CA226886：Quicktest for import_raw_vdi when no host is available for the SR.

ocaml/idl/datamodel.ml, ocaml/xapi/dbsync_master.ml, ocaml/xapi/message_forwarding.ml, ocaml/xapi/nm.ml, ocaml/xapi/records.ml, ocaml/xapi/test_common.ml, ocaml/xapi/xapi_pool.ml, ocaml/xapi/xapi_pool.mli
Updated according to review comments.
=> CP-23602: Add xapi API to toggle IGMP snooping

ocaml/idl/datamodel.ml, ocaml/xapi-consts/api_errors.ml, ocaml/xapi/cli_frontend.ml, ocaml/xapi/cli_operations.ml, ocaml/xapi/message_forwarding.ml, ocaml/xapi/ounit_comparators.ml, ocaml/xapi/record_util.ml, ocaml/xapi/sm.ml, ocaml/xapi/storage_access.ml, ocaml/xapi/storage_impl.ml, ocaml/xapi/storage_impl_test.ml, ocaml/xapi/storage_mux.ml, ocaml/xapi/test_common.ml, ocaml/xapi/test_event.ml, ocaml/xapi/test_pr1510.ml, ocaml/xapi/test_vdi_cbt.ml, ocaml/xapi/xapi_sr_operations.ml, ocaml/xapi/xapi_vdi.ml, ocaml/xapi/xapi_vdi.mli
Merge after https://github.com/xapi-project/xcp-idl/pull/168
=> Merge feature/CBT branch into master

ocaml/xapi/cli_frontend.ml, ocaml/xapi/cli_operations.ml
=> Add xe vdi-get-nbd-info CLI command

ocaml/xapi/api_server.ml
=> CA-263064: Stop logging the body of jsonrpc requests.

ocaml/idl/datamodel.ml
=> CP-23253: Amending some cbt command descriptions

ocaml/idl/datamodel.ml, ocaml/xapi/records.ml, ocaml/xapi/xapi_message.ml
=> CP-24019: Enabling messages on VDI objects

ocaml/xapi/suite.ml, ocaml/xapi/test_vm.ml
=> CP-24081: Add unit tests for VM.set_bios_strings

.travis-opam-coverage.sh
=> Fix coverage Travis build and update to OCaml 4.04.2

ocaml/idl/datamodel.ml, ocaml/xapi/message_forwarding.ml, ocaml/xapi/xapi_vdi.ml, ocaml/xapi/xapi_vdi.mli
=> CP-24459: Adding hidden VDI.set_cbt_enabled setter

ocaml/xapi/xapi.ml
An interim commit, this uses systemctl to start the xapi-nbd service
unconditionally at the end of the xapi startup sequence.
This means that on first boot, xapi-nbd is started only after the
autogenerated TLS certificate has been created.
=> CA-265469: start xapi-nbd from xapi

ocaml/xapi-consts/api_messages.ml
=> CP-24536: Add support for CBT-specific messages to xapi and SM

ocaml/idl/datamodel.ml, ocaml/xapi-consts/api_errors.ml, ocaml/xapi/api_server.ml, ocaml/xapi/cli_frontend.ml, ocaml/xapi/cli_operations.ml, ocaml/xapi/message_forwarding.ml, ocaml/xapi/record_util.ml, ocaml/xapi/records.ml, ocaml/xapi/xapi_pusb.ml, ocaml/xapi/xapi_usb_group.ml, ocaml/xapi/xapi_usb_group.mli, ocaml/xapi/xapi_vusb.ml, ocaml/xapi/xapi_vusb.mli
1. Add PUSB USB_group VUSB module
2. Add create/destroy messages to USB_group and VUSB
3. PUSB scan and VUSB unplug will add in another commit
=> CP-24409: Add PUSB USB_group VUSB

ocaml/xapi/import.ml
Importing VMs during RPU sometimes will meet problems, this patch
disables such opertaion when rolling_poll_upgrade_in_progress
Signed-off-by: Huan Xie <huan.xie@citrix.com>
=> CA-88550: Block VM.import during RPU

ocaml/xapi-types/features.ml, ocaml/xapi-types/features.mli
=> CP-24153: Add USB passthrough feature flag.

ocaml/xapi/xapi_pusb.ml
=> CP-24409: Remove mutex on pusb create

ocaml/xapi/message_forwarding.ml
Porting the changes recommended in https://github.com/xapi-project/xen-api/pull/3231 to our branch.
=> VDI.set_cbt_enabled: assert we have an SM session

ocaml/xapi-types/features.ml, ocaml/xapi-types/features.mli, ocaml/xapi/xapi_vdi.ml
=> CP-22016: Add feature flag checks to CBT XenAPI functions

Makefile
=> Makefile: run tests without buffering

ocaml/idl/datamodel.ml, ocaml/xapi/message_forwarding.ml, ocaml/xapi/xapi_vdi.ml, ocaml/xapi/xapi_vdi.mli
=> Add feature/CBT change required by SM: CP-24459: Adding hidden VDI.set_cbt_enabled setter

_oasis, ocaml/xapi/suite.ml, ocaml/xapi/test_pusb.ml, ocaml/xapi/xapi.ml, ocaml/xapi/xapi_pusb.ml, ocaml/xapi/xapi_pusb_helpers.ml, opam
1. Add yojson lib, as pusb scan will get json format data by call usb_scan script
2. Add pusb scan function
a. scan will be called when xapi start or uevent.
=> CP-24611:  Add pusb scan function

ocaml/xapi/storage_migrate.ml
=> Fix storage migration log message: list only similar VDIs instead of all the local ones

ocaml/idl/datamodel.ml
=> CA-266914: Remove product name from error message

ocaml/xapi/test_valid_ref_list.ml
Signed-off-by: Iglói Gábor <gabor.igloi@citrix.com>
=> Test_valid_ref_list: test new filter function

ocaml/xapi/ounit_comparators.ml, ocaml/xapi/test_vdi_cbt.ml, ocaml/xapi/xapi_vdi.ml, ocaml/xapi/xapi_vdi.mli
I've successfully compiled this and the tests passed. The Travis build isn't expected to pass, because we've been having build issues recently.
=> Re-enable unit tests for VDI.get_nbd_info

ocaml/xapi/quicktest_cbt.ml
Tests are now declared in the toplevel, so only test execution logic is local to a function.
=> CP-22019: Move tests to toplevel

scripts/Makefile, scripts/usb-policy.conf, scripts/usb_scan.py
USB device scanner to get USB devices info. Policy checking is performed
against file: /etc/xensource/usb-policy.conf
Signed-off-by: Xin(Talons) Li <xin.li@citrix.com>
=> CP-24615: script to get info of all USB device

ocaml/xapi/xapi_vm_lifecycle.ml
=> CA-269596: Restrict vm checkpoint operation

ocaml/xapi/xapi_vm_helpers.ml
=> CA-269657: Detach VUSB before setting VM a template

ocaml/idl/datamodel.ml
=> CA-269677: Restrict USB related operations to role pool_admin

ocaml/xapi/vm_platform.ml, ocaml/xapi/xapi_vm.ml
=> CA-269586: Add device-model check when vm start

ocaml/xapi/xapi_vusb.ml
The mutex is to protect the pre-checks, which limit the number of VUSBs per VM,
and per USB group, in the case that multiple VSUB.create calls come in. The
critical section must start before the `Db.VM.get_VUSBs` call for this to be
thread safe.
Also note that the final couple of lines of the function are part of the second
case in the `ha_restart_priority` match, even though the indentation suggests
otherwise. This is actually (luckily) alright, because the first case raises an
exception.
=> Fix mutex in VUSB.create

ocaml/xapi/xapi_pusb.ml
1. No matter vusbs is [] nor not, we still need to
continue executing the set passthrough code.
2. List.hd vusbs is no need when match [vusb]
=> CA-270405: Can't set USB pass-through to disable

ocaml/xapi/xapi_vgpu_type.ml
MxGPU and passthrough cannot be used on the same host.
Workaround is that AMD will define an MxGPU.1 device which is
equivalent to passthrough of the whole PF, using the MxGPU
architecture.
=> CA-265413:  Disable passthrough when using MxGPU

ocaml/xapi/xapi_pool.ml
=> CA-271052: pool join fixup

ocaml/xapi/xapi_mgmt_iface.ml, scripts/init.d-xapissl, scripts/xapi.conf
Signed-off-by: Yarsin He <yarsin.he@citrix.com>
=> CA-265117: xapi.conf server_cert_path not respected

ocaml/xapi/cli_operations.ml
Signed-off-by: Yarsin He <yarsin.he@citrix.com>
=> CA-273239: Template-xxx CLI commands are allowed on non-template VMs

ocaml/idl/datamodel.ml, ocaml/idl/datamodel_types.ml, ocaml/xapi/xapi_globs.ml
=> Bumped the API version to 2.8.

ocaml/idl/datamodel.ml, ocaml/xapi/records.ml, ocaml/xapi/test_common.ml, ocaml/xapi/xapi_gpumon.ml, ocaml/xapi/xapi_gpumon.mli, ocaml/xapi/xapi_vgpu.ml, ocaml/xapi/xapi_vm.ml, ocaml/xapi/xapi_vm_helpers.ml, ocaml/xapi/xapi_xenops.ml
This is work in progress to add support for VM.suspend/VM.resume with vGPUs that support migration. Do not merge.
=> WIP CP-24185 - support for VM.suspend/resume and vGPUs

ocaml/database/db_cache_types.ml, ocaml/database/db_exn.ml, ocaml/database/string_marshall_helper.ml, ocaml/xapi/test_db_lowlevel.ml, ocaml/xapi/test_vdi_allowed_operations.ml, ocaml/xapi/test_vdi_cbt.ml, ocaml/xapi/test_xapi_vbd_helpers.ml
Also fix other tests that already rely on this working
=> Add a fix and test for setting an empty string as a key in a map

ocaml/cdrommon/cdrommon.ml
=> cdrommon: missing stdext fix

ocaml/pci/bindings/ffi_bindings.ml, ocaml/pci/examples/lspci.ml, ocaml/pci/lib/pci.mli, ocaml/pci/lib_test/test_pci.ml, ocaml/xapi/xapi_pci_helpers.ml, ocaml/xapi/xapi_vgpu_type.ml
This does not fix the issue overall but should solve some of the occurrences
=> CA-266936: Mitigate potential segfaults by using string_opt on ctypes bindings

ocaml/xapi-types/features.ml, ocaml/xapi-types/features.mli
=> CP-23644: Add network sriov as a feature

ocaml/xapi/xapi_vm_migrate.ml
During VM migration, a VM may shut down. When this happens, the VM's
vGPUs get released immediately. This needs to be detected before
infer_vgpu_map() is called as it relies on vGPUs being assigned.
This commit moves the call to infer_vgpu_map into the try-catch block
that deals with edge cases like this. Before infer_vgpu_map is called we
check that the VM is live and hence has its vGPUs still assigned. To
avoid a data race, the liveness check is done only after no more
events from xenopsd are accepted.
=> CA-271406 don't call infer_vgpu_map when VM is not live

ocaml/xapi/xapi_pgpu.ml
On startup, xapi updates its GPU records. This includes pGPU
compatibility meta data. Obtaining this data might fail if the pGPU is
used in pass-trough mode at the time. In the past this lead to empty
meta data overwriting the existing meta data. Since a restart of xapi
can happen for many reasons, this led to losing pGPU meta data which was
needed later.
This commit prevents existing pGPU meta data being overwritten if no
meta data can be obtained.
=> CA-279161 if unavailable, don't update pGPU compat data

ocaml/xapi/xapi_vm_migrate.ml
During VM migration, a VM may shut down. When this happens, the VM's
vGPUs get released immediately.  This needs to be detected before or
while infer_vgpu_map() is called as it relies on vGPUs being assigned.
Otherwise we see an invalid handle to a PGPU.
This commit moves the call to infer_vgpu_map into the try-catch block
that deals with edge cases like this. If the VM is no longer live during
migration, we receive an new exception and deal with this.
=> CA-271406 infer_vgpu_map: VM might not be live

ocaml/idl/datamodel.ml, ocaml/xapi/test_common.ml, ocaml/xapi/xapi_pci.ml, ocaml/xapi/xapi_pci_helpers.ml
=> CP-26302: Add driver_name in PCI object

ocaml/idl/datamodel.ml
=> CA-279502: Set the correct release for the is_default_template field

.travis-opam-coverage.sh, Makefile, configure.ml, ocaml/auth/jbuild, ocaml/cdrommon/jbuild, ocaml/database/jbuild, ocaml/db_process/jbuild, ocaml/doc/jbuild, ocaml/events/jbuild, ocaml/graph/jbuild, ocaml/idl/jbuild, ocaml/idl/json_backend/jbuild, ocaml/idl/ocaml_backend/jbuild, ocaml/license/jbuild, ocaml/mpathalert/jbuild, ocaml/perftest/jbuild, ocaml/ptoken/jbuild, ocaml/rfb/jbuild, ocaml/util/jbuild, ocaml/vncproxy/jbuild, ocaml/xapi-cli-protocol/jbuild, ocaml/xapi-client/jbuild, ocaml/xapi-consts/jbuild, ocaml/xapi-types/jbuild, ocaml/xapi/jbuild, ocaml/xapi/xapi.ml, ocaml/xe-cli/jbuild, ocaml/xsh/jbuild
Depends on https://github.com/xapi-project/xcp-idl/pull/179
=> Xapi coverage

ocaml/xapi/jbuild, xapi.opam
This should fix the travis build.
=> Added explicit dependency to message-switch-unix.

ocaml/xapi/alcotest_comparators.ml, ocaml/xapi/suite.ml, ocaml/xapi/suite_alcotest.ml, ocaml/xapi/test_vdi_allowed_operations.ml
=> Port Test_vdi_allowed_operations to alcotest

ocaml/xapi/xapi_xenops.ml
This temporary fix will be overwritten when merging Ming's change
=> Temporary fix to make xapi a sucessful build

ocaml/idl/datamodel.ml, ocaml/xapi/create_misc.ml, ocaml/xapi/dbsync_master.ml, ocaml/xapi/xapi_vm.ml, ocaml/xapi/xapi_vm_clone.ml, ocaml/xapi/xapi_vm_helpers.ml
These fields are for future use and left entirely unused for the moment.
=> Introduce fields VM.domain_type and VM_metrics.current_domain_type

ocaml/xapi/nm.ml
=> Fix indentation

ocaml/idl/datamodel.ml, ocaml/xapi/xapi_vm_migrate.ml, ocaml/xapi/xapi_xenops.ml
=> CA-283632/XOP-919: Add VM reference to VM_FAILED_SHUTDOWN_ACK error

ocaml/idl/datamodel.ml, ocaml/xapi/xapi_vmss.ml
Move all objects into their own modules. Next step: move them into their own files. I'm submitting this incrementally as otherwise the rebasing will be very painful.
=> Reorg datamodel a little

scripts/xe-edit-bootloader
Changes in #3448 look good.  I also updated the file list to account for grub2.  
Signed-off-by: Aaron Davis <aaron.davis@rackspace.com>
=> Includes changes from #3448 updated grub file list to account for grub2.

ocaml/xapi/smint.ml, ocaml/xapi/test_sm_features.ml
=> Add SR Multipath capability

ocaml/xapi/alcotest_comparators.ml, ocaml/xapi/suite.ml, ocaml/xapi/suite_alcotest.ml, ocaml/xapi/test_vdi_cbt.ml
=> Convert Test_vdi_cbt to Alcotest

ocaml/xapi/alcotest_comparators.ml, ocaml/xapi/suite.ml, ocaml/xapi/suite_alcotest.ml, ocaml/xapi/test_db_lowlevel.ml
=> Convert Test_db_lowlevel to Alcotest

ocaml/xapi/suite.ml, ocaml/xapi/suite_alcotest.ml, ocaml/xapi/test_vlan.ml
=> Convert Test_vlan to alcotest

ocaml/xapi/helpers.ml, ocaml/xapi/xapi_udhcpd.ml
=> Remove redundant (|>) pipe definitions

ocaml/xapi/xapi_host.ml
This depends upon https://github.com/xapi-project/xcp-idl/pull/204 being merged
=> CA-283754: treat potential internal errors from V6

ocaml/xapi/stream_vdi.ml
It will be removed in the next version of the library and it is a small and understandable amount of code.
Also... we were not using it for multicast so we could simplify it a bit.
=> Tar_unix: replace Tar_unix.Archive.multicast_n_string with its implementation

ocaml/xapi/xapi_fist.ml, ocaml/xapi/xapi_pif_helpers.ml
=> Remove vlan-on-vlan support

README.markdown
=> Typo in readme

ocaml/xapi/import.ml
The new `VM.domain_type` field need to be defined (derived from the
`HVM_boot_policy`) as soon as possible upon importing the VM record, since lots
of functionality now depends on it. Import pre-checks were failing because this
happened too late.
=> CA-282112: Fix domain_type setting during SXM from older releases

ocaml/xapi/quicktest_storage.ml
The SR.probe quicktest does not clean up its state changes when it
fails, it leaves some previously plugged PBDs unplugged, therefore it
interferes with the next quicktest SR selection which uses SRs with
plugged PBDs.
=> CA-285281: Make SR.probe quicktest idempotent

ocaml/tests/suite_alcotest.ml, ocaml/tests/test_client.ml
=> Add Test_client using Client module to test auto-generated layers

ocaml/tests/alcotest_comparators.ml
There is no need to write a printer by hand because we get a better one
for free generated rpclib.
=> Simplify nbd_info Alcotest comparator

.travis-opam-coverage.sh
=> Move to xapi-travis-scripts coverage script

ocaml/tests/test_guest_agent.ml, ocaml/xapi/xapi_guest_agent.ml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xapi-project/xen-api/3498)
=>  CP-23788: VM guest metrics can read SR-IOV VF IPs 

ocaml/xapi/vm_evacuation.ml, ocaml/xapi/xapi_vm_lifecycle.ml
=> CP-27272: Restore lost codes in merge commit

ocaml/quicktest/quicktest_storage.ml, ocaml/xapi/xapi_sr.ml
The quicktests passed after I've commented out the code checking for the probe capability - we still have to add that.
=> Fix SR.probe quicktest

ocaml/xapi/xapi_vm_lifecycle.ml
vGPU migration is now enabled by default - remove all checks.
=> CP-27433 remove checks for vgpu_migration_enabled()

ocaml/xapi/xapi_xenops.ml
This error is caused by calling unplug vusb which will call usb_reset to
remove device from cgroup allow list. The root cause is that we didn't
filter vusb when creating metadata according vusb field `currently_attached`.
So if we create vusb by CLI when vm is running and then shutdown the vm, this
error will be raised by the usb_reset.py with "No such file or directory",
as the vusb is not plugged to vm and then the file is not created.
So we need to filter the vusb if currently_attached is false, it
shouldn't be pushed to xenopsd.
=> CA-285511: TCUSBPassBetweenVMWithinPool: No route to host

ocaml/xapi/xapi_network_sriov_helpers.ml
This issue was found when VM has VLAN SR-IOV network,then the PIFs of the network were not SR-IOV logical PIF. To avoid internal erros raised,change the way for getting SR-IOV object from any type of PIFs by
using `get_pif_topo`.
=> CP-27446: Group hosts failed as no sr-iov found when VM has VLAN SR-IOV network

ocaml/xapi/xapi_host.ml
When synchronising PIF currently_attached, should ignore VLAN PIF on SR-IOV and
SR-IOV logical PIF because they don't have real vswitch bridge, so that the
bridge existance does not indicate the connection status of the PIF.
=> CA-286292: VLAN PIF on SR-IOV status is incorrect after restarting toolstack

ocaml/xapi/xapi_pif.ml
Two commits in this PR:
1. Bring up bond when bring up SR-IOV physical
2. Bring down SR-IOV physical PIF when bring down bond
=> CA-286135: Bring up bond when bring up SR-IOV physical and vice versa

scripts/usb_reset.py
return the uid/gid of device file when attaching device, these ids
should be restored later.
=> CP-27452: return uid/gid of device file

ocaml/tests/suite.ml, ocaml/tests/suite_alcotest.ml, ocaml/tests/test_event.ml
=> Port Test_event to Alcotest

ocaml/quicktest/quicktest.ml
=> Remove deleted quicktests from all_tests list

ocaml/idl/datamodel.ml, ocaml/idl/markdown_backend.ml
Extended documentation in the datamodel and special cased the class in the code generating the API reference markdown. Note that this PR does not conclude the ticket as the html reference generator has not been fixed yet.
=> XSI-6: Event class documentation enhancements.

ocaml/xapi/xapi_sr.ml
Remove the clustering lock in SR.probe - now the plugin no longer tries
to mount the fs, so it's not needed any more.
=> CA-288347: Do not take clustering lock in SR.probe

ocaml/xapi/xapi_pool.ml
=> CA-284520: Adding pool pre-check for clustering enabled

ocaml/tests/test_cluster.ml
`Cluster.create` creates a cluster ref and a cluster_host ref. This PR ensures those refs are destroyed in the event of a failed `Cluster.create`. and adds a test to check this.
=> CA-273986: Test Cluster.create cleans up refs when it fails

ocaml/xapi/xapi_xenops.ml
1. Remove redundent log
2. Add log for VUSB
=> CA-289620: Remove redundant log of events_watch

ocaml/xapi/xapi_pool_update.ml
There is a race between post update-apply cleanup and db_gc.
To avoid the race condition, destroy the connector (Host_patch) before
destroying Pool_patch objects and do not call db_gc in post update-apply cleanup
procedure.
=> CA-289319: Kolkata Update application failure: HANDLE_INVALID

Makefile, deploy.sh, ocaml/idl/datamodel.ml, ocaml/idl/json_backend/gen_json.ml, ocaml/idl/markdown_backend.ml
Note I have not corrected jsapi.ml because this is only used by the SDK and I'm planning to deprecate it.
=> XSI-6: Corrected and completed event class documentation enhancements. 

ocaml/quicktest/quicktest_common.ml, ocaml/quicktest/quicktest_http.ml, ocaml/quicktest/quicktest_import_export.ml, ocaml/quicktest/quicktest_vdi.ml, ocaml/quicktest/storage_test.ml
And reorganize the helpers a bit.
This test has already found an issue, CA-290241, and it's passing on local ext and NFS.
=> Quicktest: check snapshot VDI fields

ocaml/database/db_remote_cache_access_v1.ml, ocaml/database/redo_log.ml, ocaml/xapi-types/ref.ml
This is not enough to compile xapi with safe-strings, but it's a start
=> xapi-database, xapi-types: make safe-string compliant

ocaml/quicktest/quicktest_vdi_ops_data_integrity.ml
=> CA-290450: quicktest_vdi_ops_data_integrity: test large VDIs too

ocaml/xapi/xapi_globs.ml, ocaml/xapi/xha_scripts.ml
=> CA-290526: Update location for cluster stack supported SRs file

scripts/nbd_client_manager.py
We wait up to 5 minutes when all the 128 NBD devices are in use.
=> nbd_client_manager: increase number of /dev/nbds and wait for a free one

ocaml/quicktest/quicktest_sr.ml, ocaml/quicktest/storage_test.ml, ocaml/quicktest/storage_test.mli
=> CA-272147: add quicktest for SR.set_name_label & description

ocaml/quicktest/quicktest_vdi.ml, ocaml/quicktest/quicktest_vdi_ops_data_integrity.ml, ocaml/quicktest/storage_test.ml, ocaml/quicktest/storage_test.mli
=> CA-290466: Add quicktest to test parallel VDI dom0 attach limit

ocaml/idl/datamodel_cluster.ml, ocaml/idl/datamodel_cluster_host.ml, ocaml/idl/datamodel_errors.ml
=> CP-28227: Add API errors to clustering datamodel

ocaml/xapi/storage_access.ml
Previously we only created SM objects for those SMAPIv2 drivers that had
an SR of that type. This is inconsistent with the SMAPIv1 behaviour,
because we always create SMs for all the SMAPIv1 drivers.
This commit ensures that we create SMs for all the running SMAPIv2
drivers, even the ones we did not know about.
I've also made this function safer, because if it raises an exception,
it will cause the startup sequence to fail. Now the function will not
fail if we fail to query one of the SMAPIv2 plugins, it will just log an
error.
=> CA-292372: Create SM objects for all running SMAPIv2 drivers

ocaml/tests/test_cluster.ml, ocaml/tests/test_cluster_host.ml, ocaml/xapi/attach_helpers.ml, ocaml/xapi/storage_access.ml, ocaml/xapi/storage_access.mli, ocaml/xapi/storage_impl.ml, ocaml/xapi/storage_migrate.ml, ocaml/xapi/storage_mux.ml, ocaml/xapi/xapi_cluster.ml, ocaml/xapi/xapi_clustering.ml, ocaml/xapi/xapi_vbd.ml, ocaml/xapi/xapi_vm_migrate.ml, scripts/static-vdis
This has been reviewed previously and had a nightly test run.
Has to be merged together with:
https://github.com/xapi-project/xcp-idl/pull/232
https://github.com/xapi-project/xapi-storage-script/pull/73
https://github.com/xapi-project/xapi-storage/pull/89
https://github.com/xapi-project/xen-api/pull/3645
https://github.com/xapi-project/xenopsd/pull/524
<specfile change>
=> [477 merge] SMAPIv3 VDI.attach2 API

ocaml/quicktest/qt.ml, ocaml/quicktest/qt.mli, ocaml/quicktest/qt_filter.ml, ocaml/quicktest/qt_filter.mli, ocaml/quicktest/quicktest.ml, ocaml/quicktest/quicktest_static_vdis.ml
=> CA-292432: Add quicktest for static-vdis script

ocaml/xapi/xapi_clustering.ml
If there is no clustering daemon package installed fail with a not implemented error when calling Cluster.create instead of an internal error.
=> CP-27694: fail with NOT_IMPLEMENTED if there is no clustering daemon available

ocaml/quicktest/qt.ml, ocaml/quicktest/qt.mli, ocaml/quicktest/qt_filter.ml, ocaml/quicktest/qt_filter.mli, ocaml/quicktest/quicktest.ml, ocaml/quicktest/quicktest_max_vdi_size.ml, ocaml/quicktest/quicktest_vdi_ops_data_integrity.ml, ocaml/quicktest/sizes.ml
=> Quicktest to run VDI ops on empty VDI with max supported size

ocaml/tests/test_vdi_cbt.ml
=> CP-27915: test that VBD.create isn't allowed for cbt_metadata VDI

ocaml/quicktest/qt.ml, ocaml/quicktest/qt_filter.ml
=> CA-292676: Filter out missing VDIs when looking for some to use

ocaml/xapi/xapi_udhcpd.ml
The pidfile is written _after_ udhcpd daemonizes, so we need to wait
for a short amount of time until it turns up.
=> CA-289650: Wait for the pidfile from udhcpd before releasing lock

ocaml/xapi/db_gc_util.ml, ocaml/xapi/xapi_pool_update.ml
=> CA-289898: GC dangling references from 'Host.updates_requiring_reboot'

xapi.opam
=> xapi.opam: remove unused nbd dependency

ocaml/database/db_cache_impl.ml, ocaml/database/db_exn.ml, ocaml/tests/test_db_lowlevel.ml
=> CA-293399: Ensure we don't allow invalid utf8 strings into the db

ocaml/quicktest/qt_filter.mli, ocaml/quicktest/quicktest.ml, ocaml/quicktest/quicktest_example.ml
=> Extend quicktest docstrings

ocaml/xapi/smint.ml
=> CP-28923: Add sm capability for large and thinly provisioned VDIs

ocaml/doc/vm-lifecycle.md, ocaml/idl/datamodel_common.ml, ocaml/idl/datamodel_types.ml, ocaml/idl/datamodel_vm.ml, ocaml/tests/test_common.ml, ocaml/tests/test_platformdata.ml, ocaml/xapi/cli_operations.ml, ocaml/xapi/create_misc.ml, ocaml/xapi/import_xva.ml, ocaml/xapi/records.ml, ocaml/xapi/vm_platform.ml, ocaml/xapi/xapi_vm.ml, ocaml/xapi/xapi_vm.mli, ocaml/xapi/xapi_vm_clone.ml, ocaml/xapi/xapi_xenops.ml
Needs to be merged together with:
https://github.com/xapi-project/xcp-idl/pull/234
https://github.com/xapi-project/xen-api/pull/3675
https://github.com/xapi-project/xenopsd/pull/536
https://github.com/xapi-project/xenops-cli/pull/25
I've tested this on a box and was able to boot/shutdown Debian 9 and Windows 10 with UEFI.
I've opened this to get some feedback on the overall approach
=> UEFI: implement VM.start/stop

ocaml/xapi/storage_task.ml
=> Update to newer interface requirements of Task_server

scripts/xe-toolstack-restart
Add message-switch to the list of services being restarted by 
xe-toolstack-restart.
=> CA-294874 xe-toolstack-restart: add message-switch

ocaml/database/jbuild, ocaml/doc/jbuild, ocaml/idl/jbuild, ocaml/quicktest/jbuild, ocaml/tests/jbuild, ocaml/xapi-types/jbuild, ocaml/xapi/jbuild
=> Simplify PPX processing in jbuild files

ocaml/xapi/xapi_pool.ml
Usually xapi-nbd stops cooperatively, using xapi to unplug any VBDs
before it dies. During pool eject, the host is removed from the
pool and a reboot then issued. When xapi-nbd was still running at
this point it tried to unplug the VBDs and got stuck in a retry
loop because the pool refused to give it a session because it had
been ejected.
The solution is to stop xapi-nbd before we remove ourselves from
the pool, which is what this PR does.
=> CA-293085: Stop xapi-nbd before eject

ocaml/tests/test_xapi_xenops.ml, ocaml/tests/test_xenopsd_metadata.ml, ocaml/xapi/xapi_vm.ml, ocaml/xapi/xapi_vm_migrate.ml, ocaml/xapi/xapi_xenops.ml, ocaml/xapi/xapi_xenops_queue.ml
=> Use PPX Xenops interface

ocaml/idl/ocaml_backend/gen_db_actions.ml
=> Refine the format of generated db_actions code

ocaml/xapi/xapi.ml
This reverts commit 6110755ec58e82dab41931f9f3aea7218573e0ea.
=> Revert "* Workaround for NVIDIA-130"

ocaml/xapi/create_misc.ml, ocaml/xapi/xapi.ml
Job passed - id 2258127.
Signed-off-by: Wei Xie <wei.xie@citrix.com>
=> CA-298373: Set ssl_legacy=true by default in Havana

README.markdown, ocaml/doc/basics.md, ocaml/doc/index.html, ocaml/doc/templates/branding.mustache, ocaml/idl/datamodel.ml, ocaml/idl/datamodel_host.ml, ocaml/idl/datamodel_vm.ml, scripts/examples/python/shell.py, scripts/motd, scripts/xe-backup-metadata, scripts/xe-edit-bootloader, scripts/xe-restore-metadata, scripts/xe-set-iscsi-iqn, scripts/xe-xentrace
Merge feature branch to master.
=> REQ-680: Rebranding XenServer to Citrix Hypervisor in Toolstack.

ocaml/tests/test_sr_update_vdis.ml, ocaml/tests/test_storage_migrate_state.ml, ocaml/tests/test_vdi_cbt.ml, ocaml/xapi/attach_helpers.ml, ocaml/xapi/cli_operations.ml, ocaml/xapi/sm_exec.ml, ocaml/xapi/storage_access.ml, ocaml/xapi/storage_impl.ml, ocaml/xapi/storage_migrate.ml, ocaml/xapi/storage_mux.ml, ocaml/xapi/storage_task.ml, ocaml/xapi/storage_utils.ml, ocaml/xapi/xapi.ml, ocaml/xapi/xapi_pbd.ml, ocaml/xapi/xapi_services.ml, ocaml/xapi/xapi_sm.ml, ocaml/xapi/xapi_sr.ml, ocaml/xapi/xapi_sr_operations.ml, ocaml/xapi/xapi_vbd.ml, ocaml/xapi/xapi_vdi.ml, ocaml/xapi/xapi_vdi.mli, ocaml/xapi/xapi_vm_migrate.ml, ocaml/xapi/xapi_xenops.ml
Use PPX Storage API rather than Camlp4
=> PPX storage

ocaml/database/db_cache_impl.ml, ocaml/xapi/xapi_xenops.ml
Xenopsd has a global metadata lock for creating/deleting and updating the VM cache table.
This means that if you have a VM start that triggers a xenopsd metadata push then all events from other VMs get blocked until this metadata push finishes. On a slave this can be especially slow because it needs to wait for the RPC from master.
This change improves bootstorm on slaves.
The PR is not specific to UEFI, so after some more testing on the UEFI branch I intend to also submit this to master.
=> CP-29420: finer grained locking for xenopsd metadata

ocaml/xapi/xapi_sm.ml
=> CA-298318: Set the SM name_label correctly

ocaml/xapi-consts/api_messages.ml
=> CP-28951: Add message of xen low memory alarm

ocaml/xapi/helpers.ml
This used to call `killall -q -HUP mingetty agetty`, which always returned `1`,
because `mingetty` and `agetty` would never both be running. Replace the
process names with `-r .*getty`, which is happy if just one process is killed.
Also use the existing `call_script` (moved to the top of the file and extended
a little) for more fine-grained error logging.
=> Improve update_getty

ocaml/quicktest/quicktest_vdi_ops_data_integrity.ml, ocaml/xapi/export_raw_vdi.ml, ocaml/xapi/import_raw_vdi.ml, ocaml/xapi/importexport.ml, ocaml/xapi/stream_vdi.ml, ocaml/xapi/xapi_globs.ml
=> CP-29521: VDI import/export in TAR format

ocaml/doc/vm-lifecycle.md, ocaml/idl/datamodel_common.ml, ocaml/idl/datamodel_types.ml, ocaml/idl/datamodel_vm.ml, ocaml/tests/test_common.ml, ocaml/tests/test_platformdata.ml, ocaml/tests/test_vm_check_operation_error.ml, ocaml/xapi/cli_operations.ml, ocaml/xapi/create_misc.ml, ocaml/xapi/import_xva.ml, ocaml/xapi/message_forwarding.ml, ocaml/xapi/record_util.ml, ocaml/xapi/records.ml, ocaml/xapi/vm_platform.ml, ocaml/xapi/xapi_vm.ml, ocaml/xapi/xapi_vm.mli, ocaml/xapi/xapi_vm_clone.ml, ocaml/xapi/xapi_vm_lifecycle.ml, ocaml/xapi/xapi_xenops.ml
These have been reviewed previously on the `uefi` branch.
Needs to be merged together with https://github.com/xapi-project/xcp-idl/pull/252
This is not the complete set of changes from the uefi branch, just those that do not affect Bios mode, so for example this does not contain the locking changes yet.
=> Uefi merge

ocaml/xapi/xapi_vm_migrate.ml
This translates more of the Xenops_interface errors into proper API errors,
like the other lifecycle functions inside Xapi_xenops do.
=> CA-297343: Use transform_xenops_exn in pool_migrate

ocaml/idl/ocaml_backend/gen_server.ml
=> Remove unused Server.dispatch function

ocaml/xapi/xapi_globs.ml, scripts/init.d-xapissl
This change based on the latest requirement, details in the CP ticket. Thanks.
=> CP-29687: Remove TLS_RSA_WITH_AES_128_CBC_SHA(AES128-SHA) for CC

ocaml/xapi/xapi_pool_update.ml
=> CA-300715: Use Dup fd to avoid close twice.

xapi-cli-protocol.opam, xapi-client.opam, xapi-consts.opam, xapi-database.opam, xapi-datamodel.opam, xapi-types.opam, xapi.opam, xe.opam
=> Update opam files for Opam 2

ocaml/xapi/storage_access.ml, ocaml/xapi/storage_migrate.ml, ocaml/xapi/storage_mux.ml, ocaml/xapi/xapi_cluster.ml, ocaml/xapi/xapi_cluster_host.ml, ocaml/xapi/xapi_clustering.ml, ocaml/xapi/xapi_pbd.ml, ocaml/xapi/xapi_services.ml, ocaml/xapi/xapi_sr.ml, ocaml/xapi/xapi_sr_operations.ml, ocaml/xapi/xapi_vdi.ml, ocaml/xapi/xapi_vm_migrate.ml, ocaml/xapi/xapi_xenops_queue.ml
Looks like we missed merging this one
=> CP-29911: New ocaml-rpc

ocaml/xapi/xapi_pool_update.ml
=> CA-298465: Only try to detach locally attached updates when booting

ocaml/xapi/create_misc.ml
The number of vCPUs in dom0 was set to the number of CPUs in the host -
which is wrong. Read the correct number from /proc/cpuinfo from inside
dom0.
=> CA-299554 XSI-132 use correct vCPU count for dom0

ocaml/xapi/xapi_guest_agent.ml
The guest might be able to suspend, but QEMU may not support it,
for example if the guest has not unplugged its NVME disks yet.
Remove the "feature-suspend" from guest metrics and replace it with
the reason error from QEMU when this happens, this will cause the
allowed operations on the VM to be updated accordingly.
Related to https://github.com/xapi-project/xenopsd/pull/571
=> CP-29936: override control/feature-suspend if data/cant_suspend_reason is set

ocaml/idl/api_errors.ml, ocaml/idl/datamodel.ml, ocaml/xapi/xapi_vm_migrate.ml
This code has already been reviewed.
It is adding a check that is independent of the other parts of the feature, and some cleanups that the check depended on.
=> CP-30200: Merge feature/REQ-718/havana into 1.14-lcm

ocaml/database/db_cache_impl.ml, ocaml/idl/datamodel_vm.ml, ocaml/tests/test_platformdata.ml, ocaml/tests/test_vm_check_operation_error.ml, ocaml/xapi-consts/api_messages.ml, ocaml/xapi/import.ml, ocaml/xapi/vm_platform.ml, ocaml/xapi/xapi_db_upgrade.ml, ocaml/xapi/xapi_globs.ml, ocaml/xapi/xapi_guest_agent.ml, ocaml/xapi/xapi_vm.ml, ocaml/xapi/xapi_vm_clone.ml, ocaml/xapi/xapi_vm_helpers.ml, ocaml/xapi/xapi_xenops.ml, scripts/Makefile, scripts/xe-toolstack-restart
See https://github.com/xapi-project/xcp-idl/pull/260
=> CP-30222: get ready for merging Guest Uefi to master

ocaml/xapi/xapi_xenops.ml
=> CA-308834: backport CA-307829 on havana

ocaml/xapi/create_misc.ml
Don't go through logs for guessing IOMMU presence, xenopsd provides this information.
See https://github.com/xapi-project/xcp-idl/pull/265 and https://github.com/xapi-project/xcp-idl/pull/265
=> CP-30508: Reliably detect IOMMU presence in host

scripts/static-vdis
=> CP-30578: check if clustering required and wait for quorum

ocaml/tests/test_cluster.ml, ocaml/tests/test_clustering.ml, ocaml/xapi/xapi_clustering.ml
Also update unit test to return a dummy quorate diagnostics result.
=> CA-309809: avoid a stuck GFS2 mount by checking quorate state before PBD plug

ocaml/xapi/xapi_fuse.ml
This will grantee the consistency of the dumped database and make sure
there is no further writes before we exit.
=> CA-304473: lock the db before flush_and_exit on master

scripts/xe-backup-metadata
Backport of 3808701c3
Signed-off-by: Dermot O'Dwyer <dermot.odwyer@citrix.com>
=> HFX-2249 Increase VDI size for metadata backups.

ocaml/xapi/create_misc.ml
These alerts may cause confusion, because sometimes the "new features" are not
actually new hardware features, but ones that are newly exposed by Xen to
guests.
We are keeping the "lost features" alerts, which are far more useful, and also
extend the logging to include the old as well as the new features.
=> CA-311823: Do not raise alerts for "new CPU features"

ocaml/xapi/xapi_vm.ml
Extracting failed if the files were not present.
Have to first create the file and then extract.
Also add a sanity check for the filename: it must not contain slashes
to avoid path traversal attacks.
=> CA-312227: fix extraction of uefi certificates

ocaml/xapi/create_misc.ml
This complements XSI-132 CA-312644 and commit
4a2cc12d1a72854174b25773f510afcfa8c46aad
The number of vCPUs of dom0 need to be updated on xapi restart in the
dom0 metrics which usually are only written on first boot.
Backport of a3efeb064bb9d3ec7cb7c1ad87835751eb06e0c3
=> XSI-132 CA-312644 CA-299554 update dom0 vcpu count

scripts/static-vdis
=> CA-310173: remember multipath status with static vdi data

ocaml/idl/datamodel_types.ml
=> Change release name from oslo to plymouth

.travis-xs-opam.sh, ocaml/xapi/dune, ocaml/xapi/stream_vdi.ml, ocaml/xxhash/lib/XXHash.ml, ocaml/xxhash/lib/XXHash.mli, ocaml/xxhash/lib/dune, ocaml/xxhash/stubs/dune, ocaml/xxhash/stubs/xxhash_bindings.ml, ocaml/xxhash/stubs/xxhash_stubgen.ml, xapi.opam
Backwards compatability is maintained and xxHash has been vendored for this PR.
=> CP-29682: changed the checksum algorithm from SHA1 to xxHash

ocaml/xapi/pvs_cache_vdi.ml
The function `Pvs_cache_vdi.get_or_recreate_vdi` may be called for multiple
concurrently starting VMs. Without the mutex, this can lead to multiple VDIs
being created, while the should only be one for a given `PVS_cache_storage`
object.
=> CA-314317: Protect PVS-cache get_or_recreate_vdi by mutex

ocaml/xapi/xapi_xenops.ml
Backport for
- HFX-2242
- HFX-2263
=> HFP-510 for Dundee-lcm.

ocaml/xapi/xapi_gpumon.ml
vGPU uuid is needed in gpumon in the case of multiple vGPUs.
=> CP-31124: Add vGPU uuid as parameter to get metadata.

ocaml/xapi/xapi_xenops.ml
=> CP-31122: Send vGPU uuid to Xenopsd.

.travis-xs-opam.sh, ocaml/xapi/dune, ocaml/xapi/stream_vdi.ml, ocaml/xxhash/lib/XXHash.ml, ocaml/xxhash/lib/XXHash.mli, ocaml/xxhash/lib/dune, ocaml/xxhash/stubs/dune, ocaml/xxhash/stubs/xxhash_bindings.ml, ocaml/xxhash/stubs/xxhash_stubgen.ml, xapi.opam
Backwards compatability is maintained and significant performance improvements seen. 
Signed-off-by: RoryBG <rory.bertuzzi-glover@citrix.com>
=> Changed the checksum algorithm from SHA1 to xxHash

ocaml/tests/test_data/nvidia-whitelist.xml, ocaml/tests/test_vgpu_common.ml, ocaml/tests/test_vgpu_type.ml, ocaml/tests/test_xenopsd_metadata.ml
What's in the PR:
1.  Fixed test failures caused by data model change;
2.  Added test cases on metadata with multiple vGPUs.
3.  Removed platform/vgpu_extra_args test cases for vGPU. 
4.  Removed test cases around Nvidia_old.
=> Fix test failures and make new test cases

ocaml/xapi/xapi_xenops.ml
Signed-off-by: Richard Davies <richard.davies@citrix.com>
=> CA-315621 Pass in vm_uuid as well

ocaml/xapi/vgpuops.ml, ocaml/xapi/vgpuops.mli, ocaml/xapi/xapi_gpu_group.ml, ocaml/xapi/xapi_pgpu.ml, ocaml/xapi/xapi_pgpu_helpers.ml, ocaml/xapi/xapi_pgpu_helpers.mli, ocaml/xapi/xapi_vm_helpers.ml
This commit two functionalities:
1. Dry run allocation vGPU to pGPUs
2. Support assign multiple vGPUs to VM
Test done: manual dev test
=> CP-30660: Dry run the allocate vGPU to pGPU

ocaml/xapi/xapi_vm_helpers.ml
Host selection for multiple vGPU
test done:
- manual dev test
=> CP-29991: Host selection for multiple vGPU

.travis-xs-opam.sh
=> Enable non-master testing for feature/REQ-720/master in Travis

ocaml/xapi/xapi_cli.ml
=> Improve CLI log filter

ocaml/xapi/xapi_globs.ml, ocaml/xapi/xapi_sr.ml
Same as https://github.com/xapi-project/xen-api/pull/3891, but for master
=> CA-322044: throttle number of active SR scans

ocaml/xapi/monitor_dbcalls.ml, ocaml/xapi/monitor_mem_host.ml, ocaml/xapi/monitor_mem_vms.ml, ocaml/xapi/monitor_pvs_proxy.ml, ocaml/xapi/monitor_types.ml
Before it was being listed 3 times per poll, once per each RRD monitored.
=> List RRD directory once per monitor poll

ocaml/xapi/xapi_sr.ml
Need to throttle before the API call happens, because
these use up file descriptors too (e.g. to generate session id, etc.)
Need to use different throttles otherwise we deadlock.
=> CA-322044: also throttle the automated API calls for SR.scan

ocaml/xapi/xapi_vgpu_type.ml
Xapi won't start otherwise if this function raises an exception.
=> Catch any exceptions in create_compat_lookup_file

ocaml/xapi/xapi_vm_helpers.ml
From CA-322682, In a PVS Environment, if a VM has a proxy enabled for it, and the vm is then converted into a template, the proxy isn't removed. This then means that the template has an existing vif, and as such no further streamed pvs vms can be created from the template as the device already exists.
I've tested this on an environment that I had left over from the MRGs, can will probably add a few screenshots of this onto CA-322682
=> Remove PVS Proxy from a VM when it is templated

ocaml/xapi/extauth_plugin_ADpbis.ml
PBIS will return success when it queries user KRBTGT even if the domain is
offline but the user KRBTGT is in the cache. This makes the XAPI fail to
check the availability of domain by this appoach.
This commit adds logic to remove the user KRBTGT from cache before XAPI
checks the availabililty of domain.
=> CA-319960: Remove user KRBTGT from cache before checking

ocaml/idl/datamodel_errors.ml, ocaml/tests/check-no-xenctrl, ocaml/tests/dune, ocaml/tests/test_common.ml, ocaml/xapi-consts/api_errors.ml, ocaml/xapi/create_misc.ml, ocaml/xapi/create_misc.mli, ocaml/xapi/dbsync_slave.ml, ocaml/xapi/dune, ocaml/xapi/monitor_types.ml, ocaml/xapi/xapi.ml, ocaml/xapi/xapi_globs.ml, ocaml/xapi/xapi_host_helpers.ml, ocaml/xapi/xapi_host_helpers.mli, ocaml/xapi/xapi_stats.ml, ocaml/xapi/xapi_xenops.ml, ocaml/xapi/xapi_xenops_queue.ml
Depends on:
- https://github.com/xapi-project/ezxenstore/pull/13
- https://github.com/xapi-project/ocaml-rrdd-plugin/pull/31
- https://github.com/xapi-project/rrd-transport/pull/57
- https://github.com/xapi-project/xenopsd/pull/646
=> Add the ability to run xapi while out-of-sync with Xen and/or libxenctrl

ocaml/xapi/xapi_fuse.ml
light_fuse* can trigger reboots and saving of RRDs and the database.
It is enough to do this once, even if we are asked to do it multiple
times (in fact it is counter-productive to do it multiple times because
we would queueu up N RRD backups when we only wanted one).
Rebooting the system would eventually tell xapi to shutdown and trigger
the other fuse, hence the need for different fuse types: Exit when it is
for xapi itself, and Reboot when it is about the system.
I tried flooding it with `xe host-shutdown-agent` in a loop, and it logged the no-op message, and then properly exited when the main fuse was done.
=> CA-322045: make light_fuse idempotent

ocaml/xapi/dune, xapi.opam
=> Remove unused xapi-netdev dependency

ocaml/idl/datamodel.ml, ocaml/idl/datamodel_vm.ml, ocaml/xapi/cli_frontend.ml, ocaml/xapi/message_forwarding.ml, ocaml/xapi/xapi_vm.ml, ocaml/xapi/xapi_vm.mli, ocaml/xapi/xapi_vm_lifecycle.ml, ocaml/xapi/xapi_vm_snapshot.ml
=> CP-31859 Remove support for VSS

ocaml/xapi/create_storage.ml, ocaml/xapi/xapi.ml
Currently, depending on a host's setup, there are up to 3 attempts in plugging
all the PBDs in the startup process: create_storage_localhost,
wait_management_interface, and maybe_wait_for_clustering_ip. We should only
send out an alert if the last attempt still doesn't succeed (in plugging any
PBD).
The patch also consolidates/refactors some functionalities in the
Create_storage module.
=> CA-311625: alarm only if the last attempt of PBD.plug fails

scripts/bugtool-plugin/xapi/stuff.xml
To help diagnose bugs like XSI-443.
=> Gather the list of host datasources

ocaml/xapi/message_forwarding.ml
In 80a59e5f54fee845df, we lost calls which
cleared the VM.migrate current operation from
the database after the operation had finished.
Here we reintroduce these calls.
=> CA-326621 Remove VM.migrate op when finished

ocaml/xapi/xapi_fuse.ml
Signed-off-by: Robin Lee <cheeselee@fedoraproject.org>
=> Fix a typo in comment

ocaml/xapi/console.ml, ocaml/xapi/message_forwarding.ml, scripts/Makefile, scripts/wsproxy.service, scripts/wsproxy.socket
Uses socket activation to run wsproxy on-demand. Needs https://github.com/xapi-project/wsproxy/pull/21
=> Use systemd to daemonize wsproxy

ocaml/xapi/message_forwarding.ml
=> CA-329835 Improve logging

ocaml/idl/datamodel_common.ml, ocaml/xapi/message_forwarding.ml, ocaml/xapi/xapi_db_upgrade.ml, ocaml/xapi/xapi_secret.ml
See https://docs.citrix.com/en-us/citrix-hypervisor/command-line-interface.html#secrets
=> CA-329843: broaden usage of secrets API

ocaml/xapi/message_forwarding.ml, ocaml/xapi/xapi_cli.ml, ocaml/xapi/xapi_host.ml
=> CA-329466: Simplify logging for plugins' parameters

ocaml/database/backend_xml.ml
=> CA-330693: Limit access to state.db to just root

ocaml/tests/test_common.ml, ocaml/tests/test_cpuid_helpers.ml, ocaml/tests/test_pool_cpuinfo.ml, ocaml/xapi/cpuid_helpers.ml, ocaml/xapi/cpuid_helpers.mli, ocaml/xapi/create_misc.ml, ocaml/xapi/xapi_globs.ml
See commit messages for details.
=> CP-32446: support for CPUID features available only during migration

ocaml/xapi/console.ml, scripts/Makefile, scripts/wsproxy.service, scripts/wsproxy.socket
This reverts commit 4aa7e4748ed983d4f73ee5f508eb030090b9b002.
=> CA-330919: Revert "CP-32138: rely systemd to have wsproxy available"

ocaml/tests/test_common.ml, ocaml/xapi/dbsync_slave.ml, ocaml/xapi/helpers.ml
=> maintenance: optimize Helpers.get_localhost

ocaml/xapi/vgpuops.ml, ocaml/xapi/xapi_pgpu.ml
When trying to allocate a PCI VF for an NVidia SRIOV GPU, xapi looks
into its database. The database may contain an entry for a VF that
actually does not exist. This happens, when previously the corresponding
PCI PF was used in pass-through mode. Therefore, xapi needs to call
nvidia_vf_setup in every case. The setup function (which runs on the
relevant host) checks for the prensence of VFs before activating them.
Xapi calls Nvidia's sriov-manage on a PCI to activate PCI VFs. If
previously the PCI device was used as pass-through, it is still bound to
the pciback driver. It needs to be unbound and bound to the "nvidia"
driver first. This commit adds code to do so.
These commits come with corresponding changes in xenopsd but they can be merged
independently.
=> CA-325940 SRIOV switching between vGPU/pass-through

ocaml/xapi/xapi_vm_helpers.ml
Enable do_cpuid_check when recommendation from WLB is filtered. Set zero
score if the vm_incompatible_with_this_host Api_errors is detected.
Signed-off-by: Talons Lee <xin.li@citrix.com>
=> CP-32461: Delete CPUID leveling checks from WLB

ocaml/xapi/xapi_vm_snapshot.ml
There seem to be three cases for the value of domain type, in the snapshot metadata.
If it's not there, we need to fill it in
If it's there, but is unspecified, it's from a Jura era snapshot, so should be updated from `unspecified
If it's there and filled in, then we shouldn't change the value
Signed-off-by: Richard Davies <richard.davies@citrix.com>
=> CA-334909: Only update if the update is needed

ocaml/xapi/cli_operations.ml
=> CP-33121: Stop using Xstringext in cli_operations

Makefile, ocaml/gencert/dune, ocaml/gencert/gencert.ml, ocaml/gencert/lib.ml, ocaml/gencert/lib.mli, ocaml/xapi/dune, ocaml/xapi/helpers.ml, ocaml/xapi/xapi_globs.ml, scripts/11-stunnel-gencert.conf, scripts/Makefile, scripts/gencert.service
final PR for REQ-811
Instead of xapi figuring out whether it needs to generate a certificate, leave it up to systemd
=> gencert systemd service to generate ssl certificate for the stunnel daemon

ocaml/idl/datamodel_common.ml
=> datamodel_common: add quebec release

ocaml/xapi/workload_balancing.ml, ocaml/xapi/xapi_vm.ml, ocaml/xapi/xapi_vm_helpers.ml
This is a backport of https://github.com/xapi-project/xen-api/pull/4030, minus the cleanups done after the actual fixes.
=> CA-334951: Ignore 0-star recommendations from WLB (backport)

.travis-xs-opam.sh
=> fix travis for quebec

ocaml/xapi/xapi_vm_migrate.ml
fixes commit 9ea52f2c25989d6ece705b1811b179d373cf4da4
=> Fix previous patch

ocaml/xapi/helpers.ml
We need to mirror other_config in addition to progress, because we have
tests which rely on this property.
=> CA-338141 mirror other_config when performing InternalAsync operation

ocaml/gencert/test_lib.ml
This fixes the builds on master branch.
=> CP-32669: adapt tests to X509 0.11.0

ocaml/xapi/export.ml
Previously the error would've been lost by the thread.
This can occur if for example a control domain is not allowed to be
exported due to a bug, which raises an exception.
This might help debugging some stuck import tasks, such as CA-336730.
=> CA-334763: Show errors during metadata export/import

ocaml/gencert/gencert.ml
Before #4069  `hostname -f` was used to generate the issuer and the CN for the self-signed certificates, this generated an FQDN, now the code always uses a non-qualified domain name.
Now the code tries to generate the same name as before, if it can't the non-qualified hostname is used instead.
=> CA-338617: Use the FQDN if possible when generating certificates

ocaml/xapi/api_server.ml, ocaml/xapi/xapi.ml
=> CA-336258: fix API forwarder for JSONRPC calls

scripts/generate-iscsi-iqn
Instead of setting the IQN to its filename.
=> CA-339601: source the iqn conf file.

ocaml/xapi/extauth.ml, ocaml/xapi/extauth_plugin_ADpbis.ml, ocaml/xapi/helpers.ml, ocaml/xapi/message_forwarding.ml, ocaml/xapi/xapi.ml, ocaml/xapi/xapi_globs.ml, ocaml/xapi/xapi_host.ml, ocaml/xapi/xapi_subject.ml
This cherry picks the fixes for CA-338602.
=> CA-338602 merge to Stockholm

ocaml/xe-cli/newcli.ml
=> CA-338565: Improve error message.

ocaml/idl/datamodel_diagnostics.ml
This reverts commit d39fcf2994ef29df9e1545fe2a63d3ee15031473.
=> Revert "CA-339526 make gc_compact call public"

ocaml/database/master_connection.ml, ocaml/util/dune, ocaml/xapi/xapi_main.ml, ocaml/xe-cli/newcli.ml, ocaml/xsh/xsh.ml, scripts/xapi.service
Needs to be merged together with https://github.com/xapi-project/xen-api-libs-transitional/pull/78
=> CA-337546: resource leak handling

ocaml/idl/datamodel.ml, ocaml/idl/datamodel_vm.ml, ocaml/perftest/createVM.ml, ocaml/perftest/createpool.ml, ocaml/quicktest/qt.ml, ocaml/quicktest/quicktest_vdi.ml, ocaml/quicktest/quicktest_vm_import_export.ml, ocaml/tests/test_common.ml, ocaml/tests/test_vdi_cbt.ml, ocaml/xapi-cli-server/cli_operations.ml, ocaml/xapi/attach_helpers.ml, ocaml/xapi/debug_populate.ml, ocaml/xapi/import.ml, ocaml/xapi/import_xva.ml, ocaml/xapi/message_forwarding.ml, ocaml/xapi/xapi_pool_update.ml, ocaml/xapi/xapi_templates.ml, ocaml/xapi/xapi_vbd.ml, ocaml/xapi/xapi_vdi_helpers.ml, ocaml/xapi/xapi_vif.ml, ocaml/xapi/xapi_vif.mli, ocaml/xapi/xapi_vm.ml, ocaml/xapi/xapi_vm.mli, ocaml/xapi/xapi_vm_helpers.ml
Signed-off-by: benjamreis <benjamin.reis@vates.fr>
=> Enable to create a VM in Suspended mode with suspend_VDI set

ocaml/xe-cli/newcli.ml
This is a backport of https://github.com/xapi-project/xen-api/pull/4125
=>  CA-340776: disconnect from stunnel cleanly for 1.249

ocaml/xe-cli/newcli.ml
=> CA-340776: disconnect from stunnel cleanly

ocaml/idl/datamodel_common.ml
and set a schema version for stockholm
=> maintenance: bump schema version

ocaml/xe-cli/newcli.ml
Now that the formatting changes are in this can be merged. There were still some conflicts in the XE cli, I fixed by picking the LCM version.
I used git merge and solve the conflicts rather than cherry-pick to make merges easier in the future.
=> Merge stunnel fixes from LCM branch

ocaml/idl/datamodel_errors.ml
Signed-off-by: Aaron Robson <aaron.robson@citrix.com>
=> capitalise 'PEM' in English translations of certificate error messages

ocaml/idl/datamodel_types.ml
Should be merged together with the specs PR.
=> Branding for the Stockholm release

ocaml/xapi/db_gc.ml
This was happening in some cases, but not all
=> CA-341149: Ensure a wait happen when the heartbeat connection fails

ocaml/database/db_cache_types.ml
The commits below add a weak string pool that is used to hold strings used in the Xapi database. Sharing among strings is maximised by looking up the string before it is entered into the database as a key or value. The goal is to reduce memory consumption of the database. The general access pattern is that we have many more reads than insertions such that the added lookup should not matter. Some early benchmarks show that memory consumption of xapi is reduced by 10% or more.
=> Maximise string sharing in database

ocaml/tests/test_common.ml, ocaml/tests/test_pool_update.ml, ocaml/xapi/xapi_pool_update.ml
I have tested this on Havana (we can't really test on master since there are no hotfixes for master).
Once this is merged I will create PRs for Stockholm and Havana
=> CA-341988 avoid update keys="." in xapi database

ocaml/idl/datamodel_types.ml, ocaml/xe-cli/dune, ocaml/xe-cli/newcli.ml
- Backport of https://github.com/xapi-project/xen-api/pull/4165/commits
- Branding for stockholm release
=> Stockholm branding + backport xe client fixes

ocaml/xapi/message_forwarding.ml
Signed-off-by: Gheorghe Burac <gheorghe.burac@citrix.com>
=> CA-319021 fixed resident_on field in Task

ocaml/alerts/certificate/certificate_check.ml
Previously the certificate alerts were replaced every time the script
generating them was run. Now the script only replaces them when the new
alert is different.
=> CA-342551: Avoid replacing certificate alerts

scripts/xapi.service
Unless there's some magic that I'm not aware of, one is probably enough
=> Remove duplicate line from xapi.service

ocaml/idl/datamodel_values.ml, ocaml/tests/common/mock_rpc.ml, ocaml/tests/test_cluster.ml, ocaml/tests/test_cluster_host.ml, ocaml/tests/test_host_helpers.ml, ocaml/xapi/storage_access.ml, rrd2csv.opam, xapi-cli-protocol.opam, xapi-client.opam, xapi-consts.opam, xapi-database.opam, xapi-datamodel.opam, xapi-types.opam, xapi.opam, xe.opam
Also made opam definitions more complete.
Depends on https://github.com/xapi-project/xs-opam/pull/511 and https://github.com/xapi-project/message-switch/pull/56
=> CP-34942: update for rpclib 8 compatibility

ocaml/idl/datamodel.ml, ocaml/idl/datamodel_host.ml, ocaml/idl/datamodel_values.ml, ocaml/tests/common/mock_rpc.ml, ocaml/tests/test_cluster.ml, ocaml/tests/test_cluster_host.ml, ocaml/tests/test_host_helpers.ml, ocaml/xapi-cli-server/record_util.ml, ocaml/xapi-consts/constants.ml, ocaml/xapi/message_forwarding.ml, ocaml/xapi/storage_access.ml, ocaml/xapi/xapi.ml, ocaml/xapi/xapi_globs.ml, ocaml/xapi/xapi_host.ml, ocaml/xapi/xapi_host.mli, rrd2csv.opam, xapi-cli-protocol.opam, xapi-client.opam, xapi-consts.opam, xapi-database.opam, xapi-datamodel.opam, xapi-types.opam, xapi.opam, xe.opam
This allows to compile the branch with the latest ocaml upstream libraries
=> Merge master branch to feature/REQ-403

.ocamlformat, ocaml/database/block_device_io.ml, ocaml/database/database_test.ml, ocaml/database/redo_log.ml, ocaml/perftest/histogram.ml, ocaml/perftest/tests.ml, ocaml/tests/dune, ocaml/tests/test_xapi_db_upgrade.ml, ocaml/tests/test_xapi_xenops.ml, ocaml/xapi-cli-server/cli_operations.ml, ocaml/xapi/create_misc.ml, ocaml/xapi/dbsync_slave.ml, ocaml/xapi/extauth_plugin_ADpbis.ml, ocaml/xapi/import.ml, ocaml/xapi/pool_db_backup.ml, ocaml/xapi/storage_access.ml, ocaml/xapi/storage_impl.ml, ocaml/xapi/xapi_db_upgrade.ml, ocaml/xapi/xapi_globs.ml, ocaml/xapi/xapi_ha.ml, ocaml/xapi/xapi_ha_vm_failover.ml, ocaml/xapi/xapi_host.ml, ocaml/xapi/xapi_host_helpers.ml, ocaml/xapi/xapi_pool.ml, ocaml/xapi/xapi_pool_transition.ml, ocaml/xapi/xapi_session.ml, ocaml/xapi/xapi_vdi.ml, ocaml/xapi/xapi_vm_lifecycle.ml, ocaml/xapi/xapi_vm_migrate.ml, ocaml/xapi/xapi_xenops.ml
This merges master into feature/req-403 to keep it up-to-date.
=> Update feature/req-403 from master

ocaml/gencert/lib.ml
When the X509 library refuses to parse a file the API sometimes
doesn't return the reson, log the reason in those cases so it can be
visible elsewhere.
=> CP-35210: log why a private key or certificates failed to validate

.github/workflows/main.yml
Automatically the latest version in the v1 series for setup-ocaml
See https://github.com/avsm/setup-ocaml/releases/tag/v1.1.3
=> maintenance: update github actions dependency

ocaml/xapi/xapi_vm_lifecycle.ml, ocaml/xapi/xapi_xenops.ml
Testing suggests this introduced a regression on a rolling pool upgrade.
=> CA-347611: Revert CA-332779 (a fix for XSI-555)

ocaml/idl/datamodel_errors.ml, ocaml/xapi-consts/api_errors.ml, ocaml/xapi/xapi_vm.ml
This is just for initial discussion. I will refine the commit message.
=> CP-35021 assert compatibility before suspend

ocaml/xapi/xapi_vm_lifecycle.ml, ocaml/xapi/xapi_xenops.ml
Requires https://github.com/xapi-project/xcp-idl/pull/319 and https://github.com/xapi-project/xenopsd/pull/732.
=> XSI-555/CA-347560/CA-332779: State management fixes

ocaml/xapi/xapi_xenops.ml
Depends on:
* https://github.com/xapi-project/xcp-idl/pull/320
* https://github.com/xapi-project/xenopsd/pull/733
=> XSI-555 for Havana

ocaml/gencert/pem.ml, ocaml/tests/test_bios_strings.ml, ocaml/xapi/bios_strings.ml, ocaml/xapi/dbsync_master.ml, ocaml/xapi/xapi_vdi.ml
This makes the branch compatible with angstrom 0.14, includes a commit to adapt the feature code to the latest library as well.
Depends on https://github.com/xapi-project/xs-opam/pull/527
=> Merge master to feature/REQ-403 

ocaml/xapi-cli-server/cli_operations.ml, ocaml/xapi/create_misc.ml, ocaml/xapi/export.ml, ocaml/xapi/import.ml, ocaml/xapi/importexport.ml, ocaml/xapi/rrdd_proxy.ml, ocaml/xapi/sm_fs_ops.ml, ocaml/xapi/xapi_message.ml, ocaml/xapi/xapi_xenops.ml
The occurences not covered in this PR are covered [here](https://github.com/xapi-project/xen-api/pull/4269) and [here](https://github.com/xapi-project/xen-api/pull/4268).
=> Wrap IPv6 addresses when creating URLs

ocaml/quicktest/quicktest.ml, ocaml/quicktest/quicktest_date.ml
Backport to stockholm of https://github.com/xapi-project/xen-api/pull/4282
=> Backport! CP-34602: test get_server_localtime and message.get_since

ocaml/xapi/xapi_host.ml
=> Allow migration on IPv6 only host

ocaml/alerts/certificate/certificate_check.ml, ocaml/idl/ocaml_backend/gen_rbac.ml, ocaml/quicktest/quicktest.ml, ocaml/quicktest/quicktest_date.ml, ocaml/xapi-cli-server/cli_operations.ml, ocaml/xapi-cli-server/records.ml, ocaml/xapi/cancel_tasks.ml, ocaml/xapi/create_misc.ml, ocaml/xapi/dbsync_master.ml, ocaml/xapi/dbsync_slave.ml, ocaml/xapi/export.ml, ocaml/xapi/helpers.ml, ocaml/xapi/import.ml, ocaml/xapi/importexport.ml, ocaml/xapi/rrdd_proxy.ml, ocaml/xapi/session_check.ml, ocaml/xapi/sm_fs_ops.ml, ocaml/xapi/xapi_message.ml, ocaml/xapi/xapi_pif.ml, ocaml/xapi/xapi_services.ml, ocaml/xapi/xapi_vm_clone.ml, ocaml/xapi/xapi_xenops.ml
Most merge conflicts were due to formatting changes, a move of the logic for certificate verification, and a conflicting change due to name change in (ocaml/xapi/helpers.ml, inet_addrs to ipv4s) https://github.com/xapi-project/xen-api/commit/a4ca9dac85978ec6b29d92b60caf704946185445
=> merge master to feature/REQ-403

ocaml/idl/datamodel.ml, ocaml/idl/datamodel_common.ml, ocaml/idl/datamodel_errors.ml, ocaml/idl/datamodel_pool.ml, ocaml/idl/datamodel_repository.ml, ocaml/idl/dune, ocaml/tests/common/test_common.ml, ocaml/xapi-cli-server/cli_frontend.ml, ocaml/xapi-cli-server/cli_operations.ml, ocaml/xapi-cli-server/record_util.ml, ocaml/xapi-cli-server/records.ml, ocaml/xapi-consts/api_errors.ml, ocaml/xapi-consts/constants.ml, ocaml/xapi/api_server.ml, ocaml/xapi/dbsync_master.ml, ocaml/xapi/helpers.ml, ocaml/xapi/message_forwarding.ml, ocaml/xapi/repository.ml, ocaml/xapi/repository.mli, ocaml/xapi/xapi_globs.ml, ocaml/xapi/xapi_pool.ml, ocaml/xapi/xapi_pool.mli, ocaml/xapi/xapi_pool_helpers.ml, scripts/xapi.conf
This commit introduces datamodel related changes for repository function.
The repository function makes XAPI be able to update dom0 of Xen hosts from
remote YUM repository.
=> CP-35372: Repository: datamodel

ocaml/auth/extauth_plugin_ADpbis.ml, ocaml/xapi/xapi_xenops.ml, scripts/host-backup-restore/host-backup
Various backports:
* CA-343117
* CA-344268 - required minor changes
* XSI-885
=> UPD-666 backports

ocaml/vncproxy/vncproxy.ml
=> Support IPv6 in vncproxy

ocaml/xapi/xapi_host.ml
Forgot to format on some IPv6 PRs, sorry.
=> Make format on previous PRs

ocaml/xapi/message_forwarding.ml, ocaml/xapi/xapi_host.ml
NB: i didn't test this on a host, but I believe it should work
=> REQ-403 another ^ ".pem" fix

ocaml/idl/dune, ocaml/idl/schematest.ml, ocaml/xapi/xapi_vdi.ml, ocaml/xapi/xapi_vm_lifecycle.ml, ocaml/xapi/xapi_vm_snapshot.ml, ocaml/xapi/xapi_xenops.ml
* XSI-828/CA-351323 backports #4308
* XSI-859/CA-348700 backports #4271
* XSI-889/CA-349654 backports #4275 (we already bumped the schema version in #4274)
* XSI-555/CA-332779/CA-347560 backports #4251
=> backport! (stockholm) multiple xapi fixes

ocaml/xapi/repository.ml, ocaml/xapi/repository.mli, ocaml/xapi/repository_helpers.ml
This commit re-structures the code of repository with sub modules and helpers.
=> CP-35373: Restructure code of repository with modules and helpers

ocaml/xapi/xapi_tunnel.ml
=> When creating tunnels, use transport_PIF's primary_address_type

ocaml/xapi/xapi_network_sriov.ml
=> When creating sriov networks, use physical_ref's primary_address_type

ocaml/xapi/xapi_bond.ml
=> When creating bonds, use primary_member's primary_address_type

ocaml/xapi/xapi_vlan.ml
=> When creating vlans, use tagged_PIF's primary_address_type

ocaml/xe-cli/newcli.ml
=> Replace gethostbyname by getaddrinfo to support IPv6

ocaml/xapi-cli-server/records.ml
Also define functions so conventions can be easily followed
=> CA-352329: Revert original formatting of lists in xapi-cli-server

scripts/certificate-check
Backport to Stockholm of https://github.com/xapi-project/xen-api/pull/4329
=> backport! CA-352111: Do not output on cronjobs unless there's an error

ocaml/xapi/xapi_vm_helpers.ml
=> CA-352988: Allow local live migration even when host is disabled

ocaml/xapi/db_gc_util.ml
=> CA-353011: Clean up certificates from unknown hosts

ocaml/xapi/xapi_vm_lifecycle.ml
A customer has seen error messages such as:
```
xe vm-reset-powerstate --multiple --force
operation failed on <vm_uuid>. You gave an invalid object reference. The object may have recently been deleted. The class parameter gives the type of reference given, and the handle parameter echoes the bad value given.
class: PCI
handle: <PCI_ref>
```
It is not clear how they arrived in such a state, but we should be able to get them out by considering the case the the PCI is not valid in `force_state_reset_keep_current_operations`. This should fix both VM hard shutdown and VM reset powerstate
=> XSI-995 remove dangling PCI references from VM records

ocaml/xapi/repository.ml
=> CA-352116: Allow empty guidances in apply_immediate_guidances

.gitignore, ocaml/xapi/extauth.ml, ocaml/xapi/extauth_ad.ml, ocaml/xapi/extauth_ad.mli, ocaml/xapi/extauth_plugin_ADpbis.ml, ocaml/xapi/extauth_plugin_ADwinbind.ml, ocaml/xapi/message_forwarding.ml, ocaml/xapi/xapi.ml, ocaml/xapi/xapi_globs.ml, ocaml/xapi/xapi_gpumon.ml, ocaml/xapi/xapi_host.ml, ocaml/xapi/xapi_subject.ml, ocaml/xapi/xapi_systemctl.ml, ocaml/xapi/xapi_systemctl.mli
=> CP-36059: Manage winbind daemon lifecycle

ocaml/xapi/xapi_cluster.ml
This was a known bug (raised as part of XSI-501), but I have been
running into it a lot recently while testing certificate checking in
xapi-clusterd.
There are two obvious places where we might fail:
a) starting the cluster daemon on the master
b) telling all the slaves to start their cluster daemons and to join
cluster
Previously, if either of these fails, we could be left with cluster
daemons running unnecessarily, and / or cluster records lying around in
the database. You are prevented from enabling clustering again until
these records are deleted manually, which is annoying.
=> CA-329462 Cluster.create should clean up if it fails

ocaml/xapi/fileserver.ml
=> CP-35523: Always accept requests from the unix socket

ocaml/xapi/extauth_plugin_ADwinbind.ml, ocaml/xapi/helpers.ml, ocaml/xapi/xapi_globs.ml
-  Domain leave on_disable to clean local resources
- Add xapi_fs to clean local winbind folder during domain leave
=> CP-36086: Domain leave on_disable

ocaml/xapi/xapi.ml
=> Use reconfigure_ipv6 when necessary

ocaml/xapi/extauth_plugin_ADwinbind.ml, ocaml/xapi/extauth_plugin_ADwinbind.mli, ocaml/xapi/xapi_globs.ml, quality-gate.sh
The debug log is print to stderr
This commit enable the debug with highest level and logged on error
=> CP-36092: Enable winbind debug log and wait for winbind daemon during domain join

scripts/xe-reset-networking
=> Adapt xe-network-reset to ipv6

ocaml/idl/datamodel_pool.ml, ocaml/xapi/message_forwarding.ml, ocaml/xapi/rbac_audit.ml, ocaml/xapi/xapi_pool.ml, ocaml/xapi/xapi_pool.mli
Also includes some minor improvements.
=> CP-36178: Add basic precheck function for updates

ocaml/xapi/extauth_plugin_ADwinbind.ml, ocaml/xapi/xapi_systemctl.ml, ocaml/xapi/xapi_systemctl.mli
=> CP-35398: Support upgrade HCP with PBIS joined domain to winbind

ocaml/tests/test_extauth_plugin_ADwinbind.ml, ocaml/xapi/extauth_plugin_ADwinbind.ml, ocaml/xapi/extauth_plugin_ADwinbind.mli, ocaml/xapi/helpers.ml, ocaml/xapi/xapi_globs.ml
This PR implements ocaml wrappers around some wbinfo, ntlm_auth and net. I've tested the changes using this: https://github.com/xapi-project/xen-api/commit/ff36708793e27844d5495031f49b03c53b1afadd (and also `xe subject-add/remove`)
=> Winbind plugin implementations

ocaml/xapi-consts/api_messages.ml, ocaml/xapi/message_forwarding.ml
=> Add more messages to a VM lifecycle

ocaml/xapi/extauth_plugin_ADwinbind.ml
Commit d969505d9 already support it
This commit just fix a minor error
=> CP-37299: Support both SAM and UPN format for domain user SDK login

ocaml/xapi/cert_refresh.ml
When a host refreshes its internal certificate, it distributes it to all
pool members which will need it for future communication. If any host is
offline, it would miss out. Hence, we fail the operatio if that is the
case and don't refresh a host's certificate.
=> CP-36098 don't refresh certs if any host is offline

ocaml/xapi-consts/constants.ml, ocaml/xapi/import_xva.ml, ocaml/xapi/xapi_cluster.ml, ocaml/xapi/xapi_vm_lifecycle.ml, ocaml/xapi/xapi_xenops.ml, scripts/bugtool-plugin/xapi/stuff.xml
includes (original PRs):
- CA-355657, https://github.com/xapi-project/xen-api/pull/4445
- XSI-995, https://github.com/xapi-project/xen-api/pull/4364
- CA-329462, https://github.com/xapi-project/xen-api/pull/4380
- XSI-804, https://github.com/xapi-project/xen-api/pull/4302
=> [stockholm] backports

ocaml/xapi/extauth_plugin_ADwinbind.ml
CA-356655: subject-add failed with ad.xenrt.citrite.net
To support multiple trusted domain, the domain/server name needs
to be provided during ldap search.
Before this commit, the domain is provided, net command will find
the best server to perform ldap search.
However, in some scenario like lab, DNS failed to resovle the domain
name as dns configuration.
This commit fix the issue by lookup kdc and provide the IP address
instead to skip the DSN resolve
CA-356674: Hostname present on AD server not as expected
xenrt use advanced feature of PBIS to customize host dns name
This commit expose dns-hsotname and netbios-name option to advanced
users, and use default value if not provided.
netbios-name should be limitted to 15 chars
=> Two bugs fixes

.github/workflows/format.yml
=> ci: run format on future feature and lcm branches

.github/workflows/format.yml
Uses the ocamlformat from xs-opam's stockholm branch
=> ci: check whether code in PRs is formatted to stockholm / yangtze branch

ocaml/gencert/selfcert.ml
This seems to fix the intermediate bundle problem
=> REQ-403 CA-356724 add random OU to xapi-pool-tls.pem

scripts/plugins/extauth-hook-AD.py, scripts/plugins/test_extauth_hook_AD.py
Follow up of https://github.com/xapi-project/xen-api/pull/4484
=> CA-356441: reload-or-restart sshd to apply sshd configuration

ocaml/xapi/cert_distrib.ml, ocaml/xapi/certificates.ml, ocaml/xapi/xapi_pool.ml, ocaml/xapi/xapi_pool.mli
- ca certs from a joiner must be added to the database
- 'xe pool-certificate-list' should read from db rather than the file system (though these ought to be functionally equivalent)
=> CA-357151 REQ-403 ca cert fixes

ocaml/xapi/fileserver.ml, ocaml/xapi/xapi_globs.ml
Please review this first: https://github.com/xapi-project/xen-api/pull/4500
This is supposed to be the havana equivalent of https://github.com/xapi-project/xen-api/pull/4422
=> Backport CP-35523 to Havana

scripts/reset-and-reboot
This reverts commit fa1517bcabac06f2ca7a9e72ea8e8b6dddacebb8.
=> Revert "Revert "REQ-403 revert me! FIRSTBOOT_ENABLE_TLS_VERIFICATION

ocaml/xapi/xapi_mgmt_iface.ml
Regression in recent commit (d1fea38).
=> CA-358898: handle IPv6 state when management disabled

scripts/backup-metadata-cron, scripts/init.d-xapi, scripts/install.sh, scripts/xapi.conf, scripts/xe-reset-networking, scripts/xe-toolstack-restart
=> Replace ETCDIR by ETCXENDIR everywhere in scripts/

ocaml/xapi/xapi_http.ml
When a HTTPs request arrived through client cert path, a 'client_cert' role
has been assigned to this request. There is no need to do authentication again
based on credentials in HTTP headers.
This commit adds RBAC checking for this kind of HTTPs requests. In details,
the `Xapi_session.login_with_password` is re-used to create a session so that
`Rbac.check` can be re-used as well to do the RBAC checking with the session.
=> CA-360577: Add RBAC checking for client cert HTTPs requests

ocaml/networkd/bin/network_server.ml
Always require that the device has declared SR-IOV support in sysfs.
This is independent of the way that SR-IOV would eventually be enabled
for the NIC, which may be through either of the "sysfs" or "modprobe"
methods, as before.
=> CA-360485: Fix SR-IOV capability detection

ocaml/xapi-consts/api_messages.ml
=> Fix typo in message name

ocaml/xapi/extauth_plugin_ADwinbind.ml
See #4580, waiting on tests to confirm the issue is fixed before undrafting.
=> Yangtze backport of CA-360951: Failed to lookup workgroup from domain as DNS cache

ocaml/xapi/xapi_globs.ml, scripts/plugins/extauth-hook-AD.py
I couldn't find any more mentions of winbind that actually allow the code to choose it in xapi's code.
=> CA-361151: Use PBIS as the default AD backend

ocaml/xapi-idl/lib/task_server.ml, ocaml/xapi-idl/lib/task_server.mli, ocaml/xapi-idl/xen/xenops_interface.ml, ocaml/xapi/xapi_xenops.ml, ocaml/xenopsd/lib/xenops_server.ml, ocaml/xenopsd/lib/xenops_utils.ml, ocaml/xenopsd/xc/xenops_xc_main.ml
Obsoletes: https://github.com/xapi-project/xen-api/pull/4586
=> Fix xenopsd space leak and high allocation rate

.ocamlformat-ignore, ocaml/idl/datamodel.ml, ocaml/idl/datamodel_certificate.ml, ocaml/idl/datamodel_cluster.ml, ocaml/idl/datamodel_cluster_host.ml, ocaml/idl/datamodel_common.ml, ocaml/idl/datamodel_diagnostics.ml, ocaml/idl/datamodel_errors.ml, ocaml/idl/datamodel_host.ml, ocaml/idl/datamodel_main.ml, ocaml/idl/datamodel_pool.ml, ocaml/idl/datamodel_repository.ml, ocaml/idl/datamodel_roles.ml, ocaml/idl/datamodel_schema.ml, ocaml/idl/datamodel_types.ml, ocaml/idl/datamodel_utils.ml, ocaml/idl/datamodel_values.ml, ocaml/idl/datamodel_vm.ml, ocaml/idl/ocaml_backend/gen_rbac.ml, ocaml/idl/schematest.ml, ocaml/xapi/xapi_role.ml
=> CP-38892: add role.internal field

scripts/certificate-refresh, scripts/network-init
* Enable certificate checking
* Disable certificate rotation but make it available for tests
=> Enable certificate checking by default

ocaml/idl/datamodel_errors.ml
=> CA-362924: Fix typo when syncing repository fails

scripts/poweron/wlan.py
Bug in 930f879b (missing function param).
=> CA-363391: fix wake-on-lan script

scripts/plugins/extauth-hook-AD.py, scripts/plugins/test_extauth_hook_AD.py
This is backport of  https://github.com/xapi-project/xen-api/pull/4646, target to Yangtze
=> backport https://github.com/xapi-project/xen-api/pull/4646 to yangtze

ocaml/idl/datamodel_lifecycle.ml, ocaml/xapi/cert_distrib.ml, ocaml/xapi/certificates.ml, ocaml/xapi/certificates.mli, ocaml/xapi/xapi_globs.ml, ocaml/xapi/xapi_host.ml, ocaml/xapi/xapi_host.mli, quality-gate.sh
This will helps visualizing the functionality provided by the module.
The distinction between certificate_sync and upda_ca_bundle are not clear however, I'd like to come back here to remove more technical debt
=> maintenance: clean up and add interface for certificates module

scripts/bugtool-plugin/xapi/stuff.xml, scripts/bugtool-plugin/xenopsd/stuff.xml, scripts/install.sh
=> Fix and extend bugtool plugins

ocaml/libs/stunnel/stunnel.ml
When a member host is being updated, Toolstack creates a stunnel client
proxy for the connections from local YUM client to the YUM repositories
which locate on the coordinator host. The client stunnel process will be
terminated once the updating on the member host completes.
The client stunnel on a member host, however, will be left there when
the XAPI process has been terminated unexpectedly. And then when the
XAPI process starts again, and tries to create a stunnel client for
update, it will fail as there is already running one.
This commit aims to fix this issue by attempting to clean up running
client stunnel which is listening on the specific TCP port before
creating a new stunnel client proxy.
=> CA-365900: Clean up remanent stunnel client proxy

ocaml/xenopsd/xc/xenops_server_xen.ml
The existing with_data() is somewhat convoluted and executes
is_raw_image() for read and write operations where it does not make
sense to do so for write operations. This commit re-organises the code
without changing functionality for simplicity.
=> Restructure with_data () in xenops_server_xen

ocaml/xapi/helpers.ml, ocaml/xapi/nm.ml, ocaml/xapi/xapi_pif.ml, scripts/network-init
https://github.com/xapi-project/xen-api/issues/4301
=> fixes regarding DNS management

ocaml/xenopsd/xc/device.ml, ocaml/xenopsd/xc/device.mli, ocaml/xenopsd/xc/domain.ml
See [this commit message ](https://github.com/xapi-project/xen-api/commit/5f33eb2fd251e7183098f4ef96233f28b6198974) for details.
=> CA-366014: avoid qemu device state issues during migration in UEFI mode

ocaml/xenopsd/lib/xenops_server.ml, ocaml/xenopsd/lib/xenops_task.ml, ocaml/xenopsd/xc/xenops_server_xen.ml
Previous message was not insightful at all, now it should be more
evident to triage an error when this message happens along a 20 minute
timeout in the logs
=> CA-366098: Clarify logs when a xenopsd task times out

ocaml/xapi-cli-server/records.ml, ocaml/xsh/xsh.ml, scripts/poweron/wlan.py
* 26416aa39 CA-361209 UPD-825 backport utility functions in records.ml       
* dee216ce5 CA-361209 UPD-825 When using WoL find the remote physical PIF    
* 34b31e284 CA-361209 UPD-825 add vlan references to PIF's cli records       
Originals are at 
* cdc4f0707
* 930f879b7
=> UPD-825 Backports to Yangtze

ocaml/xapi/xapi_pif.ml
Instead of throwing an exception when a DNS doesn't have
the correct ip familly: just ignore it
It means when reconfiguring:
- an ipv4: only the ipv4 entries on the input dns will kept and
only the ipv6 dns already set to the pif will be kept
- an ipv6: only the ipv6 entries on the input dns will kept and
only the ipv4 dns already set to the pif will be kept
This is usefull in the case both family are configured on a pif
Right now the installer and xsconsole can fail when reconfiguring an
IP or an IPv6 and both family DNS are present, which can often happen
in case of dual stack
=> Filter input dns when reconfiguring a pif IP(v6)

ocaml/idl/datamodel_common.ml, ocaml/idl/datamodel_errors.ml, ocaml/idl/datamodel_host.ml, ocaml/idl/datamodel_repository.ml, ocaml/idl/schematest.ml, ocaml/tests/test_livepatch.ml, ocaml/xapi-cli-server/cli_operations.ml, ocaml/xapi-cli-server/record_util.ml, ocaml/xapi-consts/api_errors.ml, ocaml/xapi/livepatch.ml, ocaml/xapi/livepatch.mli, ocaml/xapi/message_forwarding.ml, ocaml/xapi/repository.ml, ocaml/xapi/repository.mli, ocaml/xapi/repository_helpers.ml, ocaml/xapi/updateinfo.ml, ocaml/xapi/updateinfo.mli, ocaml/xapi/xapi_host.ml, ocaml/xapi/xapi_host.mli, ocaml/xapi/xapi_host_helpers.ml
There are two commits in this series:
1. refine some functions added in previous commit to facilitate next commit
2. add functions to apply live patches.
=> Support livepatch - part 3 - apply livepatches

ocaml/xenopsd/lib/xenops_server.ml
=> Add matching Synchronisation point 1-mem ACK log on receiver

ocaml/xapi/xapi_host.ml
It has been observed that a "host.restart_agent" XAPI call reported
failure with error "CANNOT_CONTACT_HOST". This was caused by the race
condition between: "host.restart_agent" call on the member host
terminated the stunnel connection bearing the call.
This commit uses a new thread to run the "xe-toolstack-restart" command,
and meanwhile adds a 1-second delay in the thread to make the XAPI call
complete before the stunnel connection being terminated by
"xe-toolstack-restart" command in more probability.
=> Spawn a thread to run xe-toolstack-restart

ocaml/xapi/pvs_cache_vdi.ml
Check if the SR still exists before attempting to scan it in
PVS_cache_storage.destoy. Without that, the call may fail, making it
impossible to clean up the cache storage object.
=> CA-368910: Allow destruction of PVS_cache_storage if SR is already gone

ocaml/xapi/extauth_plugin_ADpbis.ml
In this ticket, all PBIS lwsmd service threads keep in waiting
status and not able to service new requests. Just restart the
service can resovle the issue and bring the service back.
This symptom looks like a race condition. Given PBIS is going to
be replaced with winbind, this commit workaground the issue
instead of investigate and patch PBIS
* Restart lwsmd on LW_ERROR_ERRNO_ECONNREFUSED
* Restart lwsmd on xapi start/restart
=> CA-368806: Workaround pbis get wedged

ocaml/sdk-gen/c/autogen/include/xen/api/xen_string_set_set.h, ocaml/sdk-gen/c/autogen/src/xen_common.c, ocaml/sdk-gen/c/autogen/src/xen_string_set_set.c, ocaml/sdk-gen/c/gen_c_binding.ml, ocaml/sdk-gen/c/templates/Makefile.mustache, ocaml/sdk-gen/c/templates/xen_internal.mustache
This is the last installment for this ticket.
=> CP-37225: Added unmarshalling code for Ocaml's Set(Set string) for C

ocaml/xenopsd/lib/xenops_server.ml
During VM migration memory and vGPU memory are streamed from source
to destination host. Currently, the memory stream can be compressed
optionally while the vGPU stream remains uncompressed. This patch adds
compression for the vGPU stream. It is controlled by the same mechanism
and as such is optional, too, and the default it controlled by a flag in
/etc/xapi.conf. Likewise, it us using the same compression framework
(but it would be easy to add one using different paramters).
=> CP-40392 compress vGPU migration stream

.github/workflows/docs.yml
=> ci: fix doc generation

ocaml/idl/datamodel_lifecycle.ml, ocaml/idl/datamodel_pool.ml, ocaml/xapi/message_forwarding.ml, ocaml/xapi/xapi_pool.ml, ocaml/xapi/xapi_pool.mli
=> CP-40751 Added and implemented Pool.set_https_only

Makefile
The two new libs need to be explicitly mentioned.
=> Update Makefile (un)install targets

scripts/examples/python/XenAPIPlugin.py
=> CP-41033: further updates to XenAPIPlugin for Python3

ocaml/xapi/xapi_host.ml
=> CP-41156 Patched XSI-1246 for Havana

ocaml/xapi/nm.ml
=> CP-41156 Patched XSI 1135 on Havana for NS-SDX

ocaml/xapi/nm.ml
=> CP-41156 Fix to remove reference to Stdlib to fix error

xapi-database.opam, xapi-datamodel.opam, xapi-schema.opam
Signed-off-by: Pau Ruiz Safont <pau.ruizsafont@cloud.com>
=> opam: synchronize opam metadata with xs-opam

ocaml/xapi/xapi_vm_snapshot.ml
is_snapshot_from_vmpp cannot be loaded anymore, so do not try to copy it over.
Additionally when encountering an error when writing the field print a warning instead of failing
This fixes both vm-snapshot and cross-pool migration.
I've tested import-export just in case and it works correctly
=> CA-374238: prevent copying of removed fields when reverting snapshots

ocaml/idl/datamodel_lifecycle.ml, ocaml/vhd-tool/src/direct_copy_stubs.c
Signed-off-by: Pau Ruiz Safont <pau.ruizsafont@cloud.com>
=> maintenance: commit calculated changes for datamodel_lifecycle

ocaml/xapi/xapi_session.ml, ocaml/xapi/xapi_session.mli, ocaml/xapi/xapi_stats.ml
Signed-off-by: Steven Woods <steven.woods@citrix.com>
=> CP-41812: Add total_sessions_count RRD

ocaml/tests/dune, ocaml/tests/test_ref.ml, ocaml/xapi-types/ref.ml
Explanation in commit messages. Draft, because I only unit tested it.
=> Fix total order in Ref.compare

ocaml/xapi-cli-server/cli_operations.ml, ocaml/xapi/export.ml, ocaml/xapi/import.ml, ocaml/xapi/importexport.ml, quality-gate.sh
Add support for VTPM import/export based on the current xapi database backend.
=> CP-39935 VTPM import/export

ocaml/xapi-cli-server/record_util.ml, ocaml/xapi-cli-server/records.ml
Add code to show VTPM operations on VM and VTPM objects in the CLI.
=> CP-39863 show allowed VTPM ops in the CLI

scripts/nbd_client_manager.py
This has been seen to occur in the prescence of a kernel bug which resulted in the NBD device state not being correctly updated. The fix for which is obviously to update the kernel to not have the bug, but also make the calling code robust to the condition and not block for an infinite amount of time.
Remove the lock surrounding the disconnect operation as it is are not required and provides no benefit. Locks are only required to prevent contention between multiple clients trying to acquire the same NBD device having determined that it currently unused.
=> CA-376319: Ensure that nbd_client_manager cannot block forever.

ocaml/xapi/xapi_pif.ml
If HA or clustering is enabled, we are at risk of fencing if the IP address, netmask or gateway changes. This may happen if we switch to DHCP mode, or if we change a static configuration.
The current checks deny any IP configuration change. However, changing just DNS servers in static mode would be safe even if HA or clustering is enabled. This commit relaxes the check.
=> CP-42835: Allow changing DNS servers when HA or clustering enabled

ocaml/libs/tracing/dune, ocaml/libs/tracing/tracing.ml, ocaml/libs/tracing/tracing.mli, ocaml/tests/dune, ocaml/tests/test_tracing.ml, xapi-tracing.opam
Created a Tracing library to produce and export spans on functions and send them to a specific http or file endpoint
=> Add Tracing Library

ocaml/xapi-consts/api_messages.ml
4 messages are added: UPDATES_FEATURE_EXPIRING_WARNING, UPDATES_FEATURE_EXPIRING_MAJOR, UPDATES_FEATURE_EXPIRING_CRITICAL, UPDATES_FEATURE_EXPIRED
=> CP-42019: Add messages for updates feature expiry.

ocaml/xapi/export_raw_vdi.ml, ocaml/xapi/sm.ml, ocaml/xapi/sm_exec.ml, ocaml/xapi/smint.ml, ocaml/xapi/storage_smapiv1.ml, ocaml/xapi/vhd_tool_wrapper.ml, ocaml/xapi/xapi_globs.ml
=> Add an option to use NBD to attach disks to the control domain

ocaml/sdk-gen/java/autogen/xen-api/pom.xml
Also update references to xapi project in the `pom.xml`
=> CP-42739: Bump Java SDK to JDK 11 (LTS)

scripts/Makefile, scripts/bugtool-plugin/xapi/stuff.xml, scripts/xapi-tracing-log-trim.cron, scripts/xapi-tracing-log-trim.sh
Collect spans in Bugtool and delete old spans or purge spans when above 100Mb
=> Manage and Collect spans in logs

ocaml/libs/open-uri/open_uri.ml
The file descriptor for socket /var/xapi/forker/main is leaking. Unexpectedly, Stunnel.with_connect does not close the socket to stunnel which it opens.
=> CA-377824 fix FD leak in xenopsd

ocaml/xapi/xapi_vm.ml
Backport of 7b31dec93b144fad8fa569f3688e2634c482bd96 from xen-api.git
The file descriptor for socket /var/xapi/forker/main is leaking. Unexpectedly, Stunnel.with_connect does not close the socket to stunnel which it opens.
=> CA-377824 fix FD leak in xapi

.github/workflows/main.yml, Makefile
This is needed by other packages that depend on xapi.
=> Fix build: install xapi-tracing

ocaml/libs/tracing/tracing.ml
- fix issue in which max_file_size limit wasn't being respected after batching was added
- simplify the code to remove the need for a fd ref and make sure all fds have closed
=> CA-378304: check max_file_size limit after writing to tracing file

ocaml/xapi/xapi_host.ml
Backport of 6fb867c5d57298a2f5d5d334e838e3f704fa31b5
Host.get_vms_which_prevent_evacuation is used by XenCenter as part of a rolling pool upgrade. But when it fails we are missing information in the logs about VMs that block evacuation of a host. Add logging.
=> CA-378837 log results from Host.get_vms_which_prevent_evacuation

ocaml/libs/stunnel/stunnel_cache.ml
We haev seen a hash table lookup fail unexpectedly. Handle this gracefully.
This does not fix the underlying race condition. The current code strikes me as quite challenging to improve in this regard.
=> CA-379173 handle race condition in stunnel_cache

ocaml/xcp-rrdd/bin/rrdd/xcp_rrdd.ml
- Host load refers to the number of vGPU in running or runnable status, it's similar definition to "load average" in "uptime" and "top" commands for process.
- The "hostload" metric is the host load per physical cpu.
=> CP-43574: Add host load data source

ocaml/xenopsd/lib/xenops_sandbox.ml
On some cases where the sandbox may not have properly cleaned up the remains should not block from creating another sandbox for the same domain id
=> CA-375992: clean up previous sandbox when creating one

ocaml/database/redo_log.ml
We could add some more debugging for the redo log - which in general is disabled from `xapi.conf` because it creates too much logging.
=> CA-379472 add debugging to redo_log

ezxenstore.opam, ocaml/libs/vhd/vhd_format_lwt/blkgetsize64_stubs.c, ocaml/libs/vhd/vhd_format_lwt/odirect_stubs.c, ocaml/xapi/xapi_guest_agent.ml, ocaml/xapi/xapi_message.ml, ocaml/xapi/xapi_pgpu.ml, vhd-format-lwt.opam, vhd-format.opam, xapi-storage-script.opam, xapi-storage.opam, xapi-xenopsd.opam, xapi.opam, xen-api-sdk.opam
Twin PR to https://github.com/xapi-project/xs-opam/pull/642
=> small, low-risk tweaks: opam metadata, replaces uses of deprecated functions, cleanups

ocaml/xapi/xapi_pool.ml
Set "sync_with_yum_repos_in_progress" as true in "Pool.other_config" when update sync starts, set it to false when it finishes.
=> CP-43799: Add a flag to show if an update sync is in progress

ocaml/xapi/xapi_pool.ml
This reverts commit 91104b3a15d07008ff96451a9b469ffd020f6eee.
=> Revert "CP-43799: Add a flag to show if an update sync is in progress"

.github/workflows/main.yml
Previous image was starting to need workaround because it wasn't updated anymore
Set to draft to test the change
=> ci: update base image

ocaml/database/redo_log.ml
We see connection problems for the redo log and need to understand this better. The "redo_log" is disabled but "redo_debug" is not. This logs the connection attempts.
=> CA-379472 CA-379459 add debugging to redo_log

ocaml/forkexecd/lib/forkhelpers.ml, ocaml/forkexecd/lib/forkhelpers.mli, ocaml/xenopsd/lib/xenopsd.ml, ocaml/xenopsd/xc/service.ml
Improve logging and wait long for swtpm_setup to start.
=> CA-380178: increase timeout when manufacturing TPMs, improve logging for exec'd commands

ocaml/database/redo_log.ml
"shutdown log" is called from multiple threads and this causes attempts to do the work twice, which fails. Protect the code by a lock such that an already shut down connection is recognised by later calls.
=> CA-379459 protect redo_log.shutdown with a lock

ocaml/database/redo_log.ml
The mutex for the shutdown operation should be local to the redo_log rather than the module. We can have many redo logs and they are independent.
This is a mall fixup for commit b687523fc; we ultimately might change how we use locks for redo locks but this is an improvement over what we have.
=> CA-379459 make shutdown mutex per redo_log

ocaml/xcp-rrdd/bin/rrdp-iostat/rrdp_iostat.ml
All the necessary data is available also from tapdisk/blktap3 directly, through the RRD plugin transport protocol. However, this was missed because of an assumption that tapdev kernel devices are always present. This is no longer the case.
The code is reorganised to take this into account. In the near future, we can probably just delete all of the tapdev-dependent code.
=> CP-42949: Ensure storage RRDs are created without tapdev in kernel

ocaml/xapi-storage/generator/lib/control.ml, ocaml/xapi-storage/generator/test/storage_test.ml
Description was adapted from SMAPIv2.
=> CP-45006: Define volume.compose API for SMAPIv3.

ocaml/idl/datamodel_errors.ml, ocaml/xapi-consts/api_errors.ml, ocaml/xapi/xapi_pool.ml
=> CA-381044: Raise error when `pool.set_update_sync_enabled` is called with `true` and empty repos

ocaml/quicktest/qt_filter.ml
When using `-sr` or `-default-sr` only
count VDIs on those SR to check for leak
VDIs.
=> Only count VDIs on tested SRs

ocaml/xapi/xapi_observer.ml
Observer. Remove the user. prefix from db attributes
=> CP-44561: Preserve the default attributes when setting attributes on an

scripts/xe-reset-networking
Update service name xcp-network to xcp-networkd and use systemctl
=> Fixup xcp-networkd service name

scripts/host-display, scripts/xe-reset-networking
Xapi run some startups on bootup, and some of them are in python This commit update the python scripts to python3
=> CP-46168: Some py2->py3 update for xapi startup

scripts/examples/python/echo.py, scripts/plugins/install-supp-pack, scripts/plugins/perfmon
- change shebang to python3
- format with black
Test passed with ToolStack-Input: Karma Tests, job id: 191565
=> CP-45978 update /etc/xapi.d/plugins to python3 for xs9

scripts/poweron/DRAC.py, scripts/poweron/power-on.py, scripts/poweron/wlan.py
- using xcp.cmd to replace subprocess.popen
- using bytes.fromhex to replace struct.pack
- raise Exception instead of raw string.
- sort out some code style 
Test passed on XenRT, job id 3870994
=> CP-45978 update /etc/xapi.d/plugins/power-on-host to python3 for xs9

scripts/plugins/openvswitch-config-update
- format with black
- using the shared lib xcp.cmd instead of subprocess.popen
- optimize code logic
Test passed with XenRT, job id: 3871613
=> CP-45978 update /etc/xapi.d/plugins/openvswitch-config-update to python3 for xs9 

ocaml/xenopsd/xc/device.ml
This code will need some changes for XS9; in preparation just some logging and simplification.
=> CA-384537 add logging, simplify

ocaml/xcp-rrdd/bin/rrdd/xcp_rrdd.ml
This PR aims to add the Dom0 CPU usage and free memory into rrdd:
- For the Dom0 CPU usage, I extracted and converted it from _xenctrl.domain_getinfo.cpu_time_, I have maintained special treatment for **uptime** like we handled it in the vCPU usage since I am not sure whether we will encounter the same issue as the _vcpuinfo cputime_. This change will update the CPU usage for all domains, not just Dom0.
- For the free memory, I did not find the domain free memory related attribute in _xenctrl_, so I extracted it from '/proc/meminfo'  using **memory available**, which is the same as the guest free memory.
New test result:
```
xe vm-data-source-query uuid=0907edb2-50f8-4784-9971-38c3102337c5 data-source=cpu_usage
0.046414
```
```
xe vm-data-source-query …
```
=> CP-44531 Toolstack: Add dom0 CPU usage, total and free memory into rrdd

ocaml/xenopsd/xc/device.ml
Wait for the state of DEMU to be runnung before unpausing a guest.
* split out the code for waiting into wait_for_vgpu_state
* adjust timeouts
=> CP-46917 wait for DEMU "running" before unpausing

ocaml/xenopsd/pvs/pvs_proxy_setup.ml
Emit port-oriented rules for IPv4 and IPv6 only when needed.
The complication is that a single PVS server can have multiple addresses each of which can be IPv4 or IPv6. So we need both kind of rules if addresses as mixed but can emit only one kind if addresses are of one kind.
This was tested manually and by @rosslagerwall for IPv6.
=> CP-47046 optimise rule emitter

ocaml/idl/datamodel_errors.ml, ocaml/tests/test_repository_helpers.ml, ocaml/xapi-consts/api_errors.ml, ocaml/xapi/repository.ml, ocaml/xapi/repository_helpers.ml, ocaml/xapi/xapi_host.ml
The changes in this series include:
1. Set recommended and full pending guidance lists
2. Add safety check in host.apply_updates
3. Set pending RestartVM for all VMs in the pool
=> CP-45567: Update host.apply_updates for guidance improvement

ocaml/xenopsd/xc/device.ml
Passing an NBD to qemu using qmp: open the socket and pass it to qmp.
Compared to the existing case that the CD is opened as a raw device the
handling of the socket is slightly different: it does not require a `Qmp.Remove_fd`.
=> CA-384537 support NBD for CD device

doc/content/toolstack/features/NUMA/hwloc.svg, doc/content/toolstack/features/NUMA/index.md, ocaml/idl/datamodel_common.ml, ocaml/idl/datamodel_host.ml, ocaml/idl/schematest.ml, ocaml/tests/common/test_common.ml, ocaml/xapi-cli-server/record_util.ml, ocaml/xapi-cli-server/records.ml, ocaml/xapi-idl/xen/xenops_interface.ml, ocaml/xapi/message_forwarding.ml, ocaml/xapi/xapi_host.ml, ocaml/xapi/xapi_host.mli, ocaml/xapi/xapi_xenops.ml, ocaml/xenopsd/lib/softaffinity.ml, ocaml/xenopsd/lib/xenops_server.ml, ocaml/xenopsd/lib/xenopsd.ml, ocaml/xenopsd/xc/domain.ml, ocaml/xenopsd/xc/xenops_server_xen.ml
Draft PR, will need to rerun the perf tests from last time. Also I've only compile tested this.
And I think I have an explanation for the regression that was seen last time with this turned on: it is only a regression if we have a single VM on the host, as soon as you have more and they're all busy it is expected that this change would be the same or slightly better. Yet to confirm that theory, if it turns out to be false I'll remove the last commit that changes the default.
I can also introduce a pool level setting, but if this works well it may not be needed (i.e. just as an escape hatch if something goes wrong).
=> NUMA-aware VM placement: introduce host level control and turn best effort placement on by default

.github/workflows/main.yml, Makefile, doc/content/toolstack/features/NUMA/index.md, ocaml/idl/datamodel_common.ml, ocaml/idl/datamodel_host.ml, ocaml/idl/schematest.ml, ocaml/tests/common/test_common.ml, ocaml/xapi-cli-server/record_util.ml, ocaml/xapi/xapi_host.ml, ocaml/xapi/xapi_xenops.ml
'auto' is a keyword too.
Lets use 'default-policy' instead.
Fixes: d557b697a ("CP-38020: introduce Host.numa_affinity_policy")
=> fix(NUMA): 'default' is a keyword in some SDK languages

scripts/link-vms-by-sr.py
- refactor code to put the entire loop into the try-except block for performance
- change print syntax
- use argparse instead of getopt
- remove unused arguments
- rename `dir` variable as it is python buildin variable
- improve code readablity
Test manunally passed.
=> CP-45979 update link-vms-by-sr.py to python3

scripts/host-display
- format with black
- use xcp.cmd to replace subprocess.popen
Test passed on Xenrt, job id: 3880959
=> CP-45979 update host-display to python3

scripts/hfx_filename, scripts/perfmon, scripts/static-vdis, scripts/test_perfmon.py, scripts/test_static_vdis.py, scripts/xe-scsi-dev-map
Overview:
- Update to Python3
- Fix some tab-space issues
- rename `list` variable as it is python build-in module
- rename `xmlrpc` varialbe as it is python3 module
Tests:
1. hfx_filename:
3880043 miscsinglehost.seq passed (one case failed, but it also faied with rt-next, see 3879984)
2. perfmon:
- manually tested
[root@lcy2-dt49 bin]# ps -ef | grep perfmon 
root     32049 17718  0 05:52 pts/1    00:00:00 python3 perfmon
root     32221 21004  0 05:53 pts/2    00:00:00 grep --color=auto perfmon
- 3880044 alerts.seq passed
3. static-vdis:
- 3882705 corosync4hostsHAP1 passed
- 3882706 Debian passed
4. xe-scsi-dev-map:
- manually tested
[root@lcy2-dt49 bin]# python3 xe-scsi-dev-map 
serial number 'W470E22S' maps the following devices 
/dev/sda6
/dev/sda5
/dev/sda4
/dev/sda3
/dev/sda2 …
=> Update to python3: hfx_filename, perfmon, static-vdis, xe-scsi-dev-map

ocaml/xapi/bios_strings.ml
The host object maintains a map bios_strings that has an entry for the "hp-rombios key. The value is based on a value read from dom0 memory using /dev/mem. This is incompatible with secure boot and this patch makes the value returned the empty string. The value is patched into a guest's memory so we can't return anything else.
We might want to remove the key `hp-rembios` in the future.
=> CP-46264 deprecate host.bios_strings[hp-rombios] entry

ocaml/xapi/xapi_clustering.ml
This is an experimental feature, which is disabled by default. It can be enabled by running:
echo 1 > /etc/xenserver/features.d/cluster_health
and restarting xapi.
=> Only start cluster watcher if cluster_health feature enabled

ocaml/xenopsd/xc/device.ml
Further adjust parameters passed to QEMU when using an NVidia compte (VCS) profile.
=> CP-46200 CP-45741 pass -std-vga to QEMU in the case of compute GPU

Makefile, ocaml/xapi-storage-script/test/volume/org.xen.xapi.storage.dummy/plugin.py, ocaml/xapi-storage-script/test/volume/org.xen.xapi.storage.dummy/sr.py, ocaml/xapi-storage-script/test/volume/org.xen.xapi.storage.dummy/volume.py, ocaml/xapi-storage-script/test/volume/org.xen.xapi.storage.dummyv5/plugin.py, ocaml/xapi-storage-script/test/volume/org.xen.xapi.storage.dummyv5/sr.py, ocaml/xapi-storage-script/test/volume/org.xen.xapi.storage.dummyv5/volume.py, ocaml/xapi-storage/python/xapi/__init__.py, ocaml/xapi-storage/python/xapi/storage/api/datapath.py, ocaml/xapi-storage/python/xapi/storage/api/plugin.py
Some issue with the porting were detected, and needs some changes.
For the original PR see https://github.com/xapi-project/xen-api/pull/5375
=> Revert xapi-storage and xapi-storage-scripts porting to python3

ocaml/tests/test_observer.ml
Adds a unit test for `observed_components_of`.
Tests over a list of inputs fot `observed_components_of_inputs` while changing the value of
`Xapi_globs.observer_experimental_components` with:
`no_exp_comp`    -- empty `StringSet`;
`smapi_exp_comp` -- singleton `StringSet` that represents smapi.
=> CP-46157: Add unit test for `observed_components_of`

ocaml/sdk-gen/java/autogen/xen-api/pom.xml
Also update docs URL in `pom.xml`
=> Bump maven plugin versions in Java SDK's `pom.xml`

Makefile, ocaml/sdk-gen/c/autogen/src/xen_common.c, ocaml/sdk-gen/c/gen_c_binding.ml
This PR is a simple cherry pick of the commits in https://github.com/xapi-project/xen-api/pull/5436
=> Port of "Fix C SDK build on Fedora39" to `master`

ocaml/xapi/context.ml
Add standard http attributes from opentelemetry such as:
- `http.request.method`
- `http.request.header.content-type`;
- `http.request.body.size`;
- `http.request.header.user-agent`;
- `http.request.header.(key)`.
Add standard network attributes from opentelemetry such as:
- `network.local.address`;
- `network.local.port`;
- `network.peer.address`;
- `network.peer.port`.
This improves debuggability associated with client requests.
TODO: add `network.transport`.
=> Improve span attributes associated with remote clients

ocaml/idl/ocaml_backend/gen_api.ml, ocaml/idl/ocaml_backend/ocaml_utils.ml, ocaml/tests/test_vm_check_operation_error.ml, ocaml/xapi/xapi_host_helpers.ml, ocaml/xapi/xapi_sr_operations.ml, ocaml/xapi/xapi_vdi_helpers.ml, ocaml/xapi/xapi_vm_lifecycle.ml
This wasn't tested, and the logic in the tests makes it difficult to understand, so add tests that clarify the behaviour.
I've added tests for all interactions when there's a new hard shutdown and restart requested.
If you have more interesting examples, I'll add them
=> test: add tests for allowed VM operations

scripts/xe-xentrace
TODO: would be better to rewrite this in python or ocaml
=> CA-391660: xe-xentrace: fix and allow dumping on high CPU

ocaml/xapi/extauth_plugin_ADwinbind.ml
Refactor the representation of Kerberos Domain Controller (KDC) to better support IPv6. It became apparent that the current implementation assumes standard port 88 being used by a KDC - which we should relax in the future.
Capture a KDC configuration as KDC.t and provide functions to create, serialise, log a value. Represent the IP address as Ipaddr.t (which can be IPv6 or IPv4).
The existing implementation does not properly use a domain controller's port number that it obtains from a `net lookup kdc`:
* the port number is not passed to other net commands that query the domain controller
* the port number is not stored in the xapi database (along the IP address).
=> CP-49429 add IPv6 support for winbind/KDC

.github/workflows/generate-and-build-sdks.yml, .github/workflows/release.yml
Tested in https://github.com/acefei/xen-api/releases/tag/v0.0.2
=> CP-50055 Add Go SDK as a release package in XAPI

ocaml/idl/datamodel_errors.ml
CA-386173: Update the message of WLB authentication issue
=> CA-386173: Update the message of WLB authentication issue

python3/extensions/pool_update.apply, scripts/plugins/extauth-hook-AD.py
Python3: Cleanup unused imports
=> Python3: Cleanup unused imports

quality-gate.sh
Github let a conflict pass by in the last merge
=> quality-gate: fix list.hd

python3/plugins/extauth-hook-AD.py, python3/plugins/test_extauth_hook_AD.py
To: @liulinC (Author of the removed lines)
XS8 removed PBIS Active Directory support (was replaced by Winbind).
- I assume, that PBIS code could be removed from Xapi therefore.
Testing:
- The unit test `python3/plugins/test_extauth_hook_AD.py` provides code coverage for 100% of the changed lines.
- The current `diff-cover` configuration that runs in `pre-commit` and GitHub CI ensures that indeed 100% of all changed lines are covered by the test.
----
PS:
These OCaml sources could be removed too:
```py
ocaml/tests/test_extauth_plugin_ADpbis.ml
ocaml/xapi/extauth_plugin_ADpbis.ml
scripts/pbis-force-domain-leave
```
They are needed by those (PBIS is also referred to in those and would need changes too):
```py
ocaml/tests/test_extauth_plugin_ADwinbind.ml
ocaml/tests/suite_alcotest.ml …
```
=> Cleanup obsolete `PBIS` support (removed in XS8) from extauth-hook-AD.py

ocaml/xapi/xapi_clustering.ml
Sometimes it takes the underlying cluster stack (corosync) some time to return a consistent view of the quorum. For example, it may be that the membership information correctly reflects the new members after a membership change, while the quorum field is still out of date. Add a delay here to make sure that the information from corosync represents a consistent snapshot of the current cluster state.
=> CA-396635: Wait for corosync to update its info

ocaml/xapi-storage/generator/lib/control.ml
* Give the parameters meaningful names
* Describe host this might be implemented with delta files
* Declare that the parent volume should be considered invalid after completion.
=> Update the docs for Volume.compose

ocaml/xapi/xapi_xenops.ml
Dates converted from unix timestamps have subsecond precision, but dates serialized in the database do not. This is a change in behaviour introduced in 233b96ba44b002a27205b0681f35527457b78c2c
This fix was supposed to be included in the change, but got lost. No other users were found that hit this change in behaviour.
Fixes the test about VMs pending guidances being removed when not needed, job 411209
=> CA-398128: Be wary that dates in database lose precision

ocaml/idl/datamodel.ml
I noticed these when I dropped the latest SDK into XC.
=> Corrected strings.

ocaml/xapi/xapi_globs.ml, ocaml/xapi/xapi_session.ml
Workaround for CA-400339.
This'll allow us to get a proper fix in, without having to rush that change.
=> Revert changes causing deadlock

ocaml/xapi/xapi_cluster_helpers.ml
Draft because I need to get Yizhou's agreement on this
=> CP-51938: Generate XML alert for cluster health

ocaml/idl/datamodel_common.ml, ocaml/idl/datamodel_lifecycle.ml, ocaml/idl/datamodel_pool.ml, ocaml/idl/schematest.ml, ocaml/tests/common/test_common.ml, ocaml/xapi-cli-server/records.ml, ocaml/xapi/dbsync_master.ml
Add new XAPI pool level data for licensing
=> CP-52114: Add pool.license_server for pool level licensing

ocaml/xapi/xapi_host.ml
Get licensing data from host.license_server and pool.license_server. For the same keys, host level data will overwrite the pool level data.
=> CP-52116: Support pool level licensing data in Host.apply_edition

doc/content/toolstack/features/NUMA/index.md
Hi, in this PR for https://xapi-project.github.io/new-docs/toolstack/features/NUMA/index.html,
I'd like to:
- Add more sections to improve the document structure
- Fix a few typos
- Simplify some parts
=> ### `new-docs`/NUMA : Fix typos and simplify some parts

doc/content/xapi/internals/_index.md, doc/content/xapi/internals/generated.md
Provides a short article that tries to elucidate aspects concerning API, Server, Client, and Db_actions.
=> Document Xapi's auto-generated modules

ocaml/tests/test_sm_features.ml, ocaml/xapi/smint.ml
For some reason the SR_CACHING feature was never defined in xapi.
=> Define SR_CACHING capability

.github/workflows/setup-xapi-environment/action.yml
It got changed by
https://github.com/xapi-project/sm/commit/84992502148a8a5e5639151f3e8f1c19e18cac38
=> ci: url of XS_SR_ERRORCODES.xml

ocaml/xcp-rrdd/bin/rrdd/xcp_rrdd.ml, ocaml/xcp-rrdd/lib/transport/file/rrd_file_writer.ml
Two small commits to improve RRD daemons.
=> Improve RRD robustness

ocaml/xapi-idl/storage/storage_interface.ml, ocaml/xapi-idl/storage/storage_skeleton.ml, ocaml/xapi-storage-script/main.ml, ocaml/xapi/storage_migrate.ml, ocaml/xapi/storage_mux.ml, ocaml/xapi/storage_smapiv1.ml, ocaml/xapi/storage_smapiv1_migrate.ml, ocaml/xapi/storage_smapiv1_wrapper.ml, ocaml/xapi/storage_smapiv3_migrate.ml
Sorry guys, forgot about `receive_finalize2` 🤪. I hope there is no more....
=> CA-408492: Add back `receive_finalize2` as well

ocaml/idl/datamodel_lifecycle.ml
Update all `25.20.0-next` to `25.21.0` in `datamodel_lifecycle.ml`.
=> Update datamodel_lifecycle (25.21.0)

ocaml/xapi/vm_sysprep.ml
Replace code that loops waiting for an update in xenstore with a watch. This should eliminate the chance of a race condition. We are introducing a small delay to give sysprep the chance to read its file before we eject the CD.
=> CP-308455 VM.sysprep use watch to detect sysprep running

.github/workflows/other.yml, .pre-commit-config.yaml, doc/content/python/_index.md
Some tools are displaying deprecation warnings, this PR addresses them by using the direct replacements
=> CI: update python config

ocaml/xapi-cli-server/cli_frontend.ml, ocaml/xe-cli/bash-completion
Also add it to the documentation of the parameter of vbd-create
=> xe-cli: Allow floppy to be autocompleted

ocaml/xapi/xapi_globs.ml
The current Windows drivers now support this (according to Vikas) and we can enable this.
=> CP-308455 VM.sysprep turn on feature
