xapi-project/xen-api

- ocaml/client_records/record_util.ml
- ocaml/client_records/records.ml
- ocaml/idl/datamodel.ml
- ocaml/xapi/import.ml
- ocaml/xapi/xapi_vbd.ml
- ocaml/xapi/xapi_vm.ml
- ocaml/xapi/xapi_vm_helpers.ml
- ocaml/xapi/xapi_xenops.ml
Original pull request: https://github.com/xapi-project/xen-api/pull/2057
This fixes two bugs. Floppy VBDs can now be successfully attached and used in HVM guests.
The first commit 6c391c5a7c10611f85b316e9470132463712bea4 fixes userdevice assignment issues, so that floppies are properly assigned an "fd?" rather than "xvd?". qemu *requires* this, in addition to the drive being on the "floppy" bus.
Despite `Device_number.to_disk_number` not being unique (see https://github.com/xapi-project/xcp-idl/pull/47), it is still used in several places around the code. We need to check these to make sure they don't interfere with floppy support. The second commit bde0bb68623322272ab8d68e8597160894fa2cb3 is an example of fixing this, where xen-api would previously get confused between "fda" and "xvda" …
> [RFC]: Add a 'floppy' VBD type (take #2)

- ocaml/idl/datamodel.ml
- ocaml/xapi/cli_frontend.ml
- ocaml/xapi/cli_operations.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_vm.ml
- ocaml/xapi/xapi_vm.mli
- ocaml/xapi/xapi_vm_lifecycle.ml
- ocaml/xapi/xapi_xenops.ml
> CP-10203: XenAPI: api call for RDP on/off request

- ocaml/xapi/xapi_vm_lifecycle.ml
- ocaml/xapi/xapi_xenops.ml
The Resume operation sould be blocked when a checkpoint is ongoing,
otherwise two domains may coexist for a single VM.  In existent
implement the current-operations field of a VM were cleaned upon
the finish of the suspension, which is a part of a checkpoint task,
makes Resume become an allowed operation.
Signed-off-by: Kaifeng Zhu <kaifeng.zhu@citrix.com>
> CA-154341: Disallow Resume when a Checkpoint is ongoing

- scripts/examples/python/XenAPI.py
Pyython 2.7 requires the Transport instance to have a _connection tuple.
> CA-154346: scripts: Fix compatibility with Python 2.7

- ocaml/xapi/message_forwarding.ml
When attempting to restart HA-protected VMs after an HA failure, they
should be not treated as new VMs to add to the HA plan, since HA will
already be taking them into account.
> CA-151670: Don't double count HA-protected VMs when restarting them

- xapi.spec.in
net-tools is not pulled in by default on CentOS 7, so depend on it.
> CP-9798: Depend on net-tools for ifconfig

- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_main.ml
- ocaml/xapi/xapi_pci_helpers.ml
- ocaml/xapi/xapi_pgpu.ml
- scripts/xapi.conf
This is the work for CP-10795. It has stubbed out the functionality for checking that a PCI device has been hidden from dom0 since that will be delivered in a separate pull request.
> Add passthrough to supported_vgpu_types when appropriate

- ocaml/xapi/xapi_guest_agent.ml
- ocaml/xenops/xenops_server_xen.ml
Add data/ts to VM_guest_metrics so XenCenter can detect guest VM RDP status.
> CP-10236: Expose RDP status to VM guest metrics

- ocaml/xapi/pciops.ml
- ocaml/xapi/pciops.mli
pciops now has functions hide_pci, unhide_pci, is_pci_hidden
> CP-10787: functions for (un)hiding PCI devices from dom0 kernel.

- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_vm.ml
This pull requst is to implement the RDP feature design update.
It contains 2 commits. One is to increase the API version so that XenCenter could distinguish the Xapi version and know if it supports RDP feature. Another one is to use "feature-ts2" as RDP feature indicator so Xapi could understand if the Windows Guest Agent supports the new RDP feature.
> CP-10954: Use "feature-ts2" as RDP feature indicator and update api minor version

- ocaml/database/master_connection.ml
- ocaml/xapi/xapi.ml
The master connection watchdog did not take effect as
a) Only the processing time of the HTTP response was treated as the lasting time to compare with the timeout value;
b) The watchdog thread was not started.
So extend the scope of with_timestamp and start the watchdog thread in slave before attempting to communicate with pool master.
> CA-153127: Enable master connection watchdog

- ocaml/test/test_xenopsd_metadata.ml
- ocaml/xapi/pciops.ml
- ocaml/xapi/pciops.mli
- ocaml/xapi/xapi_pci_helpers.ml
- ocaml/xapi/xapi_pgpu.ml
- ocaml/xapi/xapi_xenops.ml
Ensure that qemu is started with the -gfx_passthru flag when an
appropriate integrated GPU is available.   The logic is explained in
the following design document:
http://xapi-project.github.io/features/futures/integrated-gpu-passthrough.html
> CP-10125: Pass -gfx_passthru flag down to qemu

- ocaml/xapi/xapi_xenops.ml
We need to be able to use 0 and 1 in (at least) the case of the acpi key.
Before this patch, using 0 and 1 would have both been converted to true when
passed to Xenopsd and therefore wrong arguments could be passed to Qemu when
trying to disable this feature.
This patch makes the 'bool' function a little more lenient on its input rather
than using OCaml's stock bool_of_string. It also introduces a warning message
if the value has been specified incorrectly.
> [Caboodle/HFX-1263] CA-146595: Improve parsing of VM platform flags

- ocaml/xapi/storage_migrate.ml
- ocaml/xapi/xapi_blob.ml
There's a rather fundamental race in the SMAPIv1 backends with
the storage motion code. Fortunately the race only really affects
a cosmetic issue - whether VDIs temporarily show up in the GUI
while storage motion is going on. The bug exhibits as the
VDI of the VM containing a 'base_mirror' key in the sm_config
field.
Unfortunately this problem becomes worse when a subsequent SXM
operation is attempted - at this point the operation will fail
as we try to put a new base_mirror key in, getting a Duplicate_key
error.
This changeset fixes this such that we simply overwrite the
existing key. This doesn't change the cosmetic problem that the
VDIs will be missing from the GUI, but it does mean you can now
migrate the VM again.
Additionally this changeset fixes more minor problems:
- on cancelling …
> [Caboodle/HFX-1306] CA-98606: Reduce impact of duplicated base_mirror key

- ocaml/xapi/xapi_vm_snapshot.ml
Instead of ignoring the snapshot's CD VBDs, we clone them as normal to
the new VM. However, we still disregard the CD VBDs when fixing up the
snapshot_of links.
> CA-160970: Recreate CD VBDs after a revert to snapshot

- ocaml/idl/datamodel.ml
- ocaml/xapi/OMakefile
- ocaml/xapi/dbsync_slave.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/pciops.ml
- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_host.mli
- ocaml/xapi/xapi_host_display.ml
- ocaml/xapi/xapi_host_display.mli
- ocaml/xapi/xapi_pci_helpers.ml
- ocaml/xapi/xapi_pgpu.ml
- scripts/OMakefile
- scripts/host-display
- xapi.spec.in
Introduces the API field `host.display`, and the API calls `host.enable_display` and `host.disable_display`.
This allows an API client to enable or disable host console output the system display device.
Also includes some fixes to related code.
> CP-10978: Implement host-level display configuration

- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_pci.ml
- ocaml/xapi/xapi_pci.mli
If the host display is disabled, disable the host's primary display device.
This is done by writing "decodes none" to /dev/vga_arbiter
> Add mechanism for disabling the primary display device

- ocaml/client_records/records.ml
The fifth of four commits for this feature.
> CP-11136: Fix field-name: hyphens not underscores

- ocaml/xapi/import_raw_vdi.ml
- ocaml/xapi/vhd_tool_wrapper.ml
- ocaml/xapi/xapi_vbd.ml
- ocaml/xapi/xapi_vdi_helpers.ml
Several fixes for XAPI's `import_raw_vdi` call were made on trunk that would be worth backporting to enable Packer/Supp pack integration.
> Backport patches for fixing VDI upload

- ocaml/client_records/record_util.ml
- ocaml/client_records/records.ml
- ocaml/idl/datamodel.ml
- ocaml/xapi/import.ml
- ocaml/xapi/xapi_vbd.ml
- ocaml/xapi/xapi_vm.ml
- ocaml/xapi/xapi_vm_helpers.ml
- ocaml/xapi/xapi_xenops.ml
- ocaml/xenops-cli/xn.ml
- ocaml/xenops/device.ml
- ocaml/xenops/device.mli
- ocaml/xenops/device_number.ml
- ocaml/xenops/device_number.mli
- ocaml/xenops/xenops_interface.ml
- ocaml/xenops/xenops_server_xen.ml
This is primarily needed right now to enable packer integration for OSes that require a floppy drive for autoinstalls (e.g. Windows).
I've re-created the patches as best I could to preserve history/authorship and created a fix up commit to handle the alterations required for the pre-disaggregation of XAPI.
> Backporting patches for floppy support

- ocaml/database/block_device_io.ml
32-bit OCaml ints cannot hold values of 2^30 or more, which the database generation count can (eventually) exceed.
> CA-161534: Don't try to put the database generation count in an int

- scripts/init.d-xenservices
init.d/xenservices is limiting the max number of fds in xenconsoled to 4096.
xenconsoled uses 4 fds for each vm, so this is limiting the number of vms in
the host to 1000.
Increasing the max number of fds in xenconsoled to 16384 will let the host
start up to 4000 vms, which is a more reasonable limit given the other
current limits in dom0.
> CA-162159: bump the fd limit in xenconsoled to 16384

- ocaml/client_records/records.ml
Reverts xapi-project/xen-api#2172
It turns out that the code in the xen-api-sdk repository cannot cope with a Set of Int, which is used by the virtual hardware platform version features.
Therefore reverting this for now, until the sdk code has been extended to cope.
(Must revert this before reverting #2169.)
> Revert "CP-11136: Fix field-name: hyphens not underscores"

- ocaml/xapi/storage_access.ml
- ocaml/xapi/xapi_globs.ml
As well as solving race conditions, this actually better reflects the reality
of the underlying implementation since a VDI is reference counted and only ever
attached at most once per host.
> CA-163618: Make read_caching key a per-VDI, per-host property

- ocaml/xapi/xapi_vm_lifecycle.ml
> CP-10605: Allow vgpu enabled VMs to migrate and suspend

- ocaml/xapi/xapi_pool_patch.ml
We should consider the space available for privileged users too.
From `man statvfs`:
struct statvfs {
...
fsblkcnt_t     f_bfree;    /* # free blocks */
fsblkcnt_t     f_bavail;   /* # free blocks for unprivileged users */
...
};
> CA-163770: Use f_bfree to check available space for hotfixes

- ocaml/xapi/xapi_vm_clone.ml
- ocaml/xapi/xapi_vm_snapshot.ml
Make sure that snapshot_of links are set correctly after
* Reverting a VM with multiple disks to a snapshot
* Reverting a VM to a snapshot after deleting one or more of the VM's disks
> More snapshot-revert fixes

- ocaml/client_records/records.ml
- ocaml/idl/datamodel.ml
- ocaml/xapi/import.ml
- ocaml/xapi/xapi_guest_agent.ml
- ocaml/xapi/xapi_vm_helpers.ml
1. Introduce networks_path_optimized and storages_path_optimized flags to vm_guest_metrics.
2. Update the implementation of PV_drivers_up_to_date.
> CP-10531: Update vm_guest_metrics to implement PV drivers update

- ocaml/xapi/xapi_services.ml
- scripts/xapi.conf
This enables the plumbing so that it's (hopefully) easy to experiment with SMAPIv3 plugins.
This requires xen-api-libs-specs#110
The combination of fixes passed a BVT via the trunk-ring3-smapiv3on-take3 branch.
> Enable SMAPIv3

- ocaml/xapi/storage_migrate.ml
- ocaml/xapi/xapi_vm_migrate.ml
This avoids using the Unix domain socket which won't exist if you're
using a message switch.
> Use HTTP to /services/SM for both local and remote cases

- ocaml/xapi/cli_frontend.ml
- ocaml/xapi/cli_operations.ml
1) Cross pool vm migrate:
vdi:vdiuuid=sruuid map can be provided to define destination sr
or default sr of destination pool is taken as a destination sr
2) Intra pool vm migrate:
default sr of a pool is taken as a destination sr
> CA-166757: Deprecating "destination-sr-uuid" param during vm-migrate

- ocaml/xapi/monitor_master.ml
- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_xenops.ml
- scripts/xapi.conf
This allows admins to configure a system default when the package
is installed, without relying on the infrequently-polled
Pool.other_config override mechanism.
> Add the default value of 'pass-through-pif-carrier' to xapi.conf

- ocaml/xapi/xapi_vm_clone.ml
Not using the default of "false", but use the value of the VM clone from.
> CP-12148: Inherit auto_update_drivers and hardware_platform_version on VM.clone

- ocaml/xapi/create_misc.ml
- ocaml/xapi/xapi_globs.ml
I have tested this by modifying `state.db` and then restarting Xapi with this patch. The port numbers are updated if the consoles already exists and are correctly created if they do not.
> CA-169483: Update dom0 console port numbers on startup

- ocaml/xapi/quicktest.ml
Using the unix domain socket now automatically authenticates, so
these tests now fail. XenRT uses TCP connections, so it still tests
the behaviour.
> CA-171273: Disable the http auth tests when using the unix socket

- ocaml/xapi/xapi_globs.ml
Cream will have API version 2.4.
Also bump xencenter_[min|max]_verstring.
> Bump API version to 2.5

- ocaml/xapi/xapi.ml
Dbsync on a slave needs to be able to do a storage call for PBDs that are
already attached (e.g. when xapi restarts during a master switchover).  The
storage calls need the SMAPIv1 proxies to be running. The SMAPIv1 proxies need
the DB to be up, and therefore need a master connection on a slave.  Therefore,
on a slave, the proxies need to be started after establishing the master
connection, but before the dbsync.
> CA-170667: Start SMAPIv1 proxies before dbsync on slave

- scripts/examples/python/xva.py
This module shows how to parse an XVA (with and without disk blocks),
modify the metadata and write out a fresh archive.
> Add an example python script which rewrites SCSIids in XVA archives

- ocaml/xapi/xapi_guest_agent.ml
This commit assume that the xenstore key that gates XenMotion ( feature-suspend ) gets written by the PV drivers very quickly, quicker than the guest agent writes its version number. This should significantly reduce the likelihood of a migration failing due to it thinking that the drivers are missing.
XAPI will use  feature-suspend , rather than the drivers' version number, to find out whether a VM can migrate
In this commit, following thing been done:
1.Remove PV version check before update VM status
2.Merge the if and else to the same logic since condition are the same.
> CA-171738: Remove PV version check before update VM status

- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_pif.ml
- scripts/xapi.conf
Xapi executes the script during a PIF.scan to set the PIF.managed accordingly.
> CP-12292: Allow a script to list PIFs that should not be managed by xapi

- ocaml/xapi/xapi_pci.ml
This is required for upgrades from 6.5 where we weren't storing the whole class ID. We only stored the most significant byte as a string. For example, display controllers have PCI class `03xx` and we were storing `03` in the database for `PCI.class_id`. The new code stores the whole class ID and checks that the 16-bit integer has the right base class to determine whether or not to create a PGPU. This changeset updates the class fields on the PCI object when Xapi starts and will result in any PCIs with `class_id` `03` be updated to have their full class ID.
> Update PCI class fields on update_pcis

- scripts/examples/python/XenAPI.py
Several API examples exist, including one in the xen-api repo, that use
session.logout directly without going through session.xenapi or
session.xenapi.session.  While this is not the correct way to
logout of the XAPI session, logout is one of the special cases
that needs to be supported from the session object.
Signed-Off-By: Bob Ball <bob.ball@citrix.com>
> CA-173622: Enable session.logout()

- ocaml/xapi/xapi.ml
- ocaml/xapi/xapi_host.ml
Host.ssl_legacy now controls the protocol-version and ciphersuites
used by outgoing TLS connections, not just incoming ones.
> CP-12512 ssl-legacy controls outward stunnels too.

- scripts/examples/python/xva.py
This patch also adds a convenient '--test' mode which does the same
thing with other_config, which is easier to manipulate.
> XVA rewrite script now works with python 2.4.3 (as seen in XS 6.2)

- ocaml/xapi/xapi_fist.ml
- ocaml/xapi/xapi_vm_lifecycle.ml
* Restrict migration/suspend to NVIDIA vGPUs only
* Add a FIST point to allow vGPU migration/suspend
> Tidy up allowed_operations code for vGPU migration and suspend

- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/mtc.ml
- ocaml/xapi/xapi_vbd.ml
- ocaml/xapi/xapi_vgpu.ml
- ocaml/xapi/xapi_vm.ml
- ocaml/xapi/xapi_vm.mli
- ocaml/xapi/xapi_vm_lifecycle.ml
- ocaml/xapi/xapi_vm_migrate.ml
- ocaml/xapi/xapi_xenops.ml
Some commits for refactoring and suchlike, then the behaviour change.
This is an improvement but does not solve the problem completely: if a
clean shutdown or reboot is in progress on a VM on a slave then a hard
shutdown will cancel it, but then the VM does not shut down (but a
subsequent hard shutdown will work).
> SCTX-2115: Force lifecycle operations should cancel clean operations

- ocaml/client_records/records.ml
- ocaml/idl/datamodel.ml
- ocaml/xapi/network.mli
- ocaml/xapi/xapi_bond.ml
- ocaml/xapi/xapi_pif.ml
- ocaml/xapi/xapi_tunnel.ml
- ocaml/xapi/xapi_vlan.ml
Use fcoe_driver interface to identify fcoe capable NICs.
Capabilities field:
1) ["fcoe"] - represents NIC supports fcoe
2) [] - represents NIC doesn't support fcoe
Signed-off-by: sharad yadav <sharad.yadav@citrix.com>
> CP-12093: Add a new field "capabilities" to PIF record

- ocaml/test/test_pgpu.ml
- ocaml/test/test_pgpu_helpers.ml
- ocaml/test/test_vgpu_common.ml
- ocaml/test/test_vm_helpers.ml
- ocaml/xapi/xapi_pgpu_helpers.ml
When checking whether a VGPU can run on a PGPU, xapi now needs to check the VGPUs scheduled to run on that PGPU as well as the VGPUs already running.
> CA-174923: Fixes for VGPU capacity planning

- ocaml/xapi/message_forwarding.ml
This occasionally caused testcases failing. It was introduced by some last minute change after the review. I've run two rounds of the same test sequence to verify the fix works.
> CAR-483 bug fix

- ocaml/xapi/cli_frontend.ml
- ocaml/xapi/cli_operations.ml
The `type` field is mostly vestigial, there's no point in requiring
people to supply a value.
> xe: make 'type=<user>' the default on `xe vdi-create`

- ocaml/xapi/xapi_sm.ml
Previously we used the version field, which should be the version
of the plugin itself, not which version of the SMAPI it needs.
> Detect a SMAPIv3 plugin via the required_api_version field

- ocaml/xapi/xapi.ml
- ocaml/xapi/xapi_host.ml
- scripts/0001-Workaround-for-NVIDIA-330.patch
When a slave starts, it cannot learn its Host.ssl_legacy without using
an stunnel to contact the master to consult the database. Therefore a
locally stored copy is needed.
> CP-12512 Store copy of ssl_legacy in Inventory

- ocaml/xapi/storage_access.ml
- ocaml/xapi/storage_impl.ml
- ocaml/xapi/storage_impl_test.ml
- ocaml/xapi/storage_mux.ml
- ocaml/xapi/storage_proxy.ml
- ocaml/xapi/xapi_vdi.ml
This allows it to be converted into a simple Volume.stat in the
SMAPIv3 (no special support required)
This depends on [xapi-project/xcp-idl#81]
> Plumb VDI.introduce through the SMAPIv2

- scripts/init.d-xapissl
For incoming connections to XAPI, this commit implements the
recommendation from the Citrix security team that XenServer should
use only ciphersuite TLS_RSA_WITH_AES_128_CBC_SHA for TLSv1.2.
(The exception is when the host ssl-legacy setting is switched on for
backward compatibility).
This recommendation is based on a combination of criteria:
* technical (security) considerations
* legal considerations
* compatibility with third-party TLSv1.2 clients
This commit relies on a corresponding commit in another repository to
set the ciphersuite used for outgoing connections from xapi, so that
XenServer hosts will be able to communicate with one another.
> CP-13189 TLS ciphersuite TLS_RSA_WITH_AES_128_CBC_SHA

- ocaml/xapi/message_forwarding.ml
These must be executed on a host which has access to the SR, so the
SR metadata (if any) can be updated.
> CA-177052: forward VDI.set_name_label and VDI.set_name_description

- ocaml/xapi/message_forwarding.ml
enable_ha call passed wrong op:`ha_disable during assert_operation_valid
My Bad: During git rebase for PR https://github.com/xapi-project/xen-api/pull/2260 it had occurred.
> CA-177425: Fixing enable_ha call

- ocaml/xapi/cli_frontend.ml
- ocaml/xapi/cli_operations.ml
- ocaml/xapi/import.ml
- ocaml/xapi/xapi_dr.ml
`xe vm-import --metadata` now supports an optional `vdi:src=dest` rewrite map, like with storage migration.
In the rewrite rules, the source VDI is identified by:
- uuid
- SCSIid (in sm-config)
The destination VDI is identified by:
- uuid
- SCSIid (in sm-config)
If a rewrite doesn't match then the source VDI is identified by:
- SCSIid
- SR and VDI.location
- other_config:storage_migrate_vdi_map_key
> Allow disk ids to be rewritten during metadata import

- scripts/static-vdis
If the SM plugin exposes the capability VDI_ATTACH_ONLINE then we store
the SR and Volume URIs, and then call the regular SR.attach, Datapath.attach
and Datapath.activate functions.
This patch also fixes instances of `raise <raw string>` into
`raise Exception(<raw string>)`
> static-vdis: support SMAPIv3

- ocaml/xapi/quicktest.ml
- ocaml/xapi/quicktest_vdi_copy.ml
Some valid configurations don't have a default SR, so quicktest fall back to any other suitable SR. Note that the ISO SR is a bit of an anomaly because it supports the `VDI_CREATE` capability but is usually on read/only storage media. Even when not on read/only storage media, the `SR.content_type=iso` triggers different behaviour on import which we (in the quicktest test) want to avoid.
> quicktest: don't rely on the default SR

- ocaml/xapi/smint.ml
- ocaml/xapi/xha_statefile.ml
- allow HA statefiles on an SR if either VDI_GENERATE_CONFIG or
VDI_ATTACH_OFFLINE is exposed
- query SM features via the SM table rather than the SMAPIv1
hashtable
> Add capability VDI_ATTACH_OFFLINE

- ocaml/xapi/xapi_vdi.ml
Previously this happened in the SMAPIv1 plugins, but the SMAPIv3 doesn't
have an explicit notion of `introduce`, instead it just has `Volume.stat`
which will succeed if the `location` is valid.
> VDI.introduce: raise an exception if the `location` field already exists

- ocaml/xapi/xapi_sr.ml
The SMAPIv1 backends update all SR fields in `SR.scan`, whereas
the SMAPIv2 and SMAPIv3 clearly separate the `SR.scan` (list VDIs)
from the `SR.stat` (query SR properties). To avoid confusing clients,
the XenAPI `SR.scan` should do both functions.
> CA-174968: XenAPI SR.scan: call both SMAPI SR.scan and SR.stat

- ocaml/test/test_common.ml
- ocaml/test/test_vdi_allowed_operations.ml
- ocaml/xapi/xapi_sr_operations.ml
- ocaml/xapi/xapi_vdi.ml
- ocaml/xapi/xapi_vm_snapshot.ml
- Update `VDI.allowed_operations` after `VDI.create`: otherwise we can't destroy the disk immediately from XenCenter
- Use the `SM` table to drive `SR.allowed_operations`: otherwise the computations don't work for SMAPIv3.
> Fixes for VDI and SR allowed_operations

- ocaml/xapi/storage_access.ml
- ocaml/xapi/storage_impl.ml
- ocaml/xapi/storage_impl_test.ml
- ocaml/xapi/storage_mux.ml
- ocaml/xapi/xapi_xenops.ml
Rather than relying on the SMAPIv2 implementation storing the
persistent flag (via `VDI.set_persistent`) we pass it as an
argument to `VDI.epoch_begin` instead.
This depends on [xapi-project/xcp-idl#83]
> VDI.epoch_begin: add persistent argument

- ocaml/idl/datamodel.ml
We didn't need this before as all objects with allowed_operations and
current_operations had them from the beginning. Now we need defaults, as
these fields have been added to the pool object.
> CA-178276: Add defaults for allowed_operations and current_operations fields

- ocaml/xapi/storage_access.ml
- ocaml/xapi/storage_impl_test.ml
- ocaml/xapi/xapi_sr.ml
- ocaml/xapi/xapi_vdi.ml
For SMAPIv1 backends, there is no change: backends supply the uuid.
For SMAPIv2 and SMAPIv3 backends, the backend can supply a uuid which will then be used for the VDI's uuid. If nothing is supplied then a uuid will be generated as before.
This depends on [xapi-project/xcp-idl#85]
> Allow storage backends to supply a uuid (or not)

- ocaml/idl/datamodel.ml
- ocaml/xapi/cli_frontend.ml
- ocaml/xapi/cli_operations.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_vm.ml
- ocaml/xapi/xapi_vm.mli
This implementation does not yet do any useful actions, but it
enables the writing and testing of client code that calls the new
XenAPI function.
> CP-13241 Stub implementation of VM.xenprep_start (with CLI)

- ocaml/idl/datamodel.ml
- ocaml/test/test_common.ml
- ocaml/test/test_vgpu_common.ml
- ocaml/test/test_vgpu_type.ml
- ocaml/xapi/db_gc.ml
- ocaml/xapi/import.ml
- ocaml/xapi/xapi_pgpu.ml
- ocaml/xapi/xapi_vgpu_type.ml
Design: http://xapi-project.github.io/xapi/futures/vgpu-type-identifiers.html
> CP-12616: Use a string identifier to help uniquely identify VGPU_type objects

- scripts/OMakefile
Using IPROG results in logrotate.d/{audit,xapi} having execute
permissions. logrotate ignores these files.
> CA-179046: fix permissions on logrotate config

- ocaml/xapi/OMakefile
- ocaml/xapi/sparse_dd_wrapper.ml
- ocaml/xapi/storage_migrate.ml
- ocaml/xapi/xapi.ml
- ocaml/xapi/xapi_vm_migrate.ml
This was reported as "SCTX-2047: XenMotion fails due to a leaked storage datapath after SXM". The root cause of this issue was: if XAPI is restarted while a SXM is in progress, XAPI would totally forget about the fact that there is an unfinished SXM in progress. In these cases, there would be dangling sparse_dd processes and datapaths leaked around, which will forbid further operations on objects sharing the same resources. This pull req will persists the relevant SXM information and lets XAPI do the cleanup (if necessary) based on that during its startup.
> CA-166748: cleanup SXM after XAPI restart

- ocaml/xapi/xapi_vdi.ml
We already call the storage implementation to set the name label and
name description. We have to call VDI.update -> SMAPIv2 VDI.stat ->
SMAPIv3 Volume.stat to find out the value that 'stuck' (which may have
been truncated for example) and to update the xapi db accordingly.
> CA-177415: update VDI.name_label and name_description on changes

- ocaml/idl/datamodel.ml
Also set the default to "". This avoids having any cluster-stack specifics in
the datamodel.
> Improve API doc for pool.ha_cluster_stack field

- ocaml/xapi/rrdd_proxy.ml
Since change eae565f, starting a VM on a slave host has caused
a 'Pool_role.This_host_is_a_master' exception to be raised in
Rrdd_proxy.push_rrd.   The VM will start correctly, but no RRDs will
be available.
The exception is only raised when starting a VM on a slave.  In this case,
Rrdd_proxy.push_rrd incorrectly calls Pool_role.get_master_address, which
raises an exception when run on the master.  Rrdd_proxy.push_rrd is only
ever run on the master, so the exception is always raised when starting
a VM on the slave.
> CA-177513: Push RRDs to slaves correctly

- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_sr.ml
The longer the time between calling Storage_access.SR.scan and checking
the database to see what needs updating, the more time there is for
something to change behind the scenes - for instance, the SM GC could
call VDI.forget. Moving the SR.stat call means that this window is much
smaller.
> CA-178240: Shrink SR.scan race window

- ocaml/client_records/records.ml
- ocaml/idl/datamodel.ml
- ocaml/xapi/sm_exec.ml
- ocaml/xapi/smint.ml
- ocaml/xapi/storage_access.ml
- ocaml/xapi/storage_mux.ml
- ocaml/xapi/xapi_services.ml
- ocaml/xapi/xapi_sm.ml
The SM plugins can declare that they require a specific cluster stack;
we take note of this information.
This requires: [xapi-project/xcp-idl#87]
> CP-13697: record SM `required_cluster_stack`

- OMakefile
- configure.ml
- ocaml/idl/datamodel.ml
- ocaml/idl/datamodel_types.ml
- ocaml/idl/datamodel_utils.ml
- ocaml/idl/ocaml_backend/OMakefile
- ocaml/idl/ocaml_backend/gen_empty_custom.ml
- ocaml/idl/ocaml_backend/gen_server.ml
- ocaml/idl/ocaml_backend/server_helpers.ml
- ocaml/xapi/api_server.ml
- ocaml/xapi/cli_frontend.ml
- ocaml/xapi/cli_operations.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_extensions.ml
- ocaml/xapi/xapi_extensions.mli
- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_pool.ml
- ocaml/xapi/xapi_pool.mli
- scripts/OMakefile
- scripts/extensions/Test.test
- xapi.spec.in
A XenAPI extension implements a single XenAPI call, outside of xapi. The extension can either be
- *declared*: represented in the data model as a message, with `forward_to` set. This is preferred since it formalises the argument types, result types, documentation strings, acceptable errors, lifecycle and ensures first-class support in the SDK
- *undeclared*: an API which isn't declared in the datamodel can still be invoked, if the implementation is found to be present at runtime.
If an *undeclared* API is created then the definition *must* still be added to the master branch, so that future builds of the SDK will include it. The useful thing is that the very same undeclared API *implementation* can be added to an older dom0 (e.g. in another RPM) and will work. Hopefully for a lot of …
> CP-12901: add a notion of XenAPI "extensions"

- ocaml/xapi/dbsync_slave.ml
- ocaml/xapi/xapi_globs.ml
- scripts/xapi.conf
A failing dbsync causes xapi not to start, which makes the system
unmanageable. Before this patch the only way to skip part of the
dbsync wa to add a pool other-config key; however this is not much
good if xapi won't start and the database is offline.
After this patch you can add
disable-dbsync-for=sync_pgpus sync_foo sync_bar
in /etc/xpai.conf to fix this problem.
> Add dbsync-exception list to the config file

- ocaml/xapi/pciops.ml
- ocaml/xapi/xapi_globs.ml
- scripts/xapi.conf
This will make it easier to run xapi on systems which adhere to the
FHS.
> Allow the xen-cmdline path to be set via the config file

- ocaml/xapi/cli_operations.ml
- ocaml/xapi/storage_access.ml
- ocaml/xapi/storage_access.mli
- ocaml/xapi/storage_impl.ml
- ocaml/xapi/xapi_sr.ml
All `SR.probe` calls now go through the SMAPIv2, allowing SMAPIv3 implementations to support probe.
Note we now have 2 probe result formats:
1. old raw arbitrary xml
2. structured XML as defined in `Storage_interface.probe_result`
The new structured XML format allows the CLI to properly understand the pretty-print the results.
> CP-13525: plumb through SR.probe

- ocaml/idl/datamodel.ml
- ocaml/xapi/xapi_pool.ml
- ocaml/xapi/xapi_pool.mli
Same for Pool.disable_ssl_legacy.
This is so that an API client calling one of these functions can
assume that if its SSL/TLS connection is closed by the server, all
hosts in the pool have been updated.
Also some datamodel changes for the ssl_legacy items:
* Improve (add to) documentation strings.
* Lifecycle change: they are now Published (not Prototyped).
> CP-13830 Pool.enable_ssl_legacy: change master last.

- ocaml/xapi/sm_exec.ml
The low-level SM code can only throw exceptions declared in the
`Storage_interface` module; everything else is converted into an
`Internal_error`. In particular the code must throw `Backend_error`
instead of `Server_error` directly to avoid unnecessary wrapping.
This fixes `xe sr-probe` which relies on the error message not
being wrapped.
> CA-180531: Throw `Backend_error` instead of `Server_error` in SM

- ocaml/xapi/dbsync_master.ml
- ocaml/xapi/sm_exec.ml
- ocaml/xapi/storage_access.ml
- ocaml/xapi/storage_access.mli
- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_pbd.ml
- ocaml/xapi/xapi_sm.ml
- scripts/xapi.conf
- xapi.spec.in
This adds an SM whitelist to xapi.conf and allows configuration file fragments in /etc/xapi.d/conf to override it.
This will need [xapi-project/xcp-idl#86] to actually work.
> Add an SM whitelist

- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_xenops.ml
- scripts/xapi.conf
The tapdisk3 polling feature will use new xenstored keys as parameters, populated by XAPI from configuration obtained from the following sources, in priority order:
- other-config:polling-idle-threshold and other-config:polling-duration from the corresponding VBD record
- xapi.conf's default-vbd3-polilng-idle-threshold and default-vbd3-polling-duration
- xapi_glob's internal constants default_vbd3_polling_idle_threshold and default_vbd3_polling_duration
There's also range protection that defaults to a sensible default value acceptable to tapdisk3 in case the result from the sources above specify an out-of-range value.
> CAR-1935: VBD other-config polling keys with default values

- scripts/xapi-logrotate
On CentOS 7 the syslog daemon is not called syslogd. The convention is
to get the PID from syslogd.pid which is populated by whatever daemon
is actually running.
> CA-180767: fix postrotate action

- ocaml/xapi/xapi_xenvmd.ml
> CP-13881: Xenvmd config files are in a new location

- scripts/xapi.conf
Without this the plugin won't show up in the SM list.
> CA-181227: add 'lvmofcoe' to sm-plugins list in xapi.conf

- ocaml/xapi/xapi.ml
- ocaml/xapi/xapi_sr.ml
1) This new thread will run on each host.
2) Thread will update physical utilisation only for SR
which has SR_STATS capability and sr-master.
Duplicate of https://github.com/xapi-project/xen-api/pull/2352
> CP-13493: Thread to update xapi db for physical utilisation of SR

- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_xenops.ml
When doing a VM.suspend we know "exactly" how much space is going to be used by the operation. We should therefore fully inflate the VDI to its virtual size to avoid the dynamic allocation overhead.
> CP-13468: Eagerly allocate (fully inflate) suspend VDIs

- ocaml/xapi/cli_operations.ml
This makes it easier to identify if the found SR is the one you want.
> CP-13525: Print the SR `name_label` and `name_description` in `probe`

- scripts/xapi.conf
If a plugin is whitelisted but doesn't actually exist, xapi assumes it
is a SMAPIv2 plugin and hangs forever trying to query it. This needs
fixing before we can whitelist rawhba.
This reverts commit a6c4b58277e0f7da6c7e464f0613fd9c12e0d01c.
> Revert "CA-180871: Whitelist the rawhba SR"

- scripts/perfmon
This introduces a new class of Monitor in perfmon since now there is
a first-class SR RRD type.
There is currently just one variable that can be monitored, physical
utilisation. A special consolidation function has been specified to calculate
the percentage usage based on the absolute datasource values `size` and
`physical_utilisation`.
The SR can have alerts enabled for it in the usual way by setting the
other-config:perfmon key to an XML configuration for the object required. In
this case the `name` is `physical_utilisation`. The `alarm_trigger_level` can
be specified as a float between 0.0 and 1.0 which defaults to 0.8.
For example, to receive alerts when the physical utilisation of the SR goes
above 70%, set the SR config key as follows:
$ CONFIG='<config><variable><name …
> CP-13494: perfmon: Monitor and alert for SR space

- ocaml/xapi/message_forwarding.ml
Also same for VM.hard_reboot.
When Message_forwarding.VM.hard_shutdown cancels other tasks such as
clean_shutdown, now it uses a fresh subtask for each cancellation,
instead of doing the cancellation more directly.
This fixes a bug: if a clean_shutdown task was in progress on a VM on
a slave, then VM.hard_shutdown invoked via "xe vm-shutdown --force"
would fail after cancelling the clean_shutdown. This was because when
the call to the slave (to cancel the clean_shutdown) completes, it
marks the task running it as completed successfully. Since this task
was the main task for the hard_shutdown, the waiter in cli_operations
noticed and destroyed the task, logging out the corresponding xapi
session and telling xe that the command had succeeded. Therefore when …
> CA-182595 VM.hard_shutdown: use subtask for cancelling

- ocaml/xapi/cli_frontend.ml
- ocaml/xe-cli/newcli.ml
This reverts commit ed6840d8ac3e89d5e4a62fb09b2bcc9cb78e6909.
This patch was unescaping escaped values on the CLI, causing problems
with the XenRT RBAC tests.
> CA-182869: Revert "CAR-1744: Escape the value strings passed between xe command and CLI server"

- ocaml/xapi/xapi_dr_task.ml
- ocaml/xapi/xapi_dr_task.mli
- ocaml/xapi/xapi_pool_helpers.ml
- ocaml/xapi/xapi_pool_helpers.mli
Previously the PBDs were plugged in whatever order they were returned by
Db.Host.get_all.
Since commit 5b6d293 PBDs for shared SRs cannot be plugged on slaves
unless they are already plugged on the master.
> CA-180653: Plug PBDs on master first during DR_task.create

- scripts/xapi-logrotate
Allow logrotate to rotate xensource.log when smaller than 16M.
This will keep size of live logs smaller.
Signed-off-by: Salvatore Cambria <salvatore.cambria@citrix.com>
> CA-180727: let xensource.log rotate when smaller than 16M

- ocaml/xapi/xapi_host.ml
Newly created host will be marked as enabled=false till
Xapi is starting on the host.
Once Xapi startup sequence is running, Initialising storage step
will mark host as enabled=true.
> CA-178795: Set the newly created host record as enabled=false

- ocaml/idl/datamodel.ml
- ocaml/xapi/cli_frontend.ml
- ocaml/xapi/cli_operations.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_host.mli
> CP-14229: Remove old CPU levelling functions from datamodel and CLI

- scripts/static-vdis
org.xen.xcp.storage doesn't exist anymore, which causes static-vdis to fail
when working on SMAPIv3 volumes.
Signed-off-by: Robert Breker <robert.breker@citrix.com>
> CA-184494: Make static-vdis refer to org.xen.xapi.storage for SMAPIv3

- ocaml/xapi/xapi_pif.ml
- ocaml/xapi/xapi_pif.mli
FCoE boot from SAN NIC should be made un-pluggable.
This commit extends pif scan routine to set disallow-unplug=true for all
fcoe boot from SAN interfaces.
Signed-off-by: Anoob Soman <anoob.soman@citrix.com>
> CP-14151: Extend pif scan to set disallow-unplug=true fcoe bfs interfaces

- ocaml/test/OMakefile
- ocaml/test/test_printers.ml
First pass adds printers for basic types and combinators for
lists, arrays, pairs and association lists.
> test: Add printer combinators to use with Test_highlevel

- scripts/set-hostname
Since CentOS 7 hostnamectl tool is used to configure hostname.
> CA-185036: Set hostname with hostnamectl.

- ocaml/test/test_vdi_allowed_operations.ml
- ocaml/xapi/xapi_vdi.ml
This isn't needed on all SR types, but is for some. Longer term plan is to have the SM backends expose a capability saying whether this is necessary or not.
> CA-145540: Restrict VDI snapshot during VDI copy

- ocaml/xapi/xapi_vdi.ml
VDI.introduce should not be accepted by toolstack if the location is
not unique in the SR. However, if a VDI is being introduced with the
location being same as that before, then it should be allowed.
This is required in the case, where VDI.introduce is used to set the
VDI.managed = true, for e.g., in iSCSI SR
> CA-183547: Allow VDI.introduce if the location is not unique in the SR except the VDI in question

- ocaml/test/test_helpers.ml
- ocaml/test/test_highlevel.ml
- ocaml/test/test_http.ml
- ocaml/test/test_map_check.ml
- ocaml/test/test_pgpu_helpers.ml
- ocaml/test/test_platformdata.ml
- ocaml/test/test_pool_license.ml
- ocaml/test/test_sm_features.ml
- ocaml/test/test_storage_migrate_state.ml
- ocaml/test/test_vgpu_type.ml
- ocaml/test/test_xenopsd_metadata.ml
With this change, OUnit reports each testcase, rather than
only reporting groups of tests created by Test_highlevel
modules.
> Test_highlevel: Make test families for highlevel tests

- ocaml/xapi/xapi_globs.ml
- scripts/xapi.conf
ibft-to-ignore is now renamed to bfs-interface and it returns space
separated list of IBFT NICs and FCoE boot from SAN NICs.
Signed-off-by: Anoob Soman <anoob.soman@citrix.com>
> Rename ibft-to-ignore script to bfs-interface.

- ocaml/xapi/cpuid_helpers.ml
- ocaml/xapi/cpuid_helpers.mli
- ocaml/xapi/create_misc.ml
To support VMs migrated from hosts that do not support the new CPU levelling
("levelling v2"), the `host.cpu_info:features` key is set to (approximately)
what it would be on such hosts.  To do this, we take the HVM features of the
host, and add in any features that we don't care about for migration, such that
the absence of such features will not cause a migration to be disallowed from
the sender.
> Support SXM from pre-levelling-v2 hosts

- ocaml/xapi/cli_protocol.ml
- ocaml/xapi/sparse_encoding.ml
Change the locally defined << and >> operators to <<< and >>>.
For consistency, also change definitions of && and ||.   This avoids
a clash with Camlp4's quotation markers and allows us to use bisect on
these files.
> Fix operators which clash with Camlp4 quotation markers

- ocaml/xapi/helpers.ml
- ocaml/xapi/xapi_dr_task.ml
Since 3378d71 attempting to unplug a master PBD for a shared SR while
slave PBDs are stil plugged raises an error.
> CA-187174: Unplug master PBDs last during DR_task.destroy

- ocaml/test/test_cpuid_helpers.ml
- ocaml/test/test_printers.ml
- ocaml/xapi/cpuid_helpers.ml
- ocaml/xapi/cpuid_helpers.mli
- ocaml/xapi/xapi_vm.ml
Almost 100% coverage - missing the invalid CPU features don't care mask and remote host compatibility cases for assert_vm_is_compatible.
> Improve unit test coverage for cpuinfo_helpers

- ocaml/xapi/create_misc.ml
Xapi_message.create cannot be called directly on a pool slave, so
Message.create calls need to go to the master.
> create_misc: always create Messages through the high-level API

- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/pciops.ml
- ocaml/xapi/pciops.mli
- ocaml/xapi/vgpuops.ml
- ocaml/xapi/vgpuops.mli
- ocaml/xapi/xapi_vgpu.ml
- ocaml/xapi/xapi_vm.ml
- ocaml/xapi/xapi_xenops.ml
Make vGPU -> pGPU allocation consistent with VM -> host allocation, in that all reservations are made on the master, via the `scheduled_to_be_resident_on` field, with the global lock held.
Manual tests run in a pool of two hosts with one K1 board each:
* Bootstorm 16x K160q-equipped VMs
* Bootstorm 8x K1 passthrough VMs
Automated tests run:
* dundeevgpuk1func.seq
> CA-115552: Move VGPU reservation to the master

- xapi.spec.in
xen-ocaml-devel provides the Xenctrl module, amongst other things.
> xapi.spec: Add build-time requirement on xen-ocaml-devel

- ocaml/xapi/xapi_vm_lifecycle.ml
For operations
suspend, checkpoint, pool_migrate, and migrate_send
on running HVM guests with no valid PV drivers version,
we now require the "feature-suspend" flag from the guest.
This reverses the spirit of commit
55c412107bb82b06c1158798096e75168a659d45
> CP-14154: Check feature-suspend for some operations

- ocaml/idl/datamodel.ml
- ocaml/xapi/xapi_xenops.ml
Pending implementation of a new design for the feature, this commit
disables it so that all VMs will have only the old set of emulated
PCI devices.
> CP-14781: disable auto_update_drivers feature

- ocaml/xapi/message_forwarding.ml
These messages confusingly appeared in the logs as
```
Caught exception while <exception> in message forwarder: <task>
```
> Fix some confusing Message_forwarding log messages

- scripts/perfmon
There is an optimisation for configuring SR IO throughput alerts in perfmon:
Since commit 9a4ce078b (CP-2190), you can add perfmon config
`sr_io_throughput_total_per_host` to the SR record in prefrence to adding
`sr_io_throughput_total_<uuid>` to each of the host records.
This patch makes the recently added SRMonitor ignore this configuration option
on the SR record since it cannot process it.
Moving the processing of `sr_io_throughput_total_per_host` to the SRMonitor was
considered but it is not possible since the monitors of each kind only process
RRDs of the same kind (e.g. VM, Host, and now SR) and these throughput RRDs are
actually Host RRDs.
This allows IO throughput alerts to be configured on SRs that export SR RRDs
(currently just the new thinly-provisioned block SR) and also use …
> CA-188565: perfmon's SRMonitor should ignore IO throughput

- ocaml/xapi/create_misc.ml
During rolling pool upgrade, an upgraded host may see cpuinfo
records from older hosts when trying to update the pool feature
level.   These records won't have the expected feature keys and
should be ignored.
> CA-188665: Ignore cpuinfo from older hosts during RPU

- ocaml/xapi/create_misc.ml
When a pre-levelling-v2 host is asked to storage-migrate a VM to
a post-levelling-v2 host, the older host will compare its local CPU
features to the 'features' flag sent by the new host.   The new host
must send its features key in the old, pre-levelling-v2 format so that
the older host can understand it.
> CP-14811: Support SXM from pre-levelling-v2 hosts

- ocaml/xapi/quicktest_lifecycle.ml
Xenctrl.Halt has always been incorrect in the libxc bindings (and should have
been Watchdog).  This was fixed upstream in
http://xenbits.xen.org/gitweb/?p=xen.git;a=commitdiff;h=87a16694248e80195943741bb9f857edd6a6bf51,
but subsequently causes a compilation error in xenopsd.
Instead of shutting the domain down with a Watchdog signal, use Poweroff.
This fixes the build against upstream Xen.
Signed-off-by: Andrew Cooper <andrew.cooper3@citrix.com>
> Correct the use of Xenctrl.Halt

- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_mgmt_iface.ml
- scripts/xapi.conf
File /etc/issue needs to be updated with latest management ip
on performing management_interface re-configure.
This can be achived by running update-issue service.
> CA-180495: Run update-issue service on management_interface re-configure

- scripts/mail-alarm
> CA-183272: Improving Dom0 mem usage alert mail text

- ocaml/idl/api_errors.ml
- ocaml/idl/datamodel.ml
- ocaml/xapi/xapi_vm_migrate.ml
Cross-pool vm-migration must be blocked if VDIs are on rawHBA
source SR or VDIs going to be mirrored to rawHBA destination SR.
> CA-119941: Block vm-migration if VDIs are on rawHBA SR

- ocaml/xapi/xapi_ha.ml
We were raising an error in `ha_prevent_restarts_for` if HA was not
enabled, but this is a valid thing to do (what if someone is about to
enable HA?) and we were hitting the error when migrating a VM between
pools when neither pool had HA enabled but the VM had `ha_always_run`
set to `true`.
> CA-189075: allow HA pause even if HA is disabled.

- ocaml/xapi/xapi_vm_migrate.ml
We disallow 'downhill' migrations from newer hosts to older hosts.
The check for such downhill migrations should be made first as later
checks might try to access of newer record fields which aren't available
on the older host, leading to runtime errors.
> CA-189736: Check for downhill migrations first

- ocaml/xapi/message_forwarding.ml
Previously, we would upgrade a VM's CPU flags before asking the host on
which it was resident to migrate it.  If the older host tried to read
the CPU flags while preparing to migrate the VM, it would see new-style
feature flags, which it could not understand, causing it to raise an
exception.
Now, we upgrade the CPU flags after the VM has been migrated.   During an
upgrade, if the VM does not have appropriate feature flags, xenguest
will give it maximum features for the destination host, then Xapi will
apply proper new-style features which will be used for all subsequent
migrations.   The older host will never see the new-style features.
> CA-192191: Upgrade CPU flags after domain has migrated

- ocaml/xapi/cli_operations.ml
In the implementation of the xe vm-install command, just before the
call to VM.provision, we attempt to set VM.has_vendor_device to the
value from the VM.recommendations field (defaulting to false if not
specified in the recommendations xml).
If the licence feature-set does not permit setting has_vendor_device,
we write a warning to stderr and continue the installation without
setting that flag.
> CP-14791: vm-install: apply vendor-device recommendation

- ocaml/idl/api_errors.ml
- ocaml/idl/datamodel.ml
- ocaml/xapi/xapi_vm_migrate.ml
Reverts xapi-project/xen-api#2529
This needs to come out so that QA can adapt their test cases.
Also we need to make sure that we don't require a VIF map for intra-pool migration.
> Revert "CA-187693: Handle unmapped VIFs and VDIs correctly"

- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_vm.ml
With the delays called in Message_forwarding, they occur before the task finishes when running on a master but after the task finishes when running on a slave. This leads to inconsistent behaviour when starting and shutting down VM appliances, which watch for their subtasks to complete.
> CA-192884: Move start/shutdown delays to Xapi_vm

- ocaml/xapi/xapi_vgpu_type.ml
GVT-g is now always enabled, independent of whether the device is hidden
from xen/dom0.
Passthrough of Intel GPUs still requires the device to be hidden from
both xen and dom0.
> CA-193817: Allow GVT-g even when device is hidden from xen/dom0

- ocaml/xapi/xapi_vm_migrate.ml
> CA-191048: Reword 'VIF map not allowed for intra-pool' migration message

- ocaml/xapi/xapi_vbd_helpers.ml
- ocaml/xapi/xapi_vif_helpers.ml
VBD plug must fail gracefully when VM undergoing operations
like clean_shutdown, hard_shutdown, pause and suspend.
> CA-187691: VBD plug must fail under certain VM Lifecycle operations

- ocaml/xapi/xapi_vm_migrate.ml
During RPU: When vm-migrate is in progress and storage backend
losses connection to host. In such case xapi must handle
Storage_backend_error.
> CA-186212: Handle Storage_backend_error during vm-migrate

- ocaml/xapi/xapi_vm.ml
In Xapi_vm.assert_can_set_has_vendor_device, we were raising an
exception if the PV drivers were in use.  Now we do this check only
if the new value of has_vendor_device is different to the old one.
> CA-194089: allow no-op VM.set_has_vendor_device

- ocaml/xapi/db_gc.ml
For example when a host leaves the pool, the dom0 console records remained.
> CA-175354: GC console records when VM is destroyed

- ocaml/client_records/record_util.ml
- ocaml/client_records/records.ml
- ocaml/idl/datamodel.ml
- ocaml/xapi/import.ml
- ocaml/xapi/xapi_guest_agent.ml
- ocaml/xapi/xapi_vbd_helpers.ml
- ocaml/xapi/xapi_vif_helpers.ml
- ocaml/xapi/xapi_vm_helpers.ml
Where an HVM guest has specified that it does or does not support
hotplug of VIF or VBD, we use this to decide whether to allow the
relevant operations.  Otherwise, we fall back to the old heuristic
of allowing them iff the guest has announced a PV driver version.
> CP-15277: allow vif|vbd hotplug if guest claims support

- ocaml/xapi/cli_operations.ml
An improvement to the message that is written to stdout (and to
the log) by the vm-install CLI implementation when the VM template
recommends has-vendor-device=true but the host's licence does not
permit this setting.
> CA-195668: Better text if licence forbids recommendation

- ocaml/xapi/xapi_fuse.ml
XenServer has moved the firstboot service to systemd and this does not support
arbitrary actions. As such, when we eject from a pool, calling `service
firstboot activate` does not work.
The package has been revised and we now need to call the script directly
(rather than exercise via `service`) and the verb has been changed to be more
semantically meaningful: from `activate` to `reset-and-reboot`.
> CA-195644: Handle the change in the xs-firstboot package

- OMakefile
We need this because mutable Strings are deprecated.
> Remove warning 3 (deprecated feature)

- scripts/init.d-xapi-domains
In some cases when there are running VMs on a remote filesystem like NFS
and the host is rebooted, the NFS mount is unmounted before xapi-domains
has run (to move or shutdown the VMs). The unmount fails because it is
in use. Later, after all processes have been killed, unmount is
attempted again which causes the host to hang because the network has
been shutdown.
To prevent the hang, add a dependency for xapi-domains on $remote_fs.
This means that during shutdown, xapi-domains will run before remote
filesystems are unmounted. The unmount will then succeed, preventing the
reboot from later hanging.
> CA-196701: Prevent hang during host shutdown

- ocaml/xapi/xapi.ml
- ocaml/xapi/xapi_globs.ml
- scripts/init.d-xapissl
- scripts/xapi.conf
Instead of being hard-coded in the Stunnel library module, these are
read from xapi.conf and passed to the Stunnel module on xapi start-up.
Compiling the new code relies on a corresponding change to the Stunnel
module in the xen-api-libs-transitional repository.
> CP-14531: Configurable outgoing TLS ciphersuites

- scripts/init.d-xapissl
- scripts/xapi.conf
For both incoming and outgoing TLS connections through
stunnel, when the host is not in ssl-legacy mode, the one
permitted ciphersuite uses SHA-256 rather than SHA-1 now.
(Also removed MD5 from the list of ciphersuites permitted
for outgoing stunnel connections when in ssl-legacy mode.)
> CP-14530: SHA-256 not SHA-1 for TLS (non-legacy)

- scripts/OMakefile
- scripts/xapi-logrotate
- scripts/xapi-logrotate.conf
- scripts/xapi-logrotate.cron
- scripts/xapi-logrotate.sh
- xapi.spec.in
A new cron job calls a new shell-script which calls logrotate
with a new configuration file (based on the old one).
The job runs once per minute, and as well as rotating daily,
it rotates if the file is larger than 100M.
> CA-195429: logrotate xensource.log when over 100M

- scripts/mail-alarm
Making the encoding used in email alerts configurable using the pool other_config key `mail-charset`.
Signed-off-by: Rob Dobson <rob.dobson@citrix.com>
> CP-16038: Adding support for switching the supported character set for mail alarms

- ocaml/xapi/xapi_vm_migrate.ml
- ocaml/xapi/xapi_xenops.ml
This pull request addresses several issues with the handling of events between Xapi and Xenopsd.
Prior to this patch series there were some race-conditions on error paths that could cause 2 domains to be concurrently running for the same VM due to events being missed by Xapi and Xapi not syncing with events before doing lifecycle operations.
Among the commits in this pull-request, these are the ones that are of most interest with respect to re-gaining thread safety:
4486f94: CA-195652: Stack with_events_suppressed calls …
cd12c21: CA-195652: Sync with Xenopsd events after suppression …
b5ff609: CA-195652: Cause Xenopsd to cleanup before creating new domains …
e768829: CA-195652: Wait for events to be un-suppressed after suppression …
f6b51b3: CA-195652: Refresh VM after re-enabling events …
> CA-195652: Cause Xenopsd to cleanup before creating new domains

- ocaml/xapi/xapi_vm_migrate.ml
- ocaml/xapi/xapi_xenops.ml
By waiting for event suppression to finish in set_resident_on,
localhost migration was deadlocking because pool_migrate_complete
was called with events suppressed on the sender, and this was
in turn calling set_resident_on.
This fix simply ignores event suppression during set_resident_on,
which is safe because we only call set_resident_on when the VM
is just starting, and so we should be protected by the VM's
current_operations.
> CA-197914: Avoid deadlock by ignoring suppression in set_resident_on

- ocaml/xapi/import.ml
- ocaml/xapi/importexport.ml
- ocaml/xapi/xapi_db_upgrade.ml
This is needed because the default value for VM.has_vendor_device
defined in the datamodel is used in two places:
* When upgrading the database from a version that lacks the field
(where we want it false)
* When VM.create is called without specifying the field
(where we want it true).
Therefore this new database upgrade rule sets has_vendor_device=false
for each VM, if the upgrade is from a version that lacks the field
(determined by checking whether it is a pre-dundee version).
> CA-197067: DB upgrade rule: has_vendor_device=false

- ocaml/xapi/xapi_sync.ml
- ocaml/xsh/xsh.ml
When synchronising non-database data across the pool, now
we honour xapi's ssl_legacy and ciphersuites settings.
> CA-198283: Configure Stunnel in xsh for host-sync

- ocaml/xapi/xapi_vm_migrate.ml
Boston doesn't call 'migrate_complete', and hence we need to do
a bit extra on the memory image handler.
> CA-198613: Fix RPU from Boston

- scripts/mail-alarm
Triggering at 0 is often used by QA to test things, and the
email generated under this condition (and only under this
condition) was just incorrect.
> CA-201311: Fix email alert text when trigger level is 0

- scripts/mail-alarm
Before this patch, emails would come in unformatted like the following:
From: noreply@dt04
To: simon.beaumont@citrix.com
Date: Tue, 1 Mar 2016 17:34:00 +0000
Subject: [dt04] XenServer Message: VM 88eea7dc-6b81-4a1e-a43d-86b3eb097fd5
ALARM
Field           Value
-----           -----
Name:           ALARM
Priority:       3
Class:          VM
Object UUID:    88eea7dc-6b81-4a1e-a43d-86b3eb097fd5
Timestamp:      20160301T17:33:53Z
Message UUID:   4116332a-995e-57d1-a318-c9c06a08c918
Pool name:      dt04
Body:
Parameter=log_fs_usage
Value=0.040000
Alarm trigger value=0.0
Alarm trigger period=0
Now they come in formatted like this:
From: noreply@dt04
To: simon.beaumont@citrix.com
Date: Tue, 1 Mar 2016 17:39:56 +0000
Subject: [dt04] XenServer Alarm: Log partition nearly full on "Control domain
on …
> CA-201093: mail-alarm: Add formatter for log partition usage alerts

- ocaml/xapi/xapi_vif.ml
The address is given in CIDR format, so we need to extract the IP bit before
comparing it to the allowed IP addresses.
> VIF.configure_ipv{4,6}: fix locking check

- ocaml/xapi/xapi_vm_migrate.ml
The last_boot_CPU_flags field of a VM that is migrated to a newer-version host
in another pool (SXM) was not updated in the xapi DB. This would not make the
migration itself fail, because the receiving xenopsd upgrades the featureset
itself before restoring the domain. However, after the migration, xapi would
overwrite the featureset in xenopsd's VM metadata with the one from the xapi
DB, which was still out-of-date. For this reason, a following reboot may fail.
This patch ensures that the last_boot_CPU_flags field is updated immediately
after a cross-pool migration finishes, in the pool_migration_complete call.
> CA-203414: Upgrade CPU features in pool_migrate_complete after SXM

- ocaml/xapi/xapi_sr_operations.ml
The cumulative effect of these patches is to improve the time to create a large number of XenDesktop-like VMs from 4 days to 16 hours.
> CA-202385: reduce duration of VDI operations when there are many existing VDIs

- ocaml/xe-cli/newcli.ml
Calling the parameter ssl-legacy means it's impossible to set the host
field Host.ssl_legacy via the CLI - xe consumes the parameter rather
than passing it on to xapi.
> CA-204263: Rename xe parameter ssl-legacy to allow-ssl-legacy

- ocaml/xapi/xapi_xenops.ml
The 2 caches (xapi and xenopsd) should be populated whenever there
is metadata in xenopsd. This fix populates it at start-of-day
by asking xenopsd which VMs it knows about, and prevents premature
removal of the caches. Previously the 'maybe_cleanup_vm' function
was removing the caches whether or not it managed to cleanup the
VM from xenopsd.
The caches are now removed in only one place - when the VM metadata
is removed from xenopsd.
> CA-200924: Avoid premature cache invalidation

- ocaml/database/db_xml.ml
If during development you accidentally added a field to a table in the xapi
database that is no longer in the schema, you'll get a cryptic Not_found
exception during xapi startup. This patch helps debugging by making it more
obvious what went wrong.
Signed-off-by: Jonathan Davies <jonathan.davies@citrix.com>
> Aid DB unmarshalling debugging

- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_vm.ml
Failing to do this has caused problems as it violates the principle that there should only be one operation per VM talking to xenopsd at a time.
> CA-204474: Wait for cancelled operations to finish before proceeding with hard shutdown/reboot

- ocaml/test/OMakefile
- ocaml/test/suite.ml
- ocaml/test/test_vm_migrate.ml
- ocaml/xapi/xapi_vm_migrate.ml
This is a subset of the changes from #2594
> SXM: Carry out the VDI/VIF map checks in assert_can_migrate

- ocaml/idl/datamodel.ml
- ocaml/xapi/xapi_db_upgrade.ml
We already had a DB upgrade rule to set VM.has_vendor_device to false
on upgrade from a pre-Dundee version of the DB schema.
Now instead of "pre-Dundee", the rule is applied if the schema version
is older than the first tech-preview in which the has_vendor_device
field controlled the presence of the device. (In the previous schema
version and tech preview, the field was present but had no effect.)
> CA-205589: Preserve has_vendor_device on DB upgrade

- ocaml/idl/datamodel.ml
- ocaml/test/test_common.ml
- ocaml/xapi/create_misc.ml
- ocaml/xapi/create_misc.mli
- ocaml/xapi/dbsync_slave.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_host.mli
- ocaml/xapi/xapi_pool.ml
A new ssl_legacy parameter for the Host constructor message.
When a host is joining a pool and calls that constructor on the pool
master, supply the ssl_legacy parameter so as to maintain the existing
value.
> CA-206602: Preserve Host.ssl_legacy on pool-join

- ocaml/client_records/records.ml
- ocaml/database/db_xml.ml
- ocaml/idl/datamodel.ml
- ocaml/xapi/import.ml
- ocaml/xapi/xapi_db_upgrade.ml
- ocaml/xapi/xapi_guest_agent.ml
- ocaml/xapi/xapi_vm.ml
- ocaml/xapi/xapi_vm_helpers.ml
- ocaml/xapi/xapi_xenops.ml
Track the value of PV_drivers_detected returned from xenopsd rather than deducing this as "storage_paths_optimized" and "network_paths_optimized" from the xenstore data exported from xenopsd.
> CA-203169: let xenopsd work out whether PV drivers are detected

- ocaml/xapi/xapi_pool.ml
When a host is about to join a new pool, it tells its soon-to-be new
pool-master to create a Host DB entry for it; now the host tells the
master to set the Host.ssl_legacy the same as the new master's value
(rather than preserving the host's value).
Also the host updates its local (non-DB) setting so that on next xapi
start (before it contacts the master to query the DB) it will use the
new setting.
> CA-208614: On pool-join, copy ssl_legacy from master.

- ocaml/xapi/message_forwarding.ml
Without this, the VGPU will be (incorrectly) accounted for in PGPU free
space calculations, even though the VM is not running or starting up.
> CA-209507: Clean up VGPU.scheduled_to_be_resident_on if VM.start fails

- scripts/poweron/iLO.py
The iLO plugin was just using the defaults from the M2Crypto
python library (which wraps OpenSSL).
Now we enforce TLS (no SSL) and specify a list of ciphersuites.
> CA-209875: iLO plugin: TLS-only, set ciphersuites.

- ocaml/xapi/xapi_udhcpd.ml
The advertising of the routers (gateway) can be disabled by setting an
other-config key on the HIMN. The meaning of this key was accidentally reversed
in 090dd2cf408c50930f547dac4aa4c759373a376f.
> DHCP on HIMN must advertise routers by default

- ocaml/xapi/pciops.ml
- ocaml/xapi/pciops.mli
- ocaml/xapi/xapi_pci.ml
- ocaml/xapi/xapi_pci.mli
This means that the VM.attached_PCIs will be updated when the VM is
started and shutdown and this will inform the VM.allowed_operations.
For example, VMs with PCI-passthrough (using the other-config:pci key)
will have the same operation restrictions as a VM using GPU-passthrough
(previously the only class of managed PCI device). Presently the
operations restricted based on attached PCI devices are:
* suspend
* checkpoint
* pool_migrate
* migrate_send
> CP-17469: Treat all known PCI classes as managed

- ocaml/xapi/sparse_dd_wrapper.ml
Enable TLSv1.2 capability for sparse_dd.
> CA-208537: vdi-copy between local SRs proposes unwanted ciphers

- ocaml/idl/datamodel.ml
- ocaml/idl/ocaml_backend/taskHelper.ml
- ocaml/idl/ocaml_backend/taskHelper.mli
- ocaml/xapi/xapi_task.ml
There is a requirement from vm scheduled snapshot to
create and destroy task while running vmss policy.
Before destroying the Task, It must be marked as
`success or `failure. For that we need to expose an API
set_status.
> CP-16190: Add an API to set the status of Task

- ocaml/xapi/xapi_vm_snapshot.ml
For VSS snapshot taken from VMSS policy `is_vmss_snapshot` field
must be set to True.
> CA-207565: Update `is_vmss_snapshot` field for VSS snapshot

- ocaml/idl/datamodel.ml
> Improve API doc of VM.affinity

- ocaml/xapi/xapi_xenops.ml
Xenopsd is responsible for sorting out the defaults and there's a good
reason to leave it empty as it enables QEMU's ExtendedKeyEvent
extension (see https://github.com/xapi-project/xenopsd/pull/272).
> CP-17631: Don't default HVM keymap to en-us

- ocaml/xapi/xapi_vm_migrate.ml
> CA-199734: best-effort DP destroy and other cleanups for mirror/copy task failures

- ocaml/test/test_vdi_allowed_operations.ml
- ocaml/xapi/helpers.ml
- ocaml/xapi/import.ml
- ocaml/xapi/memory_check.ml
- ocaml/xapi/memory_check.mli
- ocaml/xapi/xapi_vm_helpers.ml
- ocaml/xapi/xapi_vm_migrate.ml
Commit 54933c4 excluded domain zero from the `is_hvm` check as a special case.
This was only added to placate a test case which had not correctly used
the dom0 record for plugging a dummy VBD to dom0. In general we don't
want this commit because it breaks VM.import because it cannot get the VM record for the incoming VM from the database because, by definition it is not there yet.
This pull request reverts 54933c4 and fixes the offending test-case to get domain zero's VM record properly. Previously it was using `Test_common.make_vm` which created a HVM record which was then subject to PV driver checks for the VBD allowed-operations.
> CA-214015: Don't check for domain zero in is_hvm

- ocaml/xapi/xapi_network.ml
When two threads try to bring up the same internal bridge (which can happen if
we boot two VMs attached to the same internal network in parallel), there is a
chance of confliction as bridge creation steps are not atomic.
Signed-off-by: Zheng Li <dev@zheng.li>
> CA-213224: Avoid concurrent internal bridge creation

- ocaml/xapi/xapi_vm_snapshot.ml
Restore VM power state before raising an exception for
checkpoint failure.
> CA-213568: Restore VM power state on checkpoint failure.

- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_xenops.ml
Xenopsd has the ability to handle paths to block devices in dom0 which
don't require Xenopsd to do a SMAPI attach and activate.
We now trigger this functionality based on the a VBD.other-config field.
> CP-17923: Conditionally set Xenopsd Vbd.backend to Local

- xapi.spec.in
This commit removes tetex-latex as a build dependency. The dependency
isn't required and causes 95 latex-related RPM packages to be installed
at build time (representing about 25% of all packages at build time).
> CP-18021 remove dependency on tetex-latex

- ocaml/xapi/dbsync_master.ml
The usual form for the console URL is:
https://<host-ip-address>/console?ref=<console-ref>
However, when the host doesn't have an IP address because, for example,
the host management network has been disabled, then the console URL
becomes
https:///console?ref=<console-ref>
which doesn't make sense. It doesn't make sense, either, to maintain the
IP address that the host _used_ to have because this IP might be in use
somewhere else if, for example, there was a DHCP server running on the
network.
This patch sets the location URL to the empty string if the host doesn't
have an address on the network.
> CA-105021: Set Console.location to empty if Host.address is empty

- ocaml/xapi/message_forwarding.ml
create_vgpus could fail if vGPU is not licensed. The VM must not be
left marked as scheduled_to_be_resident_on a host, or it will be
considered to be taking up space on that host.
> CA-207577: clear scheduled_to_be_resident_on if create_vgpus fails

- scripts/10resetvdis
Since xapi's DB GC's logic to determine whether a host has failed takes a while
to see the first heartbeat from each host, it calls the
host-post-declare-scripts with reason="assume-failed" on each host.
This means that the "assume-failed" logic is called for every slave after every
toolstack start on the master.
Even if "assume-failed" is used on appropriate occasions, resetting the VDIs is
still dangerous because any VMs running on a slave will be treated as not being
attached, which can cause the SM layer to make invalid assumptions, possibly
leading to data loss and corruption.
Signed-off-by: Jonathan Davies <jonathan.davies@citrix.com>
Reviewed-by: Alex Brett <alex.brett@citrix.com>
> CA-214975: don't reset VDIs on assume-failed

- scripts/static-vdis
The static VDI config file includes the SR's device_config, the contents
of which is dependent on the SR type. This change allows the static-vdi
script to handle unicode characters in device_config.
> CA-216244: Handle unicode characters in static VDI config

- ocaml/idl/api_errors.ml
- ocaml/idl/datamodel.ml
- ocaml/test/OMakefile
- ocaml/test/suite.ml
- ocaml/test/test_no_migrate.ml
- ocaml/test/test_platformdata.ml
- ocaml/test/test_xapi_xenops.ml
- ocaml/xapi/OMakefile
- ocaml/xapi/vm_platform.ml
- ocaml/xapi/xapi_vm.ml
- ocaml/xapi/xapi_vm_lifecycle.ml
- ocaml/xapi/xapi_xenops.ml
The check is a little more exhaustive: Migration, suspension, and checkpointing must be blocked if either nested virtualisation is active or platform:nomigrate is true. This can be overridden with --force. The commit contains unit tests.
_This commit will be updated to use a library function that interprets boolean values from platform flags._
> CP-18173 add check to vm lifecycle: no migration when using nested virt

- ocaml/idl/api_errors.ml
- ocaml/idl/datamodel.ml
- ocaml/test/OMakefile
- ocaml/test/suite.ml
- ocaml/test/test_no_migrate.ml
- ocaml/test/test_platformdata.ml
- ocaml/test/test_xapi_xenops.ml
- ocaml/xapi/OMakefile
- ocaml/xapi/vm_platform.ml
- ocaml/xapi/xapi_vm.ml
- ocaml/xapi/xapi_vm_lifecycle.ml
- ocaml/xapi/xapi_xenops.ml
This PR implements checks about VM mobility based on values in the platform flags. Originally we intended to test the platform flags as recorded in the immutable last-booted record. It turns out that XAPI doesn't maintain this properly. We now check the current platform flags for the decision about mobility.
The problem is that a user can manipulate the platform flags after booting in a way that suggests to Xapi that a VM is mobile when it is not by setting `platform:nested-virt:false`.
> CP 18173 - check platform flags to decide mobility of VM for Bromium

- ocaml/idl/datamodel.ml
- ocaml/idl/datamodel_types.ml
- ocaml/idl/ocaml_backend/gen_server.ml
- ocaml/xapi/cli_frontend.ml
- ocaml/xapi/cli_operations.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_host.mli
- ocaml/xapi/xapi_pool.ml
The current design for CAR-2245 assumes that a client can perform update operations on both master and slaves. It would be preferable to implement the server-side behavior as a XAPI extension (to enable it to be easily updated).
This PR is to allow XAPI extensions to be invoked on a specific host.
> CP-18024: Allow XAPI extensions to be invoked on a specific host

- ocaml/xapi/message_forwarding.ml
Recent changes to forward_vm_op meant that this function no longer raises the
power-state exception that VM.query_data_source relies on, so we add they
assertion back but in query_data_source itself.
Other function that use forward_vm_op have any power-state checks done already
as part of with_vm_operation, but VM.query_data_source was an exception.
> Assert that a VM is running or paused in VM.query_data_source

- ocaml/xapi/message_forwarding.ml
In SMAPIv3 plugins model, SR should own its own metadata rather than relying on
the central xapi database. As such, the setting of name_lael/description of a
SR should be forwareded to the host where the SR is currently in use.
> CA-216934: forward name_label/description setting to the right hosts

- ocaml/idl/datamodel.ml
- ocaml/xapi/cli_frontend.ml
- ocaml/xapi/cli_operations.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_bond.ml
- ocaml/xapi/xapi_network_attach_helpers.ml
- ocaml/xapi/xapi_network_attach_helpers.mli
- ocaml/xapi/xapi_vif.ml
- ocaml/xapi/xapi_vif.mli
- ocaml/xapi/xapi_vm_helpers.ml
Add vif-move command, including sanity checking that the
requested network can be seen from the host running the VM (if it's running)
Replaces https://github.com/xapi-project/xen-api/pull/2697
Signed-off-by: Bob Ball <bob.ball@citrix.com>
> CA-215192: Expose vif-move to the CLI

- ocaml/test/OMakefile
- ocaml/test/suite.ml
- ocaml/test/test_features.ml
- ocaml/xapi/features.ml
- ocaml/xapi/pool_features.ml
I have tested this by removing the `restrict_xen_motion` key from the `license_params` of the slave in a two-host pool. It used to be `restrict_xen_motion = "false"`, i.e. XenMotion is enabled, on both the master and slave. Then I checked the resulting value of `pool.restrictions`. Before the patch, `pool.restrictions` had `restrict_xen_motion = "true"` (i.e. XenMotion disabled). With the patch, it correctly had `restrict_xen_motion = "false"`.
> CA-212079: Allow XenMotion and AD during RPU from pre-Dundee

- ocaml/license/license_init.ml
- ocaml/test/mock.ml
- ocaml/test/suite.ml
- ocaml/xapi/cancel_tests.ml
We no longer support versions of OCaml which don't have this operator
in the standard library.
> Remove local definitions of the |> operator

- xapi.spec.in
This is a dependency to build https://github.com/xapi-project/xen-api/pull/2735
Signed-off-by: Marcus Granado <marcus.granado@citrix.com>
> CAR-2259: add ocaml-sha-devel dependency to xapi

- ocaml/test/OMakefile
- ocaml/xapi/OMakefile
- ocaml/xapi/stream_vdi.ml
- opam
This patch series adds some vhd-tool VDI import and export performance features to Xapi to improve its VM import and export performance. This is considered a better option than calling vhd-tool from Xapi, because adding Xapi VM import and export features to vhd-tool is considerably more difficult and error-prone.
The resulting VM import and export performance in Xapi is better than the corresponding VDI import and export performance in vhd-tool, for the same amount of VDI data:
| Time for a 10GiB VDI with random data | `xe vm-export`                         | `vhd-tool export` | `xe vm-import`                         | `vhd-tool import` | 
|---------------------------------------|----------------------------------------|-------------------|----------------------------------------|--------- …
> CAR-2259: Faster VM import and export

- scripts/xapi.service
This reverts commit dce1cc044d931b1fe89721c9471034e5ea882321.
That commit made xapi stop when xcp-rrdd stops, which we don't want. Also it
didn't fix CA-219717, which was actually a problem in the relationship between
xcp-rrdd and forkexecd.
> Revert "CA-219717: make xapi require xcp-rrdd"

- scripts/xe-toolstack-restart
Other daemons (xapi, xcp-rrdd) require forkexecd to stop properly.
Having "systemctl restart" was causing race condition when other daemons were
trying to spawn a subprocess while forkexecd was not running.
We split "systemctl restart" into two separate stop - start steps and extract
forkexecd to stop as the last process and start as the first process in the queue.
Signed-off-by: Rafal Mielniczuk <rafal.mielniczuk@citrix.com>
> CA-219717: xe-toolstack-restart: Stop forkexecd as a last service

- ocaml/xapi/xapi.ml
- scripts/xapi-autostart-vms
Update openvswitch configuration only after the `xenbr*` bridges are configured, avoiding many backtraces.
Use `xe` filtering capabilities to avoid an innocuous backtrace in the logs.
> CP-18710 - Eliminate spurious stack traces from log files

- scripts/host-backup-restore/host-backup
`xe host-backup` invokes an external script (`host-backup`) that terminates successfully also when some of its subcommands fail. This may leave the backup in a partially corrupted state.
As an example, the following is extracted from a log: `host_backup succeeded - returned: tar: -: Wrote only 4096 of 10240 bytes#012tar: Error is not recoverable: exiting now.`
>  CA-220154 - host-backup can fail silently and be considered successful

- ocaml/license/OMakefile
- ocaml/license/v6daemon.ml
- ocaml/license/v6daemon.mli
Remove the daemonisation and watchdog code now that were are using systemd.
Systemd will do all the forking and watching for us.
The rest of the code in v6daemon.ml will go away once we move v6d to xcp-idl.
> CA-218103: v6: don't daemonise

- ocaml/xapi/cli_operations.ml
- scripts/xe-set-iscsi-iqn
This is a minor fix to avoid a parameter lookup that was generating spurious backtraces in the log files. 
While investigating this I've noticed that only some of the error messages where explicitly identifying which key was the cause of the error, so I added the information to the other error messages as well.
> CP-18759 - Eliminate spurious stack traces from log files (2)

- ocaml/client_records/records.ml
- ocaml/idl/datamodel.ml
- ocaml/test/test_no_migrate.ml
- ocaml/xapi/create_misc.ml
- ocaml/xapi/dbsync_master.ml
- ocaml/xapi/monitor_master.ml
- ocaml/xapi/xapi_vm.ml
- ocaml/xapi/xapi_vm_clone.ml
- ocaml/xapi/xapi_vm_lifecycle.ml
- ocaml/xapi/xapi_xenops.ml
When a VM starts, xenopsd records the current values of `platform:nomigrate` and `platform:nested_virt`. These are reported to xapi via xcp-idl. This PR adds code to xapi to pick up these values (as well as the value of `hvm`) and to store them in the `VM_metrics` class. The values of `nomigrate` and `nested_virt` are used in `xapi_vm_lifecycle.ml:is_mobile` to decide the mobility of VMs in the Bromium context. Previously this code used the actual values from `platform`, which is wrong because it can be manipulated over the lifetime of the VM.
I have manually verified on a DT machine that indeed the values are picked up by xenopds when a VM boots, are reported correctly and indeed block migration of VMs.
> CP-18294/Bromium maintain nested_vir, nomigrate, hvm as reported by xenopsd

- ocaml/xapi/xapi_xenops.ml
When updating the MTU of a `VIF` it can happen that the VM `domid` is still out of sync and consequently the computed device id is wrong.
We can use the correct device value passing it via `xenopsd` as a field in `VIF.stat`.
See also: 
xapi-project/xcp-idl#131
xapi-project/xenopsd#288
> [CP-18781] Use the correct vif device id in set_MTU or fail

- ocaml/xapi/quicktest.ml
- ocaml/xapi/xapi_event.ml
Avoid returning duplicate events in event.from. This PR also adds a test for this in quicktest.
> CA-122248: Avoid returning duplicate events in event.from

- ocaml/client_records/records.ml
Signed-off-by: Frezzle <frederico.mazzone@citrix.com>
> CA-220170: Fix ha-network-peers CLI field showing hosts as "not in database"

- ocaml/idl/datamodel.ml
- ocaml/xapi/features.ml
- ocaml/xapi/features.mli
- ocaml/xapi/xapi_vm.ml
Do not merge this until the feature has been added to the relevant licence definitions.
As it is, this will build but then any installed XenServer will not permit the use of the function.
> CP-18919: Licence-control VM.set_VCPUs_number_live

- ocaml/xapi/xapi_xenops.ml
This allows the update process to complete.
We could alternatively check for `gm = Ref.null` in `update_pv_drivers_detected`, or ignore any error as done later at line `1514` (although I would rather change that and add a debug line also at that stage). 
> When GuestMetrics are NULL, `update_vm` is partial

- ocaml/idl/datamodel.ml
- ocaml/xapi/xapi_vm_lifecycle.ml
- ocaml/xapi/xapi_vm_memory_constraints.ml
- ocaml/xapi/xapi_xenops.ml
> The toolstack shall not allowed the setting of a dynamic memory range on a VM configured with nested virt (i.e. it will enforce memory dynamic-min = dynamic-max = static-max)". 
The PR prohibits to set memory limits when a VM uses nested virtualisation. However, I'm not sure that I cover all cases here and I'm inviting @jonludlam in particular to review this. Currently the only VM operation being blocked is `changing_dynamic_range`.
As part of this I slightly refactored the `is_mobile` predicate which is also used in the context of limiting VM operations for Bromium VMs.
The PR includes a unit test.
> CP 18860 - Restrict setting memory limits for Bromium VMs

- ocaml/xapi/xapi_xenops.ml
Reverts xapi-project/xen-api#2781, because it seems to have caused a regression (CA-223387), and there are plans to do this differently anyway.
> Revert "When GuestMetrics are NULL, `update_vm` is partial"

- xapi.spec.in
> CA-223671: Don't run xapi-domains.service with restart on %postun xapi-core rpm.

- ocaml/graph/graph.ml
- ocaml/xapi/vhd_tool_wrapper.ml
- ocaml/xapi/workload_balancing.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_pif.ml
- ocaml/xapi/xapi_templates.ml
- ocaml/xapi/xapi_vm.ml
- ocaml/xapi/xapi_vm_migrate.ml
- ocaml/xapi/xapi_vm_snapshot.ml
- ocaml/xapi/xapi_xenops.ml
Replace all assert statements with appropriate `Server_errors` carrying enough information for debugging.
> [CA-223800] Fix xapi-xenopsd assert-statements

- ocaml/xapi/xapi_guest_agent.ml
- ocaml/xapi/xapi_vm.ml
- ocaml/xapi/xapi_xenops.ml
Generate the VM guest metrics during the VM start, making sure that the cache and the PV driver detection is kept up to date. This should help avoiding spurious errors related to VM guest metrics missing references and should also help to solve some issues related to the clean shutdown of HVM linux guest without the guest tools (CA-224331).
> Create VM guest metrics on VM start

- ocaml/xapi/xapi_vbd_helpers.ml
- ocaml/xapi/xapi_vif_helpers.ml
- ocaml/xapi/xapi_vm_lifecycle.ml
If we detect a guest using PV drivers then we can assume it is safe to
hotplug and unplug VIFs and VBDs.
> CA-224331: Detect PV drivers => vif|vbd hotpluggable

- ocaml/xapi/OMakefile
- ocaml/xapi/pvs_cache_vdi.ml
- ocaml/xapi/pvs_proxy_control.ml
- ocaml/xapi/xapi_pvs_cache_storage.ml
PVS-cache supports a new kind of SR that is based on a RAM disk. A consequence
is that the contents of the SR disappear when the host is rebooted, while
leaving the VDI records behind in the database, and PVS_cache_storage.VDI
fields may be invalid.
To handle this, we now check whether the PVS_cache_storage.VDI that is needed
when a PVS-cached VM is started still actually exists. If not, it will be
recreated. Furthermore, in PVS_cache_storage.destroy, we ignore errors about
the VDI not existing anymore.
> CA-224975: PVS-cache: Handle cache VDIs on non-persistent SR

- ocaml/xapi/xapi_guest_agent.ml
Systemd naming scheme standard changed to support a broader range of interface names. This was to improve the stability of interfaces' naming across reboots and hardware changes. For reference see: https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames
This PR adds the support for the new network interface names and allows their extraction from xenstore paths, so that the `networks` field of the `VM guest metrics` contains the correct informations.
> CA-189725: support new systemd network interfaces naming in the VM guest metrics

- ocaml/idl/datamodel.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_vbd.ml
VBD.unplug_force() and VBD.unplug_force_no_safety_check() are identical.
Now the latter is simply another name for the former rather than an
identical implementation.
> VBD.{unplug, unplug_force_no_safety_check}: remove code duplication

- ocaml/client_records/records.ml
- ocaml/idl/datamodel.ml
`VDI.parent` field was never set to anything. 
It's not used, SM currently sets `VDI.sm_config["vhd-parent"]` to the parent VDI instead.
> CA-148930: mark VDI.parent as deprecated

- ocaml/xapi/xapi_mgmt_iface.ml
This commit addresses agetty being restarted so frequently that systemd
would block it. We now limit restarts to situation where we know that
the IP address has changed. This should bring down the frequency.
> CA-224335 re-start agetty only after change of IP address

- scripts/examples/python/shutdown.py
- scripts/xapi-domains.service
The previous setting was 240s, which isn't enough for migrating VMs in worst
cases given our current support limit on host memory. This change increases the
uplimit and also adds some parametric flexibility to it.
Signed-off-by: Zheng Li zheng.li3@citrix.com
> CA-220275: increase host evacuation timeout during host shutdown

- scripts/extensions/pool_update.precheck
For livepatch precheck returns single string instead of structured
XML format, change the implementation accordingly.
> CA-227145: Parse return string of livepatch precheck.

- scripts/init.d-xapi
The start function in the init-script for xapi was writing
"Starting xapi: " with no newline on success, so the text
did not reach the logging system until the next stop; this
caused wrong and confusing logs.
Now the function emits a newline immediately before it
replaces itself with a xapi process.
> CA-227721: init-script: flush to log on xapi start

- ocaml/xe-cli/newcli.ml
When the CLI makes a TLS connection to a remote host as part of a
command, there was code to monitor the stunnel process and exit
early if the stunnel process died. There was a race, therefore,
when a TLS connection terminiated correctly but the command hadn't
finished processing on the control socket, for example, when
uploading a VDI via a CLI on a slave. This commit removes the active
monitoring of stunnel processes.
> CA-226177: Fix premature termination of cli

- ocaml/xapi/xapi_vm.ml
- ocaml/xapi/xapi_xenops.ml
This commit moves the memory limit check into VM.start where it can be
overridden using --force.
Signed-off-by: Christian Lindig christian.lindig@citrix.com
> CA-226028 support vm-start --force for memory limits under nested-virt

- scripts/extensions/pool_update.precheck
To ensure precheck can run more than once and return
the expected output, the precheck script should be
called in extension.
> CA-227145: Call precheck script in extension.

- scripts/xe-install-supplemental-pack
The problem here is that for code like
trap "xe update-pool-clean uuid=$update_uuid" EXIT ERR
trap "xe update-destroy uuid=$update_uuid" ERR
In testing, it will call xe update-destroy first.
After xe update-destroy, xe update-pool-clean will have no object to refer.
We expect the code will call pool_clean first then destroy.
But what we wrote in trap seems cannot make sure this sequence
> CA-228029: Fix update destroy failure in xe-install-supplemental-pack when exception happens

- ocaml/xapi/xapi_pool_update.ml
Remove any pool_patch objects that don't have a corresponding
pool_update object
> CA-226000: Old patches are not removed on Host Upgrade

- ocaml/xapi/xapi_pool_update.ml
> CA-229347: Pool_update.introduce doesn't need dom0 free disk space 3 times of the update size.

- ocaml/database/block_device_io.ml
- ocaml/database/redo_log.ml
1) Print the exception raised for `Redo_log.shutdown`.
2) Print the block device path while opening and closing it.
> CA-223461: Add more info to redo_log and block_device_io logging.

- ocaml/idl/datamodel.ml
- ocaml/xapi/cli_operations.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_ha.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_host.mli
- scripts/attach-static-vdis.service
- scripts/examples/python/shutdown.py
- scripts/xapi-domains.service
This is an alternative version of #2827.
It's slightly better as it doesn't hard wire the xhad (the default cluster-stack) commands. But it comes with the cost of adding an optional parameter to an existing API method.
> [For Review] CA-225070-v2: Refined order of xapi/xhad/attach-static-vdis start/stop

- ocaml/xapi/task_server.ml
If `check_cancelling` fails then `cancel_fn` called with `with_cancel`
is removed from Task cancel list and `cancel_fn` is never getting executed.
> CA-226280: Fix the `cancel_fn` call on failed `check_cancelling`.

- ocaml/xapi/monitor_dbcalls_cache.ml
- ocaml/xapi/monitor_pvs_proxy.ml
- ocaml/xapi/xapi_xenops.ml
These commits fix the problem that the xapi database would not contain the correct status of a PVS proxy.
The problem is rooted in a caching layer: the status as reported via RRD from PVS proxies is read into a cache. When the cache is updated, this update is propagated to the Xapi database. However, the Xapi database is updated only for attached proxies. This leads to an inconsistency: when the PVS Proxy reached the state of "caching" before it was attached, the Xapi entry would never be updated, staying in status "initialised". The problem is solved by invalidating the cache entry once the PVS proxy is attached. Now the current state is read into the cache and propagated to the Xapi database.
The commit contains code to validate the cache for debugging but it is currently disabled. When …
> CA-229176 fix PVS status cache incoherence - invalidate cache entry when attaching proxy

- ocaml/idl/datamodel.ml
- ocaml/xapi/cli_operations.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_host.mli
Revert the change to add the new API call that reports _all_ errors for an evacuation plan - it's just not correct, and we only really _can_ report one error per VM reliably.
Additionally, we were reporting the _wrong_ error when a VM wasn't migratable.
> CA-229331: Fixes to compute_evacuation_plan

- ocaml/xapi/cli_operations.ml
Return a URI that has the full master IP in it, so that it always works, even
when called on a pool slave.
> CA-232307: Fix xe pool-dump-database on slave

- ocaml/client_records/records.ml
> CA-233312: Hide VM's nested-virt and nomigrate fields from CLI

- ocaml/xapi/xapi_pool_update.ml
Db.VDI.destroy in Pool_update.pool_clean just removes the Xapi database record.
It should invoke Client.VDI.destroy instead and remove both the VDI and the database record.
> CA-233306: Delete the VDI when invoking Pool_update.pool_clean

- ocaml/xapi/cli_frontend.ml
- ocaml/xapi/cli_operations.ml
This fix reorders the checks when using the `host=` and `vm=` slectors in the calls to `xe host-...` and `xe vm-...` to make sure that the eventual call `get_by_uuid` is done only after `name-label` (and for hosts also `hostname`) has been checked first.
This avoid the appearance of a spurious backtrace. Also fixes a minor issue that could prevent a confusing lookup if `hostname` and `name-label` are out of sync (they are synced on start but `name-label` can be easily modified and this would not be reflected in the `hostname`).
> CA-227062: Fix cli selector fns for host, vm, sr

- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_vbd.ml
- ocaml/xapi/xapi_vgpu.ml
- ocaml/xapi/xapi_vm.ml
- ocaml/xapi/xapi_vm_lifecycle.ml
- ocaml/xapi/xapi_xenops.ml
> CA-228680: Improve error message when VM crashes before VM.start finishes

- ocaml/xapi/db_gc.ml
When RPU completes, db_gc.detect_rolling_upgrade should invoke
xapi_pool_update.resync_host to remove the old patch records.
> CA-234875: Remove old patch records after RPU completes.

- ocaml/xapi/xapi_xenops.ml
Most VM operations that change the power state of a VM include
assertions that the power state is indeed as expected after that
operation. Such a check can issue a false alarm in some cases and this
commit removes it from operations that change the power state to
"running":
* start
* unpause
* reboot
* resume
The problem is that these assertions are too naive when changing the
state into running: when a VM quickly changes its state once it is
running (e.g., by rebooting) the assertion can fail because it can be
too late and would find the VM not running as expected.
Assertions after operations that change the state away from running are
kept by this commit.
> CA-233915 remove some post-op assertions over VM power state

- Makefile
- xapi.spec.in
Use a larger minor version number to ensure that the ely-bugfix version
of xapi can increment the minor version number a few times before
collision - we have to ensure that the version number of xapi in the
master branch of xapi-project/xen-api is always higher than the one in
the ely-bugfix branch of xenserver/xen-api.
> Update xapi version number to 1.20.0

- ocaml/auth/extauth_plugin_ADpbis.ml
When user input username as "ChildDomain\Username", the original code
ignores "ChildDomain".
> CA-235358: Fix AD users in child domains cannot log in to XenCenter 7

- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_vm_helpers.ml
- ocaml/xapi/xapi_vm_lifecycle.ml
Also: allow operation start_on for control domains; ensure that a control domain
won't start on a host different from its affinity.
> CA-233580: allow control domains to start on disabled hosts.

- Makefile
- xapi.spec.in
To keep it in sync with the actual version of xapi. The version tag
v1.20.1 should be at this commit.
> Update version number in xapi.spec.in to 1.20.1

- ocaml/xapi/xapi_vm_lifecycle.ml
The `Rrdd.archive_rrd` operation could wait for a mutex or be stuck in IO operations for some time. In rare cases, this means that the power state (and allowed operations) informations in the database could be wrong for a long time.
By inverting the order of operations, we make sure that the potentially slow operation only happens  after the database state has been completely updated.
> CA-234510: update db before archiving rrd

- ocaml/idl/datamodel.ml
This commit marks fields and objects in the datamodel as deprecated that
are no longer updated because this functionality has been replaced by
RRD statistics:
* fields IO bandwidth as part of VIF_metrics, VBD_metrics, PIF_Metrics
* VIF_metrics
* VBD_metrics
* field vCPU utilisation as part of VM_metrics
* memory_free as part of host_metrics (was internally deprecated)
> CA-223868 deprecate fields that are superseded by RRDs

- scripts/extensions/pool_update.apply
The commit 76070441 causes yum to add 'update' to the list of
groups. Attempting to reinstall an update then fails to install the
payload packages because yum believes the group to still be present.
Marking the group as removed fixes this.
> CA-237415: remove update group from yum

- ocaml/xapi/xapi_vgpu_type.ml
If the Intel GPU BAR size is too small, the number of VGPUs per PGPU
could become zero and give rise to a division by zero.  This crashes the xapi initialisation leaving the server unresponsive. Currently the only solution was to figure out the issue and change the BIOS settings. 
The suggested fix adds an intermediate check to the VGPU generation code to prevent
the division by zero from happening and adds an explicative warning in the log files.
> CA-236863: division by 0 in VGPU-g detection

- opam
Add the missing xapi-test-utils OPAM dependency to the opam file. It is
declared as a "BuildRequires" in the spec file of xapi, but it was missing from
the opam file. With this dependency added, the OPAM build of xapi works again.
The corresponding PR for opam-repo-dev is https://github.com/xapi-project/opam-repo-dev/pull/127
> opam: add xapi-test-utils OPAM dependency

- scripts/examples/python/XenAPI.py
SSL verification is still enabled by default, but can be disabled by
developer for testing purposes by adding the optional parameter
`ignore_ssl` during the Session creation.
> CA-172901: XenAPI.py, make SSL verification optional

- ocaml/xapi/message_forwarding.ml
By design, an internal superuser session will be created and used for message
forwarding to slaves, so permission checking afterwards (i.e. where the message
is already forwarded) will always return success. So we should make the
permission checking right on the front.
CVE ID: CVE-2017-5573
Security Bulletin: CTX220112
> CA-232290: Task.cancel verify permission before forwarding

- ocaml/xapi/test_pool_update.ml
- ocaml/xapi/xapi_pool_update.ml
In the unit test, mock the function that gets free space of the filesystem to
avoid concurrency issues.
> Fix test_assert_space_available unit test

- scripts/extensions/pool_update.apply
If an existing update is upgraded (e.g. a device driver) it increases
its version number but retains its original name. When yum is asked to
install the update package it reports it as a no-op as a package of
that name is already present.
Using 'yum upgrade' instead makes upgrades behave as expected. Initial
installs continue to work as well.
> CA-241704: switch from 'yum install' to 'yum upgrade'

- ocaml/xapi/xapi_pool_update.ml
If db indicates an update is not applied to any host but the corresponding patch is applied
on some host(s), that means the RPU has completed and caused such inconsistency.
The update record should be removed.
The patch record will be removed along with the update record.
> CA-237165: Remove applied update records from Xapi db after PRU.

- ocaml/xapi/rrdd_proxy.ml
The function `Rrdd_proxy.push_rrd` is called from message_forwarding at the end
of a VM start or resume. It looks up the VM's host of residence, assuming the
VM is now running. If it has already crashed (for whatever reason), then the VM
isn't resident anywhere, and we should not attempt to push the RRD. The
start/resume call will still succeed in this case, because the VM crashed
_after_ starting/resuming it.
> CA-241301: Don't push RRD for VM if it is not running

- ocaml/idl/datamodel.ml
- ocaml/idl/datamodel_types.ml
- ocaml/xapi/test_common.ml
- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_pci.ml
- ocaml/xapi/xapi_vgpu_type.ml
- ocaml/xapi/xapi_xenops.ml
Extend datamodel.ml and xapi_vgpu_type.ml with the new items
that will be needed for running virtual GPUs on AMD MxGPU cards
> CP-20411: AMD MxGPU in datamodel and vgpu-type

- ocaml/xapi/helpers.ml
- ocaml/xapi/xapi_mgmt_iface.ml
Management interface must not be marked as up if IP is acquired
and physical connectivity is down.
This might be possible in case of static ip configuration.
> CA-223676: Check physical connectivity for management interface.

- ocaml/xapi/dbsync_slave.ml
- ocaml/xapi/pciops.ml
- ocaml/xapi/pciops.mli
- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_pci.ml
- ocaml/xapi/xapi_pci.mli
- ocaml/xapi/xapi_pgpu.ml
- ocaml/xapi/xapi_pgpu.mli
In a new function Xapi_pgpu.mxgpu_vf_setup (to be called on starting a
VM that uses a vGPU backed by an MxGPU physical device) we:
* ensure the kernel module (driver) is loaded,
* add database entries for the new PCI devices that appear for the
Virtual Functions, and
* link each of them to its Physical Function.
Incidentally add some utility functions:
* Picops.is_bdf_format
* Xapi_pci.get_local_pcis_and_records
* Xapi_pci.get_local_pci_refs
> CP-20432: MxGPU: Load kernel module; add VF pcis to DB

- ocaml/xapi/dbsync_slave.ml
- ocaml/xapi/xapi_pci.ml
- ocaml/xapi/xapi_pci.mli
- ocaml/xapi/xapi_pgpu.ml
- ocaml/xapi/xapi_pgpu.mli
In some functions that took a host parameter that had to be the
local host, I have removed that parameter and made the functions
call Helpers.get_localhost instead.
That get_localhost function has not been changed here: it looks
as if it could be optimised by using Xapi_globs.localhost_ref when
it has been set, but that approach causes failures in our current
test code.
> Remove some host params that have to be localhost

- ocaml/xapi/pciops.ml
- ocaml/xapi/pciops.mli
- ocaml/xapi/test_vgpu_common.ml
- ocaml/xapi/vgpuops.ml
- ocaml/xapi/xapi_pgpu.ml
- ocaml/xapi/xapi_pgpu_helpers.ml
- ocaml/xapi/xapi_vgpu.mli
- ocaml/xapi/xapi_vgpu_type.ml
- ocaml/xapi/xapi_vm_helpers.ml
Most of these patches refactor the current code, to make things easier to implement the final bits, and should by themselves not change anything. The real changes are in the commits marked with the CP-number. Next step: fix the race condition that exists when choosing free VFs.
> CP-20787: Allocate VF for MxGPU VGPU types when starting VM

- ocaml/xapi/pciops.ml
...except the one used in the new `is_bdf_format` function.
The older patterns are used in scanf calls where end-of-input match is not
appropriate.
> Pciops: revert to format strings without end-of-input match

- ocaml/xapi/xapi_pgpu.ml
PCI dependencies link PCI devices (or PCI functions, to be precise) that need
to be passed through to a VM together. The original use case for this was a GPU
card that had a video as well as an audio component, which belong together.
These two would always show up as two separate functions of the same device
on the PCI bus: xxxx:xx:xx.0 and xxxx.xx.xx.1. For this reason, the heuristic
that xapi uses to find dependent devices is based on their common
domain+bus+device parts (the xxxx:xx:xx portion of the bus address).
For SR-IOV devices, however, several virtual functions tend to have a common
domain+bus+device, which leads to all of those being marked as dependent on
each other, and all passed-through to the same VM. This patch fixes it by
extending the heuristic by marking all MxGPU VFs …
> CA-245332: Clear PCI.dependencies for virtual functions

- ocaml/xapi/xapi_vgpu_type.ml
XenCenter assumes 0 heads == passthrough.
Default to the same number of heads as shown for GVT-g (1).
Signed-off-by: Bob Ball <bob.ball@citrix.com>
> Set default heads to 1 for MxGPU

- ocaml/xapi-cli-protocol/OMakefile
Installing a library can fail if the directory is not created
ahead of it. This is now analogous to the OMakefile for the
other libraries.
> Add mkdir before doing ocamlfind install

- ocaml/xe-cli/bash-completion
When completing 'params', consider only one object to get the complete
list of possible params rather than all objects
> CA-246262: Bash completion performance fix

- ocaml/xapi/xapi_vm_helpers.ml
List.filter_map on VBDs for checking `on_boot=reset` in vdi sm_config
gives non empty list, incorrectly.
Fix it to use List.exists instead.
> CA-245811: Fix `assert_vm_supports_quiesce_snapshot` function

- ocaml/xapi/storage_migrate.ml
- ocaml/xapi/xapi_vm_migrate.ml
During SXM, we derive a VDI from its closet neighbour in order to do incremental copy. If this neighbour is larger in size, a failure will occur as we don't currently support VDI resize downwards. This PR fixes it.
> CA-247452: reorder the VDI copy sequence in SXM

- configure.ml
- scripts/Makefile
The install.sh script is used in scripts, hence the previous commit,
but it's also used elsewhere. This shifts the export command into
the config.mk makefile fragment that's included, making it work
everywhere where the variables are needed.
> Further BVT fixes

- scripts/extensions/pool_update.precheck
- scripts/plugins/disk-space
See the ticket for full explanation, but for Ely updates we will use the sum of the sizes of the packages in an update as the installation size, instead of the delta of the installed size from the last major release. Since that already represents the worst case space needed we dont't need to multiply it to calculate the required space now.
Justification for keeping the disk-space get_required_space method (which now just returns its args["size"]) is to avoid forcing XenCenter/the client to be aware of this change - they can continue calling the plugin with the new update size and it'll behave as expected.
Signed-off-by: Callum McIntyre <callum.mcintyre@citrix.com>
> [CP-21359] Remove the multiplier on update size calculations

- Makefile
- _oasis
- configure.ml
- ocaml/doc/branding.js
- ocaml/doc/jsapi.ml
- ocaml/doc/xenserver/branding.js
Also: updated branding for ely; modified jsapi.ml to accept the target directory
as a parameter.
> CA-248243: Include the html xenserver flavour of the docs in the build.

- scripts/plugins/openvswitch-config-update
1. When xapi restart, the plugin should report no change of SDN controller.
2. Do not print iptablectl output to ensure xapi correctly handles plugin output.
> CA-248125: Fix openvswitch-config-update plugin issue.

- ocaml/auth/libpam_stubs.clib
This file is generated by OASIS, so we don't need to keep it in version
control. I removed it by running the command
```
oasis setup-clean -replace-sections -remove
```
to clean up any files and sections generated by OASIS.
> Remove leftover file generated by OASIS

- ocaml/xapi/workload_balancing.ml
WLB return CanPlaceAllVMs to indicate all vms have
been placed on a host.
Currently, xapi thinks no recommendation is provided from WLB
if it detects CanPlaceAllVMs field.
This commit fix this error and let xapi ignore CanPlaceAllVMs since
xapi does not make use of it at all
> CA-241130: Retrieved recommendations not as expected

- ocaml/xapi/xapi_network.ml
This happens during the startup sequence, and fixes the fix for CA-248389.
> CA-248921: If there is no session in the context, assume it's internal

- ocaml/xapi/db_gc.ml
This reverts commit b21761ecf4b70e1ad9121c46fb9a8a127c4bf05f, because we
suspect that it introduced a regression.
> CA-248658: Revert "CA-247700: Don't GC VBDs that are currently attached"

- Makefile
Note that this breaks simple use of ocamlfind to build individual things, but that's easily fixed by running 'oasis setup' yourself.
> Avoid myocamlbuild.ml changing every time you build

- ocaml/xapi/taskHelper.ml
- ocaml/xapi/taskHelper.mli
- ocaml/xapi/xapi_xenops.ml
... as they are based on destructive operations, and might leave user with surprises once cancelled while progressing.
> CA-244659: Disable cancellation of some xapi tasks

- .travis.yml
Explicitly set XS branch name in .travis.yml, because the git branch name does not match the XS branch name in this
case. This will fix the Travis build as Travis will now use the correct
RPMs.
This commit depends on the PR https://github.com/xenserver/xenserver-build-env/pull/76, which makes it possible to use a git branch name that is different from the XS branch, and explicitly set it in the GIT_BRANCH environment variable.
> [MERGE xenserver/xenserver-build-env#76 first!!] Fix Travis build

- ocaml/idl/datamodel.ml
- ocaml/xapi-consts/api_errors.ml
- ocaml/xapi/create_misc.ml
- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_pool.ml
Removed comparison of host patches and implemented comparison on the api version
and database schema instead.
> New pool join rules to reflect ely changes in the updates.

- ocaml/xapi/helpers.ml
- ocaml/xapi/xapi.ml
- ocaml/xapi/xapi_mgmt_iface.ml
During xapi startup, the on_dom0_networking_change function does not
recognize the IP address change, as it gets set in the database at an
earlier startup phase. This commit adds an unconditional call to the
update_getty function during startup.
> CA-242706: call update_getty at xapi startup

- Makefile
To targets that need it and don't already depend on it transitively. Now
these targets, such as "make all", will work with a clean repo without
generated OASIS files.
> Makefile: add setup.ml prerequisite

- ocaml/database/db_cache_impl.ml
- ocaml/database/db_cache_types.ml
- ocaml/database/db_cache_types.mli
- ocaml/database/db_globs.ml
- ocaml/database/db_rpc_common_v1.ml
- ocaml/database/db_rpc_common_v2.ml
- ocaml/idl/ocaml_backend/gen_db_actions.ml
- ocaml/xapi/test_db_lowlevel.ml
- ocaml/xapi/xapi_globs.ml
This allows the DB add_to_map calls to be idempotent. So if a map contains:
```
[('key','value')]
```
then
```
add_to_map(x,'key','value')
```
will succeed if idempotency is enabled, and fail with `Duplicate_key` if not.
```
add_to_map(x,'key','value2')
```
will always fail with a `Duplicate_key` exception.
By default, this behaviour is turned on when xapi uses the remote DB access from slaves, but turned off on the master. This has the effect of ensuring that the Xen API calls retain their current semantics for now.
The behaviour can be normalised across master/slave via the config file parameter
```
db_idempotent_map
```
which currently defaults to `false`. This default will change at some point in the future.
> CA-171948: Adjust semantics of 'add_to_<map>' in Db layer

- ocaml/xapi/xapi_pool_patch.ml
> CA-249662: Pool_patch handler: If an SR is not specified, use default_SR

- ocaml/xapi/xapi_pool_update.ml
This change it to add a refresh after update been applied, so software version of:
xen_livepatches and kernel_livepatches
can update in time.
> CA-250757: refresh software version after update been applied

- ocaml/xapi/nm.ml
> CA-250748: MTU on pif does not always sync to xapi db

- ocaml/xapi/xapi_vm_migrate.ml
This is done after the assignment of a new PGPU for the VM (in case the VM has
a VGPU). The metadata update includes the PCI address of the PGPU on the
destination host, which gets passed by xenopsd on the sender to xenopsd on the
destination. If we don't do this, then the destination's xenopsd may have the
wrong PCI address when setting up the VGPU.
> CA-251254: Force a xenopsd VM metadata update before a pool-migration

- ocaml/xapi/xapi_gpumon.ml
- ocaml/xapi/xapi_gpumon.mli
- ocaml/xapi/xapi_pgpu.ml
A small optimisation: pass the appropriate value of
compatibility_metadata to the PGPU constructor, rather than creating
the object and then populating the field afterwards.
Doing this involved changing some of the underlying functions, and
we make fewer database lookups now.
Also the code now passes the correct debug-string to the xcp-idl
xmlrpc call that fetches the gpgu metadata.
Also removed some needless detail from a specified return-type in an
mli file.
> CP-20679: Optimise some bits, simplify others

- ocaml/xapi/wlb_reports.ml
This PR aim to fix a potential bug of WLB in xapi.
For more details please refer to CA-250858 and check the two test cases that created to reproduce and verify the fix of this issue.
> CA-250858: Fix bugs when cut out WLB health check report from WLB response

- ocaml/xapi/xapi_pgpu.ml
The code that fetched the pgpu metadata from the Nvidia driver was
assuming that this would always work for every GPU made by Nvidia.
In fact only some Nvidia GPUs support the feature, and even where
the feature is available, and the Nvidia driver has been installed
on the host, that Nvidia driver has not yet been loaded when xapi
starts on host boot.
Therefore this commit catches the exception
Gpumon_interface.NvmlInterfaceNotAvailable
and the exception handler returns and empty list for the metadata.
> CP-20679: cope when pgpu metadata is unobtainable

- ocaml/xapi/xapi_pgpu.ml
By managing additional unexpected failures. This should prevent failures to block xapi startup process
> CP-20679: improve safety of maybe_fetch_compatibility_metadata

- ocaml/xapi/xapi_gpumon.ml
- ocaml/xapi/xapi_gpumon.mli
This provides a safe way to pass the opaque blob as an ascii string and
avoid possible encoding issue in the serialization and deserialization
of the database field.
> CP-20679: Use base64 to encode and decode the `pgpu_metadata`

- .travis-opam-coverage.sh
- .travis-xenserver-build-env.sh
- .travis.yml
- opam
Add a new build to the build matrix that uses OPAM with the `xs-opam` repo & computes the coverage of the unit tests (without quicktests).
I kept the OPAM build simple, and did not make it general, it is only used for the coverage report.
> Send coverage to coveralls using OPAM Travis build

- ocaml/xapi/storage_access.ml
Some of the task names did not match the names of the invoked SMAPIv2
operation.
> Storage_access: fix task names to match called op

- README.markdown
Feel free to add or remove badges from this PR.
> README: add build, coverage, LoC badges

- ocaml/idl/datamodel.ml
We have been updating these two constants with every release,
but nothing has been reading them since 2009.
> Remove Datamodel.last_release_schema_m{aj|in}or_vsn

- ocaml/xapi/message_forwarding.ml
This ensures that resources, such as memory and space on a GPU, are allocated
and reserved on the destination host, during the migration.
> CP-13909: Call reserve_memory_for_vm for intra-pool VM.migrate_send

- ocaml/xapi/smint.ml
This is not used at all right now, and it seems that it was never used.
> smint.ml: Remove unused all_capabilites variable

- _tags
- ocaml/xapi/cli_operations.ml
- ocaml/xapi/xapi_vm_helpers.ml
- ocaml/xapi/xapi_xenops.ml
This PR introduces a minimal amount of changes to silence a new warning introduced in ocaml 4.03 that was previously breaking the build.
In most cases it was possible to refactor the code minimally and safely. For `cli_operations.ml` this was not possible and instead we are silencing the warning (and leaving a new comment mentioning the potential break in a future compiler -- newer than 4.05+).
> Make xapi compile with ocaml 4.03 and 4.04

- ocaml/xapi/cli_frontend.ml
- ocaml/xapi/cli_operations.ml
- ocaml/xapi/cli_util.ml
The `Import_raw_vdi` handler sets the wrong task to failed in case of errors: not the task we passed to it in the query, but a newly-created task. As a result, we cannot detect errors that happen in this handler on the CLI side, in the `Cli_util.track` function, when we call `xe update-updload`. This PR adds error checking to the CLI side, thereby fixing CA-253489, there will be a subsequent pull request to fix the task handling in the handler.
Please help with the style and wording of the error and help messages, thanks.
> CA-253489: xe update-upload: Add more error handling to the CLI

- ocaml/xapi/xapi_mgmt_iface.ml
To avoid bugs in the future in code relying on the correctness of that function.
> CA-242706: Add "warning" comment explaining issue

- ocaml/idl/datamodel.ml
- ocaml/idl/datamodel_types.ml
- ocaml/xapi/xapi_crashdump.ml
* Deprecate the `crashdump` XenAPI class
* Remove dead code and duplicated functions. (We don't really use this XenAPI class anyway.)
> Clean up & deprecate crashdump

- ocaml/xapi/xapi_vm_lifecycle.ml
Get rid of the unnecessary get_info function.
> Clean up Xapi_vm_lifecycle.check_operation_error

- ocaml/xapi/xapi_pool.ml
On Pool.eject, xcp-networkd startup creates bridges if management
bridge is present in inventory.
Then firstboot again tries to create PIFs and bridges.
This is a failure for management vlan case.
To fix this, we can avoid writing management bridge into inventory
and let the firstboot create the management pif and update the inventory.
> CA-255133: Pool.eject - Don't write bridge into inventory

- .travis-xenserver-build-env.sh
Export environmental variables instead of setting them for the first
script only with "env", because some of these variables are used by the
deploy.sh script too.
> build-env Travis job: fix documentation upload

- .travis-python-nosetests.sh
- .travis.yml
This PR includes the installation of `nose` and `python-mock` in Travis, and the execution of `nosetests` in `scripts/ scripts/examples scripts/examples/python`.
At the moment no test is present and no test is run. From now on, any python unittest dropped in such folders will be executed in the travis build.
Some example tests (with their travis builds) are available at https://github.com/mseri/xen-api/tree/test-nose.
We should consider running the python tests first, given how faster they are...
> Enable python tests

- ocaml/idl/datamodel.ml
- ocaml/xapi-consts/constants.ml
- ocaml/xapi/cli_operations.ml
- ocaml/xapi/import.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_pgpu_helpers.ml
- ocaml/xapi/xapi_pgpu_helpers.mli
- ocaml/xapi/xapi_vm_migrate.ml
- ocaml/xapi/xapi_xenops.ml
This PR also meant to address the potential issue discovered reviewing https://github.com/xapi-project/xen-api/pull/3058
However it looks like this was a non-issue, in the sense that a failure in calling `allocate_vm_to_host` during SXM migration would trigger the cleanup already in there, while a failure later on during the migration would anyway trigger the cleanup on the remote host that will take care of everything else.
This PR needs a small change to xapi-idl to introduce the other_config field to the vgpu interface, this is needed as temporary store to mimick the map functionality that we are already using for vifs and vbds.
> CP-22597: Add vGPU-to-GPU-group map to SXM migration

- ocaml/xapi/xapi_vdi.ml
Check the SM capability for VDI.snapshot the standard way, using the
check_sm_feature_error function.
> Xapi_vdi: clean up snapshot capability check

- ocaml/xapi/xapi_xenops.ml
These are not needed for the migration.
This PR goes with the corresponding changes to the idl: https://github.com/xapi-project/xcp-idl/pull/161
> Revert "CP-22597: xapi_xenops: add other_config parameter introduced in idl"

- ocaml/idl/datamodel.ml
> Update lifecycle for PVS classes

- .travis-opam-coverage.sh
By changing the owner of the /mnt directory containing the source from
root to the current user.
> Travis: fix the coverage build

- ocaml/xapi/suite.ml
- ocaml/xapi/test_xapi_vbd_helpers.ml
- ocaml/xapi/xapi_vbd_helpers.ml
VM should be able to reboot while migrating the VDI to another SR.
This PR contains:
* bugfix
* UT for bugfix
> CA-253933: VM cannot reboot when migrating to another SR

- ocaml/xapi/xapi_vm_lifecycle.ml
> Xapi_vm_lifecycle.check_operation_error: clarify comment

- ocaml/xapi/suite.ml
- ocaml/xapi/test_vdi_cbt.ml
These tests stub out a real SMAPIv2 storage server, by registering a
mock server with the Storage_mux multiplexer. So this means that the
SMAPIv2 calls will still go through Storage_impl.Wrapper and Storage_mux -
it is not possible to circumvent these without modifying xapi_vdi.ml,
because it directly uses Storage_mux.Server, which is basically
Storage_impl.Wrapper(Mux). However, by registering the mock server with
Storage_mux, we avoid the the Storage_access.SMAPIv1 server, which does
the SMAPIv2 -> SMAPIv1 translation.
> Add some CBT enable/disable tests

- ocaml/util/ocamltest.ml
- ocaml/util/ocamltest.mli
- ocaml/util/stats.ml
- ocaml/util/stats.mli
Please let me know if I removed something that's needed.
In the future we should completely get rid of the Ocamltest module, and move to the functions provided by alcotest/ounit, but this is a good first step towards removing that file.
> Remove dead code from ocaml/util

- ocaml/idl/datamodel.ml
- ocaml/xapi-consts/api_errors.ml
When disable external auth, although failed, the external auth been disabled.
So refine the error message.
> CA-187179: Refine error message of pool auth disable

- ocaml/idl/datamodel.ml
- ocaml/xapi/records.ml
- ocaml/xapi/test_common.ml
- ocaml/xapi/xapi_pool.ml
- ocaml/xapi/xapi_pool_update.ml
This commit adds an additional check before a host can join a pool.
The joining host compares its set of updates with the updates on each
host in the pool.  These sets must be equal for the host being able to join
the pool.  The comparison only considers updates that are marked as
enforce-homogeneity="true" in their update.xml definition -- see below.
This attribute is new. The absence of the enforce-homogeneity attribute
in an update defaults to enforce-homogeneity=false. This makes the code
backward compatible with updates that don't have this annotation.
Typically, code updates will have enforce-homogeneity=true but driver
updates will have enforce-homogeneity=false such that hosts in the pool
can have different sets of drivers but have the same code updates.
The implementation changes …
> [WIP] Add new pool join-check: pool and host must have same "enforced" updates

- ocaml/xapi/suite.ml
- ocaml/xapi/test_vm_check_operation_error.ml
- ocaml/xapi/xapi_vm_lifecycle.ml
And update the operations put into the `VM.allowed_operations` field by `VM.update_allowed_operations` - there were many VM operations missing that the function didn't even consider.
> Add some tests for Xapi_vm_lifecycle.check_operation_error

- ocaml/client_records/records.ml
- ocaml/idl/api_errors.ml
- ocaml/idl/datamodel.ml
- ocaml/idl/datamodel_types.ml
- ocaml/test/test_common.ml
- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_pool.ml
- ocaml/xapi/xapi_pool_update.ml
This is a backport from the master branch. The main difference is that we don't 
increment the API version because that would make it equal to the API version of
another release. It's also worth noting this commit replaces an existing overly
restrictive check with this new one.
This commit modifies checks before a host can join a pool.
The joining host compares its set of updates with the updates on each
host in the pool.  These sets must be equal for the host being able to join
the pool.  The comparison only considers updates that are marked as
enforce-homogeneity="true" in their update.xml definition -- see below.
This attribute is new. The absence of the enforce-homogeneity attribute
in an update defaults to enforce-homogeneity=false. This makes the code
backward compatible with …
> Backport: Add pool join check CP-23026: pool/host must have same "enforced" updates

- ocaml/idl/datamodel.ml
- ocaml/idl/datamodel_types.ml
- ocaml/xapi/xapi_pool.ml
This commit fixes an oversight: the new field in the API Pool_update.enforce_homogeneity was introduced for Honolulu, which must be defined first.
> CP-23026 mark new field 'enforce_homogeneity' as introduced in rel_honolulu

- ocaml/idl/datamodel.ml
The previous commit did not bump the database schema in the belief that
it would run into the version of the Falcon release. However, this is
not the case and it can be safely bumped as it should have been already.
> CP-23026 bump database schema to 5.109 after change

- ocaml/xapi/create_misc.ml
Function assert_db_schema_matches relies on the database schema version
being available from Client.Host.get_software_version. This commit adds
the code that puts it there. It is backported from the master branch.
> CP-23026 add database schema version to software_version ()

- ocaml/idl/datamodel.ml
- ocaml/idl/datamodel_types.ml
- ocaml/xapi/records.ml
- ocaml/xapi/test_common.ml
- ocaml/xapi/xapi_pool.ml
- ocaml/xapi/xapi_pool_update.ml
This commit reverts commits that together implement the pool join rules
that consider only "enforced" updates. This code will be added back once
automated testing is in place. See CP-23026 and CP-22959.
modified:   ocaml/idl/datamodel.ml
modified:   ocaml/idl/datamodel_types.ml
modified:   ocaml/xapi/records.ml
modified:   ocaml/xapi/test_common.ml
modified:   ocaml/xapi/xapi_pool.ml
modified:   ocaml/xapi/xapi_pool_update.ml
> Revert CP-23026 pool join rules until automated testing is available

- ocaml/xapi/xapi_pool_update.ml
This commit changes the behaviour of Xapi_pool_update.resync_host which
reads the updates from the file system and is called during startup.
Previously, new updates records were created for updates that were
unknown. This commit changes this this behaviour: for an update found in
the file system a potentially existing record is partially updated.
The rationale for this change is that an updated xapi at startup might
interpret an existing update's meta data differently than before. This
provides an opportunity to correct previous wrong or inconvenient
interpretations. This particular instance was triggered by the
introduction of the enforce_homogeneity attribute.
> CP-23026 CA-258536 update update records at startup

- ocaml/xapi/xapi_vdi.ml
- ocaml/xapi/xapi_vdi_helpers.ml
except for `blocked.
This function did not consider some VDI operations for some reason, it
only considered a subset of them. Now it considers all VDI operations,
therefore the allowed_operations field of the VDI will now contain new
VDI operations.
The following 6 VDI operations were not considered before by
Xapi_vdi.update_allowed_operations: enable_cbt, disable_cbt,
force_unlock, mirror, scan, set_on_boot. Only the enable_cbt,
disable_cbt, and set_on_boot operations have user-visible VDI methods
with the same name, `mirror is used for VDI.pool_migrate,
VDI.force_unlock is hidden from the docs, and it seems that `scan is not
used at all.
> Xapi_vdi.update_allowed_operations: consider all VDI ops

- ocaml/xapi/xapi_pool_update.ml
A lower-level operation would error out in this case, even without this
check - however, it's best to add a check here as this behaviour is
probably an implementation detail of this XenAPI call and could change
in the future.
> pool_update.introduce: disallow cbt_metadata VDI

- ocaml/xapi/xapi_pool.ml
With this commit, when pool_hosts_not_homogeneous is raised in pool-join
pre-checks, it provides a descriptive error message rather than a UUID.
This is now in line with other call sites of this error. The main
concern here is that this string is also shown in XenCenter to the user.
> CA-259288 provide descriptive reason when raising pool_hosts_not_homogeneous

- ocaml/doc/README.md
- ocaml/doc/doc-convert.sh
- ocaml/doc/templates/cover.mustache
- ocaml/doc/vm-lifecycle.md
- ocaml/doc/wire-protocol.md
- ocaml/idl/markdown_backend.ml
It seems not all systems understand notation the same way and to keep things simple and maintenance overheads low I'd rather we didn't have to resort to installing too many packages. The suggested changes work ok with only pandoc and texlive on centos 7 and ubuntu 16 (presumably on mac too).
> Further tweaks to make building the pdf more environment agnostic.

- ocaml/.merlin
Sometimes I go to the definition of a symbol from a different file using
merlin, and edit that file. However, with the old merlin file I jumped
to the source file in the _build directory, and my modifications got
lost after a "make clean".
I changed the order of entries in the .merlin file, so that for existing
source files, we will go to the source directory now instead of _build,
but auto-generated files are still found in the _build directory.
> .merlin: search source dir for source files first before _build

- ocaml/xapi/dbsync_slave.ml
- ocaml/xapi/xapi.ml
- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_main.ml
Prior to this fix, xapi was responsible for calculating the
initial host free memory and recording it in a file in dom0.
This caused an issue on hosts with a CVM; xapi would exclude
the CVM memory in its calculation but it would include it in
subsequent reboots; this happened because, on firstboot, the
CVM is started after xapi, but on reboots it starts before.
squeezed always starts before the CVM and xapi, so the
calculation is moved to squeezed to ensure predictable
behaviour.
> CA-258652/SCTX-2565: Get initial host memory from squeezed

- ocaml/xapi/xapi_pool.ml
Other hosts have transiently incorrect updates shortly after they join,
leading to a problem if several hosts are pooled rapidly.
> CA-259405: Only check pool master's updates on pool join

- ocaml/idl/datamodel.ml
- ocaml/xapi/record_util.ml
- ocaml/xapi/test_xapi_vbd_helpers.ml
- ocaml/xapi/xapi_vdi.ml
- ocaml/xapi/xapi_vdi_helpers.ml
It seems that this operation is not currently used.
> datamodel: remove `scan from vdi_operations enum

- ocaml/idl/datamodel.ml
- ocaml/xapi-consts/api_errors.ml
- ocaml/xapi/xapi_vm_migrate.ml
- ocaml/xapi/xapi_xenops.ml
See https://github.com/xapi-project/xenopsd/pull/359 for the context
> CA-259579: Introduce ballooning timeout before migration error

- ocaml/idl/datamodel.ml
- ocaml/idl/datamodel_types.ml
- ocaml/xapi/records.ml
- ocaml/xapi/test_common.ml
- ocaml/xapi/xapi_pool.ml
- ocaml/xapi/xapi_pool_update.ml
This PR is a collection of cherry-picks that brings the implementation of pool-join rules from Honolulu to Master. It contains one additional commit to fix a comment in the code that became misleading after a code change. Pool join does:
* check that the set of updates marked as enforced are identical on joining host and master
* on restart, updates are read and in particular checked for the new attribute "enforce-homogeneity"
* error messages are made to fit into the existing scheme (using strings) but might need revising to avoid problems with i18n in the future.
> Port pool-join rules from Honolulu to Master CP-23535

- ocaml/xapi/message_forwarding.ml
If the VDIs are from different SRs, then the changed blocks are all the
blocks of vdi_to, so the SR of vdi_from doesn't have to be connected.
Using SR.forward_multiple_op caused a bug where the
export_changed_blocks call was forwarded to a slave, even though this
call has to be run from the SR master, which is the pool master in case
of a shared SR. The forward_vdi_op function correctly forwards the call
to the SR master.
> VDI.export_changed_blocks: only require SR of vdi_to

- ocaml/xapi/test_vdi_allowed_operations.ml
- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_vdi.ml
To ensure we don't get failures in the RPU testing until the next rebase on master.
> Backport RPU fix (CA-260262) to feature/CBT branch

- ocaml/xapi/xapi_pool_update.ml
The path to updates in the file system is controlled by global variable
Xapi_globs.host_update_dir but it was not used and "/var/update" was
used directly. This commit makes sure the prefix is taken from the
global variable.
> Use Xapi_globs.host_update_dir in pool_update.resync_host

- ocaml/xapi/suite.ml
- ocaml/xapi/test_sr_update_vdis.ml
- ocaml/xapi/xapi_sr.ml
This carries on from a previously closed PR: https://github.com/xapi-project/xen-api/pull/3065
The 2 scenarios are each unit tested in their own function, and each one is also fixed in its own commit.
> CA-254515: Fix 2 cases where snapshot_of becomes null; unit tests included!

- scripts/extensions/pool_update.precheck
This PR fixes a confusing error message from the update precheck script.
When existing hotfix prevents a service pack update which provides a newer `product version`, the original error message was `PrerequisiteMissing`, this is not correct because it is the wrong version which prevents the update.
> CA-253959: Modify error message from update precheck script.

- ocaml/xapi/xapi_vdi.ml
To avoid returning an error when one of the DB references become invalid
while this function is running - these references will simply be skipped
and not included in the final list of URIs. This could happen due to
concurrent operations manipulating the PBDs of the SR, for example.
It is probably much more user friendly to skip these references that
become invalid, instead of returning an obscure error about an invalid
DB reference.
> VDI.get_nbd_info: make it more robust

- Makefile
- ocaml/doc/README.md
- ocaml/doc/classes.dot
- ocaml/doc/doc-convert.sh
- ocaml/doc/index.html
- ocaml/idl/markdown_backend.ml
Also: fixed the size of the image; moved the method return type into the same
line as the rest of the method signature.
> CA-261855: Generate automatically an image map for the API classes.

- scripts/extensions/pool_update.precheck
Extend the list of errorcode handled by parse_precheck_failure().
> Add LICENSE_RESTRICTION to the error whitelist

- scripts/extensions/pool_update.precheck
This fixes the previous commit.
> Fix spelling of LICENCE_RESTRICTION / LICENSE_RESTRICTION in pool_update

- scripts/extensions/pool_update.precheck
When the precheck script is called directly the output will contain an
XML document on failure. Process it in the same manner as when it
fails during installation of the control package.
> CA-263587: extract error content from precheck script

- ocaml/xapi/test_vdi_allowed_operations.ml
- ocaml/xapi/xapi_vdi.ml
- ocaml/xapi/xapi_vdi_helpers.ml
Storage migration was failing when the source was an older
XenServer host with no knowledge of the \`cbt_enable and
`cbt_disable VDI operations.
This commit filters out these operations when
populating a VDI's allowed_operations list.
> CA-260245: Fix SXM: old host choking on new op

- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_vdi.ml
- ocaml/xapi/xapi_vdi_helpers.ml
When populating VDI.allowed_operations, consider only the operations
that existed before the Ely release (corresponding to XenServer 7.1).
(Ely contained the first additions since 2009 or earlier.)
(The previous commit marked CA-260245 was insufficient to fix the SXM.)
> CA-260245: Fix SXM: old host choking on new op (2)

- ocaml/xapi/cli_frontend.ml
- ocaml/xapi/cli_operations.ml
Remove this command, as it currently does not work, because each CLI
command create a new session that it closes when it finishes.
We cannot accept a session parameter or return a dedicated newly-created
session from this command until we have implemented command-line session
handling.
This reverts commit c9d1e6ebce641d49aa0421ef88e2fea2f1d373d8.
> CA-262941:  	Remove "xe vdi-get-nbd-info" CLI command

- scripts/import-update-key
If the `import-update-key` script is used when a TTY is not available (e.g.
during RPM installation), it can result in a situation where the key is
imported, but not marked as trusted. By passing `--batch` we avoid this
situation.
Signed-off-by: Alex Brett <alex.brett@citrix.com>
> CA-264428: Use --batch when calling gpg

- ocaml/xapi/xapi_globs.ml
- scripts/xapi.conf
This setting was previously configurable from the `xapi.conf` file,
when xenopsd was still a part of xapi. When they split, the setting
was not transferred and nor was it wired up to be used by xenopsd.
This commit removes the setting from xapi.
A corresponding commit in xenopsd adds it there and makes it
configurable in `xenopsd.conf`.
> CA-264331: Remove unused shutdown ack timeout setting

- ocaml/idl/datamodel.ml
The Host.get_server_certificate function was restricted to the
Pool Operator role and higher.
Now it is available to all RBAC roles.
> CP-23051: Host.get_server_certificate: all RBAC roles

- scripts/generate_ssl_cert
When autogenerating a self-signed certificate for server-side TLS
use, add "Subject Alternative Names" for all the host's IP addresses
and host names that the `hostname` command can tell us.
> CP-24466: subjectAltName for TLS cert

- ocaml/idl/datamodel.ml
- ocaml/xapi/cli_frontend.ml
- ocaml/xapi/cli_operations.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/record_util.ml
- ocaml/xapi/sm.ml
- ocaml/xapi/storage_access.ml
- ocaml/xapi/storage_impl.ml
- ocaml/xapi/storage_impl_test.ml
- ocaml/xapi/storage_mux.ml
- ocaml/xapi/xapi_sr_operations.ml
- ocaml/xapi/xapi_vdi.ml
- ocaml/xapi/xapi_vdi.mli
Because the latter is clearer. People found the function name
export_changed_blocks confusing, because it suggested that the actual
data of the changed blocks will be "exported".
> Rename VDI.export_changed_blocks to VDI.list_changed_blocks

- ocaml/xapi/quicktest.ml
- ocaml/xapi/quicktest_bvt.ml
Increase quicktest code coverage by adding the following unused XenAPI calls:
- Client.PBD.get_all
- Client.PBD.get_uuid
- Client.PBD.get_by_uuid
> Increase quicktest code coverage by adding the following unused XenAPI calls

- scripts/extensions/pool_update.apply
- scripts/extensions/pool_update.precheck
Current log of pool_update.apply and pool_update.precheck are
using %r for output string format which lead to illegible logging,
this patch will split the execution output before logging, so it's
user friendly format.
Signed-off-by: Huan Xie <huan.xie@citrix.com>
> CA-249810: Change pool update related log format

- ocaml/xapi/vm_platform.ml
- ocaml/xapi/xapi_vm.ml
- ocaml/xapi/xapi_vm_clone.ml
- ocaml/xapi/xapi_vm_helpers.ml
The HVM templates of a host shall have a `VM.platform["device-model"]`
field containing the default device model according to the QEMU feature
release stages.
When a VM is created from a template, if `VM.platform["device-model"]`
is not set, then it shall be initialized from the default device model
profile.
> CP-24360: Initialise VM.platform['device-model'] values - Stage 1

- ocaml/xapi/cli_frontend.ml
- ocaml/xapi/cli_operations.ml
- ocaml/xe-cli/bash-completion
Append -uuid to vdi-list-changed-blocks param names, and add a special
case for them in ocaml/xe-cli/bash-completion to enable tab completion.
I had to change the bash-completion file, because these parameter names
(vdi-from-uuid and vdi-to-uuid), contain two hyphens - for params
containing only one hyphen and ending with -uuid, tab completion works
automatically.
Signed-off-by: Iglói Gábor <gaborigloi@gmail.com>
> CLI: enable tab completion for "xe vdi-list-changed-blocks"

- ocaml/xapi/ipq.ml
- ocaml/xapi/xapi_periodic_scheduler.ml
This is an attempt to make the periodic scheduler more robust against
clock changes by moving it to a monotonic clock. This requires
changing the representation of time from float (seconds) to Int64.t
(nanoseconds).
I'm inviting comments but still need to test this - most likely on a branch to run a BVT. 
> CA-223754 move periodic scheduler to a monotonic clock

- ocaml/xapi/test_common.ml
- ocaml/xapi/test_vdi_cbt.ml
- ocaml/xapi/xapi_vdi.ml
Because it is already updated in the message forwarding layer by
unmark_vdi called from with_sr_andor_vdi, and we use that function for
data_destroy.
In the unit test I check that this actually happens in the message forwarding layer.
> Xapi_vdi.data_destroy: don't call update_allowed_operations + unit test

- ocaml/xapi/test_vdi_allowed_operations.ml
Add the following validations from design brief v12 p15:
- valid only for snapshot VDIs whose cbt_enabled field is true
- cannot be run on SRs of type "udev"
- cannot be run on an SR that contains the Tools ISO VDIs (when is_tools_sr is true)
> CP-23198: Add test to check VDI.data_destroy throws correct exception

- ocaml/xapi/test_vdi_allowed_operations.ml
As in design doc v12
- check data_destroy is idempotent
Additionally, `data_destroy` has been added to the list of `all_cbt_operations` and will now be included in the `test_sm_feature_check` test.
> Extend PR #3211 with further test

- scripts/generate_ssl_cert
Instead of concatenating text into the file in its final location and
then setting its permissions, prepare the file (content and
permissions) in a staging area and then use an atomic move operation
to make it appear in its final location.
Also some other improvements to reliability and safety.
> TLS cert generation: make cert appear atomically

- ocaml/xapi/test_vm_check_operation_error.ml
- ocaml/xapi/xapi_vm_lifecycle.ml
- ocaml/xapi/xapi_vm_migrate.ml
By moving the check from the message forwarding layer to the
implementation, because in message forwarding we do not know the VDI to
SR mapping.
I added a check to Xapi_vm_migrate.migrate_send and assert_can_migrate,
checking that no CBT-enabled VDI is mapped to an SR different from its
current one. This is the only check that is done, whether the migration
is cross-pool or intra-pool. I assume the existing checks disallow
mapping a VDI to its current SR in case of cross pool migration, because
this pool's SR is probably not accessible to the remote pool. If this is
true, then cross-pool migration of VMs with CBT-enabled VDIs will never
be allowed, as expected, because all the VDIs have to be mapped to a
different SR.
In assert_can_migrate, I've added the checks for CBT-enabled VDIs to …
> CA-265183: Allow intra-pool migration when CBT-enabled VDIs are not moved

- ocaml/xapi/xapi.ml
Don't start xapi-nbd from xapi, because it will be path-activated by
systemd when the .pem certificate file appears that xapi-nbd needs for
TLS, which is enabled by default. When it was started by xapi, during
first boot the .pem file was generated by scripts/generate_ssl_cert
*after* the startup sequence finished when we got a management interface
& IP, and therefore xapi-nbd failed to start, because the .pem file it
required wasn't there.
This reverts commit 5a4fc0d132132b7be674c56b000a7332dee9f885.
> CA-265469: Revert "CA-265469: start xapi-nbd from xapi"

- scripts/usb_reset.py
Before USB device is passed through, this script is called to reset it.
Clear device status is for better security.
>     CP-24616: script to reset USB device

- ocaml/xapi/test_vdi_allowed_operations.ml
- ocaml/xapi/test_vdi_cbt.ml
As in CBT design brief v12, PR verifies the following results of calling VDI.data_destroy :
- VBDs are no longer associated with VDI
- If VDI is the suspend VDI of a suspended VM, after the call VM.suspend_VM is set to Ref.null
- VDI type set to cbt_metadata
- idempotence for metadata snapshot VDIs
> CP-23198: verify results of calling VDI.data_destroy

- scripts/nbd-firewall-config.sh
A new script that can be used to specify the interfaces
(if any) on which incoming connections to the NBD server
will be permitted by the iptables firewall.
> CP-24777: A script to configure firewall for NBD

- ocaml/xapi/jbuild
As now use jbuilder, lib yojson is missed. This is to add it.
> CP-24611:  add lib yojson used by PUSB scan

- ocaml/xapi/xapi_pci_helpers.ml
- ocaml/xapi/xapi_vgpu_type.ml
Rarely `xap`i is booting and updating the PCI records while the data in
`sysfs` is being written/changed. This invalidated the `access` structure
and caused a segmentation fault.
By using the `dump` access, that in practice means dumping the
equivalent of `pci -x` in a temporary file (see man pciutils) we can
make sure that the data is not changing under our feet.
This seems to have resolved the segmentation fault, at the price of
potentially having partial information about the pci devices on the
host. This did not seem to affect system tests, and in the worst case
scenario, after a toolstack restart all the pci devices are detected.
> CA-266936: pciutils: use the file dump in a temp file if possible

- ocaml/xapi/import.ml
- ocaml/xapi/vm_platform.ml
- ocaml/xapi/xapi_vm.ml
- ocaml/xapi/xapi_vm_clone.ml
- ocaml/xapi/xapi_vm_helpers.ml
This PR merges the changes from the feature branch for upstream qemu support into the master branch. The branch has been re-based and builds successfully. 
```
commit 6be8032b8d7fec01b4ade0801d28d92461dd583a
Author: Liang Dai <liang.dai1@citrix.com>
Date:   Fri Sep 22 14:19:16 2017 +0800
CP-24360: Initialize platform[device-model] during VM.import and VM.migration
The previous patch is missing the VM.import and VM.migration cases.
Need to initialize platform["device-model"] if it is not set in
vm_record.
The VM.import also calls VM.import, so add this code in VM.import.
ocaml/xapi/import.ml | 8 ++++++++
1 file changed, 8 insertions(+)
commit 482a48553029f6436baae5bf8879cb821db90b9c
Author: Liang Dai <liang.dai1@citrix.com>
Date:   Fri Sep …
```
> Merge support for qemu into master 

- ocaml/xapi/storage_migrate.ml
that don't have any actual data, when finding the nearest VDI. This is
to avoid accidentally using a cbt_metadata VDI without data.
The VDI.similar_content call already does this filtering when we look
for similar local VDIs, and this commit extends the filtering to the
remote VDIs that we compare the similar VDIs to.
The content_id of all the cbt_metadata VDIs is set to the same constant,
so this change prevents accidentally matching two of these two each
other when we try to find the nearest VDI.
> Storage_migrate.receive_start,copy: filter out cbt_metadata VDIs

- ocaml/xapi/ipq.ml
- ocaml/xapi/xapi_periodic_scheduler.ml
This reverts commit cafce7226210123536a632493340a3136b9dad4f.
The `event_from_parallel_test` unit test occasionally hangs in `event.from`,
even though a 2s timeout is applied. This may be due to the clock changes, so
reverting this, just in case.
> Revert "CA-223754 move periodic scheduler to a monotonic clock"

- ocaml/xapi/xapi_network.ml
If any network had any purpose, this was being treated as a
conflict with the addition of any purpose to any network.
> CA-268279: Fix self-conflicting network purposes

- ocaml/xapi/storage_access.ml
- ocaml/xapi/storage_impl_test.ml
- ocaml/xapi/xapi_sr.ml
- scripts/examples/smapiv2.py
This PR contains the xapi changes required for for adding cbt_enabled to vdi_info SMAPIv2 type.
> CP-22446: add cbt_enabled to vdi_info type

- ocaml/idl/datamodel.ml
- ocaml/xapi/api_server.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/test_vdi_cbt.ml
- ocaml/xapi/valid_ref_list.ml
- ocaml/xapi/valid_ref_list.mli
- ocaml/xapi/xapi_vdi.ml
- ocaml/xapi/xapi_vdi.mli
Instead of a list of strings, this function now returns a list
of a record-type which is newly defined in the datamodel.
This breaks and disables the unit-test-case testing the function.
> CP-24914: Vdi.get_nbd_info: return type with cert

- scripts/generate_ssl_cert
When autogenerating a self-signed TLS certificate, the Subject
Alternative Names section no longer contains IP subjects, only DNS.
> CP-24904: Omit IP SubjectAltNames from TLS certs

- ocaml/xapi/records.ml
> xe CLI: update name of network's purpose field to match the corresponding XenAPI field

- scripts/Makefile
This script is now included in the "install" target of the
relevant Makefile.
> CP-25015: nbd-firewall-config.sh in "make install"

- .vscode/tasks.json
Press Ctrl+Shift+B to `make test` from the editor terminal!
> Add build shortcut for VS Code

- ocaml/xapi/test_vdi_cbt.ml
- ocaml/xapi/xapi_vdi.ml
We should not try to guess here whether CBT is enabled or not on the
snapshotted VDIs. SM should be responsible for updating this VDI field
in the DB, instead of xapi trying to guess and keep track of it, as SM
is in the best position to know when CBT is enabled, and it is already
setting this field during SR scan.
> Xapi_vdi.snapshot: remove logic setting cbt_enabled in the DB

- ocaml/.merlin
- ocaml/xapi/ipq.ml
- ocaml/xapi/jbuild
- ocaml/xapi/storage_migrate.ml
- ocaml/xapi/xapi_periodic_scheduler.ml
- xapi.opam
This is the second attempt to move the periodic scheduler to a monotonic clock. The PR contains two commits:
* f9c544ac9 replaces the oclock with mtime 
* 3630167ab moves the periodic scheduler to use mtime
Previously with using oclock for the periodic scheduler we saw xapi locking up and suspected problems in oclock. This PR has been tested:
* running unit tests that exhibited the problem in the past
* running builds on Jenkins that exercised unit tests
*  BVT run 72144
> CP-24647 replace oclock with mtime, use it for periodic scheduler

- ocaml/xapi/xapi_vm_helpers.ml
Instead of physical equal, here what we want is value equal.
> CP-25052: Fix comparison error in assert_usbs_available

- ocaml/xapi-types/event_types.ml
- ocaml/xapi-types/jbuild
- ocaml/xapi-types/ref.ml
- xapi-cli-protocol.opam
- xapi-client.opam
- xapi-consts.opam
- xapi-database.opam
- xapi-datamodel.opam
- xapi-types.opam
- xapi.opam
- xe.opam
This will allow us to re-introduce xapi into xs-opam and be able to use selected sub-libraries without the need to have the whole xapi
> Update opam files and cleanup xapi-types

- ocaml/xapi/quicktest.ml
- ocaml/xapi/quicktest_cbt.ml
- ocaml/xapi/valid_ref_list.ml
Test does the following:
- search for an lvm SR
- create a VDI attached to it
- test cbt_enabled:false for newly created VDI
- call enable_CBT and disable_CBT
- destroy VDI
In future:
- snapshot newly created VDI
- test data_destroy does the following:
-- update content_id field to specified string
-- update type to CBT_metadata
- destroy snapshot VDI
> Test CBT VDI operations with quicktest

- ocaml/idl/datamodel.ml
There is no need for this, as it shouldn't be blocking. Each host has to
read a file to get their certificates, but it still shouldn't take long.
And we can always re-add it in the future.
> Datamodel: don't generate async VDI.get_nbd_info

- ocaml/xapi/xapi_vusb.ml
> CP-24409: No need to check vm status when destroy VUSB

- ocaml/idl/datamodel.ml
- ocaml/xapi/vm_platform.ml
- ocaml/xapi/xapi_db_upgrade.ml
- ocaml/xapi/xapi_vm_helpers.ml
If the `VM.platform["device-model"] field of a HVM VM is not set, then
it shall be initialised from the fallback device model profile when
a host is upgraded to a newer version of XenServer, using the Xapi 
database upgrade mechanism. During the upgrade, the database initialises 
this value using the fallback device model profile value for the 
XenServer version that the host is being upgraded from. 
Passed dev-tests in CP-24805.
Signed-off-by: Marcus Granado <marcus.granado@citrix.com>
> CP-24805: Update VM.platform.device-model field during Xapi database upgrade

- ocaml/xapi/xapi_xenops.ml
This PR is to fix the error log that when updating VUSB  in update_vusb funciton, which throw missing row PUSB.
> CA-269367: Fix missing row PUSB while updating VUSB

- ocaml/xapi/xapi_pusb.ml
> Should not check usb-passthrough licence when xapi starting

- ocaml/xapi/test_vdi_cbt.ml
- ocaml/xapi/xapi_vdi.ml
IPv6 addresses should only be surrounded by square brackets when they are part of a URL.
>  CA-269366: VDI.get_nbd_info: fix returned IPv6 addresses

- ocaml/xapi/vusbops.ml
1. Should not check feature restriction as if the license expired
the vm can not start.
> CA-269588: BVT failed as the licence check issue.

- ocaml/xapi/xapi_xenops.ml
When xapi starts, it queries xenopsd about the state of local VMs. In
SCTX-2619 we found that xenopsd passed data about a VM that was *not*
resident locally but was left over from a previous failed migration to
local host. This data was erroneously used to reset the power state of
that non-local VM. This commit fixes this.
If xenopsd reports the VM as running, it must indeed be resident on the
local host - so we reset the state of the VM to what xenopsd is
reporting.
If xenopsd reports the VM as suspended or halted, we only reset the
state of the VM if xapi believes the VM is resident on localhost.
Previously it would reset the state regardless - which caused the error.
CP-25141 log when VM's powerstate is reset
Signed-off-by: …
> CP-25141 SCTX-2619 fix sync from xenopsd in on_xapi_restart

- ocaml/xapi/xapi_vm_lifecycle.ml
This commit employs partial evaluation to avoid re-evaluating expensive
expressions. In a nutshell, when evaluation f x y z is expensive, some
work can be saved when we need to compute f x y1 z1 and f x y2 z2 with x
being the same. We compute f x, which returns a function f' that takes
two arguments y and z. Now we can call f' and its evaluation can use the
work that already went into the evaluation of f x.
> CA-267946: VM.update_allowed_operations: cache some common values when checking operation errors in a loop

- ocaml/xapi/xapi_pusb_helpers.ml
1. when usb policy file is modified, usb_scan script will exit(1).
Xapi will log the error.
> CP-25186: Handle usb_policy error

- scripts/usb-policy.conf
- scripts/usb_scan.py
CP-25172: Improve the error handling of scanner
If the policy file cannot be parsed, return 1 to indicate the error
instead of just ignoring the line.
Signed-off-by: Xin(Talons) Li <xin.li@citrix.com>
> CP-25172: Improve the error handling of scanner

- scripts/usb-policy.conf
Remove the DENY hubs line from policy file, because hubs are always
ignored. Also add comment to make it clear.
Signed-off-by: Xin(Talons) Li <xin.li@citrix.com>
> CP-25328: update policy file, hubs are always denied

- ocaml/xapi/xapi_vm_snapshot.ml
1. Need to clean up VUSBs when reverting snapshot.
> CA-269642: Revert snapshot should clean up VUSBs

- ocaml/xapi/xapi_pusb.ml
- ocaml/xapi/xapi_pusb_helpers.ml
1.When unplug usb from host, we need to unplug vusb from vm if it is attached to vm.
> CA-269728: Unplug the USB from host, not detach the vusb from VM

- ocaml/database/xml_spaces.ml
This is an issue in how xapi serialises the fields in the database xml dump.
Xapi creates row tags that have all the fields set as attributes and
by spec spaces in attrributes are stripped and normalised.
Currently xapi uses an internal encoding/decoding that escapse the
character that would otherwise be stripped, with the possible
exception of one space at the beginnin of the content and one
at the end.
This PR changes this escape mechanism by escaping all white spaces
singularly instead of in pairs. The unescape mechanism is
kept backward compatible.
> CA-268761: Trailing whitespaces are lost by the xapi database

- ocaml/xapi/certificates.ml
- ocaml/xapi/jbuild
- ocaml/xapi/test_vdi_cbt.ml
- ocaml/xapi/xapi_vdi.ml
- xapi.opam
Use the x509 library to parse the certificate and read its
DNS subject names, if any.
(This replaces the stopgap of using Host.hostname for the
value of the "subject" field of the vdi_nbd_server_info objects.)
> CA-269137: get_nbd_info: get subject from TLS cert

- ocaml/xapi/xapi_vdi.ml
In the VDI.get_nbd_info function, when reading a TLS certificate and
choosing a subject from it to include in the return value, avoid
wildcard subjects if possible: return a concrete hostname (DNS name)
if there is one, and a wildcard only as a last resort.
> CP-25372: Prefer non-wildcard certificate subjects

- ocaml/xapi/quicktest_cbt.ml
Test that VDI.data_destroy:
- updates VDI.type to cbt_metadata
- updates content_id to: "/No content: this is a cbt_metadata VDI/"
> CP-22019: Test VDI.data_destroy

- ocaml/xapi/test_vm_check_operation_error.ml
- ocaml/xapi/xapi_vm_lifecycle.ml
Looping through more elemnts during VM.update_allowed_operations has a
performance impact. This commit restores the list of operations that we
check in VM.update_allowed_operations to the original set, which does
not include all VM operations.
This reverts commit 5497ab7b4569cd3422c0674295b92619294b8a09.
> Revert "Factor out all_vm_operations"

- ocaml/xapi/db.ml
e.g. in `update_allowed_operations` avoid repeated RPC calls that we know are
always going to return false when the field is not set.
Of course we'll still do the RPC call when it is not NULL to validate the ref.
> CA-267946: Avoid Db.is_valid_ref RPC call when Ref is NULL

- ocaml/xapi/quicktest_cbt.ml
Test VDI.clone and VDI.copy set cbt_enabled to false when called on a CBT-enabled VDI, as specified in CBT design doc v13.
> CP-22019: Test VDI.clone and VDI.copy

- scripts/test_usb_scan.py
- scripts/usb_scan.py
add unit test for usb_scan.py
Signed-off-by: Xin(Talons) Li <xin.li@citrix.com>
> CP-24132: unit test for usb_scan.py

- ocaml/xapi/test_common.ml
- ocaml/xapi/test_xapi_xenops.ml
- ocaml/xapi/xapi_xenops.ml
This PR fixes an issue with the start-of-day sync of xapi and xenopsd that occurs when there are non-dom0 control domains.
> CA-271857: Add a fix for start-of-day xenopsd sync

- ocaml/xapi/xapi_vgpu_type.ml
This bypasses the changes from b66e46cc, until low-level bits have been fixed.
This is the "smallest" fix for this issue. We already have a fallback to the
old method for the case that the XML is invalid. We'll now take that path even
when the XML did give us some valid vGPU types.
> CA-272126: Don't get NVidia vGPU types from XML file for now.

- ocaml/idl/datamodel.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_vdi.ml
- ocaml/xapi/xapi_vdi.mli
Deprecate VDI.resize_online because there are no sm backend support this feature.
> CA-262059: No SM backends support VDI.resize_online - should be deprecated & removed

- ocaml/xapi/xapi_vm_migrate.ml
The error takes the feature name as argument.
> CA-272679: Fix error args of feature check for VM.pool_migrate

- ocaml/xapi/helpers.ml
- ocaml/xapi/xapi_sr.ml
This greatly improves the performance of the pool master in a large pool. The current loop means that every 2 minutes each host in the pool queries, for each PBD (regardless of which host it's on), whether it's currently attached, and its SR. It then updates the xapi database with the RRDD physical utilisation value for those SRs it has the data. As an optimisation therefore, this commit adds a new method to only get PBDs on the calling host, and then the SRs for those will be those that it can update the RRDD data for.
The issue with this physical utilisation thread is the overhead on the pool master, which must handle all the database queries. This is now only one query to get the PBDs currently attached on the calling host, plus one more for each PBD currently plugged on localhost (to …
> [CA-271014] Only get local SRs on the physical utilisation thread

- ocaml/util/jbuild
- ocaml/util/xapi_version.ml
Get build date from `xensource-inventory` instead of hard coding to `1970-01-01`.
This PR depends on the change of other repos, I have recorded them in the ticket.
> CA-271852 XenServer build date hardcoded to 1970-01-01

- ocaml/xapi/quicktest_cbt.ml
Quicktest currently contains 2 tests for CBT:
- one checks VDI.snapshot and VDI.data_destroy retain CBT-relevant VDI fields
- as above but for VDI.copy and VDI.clone
This PR extends those both to call VDI.update after every CBT-relevant call, ensuring VDI.update preserves CBT-relevant fields
Note: this is a preliminary test, ideally would like to set incorrect database values and check for VDI.update to fix them, looking for a way to do this within a quicktest
> CP-22019: xapi quicktest checks VDI.update is CBT-compatible

- xapi-datamodel.opam
When setting up an empty ocaml switch and installing the dependencies of `xapi` it failed with:
```
```
> xapi-datamodel: add missing dependency on mustache

- ocaml/xapi/xapi_vm_lifecycle.ml
Suspending a VM must be blocked if the vGPU driver does not support it. This PR extends xapi_vm_lifecycle.check_vgpu() to check for it. The check implements a heuristic: if a pGPU does not provide metadata for compatibility checks (that are required when resuming the VM on a host), we assume suspending is not supported.
This PR refactors the existing code to use `List.for_all` for checking that all vGPUs have the necessary properties.
This has been manually tested: a VM using a vGPU driver that does not provide compatibility metadata can't be suspended because it is not an allowed operation.
> CA-270463 block VM suspend if vGPU driver doesn't support it

- ocaml/xapi/xapi_pusb.ml
Two exactly same pusbs in two hosts of a pool will be deleted when
unplug one of the pusbs, this change is to fix it.
> CA-274079: Removing one Pusb removes all Pusbs in the pool

- scripts/examples/python/XenAPI.py
older version of python doesn't know about SSL context in xmlrpclib. 
[root@xxx ~]# python --version
Python 2.7.5
[root@xxx ~]# pydoc xmlrpclib | grep __init__
|  __init__(self, data=None)
|  __init__(self, value=0)
|  __init__(...)
|      x.__init__(...) initializes x; see help(type(x)) for signature
|  __init__(self, target)
|  __init__(self, faultCode, faultString, **extra)
|  __init__(self, response)
|  __init__(self, encoding=None, allow_none=0)
|  __init__(self, server)
|  __init__(self, results)
|  __init__(self, url, errcode, errmsg, headers)
|  __init__(...)
|      x.__init__(...) initializes x; see help(type(x)) for signature
|  __init__(self, use_datetime=0)
|  __init__(self, uri, transport=None, encoding=None, verbose=0, allow_none=0, use_datetime=0)
|  __init__(self, uri, …
> fix compatibility for older python (doesn't know context [SSL])

- ocaml/idl/ocaml_backend/gen_api.ml
- ocaml/xapi/cpuid_helpers.mli
- ocaml/xapi/xapi_pgpu_helpers.mli
- ocaml/xapi/xapi_vdi.mli
- ocaml/xapi/xapi_vm_clone.mli
[`Foo] Ref.t and [`Bar] Ref.t were both accepted in rpc_of_ref_foo, becase it was
accepting 'a Ref.t.
They are strings underneath so this was working but could lead to bugs not being
detected at compile time: such as looking up the wrong object by uuid, and then passing it to a create function on another object.
Annotate the generated rpc_of_t and t_of_rpc functions to make sure that the
ignored value is of the right type.
Now rpc_of_ref_foo accepts only [`Foo] Ref.t.
Update some interfaces that are now more strictly typed.
> API: more strict typing for 'a Ref.t conversions from Rpc.t

- ocaml/xapi/xapi_vm_lifecycle.ml
Checkpoint-ing a VM has been permitted for VMs/vGPUs that support
migration. I always has been blocked for all other VMs/vGPUs.  This
commit removes the ability to checkpoint a VM/vGPU that can be migrated
and suspended.
> CP-26076 block VM.checkpoint on any VM with a vGPU

- ocaml/xapi/xapi_pgpu_helpers.ml
- ocaml/xapi/xapi_pgpu_helpers.mli
- ocaml/xapi/xapi_vm_migrate.ml
The function `assert_destination_pgpu_is_compatible_with_vm`
had a heuristic to select the destination pgpu that was
filtering over vgpu implementation, however this is `nvidia`
for any Nvidia card, resulting in potentially meaningless
choices.
The function was also assuming that the user-defined
vgpu_map was complete (all vgpus would be mapped) but
this is often not the case.
The function was called in two migration places, in one
we had preselected the pgpu, making any heuristic
a potential source of errors.
This commit splits the check into two assertions:
- `assert_destination_pgpu_is_compatible_with_vm`, to be called
when the destination pgpu has already been selected
- `assert_destination_has_pgpu_compatible_with_vm`, using
a heuristic (based on the one used by vm-import) to
select …
> CA-274957: simplify and reorganise Nvidia VGPU compatibility check

- ocaml/xapi/jbuild
This depends on https://github.com/xapi-project/xs-opam/pull/179
Build will be broken until that is released
> xapi: oPasswd -> opasswd for support to version 1.0.2

- ocaml/xapi/helpers.ml
- ocaml/xapi/xapi_vm_lifecycle.ml
This patch attempts a best-effort approach to detect if the host the VM is
attempting to vgpu-migrate from is Jura or later. If this sending host is
earlier than Jura, it prevents the vgpu-migrating capability for the VM so that
the migration operation will not be allowed for this VM. This is specially
useful during an RPU, where in the same pool the master will be running the new
updated Jura code with this patch but the slaves not and vgpu-migration cannot
be allowed because it's known to deliberately fail between pre-Jura and
Jura/later hosts.
Other similar VM lifecycle operations (suspend, checkpoint) are still allowed
since they don't involve moving the VM to another host using an incompatible
vgpu-migration protocol.
This patch **_REQUIRES_** that Jura and later hosts use a …
> CP-26145: prevent vgpu-migration of VMs between pre-Jura and Jura/later hosts during RPU

- ocaml/idl/datamodel.ml
- ocaml/xapi-consts/api_errors.ml
- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_pif.ml
Prevent unplugging PIF which is used by FCoE
When unplugging PIF, if the PIF is used by FCoE SR, we should prevent the action.
> CA-178651: FCoE NIC is not prevented from unplugging

- ocaml/xapi/xapi_pgpu_helpers.mli
This fix limits the type of
assert_destination_pgpu_is_compatible_with_vm in the interface (MLI)
file to be more specific. This is required to make it compile after
rebasing onto more recent versions of Xapi.
'a Ref.t becomes [<`session] Ref.t
> Fix type of assert_destination_pgpu_is_compatible_with_vm

- ocaml/xapi/quicktest_cbt.ml
- ocaml/xapi/test_valid_ref_list.ml
- ocaml/xapi/valid_ref_list.ml
- ocaml/xapi/valid_ref_list.mli
There is a race condition where we get the list of VDIs, but before we
process them some of them get removed from the DB, and the cleanup fails
with an invalid ref error.
This can happen for example when SM creates an internal VDI record in
the DB, and then later it removes it, in parallel with the cleanup at
the end of the CBT quicktest.
> CA-276638: Quicktest_cbt: don't fail in cleanup due to VDI refs becoming invalid

- ocaml/xapi/xapi_vm_lifecycle.ml
When a VM is suspended, it must release all vGPUs it has allocated. So
far, this is only happens on shutdown but not suspend. This commit
rectifies this.
> CA-275660 release vGPUs from VM on suspend

- ocaml/cdrommon/cdrommon.ml
- ocaml/cdrommon/jbuild
This was exposed by the new release of xcp-inventory.
> cdrommon: fix incorred dependencies

- ocaml/idl/datamodel.ml
As title.
When reviewing https://github.com/xenserver/xenadmin/pull/1899/files Miheala proposed about this change.
> Correct FCoE SR to uppercase

- ocaml/xapi/xapi_pif.ml
The result from `forkhelpers.execute_command_get_output` contains the tailing `\n` so that the last item(SCSI ID) of the result cannot match correctly.
This fix trim the result.
> Trim the result after executing script with forkhelper

- ocaml/database/backend_xml.ml
- ocaml/database/block_device_io.ml
- ocaml/database/db_backend.ml
- ocaml/database/db_cache_impl.ml
- ocaml/database/db_cache_test.ml
- ocaml/database/db_cache_types.ml
- ocaml/database/db_conn_store.ml
- ocaml/database/db_connections.ml
- ocaml/database/db_interface.ml
- ocaml/database/db_lock.ml
- ocaml/database/db_remote_cache_access_v1.ml
- ocaml/database/db_upgrade.ml
- ocaml/database/db_xml.ml
- ocaml/database/jbuild
- ocaml/database/master_connection.ml
- ocaml/database/parse_db_conf.ml
- ocaml/database/redo_log.ml
- ocaml/database/ref_index.ml
- ocaml/database/static_vdis_list.ml
- ocaml/database/string_marshall_helper.ml
- ocaml/idl/ocaml_backend/gen_api.ml
- ocaml/idl/ocaml_backend/gen_server.ml
- ocaml/xapi-types/features.ml
- ocaml/xapi-types/jbuild
- xapi-database.opam
- xapi-types.opam
And overall cleanup of dependencies. Includes the removal of `xapi-stdext-deprecated` from the database but does _not_ include the removal of `xstringext`.
This PR blocks the release of https://github.com/xapi-project/xen-api-libs-transitional/pull/35 as it removes the transitive dependencies re-added here.
> xapi-types, xapi-database, idl: fix transitive dependencies issues

- ocaml/xapi/import.ml
On importing a VM, we must check that its suspend_SR is meaningful and
set it to Null if it isn't. The existing code has the test flipped.
Helpers.check_sr_exists ~__context ~self:vm_record.API.vM_suspend_SR
The above call returns `Some vM_suspend_SR` if it exists and `None`
otherwise. The test needs to look for None but previously did not.
> CA-276964 on import, set suspend_SR to null when unknown

- ocaml/xapi/xapi_vm_migrate.ml
This reverts commit b91552922a8db4d6300aba2aef96582ad2d5f508.
This was accidentally merged as part of the vGPU migration code but should not have been because it is just code added for debugging a current issue.
> Revert "CA-271406 debugging: add Null checks"

- ocaml/xapi/suite.ml
Travis has a limit of 4MB, after which it kills the build.
A feature branch was at 5MB before this patch due to having more tests,
after this patch we're down to 3.2MB, but master is failing inexplicably too.
This disables the 'Adding new database table' messages while running the test suite.
4MB limitation seems to be hardcoded in Travis:
https://github.com/travis-ci/travis-ci/issues/1382#issuecomment-23508178
> Reduce 'make test' output size to fit Travis limit

- .travis-xenserver-build-env.sh
This is not ideal but Travis is still failing inexplicably on master, lets try to reduce test output to a minimum: just the test summary and the error backtrace.
> Travis test: output only failure message

- ocaml/xapi/suite.ml
- ocaml/xapi/xapi_ha.ml
- ocaml/xapi/xapi_host.ml
When shutting the HA master we must ensure that we disable the redo log, otherwise we hang/fail when detaching the static VDIs or unplugging the PBD.
We should also ensure that slaves can no longer make requests to the master DB after we've started  to shutdown the master. This is done for now by moving where we stop the remote request thread, but it could also be done by killing the listening stunnel as discussed in the morning.
Tested on REQ-477 branch and was able to shutdown the HA master successfully several times.
While testing also found another bug in the new HA scripts, and I added a commit here that made debugging that easier.
> HA master shutdown

- .travis-xenserver-build-env.sh
- ocaml/xapi/test_clustering.ml
- ocaml/xapi/xapi_clustering.ml
- ocaml/xapi/xapi_pbd.ml
- ocaml/xapi/xapi_sr.ml
Currently in xapi_pbd and xapi_sr we take a clustering lock (`with_clustering_lock`) regardless of the SR type. However we only need to do this if the SM type requires a cluster stack. This commit adds a new function `with_clustering_lock_if_needed`, which calls `with_clustering_lock` if the SM type requires a cluster stack, otherwise it executes the passed function without any wrapper. The calls in xapi_pdb and xapi_sr are changed to use this new function.
This is tested by the fact that nesting two calls to `with_clustering_lock` will deadlock. We test that the lock is correctly taken when needed by nesting two calls to `with_clustering_lock_if_needed`, which should both take the lock and therefore deadlock. If they don't then the test fails, otherwise it times out and passes. We test …
> [CA-273985] Take clustering lock only if SM requires a cluster stack

- ocaml/xapi/test_cluster_host.ml
- ocaml/xapi/test_clustering.ml
- ocaml/xapi/test_common.ml
- ocaml/xapi/xapi_cluster.ml
- ocaml/xapi/xapi_cluster_host.ml
- ocaml/xapi/xapi_cluster_host.mli
- ocaml/xapi/xapi_clustering.ml
Previously these prerequisites were not checked, and the operation
succeeded when the PIF of the master wasn't permaplugged for example,
and we ended up with a cluster and a Cluster_host.
> CA-275786: Check PIF prerequisites when creating cluster

- .travis-xenserver-build-env.sh
We have reduced the verbosity of the travis tests and printed only the error.
Make sure we actually exit with an error-code when the tests fail!
I just noticed that I got a green tick on one of my PRs  to the feature branch, but the test actually failed and printed the error.
This was an oversight from my previous PR which introduced the log shrinking in the first place.
> Travis: if travis tests fail exit with code 1

- ocaml/idl/datamodel.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/records.ml
- ocaml/xapi/test_common.ml
- ocaml/xapi/test_host_helpers.ml
- ocaml/xapi/xapi.ml
- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_host.mli
- ocaml/xapi/xapi_host_helpers.ml
- ocaml/xapi/xapi_host_helpers.mli
And sync the ISCSI IQN and multipathing config files at startup.
> CP-26457: Make multipath configuration a host parameter

- ocaml/xapi/jbuild
This depends on https://github.com/xapi-project/tapctl/pull/11 and https://github.com/xapi-project/netdev/pull/10.
> CP-24602, CP-24605: Renamed libraries after porting to jbuilder.

- .travis-xenserver-build-env.sh
- ocaml/xapi/context.ml
- ocaml/xapi/context.mli
- ocaml/xapi/create_storage.ml
- ocaml/xapi/suite.ml
- ocaml/xapi/test_cluster.ml
- ocaml/xapi/xapi_cluster.ml
- ocaml/xapi/xapi_cluster_host.ml
- ocaml/xapi/xapi_clustering.ml
Start the cluster daemon when:
* a Cluster_host / Cluster object is created
* on startup when we try to re-enable the Cluster_host
Stop the cluster daemon when:
* we destroy the Cluster_host or Cluster object
In general before any RPC call to the cluster daemon it has to be started.
So remember whether we started it or not, and if we didn't start it when it gets
the first RPC.
We could have made the daemon socket activated, but see CA-265469 systemd
retries don't work with socket activation reliably.
Also modified xenserver-release by dropping our branch to avoid auto-starting on boot.
This avoids having the xapi-clusterd ports open when nothing uses it.
Wrote unit tests for Cluster/Cluster_host creation/destruction with a mock RPC.
Jenkins test pending.
> CP-26197, CP-25397: Do not run xapi-clusterd if clustering is turned off

- scripts/static-vdis
This is required for HA to work correctly after the SMAPIv3 API change that added `uuid` to `SR.attach`, otherwise we fail while enabling HA because we fail to attach the statefile VDI.
Tested on a pool of 2 hosts and I was able to enable HA.
> static-vdis: need to save/pass uuid to SR.attach with SMAPIv3

- ocaml/xapi/xapi_host.ml
> Host.set_iscsi_iqn: reject empty string

- ocaml/xapi/quicktest_vdi_copy.ml
I think the issue is that when we call read_from_vdi and send the HTTP
export_raw_vdi GET request, on the server side we tell vhd-tool to write
the VDI in a given format to the file descriptor, and when it returns,
we unplug & destroy the VBD. Maybe vhd-tool closes the TCP connection
when it finishes and then the client sending the HTTP get request
continues to destroy the VDI, before the VBD is unplugged on the server
side.
> CA-277464: Quicktest_vdi_copy: wait for VBD unplug before destroying VDI

- ocaml/idl/datamodel.ml
- ocaml/xapi/dbsync_slave.ml
- ocaml/xapi/xapi_bond.ml
- ocaml/xapi/xapi_pif.ml
- ocaml/xapi/xapi_tunnel.ml
- ocaml/xapi/xapi_vlan.ml
1. Set PIF.pci of physical PIF to corresponding pci ref when creating
2. Set PIF.pci of vlan master PIF to the PIF.pci of the underlying PIF
3. Set PIF.pci of Bond master or tunnel PIF to Ref.null
4. Refresh PIF.pci on xapi restarting for all kinds of PIFs
> CP-26333 Add PIF.PCI field

- ocaml/xapi/storage_access.ml
Depends on https://github.com/xapi-project/message-switch/pull/37
> CP-26471: Message switch has been renamed after been ported to jbuilder.

- ocaml/xe-cli/bash-completion
To support auto-completion for uuid of network-sriov-*, need to chop off `network-sriov-*` at the second '-' and append the list.
> CP-26430:fix auto-completion error of network-sriov

- .travis-opam-coverage.sh
- Makefile
- ocaml/xapi/jbuild
- ocaml/xapi/suite.ml
- ocaml/xapi/suite_alcotest.ml
- ocaml/xapi/suite_init.ml
- ocaml/xapi/test_valid_ref_list.ml
- xapi.opam
And test Valid_ref_list using alcotest.
> Add suite with alcotest

- .travis-opam-coverage.sh
- xapi.opam
Currently this has to be a normal dependency. To ensure test
dependencies are not compiled into xapi, we'll have to make a new
internal xapi library that the unit test binaries will depend on.
> Make alcotest a non-test OPAM dependency

- ocaml/xapi/xapi_vm_lifecycle.ml
When vm is halted, the reserved virtual function doesn't need anymore, it is needed to clear `reserved_pci` on `vif`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xapi-project/xen-api/3410)
> CP-26014: Clear reserved_pci in vif when vm with sriov vif halted

- ocaml/xapi/cpuid_helpers.ml
- ocaml/xapi/cpuid_helpers.mli
- ocaml/xapi/create_misc.ml
- ocaml/xapi/test_cpuid_helpers.ml
> XOP-908/CA-279498: Zero-extend CPU features when comparing old and new sets

- ocaml/xapi/cli_operations.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_pool.ml
This PR is the second of three which port the licensing daemon to PPX:
1. xcp-idl: [port V6d interface to use PPX](https://github.com/xapi-project/xcp-idl/pull/186)
2. xapi: update references to v6 interface
3. v6d: port daemons to ppx
This PR in particular updates xapi to use the following:
- ppx-based error handling (defined in v6 interface)
- new edition type (defined in v6 interface)
- some formatting changes for readability, as well as whitespace removal and ocp-indent
Note: CP-26098 is part of REQ-417
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xapi-project/xen-api/3391)
> CP-26098: Upgrade xapi to use PPX-based v6d interface

- ocaml/xapi/jbuild
- xapi.opam
This is part of the `opam/next` patches.
> [opam/next] Depend on new tar-unix ocamlfind package

- ocaml/xapi/test_valid_ref_list.ml
- ocaml/xapi/valid_ref_list.ml
This exception is thrown when we use the Client module.
> CA-276638, CA-281320: Catch handle_invalid in Valid_ref_list

- ocaml/xapi/suite.ml
- ocaml/xapi/suite_alcotest.ml
- ocaml/xapi/test_vm_check_operation_error.ml
> Convert Test_vm_check_operation_error to alcotest

- ocaml/xapi/xapi_sr.ml
- ocaml/xapi/xapi_sr_operations.ml
Adding a SR to a large pool(64 hosts) seems very slow which is caused by
serial PBD plug across the pool. This fix is to use async PBD plugwhen creating SR.
By doing this change, I have run Ring3 and Stroage BST which are both
passed(refer to 78821, 78820).
> CA-271491: Creating NFS SR on 64-host pool ~7x slower than 16-host

- scripts/xe-edit-bootloader
Line 41 had a typo removed and extraneous p that broke this script from working.
Signed-off-by: Aaron Davis <aaron.davis@rackspace.com>
> Fixed an issue with device number in script.

- ocaml/xapi/suite_alcotest.ml
- ocaml/xapi/test_common.ml
- ocaml/xapi/test_cpuid_helpers.ml
- ocaml/xapi/test_ha_vm_failover.ml
- ocaml/xapi/test_host.ml
- ocaml/xapi/test_pool_apply_edition.ml
- ocaml/xapi/test_state.ml
- ocaml/xapi/test_vdi_cbt.ml
- ocaml/xapi/test_xapi_xenops.ml
- ocaml/xapi/test_xenopsd_metadata.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_host.mli
- ocaml/xapi/xapi_pool.ml
Testing during the pool-join prechecks is racy, so we now _also_ check in Xapi_host.create
> CA-268763 - additional check for pool_size feature

- ocaml/xapi/xapi_gpumon.ml
- ocaml/xapi/xapi_pgpu.ml
This PR is the second of three to port GPU monitoring daemon gpumon to use PPX-based code generation for RPCs.
1. [Port Gpumon interface](https://github.com/xapi-project/xcp-idl/pull/196)
2. this
3. [Port Gpumon](https://github.com/xapi-project/xen-api/pull/3418)
> CP-26717: Update Xapi to use PPX-based Gpumon IDL

- ocaml/pci/bindings/ffi_bindings.ml
- ocaml/pci/lib/pci.ml
The original code was passing an ocaml managed Buffer as
a buffer for `pciutils` to write the pci names. This can
have unexpected consequences, and in our case was causing
(rare and harmless) segfaults.
As recommended also in [ctypes FAQ](https://github.com/ocamllabs/ocaml-ctypes/wiki/FAQ#-whats-the-best-way-to-bind-c-functions-that-act-on-strings)
we can solve this issue by allocating a C array (that lives
outside the ocaml heap) and use it as the string buffer
expected by the C function. This is still managed by ocaml
and will be freed by the GC once it is no longer in use
but it will not change unexpectedly under our feet.
Signed-off-by: Marcello Seri <marcello.seri@gmail.com>
> CA-266936: Use a CArray instead of an ocaml Buffer

- ocaml/xapi/test_cluster.ml
- ocaml/xapi/xapi_cluster.ml
- ocaml/xapi/xapi_cluster_host.ml
- ocaml/xapi/xapi_clustering.ml
Starting the cluster daemon on the first XAPI RPC call doesn't work when HA is
enabled and we need to start clustering from the static-vdis script before XAPI
is fully operational.
Instead of starting/stopping the clustering daemon from XAPI on boot let systemd
do it: just enable/disable the service when a cluster host is created/destroyed.
This still keeps the semantics we wanted, i.e. when clustering is disabled we do
not have a running clustering daemon.
[I'm running a BVT on an internal branch, we should wait until that completes before merging]
> CA-282012: enable/disable clustering daemon

- ocaml/xapi/nm.ml
- ocaml/xapi/test_common.ml
- ocaml/xapi/test_vlan.ml
- ocaml/xapi/xapi_bond.ml
- ocaml/xapi/xapi_pif.ml
- ocaml/xapi/xapi_pif_helpers.ml
- ocaml/xapi/xapi_tunnel.ml
- ocaml/xapi/xapi_vlan.ml
1. Add Xapi_pif_helpers.ml contains:
+ Add get_pif_type to get PIF type
+ Add X_is_allowed_on_pif serial functions to exectue check before creating
VLAN, bond and tunnel
2. Add support of sriov PIF in nm.bring_pif_up and nm.bring_pif_down
3. Apply Xapi_pif_helpers.get_pif_type in nm.ml
4. Refine VLAN UT
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xapi-project/xen-api/3431)
> CP-25699 Refine PIF type check related stuff

- ocaml/xapi/xapi_vm_migrate.ml
When a VM shuts down or reboots during storage migration, the VGPU field
scheduled_to_be_resident_on is reset. This makes it impossible to
compute the VGPU map required for the migration. With this commit, we
don't try to recover from this but let the migration fail.
* CA-281002
* CA-271406
> CA-281002 CA-271406 let XSM+vGPU fail if VM reboots

- ocaml/xapi/storage_access.ml
- ocaml/xapi/storage_access.mli
- ocaml/xapi/test_sr_update_vdis.ml
- ocaml/xapi/xapi_sr.ml
- ocaml/xapi/xapi_vdi.ml
- scripts/static-vdis
This is part of the SMAPIv3 interface  change from `feature/REQ477/master` branch.
Also expose the `sharable` field to SMAPIv3 (required for the HA statefile and redolog), internally XAPI already tracked this field. SMAPIv1 looked in `sm-config` to find this out, no change there.
This PR needs to be merged together with these ones otherwise the build breaks:
https://github.com/xapi-project/sm-cli/pull/26
https://github.com/xapi-project/xapi-storage/pull/70
https://github.com/xapi-project/xapi-storage-script/pull/56
https://github.com/xapi-project/xcp-idl/pull/202
Build on internal branch `private/edvint/477-idl-part2`. The `feature/REQ477/master` branch that these commits were part of had 2 full nightlies run on it, please let me know what kind of tests should be run on these reduced set …
> [477 idl part2] SR.create API change and sharable flag

- ocaml/xapi/xapi_vm_migrate.ml
When a VM shuts down or reboots during storage migration, the VGPU field
scheduled_to_be_resident_on is reset. This makes it impossible to
compute the VGPU map required for the migration. With this commit, we
don't try to recover from this but let the migration fail.
* CA-281002
* CA-271406
> RFC - CA-281002 CA-271406 let XSM+vGPU fail if VM reboots

- ocaml/xapi/xapi.ml
`Xcp_coverage.dispatcher_init` only initializes the message-switch dispatcher
for  coverage messages, but doesn't make XAPI listen for such messages itself.
This meant that xenopsd was collecting coverage info, but XAPI was not.
> CP-20544: initialize coverage for XAPI itself too

- ocaml/xapi/xapi_xenops.ml
Three commits in this PR:
1. Support network SR-IOV VF backed vif. Add a new function to get backend of vif.
2. Add PCIs of network SR-IOV VFs into metadata.
3. Enhance backend_of_network function to reduce duplicate DB access.
Signed-off-by: Ming Lu ming.lu@citrix.com
> CP-25795: Add new VIF backend for network SR-IOV

- README.markdown
This PR seeks to update the information a newcomer would see when looking to either build or contribute to xapi, such as:
- the maintainers list (switched out for mailing list address)
- the OCaml version Xapi builds on
- build instructions (may be worth removing these too?)
> Update readme and maintainer info

- ocaml/xapi/storage_access.ml
- ocaml/xapi/storage_access.mli
- ocaml/xapi/xapi_vdi.ml
We use vdi_info_of_vdi_rec to ensure that the vdi_info we pass down to
SMAPIv2 contains the correct information about the VDI.
Previously when we were debugging an issue, we were looking at the
vdi_info printed out by SMAPIv2, and it was misleading as many of the
fields, such as is_a_snapshot and cbt_enabled, were incorrect because
they were just taken from the default_vdi_info.
I determine the snapshot time in SMAPIv2, to ensure that in the vdi_info
we only have to pass down the fields of the snapshotted VDI, not the new
fields of the snapshot. This means that SMAPIv3 plugins will also have
to set the snapshot time correctly, instead of relying on the old
behaviour.
>  VDI.snapshot, clone: pass down complete vdi_info 

- ocaml/xapi/export.ml
- ocaml/xapi/importexport.ml
This record may contain data, e.g. perfmon settings in other-config, that we would like to keep in the pool. Previously, the dom0 record was recreated in the pool after xapi first restart as a slave.
> CA-280981: Import dom0 record on pool join

- ocaml/xapi/context.ml
- ocaml/xapi/context.mli
- ocaml/xapi/helpers.ml
- ocaml/xapi/mock_rpc.ml
- ocaml/xapi/network_event_loop.ml
- ocaml/xapi/quicktest_storage.ml
- ocaml/xapi/test_event_common.ml
- ocaml/xapi/test_network_event_loop.ml
- ocaml/xapi/test_vdi_cbt.ml
- ocaml/xapi/test_xapi_xenops.ml
- ocaml/xapi/xapi_vdi.ml
- ocaml/xapi/xapi_xenops.ml
CP-24206: check snapshot works when VDI is activated on different hosts
CA-271525: Add a test_rpc field to the context
CA-271525: Move over all uses of 'test_mode' to use the mock rpc function instead.
> [From REQ-477] Cherry-pick testing changes around SMAPIv3

- ocaml/xapi/test_vdi_cbt.ml
> Simplify & speed up data_destroy timing tests

- ocaml/database/database_server_main.ml
- ocaml/database/database_test.ml
- ocaml/database/database_test.mli
- ocaml/database/db_cache_impl.ml
- ocaml/database/db_interface.ml
- ocaml/database/db_remote_cache_access_v1.ml
- ocaml/database/db_remote_cache_access_v2.ml
- ocaml/database/db_rpc_client_v1.ml
- ocaml/database/db_rpc_client_v2.ml
- ocaml/database/db_rpc_common_v1.ml
- ocaml/database/jbuild
- ocaml/database/schema.ml
- ocaml/database/test_schemas.ml
> Resurrect a database unit test

- ocaml/tests/suite_init.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/storage_impl.ml
- ocaml/xapi/xapi_ha.ml
- ocaml/xapi/xapi_pool_helpers.ml
- ocaml/xapi/xapi_pool_helpers.mli
- ocaml/xapi/xapi_sr.ml
- CP-24688: Refactor `with_pool_operation` to be easily testable
- Storage_impl: drop dead code 
- CA-271525: Log everything from the unit-test suite
- CA-272147: Fix SR.set_name_label and _description for SMAPIv3
- CA-277346: log backtrace when parsing HA liveset
The first commit needed a small fix due to the change in Datamodel, the others applied cleanly.
> [From REQ-477] Cherry-pick a few miscellaneous changes 

- ocaml/xapi/alcotest_comparators.ml
- ocaml/xapi/suite.ml
- ocaml/xapi/suite_alcotest.ml
- ocaml/xapi/test_cluster.ml
- ocaml/xapi/test_cluster_host.ml
This enables cleaner test output and follows the initiative to move away from OUnit in favour of Alcoport for toolstack unit tests.
> Port test_cluster and test_cluster_host to Alcotest framework

- ocaml/quicktest/quicktest_vdi_copy.ml
Quicktest_vdi_copy: clean up (destroy VDIs created by this test like the others do)
CA-277464: Quicktest_vdi_copy: wait for VBD unplug before destroying VDI
> [From REQ-477] Quicktest_vdi_copy: Wait for VBD unplug and destroy VDIs created by this test

- ocaml/xapi/xapi_network_sriov_helpers.ml
- ocaml/xapi/xapi_pci.ml
- ocaml/xapi/xapi_pgpu.ml
1. Update virtual/physical function relations when updating pci devices
2. call update_pci after bring up/down sriov logical pifs
3. refine gpu code of updating pgpu records, eliminate the annoying side effect
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xapi-project/xen-api/3465)
> CP-27001 Update pci status after enable/disable sriov

- ocaml/xapi/helpers.ml
- ocaml/xapi/sm.ml
- ocaml/xapi/static_vdis.ml
- ocaml/xapi/storage_access.ml
- ocaml/xapi/storage_impl.ml
- ocaml/xapi/storage_migrate.ml
- ocaml/xapi/storage_mux.ml
- ocaml/xapi/storage_utils.ml
All applied cleanly on master.
> [from-REQ-477] allow SMAPIv3 VDI snapshots to run on hosts other than the master

- ocaml/xapi/xapi_network_sriov.ml
- ocaml/xapi/xapi_vif_helpers.ml
- ocaml/xapi/xapi_vm.ml
The following operations must be blocked if the pool is not licensed appropriately
Enabling SR-IOV on a NIC.
Configuring a VM to use an SR-IOV VF. 
Starting a VM that is configured to use an SR-IOV VF. 
> CP-23782: Add license restriction for SRIOV usage

- ocaml/idl/datamodel_host.ml
- ocaml/tests/suite.ml
- ocaml/tests/test_common.ml
- ocaml/tests/test_host_helpers.ml
- ocaml/tests/test_sm_features.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/records.ml
- ocaml/xapi/smint.ml
- ocaml/xapi/xapi.ml
- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_host.mli
- ocaml/xapi/xapi_host_helpers.ml
- ocaml/xapi/xapi_host_helpers.mli
- scripts/xe-set-iscsi-iqn
This adds the iSCSI IQN functionality and multipatching changes (they were closely intertwined, and only 2 commits were identified initially as multipathing anyway so I combined them here).
Note that the changes to `datamodel.ml` in a few commits were manually patched into `datamodel_host.ml` since the split was done since those commits were made.
> [From REQ-477] Cherry-pick addition of iSCSI IQN and multipathing changes

- ocaml/idl/datamodel_host.ml
- ocaml/xapi-client/jbuild
- ocaml/xapi-client/tasks.ml
- ocaml/xapi-client/tasks.mli
- ocaml/xapi/cli_frontend.ml
- ocaml/xapi/cli_operations.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/vm_evacuation.ml
- ocaml/xapi/xapi_ha.ml
- ocaml/xapi/xapi_ha.mli
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_host.mli
- ocaml/xapi/xapi_host_helpers.ml
- ocaml/xapi/xapi_host_helpers.mli
- ocaml/xapi/xapi_pbd.ml
- ocaml/xapi/xha_scripts.ml
- scripts/xapi-domains.service
- xapi-client.opam
** Do not merge before #3470, that adds an mli file that I need to make a change to here, will need to fix after rebasing after that merges**. This builds because that mli file doesn't exist on master, once it's there I'll need to add the change to it. It's added over a few commits in #3470 though, more straightforward to rebase later.
Again, adding this one despite the rebase and small fix needed because it's significant changes and would appreciate feedback! Needed a fair bit of manual tweaking around the pbd.ml (untangling clustering related changes from the bug fixes) and the datamodel due to the split.
- CA-274585: allow unplugging statefile VDI 
- CA-274585: unplug all local PBDs on shutdown/reboot 
- CP-24693: Tasks.with_tasks_destroy: add a function that waits for tasks with a …
> [From REQ-477] Cherry-pick of shutdown changes

- ocaml/idl/datamodel.ml
- ocaml/xapi-consts/api_errors.ml
- ocaml/xapi/db_gc_util.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/sync_networking.ml
- ocaml/xapi/sync_networking.mli
- ocaml/xapi/xapi.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_host.mli
- ocaml/xapi/xapi_pif.ml
- ocaml/xapi/xapi_pool.ml
1. Add network sriov precheck for pool join
2. Sync network sriov from master to slave after join
3. Gc sriovs when gc PIFs
4. Best effort bring up sriov logical PIFs when xapi start
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xapi-project/xen-api/3474)
> CP-26022 SR-IOV pool join/leave

- ocaml/tests/suite.ml
- ocaml/tests/suite_alcotest.ml
- ocaml/tests/test_clustering.ml
- ocaml/tests/test_clustering_allowed_operations.ml
Motivation: Alcotest allows for cleaner error reporting and debugging. Additionally, I will be submitting a PR that adds a unit test to test_clustering which is written in Alcotest, hence a port was necessary.
Changes in test_clustering:
- `assert_equal` now uses an Alcotest comparator
- every individual unit test is now a toplevel function
Changes in test_clustering_allowed_operations:
- OUnit.assert_bool -> Alcotest.(check bool)
> Port test_clustering to Alcotest

- ocaml/idl/datamodel.ml
- ocaml/idl/datamodel_vm.ml
> Fix release info for domain_type fields

- ocaml/xapi/binpack.ml
- ocaml/xapi/xapi_sr.ml
- ocaml/xapi/xapi_sr_operations.ml
On branch REQ-503, there are two CA tickets fixed and staging
CA-270622: HA max tolerance is wrong for >16-host pools (PR: https://github.com/xapi-project/xen-api/pull/3416)
CA-271491: Creating NFS SR on 64-host pool ~7x slower than 16-host (PR: https://github.com/xapi-project/xen-api/pull/3422)
This PR is to merge the fix to master.
Ring3 BST (suite 80506) has run and passed on REQ-503 branch.
> Merge REQ-503 to master.

- ocaml/database/jbuild
I need this fix (and another in xs-opam) to be able to run `jbuilder utop ocaml/xapi` and triage issues using the xapi internals.
> database: resurrect additional test

- ocaml/idl/datamodel_host.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/sync_networking.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_host.mli
- ocaml/xapi/xapi_pif.ml
Two commits:
CP-27381: Auto-plug SR-IOV physical PIF 
This change aims to bring up physical SR-IOV PIF when plugging logical
SR-IOV PIF. Because we observed that if a physical PIF is unplugged, and 
SR-IOV on this physical PIF can be enabled, but the generated VFs can 
not be used by VM due to the physical PIF's interface is down.
CP-27329: Make Network SR-IOV Sync Do Plug on Slave
During reboot of a slave XenServer in a pool, XAPI logic on slave will
try to synchronize some networks from master. These networks include
bond, sriov, vlan, and tunnel. There is a difference between bond/sriov
and vlan/tunnel: the sync of bond/sriov is done on slave host, while the 
sync of vlan/tunnel is done on master host. This is because sync of
vlan/tunnel is just to create DB objects without plug. …
> CP-27381: Auto-plug SR-IOV physical PIF; CP-27329: Make Network SR-IOV Sync Do Plug on Slave

- ocaml/tests/test_vm_helpers.ml
- ocaml/xapi/xapi_network_sriov_helpers.ml
- ocaml/xapi/xapi_vm_helpers.ml
This is a fix for host selection and reserve VF when vm without sr-iov VIF.
The function `get_local_underlying_pif ` was called in `assert_netsriov_available` and `reserve_sriov_vfs`.
These two functions will be called unconditionally when host selection and after selection to reserve VFs, so `get_local_underlying_pif ` should not raise an exception when no pif found due to exn will impacts VM start which hasn't sr-iov VIF.
> CP-27272: Fix for VM without SR-IOV VIFs start failed

- ocaml/tests/test_clustering.ml
- ocaml/xapi/xapi_pif.ml
Previously, `PIF.set_disallow_unplug` raised `clustering_enabled_on_network` even when trying to set to the same value, if cluster objects were found, causing tests to fail unnecessarily. This PR makes `PIF.set_disallow_unplug` idempotent and updates the relevant tests to check this new behaviour.
> CA-285605: Make PIF.set_disallow_unplug idempotent

- ocaml/idl/datamodel.ml
- ocaml/quicktest/quicktest.ml
- ocaml/quicktest/quicktest_cluster.ml
- ocaml/xapi/xapi_pif.ml
CA-282006 raises the issue of host fencing when trying to reconfigure IP on a live cluster network. This PR asserts no clustering is enabled on the chosen network for calls such as `PIF.reconfigure_IP(v6)`. and `PIF.forget`, as well as adding the relevant errors to the datamodel for these calls.
> CA-282006: Prevent IP reconfiguration on a live cluster network

- ocaml/tests/suite.ml
- ocaml/tests/suite_alcotest.ml
- ocaml/tests/test_ca91480.ml
- ocaml/tests/test_gpu_group.ml
- ocaml/tests/test_no_migrate.ml
- ocaml/tests/test_pool_apply_edition.ml
- ocaml/tests/test_pool_update.ml
- ocaml/tests/test_pusb.ml
- ocaml/tests/test_pvs_proxy.ml
- ocaml/tests/test_pvs_site.ml
- ocaml/tests/test_vlan.ml
- ocaml/tests/test_vm_migrate.ml
Spent a lot of time on trains lately, so ported the following unit tests from OUnit to the Alcotest framework:
- test_vm_migrate
- test_ca91480
- test_no_migrate
- test_gpu_group
- test_pool_update
- test_pusb
- test_pool_apply_edition
- test_pvs_site
- test_pvs_proxy
> Port unit tests to Alcotest

- ocaml/quicktest/quicktest.ml
- ocaml/quicktest/quicktest_common.ml
- ocaml/quicktest/quicktest_storage.ml
As a result of the recent REQ-477 PR review, it was suggested to make the following switch:
- `-only-sr [name-label]`: former flag, only ran quicktests on SRs with a matching `name-label` field
- `-default-sr`: replacement flag, only runs quicktests on the pool's default SR
This flag is passed to all relevant quicktests which iterate through SRs. Currently this only includes the CBT and storage quicktests.
> CA-285349: replace -only-sr quicktest flag with -default-sr

- ocaml/xapi/xapi_cluster_host.ml
- ocaml/xapi/xapi_cluster_host.mli
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_pbd.ml
As per the GFS2 PR review, this change splits `Xapi_pbd.unplug_all_pbds` into two separate internal functions; one to unplug all PBDs and one to disable clustering, allowing for better decoupling of these functions. The external `Xapi_pbds.unplug_all_pbds` interface and logic is unchanged.
> CA-285349: split `unplug_all_pbds` into two internal functions

- ocaml/xapi/helpers.ml
In function `timebox`, we create a new thread to handle the real stuff, but once
the stuff hangs forever, it will result in fd of one endian of the pipe leak.
So if the stuff times out, close the fd and ignore any exception if occurs. (The
main and new thread may close the fd at the same time once the stuff finished suddenly.)
> Eliminate fd leak in timebox

- ocaml/xapi/xapi_xenops.ml
The background logic is that XAPI will try to construct all information
on a VM as metadata and push this metadata to Xenopsd to manage the VM.
Particularly the logic on vifs are: for the `start` of VM, XAPI will try
to push all vifs, no matter attached or not, to Xenopsd; while for the
`reboot` of VM, it will try to push the vifs which are currently
attached only.
SR-IOV VF backed vifs should follow same logic. This means XAPI should
not push the VFs' PCIs which are backend of un-attached vifs also.
This fix adds a filter on contructing PCI metata to filter out the vifs
which are backed by VF PCIs and currently un-attached.
> CA-285897: Filter out un-attached VF-backed vifs in PCI metadata

- ocaml/xapi/xapi_vm_lifecycle.ml
- ocaml/xapi/xapi_vm_migrate.ml
If a VM is not running, then we don't have to worry about being able to
live-migrate its vGPUs, so don't bother checking if the vGPU supports it.
Note that the `migrate_send` operation in use for VM.migrate_send, but also for
VDI.pool_migrate.
> CA-284492: Ignore vGPU live-migratability in migrate_send for halted VMs

- ocaml/xapi/xapi_clustering.ml
- ocaml/xapi/xapi_globs.ml
- scripts/xapi.conf
> CA-280423: Open/close xapi-clusterd port when starting/stopping daemon

- ocaml/tests/test_xapi_xenops.ml
start is not present in xenopsd anymore
I missed this when testing the xenopsd changes.
> xapi-xenops test: call WorkerPool.set_size instead of WorkerPool.start

- ocaml/xapi/xapi_cluster.ml
- ocaml/xapi/xapi_cluster_host.ml
- ocaml/xapi/xapi_cluster_host.mli
- ocaml/xapi/xapi_pbd.ml
The current `Xapi_cluster.pool_resync` function duplicates existing logic from `Xapi_clustering.create_as_necessary`, so the following changes were made:
- use `create_as_necessary` instead of duplicating code
- move this and host-enabling logic to `Xapi_cluster_host.host_resync` function (also add to interface)
- iterate over `host_resync` in `pool_resync`
- add logging
(This has passed all unit tests and the GFS2 BVT)
> [REQ477] CA-286294: Refactor pool_resync, add best-effort host_resync

- ocaml/xapi/xapi_host_helpers.ml
In a pool, restarting the toolstack on a slave will go through two
stages: first shutting down, and next booting up again.  In the
shutting-down stage, Host.enabled will be set as false. Then in the
booting-up stage, XAPI will set it back to true in the 'initialising
storage' step.
The bug to be fixed in this ticket is that the allowed_operations of
the slave host is not updated correspondingly when setting 
Host.enabled back to true while booting up.
> CA-281178: Update allowed operations in consider_enabling_host

- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_vbd.ml
- scripts/Makefile
- scripts/nbd_client_manager.py
- scripts/static-vdis
> Merge of qemu-datapath into REQ477/master branch

- ocaml/idl/datamodel.ml
> Fix typo of `modprobe`

- ocaml/tests/test_host_helpers.ml
- ocaml/xapi/helpers.ml
- ocaml/xapi/xapi_host_helpers.ml
- ocaml/xapi/xapi_host_helpers.mli
When the pool is in RPU mode we no longer try to call `host.set_iscsi_iqn`
or `host.set_multipathing` if the database is inconsistent. When the pool
exits RPU mode we then run through the consistency check for all hosts and
do any calls that are necessary.
> CA-285596: Suppress host.set_iscsi_iqn during RPU

- ocaml/xapi/xapi_bond.ml
- ocaml/xapi/xapi_pif.ml
- ocaml/xapi/xapi_pif.mli
When creating bond, ensure slave PIF are not participating FCOE.
> CA-260638 Bonds are created on interfaces which participates in FCoE

- ocaml/xapi/xapi_vm_helpers.ml
When VM with GPU implementing VDI migration, resources (memory and Vgpu)
will be reserved and then Vgpu and memory checks will be performed, when
Vgpu has big size, checks will fail with no remaining capacity.
This fix aims to check there has 'non_allocated' vgpus before check the
GPU resources.
> CA-282684: VDI migration with vGPU is failing when vGPU size is big

- ocaml/xapi/xapi_cluster_host.ml
If HA enabled on pool:
- set ha_cluster_stack to "corosync" when enabling clustering
- set ha_cluster_stack to "xhad" when disabling clustering
Linebreak separates assertions from API call logic
> CA-281638: Set Pool.ha_cluster_stack when enabling/disabling clustering

- ocaml/xapi/xapi_sr.ml
- Added an assertion for SR.probe as it is currently only safe with clustering enabled. 
- Wrapped `Xapi_sr.call_probe` (called by both `SR.probe` and `SR.probe_ext`) in a clustering lock in case the SR is in use elsewhere to prevent database inconsistency
- Removed local opens of `Storage_interface` and `Storage_access`
> CP-27343: SR probe: add clustering lock, assert cluster_host enabled

- ocaml/xapi/xapi.ml
In the stunnel connection retry loop a new hook has been added to allow
for a test to be run before going around the loop. This commit populates
the hook with a function to check for host_metrics.live so that if a
host has been marked as dead we exit the retry loop quickly.
> CA-285840: Check for host liveness in the new stunnel hook

- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_cluster.ml
- ocaml/xapi/xapi_cluster_host.ml
- ocaml/xapi/xapi_clustering.ml
This PR adds logging to Cluster and Cluster_host API calls where necessary, as well as updating existing log comments to provide object OpaqueRefs where possible.
In particular, debugging comments indicate whether an API call returned successfully, to make the logs more explicit, such as clearly indicating that an error occurred during the specific API call before a backtrace is logged.
> [REQ477] CP-27544: Add/modify cluster logging

- ocaml/xapi/cli_operations.ml
- ocaml/xapi/records.ml
> Hyphenate xe clustering params instead of using underscores

- ocaml/xapi/xapi_vbd_helpers.ml
If operations of VBD's VDI is not copy(mirror), then the log will shows
"VBD operation  not allowed because VDI.current-operations =    "
unconditionally, this is wrong because only attach/plug/insert will be blocked
for VBD, other operations will succeed and also with the confusing log.
> CA-267687: Logs of VBD operation check that inspects operations of VBD's VDI do not match returned errors

- ocaml/xapi/server_helpers.ml
When master forward a task to slave, slave will mark the task as completed once
finish processing it, however when master finishing the forwarding, it will also
mark the task as completed. Furthermore, when slave finished the task, that does
not mean the task is done, there may be some stuff that master has to handle, so
we have to ensure the task only complete once the master finish its work.
> CA-287863: xe vm-shutdown complete the task too early

- ocaml/idl/datamodel_common.ml
- ocaml/xapi/vm_platform.ml
- ocaml/xapi/xapi_db_upgrade.ml
- ocaml/xapi/xapi_vm_helpers.ml
The commits implement that imported and existing VMs use Device Model "qemu-upstream-compat". The change is implemented in ensure_device_model_profile_present() that either assigns this as the new default, or updates an existing device model. This function is also called during a xapi upgrade.
> CP-27560 move to Device Model "qemu-upstream-compat"

- ocaml/idl/datamodel.ml
- ocaml/idl/datamodel_errors.ml
- ocaml/xapi/xapi_ha.ml
- ocaml/xapi/xapi_vusb.ml
The API erros at least need to be correct because they are visible to the users and exposed on the UI.
> Cannot is one word.

- ocaml/xapi/xapi_message.ml
It was claiming that 11428 > 11428.
`Apr 13 17:48:00 xrtuk-08-03 xapi: [debug|xrtuk-08-03|135913 INET :::80|event.from D:1764185364b8|xapi] get_since_for_events: last_in_memory (11428) > since (11428): Using slow message lookup`
If you look at the code this is reached when `last_in_memory >= since`, and I think the code is correct: if the last message you have is equal to since, i.e. you do not have anything older then you cannot be sure whether you have all the messages with `t=since` because some of the messages that do not fit into the cache might have `t=since` too, thus you have to fall back to the slow lookup.
I think the code is doing the right thing
> CA-287929: fix incorrect log message (11428 > 11428)

- ocaml/tests/test_cluster.ml
- ocaml/tests/test_clustering.ml
- ocaml/xapi/cluster_stack_constraints.ml
- ocaml/xapi/xapi_cluster.ml
- ocaml/xapi/xapi_cluster_host.ml
- ocaml/xapi/xapi_clustering.ml
This is a follow-up to my previous PR [here](https://github.com/xapi-project/xen-api/pull/3539), which set the pool's HA cluster stack for `Cluster_host.enable/disable`. Unfortunately this wasn't enough to automatically update the value, so now this PR should cover the introduction and destruction of a cluster, along with enabling and disabling clustering.
Note: I'm adding unit tests _but_ they use a change made [in this PR](https://github.com/xapi-project/xen-api/pull/3554), which should be merged first.
> CA-281638: Set pool.ha_cluster_stack for Cluster.create/destroy

- ocaml/tests/test_storage_migrate_state.ml
- ocaml/xapi/storage_migrate.ml
This PR fixes 2 issues in 2 commits:
1. when recover SXM state from persistent files, we just recover the data of `Send_state` in case of wrong format of code of `try...with...`
2. When executing SXM, the time window between dp creation and persistent is large,
it is possible lead to dp leak if xapi restarted in the time window.
Aiming to mitigate the impact of this issue, this change persistents the dp
before we sending it to remote to shrink the time window.
> CA-244573 XenMotion fails after previously attempted SXM is interrupted by XAPI restart and vm goes into suspended state 

- ocaml/tests/suite.ml
- ocaml/tests/suite_alcotest.ml
- ocaml/tests/test_network_event_loop.ml
- ocaml/xapi/network_event_loop.ml
> Convert test_network_event loop_alcotest and avoid calling the firewall script with repeated interfaces

- scripts/set-hostname
This is no longer required. The following call to `hostnamectl` sets the
current hostname, and also updates `/etc/hostname` to persist it.
> CA-288312: Don't update HOSTNAME in /etc/sysconfig/network

- ocaml/tests/suite.ml
- ocaml/tests/suite_alcotest.ml
- ocaml/tests/test_network.ml
- ocaml/tests/test_pci_helpers.ml
- ocaml/tests/test_pgpu.ml
- ocaml/tests/test_pool_db_backup.ml
- ocaml/tests/test_pool_restore_database.ml
- ocaml/tests/test_workload_balancing.ml
- ocaml/tests/test_xapi_db_upgrade.ml
Ported a few simpler tests while waiting around for a build. We should make a list of which would be the most useful tests to port somewhere.
> Port some Xapi unit tests from OUnit to Alcotest framework

- ocaml/xapi/xapi_xenops.ml
This fixes a regression introduced in the fix for XOP-830,
where `add_caches` got dropped from the startup resynchronization logic.
This resulted in periodic writes to the database, which are especially
bad with redo log (or implicitly with HA) turned on.
> CA-288411: make the cache work after a toolstack restart

- ocaml/idl/ocaml_backend/gen_rbac.ml
- ocaml/rfb/rfb_randomtest.ml
- ocaml/xapi-cli-protocol/cli_protocol.ml
- ocaml/xapi-client/tasks.ml
- ocaml/xapi/cli_progress_bar.ml
- ocaml/xapi/extauth_plugin_ADpbis.ml
- ocaml/xapi/rbac_audit.ml
- ocaml/xapi/record_util.ml
- ocaml/xapi/sparse_encoding.ml
- ocaml/xapi/storage_mux.ml
- ocaml/xapi/xapi_pif.ml
- ocaml/xapi/xapi_sm.ml
This will not solve all the warnings, but it moves slowly in the direction that we need to make xapi safe-string compliant and warning free
> Reduce amount of deprecation warnings when compiling xapi

- ocaml/tests/suite.ml
- ocaml/tests/suite_alcotest.ml
- ocaml/tests/test_bond.ml
- ocaml/tests/test_host_helpers.ml
- ocaml/tests/test_network_sriov.ml
- ocaml/tests/test_pvs_server.ml
- ocaml/tests/test_sr_update_vdis.ml
- ocaml/tests/test_tunnel.ml
- ocaml/tests/test_xapi_vbd_helpers.ml
- ocaml/tests/test_xapi_xenops.ml
Porting the remaining OUnit tests that don't use test_highlevel, as this will require a separate port.
>  CP-27911: Alcotest unit test ports

- ocaml/xapi/create_storage.ml
- ocaml/xapi/storage_access.ml
In CA-289140 I've run SR.forget on a shared SR at the same time as another host was booting in the pool. That host did a `Helpers.get_my_pbds`, got a list of PBDs, then SR.forget ran and deleted a PBD, followed by an exception when `plug_all_pbds` tried to plug the PBD that no longer existed.
Ignoring not found errors on PBD plug on startup would avoid these race conditions. Another possibility would be to block the SR.forget itself while any host is booting via `blocked_operatiosn`, but that would risk the operation to be blocked forever if a host fails to boot completely (e.g. crashes).
> CA-289140: fix host boot when run concurrently with SR.forget

- ocaml/quicktest/quicktest.ml
- ocaml/quicktest/quicktest_vdi_copy_data_integrity.ml
- scripts/nbd_client_manager.py
Merge with https://github.com/xapi-project/vhd-tool/pull/56
Keep track of the mapping of the connected /dev/nbdX NBD devices to the
Unix domain socket of the server and the exportname used for the
connection. This allows sparse_dd to look up the NBD connection details
based on the NBD device it receives, then it can extract the list of
allocated extents to copy from the NBD server using the BLOCK_STATUS NBD
extension.
Also, add randomized quicktest to check VDI.copy data integrity
>  CA-287921: nbd_client_manager: track nbd device -> nbd server mapping 

- ocaml/xapi/cancel_tasks.ml
- ocaml/xapi/xapi_vdi.ml
Speed up VDI allowed operations checks with this one weird trick! This is the performance speedup the perf team don't want you to see!
Tested on a pool with ~15000 VDIs and ~15000 VBDs
Before: 
```
May  2 13:35:12 xrtmia-07-26 xapi: [debug|xrtmia-07-26|0 |dbsync (update_env) R:89bd2ce97526|dbsync] Updating allowed operations: VDI
May  2 13:42:53 xrtmia-07-26 xapi: [debug|xrtmia-07-26|0 |dbsync (update_env) R:89bd2ce97526|dbsync] Finished updating allowed operations: VDI
```
(461 seconds)
After:
```
May  2 13:46:59 xrtmia-07-26 xapi: [debug|xrtmia-07-26|0 |dbsync (update_env) R:37ad9661e80b|dbsync] Updating allowed operations: VDI
May  2 13:47:36 xrtmia-07-26 xapi: [debug|xrtmia-07-26|0 |dbsync (update_env) R:37ad9661e80b|dbsync] Finished updating allowed operations: VDI
```
(37 seconds) …
> Speed up update_all_allowed_operations: VDI

- ocaml/tests/suite.ml
- ocaml/tests/suite_alcotest.ml
- ocaml/tests/test_sdn_controller.ml
> CP-27911: Port test_sdn_controller to Alcotest

- ocaml/pci/lib_test/jbuild
This should fix the ocaml side of xapi Travis tests. I am still investigating how to fix python's tests
> pci/lib_test: disable tests until we move back to upstream library

- ocaml/quicktest/quicktest_cluster.ml
- ocaml/tests/test_clustering_allowed_operations.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi.ml
- ocaml/xapi/xapi_cluster_helpers.ml
- ocaml/xapi/xapi_cluster_host.ml
- ocaml/xapi/xapi_cluster_host_helpers.ml
- ocaml/xapi/xapi_pool_helpers.ml
Prevent all clustering operations during a rolling pool upgrade, wrap all clustering calls in a clustering lock, and add a test to check for this.
> CP-25121, CP-26147: Prevent clustering operations during rolling pool upgrade or concurrently

- ocaml/tests/test_pool_cpuinfo.ml
- ocaml/xapi/create_misc.ml
- ocaml/xapi/helpers.ml
- ocaml/xapi/xapi_vm_helpers.ml
This field should be the intersection of the HVM-specific feature sets over all
hosts in the pool that can actually run HVM guests.
The `host.cpu_info:features_hvm` field of non-HVM-capable hosts is a string
with just zeros: no features. Therefore, the intersection currently ends up
disabling all features for HVM guests in the entire pool (including for HVM
capable hosts), which is obviously not what we want.
> Base pool.cpu_info:features_hvm on HVM-capable hosts only

- ocaml/idl/datamodel.ml
There are some calls, such as VDI.db_introduce and SR.set_physical_utilisation, that are publicly visible, but can only be called by SM, because we call Sm.assert_session_has_internal_sr_access in message forwarding for these functions. We should make these hidden by setting hide_from_docs to true in the datamodel. Going through all of the 'should be hidden' APIs is outside the scope of this ticket. This ticket only concerns hiding the public SR and VDI function that are only callable by SM.
Please refer to the ticket for more discussion.
> CA-275120: XenAPI methods only callable by SM are publicly visible

- ocaml/xapi-consts/api_messages.ml
- ocaml/xapi/xapi_cluster_host.ml
`Cluster_host.resync_host` is iterated over all hosts in a pool by `Cluster.pool_resync`, and is also called at startup as part of the task `resync cluster host state`.
Question: should the new messages have a different priority? Also open to suggestions to make the formatting less awful.
> CP-26199: Send alerts when Cluster_host.resync_host fails

- ocaml/idl/datamodel_cluster.ml
- ocaml/idl/datamodel_cluster_host.ml
- ocaml/idl/datamodel_common.ml
- ocaml/tests/test_cluster_host.ml
- ocaml/tests/test_common.ml
- ocaml/xapi/db_gc_util.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/records.ml
- ocaml/xapi/xapi_cluster.ml
- ocaml/xapi/xapi_cluster_host.ml
- ocaml/xapi/xapi_cluster_host.mli
- ocaml/xapi/xapi_hooks.ml
- ocaml/xapi/xapi_host.ml
Introduced a new API `Cluster_host.forget`, because declare dead already has a different semantics in Xen API (see comments in commit message for full details).
There is this outstanding TODO on which I'd like some thoughts: "although things could go wrong if we try to join a host with the same IP as one that we are trying to declare as dead... (which can happen due to DHCP)."
If we have 2 hosts dead, declare one of them as dead (it gets added to pending forget), and then try to join a new node which reuses the same IP before marking the 2nd host as dead then we can't really tell the difference between the newly joined host and the one declared as dead.
> CP-27172: Implement Host.destroy integration with clustering daemon

- ocaml/idl/datamodel_cluster.ml
- ocaml/idl/datamodel_common.ml
- ocaml/tests/test_cluster_host.ml
- ocaml/tests/test_common.ml
- ocaml/xapi/records.ml
- ocaml/xapi/xapi_cluster.ml
- ocaml/xapi/xapi_db_upgrade.ml
Use same units for object default value and parameter default value, see commit message for explanation.
Tested by installing latest feature branch build, replacing xapi, and it has correctly updated the field in the database. The next time we build an SDK and rebuild XenCenter then XenCenter should get the correct value as well.
> CA-290471: fix wrong token timeout in XenCenter

- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_db_upgrade.ml
- ocaml/xapi/xapi_vm_helpers.ml
- ocaml/xapi/xapi_vm_snapshot.ml
A snapshot stores all relevant VM meta data inside VM.snapshot_metadata
which contains a platform value, which in turn contains a device model
profile. This needs to be updated when xapi's database is updated but so
far was not. Confusingly, the VM.platform field of a snapshot is not
used when restoring a snapshot. This commit updates the device model
profile inside the snapshot metadata.
Snapshot meta data is encoded as an s-expression. Updating it thus
requires decoding, updating, and encoding it again.
This fix also pulls in CA-290874 from the master branch to make sure the domain
type is handled correctly in snapshots.
>  CA-290006 update snapshot device model profile

- ocaml/tests/test_cluster_host.ml
- ocaml/tests/test_clustering.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_cluster.ml
- ocaml/xapi/xapi_cluster_host.ml
- ocaml/xapi/xapi_clustering.ml
- ocaml/xapi/xapi_ha_vm_failover.ml
- ocaml/xapi/xapi_pbd.ml
- ocaml/xapi/xapi_sr.ml
This was useful in debugging problems with @minishrink PR.
> CP-28406: improve logging and error checking in clustering functions

- ocaml/tests/test_cluster.ml
- ocaml/xapi-consts/constants.ml
- ocaml/xapi/xapi_cluster.ml
Just as the default cluster token timeout values are stored as constants rather than inline, it makes sense to do this for the minimum threshold for token timeout values.
> Define constants for checking cluster token values

- Makefile
7d3504290fa0dd5f139d582df33597fb6cc5f721 dropped the whole ocaml/graph/
Travis was not catching this problem because it uses opam rules (jbuilder) to install things, and not the Makefile.
> drop debug/graph: not built anymore

- ocaml/xapi/xapi_ha.ml
- ocaml/xapi/xapi_ha_vm_failover.ml
This is PR #3597 rebased and with minor fixups. The following is from @edwintorok directly copied from the previous PR for reference:
I have dev-tested this using VMs created by this script, and then turning the power off on an HA slave, and watching VMs get restarted in the correct order (first all with order=0 got started in parallel, then order=1, then order=2).
```
#!/bin/bash
set -e
MEMORY='16MiB'
N=50
ORDER=2
if [ ! -f /boot/guest/test-vm.xen.gz ]; then
wget https://github.com/xapi-project/xen-test-vm/releases/download/0.0.5/test-vm.xen.gz
sha256sum test-vm.xen.gz
mkdir -p /boot/guest
mv test-vm.xen.gz /boot/guest
fi
. /etc/xensource-inventory
host_uuid="$INSTALLATION_UUID"
SR=$(xe pool-list params=default-SR --minimal)
for order in $(seq 0 "$ORDER"); do
for i in $(seq 1 "$N"); do …
```
> CP-28117: restart VMs in parallel when recovering from a host failure in HA

- ocaml/tests/test_cluster.ml
- ocaml/tests/test_cluster_host.ml
- ocaml/xapi/xapi_cluster.ml
- ocaml/xapi/xapi_clustering.ml
Previously `Cluster.get_network` returned the network of the cluster_host's PIF on master, failing if no cluster_host could be found on master. Now it will check for a common network among the cluster_hosts before failing.
> CP-28561: Cluster.get_network returns common clustering network

- ocaml/xapi/attach_helpers.ml
- ocaml/xapi/storage_access.ml
- ocaml/xapi/storage_access.mli
- ocaml/xapi/storage_impl.ml
- ocaml/xapi/storage_migrate.ml
- ocaml/xapi/storage_mux.ml
- ocaml/xapi/xapi_vbd.ml
- ocaml/xapi/xapi_vm_migrate.ml
- scripts/static-vdis
We cannot change the original VDI.attach call, because during SXM, older
xapis call Remote.VDI.attach, therefore changing it's return type would
break backward compatibility and SXM. Therefore I kept the old
VDI.attach for backward compatibility, it just calls attach2 at the
Storage_impl layer and transforms its return type. Although that is not
strictly necessary, because in older xapis we ignore the return type of the
Remote.VDI.attach call.
Now only older xapis will be calling the deprecated VDI.attach during
SXM, newer versions starting from this one will use the new VDI.attach2
call.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> [smapiv3 merge] Implement & move to VDI.attach2 SMAPIv2 call, deprecate VDI.attach

- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_mgmt_iface.ml
CA-292621: ensure PIF has an IP before calling clustering methods
The IP address would be updated asynchronously by the network monitor thread,
so we can detect there is an IP on the link but fail later when trying to read
the IP from the DB.
We cannot simply wait on the condition variable until the DB is updated:
the condition is not signalled. We could use the event mechanism to wait
until the IP field gets updated, but that adds more connections to the
master which hurts large pool scalability.
Also when we wake up we couldn't been woken up due to a change on
another PIF, not the one we were watching.
To avoid race conditions always update the IP addresses of all PIFs on a
networking change, and check for the presence of an IP address in the DB
in the clustering network watcher thread. …
> CA-292621: ensure PIF has an IP before calling clustering methods

- ocaml/xapi/xapi_host.ml
Just unplug the PBDs, and allow the clustering daemon to shut itself
down using the `xapi-clusterd-shutdown.service` unit.
This is to avoid a circular dependency between `xapi-domains`, `dlm`,
and `remote-fs` that prevents `dlm` from getting stopped from inside
`xapi-domains` on shutdown.
This needs to be merged together with matching PR on the clustering daemon.
> CA-289735: do not disable clustering daemon on shutdown from xapi-domains

- ocaml/xapi-consts/api_messages.ml
This message is created by clustering daemon fencing hooks,
and needed by XenCenter to localise the message.
> CP-28753: add CLUSTER_HOST_FENCING message

- ocaml/xapi/xapi.ml
- ocaml/xapi/xapi_ha.ml
HA is disarmed on boot if we determine that it got disabled on the pool
while we were off.
However the static VDIs stayed attached, which prevented the PBD from
getting unplugged, e.g. on shutdown. Normally the shutdown code would unplug
these but since HA was disabled that code does not run.
Clean up any static VDIs at the point where we disarm HA on boot by
releasing all HA resources, not just the monitor.
The monitor is stopped when releasing the HA resources, so replace the
call to stop a monitor with releasing the resources.
Dev-tested on a virtual pool and tap-ctl list wasn't showing any active disks after this patch and I was able to unplug the PBDs.
> CA-292063: detach static VDIs when HA is disarmed on boot

- ocaml/xapi-consts/api_messages.ml
We only use CLUSTER_HOST_ENABLE_FAILED, after some refactoring create is
calling the same resync_host API that calls enable, so there is only
message that can be raised.
Also add a comment that the cluster host fencing script is raised by
external script, so that it doesn't get removed next time someone does a
dead code cleanup.
> CP-28753: drop unused CLUSTER_HOST_CREATION_FAILED message

- ocaml/idl/datamodel_cluster.ml
This appears to have been due to copying the other API functions definitions as a template when defining this one. There is no reason to restrict this to pool admin, anyone should be able to see the configuration.
Using _R_READ_ONLY is consistent with other `get_` APIs, e.g. `get_data_sources`.
> CA-293786: Cluster.get_network should not be restricted to pool admin

- scripts/init.d-xapissl
Stunnel restrict it could only use 125/256 of the fds that limited by system. We
set the fd limit to 1024 by default, so stunnel could only use 500 fds for
connection. It is not enough for the master host in pool of 64 hosts when the
pool experiencing high loads.
This fix target to reconfigure the fd limites for xapi and stunnel from 1024 to
4096 to resolve the issue.
> CA-291017: Unable to connect server in pool of 64 physical hosts

- ocaml/idl/datamodel_cluster.ml
- ocaml/idl/datamodel_cluster_host.ml
Other dangerous operations like enabling HA and Host destroy can be
performed by pool operator, so this one should be too.
Discussed with @robertbreker , the REQ was wrong here.
We should probably wait until the internal PR on the design is merged before merging this though.
> CP-28844: Allow pool operator to perform clustering operations

- ocaml/tests/alcotest_comparators.ml
- ocaml/tests/test_vdi_allowed_operations.ml
- ocaml/xapi/cancel_tasks.ml
- ocaml/xapi/xapi_vdi.ml
- ocaml/xapi/xapi_vdi.mli
Fix a confusion between 'None' and 'Some []' leading to the field VDI.allowed_operations being computed without ever referencing any VBDs.
> CA-289997: Fix for VDI.allowed_operations

- scripts/xe-reset-networking
> CA-294281: Network reset: warn if networkd.db could not be deleted

- ocaml/pci/lib/pci.ml
The language binding to the C function is:
```
foreign "pci_lookup_name"
(Pci_access.t @-> ptr char @-> int @-> int @-> int @-> returning string_opt)
```
The return value `string_opt` is constructed by the memory content of the second
parameter `ptr char`, however the corresponding OCaml value of `ptr char` is
GC-able (because we no longer reference it) before coping it to the return
value. So the return value may be incorrect.
Indeed this is bug of CTypes that it does not keep the OCaml variable alive
through the C binding invocation.
We make a local function call to foll the compiler to make the corresponding
OCaml variable alive through the C binding invocation.
> CA-293399: Corrupted PCI information in xapi database

- ocaml/quicktest/qt.ml
- ocaml/quicktest/qt.mli
- ocaml/quicktest/qt_filter.ml
- ocaml/quicktest/qt_filter.mli
- ocaml/quicktest/quicktest.ml
- ocaml/quicktest/quicktest_vm_import_export.ml
- ocaml/quicktest/quicktest_vm_lifecycle.ml
I haven't reintroduced the other two VM quicktests that I've deleted, test_vhd_locking_hook, and vm_powercycle_test, because I think the former does not fail in case of product fault, and the latter is complex.
> CP-28116: reintroduce VM quicktests

- xapi.opam
Xapi vendors ocaml-pci but fails to declare dependencies on ctypes which are used by ocaml-pci. This commit adds them to xapi.opam.
> Add dependency on ctypes to xapi.opam

- scripts/init.d-xapi
Also make sure there's only one arena from which to allocate. No point
in having per-thread arenas due to the global lock. Jemalloc also should
reduce fragmentation.
> CA-289625: Use jemalloc

- ocaml/database/jbuild
The whole ppx_rewriter should not be linked in the executable
> database/jbuild: link only ppx_sexp_conv.runtime-lib

- ocaml/xapi/stream_vdi.ml
Only log skipped blocks, not every block.
> Reduce amount of log messages when importing

- ocaml/idl/datamodel_vm.ml
- ocaml/tests/test_vm_check_operation_error.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/record_util.ml
- ocaml/xapi/xapi_vm.ml
- ocaml/xapi/xapi_vm.mli
- ocaml/xapi/xapi_vm_lifecycle.ml
The coresponding varstored changes got merged, so this is ready for review/merge now.
> Prevent changes to NVRAM field while a VM is running

- ocaml/xapi/cli_operations.ml
The code shows the functionality of `parse_device_config` is the same as `read_map_params` + key_name , and also the latter one supports `device-config-key` syntax.
So there is no need to keep the duplicate code.
> CP-29389: Delete duplicate function 'parse_device_config'

- ocaml/xapi/xapi.ml
Reverts xapi-project/xen-api#3702... Looks like this wasn't needed after all!
> Revert "Workaround for NVIDIA-130"

- ocaml/idl/ocaml_backend/server_helpers.ml
- ocaml/test/suite.ml
- ocaml/xapi/test_guest_agent.ml
- ocaml/xapi/xapi_guest_agent.ml
- ocaml/xapi/xapi_ha.ml
- ocaml/xapi/xapi_ha_vm_failover.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_pool.ml
- ocaml/xapi/xapi_xenops.ml
- scripts/xapi-logrotate.sh
This PR contains a series of backports from the master branch. All commits were cherry-picked and did not require manual changes. Below are the key commits:
* f446487c4 2018-04-12 CA-287865: Forwarded task calling Message_forwarding.xxx result.. Rob Hoes
* 7c31dd1de 2018-04-13 CA-287863: xe vm-shutdown complete the task too early             Yang Qian
* 3f9e67c5f 2018-04-13 CA-287863: Reorgnize the code                                     Yang Qian   
* 7c35d0685 2018-04-04 CA-286364: When creating guest_metrics, ensure all fields refle.. ..cello Seri
* 10b5068f0 2017-05-23 CA-223802 [xso-672] When existing network is deactivated and ne.. Rob Hoes
* 06e538067 2018-06-12 CP-28117: restart HA VMs in parallel when recovering from host .. Jon Ludlam  
* 5f620523e 2018-06-12 CP-28117: …
> Backports from Master

- ocaml/xapi/xapi_xenops.ml
Set the task to un-cancellable after xenopsd updated it to un-cancellable
> CA-290696: Update task to un-cancellable after xenopsd notify xapi

- ocaml/xapi/xapi_guest_agent.ml
I'm suggesting this change to fix the above issue whereby querying a VM's PV-drivers-version returns on occasion (for example, when it's a new VM without PV drivers) the following:
```
[root@xxxx ~]# xe vm-param-get uuid=2ff4edfd-3477-6507-63fd-e0055a578912 param-name=PV-drivers-version
micro: -1
```
This looks weird because major/minor are not there. The original code adds a micro version to pv_drivers_version if it's missing, but I think this should only happen if pv_drivers_version is not empty.
> XSO-886: Do not add micro version to the pv_drivers_version if the latter is empty.

- ocaml/xapi/attach_helpers.ml
- ocaml/xapi/storage_impl.ml
- ocaml/xapi/storage_migrate.ml
- ocaml/xapi/xapi_vbd.ml
This helper has been moved to the storage interface in xcp-idl to reduce
duplication.
> Move implementations_of_backend to xcp-idl

- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_vm_clone.ml
- ocaml/xapi/xapi_xenops.ml
- scripts/Makefile
On clone certain UEFI variables may need to be cleared.
Call `varstore-rm -c <uuid>` to perform this.
The actual variables to clear are defined in the `/etc/xapi.d/efi-clone` directory,
however the format of NVRAM is managed by `varstored`, hence XAPI can't
clear them itself and needs to invoke the helper executable.
There is a related specfile change to make this directory owned by XAPI, however this builds even with the old specfile.
> CP-29169: call varstore-rm on UEFI VM clone

- ocaml/xapi/records.ml
This hides it from `xe vm-param-list` too, not just `xe vm-list`.
One can still query it by doing `xe vm-param-get uuid=... params=NVRAM`.
> CA-299371: mark NVRAM as hidden by default

- ocaml/xapi-consts/api_messages.ml
This message is emitted by varstored on behalf of the guest when a
security violation occurs and Secure Boot is turned on.
> CP-28675: Add a VM_SECURE_BOOT_FAILED message type

- .travis-opam-coverage.sh
- .travis-xs-opam.sh
- ocaml/database/database_test.ml
- ocaml/database/db_cache_impl.ml
- ocaml/database/db_exn.ml
If a row already exists, and all of the fields passed in are the same,
we should do nothing and return successfully.
If a row already exists, and any of the fields are different to what was
passed in, we should fail.
- For this I've created a new exception - Integrity_violation.
I've also updated the database tests to cover these cases
Signed-off-by: Richard Davies <richard.davies@citrix.com>
> CA-297297 Make create_row idempotent

- .travis-opam-coverage.sh
- .travis-xs-opam.sh
- ocaml/quicktest/qt_filter.ml
- ocaml/quicktest/qt_filter.mli
- ocaml/quicktest/quicktest_vdi_ops_data_integrity.ml
- ocaml/xapi/stream_vdi.ml
- ocaml/xapi/xapi_globs.ml
Try to use sparseness information in case the vdi to be exported in tar format has an associated NBD.
This will speed-up dramatically XVA VM export (tar) and vdi-export (tar) in case the VDI is scarcely written.
> CP-29605: Write function to query sparseness of VDIs on GFS2 SRs and do sparse data export

- scripts/init.d-xapissl
To meet the requirement, add `CIPHER_SERVER_PREFERENCE` to let the server use the preference of cipher. 
Test passed. 
> CA-300210: Add 'CIPHER_SERVER_PREFERENCE' option in xapi ssl config file.

- ocaml/idl/datamodel.ml
- ocaml/idl/datamodel_common.ml
- ocaml/tests/test_pool_update.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_pool_update.ml
- scripts/extensions/pool_update.apply
- scripts/extensions/pool_update.precheck
> CA-299944: Cross pool update apply failed because HTTP connection not enabled in CC mode

- ocaml/test/test_pool_update.ml
- ocaml/xapi/fileserver.ml
- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_pool_update.ml
This PR is for removing the patch `ca293417-honolulu.patch` for Havana to avoid possible conflict.
Build passed in Branch 'private/minl1/backport-patch'. 
The PR #3744 needs to rebase this one after merged.
> Backport-ca293417-honolulu.patch to Havana

- ocaml/xapi/xapi_xenops.ml
Under some circumstances, for example if a domain is being destroyed, a VM.stat
call to xenopsd may return an undefined domain type if the domain is not
halted. We assume that this is always a transient state, and ignore it.
> CA-297137: Don't update current_domain_type if xenopsd returns undefined

- scripts/xe-backup-metadata
Increase VDI size from 250 to 500MiB due to it running out space during metadata backups.
> Increase VDI size for metadata backups

- ocaml/idl/datamodel.ml
- ocaml/idl/datamodel_types.ml
- ocaml/test/test_pool_update.ml
- ocaml/xapi/create_misc.ml
- ocaml/xapi/helpers.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi.ml
- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_pool_update.ml
- scripts/extensions/pool_update.apply
- scripts/extensions/pool_update.precheck
- scripts/init.d-xapissl
This PR contains several fixes and refine:
1. CA-299944: Proxy requests to updates
2. CP-29687: Remove TLS_RSA_WITH_AES_128_CBC_SHA(AES128-SHA) for CC 
3. CA-300210: Add 'CIPHER_SERVER_PREFERENCE' option in xapi ssl config
4. CA-300650: Set ssl legacy = false for Havana in CC mode.
5. CA-300715: Use dup fd to avoid close twice.
1.2.3 get reviewed already, the 4,5 commit is new and targets only in Havana branch.
As there is minor conflict in Havana build, I need to refine a little tomorrow but needs to get reviewed at first on UK daytime today.
Please help to review, thanks @robhoes
> Backport a few fixes/refine for CC feature to Havana

- ocaml/idl/datamodel_vm.ml
Set the permissions for VN.assert_operation_valid to READ_ONLY as this
call doesn't mutate anything and does not reveal critical information.
> CA-300115 lower VM.assert_operation_valid permissions

- ocaml/tests/test_platformdata.ml
- ocaml/xapi/import.ml
- ocaml/xapi/vm_platform.ml
- ocaml/xapi/xapi_db_upgrade.ml
- ocaml/xapi/xapi_vm.ml
- ocaml/xapi/xapi_vm_clone.ml
- ocaml/xapi/xapi_vm_helpers.ml
We want to be able to choose BIOS/UEFI boot mode from XenCenter, so the device-model should not be part of the template.
Did a basic smoke test on this, and will run more tests.
> CP-29857: defer setting device-model until VM.start

- ocaml/xapi/xapi_host.ml
During a host network reset, remove any network_sriov object that refers
to a local PIF.
> CA-294900 remove network_sriov on network reset

- ocaml/xapi/xapi_xenops.ml
The /guest_agent_features tree in xenstore disappears during reboot. To
make sure it is re-created, we call apply_guest_agent_config() during
xapi startup.
> CA-302194 XSI-87 apply guest agent config on start

- ocaml/xapi/xapi_host_helpers.ml
- ocaml/xapi/xapi_host_helpers.mli
- ocaml/xapi/xapi_vm.ml
- ocaml/xapi/xapi_vm_helpers.ml
> CA-290024: Reject booting pv-iommu VMs on a host where the premap is yet to complete

- ocaml/xapi/xapi_xenops.ml
This fixes the previous commit - the code for building the
tree in xen should be run last to be equivalent with the code
on the master branch.
> CA-302194 XSI-87 move code to end of on_xapi_restart

- ocaml/tests/test_dbsync_master.ml
- ocaml/xapi/dbsync_master.ml
- ocaml/xapi/xapi_db_upgrade.ml
- ocaml/xapi/xapi_pool.ml
This is work in progress. On joining a pool, the SR for the Guest Tools ISO is a special case. This series of commits tries to avoid that multiple such SRs are present in the final pool.
> CA-300103 Avoid duplicated tools SRs on pool join

- ocaml/test/test_dbsync_master.ml
- ocaml/xapi/dbsync_master.ml
- ocaml/xapi/xapi_db_upgrade.ml
- ocaml/xapi/xapi_pool.ml
This is the backport of CA-300103 - making sure that only one Tools SR exists,
> Backport of CA-300103 - designate a single Tools SR, delete others

- ocaml/xapi/OMakefile
- ocaml/xapi/create_misc.ml
The number of vCPUs in dom0 was set to the number of CPUs in the host -
which is wrong. Read the correct number from /proc/cpuinfo from inside
dom0.
Backport of 4a2cc12d1
> BP CA-299554 XSI-132 use correct vCPU count for dom0

- ocaml/idl/datamodel_errors.ml
- ocaml/xapi-consts/api_errors.ml
- ocaml/xapi/xapi_vm_migrate.ml
This will not block the "Move VM" operation on a halted VM in XenCenter,
because XenCenter moves the VM manually by copying the VDIs of the VM
and creating & plugging new VBDs.
But this is fine, because we wanted to block SXM of encrypted VDIs for
XenAPI users. And both the VM.migrate_send call and "xe vm-migrate" will
be blocked for encrypted VDIs, even if the VM is halted.
> CP-29757: block SXM of encrypted VDIs

- ocaml/xapi-consts/api_messages.ml
This reverts commit a2886374d4fc786de71a7574978051d2bc1aca0f.
It turned out that we didn't need this.
> Revert "CP-28951: Add message of xen low memory alarm"

- scripts/host-backup-restore/host-restore
Don't allow restoring a backup from XS < 7.0 which uses the old dom0
partition layout on a 7.x+ host which uses a newer partition layout
since there are some cases where it results in an unbootable host.
> CA-302538: Disallow restore across partition layout changes

- ocaml/xapi/xapi_vm_lifecycle.ml
- ocaml/xapi/xapi_vm_snapshot.ml
- ocaml/xapi/xapi_xenops.ml
To support checkpoint for Nvidia vGPU enabled VMs, this PR contains:
- Remove restriction for VMs with vGPUs
- Do not clear `resident_on` for VM and VGPU in checkpoint.
Signed-off-by: Talons Lee <xin.li@citrix.com>
> REQ-638: Support checkpoint for  Nvidia vGPU enabled VMs

- scripts/init.d-attach-static-vdis
When slave host cannot connect to NFS server(HA metadata VDI and HA state file VDI reside on), from the XenRT case it drops the port to NFS, the slave will in emergency mode, but when NFS server comes back by allowing the port in iptables, what's  expected is the slave host will quit emergency mode. But we met a scenario that when attaching first VDI(the NFS didn't come back), the attach-static-vdis will fail, but succeed on attaching the second one(as now NFS server can be accessed). Xapi will marked it as failed and retry to attach the VDIs after 10s, so in the second round, the first VDI will be attached successfully(Because it failed in the first round) and then the second VDI will fail to attach(as it succeeds in the first round).
Even though we discussed in the ticket CA-300644 that …
> CA-300644: return immediately when attach-static-vdis failed

- ocaml/xapi/xapi_vm_lifecycle.ml
XS support checkpoint when VM in suspend state:
https://docs.citrix.com/en-us/xenserver/current-release/dr/snapshots.html
When VM with Nvidia vGPU becoming a suspended state, it will update
allowed_operations to exclude checkpoint which is not correct.
This commit is refining to check the power_state and is_nvidia to
decide checkpoint permission.
So now there are two conditions to allow checkpoint for vGPUs VMs:
1. Checking all vgpus on VM are suspendable by calling `is_suspendable`
2. power state is `suspended` and the vGPU type is `NVIDIA`
> CA-304576: Allow checkpoint on suspended VM with Nvidia vGPU

- ocaml/test/OMakefile
The backport of CA-299554 is incomplete as the test target is broken.
This fixes it but adding a missing dependency to the Re package.
> CA-299554 fix backport

- ocaml/xapi/xapi_xenops.ml
Previously we've run it as root, sandbox it instead.
There is no domain id associated with a VM clone, so we just use
the same user `qemu_base + 0` for sandboxing. This is less than ideal, but better than running as root.
> CP-30032: spawn varstore-rm in a chroot

- ocaml/tests/test_vm_check_operation_error.ml
This should not be settable while a VM is running, one has to use the special
set_NVRAM_EFI_variables call that is restricted by RBAC.
> CP-29002: add unit test for VM.NVRAM field

- ocaml/tests/test_vgpu_common.ml
- ocaml/tests/test_vgpu_type.ml
- ocaml/tests/test_xenopsd_metadata.ml
- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_vgpu_type.ml
- ocaml/xapi/xapi_xenops.ml
This information is no longer required for starting GVT-g VMs, so xapi no
longer needs to read it from the whitelist file and pass it to xenopsd. Note
that, for backwards compatibility, we need to keep the `monitor_config_file`
key in the `Xenops_interface`, but xapi sets it to `None` from now on.
> CP-29962: Ignore monitor_config_file for GVT-g VGPU types

- ocaml/tests/test_common.ml
- ocaml/xapi/create_misc.ml
- ocaml/xapi/create_misc.mli
- ocaml/xapi/dbsync_slave.ml
- ocaml/xapi/monitor_dbcalls.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_pool_update.ml
This commit tries reduces direct calls to Xenctrl by replacing it with xenopsd communication, it also tries to reduce communication between xapi and xenopsd to gather host information, as well as making it more apparent when it's happening.
I'm unsure about not being able to retrieve the actual memory values when xenopsd is down, feedback on how to tackle this is appreciated.
I'm also unsure on whether it would be beneficial to replace the `make` in the name of methods in `create_misc.ml` to better reflect that they write to the database.
Xenctrl is still used for testing in `ocaml/quicktest/quicktest_vm_lifecycle.ml` and is used to periodically update information about the host in `ocaml/xapi/monitor_dbcalls.ml` and `ocaml/xapi/monitor_types.ml`. This last usage needs a more thought'out …
> CP-30527: Reduce direct usage of Xenctrl

- .travis-xs-opam.sh
This simplifies the Travis setup which uses xs-opam. In addition, it switches to Debian in anticipation for better support of xxHash.
> Simplify .travis-xs-opam.sh

- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_pool.ml
Take the uefi certificates from the 'old' host, and use the API to copy
them to the 'new' host. This has the added benefit of setting the pool
certificates, if they don't already exist
Message forwarding hasn't started yet because the host is still offline,
so only do the set locally
Signed-off-by: Richard Davies <richard.davies@citrix.com>
> CP-30559 Use the API to add the uefi certificates

- ocaml/xapi/console.ml
Add support for using Unix domain sockets for wsproxy requests.
> CA-309048 handle domain sockets for wsproxy

- ocaml/xapi/create_storage.ml
When HA is enabled the host only gets enabled if all its PBDs got
plugged.
However clustered PBDs only get plugged after quorum is established,
which might be after the startup sequence has finished.
There is a watcher thread for that, and when the clustered PBDs do get
plugged in we should attempt to enable the host again.
Rerunning the xenrt test that was consistently failing before on this GFS2 HA test is now passing.
> CA-310971: consider enabling the host again after plugging in clustered PBDs in HA mode

- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_vm.ml
With this change I was able to run 'vm-start' without seeing an exception.
> CP-30440: fix tarfile extraction

- ocaml/idl/datamodel_common.ml
- ocaml/idl/datamodel_types.ml
- ocaml/xapi/xapi_globs.ml
This commit updates version numbers for the Naples release and adds a
record for the Oslo release.
* Database Version: 5.400
* API Version: 2.12
* Branding
> CP-29134 Update versions for Naples release

- scripts/xe-backup-metadata
VM metadata backup will fail with no errors because of the VDI is running out of space.
- Add backup VDI usage check before perform the backup, return error
if usage greater than the usage alert. (Default 90%)
- Add the '-f' option to ignore the checking.
> CA-311705: Add VDI usage checking for metadata backup script.

- ocaml/xapi/create_misc.ml
This complements XSI-132 CA-312644 and commit
4a2cc12d1a72854174b25773f510afcfa8c46aad
The number of vCPUs of dom0 need to be updated on xapi restart in the
dom0 metrics which usually are only written on first boot.
> XSI-132 CA-312644 CA-299554 update dom0 vcpu count

- ocaml/xapi-types/features.ml
- ocaml/xapi-types/features.mli
- ocaml/xapi/cli_operations.ml
- ocaml/xapi/dune
- ocaml/xapi/export.ml
- ocaml/xapi/import.ml
- ocaml/xapi/importexport.ml
- xapi.opam
This pull request implements VM export and import using the Zstd algorithm. Compression algorithm is specified on export, and automatically detected on import via the gzip/zstd magic strings.
Comments/open questions:
* I've added a feature flag to `features.ml` mainly so clients can tell whether a server supports this feature. xapi does not actually check this feature flag before doing a zstd import/export, but I can add this if necessary.
* There is no check that the zstd binary is installed on the host. This could be done by calling `Zstd.available ()` and throwing an exception if it is not installed, but since this is not checked for `gzip` I haven't implemented this. For XCP-ng we plan to add `zstd` as a dependency of the xapi RPM.
> Zstd VM export

- ocaml/xapi/monitor_dbcalls.ml
- ocaml/xapi/monitor_dbcalls_cache.ml
- ocaml/xapi/monitor_mem_host.ml
- ocaml/xapi/monitor_mem_vms.ml
- ocaml/xapi/monitor_pvs_proxy.ml
- ocaml/xapi/monitor_types.ml
- ocaml/xapi/xapi_globs.ml
Memory statistics are now collected from rrd files in 2 new modules. These modules follow the same structure as `ocaml/xapi/monitor_pvs_proxy.ml` I'd like to reduce the amount of repeated/shared code in them, I'm open to suggestions.
Left to do: change how domain information is gathered from a string in `ocaml/xapi/monitor_types.ml`
Depends on https://github.com/xapi-project/xcp-rrdd/pull/89
> CP-30614: Use RRD to update memory stats

- scripts/xe-backup-metadata
VM metadata backup will fail with no errors because of the VDI
is running out of space.
- Add backup VDI usage check before perform the backup, return error
if usage greater than the usage alert.(Default 90%)
- Add '-f' option to ingore the checking.
Backport of 4ac33cd52a1cf67c445c52db25c340a12e13bc0a
> CA-311705: Add VDI usage checking for metadata backup scripts.

- ocaml/idl/datamodel_vm.ml
- ocaml/tests/test_vm.ml
- ocaml/xapi/bios_strings.ml
- ocaml/xapi/xapi_globs.ml
The SMBIOS type 2 info is required for some guest app to run properly.
This commit let the toolstack accept those strings and write to xenstore.
Signed-off-by: Talons Lee <xin.li@citrix.com>
> CA-314290: Allow to specify SMBIOS type2 info from the toolstack

- ocaml/xapi/xapi_gpumon.ml
- ocaml/xapi/xapi_vm_lifecycle.ml
A vGPU is supposed to hold vGPU compatibility metadata only while it is
suspended. Beyond that, it can deadlock the start of other machines as
it causes gpumon being contacted in vgpu_pgpu_are_compatible() while
gpumon might be is stopped as part of VM.start of another VM. This
commit adds code to detect, log, and remove this metadata when a VM is
halted to avoid the problem.  We still need to find the root cause why
the situation can arise in the first place.
> CA-312226 XSI-251 clear unexpected vGPU metadata on shutdown

- ocaml/xapi-types/features.ml
- ocaml/xapi-types/features.mli
- ocaml/xapi/cli_operations.ml
- ocaml/xapi/dune
- ocaml/xapi/export.ml
- ocaml/xapi/import.ml
- ocaml/xapi/importexport.ml
- xapi.opam
This is just cherry-picked from the original pull request, #3797, with one extra commit that changes the logic for trying gzip - now xapi will attempt to decompress with gzip any file that is not an uncompressed tar file or compressed with zstd.
Hopefully this will reduce the risk of regression. I have tested importing uncompressed archives, as well as archives compressed with gzip, zip and zstd.
> Zstd VM export take 2

- ocaml/idl/datamodel.ml
- ocaml/idl/datamodel_common.ml
- ocaml/tests/test_common.ml
- ocaml/tests/test_vgpu_common.ml
- ocaml/tests/test_vgpu_type.ml
- ocaml/xapi/cli_frontend.ml
- ocaml/xapi/import.ml
- ocaml/xapi/records.ml
- ocaml/xapi/xapi_vgpu_type.ml
- Add compatible_types_in_vm and compatible_types_on_pgpu into
vgpu_type, show the first one in parameter list.
- Change to use new way to read from NVIDIA config file and
initilize compatible* list.
- Add device as an option paramater in vgpu.create and show
in parameter list.
- Update test cases accordingly.
> REQ-720: CP-31058: Datamodel changes for multiple Nvidia VGPU support
