xapi-project/xen-api

- .travis-xs-opam.sh
- ocaml/xapi/xapi_vm.ml
```
VM1                                 VM2
Sys.file_exists ... -> false
create xapi_uefi_certificates.tar  Sys.file_exists ... -> false
create xapi_uefi_certificates.tar
extract xapi_uefi_certificates.tar
remove xapi_uefi_certificates.tar
extract xapi_uefi_certificates.tar:ENOENT
```
The race condition could be solved either with a lock, or with using
unique names for temporary files.
This patch uses unique names for the temporary file to avoid the race
condition.
> CA-314381: fix race condition in secure boot startup

- scripts/Makefile
- scripts/xapi-autostart-vms
- scripts/xapi-domains.service
- scripts/xapi-init-complete.target
- scripts/xapi-wait-init-complete.service
Create a xapi-init-complete.target and a xapi-wait-init-complete.service
which is wanted by it. The service invokes the existing
xapi-wait-init-complete so that it is only done in one place now.
The SPEC file will need altering to enable the xapi-wait-init-complete
service on installation.
xapi-domains.service (and any other service which needs to start after
Xapi has completed initialisation) can now declare
Wants=xapi-init-complete.target
After=xapi-init-complete.target
to ensure that Xapi will be done initialising before they are started.
> CA-315107 Create xapi-init-complete systemd target

- scripts/init.d-xapi
- scripts/xapi.service
We set environment variables to make xapi use the jemalloc library. Move
the code for this into the systemd service file to align with other
toolstack daemons.
> Move jemalloc into xapi.service (was: CA-289625)

- ocaml/tests/suite_alcotest.ml
It uses Thread.delay and assumes that events get processed within 0.4s.
That may not be enough if the CI is under high load.
Should be replaced with looking for events and a (larger) timeout
instead. Disable for now to restore build stability.
> CA-316165: workaround - disable nondeterministic unit test

- ocaml/tests/suite_alcotest.ml
- ocaml/tests/test_clustering.ml
- ocaml/tests/test_daemon_manager.ml
- ocaml/tests/test_event.ml
- ocaml/tests/test_vdi_cbt.ml
This one is not reliable either:
```
--------------------------------------------------------------------------------^M                                                                                    
ASSERT data_destroy did not return in 1.400000 seconds^M                                                                                                              
--------------------------------------------------------------------------------^M                                                                                    
Test error: Fail data_destroy should raise VDI_IN_USE after its timeout: expecting Server_error(VDI_IN_USE, [ OpaqueRef:e326b041-761c-4461-9594-3dfc16473ac3; data_des
troy ]), got Alcotest.Check_error("Error data_destroy did not return in 1.400000 seconds.").^M …
```
> CA-316165: workaround - disable CBT unit tests

- ocaml/idl/datamodel_common.ml
- ocaml/idl/datamodel_types.ml
- ocaml/idl/json_backend/gen_json.ml
Also, do not autogenerate placeholders for unreleased API versions in the docs.
> CA-315688: Bumped API version to 2.14 for the plymouth release

- ocaml/xapi/monitor_dbcalls.ml
- ocaml/xapi/monitor_mem_host.ml
- ocaml/xapi/monitor_mem_vms.ml
- ocaml/xapi/xapi_globs.ml
Depends on https://github.com/xapi-project/xcp-rrdd/pull/95
Remove code dependent of xenctrl for gathering memory statistics.
Both VM and Host statistics for memory got moved to their respective
files. They follow the same structure as monitor_pvs_proxy.
Cherry-pick of d68fc970a0ebfb8b66ae874dd91b769785ca4005
> CP-30614: Use rrd files to gather memory statistics

- scripts/probe-device-for-file
probe-device-for-file is called from xe-restore-metadata which is called
from xsconsole. Output to stderr, stdin is shown to the user and it
contains irrelevant and confusing output from probe-device-for-file
which is coming from the fsimage library. Since we can't change the
fsimage library, stderr for the call to fsimage (only) is redirected to
/dev/null. This does not make us miss errors as these are raised as
exceptions.
Backport of 823eddd8a
> CA-316241 redirect stderr output from probe-device-for-file

- ocaml/xapi/bios_strings.ml
- ocaml/xapi/xapi_globs.ml
Backport commit 94d2ff7 without the dependent commits, so only keep the
bios string copy function.
Signed-off-by: Talons Lee <xin.li@citrix.com>
> CP-31268: copy SMBIOS type2 info from host to VM

- .travis-xs-opam.sh
This allows xen-api to be built against the uefi branch of xenopsd instead of the master one.
Note: This commit must not be merged into the master branch.
> Use xs-opam's uefi branch for travis

- ocaml/tests/test_common.ml
- ocaml/tests/test_pgpu_helpers.ml
- ocaml/tests/test_vgpu_common.ml
- ocaml/tests/test_vgpu_type.ml
- ocaml/tests/test_vm_helpers.ml
Brief: 
- Fix build error caused by renaming compatible_model_names_in_vm;
- Test new function rank_hosts_by_best_vgpu;
- Cases for multiple vGPUs haven't been added;
> Fix unit test failures introduced by multi-vGPU code.

- ocaml/idl/datamodel.ml
- ocaml/idl/datamodel_errors.ml
- ocaml/tests/test_common.ml
- ocaml/tests/test_vgpu_common.ml
- ocaml/tests/test_xenopsd_metadata.ml
- ocaml/xapi/records.ml
- ocaml/xapi/xapi_vgpu.ml
- ocaml/xapi/xapi_xenops.ml
As titled, add support for extra_args for vgpu.
Customer can set extra args for the vgpu by command 
```xe vgpu-param-set uuid=xxxx extra_args="key1=v1,key2=v2"```
This is very similer to the previous verion of 
``` xe vm-param-set uuid=xxx platform:vgpu_extra_args="key1=v1,key2=v2"```
> Support extra_args for vGPU configration

- ocaml/xapi/xapi_sr_operations.ml
- scripts/init.d-xapi
- scripts/xapi.service
* c37f26fb0 HFX-2314 Move jemalloc into xapi.service (was: CA-289625)        
* 614b19e6c HFX-2314 CA-289625: Use jemalloc                                 
* 1f3682f27 HFX-2327 XOP-948: Restrict SR allowed_operations during RPU 
The backport of XOP-948 was done manually and tests were not backported because they rely on Alcotest which is not used in this branch.
> Backports: XOP-948, using jemalloc in xapi

- ocaml/xapi/cli_operations.ml
- ocaml/xapi/rbac_audit.ml
- ocaml/xapi/workload_balancing.ml
- ocaml/xapi/xapi_gpumon.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_vm.ml
- xapi.opam
Now we use Base64 3.1.0 instead of using the extended custom library.
The encoding functions should be safe to replace.
For the decoding there are 2 possible issues:
* The new calls could fail more frequently because not they are not sanitized anymore. (especially for gpumon)
* The exception from the call in ocaml/xapi/xapi_gpumon.ml, Line 103 are not caught: how to report the failing call?
> CP-30756: Replace Base64 library

- ocaml/idl/datamodel.ml
- ocaml/xapi/xapi_db_upgrade.ml
For XS with version before Naples, it has only one vGPU device with 0 as its default id.
For XS from Polymoth, it may have multiple vGPU device, 11 is the default device id.
This commit upgrade the default device ids from 0 to 11 during upgradation.
> CA-320458: Upgrade vGPU default device id from 0 to 11

- scripts/xapi-domains.service
Otherwise VM migrations may be interrupted
> CA-312654: domains must be stopped before xapi is

- ocaml/idl/datamodel_errors.ml
Apart from fixing CA-258385, this PR moves here most of the error messages with which the C# SDK overrides the original API errors. Most of the changes are conversion of 'host' to 'server', which I think is ok given there was already some mixed used of host/server in the messages. The advantage of moving those messages here is that we won't need anymore to override them in the C# SDK, and the corrected messages will be available in the other SDK flavours as well as the API docs, which means uniform terminology throughout components. Let me know if there are any concerns.
> Modifications to error messages; includes CA-258385.

- ocaml/xapi/vgpuops.ml
- ocaml/xapi/xapi_pgpu.ml
This commit check the NVML compatibility of the vGPU and the pGPU.
The vGPU can only be assigned bo a pGPU with NVML compatibility
1. The `Xapi_gpumon.Nvidia.vgpu_pgpu_are_compatible` is moved to Xapi_pgpu.assert_can_run_VGPU in https://github.com/xapi-project/xen-api/pull/3855/files#diff-3fb19a7212efdf3b669fd4374ac02838L315 as I throught every pGPU assert need such checks. But it caused other inconsistency behaviors when doing the RPU. So I revert it back.
2. Add the  `Xapi_gpumon.Nvidia.vgpu_pgpu_are_compatible` when allocate a vGPU to a pGPU to guarantee only the compatible pGPUs are allocated.
> CA-321787: Block migrate/suspend/resume when there is no pGPU compatible with vGPU

- ocaml/idl/datamodel_errors.ml
Replace "VGPU" with "virtual GPU", as VGPU should be avoided in user interface.
> CP-31400: Update API error text.

- scripts/probe-device-for-file
The Python module fsimage has been renamed to xenfsimage as part of Xen 4.12.
This commit changes the client accordingly.
> CA-322450 xe-restore-metadata: ImportError: fsimage

- ocaml/xapi/xapi_gpumon.ml
- ocaml/xapi/xapi_vgpu.ml
- ocaml/xapi/xapi_vm_snapshot.ml
When saving a snapshot, make sure to save VGPU metadata such that it is
available on resume.
> CA-321930 XSI-374 GPU compatibility check not done on snapshot snapshot

- ocaml/idl/datamodel_errors.ml
When trying to repair a GFS2 SR and clustering is disabled I got this error message.
Try to simplify it for the user: they have to enable clustering to fix it, so try to be more obvious in telling the user that the problem is that clustering is not enabled.
> CA-322710: improve clustering error message

- dune-project
Warning: .merlin generated is inaccurate. Cannot mix preprocessed and
non preprocessed specificiations.  Split the stanzas into different
directories or silence this warning by adding
(allow_approximate_merlin) to your dune-project.
> Maintenance: silence Merlin warnings

- ocaml/auth/extauth_plugin_ADpbis.ml
PBIS will return success when it queries user KRBTGT even if the domain is
offline but the user KRBTGT is in the cache. This makes the XAPI fail to
check the availability of domain by this appoach.
This commit adds logic to remove the user KRBTGT from cache before XAPI
checks the availabililty of domain.
> CA-319960: Remove user KRBTGT from cache before checking

- ocaml/tests/test_vgpu_type.ml
- ocaml/tests/test_xenopsd_metadata.ml
- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_pgpu.ml
- ocaml/xapi/xapi_vgpu_type.ml
- ocaml/xapi/xapi_xenops.ml
This PR make xapi work with old NVidia drivers that has no multiple vGPU support as followings
- Check whether the Nvidia host installed suport multiple vGPU
-  Make up old config_file argument for demu in case host driver does not support multiple vGPU
- Make all VGPU_type does not compatible with any one (including themselves) if host driver does not support multiple vGPU
How xapi judge whether a Nvidia driver support multple vGPU:
Add configration variable nvidia_multi_vgpu_enabled_driver_versions
nvidia_multi_vgpu_enabled_driver_versions is a list and configurable
in xapi confie file /etc/xapi.conf, it stating the version of Nvidia
host drivers that have multiple vGPU support. The elements in the list
have following two formats:
1. "major_version.minor_versoin": the specific version …
> CA-322749: Make toolstack work with old Nvidia drivers

- ocaml/tests/test_event.ml
- ocaml/tests/test_network_event_loop.ml
- ocaml/tests/test_vdi_cbt.ml
Following suggestions on the ticket, here we convert some unconditional wait
(Thread.delay) to conditional wait (Delay.wait).
The pattern is, in these tests we expect to observe something to happen, but it
has to be within a reasonable time frame. From testing point of view, we can
not assume a function will always return (especially if it was implemented
wrong) and we certainly don't want to wait indefinitely.
Previously with Thread.delay, we unconditionally wait for a timeout, then check
the observed value. Not pretty, but it doesn't require any kind of
collaboration from the observed party. The problem is, if we set the timeout
tight, it might time out if the system is extremely stressed. But if we set the
timeout too relax, we end up wasting time every single run.
Now With Delay.wait, …
> CA-316165: Convert some Thread.delay to Delay.wait

- scripts/init.d-xapi
On shutdown XAPI asks xcp-rrdd to backup the RRDs, which can be slow if you have a lot of VMs, SRs, etc.
The shutdown script then asked xapi to shutdown again a second later, which asked xcp-rrdd to save a backup again,
and so on, until finally it gave up after a minute, finally allowing xcp-rrdd to catch up.
If 'xe host-shutdown-agent' succeeds then do not try to repeatedly tell xapi to shut down again,
it heard us the first time. If it fails then do try to tell it to shutdown again.
Either way keep looping until we detect that xapi is down.
A toolstack restart now takes only 18s instead of 2-3m:
```
Executing xe-toolstack-restart
done.
real	0m18.581s
user	0m0.127s
sys	0m0.603s
```
> CA-322045: tell XAPI to shut down only once

- ocaml/tests/test_xapi_xenops.ml
- ocaml/xapi/debug_populate.ml
- ocaml/xapi/xapi_sr_operations.ml
OCaml 4.08.1+rc1 found this:
```
File "ocaml/xapi/xapi_sr_operations.ml", line 236, characters 18-705:
236 | ..................Thread.create (fun () ->
237 |               let rec loop () =
238 |                 Thread.delay 30.;
239 |                 let info = C.SR.stat dbg (Storage_interface.Sr.of_string (Db.SR.get_uuid ~__context ~self)) in
240 |                 if not (Db.Task.get_status ~__context ~self:task = `cancelling) &&
...
247 |                 end
248 |               in
249 |               loop ()
250 |             )
Error (warning 5): this function application is partial,
```
And it is indeed correct, this is dead code, we never actually created
the thread, because the `_` was of type `unit -> Thread.t`.
Be explicit about the type of the ignored argument and fix it.
None of …
> sr_health_check: Actually make the thread start instead of dead code

- ocaml/tests/test_network_event_loop.ml
We've already made some improvements here, however some `Thread.delay` still remain and we've noticed a few more failures.
Remove the last remaining pieces of `Thread.delay` to make the unit test more reliable, there was an obvious race condition where a test was both waiting for an function to fail by raising an exception,
and later on excepting the same function to succeed after a retry. Due to a race condition at the time the function was run it may have missed the flag to raise an exception and went straight to the success case. With this change we wait for both events explicitly instead of relying on time.
> CA-316165: make unit tests more deterministic

- ocaml/xapi/xapi_xenops.ml
Previously the actual power state of the VM was reported as the expected one
and vice versa.
> maintenance: report the actual power state on logs

- ocaml/xapi/storage_access.ml
- ocaml/xapi/storage_impl.ml
- ocaml/xapi/storage_migrate.ml
- ocaml/xapi/storage_mux.ml
- ocaml/xapi/xapi_vm_migrate.ml
We now honour the existing API of Datapath.attach by
passing the domid of vm that the vbd is being attached to.
This will enable a qemu process per vm.
Signed-off-by: ben sims <ben.sims@citrix.com>
> CP-31450: Add domid to Datapath.attach

- ocaml/xapi/xapi_vm_lifecycle.ml
Previously any PCI attached to a VM would block some VM operations.
Exempt NVIDIA SRIOV GPUs from this. We run checks if we find any other
PCI device attached to a VM.
> REQ-627 CA-325126 don't let SRIOV PCI GPU block VM ops

- scripts/host-display
There were two distinct issues with the host-display script. Firstly, it always
assumed com1 was the serial port in use, when in some cases it may be e.g. com2.
Secondly if you go through a disable/enable cycle on a normal (VGA) setup, the
result would be the loss of `console=hvc0` from the dom0 command line, because
the `set-dom0` command will *replace* all existing entries, not just append one
to the line.
These changes resolve these issues.
Signed-off-by: Alex Brett <alex.brett@citrix.com>
> CA-325319 Fix host-display script console handling

- .travis-xs-opam.sh
restrict loading the new vars to the script testing xs-opam repo
> travis: load vars from xs-opam repo

- scripts/examples/python/XenAPI/__init__.py
This keeps backwards compatibility with unpackaged XenAPI.py,
Previously users importing had to change imports to `from XenAPI import XenAPI`
> CP-12980: maintain import behaviour on package

- ocaml/xapi/xapi_pci.ml
- ocaml/xapi/xapi_pci_helpers.ml
- ocaml/xapi/xapi_vm_lifecycle.ml
PCI devices are considered to be related if they only differ in their
function. Related PCI devices are passed to a guest together.
This definition is insufficient when dealing with virtual functions,
which must be excluded.
This commit narrows the definition of "related" accordingly: virtual PCI
devices are excluded. In addition, the commit tries to make the
definition more explicit by defining predicates.
> REQ-627 CP-32057 narrow definition of "related" PCIs

- scripts/examples/python/README.md
It's not clear what the examples are when the readme is in PyPI as
there are no examples in the package.
> python: fix typo in readme, add link to examples

- ocaml/xapi/bios_strings.ml
In 4156d7fdcb300a5d72eff0c0fabb8ecd4c98c266 we started to filter out
lines with '#' from dmidecode, however by doing so we also lost newlines
from strings.
Since 94d2ff73711becc9cc92d01606ee38929808eb14 we start getting newlines
in baseboard-strings, and we are reporting the wrong values to the
guest.
So just concatenate with newlines, removing the newlines never seem to
have been the intention of the filtering code here.
> CA-325988: do not lose newlines from dmidecode

- ocaml/idl/datamodel.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/record_util.ml
- ocaml/xapi/xapi_sr_operations.ml
VDI.forget was not marking the SR with an in-progress operation so SR.scan could've run while VDI.forget was in progress.
After a VDI.forget the VDI could disappear, causing SR.scan to report a failure.
By default only the plug operation is marked as able to execute concurrently, add VDI.forget to that list:
as long as all we do is run VDI.forget in parallel its fine, but as soon as we try to combine it with
something like SR.scan the SR.scan should get OTHER_OPERATION_IN_PROGRESS error.
VDI.forget should be safe to parallelise because it is just a DB operation, and it was parallelized before.
> CA-326174: fix race condition between SR.scan and VDI.forget

- ocaml/idl/datamodel.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/record_util.ml
- ocaml/xapi/xapi_sr_operations.ml
This causes a deadlock between xapi, SM and SMGC, since SMGC takes an SM-side SR-lock, and attempts to do aVDI.forget, while a VDI.create is already running on xapi side, attempting to take the SR-lock on the SM side.
SMGC cannot proceeed because VDI.forget gets rejected by xapi due to VDI.create being in progress, and VDI.create cannot proceed because SMGC holds the lock.
Revert the change for now, to properly fix this would be better if SM was taking all the locks (as in SMAPIv3), or at least we should only forbid SR.scan+VDI.forget in parallel, not VDI.forget+VDI.create
> Revert "CA-326174: fix race condition between SR.scan and VDI.forget"

- ocaml/xapi/xapi_vm_migrate.ml
When Xapi calls VM.migrate in xenopsd by RPC the call includes a map
that handles assigning a new PCI address for the PGPU. We need a similar
mechanism for the PCI VF that is part of a vGPU. Otherwise changes in
this field would not reach Xenopsd.
This commits extends the mapping by including the vGPU.PCI value if it
is not null. It does so by using a special key in the map.
> REQ-627 CA-325131 add vGPU.PCI to vgpu map for xenopsd

- ocaml/xapi/xapi_xenops.ml
This fixes an oversight in an earlier commit: xapi creates a vgpu object which it passes to xenopsd. This contains a VF PCI field. We have to make sure to use it only when we are indeed using SRIOV mode. This code checks the implementation of the VGPU to decide this.
> fixup! REQ-627 pass PCI VF for GPU SR-IOV to xenopsd

- ocaml/idl/datamodel_errors.ml
- ocaml/xapi-consts/api_errors.ml
- ocaml/xapi/xapi_gpumon.ml
Add a more specific API error message for when the Nvidia host driver
does not support migration as is the case for Linux.
> CA-325330 add error for VGPU driver incompatibility

- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_vgpu_type.ml
Add a configuration option to assume NVidia Tesal T4 cards are using
SR-IOV mode. The current default is true but should be changed to false
before this is merged to master.
> REQ-627 introduce option to use SR-IOV for Nvidia T4

- ocaml/xapi/xapi_host.ml
Syslog outputs it anyway, so it is pointless to include it twice in the
log line, and it complicates the Debug module of xcp-idl.
> CA-326244: do not include host name in log format

- scripts/set-hostname
Prior to this change:
```
/opt/xensource/libexec/set-hostname foo
logger testing
systemctl kill -s HUP rsyslog
logger testing
```
```
Sep 20 14:25:35 piquet root: testing
Sep 20 14:26:30 foo root: testing
```
Thanks to @srowe for the suggestion.
> Fix incorrect hostname in syslog: send HUP when hostname is changed

- ocaml/tests/suite_alcotest.ml
- ocaml/tests/test_bios_strings.ml
- ocaml/tests/test_data/bios_baseboard_two.dmidecode
- ocaml/tests/test_data/bios_invalid.dmidecode
- ocaml/tests/test_data/bios_oem.dmidecode
- ocaml/tests/test_data/bios_with_array.dmidecode
- ocaml/xapi/bios_strings.ml
- ocaml/xapi/bios_strings.mli
- ocaml/xapi/dune
- xapi.opam
The current code uses `dmidecode -s` to gather baseboard values.
This is problematic because it's impossible to distinguish between multiple values and a single value with multiple lines.
This adds parser using the angstrom library which can replace all ad-hoc code that was used before. As an example, there's a commit that replaces how OEM info is gathered.
Parser has been dev-tested with outputs from workstations and servers
> CA-325988: Use one baseboard value when more than one is on the system

- xapi.opam
Missed it when adding the demidecode tests
> CA-325988: Add fmt dependency to opam for tests

- ocaml/xapi/xapi_pci_helpers.ml
It appears to be very common for devices in dom0 to not have a driver link
(/sys/bus/pci/devices/XX/driver), i.e. to not be bound to a driver. This
currently leads to lots of alarming lines in the logs. However, it is nothing
to worry about, and not worth logging.
> Remove spammy log lines

- ocaml/xapi/bios_strings.ml
In the case where more than one line is found in `remove_invisible` we assume that there are multiple values and pick the first one.
This is safe to do on all 3 usages of the function:
1. When used for oem_strings the string is guaranteed to not contain any eols (the string always ends at the first eol after it starts: `String.index_from result b '\n'`)
2. When used for hp_rombios anything that is not "COMPAQ" gets converted to "" (the 6 bytes that get read); eols are irrelevant in this case.
3. When used in `get_bios_string` none of the values gathered are expected to contain eols (manufacturer names, versions and serial numbers)
> CA-325988: Limit BIOS strings to a single line

- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_vgpu_type.ml
This supersedes commit "REQ-627 add hack to identify SR-IOV GPUs".
Previously we addressed NVidia T4 cards using SR-IOV provided it is
activated in the global configuration switch nvidia_t4_sriov. The T4
cards were detected based on their IDs.
This commit introduces more options based on the value of
nvidia_t4_sriov in xapi.conf:
* "default" - the addressing mode is taken from vgpuConfig.xml
* "true"    - T4 cards are addressed using SR-IOV, legacy otherwise
* "false"   - all cards are addressed using legacy mode
> REQ-627 more options to infer SRIOV mode

- ocaml/xapi/xapi_globs.ml
Define the default how to to address an NVidia VGPU: consult
vgpuConfig.xml. Currently no customer should have a configuration that
enables SRIOV. For development we can still enable SRIOV on T4 cards
explicitly.
> REQ-627 don't use SRIOV for VGPU by default

- ocaml/xapi/dbsync.ml
- ocaml/xapi/dbsync_slave.ml
When xapi repeatedly fails to start it was not
clearing failed dbsync tasks from the database.
Assigning the `resident_on` field fixes this
for a pool scenario.
> CA-32641 Orphaned dbsync tasks cleaned up

- ocaml/xapi/xapi_gpumon.ml
Xapi saves vGPU compatibility metadata for a vGPU when its VM is
suspended. This was failing for SRIOV vGPUs because they were not
correctly identified by the is_nvidia() predicate.
> REQ-627 CA-328495 not saving vGPU metadata

- ocaml/xapi/dbsync.ml
- ocaml/xapi/dbsync_slave.ml
Reverts xapi-project/xen-api#3964. This broke some tests, which we will need to investigate.
> Revert "CA-32641 Orphaned dbsync tasks cleaned up"

- ocaml/xapi/dbsync_slave.ml
Attempt two to fix Orphaned dbsync tasks not
being cleaned up. The first 'fix' was breaking
and was reverted in
e0aa8df8fce51be8543c77940b5f706a4712f91a
Server_helpers.exec_with_new_task uses the
global localhost_ref to set the resident on field
for the tasks it creates. However this global
variable is actually assigned during the first
task, so we must set it manually in this case.
> CA-326241 Set resident_on manually for first task

- ocaml/xapi/xapi_vm_lifecycle.ml
- ocaml/xapi/xapi_vm_migrate.ml
This commit adds code to remove stale entries in a VM's list of attached
PCI devices. See CA-328075 for a detailed description and why this
problem occurs and why it is difficult to fix properly. The code assumes
that after a migration the only PCI devices attached to a VM can be
vGPUs because PCI devices can't be migrated so far.
The second commit fixes an earlier commit for releasing PCI objects from
a VM when it is halted or suspended.
> REQ-627 CA-328075 after migration, remove stale PCI

- ocaml/idl/datamodel_vm.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_ha_vm_failover.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_vm.ml
- ocaml/xapi/xapi_vm_helpers.ml
- ocaml/xapi/xapi_vm_migrate.ml
Details in the commit messages: this is needed so that XenCenter can use an API call instead of hardcoding/duplicating logic from XAPI.
> CP-32437: `assert_can_boot_here`  should perform CPUID checks

- ocaml/xapi/xapi_vbd_helpers.ml
- ocaml/xapi/xapi_vm_helpers.ml
When creating a VM template, VM metrics were
destroyed in the DB, but ref was still
hanging around. This meant that performing
a vdi-pool-migrate on that template failed with
'invalid object reference.... class: VM_metrics'.
Fix involves setting the appropriate VM metric
ref to null, and ensuring that the VBD valid
operations are correct for halted VMs.
> CA-313081 fix moving template between SRs

- ocaml/xapi/create_misc.ml
ff50be0b3b20102ca49cd252d32bdaea89619e06 made it an error to have an
unspecified current domain type at VBD plug time.
Dom0 of slave hosts always had an unspecified current_domain_type,
a bug caused by the pool join code.
When a slave joins a pool we import all VMs, and the import code deals
only with halted VMs (it sets current_domain_type to `unspecified`).
However Dom0 is special: it is the only VM allowed to be running when
joining a pool, so we must fix up the current_domain_type.
Do this in the function that updates other fields of Dom0's metric
record on startup to ensure it is always correct.
> CA-330979: set current_domain_type for slaves

- scripts/extensions/pool_update.apply
- scripts/extensions/pool_update.precheck
It is possible to have two update ISOs which have the same update name, but
contain different versions of the update. The most obvious example is a driver
disk, where we might have different versions depending on the platform version
in use.
There is a potential issue in that yum will cache the repository metadata based
on the name of the repository (which in our case is the name of the update).
If the repository 'on disk' has an older timestamp than the cached data, then
yum will ignore the 'on disk' data, and use the cached information.
In the scenario where a user has erroneously attempted to apply the update from
the wrong version, we can end up in a situation where despite attempting to
apply the correct update, the metadata has been cached from the incorrect one,
and thus yum will …
> CA-330961 Clean the yum cache before prechecking/applying an update

- ocaml/xapi/cli_operations.ml
- ocaml/xapi/xapi_vbd.ml
- ocaml/xapi/xapi_vbd_helpers.ml
- ocaml/xapi/xapi_vm.ml
- ocaml/xapi/xapi_vm_helpers.ml
This is a backport of CA-330162 to 8.1.
It includes what I hope is a fix for failing BVTs.
Needs to go in alongside https://github.com/xapi-project/xenopsd/pull/691
> Allow guests to see floppies

- ocaml/database/db_cache_types.ml
- ocaml/database/schema.ml
- ocaml/xapi/helpers.ml
- ocaml/xapi/xapi_host_helpers.ml
- ocaml/xapi/xapi_pgpu_helpers.ml
Pervasives is deprecated in ocaml 4.08 - bringing
some compiler warnings to fix. This change is
compatible with 4.07.
> maintenance: remove Pervasives deprecated warnings

- ocaml/mpathalert/mpathalert.ml
Systemd manages daemonization of mpathalert
> CP-28369: remove unused daemonize code

- scripts/test_usb_scan.py
Fixes failing tests introduced in da190399972fcaf2643892434091d2a29a97e2d2
This happened because usb_scan.py now reads the
usb speed from udev, causing failing tests, and
this field was missing in test_usb_scan.py
> CA-328130 Fix usb_scan tests

- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_sr.ml
- ocaml/xapi/xapi_sr_operations.ml
Make sure data sources for an SR are not kept in memory in xcp-rrdd when the SR is destroyed or forgotten.
> Ca 325582 clean up dead SR metrics

- ocaml/quicktest/qt.ml
- ocaml/quicktest/qt.mli
- ocaml/quicktest/qt_filter.ml
- ocaml/quicktest/quicktest_vdi.ml
This does not fix all failures, but some.
Some storage quicktests were failing on pools
because by default it runs each test for each SR
a host can see - including the local storage of
another host in the pool. To fix we add a filter
to remove such SRs.
`vdi_snapshot_in_pool` was also iterating over
hosts - it should not have been, because we
don't necessarily have access to that host's SRs.
Instead, only test snapshot on localhost.
> CA-325582 fix some storage quicktests for pools

- scripts/init.d-xapissl
The issue to be fixed in this commit is that stunnel on server side may
close SSL connection without sending SSL alert firstly.
The case looks like that a stunnel client requests more than 640KB data
from stunnel server. When the stunnel on server side finds that its
backend (XAPI) closes the local socket, it sets `shutdown_wants_write`
as 1 so that in next receiving loop it expects to send SSL alert. But
actually before sending the SSL alert, it closes SSL connection.
This is due to `TIMEOUTclose` is set to 0. The stunnel on server side
returns from `s_poll_wait` with timeout, returns from transfer loop, and
eventually closes the SSL connection from TCP's point of view.
This is not a 100% reproducible issue.
Setting the `TIMEOUTclose` to 1 can make stunnel on server side get a
chance to …
> CA-331142: stunnel on server side close SSL sock unexpectedly

- ocaml/xapi/xapi_pci.ml
- ocaml/xapi/xapi_pci.mli
- ocaml/xapi/xapi_pgpu.ml
Before we can bind PCI drivers we need to dequarantine the device. This
is done by calling into Xenopsd to let it do the work. (Hence, this must
happen on the host where the device is.) We employ this in the context
of setting up Nvidia SRIOV devices.
This PR depends on https://github.com/xapi-project/xcp-idl/pull/302 which has been reverted but needs to be active. Because of cross-repo dependencies, Travis is broken.
> REQ-627 CA-333495 add Xapi_pci.dequarantine

- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_sr.ml
To help avoid memory usage growing in xcp-rrdd, we delete SR metrics whenever an SR is forgotten or destroyed
> CA-325582 backport to 7.1 CU2

- ocaml/tests/test_platformdata.ml
- ocaml/xapi/vm_platform.ml
[root@lcy2-dt106 ~]# xe vm-start uuid=39b8d59d-7cc7-7e71-8107-28ba5e2ad74e
The server failed to handle your request, due to an internal error. The given message may give details useful for debugging the problem.
message: Division_by_zero
Also reject a negative cores-per-socket, which is equally nonsensical, and
only gets caught by the sanity checks in the Xen:
[root@lcy2-dt106 ~]# xe vm-start uuid=39b8d59d-7cc7-7e71-8107-28ba5e2ad74e
The server failed to handle your request, due to an internal error. The given message may give details useful for debugging the problem.
message: xenopsd internal error: (Failure
"Error from xenguesthelper: xenguest: xc_domain_set_cores_per_socket: [22]
Invalid argument")
Also take the opportunity to make the error messages helpful, by returning the
current …
> Fix parsing of platform:cores-per-socket to avoid divide-by-0 error

- scripts/init.d-xapissl
This fix is to disable TLSv1.3 when legacy is true.
> CA-334797: Disable TLSv1.3 when legacy is true

- ocaml/xapi/certificates.ml
- scripts/generate_ssl_cert
This adds ocaml code equivalent to the `scripts/generate_ssl_cert` script.
Needs https://github.com/xapi-project/stdext/pull/43 to work correctly
> CP-32686: Native certificate installation

- ocaml/idl/datamodel.ml
- ocaml/idl/datamodel_certificate.ml
- ocaml/idl/datamodel_common.ml
- ocaml/idl/datamodel_host.ml
- ocaml/idl/dune
- ocaml/xapi/api_server.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/records.ml
This allows the xapi to easily expose the server certificates metadata
to clients. In particular their validity period and fingerprint.
There a quite a lot of pulls and levers to configure when adding a class to the schema db, althought they can be changed later on
So there are some things I'm don't know about:
- `~gen_constructor_destructor` what would it be needed for? I would only like to create an object when the certificate is installed.
- I'm unsure whether we want to force a 1 to 1 relationship between host and server certificate. I've added it as a one-to-many in case this could change in the future.
In addition I'm not fond of using the hand-crafted `Date` module from stdext, seems pretty limited.
> CP-32681: Add certificates to DB schema

- ocaml/database/backend_xml.ml
- ocaml/xapi/helpers.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/storage_migrate.ml
- ocaml/xapi/storage_utils.ml
- ocaml/xapi/xapi_cli.ml
- ocaml/xapi/xapi_db_upgrade.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_secret.ml
- scripts/extensions/pool_update.apply
- scripts/extensions/pool_update.precheck
- scripts/host-bugreport-upload
This PR is for a series of backports:
* be8ff590f CA-333712: use wrapped string type for pool internal API calls   
* 010b3759f CA-329466: Simplify logging for plugins' parameters              
* 49bf6d71e CA-329835 Improve logging                                        
* 1523addcd CA-329843: broaden usage of secrets API                          
* 6fe63ab87 CA-330902 host-bugreport-upload args via env vars                
* b69de0058 CA-330902 Improve logging - backport it                          
* cef84c2a7 CA-330902 Improve logging                                        
* 6609d0346 CA-330693: Limit access to state.db to just root                 
* 49351479d CA-330961 Clean the yum cache before prechecking/applying
Except for CA-333712 the backports have not required considerable …
> Havana Backports

- ocaml/xapi/workload_balancing.ml
- ocaml/xapi/xapi_vm.ml
- ocaml/xapi/xapi_vm_helpers.ml
Before, if all the recommendations were 0 for some reason xapi would needlessly migrate all the VMs.
This also introduces a small change in the API in the case an internal error happened when processing a retrieve_wlb_recommendations API call: now it's more consistent and more data is returned.
After talking with @liulinC it's clear that vm recommendation always contains both the `Stars` field and the `ZeroScore`. The code now expects those values to be congruent or it considers the whole response nonsense.
> CA-334951: Ignore 0-star recommendations from WLB

- ocaml/idl/datamodel_errors.ml
In CA-336253 xe cluster-pool-destroy failed with a confusing error message saying that the cluster stack is already in use.
The reason for the failure was that a PBD unplug has previously failed (but XenRT didn't notice and ignored it), which then caused this failure in destroy.
Improve the error message to say that something earlier failed.
@MarkSymsCtx FYI
> Fix cluster_stack_in_use error message

- ocaml/xapi/xapi_vdi.ml
Previously hostname could be empty if there were no hostnames available
in the certificate.
Now the hostname from xapi's database is picked instead.
This PR needs https://github.com/xapi-project/xs-opam/pull/433 as it's a breaking change.
> CP-32678: update to X509 0.9.0

- ocaml/xapi/xapi_vm.ml
Add a check into VM start to check its memory configuration if the VM
has an SRIOV vGPU. We disable ballooning (DMC) and POD (populate on
demand) by pinning memory to static max. The main point is disabling POD
but we found it difficult to implement while still permitting
ballooning. So we are disabling both by demanding that the memory
configuration is fixed at the upper limit at the start of the VM.
> CP-32398 must not use POD when using SRIOV vGPU

- ocaml/xapi/xapi_cluster.ml
- ocaml/xapi/xapi_cluster_host.ml
- ocaml/xapi/xapi_clustering.ml
- ocaml/xapi/xapi_ha_vm_failover.ml
The library result is deprecated and it doesn't have the same interface as the standard library.
> CP-32649: Use Stdlib's Result

- ocaml/idl/datamodel_common.ml
- ocaml/idl/datamodel_errors.ml
- ocaml/idl/datamodel_host.ml
- ocaml/idl/datamodel_pool.ml
- ocaml/tests/test_certificates.ml
- ocaml/xapi/certificates.ml
- ocaml/xapi/cli_frontend.ml
- ocaml/xapi/cli_operations.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_host.mli
- ocaml/xapi/xapi_pool.ml
Adds an API call to install user-created server certificates.
This does _not_ add parameters to xe.
Draft PR as I have some doubts around severing the connection between hosts when the certificates need to be reloaded. Especially regarding the DB update that needs to be done, and the function that checks whether the recovery of the connection happened successfully.
If something is not clear from the code or the commit messages please let me know.
> CP-32678: Add API to to install server certificates

- ocaml/xapi/xapi_vm_migrate.ml
During an intra-pool migration, the VM's VIFs must be on the same network, so make that explicit in the error message
> improve invalid VIF map error message for intra-pool migration

- Makefile
- ocaml/alerts/certificate/certificate_check.ml
- ocaml/alerts/certificate/certificate_check_main.ml
- ocaml/alerts/certificate/dune
- ocaml/tests/dune
- ocaml/tests/suite_alcotest.ml
- ocaml/tests/test_alert_certificate_check.ml
- ocaml/xapi-consts/api_messages.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_globs.ml
- scripts/Makefile
- scripts/certificate-check
Adds a daily cron job that checks the validity of the certificates for all hosts.
It also checks alerts for hosts with installed certificates and clears them before adding the new alerts.
Depends on https://github.com/xapi-project/xen-api/pull/4038
> CP-32696: Add alerts for certificate expiration

- .travis.yml
Now `.travis.yml` follows best practices:
* `sudo` doesn't have an effect anymore
* `os` and `dist` have defaults, but it's better to set them
* `matrix` is no `jobs`
* the slack token was not encrypted and it had been invalidated in any case.
> travis: follow validator recommendations

- ocaml/auth/dune
- ocaml/cdrommon/dune
- ocaml/database/dune
- ocaml/db_process/dune
- ocaml/doc/dune
- ocaml/events/dune
- ocaml/idl/dune
- ocaml/idl/json_backend/dune
- ocaml/idl/ocaml_backend/dune
- ocaml/mpathalert/dune
- ocaml/perftest/dune
- ocaml/ptoken/dune
- ocaml/quicktest/dune
- ocaml/tests/dune
- ocaml/util/dune
- ocaml/vncproxy/dune
- ocaml/xapi-cli-protocol/dune
- ocaml/xapi-client/dune
- ocaml/xapi-consts/dune
- ocaml/xapi-types/dune
- ocaml/xapi/dune
- ocaml/xapi/xapi.ml
- ocaml/xe-cli/dune
- ocaml/xsh/dune
This has been removed from xcp-idl and causing the build to fail now.
Also simplify the dune files and drop unused coverage from there too.
> Fix build: drop Xcp_coverage

- ocaml/idl/datamodel.ml
- ocaml/idl/datamodel_host.ml
- ocaml/xapi/cli_frontend.ml
- ocaml/xapi/cli_operations.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_host.mli
If successful it deletes the current certificate and places a new,
self-signed on instead. It also deletes the database record of the
server certificate currently installed in the host.
This call is only available locally only.
Its implementation is barebones as it's replicating what happens when gencert is called on first startup.
This is meant to change with https://github.com/xapi-project/xen-api/tree/feature/REQ-811/master and after both features get merged the bash script will be replaced by an ocaml binary, as well as xapi making an effort to add the existing self-signed cert to the database.
> Add emergency call to reset TLS server certificates

- ocaml/xapi/xapi_vm.ml
Interfaces such as xe were exposing this string, with the conversion to
and from float the format was changed. With this make an extra effort to
preserve the formatting for the usual range of values.
Values lower than 0.0001 will still show up with the exponential format:
9.99e-5
> CA-336735: preserve formatting of stars for wlb recommendations

- ocaml/xapi/xapi_mgmt_iface.ml
- ocaml/xapi/xapi_mgmt_iface.mli
REQ-811 removed the ability for arbitrary code inside xapi to restart
stunnel, but this is required for REQ-453, so we reintroduce it.
> REQ-453 re-expose reconfigure_stunnel

- ocaml/xapi/xapi_vdi.ml
Should be merged along https://github.com/xapi-project/xs-opam/pull/446 Travis will fail until xs-opam is updated.
> CP-33380: update to x509 0.10.0

- ocaml/database/db_cache_test.ml
- ocaml/database/dune
- ocaml/database/unit_test_marshall.ml
- ocaml/database/unit_test_sql.ml
- ocaml/pci/lib_test/dune
- ocaml/pci/lib_test/test_pci.ml
- ocaml/pci/opam
- xapi-database.opam
- xapi.opam
The PCI tests are not being run, the database tests are not run under opam and the db test  unit_test_sql didn't seem to be run in any case.
Ported the database tests to alcotest so now the ounit dependency can be dropped from xapi.
It's still used to thest ocaml-pci, but that is probably better done upstream, along with the fixes applied in this repo.
> Enable dormant tests

- ocaml/xapi/sparse_dd_wrapper.ml
the '-good-ciphersuites' argument to sparse_dd got removed erroneously, so we restore it
> restore missing argument to sparse_dd

- ocaml/xapi/smint.ml
I also had another commit in my branch for fixing some missing SM capabilities, so lets add those too.
Needs https://github.com/xapi-project/sm/pull/496 too before XenCenter can actually see this (and for old versions it might have to either hide it, or have a hardcoded list of SRs)
> CP-33292: add VDI read caching capability for SM

- scripts/gencert.service
stunnel@xapi.service depends on gencert, so if the
xapi-wait-init-complete service fails, it takes 4 minutes for stunnel to
start. This was seen when rebooting slaves, but is easily fixed by
removing this dependency
> CA-337929 remove gencert xapi-wait-init-complete dependency

- scripts/xapi.service
Stunnel is required to start/stop domains on slaves.
Fixes CA-337894 (and other related bugs).
> CA-337903 xapi-domains requires stunnel

- ocaml/xapi/sparse_dd_wrapper.ml
Due to operator precedences, the "-base" argument would not be passed to
sparse_dd whenever `prezeroed` was true. We fix this by using
List.concat instead of @, and parens by recommendation of ocamlformat
> CA-337875 base not always passed to sparse_dd

- ocaml/idl/datamodel_common.ml
This is needed since the original schema bump done for REQ-453 was invalidated by the merge for REQ-811.
> Bump schema for REQ-453

- ocaml/xapi/helpers.ml
- ocaml/xapi/import.ml
This should be reverted once a fix has been found - it only contains
logging changes.
During firstboot, the create-guest-templates script sometimes fails.
This failure appears to coincide with a call to
host.management_reconfigure at just the wrong time, but the cause is
not clear.
> CA-336730 add debugging to help solve template timeout issue

- ocaml/xapi/helpers.ml
- ocaml/xapi/import.ml
This reverts commit 9fd79835aa0e91346491efb1a35f2fd65d06b245.
We are still seeing this issue, but we remove this debug logging for
the next release.
> Revert "CA-336730 add debugging to help solve template timeout issue"

- ocaml/xapi/extauth.ml
- ocaml/xapi/extauth_plugin_ADpbis.ml
- ocaml/xapi/helpers.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi.ml
- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_subject.ml
CA-338602: lwsmd daemon should not be running when AD is not configured
This commit suppose lwsmd service is not bootup by default, and
manage lwsmd service as follows
1. during xapi start, it will start lwsmd if the host is authed
with AD
2. start lwsmd during enabling AD auth
3. stop lwsmd during disabling AD auth
> CA-338602: lwsmd daemon should not be running when AD is not configured

- Makefile
- ocaml/util/dune
- ocaml/util/gen_build_info_ml.sh
- ocaml/util/xapi_version.ml
- xapi-cli-protocol.opam
- xapi-client.opam
- xapi-consts.opam
- xapi-database.opam
- xapi-datamodel.opam
- xapi-types.opam
- xapi.opam
- xe.opam
When building with opam, we use `dune subst` to interpolate the version.
We add `dune subst` to the build steps in all opam files to avoid silent
failures if we move xapi_version.ml to a different package. dune
recommends this when integrating with opam anyway.
We cannot use `dune subst` when building the xapi rpms (no git context).
To get around this we expose a make target. For completeness this works
in a developer context, where git is available.
> CA-334811 assign xapi version automatically

- ocaml/idl/datamodel_vm.ml
This change aims to expose 'scheduled_to_be_resident_on' as a XAPI
event. Consequently, xen-api-sdk could support this event also.
> CA-337867: Expose 'scheduled_to_be_resident_on' to XAPI event

- ocaml/idl/datamodel_diagnostics.ml
Make the new gc_compact API call public:
* because it can be useful for clients
* to cause the SDK export this class, which otherwise would be empty
and not exported. This causes problems with reading state.db into
XenCenter, which is now avoided.
> CA-339526 make gc_compact call public

- scripts/generate-iscsi-iqn
- scripts/network-init
There are 4 problematic scripts - we fix 2 of them here.
To preserve old behaviour of the firstboot scripts, we don't sync the
DB during an upgrade.
If we do sync the DB during an upgrade, then we get an error complaining
that incoming DBs have an incompatible schema version. This happens
because hosts are told to send the the minimally compliant Miami DB
- see pool_db_backup.ml.
> CA-339329 firstboot scripts shouldn't sync DB when ugprading

- ocaml/gencert/dune
- ocaml/gencert/gencert.ml
- ocaml/gencert/lib.ml
- ocaml/gencert/lib.mli
- ocaml/xapi-consts/constants.ml
- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_host.ml
- scripts/gencert.service
- scripts/xapi.service
openssl was complaining about being "unable to write 'random state'".
A fix for this is to set HOME or RANDFILE. We opt for the former to
avoid depleting the system's entropy.
openssl will now write to $HOME/.rnd
> CA-339656 use HOME when generating SSL certificate

- ocaml/idl/datamodel_vm.ml
This led to BVT failures because guest templates are affected.
This reverts commit d15082d2bde4f001f31cab244493e5631b4c25ac.
> Revert "CA-337867: Expose 'scheduled_to_be_resident_on' to XAPI event"

- ocaml/idl/datamodel_vm.ml
This reintroduces d15082d2, but now with a default value added, which is
necessary for imports of existing VM images.
> CA-337867: Expose 'VM.scheduled_to_be_resident_on' field (take 2)

- Makefile
- ocaml/util/dune
- ocaml/util/gen_build_info_ml.sh
- ocaml/util/xapi_version.ml
- xapi-cli-protocol.opam
- xapi-client.opam
- xapi-consts.opam
- xapi-database.opam
- xapi-datamodel.opam
- xapi-types.opam
- xapi.opam
- xe.opam
This reverts commit 5c05f22a187908b6c832113803607b2758e95264.
We have found the bug in guest-templates-json: it was running on a
slave, when it shouldn't.
Try to restore the version number change and the stricter check.
Running a build and will do some tests.
> Revert "Revert "CA-334811 assign xapi version automatically""

- ocaml/tests/test_vm_check_operation_error.ml
- ocaml/xapi/xapi_globs.ml
It is needed to avoid downtime during RPU when VMs are running on local
storage and is already allowed for cross-pool storage migration between
mismatching XAPI versions, provided the destination has a higher version.
Related to #3764
I must admit that there may be a good reason why it was disabled in the first place, but I think that the reasons might not be valid anymore. If you look at the commit history, it was removed with commit 6760dad which says "Migrate_send wasn't a Miami operation". My guess is that the list of allowed actions was downgraded to those that "Miami" was able to handle. If I'm right, it has become less and less likely that someone would attempt an upgrade from that version (is it supported at all?).
Local migration tests went fine.
> Allow migrate_send during RPU

- ocaml/xe-cli/newcli.ml
Disconnecting from stunnel as soon as we finished uploading the
requested file causes some unexplained EOFs.
XE used to disconnect from stunnel only at the end, so restore this
behaviour. We can address the stunnel bug revealed by this another time.
Also need to keep the channels alive longer, so manually create them
instead of using the with_ variant that closes them when we're done with them.
> CA-340776: move stunnel disconnection to the end where it was

- ocaml/xe-cli/fpath.ml
- ocaml/xe-cli/fpath.mli
This vendors the fpath module such that we can use it to check paths for the XE client. I've decided that this is easier than adding the module to the xs-opam library collection because it is only used here and only in the context of a backport. You might disagree.
> CA-338596 vendor fpath module

- ocaml/idl/datamodel.ml
- ocaml/idl/datamodel_common.ml
- ocaml/idl/datamodel_types.ml
- ocaml/tests/test_common.ml
- ocaml/tests/test_tunnel.ml
- ocaml/xapi-cli-server/cli_frontend.ml
- ocaml/xapi-cli-server/cli_operations.ml
- ocaml/xapi-cli-server/record_util.ml
- ocaml/xapi-cli-server/records.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/nm.ml
- ocaml/xapi/xapi_bond.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_tunnel.ml
- ocaml/xapi/xapi_tunnel.mli
- ocaml/xe-cli/bash-completion
The commit opens the VxLAN IANA port (4789 udp) when a SDN controller is introduced and close it when its removed. 
This allow the SDN controller to creates VxLAN without having to manually change iptables rules.
> Open VxLAN port for SDN controller

- ocaml/xapi-aux/pool_role.ml
This was broken in ee226e0, since Astring.String.cut
doesn't behave as expected.
> fix pool config parsing

- ocaml/xapi/message_forwarding.ml
Prefer to use Client.InternalAsync.VDI.copy over
Client.VDI.copy to avoid long running idle
connections when instructing a slave to perform
a VDI.copy.
For more information see CA-333610, where the
same problem was fixed for VM.migrate_send
> CA-335033 avoid idle connections during VDI copy

- ocaml/tests/dune
- ocaml/tests/suite_alcotest.ml
- ocaml/tests/test_psr.ml
- ocaml/xapi/xapi_psr.ml
- ocaml/xapi/xapi_psr.mli
We implement a function which orchestrates a pool secret rotation.
We handle failure by splitting the PSR into idempotent chunks, and
saving checkpoints at the end of each chunk. This will allow us to
resume from failed PSRs, and importantly reduce the chance of hosts
becoming locked out with the wrong pool secret.
> CP-33774 PSR orchestration

- ocaml/xapi/api_server.ml
- ocaml/xapi/xapi.ml
A previous patch changed `jsoncallback` to call `callback1` with
`is_json:true`. Unfortunately, this broke the responses. The fix is to add a
new parameter `is_jsonrpc` for this case.
> CA-341442: is_json does not mean is_jsonrpc after all

- ocaml/idl/datamodel.ml
- ocaml/idl/datamodel_vm.ml
The datamodel changes in https://github.com/xapi-project/xen-api/pull/4057 incorrectly state that were introduced in the stockholm release, this feature was only added after stockhlm branched off.
> XSO-974: correctly reflect datamodel changes in stockholm

- ocaml/pci/lib_test/test_pci.ml
The testing container changed the debian distribution changed, this changed the PCI tests.
Depending on the distributions' pci package the string for red hat might change, adapt the test so it accepts the two values the string might take.
Error looks like this:
```
Value "Red Hat, Inc." is not any of the expected ones: ["Red Hat, Inc"]
```
> Fix travis tests

- ocaml/xapi/db_gc.ml
This was happening in some cases, but not all
Cherry-pick of https://github.com/xapi-project/xen-api/commit/991de5bfaaee877b9a044b178d23ee56442588e9
> CA-341149: Ensure a wait happen when the heartbeat connection fails

- ocaml/pci/lib_test/test_pci.ml
Depending on the distributions' pci package the string for red hat might
change, adapt the test so it accepts the two values the string might
take.
Backport of 7cdc390db
> pci: fix tests for all distributions (backport)

- ocaml/idl/datamodel_errors.ml
This message has an override in xen-api-sdk which corrects the language. This practice should generally be avoided, unless absolutely necessary, because the content of the override may get out of sync as it has happened in this case. This PR corrects the original message and this one https://github.com/xapi-project/xen-api-sdk/pull/177 removes the outdated SDK override.
> Error message improvement.

- ocaml/xapi-types/features.ml
- ocaml/xapi-types/features.mli
- ocaml/xapi/xapi_psr.ml
We don't actually want to ever disable this this
feature, but the flag is used by XC to determine
whether to show PSR button or not.
> CA-34357 add PSR feature flag

- ocaml/xapi/vhd_tool_wrapper.ml
Also deleted custom implementation for String.startwith
Unblocks https://github.com/xapi-project/stdext/pull/48
> CP-33121: Remove unused dependency on stdext's fun module

- xapi.opam
- xe.opam
recently fpath was introduced and stdext-monadic was removed, update the
opam metadata to reflect this
> opam: update dependencies

- .github/workflows/main.yml
This approach substitutes the current shellscript for travis, as just simply running like in https://github.com/xapi-project/xs-opam/pull/468 produced failures.
The part that loads the .env file is a bit clunky since it needs to remove ` export ` from every line.
This approach has the benefit that it better shows how a developer would build and test the repository using an opam switch instead of running an opaque scripts that only is run for CI.
When running the jobs now it's plain simple how much do the steps take, most of the time being spent compiling the dependencies. Cache is used to speed up build by about 8 minutes, the cache is invalidated daily to minimize problems with packages in xs-opam that are not versioned and use 'master' as their version.
A daily scheduled run serves as a …
> CI: use github actions

- ocaml/idl/datamodel_host.ml
- ocaml/idl/datamodel_pool.ml
- ocaml/idl/datamodel_types.ml
- ocaml/tests/test_common.ml
- ocaml/tests/test_psr.ml
- ocaml/xapi/dbsync_master.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_ha.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_host.mli
- ocaml/xapi/xapi_pool_helpers.ml
- ocaml/xapi/xapi_pool_helpers.mli
- ocaml/xapi/xapi_psr.ml
- ocaml/xapi/xapi_psr.mli
- ocaml/xapi/xapi_psr_util.ml
We add some sanity checks before performing PSR
operations.
The main motivation for this is that if the master
changes after a failed PSR then we want to block
the next PSR. The idea is to avoid lockout at all
costs, even though manual intervention may be
required to fix the issue.
> CP-34379 don't proceed with rotation if PSR state is inconsistent

- ocaml/auth/dune
- ocaml/tests/common/suite_init.ml
- ocaml/tests/test_daemon_manager.ml
We should normally only use things as set up by an opam switch, however here we were also linking in things from the system OCaml compiler, for no good reason AFAICT. Removing the `/usr/lib64/ocaml` flag still makes everything link inside a `pxc` buildenv, and it also fixes the build when the system compiler != opam compiler. (E.g. Fedora 32 has OCaml 4.10 as system compiler)
> maintenance: fix build when system compiler != 4.08

- ocaml/xapi/xapi_ha.ml
This changes how essential parameters for the HA daemon are derived from
the xe pool-ha-enable timeout parameter. So far, the network heartbeat
was always configured to use 10 heartbeats in an interval. There is good
reason to believe that this contributed to the unreliability of HA.  HA
uses two heartbeats:
(1) UDP network heartbeat - fast and unreliable
(2) State file heartbeat - slow and reliable
HA's network heartbeat is sensitive to network congestion and with only
10 heartbeats configured before a timeout would trigger HA, it was easy
for HA to trigger. This patch addresses the asymmetry of the heartbeats:
* We want more network heartbeats than storage heartbeats because they
are cheap but can be lost.
* We want a minimum time to pass between heartbeats - less for network
and more …
> Improve HA parameter derived from timeout

- scripts/host-backup-restore/host-backup
When using a UEFI-booted host, /boot/efi is a separate mountpoint and so
it does not get included in the backup tarball due to the use of
--one-file-system. This causes the restore to fail due to missing files.
Explicitly include /boot/efi to fix restore with UEFI hosts. Note that
with legacy-booted hosts, /boot/efi is not a separate mountpoint but
including it twice is fine.
> CA-343117: host-backup: Include /boot/efi in the tarball

- ocaml/xapi/xapi_host.ml
We previously changed the Stdext.Date library to
only accept UTC. This of course doesn't work
correctly when we are trying to work with a
server's localtime. The library has been modified
to handle non-UTC times again, so we use those
changes here.
> CA-342171 fix get_server_localtime

- ocaml/xapi/xapi_mgmt_iface.ml
The intention of the if-statement in `start` is to only refresh the consoles on
the master if management is enabled, which is the case when the server is
running on all IP addresses. The `listening_all` ref, however, is updated only
_after_ the call to the `start` function. Instead refer to the `addr` parameter.
Backport of 07b62434.
> CA-341155: Fix console refresh when starting management server

- ocaml/xapi/xapi_fist.ml
- ocaml/xapi/xapi_periodic_scheduler_init.ml
The existence of two fistpoints was only ever checked
when the Xapi_fist module is loaded at runtime, and
that result cached. I.e. from xapi's point of view,
these two fistpoints would be either always present,
or always not present. Instead we want to query the
filesystem each time we check for a fistpoint.
> maintenance: ensure all fistpoints work as expected

- ocaml/idl/datamodel_pool.ml
- ocaml/xapi-cli-server/record_util.ml
- ocaml/xapi-consts/api_errors.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_ha.ml
- ocaml/xapi/xapi_pool.ml
- ocaml/xapi/xapi_pool_helpers.ml
- ocaml/xapi/xapi_pool_helpers.mli
- ocaml/xapi/xapi_psr.ml
We want to avoid the master changing whilst a pool secret
rotation is pending, so in particular we should block
pool-designate-new-master.
We do _not_ block pool-emergency-transition-to-master, but note
that it should not be used lightly.
> Block PSR if pool operations are running, and vice versa

- ocaml/xapi/rbac.ml
In CA-343787 we got an incorrect backtrace:
```
Sep  1 09:36:29 localhost xapi: [error||1089 INET :::80||backtrace] host.apply_edition D:8d81d8dc6320 failed with exception Not_found
Sep  1 09:36:29 localhost xapi: [error||1089 INET :::80||backtrace] Raised Not_found
Sep  1 09:36:29 localhost xapi: [error||1089 INET :::80||backtrace] 1/13 xapi Raised at file hashtbl.ml, line 194
Sep  1 09:36:29 localhost xapi: [error||1089 INET :::80||backtrace] 2/13 xapi Called from file lib/xapi-stdext-pervasives/pervasiveext.ml, line 24
Sep  1 09:36:29 localhost xapi: [error||1089 INET :::80||backtrace] 3/13 xapi Called from file lib/backtrace.ml, line 114
Sep  1 09:36:29 localhost xapi: [error||1089 INET :::80||backtrace] 4/13 xapi Called from file lib/xapi-stdext-pervasives/pervasiveext.ml, line 35 …
```
> Do not loose backtrace in RBAC

- ocaml/xapi/xapi_vm_lifecycle.ml
During VM storage migration it was possible to start the VM.
This leads to errors (VDI in use and illegal storage transition).
To resolve this issue the start and start_on operation were removed from the allowed_operations list in the is_allowed_concurrently function.
This removes the Start and Start On operations from the XenCenter vm menu, thus preventing the user from encountering the errors.
Signed-off-by: Gheorghe Burac <gheorghe.burac@citrix.com>
> CA-322708 - VM should not be allowed to start during dead storage migration

- ocaml/xapi/helpers.ml
- ocaml/xapi/xapi_ha.ml
- ocaml/xapi/xha_scripts.ml
We don't want to log the pool secret. So we add a new option to
`call_script` which ensures nothing is logged in either the success case
or the failure case.
> CP-34936 don't log result from pool_secret_wrapper

- ocaml/gencert/selfcert.ml
This aligns REQ-403 (certificate checking) with master. There should be no difference between the two because we merged the self-signing changes into master already.
> Update feature/REQ-403 branch

- ocaml/xapi/extauth_plugin_ADpbis.ml
If the lwsmd service has only just started when xapi checks to see
whether PBIS / AD is available, then removing the KRBTGT user from
the PBIS cache fails. This is not a problem, but we should try again
to remove KRBTGT from the cache rather than erroring out completely.
To remedy this, we move the call to `ad-cache --delete-user` inside
the retry loop. Additionally, the retry loop has been decoupled from the
checking
This was tested by running a thread which restarts lwsmd periodically,
and then restarting xapi:
```
$ restart_lwsmd () { while true; do systemctl restart lwsmd; sleep 3; done; }
$ restart_lwsmd &
$ systemctl restart xapi
```
Unfortunately this only catches the issue some of the time; after
restarting xapi potentially several times, you should see the following
in …
> CA-344268: Fix timing issue in PBIS available check

- ocaml/idl/datamodel_pool.ml
Certificate Revocation Lists are issued by a Certification Authority in
contrast to SSL certs. To reflect this, add "CA-issued" to the interface
documentation.
> CA-265116 clarify doc for CA Cert Revoc. Lists

- ocaml/idl/datamodel_errors.ml
- ocaml/tests/test_platformdata.ml
- ocaml/xapi-consts/api_errors.ml
- ocaml/xapi/vm_platform.ml
Creating a Windows 8.1 VM in XenCenter by allocating 1 vCPU and
topology 1 core-per-socket would lead to an incorrectly formatted
error (i.e. "Failed","Starting VM 'Windows 8.1 (64-bit) (1)'
The value 'VCPUs_max must be a multiple of this field' is invalid
for field 'platform:cores-per-socket'.","xrtuk-01-01","Dec 6, 2019 12:55 PM")
The incorrectly formatted error made it more difficult to understand the issue
causing it.
Signed-off-by: Gheorghe Burac <gheorghe.burac@citrix.com>
> CA-332605 - Fixed Bad error message for vcpu/cores-per-socket

- ocaml/xapi/xapi_ha.ml
Backport of 8bfbb830996d7978fbc59a87df2196202f144772
This changes how essential parameters for the HA daemon are derived from
the xe pool-ha-enable timeout parameter. So far, the network heartbeat
was always configured to use 10 heartbeats in an interval. There is good
reason to believe that this contributed to the unreliability of HA.  HA
uses two heartbeats:
(1) UDP network heartbeat - fast and unreliable
(2) State file heartbeat - slow and reliable
HA's network heartbeat is sensitive to network congestion and with only
10 heartbeats configured before a timeout would trigger HA, it was easy
for HA to trigger. This patch addresses the asymmetry of the heartbeats:
* We want more network heartbeats than storage heartbeats because they
are cheap but can be lost.
* We want a minimum time to …
> Improve HA parameter derived from timeout (Backport)

- ocaml/idl/datamodel_host.ml
- ocaml/idl/datamodel_pool.ml
- ocaml/xapi-cli-server/cli_frontend.ml
- ocaml/xapi-cli-server/cli_operations.ml
- ocaml/xapi/certificates.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_host.mli
- ocaml/xapi/xapi_pool.ml
- ocaml/xapi/xapi_pool.mli
Make it more obvious that pool and host functions are handling CA-issued certificates by renaming them while keeping the old name around but deprecated.
> CA-256116 rename pool and host functions that handle CA certs

- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_host_helpers.ml
Setting the initiator IQN after attempting to connect
to and iSCSI target using an older IQN causes the daemon
to not be updated with the new IQN.
The daemon needs to be restarted in order to update
the IQN value used.
Signed-off-by: Gheorghe Burac <gheorghe.burac@citrix.com>
> CA-333441 - restarting ISCSI daemon after setting initiator IQN

- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_host_helpers.ml
Reverts xapi-project/xen-api#4212
Revert this change temporarily, whilst we wait for https://github.com/xapi-project/sm/pull/516 to be included in a tag
> Revert "CA-333441 - restarting ISCSI daemon after setting initiator IQN"

- ocaml/tests/test_pool_update.ml
- ocaml/xapi/extauth_plugin_ADpbis.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_mgmt_iface.ml
- ocaml/xapi/xapi_pool_update.ml
- scripts/extensions/pool_update.precheck
- scripts/host-backup-restore/host-backup
In preparation for a hotfix on 8.2, we backport the necessary bugfixes (some have been backported already). We will also backport REQ-819, but we'll do that separately.
In particular, we already have a PR open for backporting CA-344268 (https://github.com/xapi-project/xen-api/pull/4215) - we'll close it and include the change here to reduce the number of PRs.
All the backports were cleanly applied.
> Stockholm bugfix backports

- ocaml/idl/datamodel.ml
- ocaml/idl/datamodel_certificate.ml
- ocaml/idl/datamodel_pool.ml
- ocaml/xapi/xapi_host.ml
These allow to model certificate chains and let xapi manage which
certificates are to be installed as pool-wide CA certificates, which are
to be installed in a single host, or both.
This change does not ensure that the fields are correctly filled and are up-to-date with the certificates in the filesystem.
To do that several codepaths will need to be modified: Pool CA certificate installation and uninstallation; host certificate reset, host certificate installation; and startup to syncronize CA certificates and server certificate.
> CP-34465: Add signing fields to certificate records

- ocaml/idl/datamodel_host.ml
- ocaml/xapi-cli-server/record_util.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_host.mli
Solves https://github.com/xapi-project/xen-api/issues/4154 & https://github.com/xcp-ng/xcp/issues/407
This PR adds 2 new methods to the `Host` object:
- `set_sched_gran`: sets Xen's scheduler granularity (either `core`, `cpu` or `socket`)
- `get_sched_gran`: gets Xen's scheduler granularity
It uses `/opt/xensource/libexec/xen-cmdline`
This allows a user to select the xen's scheduler granularity and choose between efficiency and safety. For instance core scheduling prevents cross domain side-channel attack while being more efficient than disabling hyperthreading.
> Expose xen's scheduler granularity into the `Host`

- ocaml/xapi/xapi_ha.ml
This changes how essential parameters for the HA daemon are derived from
the xe pool-ha-enable timeout parameter. So far, the network heartbeat
was always configured to use 10 heartbeats in an interval. There is good
reason to believe that this contributed to the unreliability of HA.  HA
uses two heartbeats:
(1) UDP network heartbeat - fast and unreliable
(2) State file heartbeat - slow and reliable
HA's network heartbeat is sensitive to network congestion and with only
10 heartbeats configured before a timeout would trigger HA, it was easy
for HA to trigger. This patch addresses the asymmetry of the heartbeats:
* We want more network heartbeats than storage heartbeats because they
are cheap but can be lost.
* We want a minimum time to pass between heartbeats - less for network
and more …
> Improve HA parameter derived from timeout (Backport to Stockholm)

- .ocamlformat
- ocaml/idl/datamodel_host.ml
- ocaml/xapi-cli-server/cli_frontend.ml
- ocaml/xapi-cli-server/cli_operations.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_host.mli
Deprecate Host.emergency_reset_server_certificate and add
Host.reset_server_certificate. The new method is synonym for the old one
but can be called by the pool admin.
> REQ-403 CP-34468 add Host.reset_server_certificate

- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_host_helpers.ml
With HA on or during a toolstack restart we do expect other iSCSI
sessions to be active, so this cannot be changed.
Log and ignore instead of blocking XAPI startup.
> CA-333441: Do not fail the startup sequence if the iSCSI initiator cannot be set

- ocaml/idl/datamodel_errors.ml
- ocaml/tests/suite_alcotest.ml
- ocaml/tests/test_session.ml
- ocaml/xapi-consts/api_errors.ml
- ocaml/xapi-consts/api_messages.ml
- ocaml/xapi/authx.ml
- ocaml/xapi/context.ml
- ocaml/xapi/context.mli
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_periodic_scheduler_init.ml
- ocaml/xapi/xapi_pool.ml
- ocaml/xapi/xapi_pool.mli
- ocaml/xapi/xapi_session.ml
- ocaml/xapi/xapi_session.mli
We store information about failed login attempts in memory. This information is made persistent every 60 minutes, by generating a report and storing it in an alert. Each time the report is made, we forget completely about previous failed attempts - in this way, reports only contain information about the last 60 minutes.
> CP-34472 login fail alerts

- ocaml/idl/datamodel_pool.ml
- ocaml/idl/dm_api.ml
- ocaml/tests/test_cluster.ml
- ocaml/tests/test_cluster_host.ml
- ocaml/tests/test_valid_ref_list.ml
- ocaml/xapi-cli-server/cli_frontend.ml
- ocaml/xapi-cli-server/cli_operations.ml
- ocaml/xapi/context.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_pool.ml
- ocaml/xapi/xapi_pool.mli
- ocaml/xapi/xapi_vgpu_type.ml
Add a wireframe to implement Pool.assert_can_enable_tls_verification as
an API call and make it available in the CLI.
This might require some re-formatting to avoid conflicts.
> CP-34462 add wireframe to implement Pool.assert_can_enable_tls_verification

- ocaml/xapi/console.ml
- scripts/Makefile
- scripts/wsproxy.service
- scripts/wsproxy.socket
Changes the name of the socket used from wsproxy to ws_proxy as systemd
does not have a capability to take over existing sockets. This would
have been a problem when upgrading as xapi does not clean up the socket
and cannot be controlled in all cases.
Must be merged along https://github.com/xapi-project/wsproxy/pull/23
> CP-32138: rely on systemd to have wsproxy available

- ocaml/xapi/helpers.ml
Previously we would use /usr/bin/pool_secret_wrapper to generate pool
secrets 'by default'. However this might take a very long time (hours)
if entropy low and little is being generated.
Change the default to use /dev/urandom instead to avoid this issue.
> CA-347543 use /usr/bin/pool_secret_wrapper only if CC

- .github/workflows/1.249-lcm.yml
- .github/workflows/main.yml
Since the dependencies barely change, I felt like a weekly run / cache
is more than enough for testing. It depends on the rest of the packages
being attached to a commit / tag in opam instead of following a branch.
This commit is indeed on master branch, this is due to a limitation in github actions, it's the same as the scheduled runs in xs-opam: https://github.com/xapi-project/xs-opam/blob/master/.github/workflows/stockholm-lcm.yml
> maintenance: Schedule weekly run for 1.249-lcm

- ocaml/tests/test_session.ml
- ocaml/xapi/context.ml
- ocaml/xapi/context.mli
- ocaml/xapi/xapi_session.ml
Now that we have access to client IP addresses in xapi, we can now
improve the auth failure alerts to give a finer grained view of who
failed to login.
> REQ-403 CP-34472 include IP address in login fail alerts

- ocaml/idl/datamodel_errors.ml
- ocaml/xapi-consts/api_errors.ml
- ocaml/xapi/xapi_vm.ml
Backport of 
* 41204933c 
* 1f09eb799
This adds a check on VM.suspend to prevent suspending of a VM with an NVidia vGPU when the drivers or configuration of the VM don't support it.
> Backport CP-35021 VM.suspend - assert support for NVidia cards

- .github/workflows/main.yml
This solves non-fatal error messages happening on the "Installing
dependencies step" when trying to synchronize pins which clutter the logs.
Example: https://github.com/xapi-project/xen-api/runs/1386255257?check_suite_focus=true#step:8:16
> ci: unpin packages on cleanup

- .github/workflows/main.yml
- ocaml/database/master_connection.ml
- ocaml/gencert/dune
- ocaml/gencert/gencert.ml
- ocaml/gencert/lib.ml
- ocaml/gencert/selfcert.ml
- ocaml/gencert/selfcert.mli
- ocaml/idl/datamodel_pool.ml
- ocaml/tests/common/test_common.ml
- ocaml/xapi-cli-server/cli_frontend.ml
- ocaml/xapi-cli-server/cli_operations.ml
- ocaml/xapi-consts/constants.ml
- ocaml/xapi/dbsync_master.ml
- ocaml/xapi/helpers.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_pool.ml
- ocaml/xapi/xapi_pool.mli
Here we implement a naive version of `Pool.enable_tls_verification` by setting the global flag in the stunnel library.
We also change the way that xapi generates self-signed slightly, by making the IP address the CN, and adding the IP as a SAN.
Sibling: https://github.com/xapi-project/xen-api-libs-transitional/pull/85
> Add Pool.enable_tls_verification to the API and include IP address in SANs of self-signed certs

- ocaml/xapi/dbsync_master.ml
In a HTTP URL, IPv6 addresses needs to be between `[]`.
Solves https://github.com/xapi-project/xen-api/issues/4264
> Fix IPv6 console location

- ocaml/tests/test_bios_strings.ml
- ocaml/xapi/bios_strings.ml
The code relied on previous behavior to only parse a prefix and not the
whole text. This means in practice that if a failure is found the parser
emits the list of successfully parsed records instead of failing.
Should be merged along https://github.com/xapi-project/xs-opam/pull/524
> CP-34942: update dmidecode parser for angstrom 0.14

- ocaml/xapi/xapi_vdi.ml
Performing a VDI copy on a VDI that has reset-on-boot enabled may lead
to the VDI to be wiped completely, rather than reset to a predefined
state, when a VM is started. Storage migrate is blocked for VMs that
have such VDIs, and VDI.copy should have the same constraint.
> CA-348700: Block VDI.copy if on-boot=reset

- ocaml/xapi/dbsync_master.ml
- ocaml/xapi/remote_requests.ml
- ocaml/xapi/workload_balancing.ml
This was used for establishing connections to WLB appliance. Now the
general tls verification setting is used instead.
The commit is mutually dependant with https://github.com/xapi-project/xs-opam/pull/527
> CP-35584: remove unused parameter for per-connection tls verification

- ocaml/idl/datamodel_common.ml
We added `is_psr_pending` field in a Stockholm
hotfix, so we should have bumped the schema version.
> REQ-819 stockholm schema version bump

- ocaml/idl/datamodel.ml
- ocaml/idl/datamodel_host.ml
- ocaml/xapi-cli-server/cli_frontend.ml
- ocaml/xapi-cli-server/cli_operations.ml
- ocaml/xapi-consts/api_messages.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_host.mli
- ocaml/xapi/xapi_periodic_scheduler_init.ml
An escape hatch is needed in case communication breaks down in a pool.
Importantly verification will only be disabled for the host on which you
make this emergency call. This introduces a discrepancy between the pool
database and the local database, which can be fixed by executing
Pool.enable_tls_verification once again.
> REQ-403 emergency disable tls verification

- ocaml/gencert/gencert.ml
- ocaml/gencert/selfcert.ml
- ocaml/gencert/selfcert.mli
- ocaml/xapi/certificates.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_pool.ml
Now the trust anchors that verify a server certificate in a pool are store in the server certificate's database record. This means that CA certificates must be also recorded in the database when installed.
CA certificates are not removed from the database when uninstalled yet. This is for another issue that tackles CA certificates exclusively.
For self-signed certificates, these are generated, installed normally as pool ca certificates with their UUID as names and then the database record is marked as host_and_pool and the host is added to the record, as well as the field verified_by.
> CP-35280: Install self-signed certificates as trust anchors, add more information to database about certificates

- ocaml/gencert/gencert.ml
- ocaml/gencert/lib.ml
- ocaml/gencert/lib.mli
- ocaml/xapi-aux/pool_role.ml
- ocaml/xapi-aux/pool_role.mli
- ocaml/xapi/helpers.ml
- ocaml/xapi/xapi.ml
- ocaml/xapi/xapi_ha.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_pool.ml
Slaves store an address to the master in pool.conf. Historically this
has been an IP address, however for REQ-403 we need to use an fqdn
instead.
> CP-34463: pool.conf should use FQDN

- ocaml/xapi/certificates_sync.ml
- ocaml/xapi/xapi.ml
- ocaml/xapi/xapi_host.mli
- ocaml/xapi/xapi_pool.ml
- ocaml/xapi/xapi_vdi.ml
If a host certificate is present in the file system at xapi start:
* verify and install it if none was present
* check if the information about it is still valid
* verify, update, and install it if it has changed
Installing a new self-signed certificate at startup in a pool is
dangerous unless the host is the only member of the pool. Check the pool
size to verify this.
If verification fails when a valid host certificate is required, enter
emergency mode because communication will be impossible with an invalid
host certificate.
> CP-35284 validate and install updated host certs at start

- ocaml/xapi-cli-server/cli_operations.ml
- ocaml/xapi-cli-server/records.ml
This makes recovering from XSA-354 easier.
A python script can also be used as a workaround (see commit message)
> CA-350253: improve vm-param-clear, avoid O(N^2) behaviour

- ocaml/idl/datamodel_pool.ml
- ocaml/xapi/dbsync_master.ml
- ocaml/xapi/remote_requests.ml
- ocaml/xapi/workload_balancing.ml
- ocaml/xapi/xapi_vdi.ml
We need to thread the `wlb_verify_cert` flag to the stunnel client library, so that even if Pool.tls_verification_enabled is not set, wlb verification still works as expected
Needs to go in simultaneously with https://github.com/xapi-project/xen-api-libs-transitional/pull/89 - expect CI here to fail
> REQ-403 deprecate Pool.wlb_verify_cert flag, but ensure it still works

- ocaml/xapi/helpers.ml
Adds ipv6 addresses to the result of this_is_my_address.
The fix is a completion of https://github.com/xapi-project/xen-api/pull/4260
> Add ipv6 addresses to this_is_my_address

- ocaml/quicktest/quicktest.ml
- ocaml/quicktest/quicktest_date.ml
Here we add integration tests for API methods which were broken by changes made to the stdext date library
Requires https://github.com/xapi-project/stdext/pull/58
> CP-34602: test get_server_localtime and message.get_since

- ocaml/xapi/dbsync_master.ml
I missed some places where consoles' location were computed.
> Continue fixing console location in IPv6

- ocaml/idl/ocaml_backend/gen_rbac.ml
- ocaml/xapi-cli-server/cli_operations.ml
- ocaml/xapi/cancel_tasks.ml
- ocaml/xapi/dbsync_slave.ml
- ocaml/xapi/session_check.ml
- ocaml/xapi/xapi_pif.ml
- ocaml/xapi/xapi_services.ml
- ocaml/xapi/xapi_vm_clone.ml
This removes all the deprecation warnings.
> CP-34643: Replace deprecated usages of pervasiveext

- ocaml/xapi/api_server.ml
- ocaml/xapi/certificates_sync.ml
- ocaml/xapi/xapi.ml
- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_ha.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_mgmt_iface.ml
- ocaml/xapi/xapi_mgmt_iface.mli
Rework of https://github.com/xapi-project/xen-api/pull/4286
Fixes:
- first boot failure where host is put into maintenance mode
- install failure where CA cert files didn't have a .pem extension
> REQ-403 fix first boot failure

- ocaml/gencert/pem.ml
- ocaml/gencert/pem.mli
- ocaml/xapi/certs.ml
- ocaml/xapi/certs.mli
- ocaml/xapi/xapi_host.ml
This introduces module Certs which provides an interface between the
on-disk representation of certificates and their internal, more detailed
structure. This shall help to maintain the consistency between the two
as we want to make it the only interface for all of Xapi to use.
> CP-35599 add new interface for certs

- ocaml/alerts/certificate/certificate_check.ml
- ocaml/gencert/lib.ml
- ocaml/xapi-cli-server/records.ml
- ocaml/xapi/dbsync_master.ml
- ocaml/xapi/helpers.ml
- ocaml/xapi/xapi_message.ml
- ocaml/xapi/xapi_vdi.ml
The lastest change prevented creating new alerts created when there were
no other certificate alerts present.
Having no alerts now doesn't dismiss any existing alerts, as stated by the
comment.
> CA-343646: generate certificate alerts

- ocaml/xapi-types/features.ml
- ocaml/xapi-types/features.mli
TLS Certificate checking requires clients to change their behavior when
doing certain operations (like pool joins). This flag is meant to aid
them to detect which behaviour to use
> CP-35761: Add feature flag for TLS certificate checking

- ocaml/gencert/lib.ml
When the X509 library refuses to parse a file the API sometimes
doesn't return the reson, log the reason in those cases so it can be
visible elsewhere.
Cherry-pick of cfd95d2213a1ff76c57530607d5feb5eebabc849
> Backport of CP-35210: log why a private key or certificates failed to validate

- ocaml/xapi-aux/pool_role.ml
- ocaml/xapi-aux/pool_role.mli
- ocaml/xapi/helpers.ml
- ocaml/xapi/system_domains.ml
- ocaml/xapi/xapi.ml
- ocaml/xapi/xapi_pool_transition.ml
This fixes an issue where the pool role's master address was out of sync between the pool.conf file and the pool role ref
> REQ-403 pool conf fixes

- .github/workflows/format.yml
This can probably sped up with opam bin.
But it's not obvious how to generate and store the ocamlformat binary for it; configuration of opam-bin within github actions doesn't seem trivial either.
> ci: check whether code in PRs is formatted

- ocaml/idl/datamodel.ml
- ocaml/idl/datamodel_errors.ml
- ocaml/idl/datamodel_pool.ml
- ocaml/xapi-cli-server/cli_frontend.ml
- ocaml/xapi-cli-server/cli_operations.ml
- ocaml/xapi-cli-server/record_util.ml
- ocaml/xapi-consts/api_errors.ml
- ocaml/xapi-consts/constants.ml
- ocaml/xapi/helpers.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/repository.ml
- ocaml/xapi/repository.mli
- ocaml/xapi/xapi.ml
- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_host.mli
- ocaml/xapi/xapi_pool.ml
- ocaml/xapi/xapi_pool.mli
- ocaml/xapi/xapi_pool_helpers.ml
This commit implements 'pool.sync_updates' API for repository function.
The handler of this API will:
1. sync/download latest updates and metadata from remote repository;
2. create local repository on the master host in the pool;
3. check if there are available updates on each host in the pool.
> CP-35372: Repository: pool.sync_updates

- ocaml/xapi-consts/constants.ml
- ocaml/xapi/import_xva.ml
- ocaml/xapi/xapi_xenops.ml
HVM VMs need a boot order in order for qemu to successfully start them.
This check ensures early and obvious failure when the boot order is not
present, whereas previously VM.start would silently fail.
> XSI-804 ensure HVM boot params consistent

- ocaml/idl/datamodel.ml
- ocaml/idl/datamodel_errors.ml
- ocaml/idl/datamodel_pool.ml
- ocaml/xapi-cli-server/record_util.ml
- ocaml/xapi-consts/api_errors.ml
- ocaml/xapi-consts/constants.ml
- ocaml/xapi/repository.ml
- ocaml/xapi/repository.mli
- ocaml/xapi/xapi.ml
- ocaml/xapi/xapi_pool.ml
- ocaml/xapi/xapi_pool.mli
- ocaml/xapi/xapi_pool_helpers.ml
This commit implements HTTPs endpoint "/updates" for repository function.
With this HTTPs endpoint, user can get the available updates from hosts in the
pool.
> CP-35372: Repository: HTTPs endpoint "/updates"

- ocaml/alerts/certificate/certificate_check.ml
Currently it's assumed by the alert generator that all certificates have
a valid reference to a host. This is not true anymore as we model CA
certificates.
Ignore the error when the assumption does not hold for the time being
> CA-351391: Make certificate alerts ignore CA certs

- ocaml/alerts/certificate/certificate_check.ml
Previously the certificate alerts were replaced every time the script
generating them was run. Now the script only replaces them when the new
alert is different.
Backports https://github.com/xapi-project/xen-api/pull/4285 and https://github.com/xapi-project/xen-api/pull/4179
> CA-342551,  CA-343646: backport to avoid replacing certificate alerts

- ocaml/xapi/helpers.ml
- ocaml/xapi/repository.ml
- ocaml/xapi/xapi_pool_transition.ml
Two commits for fixing-up:
Fixup: Repository: Check existence before removing repo dir
This commit adds an existence checking before removing the local pool repository
directory. This fixes bug in cases of inital pool.set_repository and changing
pool master.
Fixup: Repository: Cleanup local pool repo when becoming a new slave
This commit adds cleanup when a host becoming a new slave.
> Two commits for fixing-up of repository funciton

- ocaml/idl/dune
- ocaml/idl/schematest.ml
Implementation of @edwintorok 's suggestion to use hashing to detect datamodel changes: https://github.com/xapi-project/xen-api/pull/4274#pullrequestreview-543739076
> maintenance: detect schema updates which are missing version bumps

- ocaml/idl/ocaml_backend/gen_server.ml
- ocaml/xapi/rbac.ml
- ocaml/xapi/rbac_audit.ml
- ocaml/xapi/xapi_http.ml
The rbac checks around call arguments spends a lot of effort checking that two lists are always the same length. Since we control the source, we can generate a list of pairs instead. Other list traversals were avoided as well.
Special case for parsing VMPP arguments when log-auditing was removed as the code was not trivial, introduced IO and the VMPP calls were deprecated in 6.0 so the code has been unused since then.
BST + BVT 144004 is mostly green, except for a problem with RPU, xenserver-inventory is not updated after upgrading.
I couldn't find any tests for RBAC, but I would think this code would be excercised a lot in e2e tests anyway.
> CA-342527: simplify code around rbac checks

- ocaml/xapi-cli-server/record_util.ml
- ocaml/xapi-cli-server/records.ml
Also does some clean-ups and minor fixes:
- generate an empty list when setting ipvx_allowed is empty, the code actually depends on it being an empty list for some cases
- be consistent when showing lists of references, some of them weren't separated by spaces
> CP-35941: show newly added fields of records through xe 

- .github/workflows/main.yml
- Makefile
- ocaml/gencert/lib.ml
We've decided that usage of this function is widespread and can lead to
uncaught exceptions.
The recommendation is to match the list or use List.nth_opt list 0
> ci: count usages of List.hd

- ocaml/xapi/helpers.ml
Add SNI "pool" to the stunnel server configuration. This will be used by
clients to request a specific certificate. For now, this is simply
the self-signed certificate used by xapi.
This is safe to merge into xapi. Currently no client it using the SNI. A client needs
access to the public cert of the server before it makes sense to use this feature
and currently the mechanism to distribute these certificates is not yet in place.
> CP-36094 add SNI to stunnel server config

- ocaml/idl/ocaml_backend/gen_server.ml
- ocaml/xapi/rbac.ml
- ocaml/xapi/rbac_audit.ml
- ocaml/xapi/xapi_http.ml
This reverts commit 517562e412a1e0984e32e1f8da2178745d48e2b3.
The change caused internal errors when a list of names could not be
generated that match the number of parameters in calls with defaults,
such as migrate_receive.
> Revert "CA-342527: Avoid traversing lists when possible"

- ocaml/idl/datamodel_errors.ml
- ocaml/tests/suite_alcotest.ml
- ocaml/tests/test_session.ml
- ocaml/xapi-consts/api_errors.ml
- ocaml/xapi-consts/api_messages.ml
- ocaml/xapi/authx.ml
- ocaml/xapi/context.ml
- ocaml/xapi/context.mli
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_periodic_scheduler_init.ml
- ocaml/xapi/xapi_pool.ml
- ocaml/xapi/xapi_pool.mli
- ocaml/xapi/xapi_session.ml
- ocaml/xapi/xapi_session.mli
This is a port to master from the REQ-403 branch.
These are cherry-picks from https://github.com/xapi-project/xen-api/pull/4218, https://github.com/xapi-project/xen-api/pull/4249 and [`1e2cafc` (#4284)](https://github.com/xapi-project/xen-api/pull/4284/commits/1e2cafcb385aaa0406a7ad474c28f45372b65fcb)
I didn't mark them as cherry-picks because these are from an unmerged feature branch.
The first two commits had conflicts because the function to expose the client was already added to master.
> CP-34472 Generate alerts every hour about failed login attempts

- scripts/certificate-check
This may trigger users being sent mails with the output, which is
confusing when no errors happened.
> CA-352111: Do not output on cronjobs unless there's an error

- ocaml/xapi-cli-server/records.ml
Now most lists are separated by "; ", using the same code. (this needs a note in the changelog as it's breaking behaviour)
Also generate an empty list when setting ipvx_allowed if the list is empty, there's code that actually depends on it being an empty list in some cases.
> xapi-cli-server: Use semicolons for lists

- ocaml/gencert/dune
- ocaml/gencert/gencert.ml
- ocaml/gencert/selfcert.ml
- ocaml/gencert/selfcert.mli
- ocaml/xapi/helpers.ml
- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_host.ml
- scripts/gencert.service
Now two certificates are generated at startup: the additional
certificate will be used for host-to-host communications and contains
the host UUID as the issuer and subject's Common Name. Its validity
period and key type are the same as the other certificate: 3650 days and
RSA 2048 bits, respectively.
Drops gencert's dependency on mirage_crypto_rng as it doesn't generate
the private keys itself anymore.
> CP-36096: Generate two certificates at startup

- ocaml/gencert/dune
- ocaml/gencert/selfcert.ml
The Mirage crypto modules use a random number generator and it needs to
be initialised. We do this with a side effect during startup: the code
is initialised as the part of the Selfcert module when it initialises
its global values.
> Initialise Mirage RNG on startup

- ocaml/idl/datamodel.ml
- ocaml/idl/datamodel_errors.ml
- ocaml/idl/datamodel_pool.ml
- ocaml/idl/datamodel_repository.ml
- ocaml/idl/schematest.ml
- ocaml/tests/common/test_common.ml
- ocaml/tests/test_repository.ml
- ocaml/tests/test_repository_helpers.ml
- ocaml/xapi-cli-server/cli_frontend.ml
- ocaml/xapi-cli-server/cli_operations.ml
- ocaml/xapi-cli-server/record_util.ml
- ocaml/xapi-cli-server/records.ml
- ocaml/xapi-consts/api_errors.ml
- ocaml/xapi/dbsync_master.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/repository.ml
- ocaml/xapi/repository.mli
- ocaml/xapi/repository_helpers.ml
- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_pool.ml
- ocaml/xapi/xapi_pool.mli
- ocaml/xapi/xapi_pool_helpers.ml
- ocaml/xapi/xapi_pool_transition.ml
This series update repository functions to support multiple repositories being enabled at same time. But in these enabled repositories, there should be one and only one update repository.
If a repository is an update repository, XAPI will expect that it has updateinfo.xml and will parse it to get update metadata. A new bool field "update" is added into repository datamodel. If it is true, this repository is an update repository.
> Support to enable multiple repositories

- ocaml/idl/dune
- ocaml/tests/dune
- ocaml/tests/test_xapi_db_upgrade.ml
- ocaml/xapi/xapi_db_upgrade.ml
Seems like the opam sandbox also made the tests break while using the container-based workflow for xs-opam. This change fixes them, as it happened with master.
The datamodel tests were also using the private name instead of the public one which broke them.
This change can be tested by creating an opam switch with the 8.2 packages and installing xapi while forcing opam to run its tests:
```
$ opam switch create stockholm 4.08.1
$ eval $(opam env --switch="stockholm" --set-switch)
$ opam repo add xs-opam-stockholm git+https://github.com/xapi-project/xs-opam.git#release/stockholm/lcm
$ opam repo remove default
$ opam pin add xapi . -t
```
> maintenance: allow tests to run in an opam sandbox

- ocaml/gencert/selfcert.ml
- scripts/update-ca-bundle.sh
update-ca-bundle.sh takes indvidicual certificates and bundles them into
a single *.pem for Stunnel to use. Extend this to handle
certificates both in
* /etc/stunnel/certs
* /etc/stunnel/certs-pool
Typically only certifcates in one of the two directories would be
updated and hence need to be re-bundled. However, the operation is so
cheap that the complexity of doing this selectively is not worth it. We
could pass an argument to this script to let it do work more
selectively.
This fixes also a bug: the directory find(1) operates on needs to exist.
The mkdir(1) call ensures it does.
> CP-36100 extend update-ca-bundle to handle pool certs

- ocaml/gencert/gencert.ml
- ocaml/gencert/lib.ml
- ocaml/gencert/selfcert.ml
- ocaml/gencert/selfcert.mli
- ocaml/idl/datamodel_certificate.ml
- ocaml/idl/datamodel_common.ml
- ocaml/idl/datamodel_host.ml
- ocaml/idl/schematest.ml
- ocaml/xapi-cli-server/cli_operations.ml
- ocaml/xapi-cli-server/record_util.ml
- ocaml/xapi-cli-server/records.ml
- ocaml/xapi/certificates.ml
- ocaml/xapi/dune
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_host.mli
- ocaml/xapi/xapi_pool.ml
This PR adds some new fields to certs in the database. We also make sure that certs are added to the database when they are changed via the API (this means `Host.reset_server_certificate`, `Host.install_server_certificate` and `Pool.install_ca_certificate`)
> CP-36099 REQ-403 modelling CA certs in the database

- .github/workflows/main.yml
- Makefile
- ocaml/database/master_connection.ml
- ocaml/perftest/perfutil.ml
- ocaml/quicktest/qt.ml
- ocaml/quicktest/quicktest_args.ml
- ocaml/vncproxy/vncproxy.ml
- ocaml/xapi-cli-server/cli_operations.ml
- ocaml/xapi-cli-server/xapi_cli.ml
- ocaml/xapi/api_server.ml
- ocaml/xapi/config_file_sync.ml
- ocaml/xapi/helpers.ml
- ocaml/xapi/importexport.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/pool_db_backup.ml
- ocaml/xapi/remote_requests.ml
- ocaml/xapi/vpx.ml
- ocaml/xapi/workload_balancing.ml
- ocaml/xapi/xapi.ml
- ocaml/xapi/xapi_blob.ml
- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_http.ml
- ocaml/xapi/xapi_message.ml
- ocaml/xapi/xapi_pool.ml
- ocaml/xapi/xapi_pool_update.ml
- ocaml/xe-cli/newcli.ml
- ocaml/xsh/xsh.ml
When Stunnel creates a conncetion as a client it can verify this
connection using certificates. We have intra pool connections and
connections opened to appliances, which use different verification
methods. This needs to be reflected beyond yes/no. This patch makes
(more) explicit the configuration to use for verifcation.
Some call sites still use no certificate checking (passing None to
SSL.make) and this will need to be adressed.
> CP-36100-2 Use explicit config for TLS Stunnel verification

- ocaml/xapi-aux/pool_role.ml
- ocaml/xapi-aux/pool_role.mli
- ocaml/xapi/rrdd_proxy.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_periodic_scheduler_init.ml
- ocaml/xapi/xapi_vm.ml
- ocaml/xapi/xapi_vm_lifecycle.ml
This change makes it easy to see that backup_rrds and archive_rrds are
exclusively used with the pool's members ip addresses or None.
This allows the code in xcp-rrdd to assume these calls to trust the pool's internal certificates when establishing connections.
> CP-36100: format code around rrdd commands

- ocaml/xapi/certificates_sync.ml
- ocaml/xapi/certificates_sync.mli
- ocaml/xapi/xapi.ml
The host certificate /etc/xensource/xapi-ssl.pem has a corresponding
entry in the xapi database. At startup we check for changes and update
the database entry if the certificate has changed.
The update of the database entry is not yet implemented because the
corresponding code does not yet exist.
> CP-36509 update db for xapi_ssl.pem on startup if changed

- scripts/reset-and-reboot
A host that leaves a pool goes trough a reboot. At boot, it will create
new host certificates if none are present. To trigger this, remove the
existing ones (private and public keys). This includes removing
(public) certificates of other hosts that were part of the pool.
We only remove certs for pool-internal communication. The user may have
updated the host certficate and installed additional CA certificates. We
keep these as this was the behaviour in CH 8.2.
> CP-34469 on pool eject, remove host certificates

- ocaml/idl/datamodel_host.ml
- ocaml/xapi/cert_distrib.ml
- ocaml/xapi/cert_distrib.mli
- ocaml/xapi/dune
- ocaml/xapi/helpers.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_host.mli
- scripts/update-ca-bundle.sh
You can now execute `xe pool-enable-tls-verification` and it 'just works' (without having to manually set up the bundles)
It works as expected in the usual case, where no hosts go offline, nothing bad happens, etc. It has not been tested in failure cases.
From a high level, `cert_distrib.go` is supposed to distribute certs
between hosts. More specifically, it does the following:
- aggregates a collection of host certs on the master
- instructs hosts to save this collection
- instructs hosts to regenerate their bundles, using said collection
> CP-36510 REQ-403 distribute certs during Pool.enable_tls_verification

- ocaml/xapi-cli-server/cli_operations.ml
The expiry period is important enough to show it when listing certificates.
> REQ-403: Display expiry for certificates on the cli

- ocaml/xapi/xapi.ml
Otherwise the synchronization fails on first boot and puts the host on
maintenance mode.
> CA-341715: Sync certificates after bringing up mgmnt IF

- ocaml/xapi/certificates_sync.ml
- ocaml/xapi/xapi.ml
- ocaml/xapi/xapi_mgmt_iface.ml
CP-36690 at startup, sync host certs with DB
Each host has two server certificates that identifies it, one for
internal and external communication each and both are tracked in the
Xapi database. At Xapi startup, the database entries for them need to be
kept in sync with the certificates in the file system. This was done so
far for only one of them (xapi-ssl.pem) but needs to be done for both.
This commit generalizes the code to do that.
> CP-36690 at startup, sync host certs with DB

- Makefile
- ocaml/xapi-consts/api_errors.ml
- ocaml/xapi/xapi_pool.ml
Aside from checking that the TLS verification matches in both the joiner and the joined pool, I've removed from the xapi_pool all the list.hd when retrieving the reference of the remote pool and return a better error other than "Not_found".
> CP-34467: Pre-join checks for TLS verification

- ocaml/idl/datamodel_common.ml
- ocaml/idl/datamodel_pool.ml
- ocaml/idl/schematest.ml
- ocaml/xapi-cli-server/record_util.ml
- ocaml/xapi-consts/api_errors.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_pool_helpers.ml
It must not be run concurrently with other pool operations as it might
disrupt the certificate distribution. It must not be run when HA is
enabled as it might fence hosts and change the master while the
operation is in progress.
Confirm it works when HA is enabled:
```
true
The operation could not be performed because HA is enabled on the Pool
```
> CP-36750: Block enabling TLS verification on pool ops

- ocaml/xapi/certificates.ml
It would be nice to make these kind of expressions typed.
Example of fixed code running:
```
[root@xxx ~]# xe pool-certificate-install filename=/etc/xensource/xapi-ssl.pem
[root@xxx ~]# xe certificate-list type=ca
uuid ( RO)           : 69cdbef6-8c2b-2fcc-4a50-d554d2507b75
type ( RO): ca
name ( RO): xapi-ssl.pem
host ( RO): <not in database>
not-before ( RO): 20210423T11:32:48Z
not-after ( RO): 20310421T11:32:48Z
fingerprint ( RO): 8D:C1:29:D4:A8:86:43:B4:15:AF:4B:F7:6E:69:7D:A7:A9:49:E0:9D:E3:8C:0E:51:DC:BF:F0:0C:F2:DD:5A:9D
[root@xxx ~]# xe pool-certificate-uninstall name=xapi-ssl.pem
[root@xxx ~]# xe certificate-list type=ca
[root@xxx ~]# logout
Connection to xxx closed.
```
> CA-353309: Create correct filters for uninstalling ca certs

- ocaml/xapi/xapi_xenops.ml
Set currently_attached to true before calling {VIF;VBD}.add, so that any
following metadata push would not rip out the new device's metadata again.
Not a great design, but it follows what `start` does. We have plans
to improve this more generally.
> CA-349123: Fix metadata race in VBD/VIF plug

- ocaml/idl/datamodel_host.ml
- ocaml/xapi-cli-server/cli_frontend.ml
- ocaml/xapi-cli-server/cli_operations.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/vm_evacuation.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_host.mli
- ocaml/xapi/xapi_network_attach_helpers.ml
- ocaml/xapi/xapi_network_attach_helpers.mli
- ocaml/xapi/xapi_pif_helpers.ml
- ocaml/xapi/xapi_vm_migrate.ml
- Add `network` key in `options` expecting a network ref to try to migrate on
- If not possible, fallback on management address
> Enable to choose a migration network in `VM.pool_migrate` and `Host.evacuate`:

- ocaml/xapi/xapi_xenops.ml
Set currently_attached to true before calling {VIF;VBD}.add, so that any
following metadata push would not rip out the new device's metadata again.
Not a great design, but it follows what `start` does. We have plans
to improve this more generally.
(cherry picked from commit 4d7ff096738c48e94d88772b6f1565f3a602b204)
> backport! CA-349123: Fix metadata race in VBD/VIF plug

- ocaml/xapi/helpers.ml
stunnel logs fill up disk partition
This commit set the default debug level to 5 and controlled by
debug_stunnel environment variable
> CA-353388: Control debug level by debug_stunnel env variable

- ocaml/xapi/certificates_sync.ml
- ocaml/xapi/certificates_sync.mli
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_pool.ml
When a host leaves a pool, the remaining hosts in the pool must no
longer trust it. This is implemented by removing the leaving host's
certificates from the database and file system.
> CP-36658 remove certs of ejected host

- ocaml/idl/datamodel.ml
- ocaml/idl/datamodel_host.ml
- ocaml/xapi-cli-server/cli_frontend.ml
- ocaml/xapi-cli-server/cli_operations.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_host.mli
This is only allowed in emergency mode, like the call for disabling it
> CP-36744: Allow users to reenable tls cert checking

- ocaml/xapi/xapi_xenops.ml
This is an improvement on 4d7ff096. We should set `currently_attached` a
little earlier, before the `Events_from_xapi.wait` call. The latter
triggers a metadata update, which should already take the new device into
account.
> CA-349123: Tweak previous hotplug fix

- ocaml/idl/datamodel_errors.ml
- ocaml/xapi-consts/api_errors.ml
- ocaml/xapi/xapi_pgpu.ml
Xapi sets up GPU types based on an XML configuration that tells it
whether a card is SR-IOV capable. When we actually use the card and
enable virtual functions and find the card is not correctly configured
for SR-IOV, we raised so far an internal error. This patch adds a new
API error to report the case more clearly.
> CA-353553 add API error for when NVidia GPU is misconfigured

- ocaml/idl/datamodel_pool.ml
- ocaml/xapi/cert_distrib.ml
- ocaml/xapi/cert_distrib.mli
- ocaml/xapi/certificates.ml
- ocaml/xapi/helpers.ml
- ocaml/xapi/xapi_pool.ml
- ocaml/xapi/xapi_pool.mli
- quality-gate.sh
After passing the pre-join checks the joiner and the pool exchange
certificates and place them in the filesystem, ready to be used. The
database is not modified for any of the two sides. When rebooting xapi's
startup code in the joining host will detect its internal certificate is
not in the database and will add it.
Current code does not try to merge the trusted certificates that exist
in the joining host and the pool.
I've tested it manually successfully, I'll try to throw automated testing to make sure it's robust
> CP-34467: Exchange certificate when a hosts joins a pool

- ocaml/idl/datamodel_errors.ml
- ocaml/xapi-consts/api_errors.ml
- ocaml/xapi/repository.ml
- ocaml/xapi/repository.mli
- ocaml/xapi/xapi_pool.ml
This commit aims to improve the HTTP endpoint `/updates`.
Prior to this commit, HTTP endpoint `/updates` handler will always get
the available updates from all hosts in the pool. This will take quite
long duration.
With this commit, the result of available updates will be stored in a
cache in memory which is established in `pool.sync_updates`. With this
cache, HTTP endpoint `/updates` will return the result from cache
immediately.
Meanwhile, there are a few changes for management of the cache as well.
> CP-36579: Add cache in memory for available updates

- ocaml/xapi/fileserver.ml
- ocaml/xapi/xapi_globs.ml
By default, only HTTPS is allowed, as a small step to improve security.
This only affects the web content on the GET / handler (for the time
being).  There is a config file option to re-enable HTTP access if
required.
> CP-35523: Block access to the website on port 80

- xapi.opam
This allows to especialize the detection in a single package
This change has been present in xs-opam for some months
> maintenance: use conf-pam instead of depexts

- ocaml/alerts/certificate/certificate_check.ml
- ocaml/tests/alerts/test_alert_certificate_check.ml
- ocaml/xapi-consts/api_messages.ml
Extend the alert mechansim for pool-internal and CA certificates.
> CP-35348 cover alerts for internal and CA certificates

- scripts/xe-enable-ipv6
Would solve: https://github.com/xapi-project/xen-api/issues/4256
This question remains: https://github.com/xapi-project/xen-api/issues/4256#issuecomment-727892082
> xe-enable-ipv6 edits net.ipv6.conf.{ all | default }.disable_ipv6

- ocaml/xapi-cli-server/cli_operations.ml
Replace Listext.assoc with List.assoc; this silences a deprecation
warning.
> Maintenance: replace deprecated Listext.assoc

- ocaml/idl/datamodel_errors.ml
- ocaml/idl/datamodel_pool.ml
- ocaml/xapi-consts/api_errors.ml
- ocaml/xapi/cert_distrib.ml
- ocaml/xapi/cert_distrib.mli
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_pool.ml
- ocaml/xapi/xapi_pool.mli
The cert_distrib module can now be used to gather more than one type of certificate. This is used in the pool join to retrieve the 'CA' certificates from a pool and install them in the joining host.
The joining host calculates which certificates it's missing and which certificates the pool is missing and distributes only those. Additionally it detect if there are certificates with conflicting names before doing this and stops the join in this case.
> CP-36866: Distribute trusted appliance certificates on join

- ocaml/xapi/xapi_pool_helpers.ml
- quality-gate.sh
Print the first exception raised, not the last one, this is done by
replacing the fold_left with the filter_map to store exception in the
same order as they're raised.
Avoid using List.length and List.hd.
Avoid repeating numbers in quality_gate, do not count ml files in the test directory
> xapi_pool_helpers: refactor call_fn_on_hosts; exclude tests from interface quality gate

- ocaml/xapi/extauth.ml
extauth_ad_backend is configurable and can be one of following
* pbis, older ad backend needs to be replaced
* winbind, samba solution to manage linux box with domain
> CP-36090: Xapi tell plugin extauth_ad_backend type

- ocaml/idl/datamodel_common.ml
- ocaml/idl/datamodel_errors.ml
- ocaml/idl/datamodel_host.ml
- ocaml/idl/datamodel_vm.ml
- ocaml/idl/schematest.ml
- ocaml/tests/common/test_common.ml
- ocaml/tests/test_repository_helpers.ml
- ocaml/xapi-cli-server/record_util.ml
- ocaml/xapi-cli-server/records.ml
- ocaml/xapi-consts/api_errors.ml
- ocaml/xapi/create_misc.ml
- ocaml/xapi/repository.ml
- ocaml/xapi/repository_helpers.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_host_helpers.ml
- ocaml/xapi/xapi_vm.ml
- ocaml/xapi/xapi_vm_clone.ml
- ocaml/xapi/xapi_xenops.ml
There are two kinds of update guidances designed:
1. Recommended guidances: basically these guidances will be applied by
XAPI automatically after host being updated;
2. Absolute guidances: these guidances requires user to apply manually.
Both kinds of guidances look like: RebootHost, RestartToolstack, and
RestartDeviceModel.
This commit introduces function to add absolute guidances into
host.pending_guidances or VM.pending_guidances. In this way, users can
get to know the pending guidances need to be done by them manually.
> CP-35955: Add absolute guidances in pending_guidances

- ocaml/sdk-gen/csharp/gen_csharp_binding.ml
- ocaml/sdk-gen/csharp/templates/ApiVersion.mustache
- Renamed parameter because it hid field name.
- Method overloads should be adjacent (or static analysis tools will complain).
- Removed internal method rendered obsolete since the advent of Linq.
- Replaced comments on API_Version enum members with xml documentation.
> C# SDK: Fixes to generated code:

- ocaml/tests/test_repository_helpers.ml
- ocaml/xapi/repository_helpers.ml
This commit changes the <recommended_guidances> and <absolute_guidances>
to <recommended_guidance> and <absolute_guidance> correspondingly.
For any one kind of guidance (recommended or absolute), there is only
one guidacne in one update in updateinfo.xml.
> CA-355039: Support single guidance from one update in updateinfo.xml

- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_fist.ml
- ocaml/xapi/xapi_pool.ml
- scripts/update-ca-bundle.sh
Before enabling certificate checking, check that all hosts can
communicate when using it. This is implemented in a ping call that uses
certificate checking before it is enabled by default. A host pings all
pool members and all hosts do this based on code in message_forwarding.
> CP-37014 verify TLS-based RPC before enabling it

- ocaml/xapi/certificates.ml
To track adding and removal of CA certificates, log the uuid and ref
under which it is added to the database.
> CA-354834 log ref, uuid when adding CA cert

- ocaml/tests/test_repository_helpers.ml
- ocaml/xapi/repository.ml
- ocaml/xapi/repository_helpers.ml
CA-355179: Support epoch in RPM
This commit adds logic to support epoch in RPM packages.
From https://rpm-packaging-guide.github.io/,  "the Epoch version would
win out over the traditional Name-Version-Release marker that signifies
versioning for RPM Packages."
CA-355180: Improve parsing output of 'yum list updates'
This commit improves the logic of parsing output of "yum list updates".
Usually each line of the output would look like:
"qemu-dp.x86_64                             2:2.12.0-2.0.11.xs8 local"
But for some reason, it could be:
"qemu-dp.x86_64
2:2.12.0-2.0.11.xs8 local".
This means one line can be separated by newline as well. This commit
aims to handle these cases.
> CA-355179: Support epoch in RPM;CA-355180: Improve parsing output of 'yum list updates'

- Makefile
- ocaml/idl/datamodel_types.ml
- ocaml/idl/json_backend/gen_json.ml
- ocaml/idl/schematest.ml
Restructured output so it's easier to drop it into xapi-project.github.io.
Added missing release date (or the release is not generated by gen-json.exe).
> Build the doc-json target as part of the install target. Also:

- ocaml/sdk-gen/c/gen_c_binding.ml
- ocaml/sdk-gen/csharp/gen_csharp_binding.ml
- ocaml/sdk-gen/powershell/common_functions.ml
Commit 63cbb1d8 introduced a function in the datamodel that has a
return type `Set (Set String)`, which is a valid datamodel type, but
it is not yet recognised by the API bindings (SDK).
This patch just adds match cases to the code generators, such that
`make sdk` does not fail. This will need a follow-up patch to correctly
handle unmarshalling for the type.
> Fix SDK build

- .github/workflows/main.yml
- .gitignore
The xml file is fetched straight from the SM master branch and it's placed where the makefile expects it
> ci: build the sdk when running the CI

- ocaml/tests/test_data/repository_pkg_of_fullname_all
- ocaml/tests/test_extauth_plugin_ADwinbind.ml
- ocaml/xapi/extauth.ml
- ocaml/xapi/extauth_plugin_ADwinbind.ml
- ocaml/xapi/xapi.ml
- ocaml/xapi/xapi_host.ml
- quality-gate.sh
PBIS just disable machine account during domain leave
This commit let winbind keep this behavior for backward compatibility
instead of delete the machine account
> CP-37241: Disable machine account on domain leave

- ocaml/tests/test_repository_helpers.ml
- ocaml/xapi/repository.ml
- ocaml/xapi/repository_helpers.ml
CA-355571: Include accumulative updates for updates description and guidances
When applying updates on a host, there are 2 parts would be considered:
1. Latest updates, which include binary RPM packages to be installed.
The 'yum list updates' will get these RPM packages;
2. Accumulative updates. Some of these updates may be overrided by the
latest updates. These can be get from 'yum updateinfo list updates'.
E.g. pkg-a-1.0.0-r1.x86_64 has been installed on a host. There is an
update pkg-a-1.0.1-r1.x86_64 which is included in update-1. But this
update-1 has not been applied by user. Now there is another update-2
with pkg-a-1.0.2-r1.x86_64. In this case, the latest update is update-2
(pkg-a-1.0.2-r1.x86_64), the accumulative updates are update-1 and
update-2.
With this commit, the metadata …
> CA-355571: Include accumulative updates for updates description and guidances

- ocaml/xapi/cert_distrib.ml
- ocaml/xapi/message_forwarding.ml
This fixes parallel pool.ejects, and makes cert distribs a bit safer
Additional improvements (for a later PR):
- add a lock for the 'create bundle' script
- on startup, retrieve any missing certs from the master
> REQ-403 concurrency fixes part 1

- ocaml/xapi/cert_distrib.ml
- ocaml/xapi/certificates.ml
- ocaml/xapi/helpers.ml
update_ca_bundle.sh is not thread safe because it manipulates files in
/etc/stunnel. We only allow one instance to be running at once.
> REQ-403 concurrency fixes part 2

- ocaml/xapi/message_forwarding.ml
If it's not the xapi creation will fail as the VM might be in another pool
> Only add XAPI message for VM when migration is live and intrapool

- unixpwd/c/unixpwd_stubs.c
Most of the warnings like below can be fixed by changing type from
`char*` to `const char*`.
```
unixpwd_stubs.c:77:10: warning: assignment discards 'const' qualifier from pointer target type [enabled by default]
user = String_val(caml_user);
^
```
Except for the password, where the `putpwent` API takes a `char*`
instead of `const char*`.
We can't trust that it doesn't internally modify it, so take a copy and
pass that instead, use `caml_stat_strdup`+`caml_stat_free` for this
which automatically raise OCaml exceptions on NULL.
> Maintenance: fix unixpwd warnings about loosing const qualifier

- ocaml/idl/datamodel_common.ml
- ocaml/idl/datamodel_host.ml
- ocaml/idl/datamodel_pool.ml
- ocaml/idl/schematest.ml
- ocaml/xapi-cli-server/cli_frontend.ml
- ocaml/xapi-cli-server/cli_operations.ml
- ocaml/xapi-cli-server/record_util.ml
- ocaml/xapi-consts/api_errors.ml
- ocaml/xapi/cert_distrib.ml
- ocaml/xapi/cert_distrib.mli
- ocaml/xapi/cert_refresh.ml
- ocaml/xapi/cert_refresh.mli
- ocaml/xapi/certificates.ml
- ocaml/xapi/helpers.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_host.mli
- ocaml/xapi/xapi_pool_helpers.ml
Just for discussion. This is my approach to refresh server certificates. This rotation of the certs works both on the client and the server, including updating bundles and the database. However, I don't know yet how best to activate them without losing connections. Hence, the stunnel re-configuration is commented out.
> Cert Refresh

- scripts/bugtool-plugin/xapi/stuff.xml
The number of VM data source list calls made by the deleted line during
a bugtool is `#(hosts) * #(VMs)`. A typical number at scale could be
~ 16 * 2000 = 32000
> CA-355657 XSI-1037 reduce load during bugtool

- scripts/control-domain-params-init
This makes it behave the same as network-init and other *-init services,
as well as the old firstboot scripts.
> CA-341715: control-domain-params-init: skip on upgrade

- ocaml/xapi/cert_distrib.ml
- ocaml/xapi/xapi_host.ml
When changing a host's certificate, it is enough to reload Stunnel
rather than restarting it. This keeps existing connections alive. This
requires support in the systemd configuration of stunnel.
> CA-355625 reload Stunnel instead of restart after cert change

- scripts/control-domain-params-init
Fix a014ba9 has code missing to set the UPGRADE variable.  On upgrade, this key
is found in /etc/firstboot.d/data/host.conf, but on firstboot, this file does
not exist.
> CA-341715: fix control-domain-params-init

- ocaml/tests/test_extauth_plugin_ADwinbind.ml
- ocaml/xapi/extauth_plugin_ADwinbind.ml
- ocaml/xapi/extauth_plugin_ADwinbind.mli
- ocaml/xapi/xapi_globs.ml
- scripts/plugins/extauth-hook-AD.py
- scripts/plugins/test_extauth_hook_AD.py
Winbind just use the hostname as the netbios_name to talk to DC
if hostname is changed after join domain, the auth will failed
This commit fix the issue by
* Store the netbios_name in xapi db during join domain
* Configure netbios_name to winbind daemon during xapi bootup
* Migrate netbios_name from PBIS db if domain joined but xapi
database does not have the value, to support update/upgrade
> CA-355964: Hostname change will affect the authentication

- ocaml/idl/datamodel_host.ml
- ocaml/xapi/cert_distrib.ml
- ocaml/xapi/cert_distrib.mli
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_host.mli
This fixes parallel pool joins
The idea is that the joiners only exchanges certs with the primary host during Pool.join. The secondary hosts will get joiners' certificates because of `am_i_missing_certs_loop`
> REQ-403 concurrency fixes part 3

- ocaml/xapi/xapi_host.ml
A self-signed certificate so puts host names and IP addess into the ANS
(alternatives names) field and the IP addess into the CN field. The ANS
field takes precedence, so the content of CN should not be relevant.
However, in the past (Stockholm release) we put the hostname into the CN
field and the change could be considered a regression. This patch adds
a hostname to the CN field if available.
> CA-355629 use hostname for CN in host cert

- ocaml/gencert/selfcert.ml
- ocaml/gencert/selfcert.mli
- ocaml/idl/datamodel_cluster_host.ml
- ocaml/tests/test_cluster.ml
- ocaml/xapi-types/secretString.ml
- ocaml/xapi-types/secretString.mli
- ocaml/xapi/cert_refresh.ml
- ocaml/xapi/helpers.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_cluster.ml
- ocaml/xapi/xapi_cluster_helpers.ml
- ocaml/xapi/xapi_cluster_host.ml
- ocaml/xapi/xapi_cluster_host.mli
- ocaml/xapi/xapi_clustering.ml
- ocaml/xapi/xapi_pool.ml
Xapi will generate a pem when it creates a cluster. This cert goes in the cluster database. New cluster hosts will get a copy of the cluster pem when they join (such that they can trust the cluster they are joining)
We also provide a mechanism such that we can introduce pems to an existing cluster. This may be necessary before enabling TLS verification
> CP-36097 REQ-403 ferry cluster pems

- ocaml/tests/test_extauth_plugin_ADwinbind.ml
- ocaml/xapi/extauth_plugin_ADwinbind.ml
- ocaml/xapi/xapi_globs.ml
- scripts/plugins/extauth-hook-AD.py
User information is queried through ldap
When joining domain, a machine account and pasword is created in
the joined domain controller, and such info is used to by ldap
query for authentication.
However, if the domain have multiple domain controller,
the joined domain needs time to sync the data to other controllers.
Before the syncing is finished, if one lday query goes to other
domain controller, then it will failed as auth error.
This commit fix the issue by providing winbind krb5.conf to ldap query
This will guides ldap query goes to the right domain controller
> CP-37500: Support multiple Domain controller in domain

- ocaml/idl/dune
- ocaml/xen-api-client/lib_test/dune
Prevent dependency errors when building opam packages.
Opam packages build just the parts they need, and if a 'runtest', 'test'
or 'tests' stanza in dune doesn't declare a package it will attempt to
run the tests for another opam package.
However we may be missing dependencies.
Ensure packages only run their own tests (which should also decrease
testing times of subpackages)
> Add explicit package to dune tests

- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_periodic_scheduler_init.ml
Mostly for testing purposes, it is useful to be able to configure how
often we check to see if there were any failed logins.
See c27e7fd5597c48e93d46ddb469ea4b6a50ff5b67 for the associated
implementation
> REQ-403: failed_login_alert_freq

- ocaml/idl/datamodel_pool.ml
- ocaml/idl/schematest.ml
- ocaml/xapi-cli-server/record_util.ml
- ocaml/xapi/cert_distrib.ml
- ocaml/xapi/cert_distrib.mli
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_pool.ml
- ocaml/xapi/xapi_pool_helpers.ml
Put cert refresh under the cert distrib lock.
The main aim of this is to mutually exclude both
'copy_primary_host_certs' and cert refresh (tls verification enable is
already excluded via the refresh cert pool op).
It is handy to have both locks, since the pool op excludes pool refresh
with things like HA enable/disable.
> REQ-403 concurrency fixes pt 4

- scripts/reset-and-reboot
If user would like to create a new pool with the ejectee, they will have
to reinstall any trusted ca certs
> REQ-403 pool ejectees should remove trusted ca certs

- ocaml/tests/test_extauth_plugin_ADwinbind.ml
- ocaml/tests/test_xapi_cmd_result.ml
- ocaml/xapi-cli-server/cli_operations.ml
- ocaml/xapi/extauth.ml
- ocaml/xapi/extauth_ad.ml
- ocaml/xapi/extauth_plugin_ADpbis.ml
- ocaml/xapi/extauth_plugin_ADwinbind.ml
- ocaml/xapi/xapi.ml
- ocaml/xapi/xapi_cmd_result.mli
- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_session.ml
- ocaml/xapi/xapi_subject.ml
- ocaml/xapi/xapi_systemctl.ml
subject-add needs to perform ldap query for subject information like subject-name
lockout, disabled, etc. This takes long time for subject add
This commit address the issue by
1. Only query subject information from sid once
2. Query and cache closest KDC and update regularly
> CP-37549: Address subject-add performance issue

- ocaml/tests/test_extauth_plugin_ADwinbind.ml
- ocaml/xapi/extauth_plugin_ADwinbind.ml
- ocaml/xapi/extauth_plugin_ADwinbind.mli
name to subject identifier
winbind has cache timeout set to 60s, so winbind sync its cached data
with domain controller every 60 seconds.
If a user is newly created in DC within 60s, winbind failed to resovle it.
This commit fix this issue by perform ldap query on winbin fail
> CA-356901: Perform ldap query if winbind failed to resovle subject

- configure
Use TMPDIR instead if it's provided
> configure: work around read-only /tmp found in opam's 2.1.0

- ocaml/xapi/cert_distrib.ml
- ocaml/xapi/cert_distrib.mli
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_fist.ml
The idea here is that a test harness can place `/tmp/fist_exchange_certificates_among_all_members` on the file system of the primary host, and cause subsequent calls to`Pool.enable_tls_verification` to fail during its critical section. This will allow the test harness to mimic network failures, and reliably test their effect on this api call
> REQ-403 add fist to Cert_distrib.exchange_certificate_among_all_members

- ocaml/gencert/gencert.ml
- ocaml/gencert/selfcert.ml
- ocaml/gencert/selfcert.mli
- ocaml/xapi/cert_refresh.ml
We should be creating a cert with CN=$uuid, rather than with CN=$ip
> REQ-403 change type of cert generated during cert refresh

- ocaml/xapi/cert_refresh.ml
- ocaml/xapi/helpers.ml
The stunnel reload is initiated via systemd, which in turn sends a
signal to stunnel. This is an asynchronous call and we can't know for
sure that stunnel has reloaded its configuration when the call returns.
This can create a race condition in that we try using the new
configuration when indeed it is not yet ready. To avoid this, wait 5
seconds. There is no good mechanism to make this synchronous.
> Stunnel.reload: wait 5s by default

- scripts/usb_reset.py
When a VM has PCI devices attached, xenopsd will call a usb reset with parameter "-r" for USB passthrough devices to indicate a privileged VM.
xen-api doesn't parse option "-r" properly and is wrongly expecting an integer. This PR fixes this.
> Fix issue #4491: USB device reset for Privileged VMs

- scripts/network-init
- scripts/reset-and-reboot
This PR achieves two objectives:
- fixes a bug where /var/xapi/verify-certificates was lingering around after pool eject (causing mismatch between db tls verification state + actual state)
- when we want to 'switch on' the feature by default, reverting f47c98d will ensure that ejected hosts 'come back' with verification enabled
In the future, for new installs, we can also add `FIRSTBOOT_ENABLE_TLS_VERIFICATION='true'` to /etc/xensource-inventory to get verification by default
> REQ-403 verification after pool eject

- ocaml/idl/datamodel_common.ml
- ocaml/idl/datamodel_host.ml
- ocaml/idl/schematest.ml
- ocaml/tests/common/test_common.ml
- ocaml/xapi-cli-server/records.ml
- ocaml/xapi/xapi.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_host.mli
- ocaml/xapi/xapi_pool.ml
TLS verification is enabled on the pool level but can be disabled
locally (in an emergency) for a host. To provide visibility if this has
happened, this adds field Host.tls_verification_enabled for XenCenter to
use it.
> CP-37866 add Host.tls_verification_enabled field

- ocaml/xapi-aux/kerberos_encryption_types.ml
- ocaml/xapi-aux/kerberos_encryption_types.mli
- ocaml/xapi/extauth_plugin_ADwinbind.ml
- ocaml/xapi/xapi_globs.ml
Trunk limit the encryption methods to `strong` to improve securirty.
However, There may be some existing environment with legacy encryption
like RC4-HMAC. Limit the `strong` encryption may break LCM customers.
This commit set encryption type to `strong` as default
and will configure it to `all` during back port
Details: https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html
> CP-37898: Make winbind encryption types configurable

- ocaml/xapi/create_storage.ml
- ocaml/xapi/storage_access.ml
- ocaml/xapi/system_domains.ml
- ocaml/xapi/xapi_vm_lifecycle.ml
- ocaml/xapi/xapi_xenops.ml
When plugging PBDs on startup have to ensure that:
- we wait for the driver domain to boot up and respond before calling the SMAPIv3 plugin to attach it
- ensure we don't deadlock by having cancelable timeouts on driver domain bootup wait, and doing the PBD plug after the xenops event queue is up
Also clean up after failed or missing VBD unplugs: when the system reboots explicitly transition Dom0 VM through Halted and Running power states to trigger the usual cleanups (detach virtual devices). Although take care not to reset other fields like resident on, etc.
> CA-349946: Fix startup race conditions with storage driver domains

- ocaml/xapi/repository.ml
In one update of continuous update model, a local YUM repository is
enalbed on the pool master host. The pool slaves can access this YUM
repository for updating.
This commit restricts the service port of the local YUM repository on
the pool master to TLS interface only.
> CP-36863: Expose local YUM repository only on TLS interface

- ocaml/alerts/certificate/certificate_check.ml
- ocaml/idl/datamodel.ml
- ocaml/idl/datamodel_common.ml
- ocaml/idl/schematest.ml
- ocaml/xapi-cli-server/record_util.ml
- ocaml/xapi/xapi_message.ml
By associating CA certs to the pool object, we had no way to
distinguish alerts from multiple CA certs (without examining the
contents of the message). This was leading a bug, characterised by the
following:
```bash
openssl req -x509 -newkey rsa:2048 -keyout 14key.pem -out 14cert.pem -days 14 -nodes -subj '/CN=localhost'
openssl req -x509 -newkey rsa:2048 -keyout 7key.pem -out 7cert.pem -days 7 -nodes -subj '/CN=localhost'
xe pool-install-ca-certificate filename=7cert.pem
/etc/cron.daily/certificate-check
xe message-list # alert appears as expected
xe pool-install-ca-certificate filename=14cert.pem
/etc/cron.daily/certificate-check
xe message-list # an alert about 14cert.pem appears,
```
This patch ensures the above script will retain both alerts.
NB. with this change if you uninstall a …
> CA-357417 REQ-403 ensure valid cert alerts are not deleted

- ocaml/idl/datamodel.ml
- ocaml/idl/datamodel_common.ml
- ocaml/idl/datamodel_types.ml
- ocaml/idl/ocaml_backend/gen_db_actions.ml
The motivation for change is to make it easier to figure out, from a bugtool, what happened in the xapi database
To see what this PR does, it's easiest to see the diff of the auto-generated file, db_actions.ml:
```
and destroy ~__context ~self =
let self = DM_to_String.ref_PCI self in
let __t = Context.database_of __context in
let module DB = (val (Db_cache.get __t) : Db_interface.DB_ACCESS) in
-      DB.delete_row __t "PCI" self
+      D.debug "deleting row from PCI table: ref=%s" self ; DB.delete_row __t "PCI" self
(**  *)
```
Some ways we might want to extend the change:
- add logging to other tables, apart from PCI
- write to a file other than xensource.log
- log other db calls, such as 'create'
> Add datamodel option to log Db.X.destroy calls

- ocaml/xapi/message_forwarding.ml
When enabling TLS certificate verification for a pool, also enable it
for a Work Load Balancing (WLB). Note that currently TLS certificate
checking can be disabled per host in an emergency but not for WLB.
> CA-357025 enable TLS cert checking for pool and WLB together

- ocaml/idl/datamodel_errors.ml
- ocaml/sdk-gen/csharp/FriendlyErrorNames.resx
Replaced language for values within `FriendlyErrorNames.resx` and `datamodel_errors.ml`
For Yangtze changes see #4508
> CP-37590: Replace negative language

- ocaml/idl/datamodel_errors.ml
Other changes to negative terms were excluded as not relevant to the ticket.
Please also review [xen-api-sdk#189](https://github.com/xapi-project/xen-api-sdk/pull/189)
> CP-37590: Replace negative language with bond/pool member

- scripts/Makefile
- scripts/certificate-refresh
Call `xe host-refresh-server-certificate` from cron. Do it hourly before release for increased testing but revert to doing it daily before release. This requires a corresponding change in `xapi.spec` for packaging.
> CP-37370 refresh pool-internal certs using cron

- .github/workflows/1.249-lcm.yml
- .github/workflows/format.yml
- .ocamlformat
- ocaml/database/block_device_io.ml
- ocaml/database/database_test.ml
- ocaml/database/redo_log.ml
- ocaml/idl/dm_api.ml
- ocaml/perftest/histogram.ml
- ocaml/perftest/tests.ml
- ocaml/tests/test_valid_ref_list.ml
- ocaml/tests/test_xapi_xenops.ml
- ocaml/xapi-cli-server/cli_operations.ml
- ocaml/xapi/context.ml
- ocaml/xapi/create_misc.ml
- ocaml/xapi/dbsync_slave.ml
- ocaml/xapi/extauth_plugin_ADpbis.ml
- ocaml/xapi/import.ml
- ocaml/xapi/pool_db_backup.ml
- ocaml/xapi/storage_access.ml
- ocaml/xapi/xapi_ha.ml
- ocaml/xapi/xapi_ha_vm_failover.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_pool.ml
- ocaml/xapi/xapi_pool_transition.ml
- ocaml/xapi/xapi_session.ml
- ocaml/xapi/xapi_vdi.ml
- ocaml/xapi/xapi_vgpu_type.ml
- ocaml/xapi/xapi_vm_migrate.ml
Now that ocamlformat in Stockholm and Yangtze have diverged, this must
be changed
Updated dotenv action to latest version as well
> ci: update format pipeline for Yangtze

- scripts/xn_diagnostics
It is called `xapi`, not `xcp`:
```
xenopsd-xc:4239
xenops-cli:40364
org.xen.xapi.xenops.classic
```
With this change `xn_diagnostics` prints the state of xenopsd queues
again.
> Fix missing xenopsd diagnostics from bugtools

- ocaml/xapi/xapi.ml
The web-dir parameter is not taken into account in the definition of
common_http_handlers' get_root handler, because !Xapi_globs.web_dir is
evaluated once and for all when the module loads, before the
configuration file is read.
Turn common_http_handlers into a function so that it is evaluated when
called.
Fixes #4512
Signed-off-by: Samuel Verschelde <stormi-xcp@ylix.fr>
Co-authored-by: BenjiReis <benjamin.reis@vates.fr>
> Fix handling of web-dir parameter

- ocaml/tests/test_extauth_plugin_ADwinbind.ml
- ocaml/xapi/extauth_plugin_ADwinbind.ml
Previous solution decide user account locked out by UserAccountControl
However, it is replaced by lockoutTime, see
https://docs.microsoft.com/en-us/windows/win32/adschema/a-lockouttime
This commit decide a user account is locked out if lockoutTime <> 0
> CA-356959: Decide user account locked out by lockoutTime

- ocaml/xapi/extauth.ml
- ocaml/xapi/xapi_periodic_scheduler_init.ml
- ocaml/xapi/xapi_subject.ml
- scripts/plugins/extauth-hook
- scripts/plugins/extauth-hook-AD.py
The permitted user subject name is configured in pam configuration
file /etc/pam.d/hcp_users
however, it is only updated as event callback like add subject
This commit fix this by update the pam configuration if subject
updated in domain controller
> CA-358816: Updated subject name in DC does not get updated in pam

- ocaml/xapi/xapi_vm_migrate.ml
- quality-gate.sh
When communicating between two pool, certificate checking can't be used
because this requires a prior key exchange. Add a patch to detect this
case.
Still testing this - so that's why it's a draft.
> CA-358904 REQ-403  cross pool migration must not use cert checking

- scripts/generate-iscsi-iqn
On upgrade generate-iscsi-iqn sometimes exits with code 1, but without
logging any error message.
Might be better to integrate this script into XAPI so that we get proper
stacktraces in the long run.
For now just enable verbose mode on this script so that we see exactly
how far it executed and on which line it failed in daemon.log.
> CA-356506: enable verbose mode for iqn generation script

- .github/workflows/1.249-lcm.yml
- .github/workflows/format.yml
- .github/workflows/main.yml
1.249-lcm nows follow yangtze branches instead of stockholm ones, change
the source of the .env file to accommodate this
Update the dotenv action to use the latest one. Unfortunately there
isn't a tag that's reused and that forces us to update the workflows
to follow the latest, secured version
> ci: fix lcm workflow

- ocaml/xapi/xapi_mgmt_iface.ml
This postpones the DB calls in `must_be_running` until after the pool-
role check. On the coordinator, DB calls are allowed at this time.
> CA-359076: avoid DB calls when starting management server

- ocaml/xapi/xapi.ml
The web-dir parameter is not taken into account in the definition of
common_http_handlers' get_root handler, because !Xapi_globs.web_dir is
evaluated once and for all when the module loads, before the
configuration file is read.
Turn common_http_handlers into a function so that it is evaluated when
called.
Backported from 8909814f812312014b3a386f97d20ff06d342d44
Related to issue #4512
Signed-off-by: Samuel Verschelde <stormi-xcp@ylix.fr>
Co-authored-by: BenjiReis <benjamin.reis@vates.fr>
> Backport: Fix handling of web-dir parameter

- ocaml/xapi/xapi_cluster_host.ml
Otherwise we get an exception on startup saying the clustering daemon is not enabled.
We first need to enable it, and *then* fetch the pems (fetching the pems would attempt to do an RPC to the local daemon)
> CA-356358: enable clustering daemon before attempting RPC call to fetch them

- scripts/examples/python/XenAPI/XenAPI.py
Python calls magic methods for certain operations, e.g.
`not session` calls `session.__nonzero__`
and `session == foo` calls `session.__eq__`.
In the case of `__nonzero__` the failure is obvious: XAPI will return an RPC error
because it doesn't implement __nonzero__, which will be a dict and not an integer and Python raises a type error.
For a recent example of such a bug, see: https://github.com/xapi-project/sm/pull/562/commits/c52bcdf4e219126cb2b3b7a163902b85912ce4a3
`__eq__` is more problematic because the result is an error, a dict, which can be converted to an always true boolean.
Explicitly check for magic methods (starting with `__`) and reject it as not implemented.
This will give a clear stacktrace and error message, allowing to locate these bugs more easily.
Also prints the …
> XenAPI.Session: raise exception on attempted forwarding of python magic methods

- scripts/certificate-refresh
When xapi is not available, for example early at system startup, a cron
job for cert rotation calling "xe host-refresh-server-certificate" may
fail because xe can't connect to xapi. Log these errors using syslog.
> CA-358326 log cron job for cert refresh in syslog

- dune-project
- ocaml/tapctl/tapctl.ml
- ocaml/vhd-tool/cli/main.ml
- ocaml/vhd-tool/cli/sparse_dd.ml
- ocaml/vhd-tool/src/channels.ml
- ocaml/vhd-tool/src/cohttp_unbuffered_io.ml
- ocaml/vhd-tool/src/common.ml
- ocaml/vhd-tool/src/impl.ml
- ocaml/vhd-tool/src/nbd_input.ml
- ocaml/vhd-tool/src/xenstore.ml
This was missed during the update to dune 2.0
> Enable formatting for ocaml code and format the code

- ocaml/xcp-rrdd/lib/plugin/rrdd_plugin.ml
Before systemd these binaries were daemonized when running on a system,
and not daemonized when ran for debugging purposes.
Now systemd launches them without parameters to be daemonized making
this code obsolete and make it log on daemon.log as well.
Remove the logic that allows daemonization and stop logging to stdout
This avoids the logspam in daemon.log which is produced because the ocaml libraries doesn't set a stricted loglevel. the log facility local0 already avoid logging debug-level messages to xcp-rrdd-plugins.log using syslog configuration
> CA-357785: Stop metrics binaries from logging to stdout

- ocaml/gencert/gencert.ml
- ocaml/gencert/selfcert.ml
- ocaml/gencert/selfcert.mli
- ocaml/xapi/xapi_cluster_helpers.ml
When creating new certs, we made them valid from the current moment. To
help with testing, we backdate them based if fist point
/tmp/fist_gencert_backdate is present. During testing we change the date
and that introduces the problem to have certificates that are only start
to become valid in the future. Backdating avoids the problem.
> CA-359226 add fist point to backdate new certs during testing

- README.markdown
Now with signed commits!
A continuation of #4556.
> I would prefer for lines to not exceed 80 characters and therefore makes this work well in tools like `less`. I understand that markdown rendered into HTML does take care of this but I believe these files are also viewed inside shells.
@lindig I don't have a way to count them, but I'm guessing the `PACKAGES=...` line is the main offender? I'd recommend keeping it copy/paste-able at least. This is the first solution that comes to mind, but maybe there's multi-line in bash that'd still work with `opam install $PACKAGES`?
```bash
PACKAGES="First set here"
PACKAGES="$PACKAGES second set here"
...
```
> Updating README with step-by-step build instructions v2

- ocaml/tests/test_cluster.ml
- ocaml/xapi/xapi_cluster.ml
- ocaml/xapi/xapi_cluster_helpers.ml
- ocaml/xapi/xapi_cluster_host.ml
We want to move to a more explicit interface with xapi clusterd. In
particular, when certificate checking is enabled and what certificates
it is using should be more obvious.
This leaves certificate checking still *off* by default. Expect the CI to tail because this depends on changes in https://github.com/xapi-project/message-switch/pull/74
> CP-38309 make TLS more explicit in clusterd interface

- scripts/extensions/pool_update.precheck
The variable `update_vdi_valid` is used in the `finally` handler, so it must be
initialised before the `try` block.
> CA-359714: update-precheck: fix uninitialised variable

- ocaml/xapi/importexport.ml
The current code always rejects imports of the major version of the
running xapi and the one in the import metadata are not equal. This
change makes it less strict by only rejecting imports from strictly
newer versions of xapi.
> CA-360997: Don't reject imports if the host's major version is larger

- ocaml/xapi/extauth_plugin_ADwinbind.ml
DNS cache all the domain controller information, if one domain
controller broken down, it still be returned as valid controller
This commit fix this issue by re-validate the controller list and
find out one valid controller for further actions
> CA-360951: Failed to lookup workgroup from domain as DNS cache

- ocaml/idl/datamodel.ml
- ocaml/xapi/xapi_task.ml
For now a XAPI client can create a task with `Task.create` and set its status.
But it's not possible to set the results or error_info once a task as finished with success or failure.
Which complicates the reports of the end of the task for the XAPI client.
Also a `Task` created via `Task.create` will always have the pool master as its `resident_on`. It should be settable at task creation and default to `!Xapi_globs.localhost_ref` when not provided.
> Enhance XAPI `Task` API

- ocaml/xapi/extauth_plugin_ADwinbind.ml
Ldap fails for cross domain if the target domain does not trust
the joined domain
Ldap is used to query user details like whether an account is
disabled, locked out etc, provide default value on failure
> CA-361151: Provide default user details on ldap query fail

- ocaml/idl/datamodel.ml
- ocaml/xapi/xapi_task.ml
This is a continuation of https://github.com/xapi-project/xen-api/pull/4543.
When creating a Task that is not linked to another XAPI call, a user needs to set on which host this task is running.
> Enable to set a `Task`'s `resident_on` field.

- ocaml/idl/datamodel_vm.ml
- ocaml/quicktest/quicktest.ml
- ocaml/quicktest/quicktest_vm_snapshot.ml
- ocaml/xapi-cli-server/cli_frontend.ml
- ocaml/xapi-cli-server/cli_operations.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_vm.ml
- ocaml/xapi/xapi_vm.mli
- ocaml/xapi/xapi_vm_clone.ml
- ocaml/xapi/xapi_vm_clone.mli
- ocaml/xapi/xapi_vm_snapshot.ml
- ocaml/xe-cli/bash-completion
This allow to snapshot a VM and ignore some VDIs during the snapshot
This can lead to a gain of time & space ignoring non essential data
See: https://github.com/xapi-project/xen-api/issues/4551
> Add `ignore_vdis` to `VM.snapshot` method

- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_cluster.ml
- ocaml/xapi/xapi_cluster_host.ml
Host_resync() must be executed on each host locally. For this, iterate
on the master (in message_forwarding) and call via RPC pool_resync,
which then calls host_resync().
This commit splits the code from pool_resync() between
message_forwarding) and pool_resync().
> CA-361988 execute cluster host_resync always locally

- ocaml/xapi/import.ml
Reporting duplicate vm can confuse users, see #4567
> xapi/import: report duplicate mac seeds on import as such

- ocaml/libs/http-svr/http.ml
Fixes #4593
Previously:
```
val x : string = "Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ=="
- : Http.authorization = Http.Basic ("Aladdin", "open sesame")
val to_basic : string -> string = <fun>
- : Http.authorization = Http.Basic ("Aladdin", "")
- : Http.authorization = Http.Basic ("", "password"
- : Http.authorization = Http.UnknownAuth "Basic QWxhZGRpbjp0aGU6IHBhc3N3b3Jk"
utop # Http.authorization_of_string (to_basic ":password:");;
- : Http.authorization = Http.UnknownAuth "Basic OnBhc3N3b3JkOg=="
```
now:
```
val x : string = "Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ=="
- : Http.authorization = Http.Basic ("Aladdin", "open sesame")
val to_basic : string -> string = <fun>
- : Http.authorization = Http.Basic ("Aladdin", "")
- : Http.authorization = Http.Basic ("", "password:")
- : Http.authorization = …
```
> fix (http-svr): allow : in passwords when using basic auth

- ocaml/gencert/gencert.ml
- ocaml/gencert/selfcert.ml
- ocaml/gencert/selfcert.mli
- ocaml/xapi/cert_refresh.ml
- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_host.ml
When xapi generates/refreshes a host or pool certificate, the number of
days it will remain valid will be taken from xapi.conf.
Note that initially certficates are generated using a binary 'gencert'
which does not read this value from xapi.conf and will use the current
default of 10 years.
Also note that, for now, certificates used by clusterd have an unlimited
lifetime but this could be changed to also use the value specified in
xapi.conf.
To generate new certificates with a lifetime as in xapi.conf:
* edit xapi.conf
* restart xapi to make it read xapi.conf: service xapi restart
* xe host-reset-server-certificate
* xe host-refresh-server-certificate host=<hostname>
To verify SSL certficate lifetimes:
* openssl s_client -showcerts -connect localhost:443  2> /dev/null < /dev/null
| openssl …
> CP-38850 add xapi.conf option for cert-expiration-days

- ocaml/nbd/lib_test/dune
otherwise it fails to compile as part of the wsproxy package tests
found in https://github.com/psafont/xs-opam/runs/4776218783?check_suite_focus=true#step:10:814
> nbd: include the test binary into xapi-nbd package

- scripts/stunnel-on-demand.socket
- scripts/stunnel-on-demand@.service
Add systemd a ordering dependency on xapi, matching the one that is present on
stunnel@xapi. This ensures that pool members can still communicate with the
pool coordinator (in both directions) until xapi has stopped.
> CA-363068: Ensure that stunnel-on-demand shuts down after xapi

- scripts/plugins/extauth-hook-AD.py
pam module cannot handle subject name with space, instead, it expect
space be replaced with '+'
> CA-363207: SSH access failing when using AD groups with spaces in name

- scripts/plugins/extauth-hook-AD.py
pam module cannot handle subject name with space, the subject is split
by space, put it into [] to handle it
(cherry picked from commit 1e5ab3728e34588de1bde833f73bc8b382975c65)
> CA-363207: SSH access failing when using AD groups with spaces in name (Backport)

- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_message.ml
Messages are usually small but XSI-1175 has shown that mpathalert
messages can reach 200kB per message. This puts stress on the system
because it keeps up to 10000 messages in the database. As an immediate
fix, permit to set a lower limit of messages to keep.
> XSI-1175 make message limit configurable

- ocaml/xapi/create_misc.ml
Keep more details about the version of xapi as it is recorded in the
"sofware-versions" field of a host. This is most useful on a host where
a new version has been installed but not yet started. We want to know,
what version is currently running.
To make this useful, we will have to pass a more detailed XAPI_VERSION 
during builds into the environment from where it is picked up. That 
requires changes in the SPEC file - so let's do this first.
> CP-39031 keep more xapi version details for Host.software_versions

- .ocamlformat-ignore
- ocaml/idl/datamodel_lifecycle.ml
The format of the generated file datamodel_lifecycle.ml and the one enforced by ocamlformat are different, this means when running `make` and `make format` consecutively the format of the file changes.
Make ocamlformat ignore the file altogether to avoid the conflict
> maintenance: ignore formatting of datamodel_lifecycle.ml

- ocaml/xenforeign/dune
- ocaml/xenforeign/main.ml
- ocaml/xenopsd/c_stubs/dune
- ocaml/xenopsd/c_stubs/xenctrlext_stubs.c
- ocaml/xenopsd/xc/dune
- ocaml/xenopsd/xc/xenctrlext.ml
- ocaml/xenopsd/xc/xenctrlext.mli
- quality-gate.sh
- xapi-xenopsd-xc.opam
Adding these here, to xenctrlext instead of upstream allows us to iterate faster to adapt them to new features that we need.
Depends on https://github.com/xapi-project/xs-opam/pull/600 and https://github.com/xapi-project/xenctrl/pull/4
> CP-38617: Add module with stubs for xenforeignmemory

- ocaml/xapi/helpers.ml
- ocaml/xapi/repository.ml
CA-362704: Hide proxy_username and proxy_password for repo proxy
This commit aims to hide the proxy_username and proxy_password of
repository from log file.
CA-362704: Remove credential related info from remote repository conf file
This commit removes credential related info from the remote repository
conf file as there might be proxy credentials (proxy_username and
proxy_password) and the temporary token file path in it.
> Hide credentials in repository configuration from log

- ocaml/idl/datamodel_pool.ml
- ocaml/idl/schematest.ml
Authentication with client certificate requires permission to run
'pool.set_wlb_enabled'. This commit is just for this.
> Add pool.set_wlb_enabled permission for client auth

- ocaml/idl/datamodel.ml
These two methods are used when performing VM.pool_migrate to
migrate VMs from member hosts to coordinator host.
The clients authenticated with certificates require permission to use
these methods. This commit extends the permission list of client auth
with these two methods.
> Add [post|put]_services_xenops to client auth permission list

- ocaml/message-switch/switch/q.ml
- ocaml/vhd-tool/src/channels.ml
- ocaml/vhd-tool/src/chunked.ml
- ocaml/vhd-tool/src/iO.ml
- ocaml/vhd-tool/src/impl.ml
- ocaml/vhd-tool/src/input.ml
- ocaml/xapi-aux/tar_helpers.ml
- ocaml/xapi/cert_distrib.ml
- ocaml/xcp-rrdd/lib/transport/base/rrd_reader_functor.ml
- ocaml/xcp-rrdd/lib/transport/file/rrd_file_writer.ml
- ocaml/xcp-rrdd/lib/transport/page/rrd_page_writer.ml
- ocaml/xen-api-client/lwt/data_channel.ml
- ocaml/xen-api-client/lwt_examples/upload_disk.ml
For testing we add at a random point in a list of operations a failure.
The existing code removed all operations after the inserted failure.
This commit changes this to keep them for debugging. They won't be
executed, though, because the failure is reached first.
> Fist point of cert exchange: keep all operations

- ocaml/idl/datamodel_errors.ml
- ocaml/idl/datamodel_lifecycle.ml
- ocaml/idl/datamodel_repository.ml
- ocaml/idl/schematest.ml
- ocaml/tests/test_repository.ml
- ocaml/tests/test_repository_helpers.ml
- ocaml/xapi-cli-server/cli_frontend.ml
- ocaml/xapi-cli-server/cli_operations.ml
- ocaml/xapi-cli-server/records.ml
- ocaml/xapi-consts/api_errors.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/repository.ml
- ocaml/xapi/repository.mli
- ocaml/xapi/repository_helpers.ml
- ocaml/xapi/xapi_globs.ml
CA-364450: Fix YUM repo config for repo metadata checking
The '--setopt' of yum-config-manager requires specifying the repo name.
The bug fixed in this commit is '--setopt=repo_gpgcheck=1' should be
'--setopt=<repo-name>.repo_gpgcheck=1' in parameter of
'yum-config-manager'.
In this commit, additionally the `repo_gpgcheck` is moved to the initial
repo configuration file content which contains static configurations
usually.
CP-39209: Add new field 'gpgkey_name' in repository object
Prior to this series, the GPG key file name is coded as a global
configuration of XAPI. This will get the GPG key rotation difficult in
future.
This commit changes the configuration into XAPI repository object so
that it could be changed through XAPI API.
CP-39209: Use GPG key file path from repository object …
> Bugfix and improvement for repository GPG key

- ocaml/xapi/xapi_stunnel_server.ml
The CApath stunnel config option is currently used, but it turns out
that the necessary pem file symlinks are not always created. This should
be sorted out, but for now the quickest solution is to switch to CAfile
and use the CA bundle.
> Client-cert auth: use CAfile

- ocaml/idl/datamodel.ml
- ocaml/idl/datamodel_common.ml
- ocaml/idl/datamodel_vm.ml
- ocaml/idl/datamodel_vtpm.ml
- ocaml/idl/dune
- ocaml/idl/schematest.ml
- ocaml/tests/common/test_common.ml
- ocaml/xapi-cli-server/cli_operations.ml
- ocaml/xapi-cli-server/records.ml
- ocaml/xapi/api_server.ml
- ocaml/xapi/create_misc.ml
- ocaml/xapi/xapi_vm.ml
- ocaml/xapi/xapi_vm.mli
- ocaml/xapi/xapi_vm_clone.ml
- ocaml/xapi/xapi_vtpm.ml
- ocaml/xapi/xapi_vtpm.mli
- quality-gate.sh
This is restricted to local access only, through the UNIX socket.
This allows the software TPM daemon to retrieve and push the contents of
the TPM from and to the xapi database.
Any remote accesses to the contents are forbidden
> CP-38626:Allow manipulation of VTPM contents

- ocaml/xapi/repository.ml
Prior to this commit, the assumption is the RPM GPG key will be imported
before running 'reposync'. This results in un-necessary dependency and
un-necessary RPM packages signature checking since this will be done by
'yum upgrade' later as well.
In this commit, the '--gpgcheck' paramter is removed. Thereafter,
'reposync' will only check repository metadata. It will not require the
RPM GPG key being imported anymore. And later in 'yum upgrade', the GPG
key will be imported automatically and used for RPM packages signature
checking.
> Remove RPM gpgcheck in reposync

- scripts/plugins/extauth-hook-AD.py
- scripts/plugins/test_extauth_hook_AD.py
CA-363207 complains pool admin group name with space cannot login,
that issue is fixed by surround group name with [], which works both
for pbis and winbind.
However, the fix does not work PBIS username with space.
This commit take pbis and winbind seperately
* for pbis, relace space with +, which is the original pbis solution
* for winbind, surround name with []
> CA-365112: Permit pool admin username with space to ssh login

- ocaml/tests/test_repository_helpers.ml
- ocaml/xapi/repository.ml
- ocaml/xapi/repository_helpers.ml
This series remove the hard-coded paths of repository metadata files. 
Instead, in this series, the paths are retrieved from the repomd.xml.
> Remove hard-coded paths of repository metadata files

- ocaml/xapi/cert_distrib.ml
- ocaml/xapi/xapi.ml
Previously the function was only called whenever the connection to the
coordinator was lost as it was set up once the initiall connection had
been established
Drafting this until I've made a build and tested it with parallel pool_joins
> CA-365474: Try to synchronize trust roots at startup

- ocaml/libs/gzip/gzip.mli
- ocaml/libs/xapi-compression/xapi_compression.mli
- ocaml/libs/zstd/zstd.mli
There is no good reason to limit the return type of the compression
function.  This makes it work with functions that return a (monadic)
error code.
> Make Xapi_compression.compress more polymorphic

- ocaml/networkd/bin/network_server.ml
Switching to DHCP does not simply replace existing IP addresses, but
may add one in addition.
> CA-359978: Flush IP addresses when switching from static to DHCP

- scripts/plugins/extauth-hook-AD.py
- scripts/plugins/test_extauth_hook_AD.py
CA-355588: users in pool admin group which contains # can not ssh into dom0
Linux PAM take # as comments and there is no way to escape it
This commit fix the issue by permit users and groups through
pam_listfile pam module by
- users, in /etc/security/hcp_ad_users.conf
- groups, in /etc/security/hcp_ad_groups.conf
> users in pool admin group which contains # can not ssh into dom0

- ocaml/xapi-guard/src/main.ml
- ocaml/xapi-guard/src/varstored_interface.ml
* Fix file descriptor leak
* Log the number of file descriptors in use when serving a new VM - this is optional but helps to verify the fix
* Currently testing this (after having removed the debugging code that I used to find the leak)
>  CA-364138 XSI-1217: fix FD leak, Unix.EMFILE

- ocaml/xenopsd/lib/xenops_sandbox.ml
- ocaml/xenopsd/lib/xenops_sandbox.mli
- ocaml/xenopsd/lib/xenopsd.ml
- ocaml/xenopsd/xc/device.ml
- ocaml/xenopsd/xc/dune
- ocaml/xenopsd/xc/service.ml
- ocaml/xenopsd/xc/service.mli
- quality-gate.sh
Xenopsd manages several services that sustain the lifecycle of each
domain. To launch a service, xenopsd usually starts up a daemon and it
waits for this daemon to write its pid on xenstore to signal the service
is ready to attend requests.
While this method is convenient in order to be able to cancel the wait
using xenstore watches, it's unfortunate as it makes the daemons depend
on xenstore even if it isn't needed to supply the service.
This change implements an alternative way to set up a cancellable wait
on the service readiness using inotify and epoll by setting up
filesystem watches instead of xenstore ones.
The polling loop wakes up every second to have a direct method to deal
with timeouts as well as unrelated events that happened in the
filesystem.
For every domain now xenopsd …
> CP-38554: Start up and stop SWTPM and guard for every domain

- .github/workflows/main.yml
- ocaml/xapi-cli-server/cli_frontend.ml
- ocaml/xapi-cli-server/cli_operations.ml
- ocaml/xapi-cli-server/cli_printer.ml
- ocaml/xapi-cli-server/cli_util.ml
- ocaml/xapi-cli-server/record_util.ml
- ocaml/xapi-cli-server/records.ml
- ocaml/xapi-cli-server/xapi_cli.ml
- ocaml/xenopsd/xc/device.ml
- ocaml/xenopsd/xc/domain.ml
- ocaml/xenopsd/xc/memory_breakdown.ml
- ocaml/xenopsd/xc/xenops_server_xen.ml
- quality-gate.sh
Please review both commits separately, in particular:
- the xenopsd drops code that was surprisingly unused around PCI devices, should it be used somewhere?
- Most of the (huge!) churn in xapi-cli-server is around adding named parameter to api calls and removing unused parameters / bindings
I ran a suite run 167355 with BST and BVT with the changed and it turned out green, do we want to run some more tests to be safe around the cli server?
> CP-39551: avoid warnings in xapi-cli-server and xenopsd/xc

- ocaml/idl/datamodel_host.ml
- ocaml/idl/datamodel_pool.ml
- ocaml/idl/schematest.ml
- ocaml/xapi-cli-server/records.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_host.mli
- ocaml/xapi/xapi_pool.ml
- ocaml/xapi/xapi_pool.mli
- ocaml/xapi/xapi_vm.ml
- `Pool.set_uefi_certificates` is implemented and calls `Host.set_uefi_certificates` on all hosts
- `Host.set_uefi_certificates` writes certificates on disks
- On XAPI startup certificates stored in XAPI's `Host.uefi_certificates` are written on disks
- When a host joins the pool `Host.set_uefi_certificates` is called with the certificates stored in XAPI's `Pool.uefi_certificates`
This means:
- At every XAPI startup the certificates in host disks are synced with XAPI's `Host.uefi_certificates`
- When `Pool.set_uefi_certificates` is called all hosts are synced in XAPi and disks with XAPI's `Pool.uefi_certificates`
- When `Host.set_uefi_certificates` is called the host certificates on disk are synced with XAPI's `Host.uefi_certificates`
Also: `Host.set_uefi_certificates` no longer calls …
> Sync varstore certificates in XAPI with those on disks

- ocaml/xenopsd/scripts/block
- ocaml/xenopsd/scripts/make-custom-xenopsd.conf
- ocaml/xenopsd/scripts/xen-backend.rules.in
- ocaml/xenopsd/xc/device.ml
- ocaml/xenopsd/xc/device_common.ml
- ocaml/xenopsd/xc/domain.ml
- ocaml/xenopsd/xc/xenops_server_xen.ml
This allow to use a file path towards a folder instead of a VHD
> Add `9pfs` backend to vbds

- ocaml/forkexecd/test/fe_test.sh
xs-opam's CI is the only environment where /tmp is not writable and
XDG_RUNTIME_DIR is not set. Using TMPDIR with /tmp as a backup will mean
the socket is writeable in all environments
xs-opam's CI successfuly passes with this branch: https://github.com/psafont/xs-opam/runs/6075835428?check_suite_focus=true
> ci: fix testing of xapi-xenstored in newer opam's sandboxes

- ocaml/idl/datamodel.ml
- ocaml/xapi-types/features.ml
- ocaml/xapi-types/features.mli
- ocaml/xapi/repository.ml
In commit d951478f3, a new function was added to restrict the repository
access to pool members only. With this funciton, the pool members need
to use pool_secret in access requests to the mirrorred repositories on
the pool coordinator for authentication.
But in updating, this would cause the pool members can't access the
mirrored repositories as at that time the pool coordinator has been
updated to check the pool_secret while the pool members have not been
udpated to use pool_secret.
Per suggestion from Rob Hoes, this commit adds a temporary feature flag
to make the pool coordinator be able to distinguish the case in the
mixed mode in updating.
> Add temporary feature 'Internal_repo_access' to allow update in mix mode

- ocaml/xapi/xapi_host.ml
These files are owned by other RPM packages.
Also upgrade would need to be taken into consideration where
uefi-certificates would already be set on a pool, but just with KEK+db
without PK+dbx.
In that case if we order uploading PK/dbx and restart xapi the wrong way
around we may get these files wiped completely from the system.
Wiping just KEK+db should be enough to ensure we don't have stale files
around.
Fixes a regression introduced by 53d656bec66d903425fc7bfe580d1425da5f2745
> CA-366430: do not wipe PK.auth/dbx.auth

- ocaml/libs/xapi-compression/xapi_compression.ml
Normally gzip stops reading input when it has reached its own end-of
input marker even when that is before the end of input. This is
overridden by --force for decompression and it is creating a problem for
us because suspend images on disk are represented as devices that are
larger than the actual content - so --force kept reading beyond the
actual input and this in turn was not accepted by the code taking the
uncompressed output.
> Don't use --force in gzip decompress

- ocaml/libs/uuid/dune
- ocaml/message-switch/switch/time.ml
- ocaml/xapi-client/tasks.ml
- ocaml/xapi-idl/lib/scheduler.ml
- ocaml/xapi/xapi_periodic_scheduler.ml
- ocaml/xapi/xapi_vdi.ml
- ocaml/xenopsd/xc/device.ml
- uuid.opam
This causes a failure when compiling wsproxy in an opam environment as the test binary is built for all the opam packages in the repo and wsproxy lacks the alcotest dependency when testing.
> maintenance: run uuid tests as part of that package

- ocaml/xsh/xsh.ml
xsh was closing the file descriptor both in the 'proxy' function and in
the stunnel wrapper code.
Push down the Unixfd.(!) dereference into the proxy code to make it
obvious that we have a Unix.close there, and replace that with
Unixfd.safe_close which avoids double close.
This was causing blob sync to fail in XAPI with an rsync protocol error
(due to the extra EBADF printed by xsh).
Fixes: c6511f0a48e1c058dd43bb02fc9503be0c1aca42 "CA-337546: update to new Stunnel_cache API with Safe_resources support"
TODO: needs a CA ticket and some testing, so far I just confirmed that the EBADF error is gone, need to check whether blob sync works too.
> xsh: fix XAPI blob sync in pools

- ocaml/xapi/nm.ml
Backport of dd86773b85f76fb68fe7efc1296a0b4984e3f751 with local addition
of assoc_opt.
> CP-38462 UPD-825 Recognise ethtool-advertise on PIFs

- ocaml/idl/datamodel.ml
- ocaml/idl/datamodel_lifecycle.ml
- ocaml/xapi-cli-server/cli_frontend.ml
- ocaml/xapi-cli-server/cli_operations.ml
- ocaml/xapi/xapi_message.ml
The RPC overhead when destroying many messages is high. To avoid it,
introcuce a message to destroy several messages in one call. This
introduces a new API call Message.destroy_many. The corresponding CLI
command message-destroy is extended to accept a parameter "uuids" to
accept multiple UUIDs in additio to the existing "uuid" parameter.
I notice that destroyig a message by itself is not cheap because it
parses the XML content of the message being destroyed. In an unlucky
case it also involves scanning a directory on the file system to remove
an alias.
> CP-38688 introduce Message.destroy_many() API/CLI call

- ocaml/xapi/repository_helpers.ml
Following fixes and changes are included in this series:
1. Missing net new RPMs in picking up metadata from updateinfo
2. Add un-installed packages into accumulative update list
3. Add debug logs for outputs of YUM/RPM command lines
> Missing net new RPMs in picking up metadata from updateinfo

- ocaml/xenopsd/lib/xenops_server.ml
- ocaml/xenopsd/lib/xenopsd.ml
This is needed for the case that the type of the backend's internal
state is extended in a xenopsd update, such that any running VMs have
the current runtime metadata. Case in point is the recent addition of
the platformdata key, where the default value (an empty map) is not
sufficient.
> Upgrade VM runtime state when xenopsd restarts

- ocaml/xapi/xapi_host.ml
A CH host is meant to re-apply it's license once a day, in order to
correctly handle expiry and to pick up any new licenses. This is some by
setting a timer in a thread in v6d, which triggers a host.apply_edition
call to xapi after 24 hours. The problem is that this call is rejected
if HA is enabled, which breaks the mechanism.
We'll fix this by allowing a host.apply_edition call if the edition is
not being changed. This is still consistent with the original intention
of the restriction (as evidenced by the code comment).
> XSI-1246/CA-367232: Daily license re-apply fails is HA is enabled

- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_host.mli
- ocaml/xapi/xapi_pool.ml
In particular, the evacuation plan is computed in a different way when
HA is enabled. We want the update readiness to check things as if HA is
disabled, because before updates are applied, HA will be disabled anyway.
> CA-366309: ignore HA when checking update readiness

- scripts/examples/python/Makefile
- scripts/examples/python/pyproject.toml
This fixes #4716, #4717
This only changes how the python wheel (distributable package) is generated, it's generated in the same place.
Note that this still needs to invoke `make build` to generate `setup.py`, In general this will need to have an environment where xapi is buildable in order to retrieve the API version.
> XenAPI.py: define how to build package in pyproject.toml

- ocaml/xapi/helpers.ml
- ocaml/xapi/xapi_host.ml
The check against an empty string needs to be kept as some of the
variables use an empty string as an alternative to None, meaning not to
create the file at all.
> xapi: avoid spawning processes to touch files

- ocaml/idl/datamodel_common.ml
- ocaml/idl/datamodel_host.ml
- ocaml/idl/datamodel_lifecycle.ml
- ocaml/idl/schematest.ml
- ocaml/tests/common/test_common.ml
- ocaml/xapi-cli-server/records.ml
- ocaml/xapi/xapi_host.ml
Add a new field that reflects the last time Host.apply_software_updates
was run (or the time of the first installation).
> CP-38583 add Host.last_software_update field with data/time

- ocaml/database/backend_xml.ml
- ocaml/libs/gzip/gzip.ml
- ocaml/libs/gzip/gzip.mli
- ocaml/libs/xapi-compression/xapi_compression.ml
- ocaml/libs/xapi-compression/xapi_compression.mli
- ocaml/libs/xapi-compression/xapi_gzip.ml
- ocaml/libs/zstd/zstd.ml
- ocaml/libs/zstd/zstd.mli
- ocaml/xapi/audit_log.ml
- ocaml/xapi/export.ml
- ocaml/xapi/import.ml
- ocaml/xapi/repository_helpers.ml
- ocaml/xapi/stream_vdi.ml
- ocaml/xcp-rrdd/bin/rrdd/rrdd_shared.ml
The existing interface to compressions tools assumes that all tools
receive the exact same command-line arguments. This patch removes this
limitiation while keeping the existing comamnd-line arguments as
defaults. No client code needs to be changed.
The xapi_compression.mli interace is extended by accepting additional
(and optional) flags (or other arguments) that are passed to the
compression binary. For example, the compression level could be passed
in addition.
> CP-39884 generalise interface to gzip/zstd-like tools

- ocaml/tests/common/test_common.ml
- ocaml/util/gen_build_info_ml.sh
- ocaml/xapi/xapi_host.ml
Citrix Hypervisor center receives dates via XMLRPC and JSON RPC. Recently introduced dates don't conform to the XMLRPC date format - so fix these. The format itself is a somewhat questionable interpretation for ISO8601 because it mixes no punctuation for the the date with punctuation for the time but this is the format provided in examples by http://xmlrpc.com/spec.md. See the commit messages for details.
> Fix date representations for CH Center

- ocaml/xenopsd/xc/xenops_server_xen.ml
When resuming a VM, xenopsd branches based on where the suspend image is
stored. So far it tries to open the image and read the header. This
either succeeds, in which case it concludes this is a raw image, or
fails. It then open the image again to read it. This patch simplifies
this logic by using the file type to make that decision. If the header
later can't be read this still would lead to a failure - so we are not
skipping the header check.
> Use file type for is_raw_image()

- ocaml/xapi/xapi_http.ml
A HTTP request to XAPI will be authenticated by:
1. session in header,
2. pool secret in header,
3. username and password in header, or
4. client certificate
Therefore, if there is no auth header (1, 2, or 3 above) in the HTTP
request, it should be confirmed that if the request has been
authenticated by client certificate.
The 'Xapi_session.login_with_password' is re-used in
'create_session_for_client_cert' for this purpose. Meanwhile, this
funciton will perform RBAC checking as well.
Prior to this commit, a HTTP request without auth header would be checked
by 'create_session_for_client_cert'. But the 'login_with_password' called
in it would have a long journey since 'create_session_for_client_cert'
feeds empty 'uname' and 'pwd' to 'login_with_password'. This long journey
includes local …
> Short-circuit auth of HTTP requests without auth header

- ocaml/sdk-gen/common/CommonFunctions.ml
- ocaml/sdk-gen/csharp/autogen/src/HTTP.cs
- ocaml/sdk-gen/csharp/autogen/src/Session.cs
- ocaml/sdk-gen/csharp/autogen/src/XenObject.cs
- ocaml/sdk-gen/csharp/gen_csharp_binding.ml
- ocaml/sdk-gen/java/main.ml
- ocaml/sdk-gen/powershell/common_functions.ml
The following commits have already been reviewed within XenCenter, so they can be ignored:
- CP-37091: Do not use a loop for only one iteration. https://github.com/xenserver/xenadmin/pull/2985
- CA-365905 (XSI-1215): Create a temporary file in the target download folder instead of the user's temp folder if the latter is in a different drive from the target folder. https://github.com/xenserver/xenadmin/pull/2993
These are new changes:
- Renamed parameter of abstract method to match the parameter name in the method's implementations.
- CA-355432: Fixed generation of method overloads.
The last commit, apart from the bug referenced, it also contains the SDK counterpart of CP-38610.
> Some SDK fixes

- .github/workflows/docs.yml
Xapi-storage still hosts the documentation for SMAPIv3, so to keep it up-to-date this repository needs to push the changes to xapi-project/xapi-storage.
Tested manually that this correctly updates the correct branch. The first commit will create a `.nojekyll` file once this is merged to master. This is expected as the documentation files have not changed since the last commit and the file is specific to github's pages to avoid its internal jekyll deployment.  Currently the deploy action avoids pushing empty commits, so only changes will create documentation pushes.
I believe there might be a step missing to actually publish to github pages but that can be dealt with a github action in xapi-storage.
> CP-39996: Generate and push docs to xapi-storage

- ocaml/xapi/xapi_session.ml
newer ocamlformat are unable to reach a stable format for code that
has long comment inside long boolean expressions, change the code so an
ocamlformat version compatible with ocaml 4.14 can be used to format the
code.
See https://github.com/ocaml-ppx/ocamlformat/issues/2057
> CP-39806: remove code without a stable formatting

- ocaml/xapi-guard/src/main.ml
- ocaml/xapi-idl/lib/uuidm_rpc_type.ml
- ocaml/xapi-idl/lib/uuidm_rpc_type.mli
- ocaml/xapi-idl/varstore/privileged/varstore_privileged_interface.ml
- ocaml/xapi-idl/xen/xenops_types.ml
- ocaml/xapi/xapi_xenops.ml
- ocaml/xenopsd/cli/xn.ml
- ocaml/xenopsd/lib/resources.ml
- ocaml/xenopsd/lib/suspend_image.ml
- ocaml/xenopsd/lib/suspend_image.mli
- ocaml/xenopsd/lib/xenops_sandbox.ml
- ocaml/xenopsd/lib/xenops_sandbox.mli
- ocaml/xenopsd/scripts/make-custom-xenopsd.conf
- ocaml/xenopsd/suspend_image_viewer/suspend_image_viewer.ml
- ocaml/xenopsd/test/test.ml
- ocaml/xenopsd/xc/device.ml
- ocaml/xenopsd/xc/device.mli
- ocaml/xenopsd/xc/domain.ml
- ocaml/xenopsd/xc/domain.mli
- ocaml/xenopsd/xc/xc_resources.ml
- ocaml/xenopsd/xc/xenops_server_xen.ml
See the description in the commit messages.
> vTPM state storage v0

- ocaml/xapi/livepatch.ml
The bug is the build id should be presented as hexadecimal with width 2.
> CA-368069: Got wrong kernel base build_id

- ocaml/idl/datamodel_errors.ml
- ocaml/tests/test_repository_helpers.ml
- ocaml/xapi-consts/api_errors.ml
- ocaml/xapi/repository.ml
- ocaml/xapi/repository_helpers.ml
- ocaml/xapi/updateinfo.ml
This series contains a few bug fixes to support livepatch function:
1. Bugfix - Remove RebootHostOnLivePatchFailure after a completion of update
2. Return changed guidance from host.apply_updates
3. Bugfix - Add new unit test for livepatch failure case
4. Bugfix - Add RebootHost guidance wrongly when a livepatch failed
5. Bugfix - Wrong format of livepatch in returned updateinfo
> CA-367979: Bugfixes to support livepatches

- ocaml/idl/datamodel_errors.ml
- ocaml/xapi-cli-server/cli_frontend.ml
- ocaml/xapi-cli-server/cli_operations.ml
- ocaml/xapi-consts/api_errors.ml
- ocaml/xapi/xapi_vtpm.ml
- ocaml/xapi/xapi_xenops.ml
For now, only allow a single VTPM to be associated to a VM, and only
allow VTPM creation and destruction on halted VMs to avoid desync of the
DB and the actual running state of the devices.
> CP-40032: Expose VTPM creation and destruction both on the CLI and the API

- ocaml/xenopsd/lib/xenops_sandbox.ml
- ocaml/xenopsd/lib/xenops_sandbox.mli
- ocaml/xenopsd/lib/xenops_utils.ml
- ocaml/xenopsd/xc/device.ml
- ocaml/xenopsd/xc/device.mli
- ocaml/xenopsd/xc/domain.ml
- ocaml/xenopsd/xc/service.ml
- ocaml/xenopsd/xc/service.mli
- ocaml/xenopsd/xc/xenops_server_xen.ml
The PR is better reviewed commit-by-commit. The biggest change (https://github.com/xapi-project/xen-api/pull/4720/commits/10c0291ec1f085e66684d3f445727df7a6f8924a) should only move around the code and only modify the callers' side.
Xenops and the daemons until now have used 2 ways of communicating the pid to the former: a xenstore key and optionally a file. We want to move to a model where we can use only a pidfile for some daemons (SWTPM, mainly).
Previously the path pidfile was implicit and the code to fetch it was shared among all the daemons meaning that even if the daemon always provided a pidfile, their clients always had to take into account the case where there was no file to process.
These changes force all the damon modules to declare the locations where the pidfile is expected …
> CP-39894: Move most of the daemon management code to the service module and make pid locations explicit

- ocaml/idl/datamodel_vm.ml
- ocaml/xapi-cli-server/cli_frontend.ml
- ocaml/xapi-cli-server/cli_operations.ml
- ocaml/xapi-idl/xen/xenops_interface.ml
- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_vm_migrate.ml
- ocaml/xenopsd/cli/xn.ml
- ocaml/xenopsd/lib/dune
- ocaml/xenopsd/lib/xenops_server.ml
- ocaml/xenopsd/lib/xenopsd.ml
- scripts/xapi.conf
* Migrating a VM works currently like this: The source xenopsd opens a
HTTP connection to the destination xenopsd services/xenops/memory. This
connection is used as a socket, i.e. in both direction. The handler on
the destination puts the socket connection into VM_receive_memory. The
source is using this connection for two purposes: sending the memory
stream but also a handshake protocol that syncs up source and
destination. There are more details about the GPU migration stream that
I'm not touching upon.
* This patch introduces an additional route and handler ..../migrate-mem
that will be used only for the VM memory stream and leave almost all
signaling to the two purposes: sending VM memory and keep signaling to
the original first connection. The motivation is to enable compression
of …
> CP-40027 VM migration introduce /services/xenops/migrate-mem

- update-dm-lifecycle
To avoid recompiliation when nothing changed, check for atual changes in
the the update-dm-lifecycle script.
> Update datamodel_lifecycle.ml only when changed

- .github/workflows/draft-release.yml
Currently the generation of the python package needs xapi-datamodel because the api version needs to be extracted.
All the ocaml dependencies can be removed if its version was based on the git tag (removing the `v`), making it much faster as well.
I don't believe running the unit tests is a prerequisite to publishing this package as they are run for every PR and push to master branch.
This workflow will only run on new tags starting with `v`.
> ci: generate releases from tags, upload XenAPI python lib

- ocaml/xapi-aux/throttle.ml
- ocaml/xapi-aux/throttle.mli
- ocaml/xapi/xapi_sr.ml
We use the Throttle module to execute a function multiple times in
parallel up to a configured number. This generalises the existing module
and makes it accessible in other contexts.
> Factor out Throttle module

- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_host.ml
- scripts/xapi.conf
Host.evacuate migrates all VMs from a host to another in preparation of
a host update. This is currently done sequentially, one VM after
another. We want to migrate VMs in parallel to reduce total elapsed
time.
Because a host can host hundreds of VMs, we want to limit
parallelization such that at most n migrations are active at the same
time. We implement this using batching: a fixed number of VMs is
migrated off in parallel before the next batch is started. This is
controlled by a new parameter evacuation-batch-size in xapi.conf.
I suspect that this is leaking tasks but I don't understand why this is happening
and would like to ask reviewers to have an eye towards that. Otherwise the
code works well in the tests that I have …
> CP-40155 Parallelize Host.evacuate

- ocaml/xenopsd/lib/xenops_utils.ml
- ocaml/xenopsd/xc/device.ml
- ocaml/xenopsd/xc/device.mli
- ocaml/xenopsd/xc/domain.ml
- ocaml/xenopsd/xc/service.ml
- ocaml/xenopsd/xc/service.mli
- ocaml/xenopsd/xc/xenops_server_xen.ml
This mirrors the changes in https://github.com/xapi-project/xen-api/pull/4720 except the code that is used exclusively by the swtpm daemon, mainly the code introduced by this commit and successive modifications: [`500bbab` (#4720)](https://github.com/xapi-project/xen-api/pull/4720/commits/500bbab1e5e0bac85cf9ac73972cabb1ef8e2bf1), which I cherry picked, the modified to remove the Swtpm module and functions it depends on (because they would have been unused)
It's pretty to notice the differences between this and the swtpm branch are the removal of functions needed by the swtpm daemon; and the removal of File  in the variant `Pid.path`, which would be unused, and consequent change in behaviour in the uses of this variant.
I used `git diff feature/vtpm..private/paus/pidpaths -- …
> CP-39894: move xenopsd's daemon modules from device to service

- ocaml/xapi/livepatch.ml
The latest livepatch will always roll up the previous ones. Once the
latest one has been applied, the previous ones should be un-loaded to
avoid minor memory leak.
> CA-347473: Minor memory leak from unloaded Xen livepatches

- ocaml/xapi/extauth_plugin_ADpbis.ml
In this ticket, all PBIS lwsmd service threads keep in waiting
status and not able to service new requests. Just restart the
service can resovle the issue and bring the service back.
This symptom looks like a race condition. Given PBIS is going to
be replaced with winbind, this commit workaground the issue
instead of investigate and patch PBIS
* Restart lwsmd on LW_ERROR_ERRNO_ECONNREFUSED
* Restart lwsmd on xapi start/restart
> CA-368806: Workaround pbis get wedged

- ocaml/xcp-rrdd/lib/transport/base/dune
- ocaml/xcp-rrdd/lib/transport/base/rrd_json.ml
- ocaml/xcp-rrdd/lib/transport/base/rrd_protocol_v1.ml
- rrd-transport.opam
We would like to use just one library for creating and consuming JSON;
so replace Ezjsonm with Yojson.
The serialisation of timestamps in the V1 transport appears to change:
they are now serialised as floats; to avoid errors in the parse, we need
to change the reader for the V1 transport.
> CA-367236 replace Ezjsonm with Yojson

- ocaml/xcp-rrdd/scripts/rrdd/rrdd.py
- scripts/examples/python/XenAPI/XenAPI.py
The current implementation of UDSTransport in XenAPI.py and rrdd.py has
several issues:
- It redefines xmlrpclib.Transport.send_request, whose signature has changed
in python 3, so this breaks XenAPI.py's python 3 port.
- The overridden implementation of send_request adds extra headers that are
already handled by the parent class. As a result, extra headers are sent
twice.
- Method __init__ is overridden needlessly, which could cause issues in
the future if the parent class evolves.
This commit fixes the issues by simply deleting the send_request and
__init__ methods from the implementation of UDSTransport.
At the same time, code that was written to retain compatibility with python
< 2.7 is removed.
The add_extra_header method is kept in XenAPI.py, as `sm` apparently uses it
to add a …
> Simplify and fix UDSTransport implementation

- ocaml/idl/datamodel_vm.ml
This commit adds permissions to XAPI clients authenticated by
certificates to allow them to call XAPI methods 'VM.shutdown' and
'VM.start_on'.
> CP-40375: Allow cert clients to perform VM.shutdown and VM.start_on

- ocaml/quicktest/qt_filter.ml
The value of `use_default_sr` is evaluated before it can be set to true
if the `-default-sr` parameter is provided to the command line.
Move the if test inside a function so that `use_default_sr` is only
evaluated when appropriate.
Signed-off-by: Samuel Verschelde <stormi-xcp@ylix.fr>
> Fix quicktest's -default-sr parameter

- ocaml/database/database_test.ml
- ocaml/database/db_cache_types.ml
- ocaml/database/db_upgrade.ml
- ocaml/idl/datamodel_common.ml
- ocaml/idl/datamodel_vm.ml
- ocaml/idl/datamodel_vtpm.ml
- ocaml/idl/schematest.ml
- ocaml/tests/common/test_common.ml
- ocaml/xapi-cli-server/cli_operations.ml
- ocaml/xapi-cli-server/records.ml
- ocaml/xapi/create_misc.ml
- ocaml/xapi/xapi_vm.ml
- ocaml/xapi/xapi_vm.mli
- ocaml/xapi/xapi_vm_clone.ml
- ocaml/xapi/xapi_vtpm.ml
- ocaml/xapi/xapi_vtpm.mli
- ocaml/xapi/xapi_xenops.ml
Replace the profile with single fields, which as of now cannot be changed. Unique can be made configured later on.
This means deleting the default_vtpm_profile from the VM objects. The way the design is going it looks like "empty" or otherwise vtpms associated will replace this parameter, which contain this information and more.
vtpm.create's role has been changed and it's now similat to other classes like vgpu so it uses individual fields as parameters instead of whole records. This is because VTPM records cannot be easily created by clients. (for comparison VM _does_ have a create method, but it has big warnings against using it and the default way to create VMs is by cloning templates, both in Xencenter and Xen Orchestra)
VTPM.backend has been reintroduced for internal purposes only …
> VTPM: rework datamodel, fix nits needed by clients / detected by QA

- ocaml/xapi/xapi_secret.ml
- ocaml/xapi/xapi_vdi.ml
- ocaml/xapi/xapi_vm_clone.ml
- ocaml/xapi/xapi_vtpm.ml
- ocaml/xapi/xapi_vtpm.mli
On the non-unique mode (default) it copies the VTPM, this allows bitlocker to continue functioning in the clone without re-keying.  On unique mode it creates a new VTPM with the same profile.
This PR is not enough to make snapshots work, this is because it's not easy to notify xapi about the new vtpm contents while the VM is running because xenopsd is not involved. Instead it blocks this operation showing that the functionality is not implemented to avoid loss of data.
I've manually tested the clone with both values of unique and the live snapshot with vtpms associated
> CP-39850: Copy VTPM on clone

- ocaml/xapi-types/ref.ml
- ocaml/xapi-types/ref.mli
- ocaml/xapi/helpers.ml
- ocaml/xapi/xapi_pool.ml
While ejecting multiple hosts in parallel some references may become
invalid, ignore them as they are from objects pertaining to ejected
hosts.
> CA-369599: ignore invalid references on eject

- ocaml/xapi-cli-server/records.ml
- ocaml/xapi/helpers.ml
- ocaml/xapi/xapi_cluster.ml
- ocaml/xapi/xapi_pool.ml
- ocaml/xapi/xapi_vtpm.ml
This also blocks creation of VMs from templates with vtpm in the platform data.
Tested manually both cases for feature flag, and 4 cases for fencing + vtpm (try to create vtpm with ha, clustering on + try to enable ha, cluster when a vtpm is present)
> CP-40284, CP-39874: Gate VTPM creation behind an experimental feature and Prevent VTPMs and HA from coexisting

- ocaml/xapi/certificates.ml
The check to find the header and the footer were too strict, trim the lines before comparing.
> CA-370084: Print PEMs containing DOS endlines in yangtze

- ocaml/database/db_xml.ml
attribute of row
When restore xapi database from xml file, xapi require ref be
the first attribute of row, This is not flexible, especially when
need to parse and save the xml files.
This commit fix this issue by search ref in the attribute list
> CP-40669: Restore database should not require ref as the first

- README.markdown
We moved to the GitHub CI - so use them to reflect the build status. Also removed the LoC badges because it appeared unreliable to me.
> Update CI badges in README

- ocaml/gencert/selfcert.ml
- ocaml/gencert/selfcert.mli
clusters don't need their own certificates anymore, remove code that generates them to minimize confusion
> gencert: remove unused cert generation code

- ocaml/xapi/certificates.ml
Previously when overwriting a ca certificate the old object referring to the certificate was not deleted. This meant that when uninstalling that ca certificate, after deleting the certificate file a failure was encountered instead of removing all the database objects referring to the file.
This PR now removes the old certificate objects when installing a new one and removes all of them when the certificate is uninstalled.
Note: the pool join is blocked if there are conflicting certificates so there's no worry of overwriting information in that case
> CA-370731: allow only one database entry per ca certificate

- ocaml/xapi-cli-server/records.ml
This matches the API name, and matches the fact that it's displaying a list, even if currently it will show one at most
> xapi-cli-server: change vm record to show "vtpms"

- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_host.ml
This is an implementation in what was proposed in [this comment](https://github.com/xapi-project/xen-api/pull/4689#issuecomment-1103919868).
- Erase all auth files at XAPI startup, `PK` and `dbx` included
- If after the extract of the tarball mandatory auth files are missing:
fetch them from a fallback dir and copy them in the varstore directory
- New XAPI conf entry: `fallback_auth_dir`: Fallback path for auth files installed by RPMs
> Add a fallback system for auth files belonging to RPMs

- ocaml/tests/test_xapi_db_upgrade.ml
The handling of DMC is guarded by a corresponding license feature flag. But this is not true for the database upgrade rule that is triggered during a version upgrade - it unconditionally disables DMC on all halted VMs. Change this to respect the feature flag as well. This makes backporting this code to the LTSR easier where DMC is still supported.
> CP-33973 disable DMC: adjust unit test to disable DMC feature 

- ocaml/libs/zstd/zstd.ml
- ocaml/libs/zstd/zstd.mli
- ocaml/xenopsd/lib/xenops_server.ml
Testing of vCPU/vGPU compression reveals that it does not offer a benefit on 10+ GBit/s networks because we can't saturate the network. So compression causes a slowdown compared to uncompressed migration.
So far:
* We are spawning a zstd process for compression with default parameters
* The default compression level is 3, on a scale 1 to 19, so 1 would be fast/low-compression and 19 slow/high-compression.
Define and use a new compression profile Zstd.Fast that uses less CPU; it causes less slowdown in the case of fast networks. The benefit on slow networks needs to be re-evaluated but this appears to be a better trade off.
TRUNK
evacuating xrtmia-04-21 without compression
real    3m44.421s
real    3m39.811s
evacuating xrtmia-04-24 with compression Zstd.Default
real    4m42.191s
real …
> CP-40767 CP-40429 Migration Compression - define Zstd.Fast

- .github/workflows/docs.yml
Run commands in the opam context, fix parameter for doc-uploading action
I run a successful workflow in my fork (it doesn't try to upload the artifacts):
https://github.com/psafont/xen-api/actions/runs/3173408028/jobs/5168989428
> ci: more fixes to generate docs

- .github/workflows/docs.yml
Seems like the github action is not prepared for multiple uploads and does not clean up the state immediately. Stop ssh-agent in a best-effort mode so the SSh setup on the second upload succeeds
Unfortunately this step cannot be tested on my fork as it SSH setup is skipped because the action detects it's done in a fork:
```
Run ssh-agent -k || true
SSH_AGENT_PID not set, cannot kill agent
```
> ci: stop ssh-agent to allow for a second upload

- .github/workflows/docs.yml
Seems like github workflow infrastructure is flakey there and makes the CI to fail.
We have other options, maybe using other actions, or even use pull-based, nightly method from the other repositories.
This reverts the changes in .github/workflows/docs.yml from:
bc38b245df68e63e7ed1c80e4dc1846b685da0ef
fdc2afd47bd1e6f39e0498c70bb7617a093b7e83
bed94e97b57aaa99f5c6c0565e0294f1d741ed6e
2e766873311cd165281f4b3558369beff444403a
> ci: stop trying to push docs on every commit

- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_host.ml
This reverts commit 5ad054a4baa39e0356e3c1001e2f557de3a56d50.
This commit caused xapi to delete dbx.auth from /usr/share/varstored.
Currently there's no way to recover this file once it's been deleted as it only gets written on first boot.
There is a plan to make varstored read the certificates from /var/lib/ and make xapi write and delete the files there. While that is implemented revert to the old behaviour to be able to brand shippable versions.
Sorry @benjamreis !
> Revert "Add a fallback system for auth files belonging to RPMs"

- ocaml/idl/datamodel_lifecycle.ml
- ocaml/xenopsd/xc/service.ml
This means that now xensource.log will contain the reason that produced
these exceptions
Reported by @xennifer
> xenopsd/xc: Print all information in Service_failed exceptions 

- ocaml/tests/test_platformdata.ml
- ocaml/xapi-cli-server/cli_operations.ml
- ocaml/xapi/export.ml
- ocaml/xapi/helpers.ml
- ocaml/xapi/vm_platform.ml
- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_vm_clone.ml
- ocaml/xapi/xapi_vm_migrate.ml
- ocaml/xapi/xapi_vtpm.ml
- ocaml/xapi/xapi_xenops.ml
- quality-gate.sh
CP-39744: Block BIOS VMs with vTPM attached from booting
The Physical Presence Interface part of the vTPM specification is only
implemented for UEFI guests, other functionality may be missing.
Also makes the check that raises exceptions centralised and makes it togglable using /etc/sysconfic/xapi
CA-370858: disallow VM exports with VTPMs attached
We're unable to serialize the data because the field for the contents is not exposed in the API and it's based on a secret, which can be dangerous once it's been implemented.
Exports are exposed using an HTTP endpoint, this means it's an indirect operation and that other operations that use the feature will fail in extraneous ways in a non-instantaneous way.
To avoid this the two methods that use it in xapi are changed as well (vm-export and VM …
> CP-39744, CA-370858: Block actions depending on unimplemented VTPM functionality

- xapi.opam
Added an OS package dependency line for AlpineLinux.
> Modify xapi.opam for AlpineLinux

- ocaml/xapi/dbsync_slave.ml
- scripts/plugins/firewall-port
The firewall-port script returns true if port 80 is blocked … and false if it is closed, this is captured in set_https_only to update the DB based on the state of the network, not the requested setting should there be a failure
> CP-40754 Update host.https_only field in dbsync based on firewall state

- ocaml/xenopsd/xc/device.ml
Qemu sends a signal to swtpm to cleanly shut down, this means that Qemu needs to be shut down before SWTPM, and it also means that it's normal behaviour that SWTPM shuts down itself as a consequence of this.
This means that on successful attempts this loglines will be printed when xenopsd tries to shut the service down:
```
Oct  6 14:23:13 x-11-58 xenopsd-xc: [debug||17 |events|service] About to stop vTPM (73a7dbe6-1ea8-b04b-aeea-5b3b524386d1) for domain 1 (9e2bff38-0c30-a9fe-2420-4c7f0fa1f2b4)
Oct  6 14:23:13 x-11-58 xenopsd-xc: [ info||17 |events|service] Not trying to stop swtpm-wrapper-1 since it's not running
Oct  6 14:23:13 x-11-58 xenopsd-xc: [debug||17 |events|service] Storing vTPM state of 6791 bytes
Oct  6 14:23:13 x-11-58 xenopsd-xc: [debug||17 |events|xenops_sandbox] About to …
```
> CA-370140: shut down swtpm after qemu

- Makefile
- ocaml/idl/json_backend/dune
- ocaml/idl/json_backend/gen_json.ml
- quality-gate.sh
Staarting from xapi release 1.250.0, xapi has relied more and more in its own version, rather than on xenserver releases and "API version".
This has meant that in the public docs there is no information of the API changes that have happened in the last 2 years.
This adds the information about these changes to the metadata that gets published. There are some tweaks that could be made, like adding the date of the release for each of these, or tweak the release datatype to better accomodate this new style, or even move all that information to the metadata generation side instead of being a fundamental part of xapi.
I've taken the liberty to port the json generation here to yojson. I've manually checked using jq that the json produced is equivalent, although the new one has a lot lets …
> idl/json_backend: generate data for new-style xapi-releases

- ocaml/libs/http-svr/xmlrpc_client.ml
- ocaml/libs/http-svr/xmlrpc_client.mli
- ocaml/xapi-idl/xen/xenops_interface.ml
- ocaml/xapi/storage_migrate.ml
- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_vm_migrate.ml
- ocaml/xenopsd/cli/xn.ml
- ocaml/xenopsd/lib/xenops_server.ml
This adds the ability for xapi to do VM (storage) migration over HTTPS, therefore allowing hosts to close port 80. This is currently off by default, and can be enabled using a config file option.
> Migration over HTTPS

- ocaml/xapi/xapi_pool_update.ml
- scripts/extensions/pool_update.apply
install time cannot be updated
When applied at host install time, the yum is configured with `group_command=compat`, thus yum does not have group membership information if `group_command=objects` is set during update.apply
This commit set `group_command=compat` to support Driver disks/ supp packs applied
* at host install time
* manually (install some packages)
> CA-370575: [XSI-1310] Driver disks / supp packs applied at host

- ocaml/tests/test_vgpu_type.ml
- ocaml/xapi/xapi_vgpu_type.ml
So far, we identified a GPU by its deviceId; this turns out to be ambiguous and vgpuConfig.xml may contain multiple GPUs with identical deviceId, causing us to use more vGPU types than we can actually support.
This patch introduces a new abstract type "gpu" in the VENDOR signature such that its Nvidia instance can use more information to identify a GPU. This is the core of this patch and fix.
When matching a GPU found on the PCI bus with GPUs listed in vgpuConfig.xml we use:
deviceId match and subsystemId match
or  deviceId match and subsystemId in vgpuConfig is 0
subsystemId=0 is used by Nvidia as a wildcard and thus subsystemId=0 is ignored during a match.
The matching for other vendors remains unchanged (and is still based on deviceId).
Signed-off-by: Christian Lindig …
> CA-370578 use subsystemId in NVidia GPU matching

- ocaml/xapi-cli-server/cli_operations.ml
User were allowed to define more than one certificate-chain when
installing a host certificate. The implementation picked the first one,
ignoring successive ones.
This could lead to a situation where the host served a certificate with
certificates missing in their chain of trust, making it unverifiable.
Instead detect the situation and block the operation immediately.
> CA-370082: Block multiple definitions of certificate-chain in xe cli

- ocaml/xenopsd/scripts/setup-vif-rules
Change the use of doexec in add_vswitch_port to run using the ON_ERROR_FAIL handler. This will prevent the VM from starting in the case of ovs-vsctl failing.
> CA-369446 

- ocaml/sdk-gen/powershell/gen_powershell_binding.ml
Breaks PS SDK generation as the mentions were referring to C# code
Issue introduced in 0e924451d54674b36251d4993e5f397408dd4e86
> Revert `uuidx` rename in `gen_powershell_binding.ml`

- ocaml/xapi/helpers.ml
- ocaml/xapi/static_vdis.ml
- scripts/static-vdis
Currently enabling HA can stall because the GFS2 calls when adding the
HA statefile might stall indefinitely when there are connection issues
Now xapi waits a minute before failing, signalling the user that
something has gone awry
Unfortunately using Python 2.7 blocks us from having a timeout in static-vdis, added a comment so it has more chances of getting added when porting to python 3.5+
Xapi helpers now will also print when a script is called without a callback so it's easier to spot similar situations
I've also converted this infrastructure to [mtime](https://github.com/xapi-project/xen-api/compare/master...psafont:xen-api:private/paus/its-about-mtime?expand=1), but it got big and it's better that this goes in independently
> CA-364194: Allow creation of statefiles to time out 

- ocaml/idl/ocaml_backend/gen_server.ml
- ocaml/idl/ocaml_backend/ocaml_syntax.ml
- ocaml/xapi/server_helpers.ml
- ocaml/xapi/server_helpers.mli
Explicitly define a list of tuples with names and values so the rbac checks can never fail at runtime on differing lengths for these. Instead now the check happens at build time, by list construction.
Calls with defaults allowed the values list to be shorter as they never bothered to contain the default values. Now the default values are collected to match all the names of the parameters.
To help with this, I've removed some custom functions with default ones, and changed how lists are generated to stop using cons, as it doesn't lend itself to determine a particular number of elements in a list.
To give an idea on how these changes impact the code generated here are a couple of examples:
Call without defaults before:
```ocaml
| "subject.get_record" | "subject_get_record" -> 
begin match …
```
> CA-352073: Ensure all serialized calls can pass rbac checks 

- ocaml/xenopsd/xc/domain.ml
The flag was only turning off the debug message but not the code itself. Indentation now makes it very clear that this is wrong, so lets fix it.
Currently this workaround (from the 6.x era is still on in the .conf file, but at some point we may want to turn it off)
> Fix CA-140252 flag

- ocaml/database/db_cache_types.ml
- ocaml/idl/ocaml_backend/gen_server.ml
- ocaml/xapi/rbac.ml
- ocaml/xapi/rbac_audit.ml
- ocaml/xapi/xapi_http.ml
- ocaml/xcp-rrdd/bin/rrdd/rrdd_monitor.ml
Continuation of https://github.com/xapi-project/xen-api/pull/4829
RBAC checks have complicated list traversals, quite a few of them can be avoidable changing the datastructure to a list of tuples. There were also some database lookups that were unnecessary and have been folded together, there is also some refactoring in rbac_audit that tries to reduce the cognitive complexity of the code, hopefully it's easier to analyse.
Db_cacche_types spent an unreasonable amount of time in map.update. This is because it tried to avoid running update on unchanged values. This incurred a terrible amount of cost. Currently we can use the standard library implementation of map.update which avoids this while being efficient, cutting the cpu runtime of xapi under certain conditions by half.
Additionally …
> CA-352073, CA-371780,  CA-372128: reduce overhead in xapi database and rbac checks; and in xcp-rrdd

- ocaml/vhd-tool/cli/main.ml
- ocaml/vhd-tool/cli/sparse_dd.ml
- ocaml/vhd-tool/src/channels.ml
- ocaml/vhd-tool/src/impl.ml
- ocaml/vhd-tool/src/streamCommon.ml
- ocaml/xapi/sm_fs_ops.ml
- ocaml/xapi/sparse_dd_wrapper.ml
- ocaml/xapi/storage_migrate.ml
- quality-gate.sh
This is required to be able to fully support storage migration over HTTPS. This is still off by default.
> Add certificate checking to sparse-dd

- ocaml/xcp-rrdd/bin/rrdd/rrdd_monitor.ml
- ocaml/xcp-rrdd/test/rrdd/dune
- ocaml/xcp-rrdd/test/rrdd/test_rrdd_monitor.ml
This function had quadratic costs with all the lists it was using. On
top of that all three types of owned datasources were processed in a
different way, especially the VMs, which where map from a list of active
VMs instead of the owned data sources
Further work is needed move collect the datasources into the appropriate
datastructure instead of in this function, and extend the datastructures
into the used functions isntead of converting them to lists
Additionally I've ported the unit tests to alcotests, which allowed to uncover a minor difference in behaviour: previously the host record was always created, not it only is created when there are host sources. This is irrelevant in the grand scheme of things as host sources are fed every time to the function.
I've manually tested updating a …
> CA-371780: Reduce overheads in update_rrdds

- ocaml/xenopsd/scripts/swtpm-wrapper
- ocaml/xenopsd/xc/service.ml
Steps are made so the main swtpm software dose not need to create any files on the filesytem.
This incluse:
* pre-creating UDS  and passing the FD to swtpm.
* Switching to linear file for state storage.
* pre-creating the PID file.
Note that the switching to linear file is to be controlled by xenopsd, using a parameter.  Prevously this was incorrectly set as
'file' type when it should be 'dir' type.  This has been changed.  When xenopd is ready to use linear state file, it should pass the 'file' type.  Until this is done, swtpm is allowed to create files, and is hence, still a small risk.
> cp-40190 Steps towards preventing SWTPM from filling dom0 root partition

- ocaml/xapi-idl/gpumon/dune
- ocaml/xapi-idl/gpumon/gpumon_interface.ml
- ocaml/xcp-rrdd/lib/plugin/reporter.ml
We want to tell gpumon to attach and detach its NVML library. Extend the RPC interface defined for gpumon with new calls. Futhermore, generate the gpumon-cli to exercise these operations from the command line. This requires a change in xapi.spec:
%files -n message-switch
%{_unitdir}/message-switch.service
%{_sbindir}/message-switch
%{_sbindir}/message-cli
/usr/bin/gpumon-cli
%config(noreplace) /etc/message-switch.conf
/etc/xensource/bugtool/message-switch/stuff.xml
/etc/xensource/bugtool/message-switch.xml
> CP-33044 define attach/detach IDL calls for gpumon

- ocaml/libs/http-svr/xmlrpc_client.ml
- ocaml/xcp-rrdd/bin/rrdd/rrdd_monitor.ml
- ocaml/xcp-rrdd/bin/rrdd/rrdd_server.ml
By default xcp-rrdd does not log debug lines, elevate two messages so
it's easier to know when this operation starts happening and when it
fails.
Two loglines per call removed: one is not really useful since the first
logline already contains the most important information about the
stunnel configuration and the one about the cache is not important as
the code is known to work as intended.
The main logline about stunnel has been changed to make it obvious there
has been a change in the are about logging when looking at logs
> CA-369690: Prioritize loglines when backing up RRDs, remove loglines about stunnel

- ocaml/xenopsd/scripts/swtpm-wrapper
There is code in swtpm-wrapper for changing cgroups that sholud not be there.  This is all looked after by systemd now.
> CP-41213: swtpm-wrapper should not fiddle with cgroups

- scripts/with-vdi
The vbd-plug call in with-vdi may fail after a VBD was already created. The errexit option would cause the script to fail before the VBD would be destroyed. So make sure we destroy the VBD if vbd-plug fails.
> CA-372785 make with-vdi more robust

- ocaml/xenopsd/c_stubs/xenctrlext_stubs.c
- ocaml/xenopsd/xc/device.ml
- ocaml/xenopsd/xc/device.mli
- ocaml/xenopsd/xc/domain.ml
- ocaml/xenopsd/xc/xenctrlext.ml
- ocaml/xenopsd/xc/xenctrlext.mli
- ocaml/xenopsd/xc/xenops_server_xen.ml
Xenopsd's _H() in xenctrlext_stubs blindly reaches sideways into the internals of a different libray (specifically, Xenctrl from upstream Xen).  This violates many API/ABI rules.  It also breaks now that upstream Xen has switched Xenctrl to using a Custom block.
Have Xenctrlext open its own libxc handle, to disentangle it from Xenctrl.
Signed-off-by: Andrew Cooper <andrew.cooper3@citrix.com>
> Modify Xenctrlext to use its own libxc handle

- ocaml/libs/http-svr/http.ml
- ocaml/libs/http-svr/http.mli
- ocaml/libs/http-svr/http_svr.ml
- ocaml/libs/http-svr/http_svr.mli
- ocaml/xapi/fileserver.ml
- Add `location` to `Http.Request.Hdr`
- Add `response_redirect` method to `http-svr`
- When `GET` is received by the fileserver and `website-https-only` is true: 
- if `host` is filled in the request, redirect towards the same URI but in HTTPS 
- if `host` is not present, reply with a forbidden as before
Solves: https://github.com/xapi-project/xen-api/issues/4856
> Redirect fileserver towards https

- ocaml/xapi-types/secretString.ml
Depends on the changes in https://github.com/xapi-project/stdext/pull/69
> CA-371790: Restrict the permissions on pool tokens

- ocaml/xapi-storage-script/examples/datapath/block/Datapath.activate
- ocaml/xapi-storage-script/examples/datapath/block/Datapath.attach
- ocaml/xapi-storage-script/examples/datapath/block/Datapath.deactivate
- ocaml/xapi-storage-script/examples/datapath/block/Datapath.detach
- ocaml/xapi-storage-script/test/volume/org.xen.xapi.storage.dummy/plugin.py
- ocaml/xapi-storage-script/test/volume/org.xen.xapi.storage.dummy/sr.py
- ocaml/xapi-storage-script/test/volume/org.xen.xapi.storage.dummy/volume.py
- ocaml/xapi-storage-script/test/volume/org.xen.xapi.storage.dummyv5/plugin.py
- ocaml/xapi-storage-script/test/volume/org.xen.xapi.storage.dummyv5/sr.py
- ocaml/xapi-storage-script/test/volume/org.xen.xapi.storage.dummyv5/volume.py
- ocaml/xapi-storage/python/Makefile
- ocaml/xapi-storage/python/examples/datapath/loop+blkback/datapath.py
- ocaml/xapi-storage/python/examples/datapath/loop+blkback/plugin.py
- ocaml/xapi-storage/python/examples/volume/org.xen.xapi.storage.simple-file/plugin.py
- ocaml/xapi-storage/python/examples/volume/org.xen.xapi.storage.simple-file/sr.py
- ocaml/xapi-storage/python/examples/volume/org.xen.xapi.storage.simple-file/volume.py
- ocaml/xapi-storage/python/xapi/__init__.py
- ocaml/xapi-storage/python/xapi/storage/__init__.py
- ocaml/xapi-storage/python/xapi/storage/api/__init__.py
- ocaml/xapi-storage/python/xapi/storage/api/v5/__init__.py
- ocaml/xapi-storage/python/xapi/storage/common.py
- xapi-database.opam
- xapi-datamodel.opam
- xapi-schema.opam
- xapi-storage-script.opam
- xapi-storage.opam
Other distributions other than Xenserver are used for testing the
installation of packages, and they have removed python as an alias for
python2. Being explicit doesn't break compatibility on Xenserver, and
allows us to keep newer versions of Ubuntu for testing in github.
It also has the benefit of reducing confusion when updating to python3 as the change cannot be done implicitly by switching the python binary.
This is a try to fix the latest error in the nightly CI for the docs: https://github.com/xapi-project/xapi-project.github.io/actions/runs/3700548098/jobs/6275403367
> xapi-storage{,-script}: explicitely use python2 instead of python

- ocaml/xenopsd/xc/domain.ml
The former is technical debt in the hypervisor patchqueue, while the latter is an upstream binding.
No functional change.
Signed-off-by: Andrew Cooper <andrew.cooper3@citrix.com>
> Switch from Xenctrl.hvm_check_pvdriver to Xenctrl.hvm_param_get

- ocaml/idl/datamodel_lifecycle.ml
- ocaml/idl/datamodel_pool.ml
- ocaml/idl/schematest.ml
- ocaml/tests/common/test_common.ml
- ocaml/tests/test_vm_placement.ml
- ocaml/xapi-cli-server/records.ml
- ocaml/xapi/dbsync_master.ml
- ocaml/xapi/vm_placement.ml
- ocaml/xapi/xapi_vm_placement.ml
By design, the pool master has a bias against scheduling VMs on it, preferring other member hosts.
An option to toggle this bias has been added, which can be used to improve performance, for example when the non-master hosts get overloaded.
> CP-40950: Make bias against scheduling vms on pool master configurable

- .github/workflows/1.249-lcm.yml
- .github/workflows/docs.yml
- .github/workflows/draft-release.yml
- .github/workflows/format.yml
- .github/workflows/main.yml
This is done both by changing how the output fro the action is set and by updating the versions of the actions
These warning will become errors on the last day of May 2023, so better do it now rather than later
The new versions for the actions work, and I've manually verified that the set-output action for generating the cache key works
> ci: avoid github API deprecation warnings

- ocaml/xenopsd/c_stubs/xenctrlext_stubs.c
The parameter open_flags was missing from the definition. Since it's actually [unused](https://github.com/xen-project/xen/blob/master/tools/libs/foreignmemory/core.c#L34-L67) by the underlying implementation its meaning is undefined. Remove the parameter and pass 0 to it.
> xenctrlext_stubs: fix xfm_open parameter mismatch

- ocaml/xapi-storage/generator/lib/data.ml
All the other VDI-related features declared by a SMAPIv3 plugin begin VDI_ so we should amend ATTACH_READONLY to match them and make it VDI_ATTACH_READONLY.
Signed-off-by: Tim Smith <tim.smith@citrix.com>
> CP-40946 Make ATTACH_READONLY consistent with other features

- README.markdown
- ocaml/doc/basics.md
- ocaml/doc/templates/branding.mustache
- scripts/examples/python/setup.cfg
- scripts/examples/python/shell.py
- scripts/motd
- scripts/xe-backup-metadata
- scripts/xe-edit-bootloader
- scripts/xe-restore-metadata
- scripts/xe-xentrace
---
This doesn't anything regarding the SDK.
> CP-41366: Rename Citrix Hypervisor to XenServer

- ocaml/idl/datamodel_lifecycle.ml
- ocaml/xapi/fileserver.ml
With the previous patch the requests were redirected to HTTPS instead.
Current behaviour is to deny all HTTP requests when website_https_only
is turned on. When it's not, try to redirect the request from HTTP to
HTTPS.
supersedes #4863
> CA-373785: Deny HTTP requests on website_https_only

- Makefile
This fixes being able to install the RPM, which has been broken since https://github.com/xapi-project/xen-api/commit/9c95d1ed393f6302db26a42a91717e9a967d89e0
> Makefile: install and uninstall xapi-schema using dune

- ocaml/idl/datamodel_common.ml
- ocaml/idl/datamodel_lifecycle.ml
- ocaml/idl/datamodel_vm.ml
- ocaml/idl/schematest.ml
- ocaml/tests/common/test_common.ml
- ocaml/xapi-cli-server/cli_operations.ml
- ocaml/xapi-cli-server/record_util.ml
- ocaml/xapi-cli-server/records.ml
- ocaml/xapi-idl/lib_test/xen_test.ml
- ocaml/xapi-idl/xen/xenops_types.ml
- ocaml/xapi/create_misc.ml
- ocaml/xapi/xapi_vm.ml
- ocaml/xapi/xapi_vm.mli
- ocaml/xapi/xapi_vm_clone.ml
- ocaml/xapi/xapi_xenops.ml
- ocaml/xenopsd/cli/xn.ml
- ocaml/xenopsd/lib/xenops_server.ml
- ocaml/xenopsd/test/test.ml
- An added field in actions namespace: `after_softreboot` to VM
- Contains all actions in `after_crash` and `soft_reboot`
- Updated Xenopsd VM with field and new `Vm.Softreboot` Handler which triggers the previous `B.VM.soft_reset`
> CP-41444 Added actions_after_softreboot field and passed to Xenopsd

- ocaml/xapi-idl/rrd/rrd_interface.ml
- ocaml/xcp-rrdd/bin/rrdd/rrdd_server.ml
- ocaml/xcp-rrdd/bin/rrdd/rrdd_server.mli
- quality-gate.sh
Previously when a requested datasource was not recorded, an unhelpful message "Xcp_rrdd_internal_error Not_found" was generated. Instead create a new error to signal when a source is not being recorded. This also contains what source is missing: the object related to the datasource (a VM or SR), or just the datasource.
> CA-374274: Provide more information when datasource is not found

- message-switch.opam
- ocaml/gencert/lib.ml
- ocaml/gencert/selfcert.ml
- ocaml/gencert/test_lib.ml
- ocaml/idl/datamodel_lifecycle.ml
- ocaml/idl/ocaml_backend/gen_server.ml
- ocaml/message-switch/async/protocol_async.ml
- ocaml/message-switch/switch/dune
- ocaml/nbd/src/main.ml
- ocaml/vhd-tool/src/dune
- ocaml/xapi-guard/lib/varstored_interface.ml
- ocaml/xapi-storage-script/main.ml
- ocaml/xapi/import.ml
- ocaml/xapi/session_check.ml
- ocaml/xapi/session_check.mli
- ocaml/xapi/stream_vdi.ml
- ocaml/xcp-rrdd/lib/transport/page/dune
- ocaml/xen-api-client/async_examples/event_test.ml
- ocaml/xen-api-client/lwt_examples/watch_metrics.ml
- ocaml/xenopsd/xc/service.ml
- quality-gate.sh
Adapts code to new versions introduced by https://github.com/xapi-project/xs-opam/pull/610
fixes https://github.com/xapi-project/xen-api/issues/4686
> CP-40716: update usages of third-party libraries

- ocaml/networkd/lib/network_config.ml
It is an optional field, handle its abscence gracefully. Following up: https://github.com/xapi-project/xen-api/pull/4333 (commit: e8dbc1d981ee9cb1f8090da996cd794b0ca1141c)
> CA-374872: error when `BOND_MEMBERS` is not in `management.conf`

- ocaml/xenopsd/scripts/block
When the VDI datapath is attached with an NBD export the backend expects the details to be present in physical-device-path.
> CP-33338: write physical-device-path to xenstore for nbd devices

- .github/workflows/docs.yml
This workflow started failing because the C dependencies weren't being installed.
Bypass dune's cache to avoid this, avoid pinning twice the packages and avoid running outdated dotenv action
> ci: fix docs upload of xapi-storage

- ocaml/xenforeign/main.ml
- ocaml/xenopsd/c_stubs/dune
- ocaml/xenopsd/c_stubs/xenctrlext_stubs.c
- ocaml/xenopsd/xc/dune
- ocaml/xenopsd/xc/xenctrlext.ml
- ocaml/xenopsd/xc/xenctrlext.mli
- xapi-xenopsd-xc.opam
These are known to be problematic and cause segfaults on shutdown, the call can be done by passing around NULL to let xen create a handle that can be ignored.
This needs testing with a special build of xen without the bindings from @andyhhp
> CP-42173: xenctrlext: stop using xentoolog bindings

- ocaml/xapi/repository.ml
Download only the latest version of each RPM when mirroring down from the
hosted yum repository
Signed-off-by: Gang Ji <gang.ji@citrix.com>
> CP-42016: Add parameter "--newest-only" to "reposync" command

- ocaml/xapi/storage_access.ml
- ocaml/xapi/storage_mux.ml
- ocaml/xapi/storage_smapiv1_wrapper.ml
The top-level SMAPIv2 server in xapi uses a mux to forward calls to
lower level SMAPI servers depending on the SR. This relies on having
each SR registered with the mux as soon as the related PBD is plugged on
a host. These registrations are held in memory and therefore need to be
refreshed every time xapi starts.
Previously, the mux had a wrapper on top of it, which handled some of
the SMAPIv2 calls itself, without forwarding invoking the mux at all. An
example is the SR.list call, which returns the list of currently
attached SRs on a host. This used state from a file in dom0 and
therefore worked before registering SRs with the mux.
Unfortunately, `SR.list` is used a few times in xapi's startup sequence
before mux registrations are complete. Now that the wrapper has been
removed, the …
> CA-375256: Fix storage initialisation on xapi startup

- scripts/xe-toolstack-restart
Starting all services at once is what happens on boot, so this should work.
We currently stop services one at a time, and if they get stuck (e.g. due to waiting on a network filesystem that is stuck) then each has to hit the 1m30s timeout in systemd before they get killed, which is a minimum of ~32m before the toolstack is stopped.
Which is a lot higher than the default 2 minute HA timeout, and even if the XAPI watcher would attempt recovery by restarting XAPI (or the toolstack), it would be stuck waiting for this 30m process to complete first.
Stop all services at once and then start all needed ones at once. (Don't attempt to restart all in a single command since that might result in some services restarting and immediately seeing another service being restarted, interrupting …
> CA-375280: xe-toolstack-restart: stop and start all services at once

- ocaml/database/db_cache_types.ml
- ocaml/idl/ocaml_backend/gen_server.ml
- ocaml/xapi/rbac.ml
- ocaml/xapi/rbac_audit.ml
- ocaml/xapi/server_helpers.ml
- ocaml/xapi/server_helpers.mli
- ocaml/xapi/xapi_http.ml
Backport of https://github.com/xapi-project/xen-api/pull/4835
Results on 12-core machines:
creating 512 VMs (unikernels), pausing, then shutting them down:
unpatched:
```
$ time ./minion-storm.bash
real	23m7.819s
user	0m4.063s
sys 	0m18.154s
```
```
$ time xe vm-list > /dev/null
real	0m0.733s
user	0m0.012s
sys 	0m0.015s
```
patched:
```
$ time ./minion-storm.bash
real	16m29.273s
user	0m5.737s
sys 	0m25.089s
```
```
$ time xe vm-list > /dev/null
real	0m0.449s
user	0m0.009s
sys 	0m0.032s
```
> backport CA-352073, CA-342527, CA-372128: reduce overhead in xapi database and rbac checks

- .editorconfig
- .gitignore
- Makefile
- ocaml/auth/xa_auth_stubs.c
- ocaml/libs/log/syslog_stubs.c
- ocaml/vhd-tool/src/direct_copy_stubs.c
- ocaml/xenopsd/c_stubs/tuntap_stubs.c
- ocaml/xenopsd/c_stubs/xenctrlext_stubs.c
- unixpwd/c/unixpwd_stubs.c
Fixes a race condition introduced in 40b755b6d, but also some other long standing bugs (wrong number of arguments to C stubs, incorrect O_DIRECT setting).
It also prepares the C stubs for OCaml 5.0 compatibility by removing some global state (although I don't claim this to be fully OCaml 5.0 ready yet).
There are some '[maintenance]' commits as well to make debugging better by preserving errno in a Unix_error instead of losing it with 'failwith', and better editor integration for C stubs (write out a compile_flags.txt with paths to headers/etc. so that `clang` can act as a language server, just like ocaml-lsp would for OCaml file).
There is also a static analyzer to check that these particular race conditions got fixed everywhere, but that depends on a newer version of GCC, and will come …
> OCaml C stub bugfixes

- ocaml/xapi/helpers.ml
- ocaml/xapi/xapi_vif.ml
- New `Helpers` method: `assert_is_valid_ip_addr`
- Use the new methoid in the setters and adders of a VIF's allowed IPs
Solves https://github.com/xapi-project/xen-api/issues/4694
> Allow to use a CIDR for VIFs IPv4 and IPv6 allowed IPs

- ocaml/tests/test_data/repository_pkg_of_fullname_all
- scripts/examples/python/XenAPI/XenAPI.py
- scripts/examples/python/XenAPIPlugin.py
- scripts/examples/python/setup.cfg
Replace the use of six.moves with directly importing the standard xmlrpc and http libs of Python 2.7 and Python 3.x
Tested by using xenserver-status-report/xen-bugtool with it using on XS 8.3.0 with Python 2.7 and Python 3.6 installed.
Consequently, the Requires: python-six and python3-six can be removed from the xen-api.spec file as well.
> python/XenAPI: Replace import six.moves with stdlib imports

- ocaml/xapi/extauth_plugin_ADwinbind.ml
- ocaml/xapi/xapi_globs.ml
During login, subject information is queried to verify detailed info. Default value is used in case of ldap query failed.
This commit set a configurable timeout for ldap query. For a busy system with lots of login request with remote Domain Controller, Admin can set a smaller timeout to accelerate the login process
> CP-41730: Limit ldap query timeout for subject information

- scripts/examples/python/setup.cfg
As pointed out in #4715, `setuptools` now has a warning for dash-separated keys like `long-description-content-type`:
https://github.com/pypa/setuptools/blob/main/setuptools/dist.py#L789
They don't warn when using `pip3 wheel -w dist --no-deps .`, but they warn when using `python setup.py build` etc.
I've checked the setuptools commit history to find about all the details.
We should fix the warning.
Fixes #4715
> python/setup.cfg: Fix deprecated dash-separated key

- ocaml/idl/datamodel_common.ml
- ocaml/idl/datamodel_lifecycle.ml
- ocaml/idl/datamodel_pool.ml
- ocaml/idl/schematest.ml
- ocaml/tests/common/test_common.ml
- ocaml/xapi-cli-server/records.ml
- ocaml/xapi/dbsync_master.ml
- ocaml/xapi/xapi_pool.ml
Add a new field "last_update_sync" of type DateTime to record when the last
update synchronization occurred.
> CP-42014: Add last_update_sync to pool datamodel

- ocaml/xapi/xapi_host.ml
in order to maintain backwards compatibility.
> CP-40847: synchronize read-only uefi-certificates field for both host & pool

- scripts/plugins/extauth-hook
- scripts/plugins/extauth-hook-AD.py
External auth pluins needs to import Enum, which is removed as
secureboot-certificate does not Requires it any more.
To resovle this issue there are two options:
* Requires python2-enum34 in xapi.spec in re-introduce the package
* Update the plugins to use python3
Given python2 are going to be updated to puthon3, this commit fix
the issue by telling plugins to use python3 explictly
> CA-364049: Tell external auth plugins to use python3

- ocaml/networkd/bin/network_server.ml
- ocaml/networkd/bin/networkd.ml
- ocaml/xapi-idl/network/network_interface.ml
- ocaml/xapi/xapi_pif.ml
network config will not write to disk when network state is being refreshed when starting up
- 	added `config_writable` flag. config will write on if true but will remain in memory otherwise.
- 	`config_writable` is set to false when the state is cleared
- 	added `sync_state` function to enable disk writing then write to disk: synchronising memory and disk.
This will prevent the chance of incomplete config in `networkd.db` which can cause network issues on reboot.
> CA-343683 Atomising Networkd pif plugging on Xapi startup

- ocaml/forkexecd/lib/fe_systemctl.ml
- ocaml/forkexecd/lib/fe_systemctl.mli
- ocaml/forkexecd/lib/forkhelpers.mli
- ocaml/forkexecd/test/fe_test.sh
- ocaml/quicktest/dune
- ocaml/quicktest/qt.ml
- ocaml/quicktest/qt_filter.ml
- ocaml/quicktest/qt_filter.mli
- ocaml/quicktest/quicktest.ml
- ocaml/quicktest/quicktest_args.ml
- ocaml/quicktest/quicktest_fe_systemctl.ml
- ocaml/xapi-cli-server/cli_operations.ml
- ocaml/xapi/export.ml
- ocaml/xapi/import.ml
- ocaml/xapi/importexport.ml
- ocaml/xenopsd/xc/service.ml
- quality-gate.sh
This is in preparation of running etcd as a (templated/transient) systemd service.
The test here launches 'env' through fe_systemctl and sets an environment variable containing all printable characters as values to check that quoting is done properly.
In particular systemd's quoting doesn't match either `Filename.quote` or `String.escaped` and needs a hand-written escaper. The syntax is [documented here](https://www.freedesktop.org/software/systemd/man/systemd.syntax.html#Quoting), notice how Filename.quote would produce the wrong results when escaping the single quote character (`'\''`) and String.escaped would not quote it at all.
Quote single and double quotes using hex escape sequences (this makes it independent to the kind of quote used to wrap items).
The test is not suitable for a …
> fe_systemctl: fix quoting and add a quicktest

- ocaml/idl/datamodel_errors.ml
- ocaml/idl/datamodel_lifecycle.ml
- ocaml/idl/datamodel_pool.ml
- ocaml/idl/schematest.ml
- ocaml/tests/common/test_common.ml
- ocaml/xapi-cli-server/cli_frontend.ml
- ocaml/xapi-cli-server/cli_operations.ml
- ocaml/xapi-cli-server/record_util.ml
- ocaml/xapi-cli-server/records.ml
- ocaml/xapi-consts/api_errors.ml
- ocaml/xapi/dbsync_master.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_pool.ml
- ocaml/xapi/xapi_pool.mli
This series add a few pool-wide fields and APIs to facilitate the
telemetry functionality to store and manage pool-wide configurations.
> CP-41574: Add telemetry configuration data

- ocaml/idl/datamodel_errors.ml
- ocaml/idl/datamodel_host.ml
- ocaml/idl/datamodel_lifecycle.ml
- ocaml/idl/datamodel_vm.ml
- ocaml/idl/schematest.ml
- ocaml/tests/common/test_common.ml
- ocaml/xapi-cli-server/cli_frontend.ml
- ocaml/xapi-cli-server/cli_operations.ml
- ocaml/xapi-cli-server/records.ml
- ocaml/xapi-consts/api_errors.ml
- ocaml/xapi/create_misc.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/repository.ml
- ocaml/xapi/repository.mli
- ocaml/xapi/repository_helpers.ml
- ocaml/xapi/updateinfo.ml
- ocaml/xapi/updateinfo.mli
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_host.mli
- ocaml/xapi/xapi_host_helpers.ml
- ocaml/xapi/xapi_vm.ml
- ocaml/xapi/xapi_vm_clone.ml
- ocaml/xapi/xapi_xenops.ml
1. add a new field "recommended_guidances" in both host and vm datamodel
2. return "recommended_guidances" together with "warnings" as update applying results from host.apply_updates
3. add API host.apply_recommended_guidances
4. refactor "immediate_guidances" to "recommended_guidances"
> CP-42013: Do not apply recommended guidances automatically

- ocaml/xapi/xapi_stats.ml
The "pool_total_session_count" RRD is labeled incorrectly. The number reported is the change in the number of sessions since the previous sample was taken (which I believe was 5s agao). Change the name and description to
* pool_session_count_change
* "Change in number of sessions since last update"
> CA-375359 improve "pool_total_session_count" RRD description

- ocaml/xapi/xapi_vtpm.ml
The internal function that's more complex can have another name, rename so it's easier to see which one is being used and the intention behind it.
> xapi_vtpm: do not reuse name for get_contents

- ocaml/xapi/xapi_stats.ml
For other data source units we always use the `objects/s` format.
E.G.:
- requests/s
- hits/s
- misses/s
- err/s
> CA-375359 & CP-42286: Rename `sessions per second` to `sessions/s`

- ocaml/xapi-consts/api_errors.ml
- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_host.ml
Flip the default for HTTPS migration to ON. This is another step to have no unencrypted communication.
> CP-41796 enable HTTPS migration by default

- ocaml/xapi-consts/api_errors.ml
- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_host.ml
Backports of
* b490291cd 2023-03-24 CP-41796 prevent changes to https_only in CC_PREPARATIO..
* 4679475d1 2023-03-23 CP-41796 enable HTTPS migration by default
> Yangtze: enable HTTPS migration by default, prevent changes in CC_PREPARATIONS

- ocaml/idl/datamodel_errors.ml
- ocaml/idl/datamodel_pool.ml
- ocaml/idl/schematest.ml
- ocaml/tests/common/test_common.ml
- ocaml/xapi-cli-server/cli_frontend.ml
- ocaml/xapi-cli-server/cli_operations.ml
- ocaml/xapi-cli-server/record_util.ml
- ocaml/xapi-cli-server/records.ml
- ocaml/xapi-consts/api_errors.ml
- ocaml/xapi/dbsync_master.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_pool.ml
- ocaml/xapi/xapi_pool.mli
- ocaml/xe-cli/bash-completion
1. add new fields: "update_sync_frequency", "update_sync_day", "update_sync_hour", "update_sync_enabled" in pool datamodel
2. add API: pool.configure_update_sync
3. add xe CLI: pool-configure-update-sync
> CP-42011: Config scheduled job to synchronize updates

- ocaml/libs/ezxenstore/lib_test/dune
This prevents opam from trying to compile the tests when testing other packages
> ezxenstore: make tests exclusive to it

- ocaml/xapi/import.ml
We check if a VTPM already exists in a pool during import. Make sure we are more robusy if a VTPM does not exist by catching all exceptions.
> CP-39935 catch and log unexpected exceptions during import

- ocaml/xapi/xapi_pvs_cache_storage.ml
In particular, if the host parameter is left out from the call, a null ref is used and put into the new PVS_cache_storage object. The DB GC will then destroy the object when it runs next, due to the invalid ref, but it is better to fail the create call immediately.
> CA-376448: explicitly validate refs in PVS_cache_storage.create

- ocaml/gencert/gencert.ml
- ocaml/gencert/lib.ml
- ocaml/gencert/lib.mli
- ocaml/gencert/selfcert.ml
- ocaml/gencert/selfcert.mli
- ocaml/xapi/cert_refresh.ml
- ocaml/xapi/certificates.ml
- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_host.ml
- scripts/gencert.service
- scripts/xapi.conf
- Currently /etc/xensource/xapi-ssl.pem is user (default root) readonly, to share to other users of one group add the setting "server-cert-group-id".
- gencert.service can not read xapi config file, so feed the goup id in service unit file directly. In future can consider to make "xapi_globs" as common library so that gencert.service can read "server-cert-group-id" directly.
- The group id -1 means the default group won't be changed.
> CP-42642: Support share server certificate file to group users

- ocaml/xapi-cli-server/cli_operations.ml
- ocaml/xapi-cli-server/records.ml
Use vm-uuid for vtpm-list and expose vtpm name-label as well for it, like other fields
> xapi-cli: Have a consistent interface for vtpms's vm

- .github/workflows/release.yml
This uses the new token-less authentication method added to PyPI, which
restricts the conditions around the github workflow allowed to publish
Workflow tested here: https://github.com/psafont/xen-api/actions/runs/4786024146
it only fails on upload to pypi because it lacks permissions, otherwise it works as expected, including the creation of github release and the contents of the artifact match with what's expected, with a tarball and a python wheel
> ci: publish XenAPI releases to PyPI

- ocaml/xapi/xapi.ml
The init complete file should be touched at the end of startup sequence to state the complete of init
Test:
Toolstack-input: Karma test is happy with it. 182471 (Dev Run)
> Move writing init complete to the end of startup sequence

- ocaml/xapi/message_forwarding.ml
To properly reflect that a VTPM can be added again to a VM after deleting it, we need to update allowed operations.
> CA-376894 update VM allowed ops after deleting VTPM

- ocaml/message-switch/switch/q.ml
- ocaml/tests/dune
- ocaml/xapi-cli-server/records.ml
- ocaml/xapi/xapi_vm_snapshot.ml
- ocaml/xapi/xapi_vtpm.ml
- ocaml/xapi/xapi_xenops.ml
Implement VM snapshot/revert and VM clone for VMs that have VTPMs.
A VM snapshot is a VM record with an additional field snapshot_metadata
that contains all metadata of the VM we are taking a snapshot of. This
metadata includes a reference to the VTPM the VM is/was using. In
addition, a new VTPM as a copy of the existing one is created and referred
to by the VM record that represents the snapshot. So a snapshot references
two VTPM: one directly (A) and one via snapshot_metadata (B).
Since the VM that took the snapshot is in continued use, it will continue
to update B but A is stable.
When reverting the snapshot we create a new VM from the VM record that
represents the snapshot. This can happen again and again.  Unlike a clone,
reverting a snapshot does not consume it.
As a consequence, …
> CP-40528 VTPM snapshot, revert, clone

- .github/workflows/main.yml
It's a private library so it doesn't have a corresponding package anymore
> ci: do not attempt to install xapi-database

- ocaml/xapi/xapi_vm_snapshot.ml
- quality-gate.sh
The current VTPM implementation saves the TPM content only when the VM halts. THus, taking a checkpoint while the VM is running would not save the corrent TPM state. Block this.
> CA-377169 block VM.checkpoint of running VM with VTPM

- ocaml/libs/ezxenstore/lib_test/main.ml
When developing on a Xen environment test fails when not running on root, this change circumvents the test when the user does not have access to Xenstore.
> Check if user if root before continuing with test

- ocaml/libs/http-lib/dune
- ocaml/libs/http-lib/http.ml
- ocaml/libs/http-lib/http.mli
- ocaml/libs/http-lib/http_svr.ml
- ocaml/libs/http-lib/xmlrpc_client.ml
- ocaml/libs/http-lib/xmlrpc_client.mli
- ocaml/xapi/context.ml
- ocaml/xapi/context.mli
- ocaml/xapi/dbsync.ml
- ocaml/xapi/helpers.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/startup.ml
- ocaml/xapi/system_domains.ml
- ocaml/xapi/taskHelper.ml
- ocaml/xapi/xapi.ml
- ocaml/xapi/xapi_pif.ml
- ocaml/xapi/xapi_pif.mli
- ocaml/xapi/xapi_pool.ml
Following the Library and Management API, Instrumenting Xapi to create and finish spans while completing tasks. Xapi will also send a `traceparent` header as defined by the W3C context specification. This will allow for spans to be tracked across multiple hosts.
The start up sequence has also be reorganised to link startup tasks into one trace to better identify performance issues surrounding at (Only after networks are up)
This code will include the pr-2 content so only focus on the last 4 commits
> Tracing Instrumentation in Xapi

- scripts/nbd_client_manager.py
Noticed this in a test which had failed for other reasons and then wouldn't unplug the datapath. If the device is not found there is nothing to disconnect.
> Make NBD disconnect robust to the device being gone

- ocaml/idl/datamodel_errors.ml
- ocaml/xapi-consts/api_errors.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_vgpu_type.ml
- ocaml/xapi/xapi_vm_helpers.ml
- ocaml/xapi/xapi_vm_migrate.ml
_This PR will not be merged until xs9 is ready, 
Please just help to review this PR and approve if you are happy, we will merge it later._
Edit: This PR is updated to make gvt-g support configurable, so it can be merged to master as early as possible, 
The legacy code can be removed later at proper time.
> CP-43131: Make gvt-g support configurable

- ocaml/xapi/xapi_host_helpers.ml
The SM code is supposed to create /var/lock/sm/iscsiadm but it can fail to do that before we call /opt/xensource/libexec/set-iscsi-initiator. To reduce the dependency on the SM change, create this directory if necessary. This facilitates bacporting this change by reducing the dependency on SM backports to fix this.
> CA-333441, CA-377454 create /var/lock/sm/iscsiadm

- ocaml/libs/log/debug.ml
- ocaml/libs/log/debug.mli
- ocaml/xapi/server_helpers.ml
- ocaml/xapi/session_check.ml
- ocaml/xapi/xapi_http.ml
Currently, if a session check fails and a SESSION_INVALID error is raised, the message "Session check failed: missing reference; tbl = session, ref = XX" plus a full strack trace is written to the logs. The stack trace is usually from session_check.ml and looks the same each time.
These logs are not very interesting, but unfortunately attact the attention of people triaging issue by browsing the logs. Because the SESSION_INVALID lines in xapi's logs look so worrying, they often make people suspect bugs in xapi. However, the errors just mean that a client has used an illegal or (more often) expired session. These logs are especially common when the coordinator xapi is restarted and all old sessions are automatically removed.
This patch improves logging of session errors by putting the …
> Make session errors look less scary in the logs

- ocaml/networkd/bin/network_server.ml
- ocaml/networkd/bin/networkd.ml
- ocaml/xapi-idl/network/network_interface.ml
- ocaml/xapi/helpers.ml
Read the default route for IPv6 and set it in the PIF
> Set PIF's IPv6 Gateway when in DHCP/Autconf

- ocaml/tapctl/tapctl.ml
- ocaml/tapctl/tapctl.mli
- ocaml/vhd-tool/src/image.ml
For disks that are backed by NBD rather than a blktap2 device, an update to sparse_dd is needed to be able to send a VHD difference disk when copying a VDI with respect to a base VDI. This will also be required for storage migration.
It is not feasible (efficient) to look at just the NBD exports of the two VDIs to determine the differences. The proper way to do this is to add functionality to the SMAPI to obtain the differences between two VDIs. We will look at this for SMAPIv3 a little later.
In the short term, we'll get sparse_dd to look at the VHD files behind the scenes. This is how it currently works for the blktap2 devices as well, where sparse_dd finds the VHD file from the minor number of the kernel block device.
The NBD server path exposed by tapdisk has its pid and the minor …
> CP-43387: Fix VDI delta copy with NBD datapath connection

- ocaml/xapi/xapi_vlan.ml
The issue to be fixed in this commit is that when a host joins a pool in which the management network is on a VLAN network, the new untagged PIF of the joined host shows disconnected always.
Normally, the VLAN untagged PIF should share PIF_metrics with the tagged PIF so that the PIF_metrics could be updated correctly. This sharing is ensured by 'Xapi_vlan.create'. While in pool.join, the untagged PIF is created by 'Xapi_pif.pool_introduce', in which the 'metrics' of the new untagged PIF doesn't share with the tagged PIF. This causes the 'carrier' of 'metrics' of the new untagged PIF be 'false' forever. And consequenctly the management network shows disconnected always.
Can't switch to use 'Xapi_vlan.create' simply to fix this issue as the call can't set the "management" field of the …
> CA-376879: VLAN PIF created in pool.join is shown as disconnected

- ocaml/libs/tracing/tracing.ml
- ocaml/libs/tracing/tracing.mli
- ocaml/tests/test_tracing.ml
- ocaml/xapi/context.ml
- ocaml/xapi/helpers.ml
- ocaml/xapi/xapi_observer.ml
- ocaml/xapi/xapi_pool.ml
- ocaml/xapi/xapi_vm_migrate.ml
- ocaml/xenopsd/lib/xenops_server.ml
- ocaml/xenopsd/lib/xenops_task.ml
- ocaml/xenopsd/lib/xenopsd.ml
General improvements to the library and instrumentation to improve performance, functionality and closeness to OTEL specification
1. Add error attribute to identify to UIs like jaeger that a span has an error contained
2. Ensure all uri endpoints passed to the API have a valid scheme and host
3. The `make_remote_rpc` in helpers.ml is given `__context` to it can send tracing information
4. Remove unneeded fields from tracer providers
5. Move `service_name` from `TracerProvider` into a library wide constant for a component
6.  Add SpanLink
7.  Add SpanEvent
8. Use w3c Format for sending tracing to Xenopsd
Commit messages need to be cleaned
> General improvements for Tracing

- ocaml/idl/datamodel_errors.ml
- ocaml/xapi-consts/api_errors.ml
- ocaml/xapi/repository.ml
For repository-based updates, the information of available updates on every host is stored in a cache (in memory) in XAPI process on coordinator. This cache aims to make the HTTP GET /updates requests responded quickly as a fast path. One drawback of this design is that the cache would be flushed when toolstack on coordinator restarted. As part of original design, if this happens, an error 'UPDATES_REQUIRE_SYNC' will be raised to clients so that HTTP-based users would get quick responses in all cases.
This commit aims to fill the cache again (but taking longer time) automatically instead of raising error 'UPDATES_REQUIRE_SYNC' when the cache has been flushed. This will simplify the XAPI call flow from client's perspective.
> CA-375147: UPDATES_REQUIRE_SYNC when toolstack restarted on coordinator

- ocaml/libs/tracing/tracing.ml
- ocaml/libs/tracing/tracing.mli
- ocaml/xapi-idl/xen/xenops_interface.ml
- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_observer.ml
- ocaml/xapi/xapi_xenops.ml
- ocaml/xenopsd/lib/xenops_server.ml
Instead of writing a new file for every trace we export, write into files split into 1mb batches. This will save disk space as the number of files will be drastically reduced.
> Write bugtool exports in batches

- ocaml/libs/tracing/tracing.ml
- ocaml/libs/tracing/tracing.mli
- ocaml/tests/test_observer.ml
Given concerns that exporting over http was being slow, this pull request will create spans that measure how performant the Export functions are.
> Trace Export functions to monitor performance 

- ocaml/database/redo_log.ml
- ocaml/database/redo_log.mli
- ocaml/xapi-guard/lib/varstored_interface.ml
- ocaml/xapi-guard/src/dune
- ocaml/xapi-guard/src/main.ml
- ocaml/xapi-guard/test/xapi_guard_test.ml
- ocaml/xapi-idl/varstore/privileged/dune
- ocaml/xapi-idl/varstore/privileged/varstore_privileged_interface.ml
- ocaml/xapi-idl/varstore/privileged/xapiguard_cli.ml
- ocaml/xapi/xapi_pool.ml
- ocaml/xapi/xapi_sr.ml
- ocaml/xapi/xha_metadata_vdi.ml
- ocaml/xenopsd/lib/xenops_sandbox.ml
- ocaml/xenopsd/lib/xenops_sandbox.mli
- ocaml/xenopsd/scripts/swtpm-wrapper
- ocaml/xenopsd/xc/device.ml
- ocaml/xenopsd/xc/device.mli
- ocaml/xenopsd/xc/domain.ml
- ocaml/xenopsd/xc/domain.mli
- ocaml/xenopsd/xc/service.ml
- ocaml/xenopsd/xc/service.mli
- ocaml/xenopsd/xc/xenops_server_xen.ml
- scripts/vtpm_smoke_test.sh
TODO:
* plumb creation of new socket through to 'make_server_vtpm_rest'
* add new enum for new storage backend in addition to xapi (maybe call it xapi2?), the serialization is different and incompatible (unless swtpm would implement a linear op instead of the current per-entry ops, but per-entry seems more robust)
* bring back the tests, but this time just test basic operations/scalability, not correctness in a distributed system (we won't have a distributed system anymore, we'll rely on shared storage to solve that problem)
> Minimal swtpm REST API

- ocaml/xapi-idl/lib_test/test_data/v6/responses/get_version.response.0
- ocaml/xapi-idl/v6/v6_interface.ml
- ocaml/xapi/create_misc.ml
This commit adds a new field "preview" in return of v6 interface "get_version".
To achieve this, the change has to extend the return type of "get_version" interface so that more version related information could be supported.
> CP-42999: Return new "preview" in return of v6 "get_version"

- ocaml/idl/datamodel_host.ml
- ocaml/idl/datamodel_repository.ml
- ocaml/idl/schematest.ml
- ocaml/tests/common/test_common.ml
- ocaml/xapi-cli-server/record_util.ml
- ocaml/xapi-cli-server/records.ml
- ocaml/xapi/repository.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_pool.ml
In repository-based continuous update, XAPI users/clients would like to know if the versions of software installed on individual hosts are consistent in a CH pool.
The consistency was defined as "a host is running same versions of everything as the coordinator" in hotfix-based discrete update.
Now the consistency is defined as "a host is running same versions of everything as the latest ones known in last pool.sync_updates".
Therefore, a new boolean filed "host.up_to_date" should be added as the indicator.
This field should be set in:
pool.sync_updates, and
host.apply_updates
> CP-40204, CA-366396: Add "host.up_to_date", remove "repository.up_to_date"

- ocaml/idl/datamodel_common.ml
This is needed to fix a XAPI startup error after the database schema has been changed.
Fixes: 604cfbd58 ("CP-41842 Created Observer class with IDL functions to manage Open Telemetry providers")
> Tracing: bump database schema

- ocaml/xapi/xapi_pool.ml
When the coordinator in a pool changes the package metadata cache is not transferred from the previous coordinator to the new one. This means the field pool.last_update_sync becomes out of sync with the new state.
Fix this by resetting the field on pool coordinator change
> CA-376145: Reset pool.last_update_sync on pool coordinator change

- ocaml/database/master_connection.ml
- ocaml/xapi-idl/lib/scheduler.mli
- ocaml/xapi/xapi_pool.ml
This commit is to fix an issue which may be hit when the pool coordinator is rebooting or its XAPI is restarting.
In either of the cases, other pool members keep trying to connect to the coordinator for DB connections. This connecting holds the DB lock until a timer expired. And the timer uses exponential backoff to avoid overload the coordinator. The maximum of the timer is 256 seconds.
Meanwhile in starting up, the XAPI in coordinator will issue XAPI call pool.is_slave to every pool member. This call on every pool member will try to acquire the DB lock as well and hence be blocked by the re-connecting mentioned above. In the worst case, the start-up of XAPI would be delayed up to more than 4 minutes (256 seconds).
The idea of this commit is that since the pool.is_slave is issued from …
> CA-354436: pool.is_slave took a long time to respond

- ocaml/sdk-gen/csharp/autogen/src/JsonRpc.cs
- ocaml/sdk-gen/csharp/autogen/src/Session.cs
Please review each commit separately.
Regarding the 3rd commit: .NET has a global property which allows specifying a certificate validation handler for use with the server requests. Because this is a client wide setting, it does not allow for much flexibility if the client wants to connect to various types of hypervisors and implement different certificate validation logic for each one, therefore this PR exposes it in the SDK so the client can customize the global setting for XenServer sessions.
Regarding the 4th commit: Since the beginning of the C# SDK's life, we have exposed a few properties of the web requests at the Session class level so the implementing client can override the defaults. Timeout was the very first one, but at the time it had not been exposed as a Property but as a …
> CP-43400: Expose ServerCertificateValidationCallback in the Session. Also, deprecated some of the Session constructors.

- scripts/xapi-tracing-log-trim.sh
When no observer is enabled, by default /var/log/dt is not present. In this situation, when cron runs xapi-tracing-log-trim.sh, the find commands will write to stderr ending up in dead.letter files:
find: ‘/var/log/dt’: No such file or directory
After this patch, the script will:
- skip the find operations using /var/log/dt if this path is not present,
- and use an internal DTPATH var to refer to this path instead of repeating it across many places.
Behaviour when /var/log/dt is present was maintained.
> CA-378323: prevent find writing to stderr if /var/log/dt not present

- ocaml/xenopsd/lib/suspend_image.ml
- ocaml/xenopsd/lib/suspend_image.mli
- ocaml/xenopsd/suspend_image_viewer/suspend_image_viewer.ml
- ocaml/xenopsd/xc/domain.ml
When migrating from earlier xapi releases, the migration block was not base64-encoded while newer versions assume the migration block is. Introduce a new migration block so from this version can tell when to base64-encode the contents for migration contents and when to leave the contents alone.
Drafting until the fix is manually verified
> CA-378455: Ensure TPM contents are base64-encoded on migration recieve

- ocaml/xcp-rrdd/bin/rrdd/rrdd_server.ml
- ocaml/xcp-rrdd/bin/rrdd/rrdd_server.mli
- ocaml/xcp-rrdd/bin/rrdd/xcp_rrdd.ml
- Dump all latest data of host dss to file in json format so that any client can read even if it's non-privileged user, such as NRPE.
Test passed, see CP-43551 to get details.
> CP-43551: Dump host_rrd latest data to /dev/shm/metrics/host-dss

- .github/workflows/main.yml
- ocaml/xapi/xapi_host.ml
Host.get_vms_which_prevent_evacuation is used by XenCenter as part of a rolling pool upgrade. But when it fails we are missing information in the logs about VMs that block evacuation of a host. Add logging.
> CA-378837 log results from Host.get_vms_which_prevent_evacuation

- ocaml/message-switch/python/message_switch.py
- ocaml/xapi-idl/designs/interprocesscomms.md
- ocaml/xapi-storage/python/xapi/__init__.py
- ocaml/xapi-storage/python/xapi/storage/api/datapath.py
- ocaml/xapi-storage/python/xapi/storage/api/plugin.py
- ocaml/xapi-storage/python/xapi/storage/api/volume.py
- Remove optional parentheses for "raise (...AnyException..)))":
```ml
sed -i '/raise (/s/)$//  ;  s/raise (/raise /' $(find ocaml -name *.py
```
Also updates these in with the same change:
- ocaml/message-switch/python/message_switch.py
- ocaml/xapi-idl/designs/interprocesscomms.md
> CP-40214: **/*.py: raise (AnyException()): Remove optional parentheses

- ocaml/xapi/repository.ml
In the update applying process, "EvacuateHost" will be applied before applying updates.
> CA-378757: remove "EvacuateHost" from recommended guidance

- ocaml/tests/test_repository_helpers.ml
- ocaml/tests/test_updateinfo.ml
- ocaml/xapi/updateinfo.ml
- ocaml/xapi/updateinfo.mli
Expose the `issued` and `severity` fields from updateinfo on host http endpoint: /updates.
> CP-43545: expose `issued` and `severity` from updateinfo

- .gitignore
- ocaml/xapi-storage/python/examples/datapath/loop+blkback/datapath.py
- ocaml/xapi-storage/python/examples/datapath/loop+blkback/plugin.py
- ocaml/xapi-storage/python/examples/volume/org.xen.xapi.storage.simple-file/plugin.py
- ocaml/xapi-storage/python/examples/volume/org.xen.xapi.storage.simple-file/sr.py
- ocaml/xapi-storage/python/examples/volume/org.xen.xapi.storage.simple-file/volume.py
- ocaml/xapi-storage/python/xapi/__init__.py
- ocaml/xapi-storage/python/xapi/storage/api/datapath.py
- ocaml/xapi-storage/python/xapi/storage/api/plugin.py
- ocaml/xapi-storage/python/xapi/storage/api/volume.py
Reviewed by me(@bernhardkaindl):
Migrate `xapi-storage` Python code to Python3: __Initial part of step 1__:
In order for a clear and easy review, this commit adds only two fixes:
```ml
modernize -wf except,print $(find ocaml/xapi-storage/xapi -name *.py)
```
This `modernize` makes these changes:
- `except Exception, e` to: `except Exception as e`
- Updates print() with `from __future__ import print_function`, for forcing Python2 to `raise SyntaxError` on Python2 `print` (the import of print_function could be omitted without problem)
> ocaml/xapi-storage/python/xapi/**.py: modernize -f except,print

- scripts/gencert.service
An internal test case flags that the host fingerprint is not being found by the testcase. 
The update is done by the script `update_getty`, however if the certificate is not generated then this process will not run properly. This change runs this script at the end of gencert starting.
> CA-373074 Fix Fingerprint not writing on boot 

- .github/workflows/main.yml
- Makefile
- ocaml/alerts/certificate/certificate_check.ml
- ocaml/alerts/certificate/certificate_check.mli
- ocaml/alerts/certificate/dune
- ocaml/alerts/dune
- ocaml/alerts/expiry_alert.ml
- ocaml/alerts/expiry_alert.mli
- ocaml/tests/alerts/test_alert_certificate_check.ml
- ocaml/tests/alerts/test_expiry_alert.ml
- ocaml/tests/alerts/test_suite.ml
- quality-gate.sh
- xapi-expiry-alerts.opam
This PR follows @psafont 's advise: https://github.com/xapi-project/xs-opam/pull/647#issuecomment-1618430105, after these "xapi-expiry-alerts" related changes merged into master, we can then merge https://github.com/xapi-project/xs-opam/pull/647 and use the library in proprietary daemons
The first 2 commits are cherry-picked from branch: [xapi-project:feature/stream-updates](https://github.com/xapi-project/xen-api/tree/feature/stream-updates), related PRs: https://github.com/xapi-project/xen-api/pull/5060 and https://github.com/xapi-project/xen-api/pull/5085
> Add xapi-expiry-alerts

- scripts/usb_reset.py
The mount system call takes a fifth "data" parameter but the code doesn't pass anything so the kernel gets garbage. Newer kernels are more strict than older ones and it causes the call to fail with EINVAL so pass None for the data parameter.
> CA-378931: usb_reset: Fix mount call parameters

- .github/workflows/main.yml
- scripts/plugins/extauth-hook-AD.py
- Re-enable Python 2.7 CI using tiny docker containers(very fast)
- [scripts/plugins/extauth-hook-AD.py](https://github.com/xapi-project/xen-api/blob/master/scripts/plugins/extauth-hook-AD.py) has a main function, but it's [setup_logger()](https://github.com/xapi-project/xen-api/blob/master/scripts/plugins/extauth-hook-AD.py#L38) runs during import, which breaks importing it in tests in containers not providing /dev/log. Call setup_logger() only if the module is started as a script.
> scripts/plugins/extauth-hook-AD.py: Skip init logging on import

- ocaml/idl/datamodel_errors.ml
- ocaml/xapi-consts/api_errors.ml
- ocaml/xapi/xapi_host.ml
This reverts commit d2290d419f0ecdca28d2c35ca2169a4ca1197a61.
Instead of blocking pool member update process, there is a better solution: during xapi's startup on pool member, check the coordinator's xapi version in the "master connection", and block if the coordinator has a lower version.
This revert commit removes the blocking during pool member update, will try to have a fix following the new solution later.
> Revert "CP-42787: Ensure correct pool update sequence"

- ocaml/xapi-consts/api_messages.ml
This reverts commit 3492322842a7c3eb33f05b8c29d86caf1f350312.
Will define CSS expiry related alerts in v6d, not in xapi.
> Revert "CP-42019: Add messages for updates feature expiry. (#5002)"

- ocaml/alerts/certificate/certificate_check.ml
- ocaml/alerts/expiry_alert.ml
As the suggested wording from Katherine are:
"Your Customer Success Services (CSS) agreement is expiring soon."
and "Your Customer Success Services (CSS) agreement has expired.",
remove the leading "The".
> CP-42019: Update wording for expiry message

- ocaml/xcp-rrdd/bin/rrdd/xcp_rrdd.ml
- ocaml/xcp-rrdd/lib/rrdd/constants.ml
- ocaml/xcp-rrdd/lib/rrdd/dune
- xapi-rrdd.opam
It causes logspam to have the file there
Also replaces a hardcoded version in the HTTP requests xcp-rdd sends with the actual version
> CA-379929: move json dump out of the rrdd plugin directory

- ocaml/xenopsd/lib/xenops_sandbox.ml
This commit broke secure boot on vm resume: first the sandbox was created to place a file, then when the varstored was about to start the sandbox was deleted and recreated, losing the file along with the important data.
This reverts commit eb00bc984d0c79a1bf18334bb330205fc2427b78.
> Revert "CA-375992: clean up previous sandbox when creating one"

- ocaml/xapi/repository.ml
- ocaml/xapi/repository_helpers.ml
When there remains 'recommended_guidances' or 'pending_guidances' from previous update not applied for a host, the 'recommended_guidances' and 'pending_guidances' are not calculated correctly: the previous guidance should be taken into account to calculate the new 'recommended_guidances' and 'pending_guidances'.
> CA-378778: Calculate host guidance correctly

- .github/workflows/main.yml
- forkexec.opam
- http-lib.opam
- message-switch-async.opam
- message-switch-cli.opam
- message-switch-core.opam
- message-switch-lwt.opam
- message-switch-unix.opam
- message-switch.opam
- rrd2csv.opam
- rrdd-plugin.opam
- rrdd-plugins.opam
- xapi-forkexecd.opam
- xapi-idl.opam
- xapi-nbd.opam
- xapi-networkd.opam
- xapi-open-uri.opam
- xapi-rrdd-plugin.opam
- xapi-rrdd.opam
- xapi-squeezed.opam
- xapi-storage-script.opam
- xapi-storage.opam
- xapi-tracing.opam
- xapi-xenopsd.opam
- xapi.opam
- xen-api-client.opam
- xen-api-sdk.opam
Changes some download links to stop using the git protocol, updates some dependencies on new libraries and changes the conf-python dependency to depend on python 3
Also changes the ocaml setup action to v2, as this is the one that's maintained and should give less problems than the v1 that's in use currently
> fix CI, opam: sync with latest metadata; use ocaml setup v2

- ocaml/xapi/repository.ml
This fixes an issue introduced in 47bfe89e:
CA-378778: Calculate host guidance correctly
where the "recommended_guidances" was set into "pending_guidances" by mistake.
> CA-380043: VM recommended guidances is not set correctly

- ocaml/libs/http-lib/dune
otherwise opam will try to run these on unrelated packages, this fixes the CI in xs-opam
> http-lib: make all tests belong to the package

- ocaml/xapi/redo_log_usage.ml
Recovery from redolog is critical for the correct operation of XAPI (with HA or with the redolog enabled). Do not hide these messages by default: redo_log_usage should have its own log prefix (redo_log is disabled by default).
Also do not eat exceptions: instead use log and ignore. This preserves the previous behaviour where we allow XAPI to start up even if redo log recovery fails (with possibly an older an incorrect database).
> CA-379928: enable more logging for redo_log_usage

- .github/workflows/main.yml
By adding the commit hash into the configure, the dune cache is invalidated. Use the same dummy version always to try to reuse as much of the cache as possible.
For comparison on a scheduled run, it took 6m to install dependencies, 21s to build xapi, then 26s to test it.
On a PR based on it, it took 4 m to build the dependencies, 2m 30s to build xapi, then 3m 30s to test it.
Hopefully with this change the build and test times can be reduced as well.
> ci: try to reuse dune cache as much as possible

- scripts/xe-toolstack-restart
Stopping xapi appears to take a long time for something to time out if other services have stopped before it. The assumption in xe-toolstack-restart seems to be that `systemctl stop` with multiple service names on the same command line respects the `After:` constraints of the services, but I am not convinced it does. Explicitly stopping xapi first and starting it after everything else has started, makes the whole script execute about a minute faster.
> CA-377945: toolstack restart: ensure xapi is stopped first, started last

- ocaml/xapi/cpuid_helpers.ml
- ocaml/xapi/cpuid_helpers.mli
- ocaml/xapi/export.ml
- ocaml/xapi/import.ml
- ocaml/xapi/importexport.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_dr.ml
- ocaml/xapi/xapi_vm.ml
- ocaml/xapi/xapi_vm_helpers.ml
- ocaml/xapi/xapi_vm_migrate.ml
This required adding VM_metrics to the metadata export/import.
> Cross-pool live migration: move CPU check to the target host

- ocaml/xenopsd/c_stubs/xenctrlext_stubs.c
- ocaml/xenopsd/xc/xenctrlext.ml
- ocaml/xenopsd/xc/xenctrlext.mli
- ocaml/xenopsd/xc/xenops_server_xen.ml
In order to support MSR_ARCH_CAPS, combining policlies becomes more complicated than a simple intersection.  More generally, it is more conviencient to have all levelling/compatibility logic in a single codebase to avoid needing linked changes in Xapi.
Where possible, offload the decisions into Xen.
> Offload VM CPU Policy checks to Xen

- .github/workflows/1.249-lcm.yml
- .github/workflows/docs.yml
- .github/workflows/format.yml
The documentation push failed because the ubuntu repos are not up-to-date in the ubuntu image used in the CI, work around this on all the remaining workflows.
Also update base image and actions, use the latest available. There's no need to pin any packages when checking the format, so skip that step
> ci: work around outdated ubuntu repositories on all workflows

- ocaml/xapi/xapi_vm_migrate.ml
CPU checks are needed only for running VMs that are being migrated, to check for compatibility with the remote-host's CPUs.
> CA-380580: cross-pool migration: no CPU checks for halted VMs

- ocaml/idl/datamodel_types.ml
The API version of the 8.2/Stockholm release was 2.15. Any updates to it should keep the same API version, to avoid compatibility problems with clients.
> Leave the API version for Yangtze/hotfixes as 2.15

- ocaml/database/redo_log.ml
Xapi starts block_device_io and connects to it by trying; let's observe the timing of this because it appears that it is giving up too soon in some cases.
> CA-379472 more redo_log debugging

- scripts/init.d-xapi
When a host crashes, chroots in /var/lib/xcp/run remain. Their names use the domain counter, which resets on reboot. This risks name collisions between a new chroot and an existing old one. After reboot we can be sure that no domain is running and that it is safe to remove stale chroots.
> CA-375992 remove stale swtpm chroots after boot

- ocaml/xapi/xapi_vm_snapshot.ml
- ocaml/xapi/xapi_xenops.ml
- ocaml/xenopsd/lib/xenops_server.ml
- ocaml/xenopsd/lib/xenops_utils.ml
- ocaml/xenopsd/xc/device.ml
- ocaml/xenopsd/xc/xenops_helpers.ml
- ocaml/xenopsd/xc/xenops_server_xen.ml
When creating a domain from an snapshot, the UUID of the vTPM as used by xapi
is changed as a new vTPM object is used.
Diagram of introduced behavior and in which cases these happen with analysis
below, it's assumed that xapi updates xenops metadata before doing any
lifecycle VM operation so the second column is always up-to-date with the
current xapi model.
<table>
<tr>
<td>
<td>extra vtpm
<td>VM vtpm
<td>result
<tr>
<td>1.
<td>None
<td>None
<td>None
<tr>
<td>2.
<td>None
<td>Some a
<td>Some a
<tr>
<td>3.
<td>Some a
<td>None
<td>Some a
<tr>
<td>4.
<td>Some a
<td>Some b
<td>Some b
<tr>
<td>5.
<td>Some a
<td>Some a
<td>Some a
</table>
1. Normal case when vtpm is unplugged, OK
2. This case happens in case of a xapi error, where it allowed hotplugging a
vtpm device into a snapshot. Same with …
> CA-379350: Use up-to-date vTPM UUIDs when creating device models

- ocaml/quicktest/qt_filter.ml
- ocaml/quicktest/quicktest_args.ml
- New `-sr` option which takes a SR uuid to run the tests on the option is mutually exclusive with `-default-sr`
- If the SR provided is not available on the host, fails
> Allow a user to select on which SR to run quicktest

- ocaml/quicktest/quicktest_cbt.ml
- ocaml/quicktest/quicktest_vdi.ml
These tests call at some point `VDI.update` so
the VDIs not supporting it should be filtered out.
> Add `vdi_update` filter to some tests

- ocaml/database/block_device_io.ml
- ocaml/database/db_globs.ml
- ocaml/xapi/xha_statefile.ml
The debug log level is disabled by default. Since we are strugglign to understand why this process is slow to startup or other reasons why xapi fails to connect to its socket, let's elevate more logging to the info level. We want to avoid logging the regular case where data is transferred but are interested in the setup and teardown case.
> CA-379472 log more block_device_io messages to info

- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_sr.ml
We have a race condition: PDB.plug updates the xapi database in a separate thread. This means the information there is accurate only after PBD.plug returns. In this case, the information about available space could be misleading before it is silently corrected. To avoid this, make this update synchronous.
> CA-379112 make PBD.plug wait for scan results 

- ocaml/xapi/xapi_vm_migrate.ml
This commit is to fix an issue which was introduced by 3d039f3. In VM migration, the suspend_vdis will be get from snapshots the power_state of which is `Suspended. The individual snapshots are represented as VM records in XAPI as well. They are different with the base VM record.
This commit reverts this part to the logic prior to 3d039f3.
> CA-380789: Not get power_state from snapshots with suspend VDIs

- ocaml/idl/datamodel_errors.ml
- ocaml/xapi-consts/api_errors.ml
- ocaml/xapi/repository.ml
- ocaml/xapi/repository.mli
- ocaml/xapi/xapi_pool.ml
The 'reposync_mutex' was designed for cases in which a pool is downloading updates from remote repos, but another XAPI call is being carried on to apply updates simultaneously. The assumption of this design is that the downloading may take long time. During this period, it would be nice to allow other operations, e.g get_updates, or apply_updates, etc.
The issue to be fixed in this commit is that the locked status of 'reposync_mutex' can't be populated to clients since the status of the lock is not recorded in XAPI DB.
Additionally, with 80c8153860, only the minimum set of update packages will be downloaded. The assumption above now doesn't hold anymore in most cases.
The 'pool.allowed_operations' now can take the chance to replace 'reposync_mutex' to protect consistency among repo …
> CA-380581: Remove lock on downloading updates from remote repos

- ocaml/xapi/cpuid_helpers.ml
- ocaml/xapi/cpuid_helpers.mli
- ocaml/xapi/export.ml
- ocaml/xapi/import.ml
- ocaml/xapi/importexport.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_dr.ml
- ocaml/xapi/xapi_vm.ml
- ocaml/xapi/xapi_vm_helpers.ml
- ocaml/xapi/xapi_vm_migrate.ml
We see some errors in the context of snapshots that we need to investigate.
> Revert "Cross-pool live migration: move CPU check to the target host"

- ocaml/xenopsd/scripts/qemu-wrapper
QEMU has a file size limit to prevent denial of service attacks. However with the introduction of vTPM the vTPM state is now saved in the qemu device stream. If the vTPM happens to have a lot of data then the quota is hit, qemu returns an error, the migration fails and XAPI kills the original VM.
(Same bug happens if we were trying to take a checkpoint, the VM ends up dead).
Fixing that would require fast resume, which we don't have, however the file size limit needs to be updated. Don't try to be too tight on the size, the vTPM may be a max of 256KiB, so increasing this to 512KiB should work, but to be safe double that to 1MiB.
> CA-381503: bump qemu filesize limit

- ocaml/quicktest/quicktest_vdi_copy.ml
- ocaml/tests/test_vdi_cbt.ml
- ocaml/xapi-idl/lib/scheduler.ml
- ocaml/xapi-idl/lib/scheduler.mli
- ocaml/xapi/storage_migrate.ml
- ocaml/xapi/xapi_periodic_scheduler.ml
- ocaml/xapi/xapi_udhcpd.ml
- ocaml/xapi/xapi_vdi.ml
- ocaml/xapi/xapi_vdi.mli
- ocaml/xcp-rrdd/bin/rrdp-iostat/rrdp_iostat.ml
- ocaml/xen-api-client/lib_test/dune
- ocaml/xenopsd/lib/xenopsd.ml
- ocaml/xenopsd/xc/service.ml
- ocaml/xxhash/stubs/dune
- rrd-transport.opam
- wsproxy.opam
- xapi-rrdd.opam
- xapi-storage.opam
- xapi-xenopsd-xc.opam
- xen-api-client-async.opam
- xen-api-client-lwt.opam
- xen-api-client.opam
In particular:
- add dependency to ctypes.stubs to use its new dune-compiled version
- replace ounit with ounit2
- remove usages of Mtime.Span.to_s: avoid conversion to float if possible by comparing timespans, or use manual conversion to seconds in floats, taking care to remove as little precision as possible (floats become imprecise for periods longer than 54 years). The latter is needed when there are interfaces using the float seconds, which are difficult to change because they are outside our control, or they introduce backwards-compatibility headaches.
I've been working on a bigger code change for adopting monotonic timers across the board, but I'd like to get some functions upstreamed to Mtime before that to make the comparisons easier to understand.
> maintenance: prepare code for newer versions of libraries

- ocaml/networkd/bin/network_monitor_thread.ml
- ocaml/xapi-aux/dune
- ocaml/xapi-aux/networking_info.ml
- ocaml/xapi/xapi_session.ml
Currently only address changes are detected, but state changes are needed
because MTU changes make the state of the link to change.
Not detecting this situation makes xapi hang at boot in certain scenarios.
> CA-378966: Detect state network interface changes

- ocaml/tests/test_updateinfo.ml
- ocaml/xapi/updateinfo.ml
In this way, future new added guidance can be covered by the max
guidance: RebootHost.
> CP-43977: Fallback un-recognized guidance as RebootHost

- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_gpumon.ml
Behind a feature flag: use attach/detach of the NVML library and keep gpumon running rather than shutting it down. This generally works, but:
* found problems with some cards when setting up SRIOV
* both xapi and xenopsd may call a /usr/lib/nvidia/sriov-manage which by itself shuts down gpumon. The code could be patched to use gpumon-cli instead.
Moving the code into xapi can help us to develop this further and also to share it with Nvidia.
> CP-33044 replace gpumon shutdown with NVML detach/attach

- Makefile
CP-44271: Remove python build/install from source code
This part should be removed to spec file, so it can be handled
properly basing on python2/python3
CP-44271: Conditionally run python test
The python test for xapi-storage should only be run under python2
environment, as it is in python2
> Update for python3 build

- ocaml/database/redo_log.ml
We have seen "Redo_log.RedoLogFailure("Cannot connect to redo log")" and it mostly stems from threads interfering. The redo_log module was not designed with thread-safety in mind. This path greatly reduces the problem. We might want to study the problem more closely but I would suggest to take this patch to make the problem smaller.
The key ingredient is taking the database lock before opening the redo log flushing the database to the redo_log. This blocks other operations.
> Improve redo_log

- message-switch.opam
Currently it's also compatible with mtime 2.x
> maintenance: relax message-switch's bounds on mtime

- Makefile
- ocaml/xenopsd/suspend_image_viewer/dune
- ocaml/xenopsd/suspend_image_viewer/view.sh
This is useful for debugging. It cannot be easily run out of Dom0 due to its dependency on verify-stream-v2 provided by Xen.
Also if it is not installed in Dom0 then it is bitrotting and not being tested, so when we need it then we realise it is broken.
Note that `verify-stream-v2` is currently bitrotted and its shebang needs to be edited to python2 to make it work.
Can be used like this:
```
/opt/xensource/debug/with-vdi de9bd384-b866-42b6-a8a0-b4f03a23c0fe
./suspend_image_viewer.exe --path /dev/$DEVICE --verify-stream-v2=/usr/libexec/xen/bin/verify-stream-v2
```
(This will require a specfile update when merged)
> Install suspend_image_viewer

- ocaml/xapi/xapi_vlan.ml
- ocaml/xapi/xapi_vm_migrate.ml
- scripts/bugtool-plugin/xapi/stuff.xml
```
* 7b0a03793 2023-09-19 CA-374989: Avoid using get_record on cross-pool migration
* 1950c7367 2023-09-19 CA-376879: VLAN PIF created in pool.join is shown as di..
```
Please remind me if any of this requires changes in spec files - this is easy to miss.
> Yangtze Backports

- ocaml/xenopsd/scripts/qemu-wrapper
Currently, getting debug messages out of OVMF requires (amongst other things) editing the qemu-wrapper script to enable the debug port. This is inconvenient. Fix this by simply always enabling it. With the current OVMF, this results in no change in the default behaviour since the release build of OVMF does not log anything though that is expected to change in the near future.
> CP-45175: Enable the OVMF debugging port by default

- ocaml/libs/vhd/vhd_format_lwt_test/parse_test.ml
- ocaml/libs/vhd/vhd_format_lwt_test/patterns_lwt.ml
`du -csh /tmp/*.vhd` has shown about 1.3GB of files, and this also caused the readonly unit test to fail:
```
[pid 1698168] openat(AT_FDCWD, "/tmp/parse_test.1.vhd", O_RDWR|O_CREAT|O_TRUNC, 0644) = -1 EACCES (Permission denied)
(* Check we respect RO-ness *)
let check_readonly () =
let filename = make_new_filename () in
Vhd_IO.create_dynamic ~filename ~size:0L () >>= fun vhd ->
Vhd_IO.close vhd >>= fun () ->
Unix.chmod filename 0o444 ;
Vhd_IO.openchain filename false >>= fun vhd -> Vhd_IO.close vhd
```
> Clean up after unit test: don't leave gigabytes of files in /tmp

- .github/workflows/hugo.yml
- doc/go.mod
- doc/hugo.toml
This Github Action publishes the new Hugo-based docs from /doc to a temporary staging area at https://xapi-project.github.io/new-docs/. Eventually, this will replace the old docs on https://xapi-project.github.io. However, we are still transferring docs to the new world, which we do incrementally so that it all can be updated and reviewed again.
> Publish new Hugo-based docs

- scripts/Makefile
- scripts/bugtool-plugin/observer.xml
- scripts/bugtool-plugin/observer/stuff.xml
- scripts/bugtool-plugin/xapi/stuff.xml
Move the tracing log output to its own capability as it spans more than just xapi. This also allows the max size to be increased without increasing it for all of xapi.
> CA-381047: Add observer capability to bugtool

- ocaml/quicktest/qt_filter.ml
When looking for a random SR in an empty list,
quicktest can call `Random.int 0` which will throw. Instead return an empty list.
Instead of throwing, the test won't be passed as there is no compatible SR.
This can happen when calling quickest with the `-sr` on ISO SR.
> Do not fetch random SR in empty list

- Makefile
- ocaml/xenopsd/lib/bootloader.ml
- ocaml/xenopsd/lib/bootloader.mli
- ocaml/xenopsd/lib/resources.ml
- ocaml/xenopsd/scripts/make-custom-xenopsd.conf
- ocaml/xenopsd/scripts/pygrub-wrapper
- ocaml/xenopsd/xc/xenops_server_xen.ml
pygrub doesn't need all the authority it runs with. Run it in depriv mode
instead so breaking into pygrub doesn't cause privilege escalation.
Signed-off-by: Alejandro Vallejo <alejandro.vallejo@cloud.com>
> CA-383491: Run pygrub in deprivileged mode when invoked from XAPI

- scripts/examples/python/setup.cfg
Both the URL and the author were out of date, changed them both top reference the xapi project
Note: the pypi releases are broken as github stopped allowing to do secure releases on tags (yet). The fix has been promised to arrive next month
> Python's XenAPI: Update metadata

- scripts/xapi.service
Current default jemalloc settings:
```
╭──────────────────────────────────────┬───────────────────────────┬───────────────────────────╮
│name                                  │  minor-allocated          │  monotonic clock/op       │
├──────────────────────────────────────┼───────────────────────────┼───────────────────────────┤
│  concurrent semaphore + sleep fix:1  │            14.4615 mnw/run│          40.7085 ms/op/run│
│  concurrent semaphore + sleep fix:8  │            76.0000 mnw/run│          39.6229 ms/op/run│
╰──────────────────────────────────────┴───────────────────────────┴───────────────────────────╯
```
A flamegraph shows that 'sha512_crypt_r' spends >90% of time in jemalloc and not on hashing.
With 'tcache:true'
``` …
```
> CP-45703: jemalloc: avoid bottlenecks with C threads

- ocaml/tests/common/test_vgpu_common.ml
- ocaml/tests/test_vgpu_type.ml
- ocaml/tests/test_xenopsd_metadata.ml
- ocaml/xapi-idl/xen/xenops_types.ml
- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_vgpu_type.ml
- ocaml/xapi/xapi_xenops.ml
- ocaml/xenopsd/xc/device.ml
NVidia is supporting vGPUs that can run as compute GPU. These are marked in their vgpuConfig.xml with a new class attribute "Compute":
<vgpuType id="307" name="GRID P100C-12C" class="Compute">
We don't parse and use this attribute so far but need to in order to support VCS. This commit extends the parser to recognise the class attribute and to pass it on under the internal name "vclass" to xenopsd. Xenopsd's job is to start device emulators accordingly. Selecting the correct emulators is future work. So far, xenopsd logs the vclass it receives.
Unit tests have been updated.
This commit should have no impact on current functionality, be safe to merge, and lay groundwork for extending xenopsd to support VCS.
> CP-44320 scaffolding for NVidia Virtual Compute Service (VCS)

- ocaml/idl/datamodel_host.ml
- ocaml/xapi-cli-server/cli_operations.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/vm_evacuation.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_host.mli
New optional argument to `Host.evacuate`: `evacuate_batch_size` When provided uses it instead of `xapi.conf`'s `evacuation_batch_size` When not provided uses the `xapi.conf` option
Fixes: https://github.com/xapi-project/xen-api/issues/5202
> Choose size of batch VM evacuation

- ocaml/xcp-rrdd/scripts/rrdd/rrdd.py
Python3 wants the input to crc32 to be byteslike, the content of the metadata should be essentially ascii anyway so encoding as utf-8 should not make any functional difference. Test with python2 as well and the results for a given input are the same with or without the encode.
> CP-40123: encode the dumped JSON in rrdd as utf-8

- scripts/xapi.conf
The current commented value suggests that the default value is true, but the default is actually false.
> xapi.conf: match the default value for override-uefi-certs

- ocaml/sdk-gen/csharp/autogen/src/JsonRpc.cs
- ocaml/sdk-gen/csharp/autogen/src/Session.cs
Some consumers of the Xen SDK may have use cases where they need custom handling of the HTTP requests to be made to the endpoint server. This change will allow the JsonRpc class to be overridden and provide a custom implementation of the PerformPostRequest method.
> Allow SDK Consumers to create a custom implementation for JsonRpcClient

- ocaml/xapi/xapi_message.ml
- ocaml/xapi/xapi_vm_migrate.ml
please be nit picky! 😁
tested using migration of w10 VM between 2 standalone hosts.
______
So while making this change I noticed we only move (and now clear) messages connected to the VM.
We are **not** doing the same for messages connected to other objects (such as VDIs). Is this something we should add?
> CA-365059: Clear messages in source pool after migrating VM

- scripts/Makefile
XS9 does not have python2, the building and installation of python2 stuff should be excluded from XS9
> CP-45938: Fixup xs9 failure due to python2 stuff

- ocaml/libs/vhd/vhd_format/f.ml
To make the progress bar display more interactive, we limit the amount of consecutive sectors to coalesce when generating a list to copy.
> XSI-1457: Limit number of sectors to coalesce

- ocaml/database/db_cache.ml
When loading a database from disk in XML, fields that are marked in the datamodel as removed are ignored and not written to the in-memory database. Because some fields that have been marked as removed are still written to, like host metrics' free memory, they might still be tried to be replayed and they fail because the row does not exist in the database.
The plan is to change the generation of code from the datamodel which will make the writes impossible. In the meantime follow the same strategy of the xml loading: do not replay the writes if the field has been marked as removed
I've rerun the test that was failing 6 times to verify the issue is not happening anymore. I'm looking at the reason some other tests in the suite failed to see if the change was the cause
> CA-375396: Ignore removed fields when redoing writes

- ocaml/idl/datamodel_vm.ml
- ocaml/xapi-cli-server/cli_frontend.ml
- ocaml/xapi-cli-server/cli_operations.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_vm.ml
- ocaml/xapi/xapi_vm.mli
Implemented as a localhost migration, can be made more efficient in future.
As it is simply a "pool_migrate", just reuse message forwarding of "pool_migrate" to handle "allowed operation" and "message routing".
> CP-45571: Add VM.restart_device_model function (API/CLI)

- ocaml/xenopsd/xc/device.ml
- ocaml/xenopsd/xc/service.ml
Part of CP-44317, CP-44320 suporting NVidia VCS. Adjust args when we are running a VCS (compute) vGPU when starting qemu and demu:
* don't pass -vgpu to qemu
* pass --noconsole to demu
Remove a redundant match in cmdline_of_disp.
> CP-45741 VCS support, adjust args for qemu, demu

- ocaml/xapi-types/ref.ml
- ocaml/xapi-types/ref.mli
Estimated testing time 20s (2 benchmarks x 10s). Change using '-quota'.
```
┌────────┬──────────┬─────────┬────────────┐
│ Name   │ Time/Run │ mWd/Run │ Percentage │
├────────┼──────────┼─────────┼────────────┤
│ master │  63.58ns │  28.00w │    100.00% │
│ pr     │  37.84ns │  14.00w │     59.51% │
└────────┴──────────┴─────────┴────────────┘
```
> xapi-types/ref: optimize of_string for real references 

- ocaml/idl/datamodel_errors.ml
- ocaml/idl/datamodel_host.ml
- ocaml/util/xapi_version.ml
- ocaml/util/xapi_version.mli
- ocaml/xapi-consts/api_errors.ml
- ocaml/xapi-consts/api_messages.ml
- ocaml/xapi/xapi.ml
During pool upgrade, it is expected that pool coordinator needs to be updated first, and a new xapi should start on the coordinator before it starts on any other host in the pool. Otherwise it is dangerous and may cause unpredictable problem.
This commit is to block pool member startup if it has a higher xapi version than coordinator until coordinator has a equal or higher version of xapi running.
> CP-43901: Block pool member startup if it has a higher xapi version

- ocaml/database/redo_log.ml
- ocaml/database/redo_log.mli
- ocaml/xapi/xapi_pool.ml
- ocaml/xapi/xapi_sr.ml
- ocaml/xapi/xha_metadata_vdi.ml
- ocaml/xapi/xha_statefile.ml
Commit 00cb7f2fa changed the default (recommended) size of the redo log to 4GiB, while keeping the minimum at 256MiB for backwards compatibility with existing VDIs.
However:
* HA must be disabled/re-enabled across updates anyway so backwards compatibility is not needed
* the redo-log on its own is known not to work (bug), keeping backwards compatibility here is not useful
* it makes it more difficult for XenCenter to tell the user when they chose an SR that is too small
If the SR is greater than minimum but below recommended then from the CLI you could still enable HA and create a redo log of the appropriate size, but not from XenCenter (where the size cannot be chosen).
We could expose a new RO pool field with the minimum size and update clients to use that, but that is unnecessary …
> CA-380551: bump minimum HA SR size to 4GiB

- ocaml/xapi-idl/gpumon/gpumon_client.ml
It can happens that the message switch queue for gpumon is not available and in this case the RPC is never answered. To avoid waiting forever we add a timeout.
The condition where the RPC is not answered arise when the RRDD gpumon plugin is not started. We observed in this condition and on a host with an Nvidia GPU that the xapi wait forever because it tries to get information about the GPU but we don't see a queue `org.xen.xapi.gpumon`. Adding this timeout allows the RPC to return and xapi continues its initialization. 
We also observed that starting the RRDD gpumon plugin has the effect of creating the `org.xen.xapi.gpumon` queue and so if the plugin is started the timeout is not needed.
> Add timeout to gpumon client

- ocaml/idl/datamodel.ml
This is needed for the SDK to generate functions that allow setting the json
flag by clients. (Xencenter, for example)
> CP-27910: expose json flag for /vm_rrd in the datamodel

- ocaml/database/redo_log.ml
- ocaml/xapi/static_vdis.ml
- ocaml/xapi/xapi.ml
The redo-log without HA is missing to attach the static VDIs that
actually contain the redo log. Call the same code that we are using in
the HA case.
> CA-384936 attach static VDIs for redo-log

- ocaml/libs/http-lib/http.ml
While I can't find a mention of the space this in the HTTP/1.1 spec, some clients cannot parse this correctly (tested with [Insomnia](https://insomnia.rest/)).
Also changing because we already do have this space for other headers, such as `content-length`.
> Add space between header name and value

- ocaml/xapi/xapi_globs.ml
During xapi startup, it will check availability of the essential executables, and fail if not found.
yum commands should not be essential, the repo managers will be
- yum: for xs8
- dnf: for xs9
> CP-45921: Make yum commands nonessential

- ezxenstore.opam
- forkexec.opam
- message-switch-async.opam
- message-switch-cli.opam
- message-switch-core.opam
- message-switch-lwt.opam
- message-switch-unix.opam
- message-switch.opam
- rrdd-plugin.opam
- rrdd-plugins.opam
- vhd-tool.opam
- xapi-datamodel.opam
- xapi-expiry-alerts.opam
- xapi-forkexecd.opam
- xapi-idl.opam
- xapi-rrdd-plugin.opam
- xapi-rrdd.opam
- xapi-squeezed.opam
- xapi-storage-script.opam
- xapi-storage.opam
- xapi-tracing.opam
- xapi-types.opam
- xapi.opam
In particular fixes a lot of errors caused by the incorrect format of the 'dev' pseudo-urls
> maintenance: update opam metadata from xs-opam

- ocaml/idl/datamodel_errors.ml
- ocaml/tests/test_repository_helpers.ml
- ocaml/xapi-consts/api_errors.ml
- ocaml/xapi/repository_helpers.ml
For the check of function `assert_url_is_valid`, repository-domain-name-allowlist doesn't work if you use the full FQDN for a server.
The `assert_url_is_valid` only allows if the host ends with .<entry in `repository-domain-name-allowlist`>. Now it is extended to allow if the hosts matches the entry in the list too.
> CA-365486: repository-domain-name-allowlist could accept a full hostname

- ocaml/xenopsd/scripts/common.py
- ocaml/xenopsd/scripts/igmp_query_injector.py
- ocaml/xenopsd/scripts/pygrub-wrapper
- ocaml/xenopsd/scripts/qemu-vif-script
- ocaml/xenopsd/scripts/qemu-wrapper
- ocaml/xenopsd/scripts/setup-vif-rules
Passed toolstack input test 191263
> CP-45981: Update xenopsd from python2 to python3

- ocaml/database/db_globs.ml
- ocaml/database/redo_log.ml
- ocaml/xapi/redo_log_alert.ml
Logging or redo_log is disable in xapi.conf. By logging under the module name, enable it for this module.
> CA-384148 enable logging for redo_log_alert

- ocaml/idl/datamodel_certificate.ml
- ocaml/idl/datamodel_common.ml
- ocaml/idl/schematest.ml
The hashes in the database always use SHA256
> CA-385315: document the certificates' fingerprints hash algorithm

- ocaml/idl/datamodel_roles.ml
- ocaml/idl/ocaml_backend/gen_rbac.ml
- ocaml/sdk-gen/c/gen_c_binding.ml
- ocaml/sdk-gen/common/CommonFunctions.ml
- ocaml/sdk-gen/csharp/gen_csharp_binding.ml
- ocaml/sdk-gen/java/main.ml
The PowerShell SDK needs more work as we'd need to generate a valid `dll-Help.xml` file to properly comment cmdlets: https://learn.microsoft.com/en-us/powershell/scripting/developer/help/how-to-create-the-cmdlet-help-file?view=powershell-7.3
Comment based support for `Get-Help` is only available for modules written directly in PowerShell.
Bit out of scope for this, worth opening a separate ticket.
Example of the new docs:
C#
```csharp
/// <summary>
/// Create a new VTPM instance, and return its handle.
/// Experimental. First published in 22.26.0.
/// </summary>
/// <param name="session">The session</param>
/// <param name="_vm">The VM reference the VTPM will be attached to</param>
/// <param name="_is_unique">Whether the VTPM must be unique</param>
/// <remarks>
/// Minimum allowed role: …
```
> CP-42559: Add RBAC info to C#, Java, and C SDK method comments

- ocaml/vhd-tool/scripts/get_nbd_extents.py
- ocaml/vhd-tool/scripts/python_nbd_client.py
Changes for python3 syntax:
1. format with black
2. remove redundant arguments in super() https://docs.python.org/3/library/functions.html#super
3. remove redundant pass statement
4. since Python 3, all classes inherit from object by default
5. since PEP 3120, Using UTF-8 as the default source encoding
Test passed with Storage BST，job id: 191563
> CP-45973 update vhd-tool to python3

- ocaml/xapi-cli-server/cli_operations.ml
Adds `host-id` to `pif-list` params printed by default, and fix the "MAC" case discrepancy noticed by @robhoes
> `xe pif-list` default params (#5263)

- ocaml/xapi/dune
- ocaml/xapi/xapi_observer.ml
- ocaml/xapi/xapi_observer.mli
- xapi.opam
Note that we keep the interface defined in `xapi_observer.mli` the same, i.e. the `create` and `set_components` functions continue to accept string as parameters, but internally we use ocaml's variant type.
> Change type of observer components to use variant

- scripts/plugins/disk-space
- Comparisons to singletons like None should always be done with 'is' or 'is not', never the equality operators.
- Reduce Cyclomatic complexity.
Test passed in XenRT, job id: 3871041
> CP-45978 update /etc/xapi.d/plugins/disk-space to python3 for xs9

- .github/workflows/main.yml
- .github/workflows/release.yml
I found these while trying to found out a reliable way to push the datamodel changes after a release. Unfortunately doing that seems quite fragile with github actions, so I'm only pushing for these small fixes instead.
These have been tested on my fork to ensure they work as expected
> Simplify the release and the main workflow releases

- ocaml/xcp-rrdd/bin/rrdp-iostat/rrdp_iostat.ml
- quality-gate.sh
Use scanf to to read the stats provided by the /sys file system. This rest of the code is still quite convoluted. In case of an error we are returning 0 values - not sure this is a good choice.
> Simplify scanning /sys/block/<dev>/ stats for iostat

- ocaml/xapi-cli-server/cli_operations.ml
- ocaml/xapi/context.ml
Some tasks have the name "Export of VM" concatenated with the corresponding uuid. These creates thousands of different span names for the same task. This change prevents that and slightly refactors the code to remove duplicated code when creating the span for different types of tasks.
> CP-46677: Create correct span names associated with tasks.

- ocaml/idl/datamodel_common.ml
- ocaml/idl/datamodel_host.ml
- ocaml/idl/datamodel_vm.ml
- ocaml/idl/schematest.ml
- ocaml/tests/common/test_common.ml
- ocaml/xapi-cli-server/record_util.ml
- ocaml/xapi-cli-server/records.ml
- ocaml/xapi/create_misc.ml
- ocaml/xapi/updateinfo.ml
- ocaml/xapi/updateinfo.mli
- ocaml/xapi/xapi_db_upgrade.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_host_helpers.ml
- ocaml/xapi/xapi_vm.ml
- ocaml/xapi/xapi_vm_clone.ml
This is the initial commit for the update guidance improvement:
1. Update comments for re-purposing host.pending_guidances.
2. Add new pending-guidance fields: host.pending_guidances_recommended,
host.pending_guidances_full, vm.pending_guidances_recommended and
vm.pending_guidances_full.
3. Add definition for new guidance: RestartVM,
reboot_host_on_kernel_livepatch_failure and
reboot_host_on_xen_livepatch_failure
4. Add DB upgrade rule: replace reboot_host_on_livepatch_failure in
"host.pending_guidances" with both
reboot_host_on_kernel_livepatch_failure and
reboot_host_on_xen_livepatch_failure in
"host.pending_guidances_recommended”
5. Clear reboot_host_on_kernel_livepatch_failure and
reboot_host_on_xen_livepatch_failure on reboot
6. CLI: expose those new added pending guidance fields
> CP-45565: Add new guidance fields to API and CLI

- ocaml/xapi/sparse_dd_wrapper.ml
Example log after the patch
```
Dec  7 11:11:11 xrtuk-15-02 xapi: [error||30997 ||backtrace] Async.VDI.copy R:a1c789606cb2 failed with exception Server_error(VDI_COPY_FAILED, [ Fatal error: exception Dune__exe__Sparse_dd.MyExp\x0A ])
Dec  7 11:11:11 xrtuk-15-02 xapi: [error||30997 ||backtrace] Raised Server_error(VDI_COPY_FAILED, [ Fatal error: exception Dune__exe__Sparse_dd.MyExp\x0A ])
Dec  7 11:11:11 xrtuk-15-02 xapi: [error||30997 ||backtrace] 1/22 xapi Raised at file ocaml/xapi/sparse_dd_wrapper.ml, line 168
Dec  7 11:11:11 xrtuk-15-02 xapi: [error||30997 ||backtrace] 2/22 xapi Called from file ocaml/xapi/sparse_dd_wrapper.ml, line 178
Dec  7 11:11:11 xrtuk-15-02 xapi: [error||30997 ||backtrace] 3/22 xapi Called from file lib/xapi-stdext-pervasives/pervasiveext.ml, line 24
Dec  7 …
```
> CA-384457: Add special case for End_of_file to sparse_dd_wrapper

- ocaml/idl/datamodel_errors.ml
- ocaml/xapi-consts/api_errors.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_host_helpers.ml
As mandatory host guidance must be applied after applying updates, otherwise there may be e.g. VM failures, it is safe not to enable a host when its mandatory host guidance is pending:
1. do not enable host on xapi startup if there is pending mandatory gudiance in the host.
2. raise error: host_pending_mandatory_guidances_not_empty for API host.enable if there is pending mandatory gudiance in the host.
> CP-45568: Do not enable host if its mandatory host guidance is pending

- ocaml/libs/tracing/tracing.ml
- ocaml/xapi/xapi_cluster_host.ml
- ocaml/xapi/xapi_observer.ml
- ocaml/xapi/xapi_observer.mli
create observer exporting thread regardless of whether we have observers in database.
> CA-386582: Always create exporting thread for observers

- ocaml/xapi-idl/lib/debuginfo.ml
- ocaml/xapi-idl/lib/debuginfo.mli
- ocaml/xapi/sm.ml
- ocaml/xapi/static_vdis.ml
- ocaml/xapi/storage_smapiv1.ml
- ocaml/xapi/storage_smapiv1_wrapper.ml
Functions inside 'storage_smapiv1.ml' do not propagate the 'traceparent' and/or do not start spans when called. This change makes sure the propagation is done, slightly refactors the code to remove code duplication, and ensure proper closing of spans when exceptions happen.
> CP-46379 Propagate 'traceparent' from 'storage_smapiv1.ml' to 'sm.ml'

- doc/content/xapi/walkthroughs/_index.md
- doc/content/xapi/walkthroughs/migration_overview.md
Also adds a flowchart that describes the migration to help for clarity.
As I'm currently looking how to implement fast resume in the Xapi toolstack I'm looking closely how migration is working and so I'm writing some documentation. I see from @robhoes new doc that you are using mermaid so I added a flowchart :)
And as it can be interesting for others I post it ;).
However I'm not sure if the part that describes where atomic messages are exchanged between the server and the xenopsd back-end is accurate. It seems when I read the source that enqueuing  and dequeuing the atomic message are managed by the xenopsd server and it is the xenopsd server that doing the call to the xenopsd-xc backend. Enlightenment is welcome.
Hope this help
> Add an overview of the migration of a VM

- ocaml/idl/datamodel_errors.ml
- ocaml/tests/test_repository_helpers.ml
- ocaml/tests/test_updateinfo.ml
- ocaml/xapi-consts/api_errors.ml
- ocaml/xapi/repository.ml
- ocaml/xapi/repository.mli
- ocaml/xapi/repository_helpers.ml
- ocaml/xapi/updateinfo.ml
- ocaml/xapi/updateinfo.mli
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_host_helpers.ml
This PR includes changes to support guidance data in new format in updateinfo.xml. The XAPI will support guidance data in updateinfo.xml in either old or new format for sake of backwards compatibility. Then XAPI will convert the guidance data and expose to XAPI clients through interfaces like HTTP /updates and pending guidance lists. But for simplicity, XAPI will not support backwards compatibility on these XAPI interfaces. This means a new XenCenter is required to co-work with the XAPI changes in this PR.
> CP-45566: Support guidance data in new format in updateinfo.xml

- ocaml/libs/tracing/tracing.ml
- ocaml/libs/tracing/tracing.mli
This is so that daemons like clusterd can call it and flush the spans before they exit
> Add interface for flush spans and exit the export thread

- .github/workflows/main.yml
- scripts/Makefile
Opening PR to test CI, this will also need a .spec change
> Fix 'make install' and add a CI rule

- scripts/print-custom-templates
- format with `2to3`
- In Python 2, it was possible to compare strings without using quotes, but python3 not
- fix invalid `logout` function 
Tested manually on host
> update print-custom-templates to python3

- ocaml/idl/datamodel_common.ml
- ocaml/idl/datamodel_pool.ml
- ocaml/idl/schematest.ml
- ocaml/tests/common/test_common.ml
- ocaml/xapi-cli-server/records.ml
- ocaml/xapi/dbsync_master.ml
- ocaml/xapi/helpers.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_globs.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_pool.ml
- ocaml/xapi/xapi_pool.mli
- ocaml/xapi/xapi_vm.ml
Solves: https://github.com/xapi-project/xen-api/issues/5245
> Custom UEFI certificates - API change

- ocaml/xcp-rrdd/bin/rrdd/xcp_rrdd.ml
This PR aims to add the number of running vCPU and running domain into rrdd:
1. For the running vCPUs, I derive this information from 'xenctrl.vcpuinfo', where the vCPU's state is marked as 'online' and 'not blocked'. Although we could calculate it based solely on the 'running' states, I find that 'online' and 'not blocked' covers a wider range of scenarios.
2. For the running domains, I straightforwardly derive this data from 'xenctrl.domaininfo', where the domain's state is indicated as 'running.
3. I convert the Dom0 memory_internal_free from B to KiB, due to the official document declare the unit of this attribution is KiB, see: 
new test result:
```
[root@xrtuk-13-07 ~]# xe host-data-source-query data-source=running_vcpus
1.000000
[root@xrtuk-13-07 ~]# xe host-data-source-query …
```
> CP-44533 Add running vCPU and running domain of host into rrdd

- ocaml/xapi/repository.ml
The RestartVM will be cleared when a VM's power state transits to Halted. So it is not good to add this update guidance action into shutdown VMs' pending guidance list, although it could be cleared in VM start also.
> CA-387034: RestartVM is added to pending guidances of shutdown VMs

- ocaml/idl/datamodel_errors.ml
- ocaml/xapi/repository_helpers.ml
- ocaml/xapi/xapi_host.ml
Update document for error: "host_pending_mandatory_guidances_not_empty" as it is used not only when enabling host.
> CA-387033: Update xapi error document

- ocaml/xapi/import.ml
- ocaml/xapi/xapi_vtpm.ml
- ocaml/xapi/xapi_vtpm.mli
An imported VM can have a power state different from halted. So far we enforced that a VM is halted when creating a VTPM for it. In the case of import we want to relax this because the VM is not actually running.
This might not be the best solution. In essence, when importing a VM we have to ignore its power state when creating a VTPM for it. This is also being tested after some initial testing by me.
> CA-385065 VM import with VTPM, don't block on power state

- ocaml/xenopsd/lib/xenops_server.ml
- ocaml/xenopsd/xc/xenops_server_xen.ml
Simplify the logging and reporting of internal errors in xenopsd. Rather than constructing a complex exception use a function that accepts a printf-style string for convenience. It logs the error and raises the exception.
> OIL: introduce internal_error(fmt) for error reporting

- ocaml/xapi/sm.ml
- ocaml/xapi/sm_exec.ml
- ocaml/xapi/storage_smapiv1.ml
- ocaml/xapi/xapi.ml
- ocaml/xapi/xapi_vdi.ml
The `traceparent` was not propagated from the `sm.ml` functions. This commit solve this by propagating `dbg` into `Sm_exec.exec_xmlrpc` as an optional argument.
When `dbg` is passed, `Sm_exec.exec_xmlrps` now creates a span around the call.
> CP-46378: Propagate `dbg` to `Sm_exec.exec_xmlrpc`

- scripts/sysconfig-perfmon
For example, we set the `$PERFMON_FLAGS` in scripts/sysconfig-perfmon:
```bash
PERFMON_FLAGS=""
PERFMON_FLAGS="$PERFMON_FLAGS --debug"
PERFMON_FLAGS="$PERFMON_FLAGS --interval=60"
PERFMON_FLAGS="$PERFMON_FLAGS --rrdstep=5"
```
What we ultimately want the value of `PERFMON_FLAGS` is `--debug --interval=60 --rrdstep=5`, then pass `PERFMON_FLAGS` to @OPTDIR@/bin/perfmon.
But there are some limits in EnvironmentFile of service in the [document of systemd](https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#Environment):
> Variable expansion is not performed inside the strings and the "$" character has no special meaning.
>
> Settings from these files override settings made with Environment=. If the same variable is set twice from these files, the files will be read in …
> CA-386457: fix environment variable loading of `$PERFMON_FLAGS` in perfmon.service

- ocaml/idl/datamodel_host.ml
- ocaml/idl/schematest.ml
- ocaml/tests/common/test_common.ml
- ocaml/xapi-cli-server/records.ml
- ocaml/xapi/xapi_host.ml
Add field "last_update_hash" on host object to record the SHA256 checksum of updateinfo of the most recently applied update on the host.
> CP-43875: Record the repository hash on the host object when updating

- scripts/bugtool-plugin/xapi/stuff.xml
The xapi database holds task but this table is not persisted. In conjuction with XSI-1559 it would be useful to have the currently active tasks. Add the output of "xe task-list" to the bugtool.
This was manually tested. In the typical case the task list is empty. So this adds no weight to the bugtool.
> CP-47153 add task list to bugtool

- ocaml/message-switch/async/protocol_async.ml
- ocaml/message-switch/core/make.ml
- ocaml/message-switch/core/s.ml
- ocaml/message-switch/lwt/protocol_lwt.ml
- ocaml/message-switch/switch/switch_main.ml
Previously the `protocol_lwt` server handles one request at a time which makes clusterd, for example, blocked if one request is taking a long time. Modifying the `protocol_lwt` (and `protocol_async` until it's removed) to make it possible to handle multiple requests.
> CP-47033: Allow `protocol_lwt` server to handle multiple requests at the same time

- ocaml/idl/datamodel.ml
- ocaml/idl/datamodel_host.ml
- ocaml/xapi-cli-server/cli_frontend.ml
- ocaml/xapi-cli-server/cli_operations.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_host.ml
- ocaml/xapi/xapi_host.mli
The non-empty host pending mandatory guidance will result in the host blocked from being enabled or updated. This commit introduces a new API to clear the pending mandatory guidance in emergency cases. Otherwise, the host might be stuck in such a situation.
> CP-45569: Add API Host.emergency_clear_mandatory_guidance

- ocaml/xapi/repository.ml
A safety check in host.apply_updates will raise error if there is a mandatory EvacuateHost guidance but some VMs are running on the host. Meanwhile, EvacuateHost should not be added into pending list as it should be be carried out before host.apply_updates. Hence it needs to be filtered out.
This commit fixes a bug that filering out the EvacuateHost before the safety check. It should be filtered out after the safety check.
> Fixup: filter out EvacuateHost before safety check

- ocaml/xapi/import.ml
POSIX/PAX headers in TAR may be larger than 1 TAR block (otherwise we see the Pax global headers as a "file" in backwards compatible mode).
Calling Tar_unix.get_next_header would already read the appropriate amount from a FD to find the first true file header.
However an imported file can be either compressed or not, and we need to retry with decompression if parsing as a Tar failed. But we might be importing from a socket or pipe, so we cannot just seek back to the beginning, and we cannot use Tar_unix.get_next_header either because we don't have access to its internal buffer.
Implement a custom Tar header reader using the functor, that first feeds the block that we already read to the reader, and then the file itself directly (at which point we turn off the retry because we no longer …
> CP-46122: Support PAX/POSIX tar on import

- ocaml/xapi/xapi_pool.ml
When a user adds more update repositories as enabled ones, the pool.last_update_sync will be invalid as at the moment not all the enabled repositories have been synced at the time which is recorded in pool.last_update_sync.
To avoid confusion, this commit resets the field to epoch so that the user can be notified to do a pool.sync_updates soon.
Disabling an update repository will not make the pool.last_update_sync be invalid unless no enabled repositories after the disabling.
> CA-387201: Pool.last_sync_date not reset if the user changes update channel

- scripts/mail-alarm
- scripts/usb_scan.py
As @bernhardkaindl mentioned, those file already support python3, so this PR only changed:
- update shebang
- sort out imports
> update mail-alarm and usb_scan to python3

- ocaml/message-switch/async/protocol_async.ml
Monadic concurrency libraries can switch away to another 'promise' whenever the bind operator is called.
In fact Async will always switch away, but Lwt would only switch away if the promise is blocked (this is probably the origin of the bug).
Move the 't.m <- true' next to where we checked that it is false to ensure that we are the only ones holding it.
(This is still vulnerable to race conditions with pure OCaml threads, but not with Async promises).
Another alternative would be to use Async.Throttle.Sequencer, but this change is a minimal one that could be backported to Yangtze even.
> CA-387699: Fix Protocol_async.with_lock bug spotted by Vincent

- scripts/mail-alarm
- scripts/usb_scan.py
This reverts commit 3259196db57c7e2c301519236b0723dfa095554d.
We've seen in the testsuite likely caused by this change:
```
Unexpected exception in message hook /opt/xensource/libexec/mail-alarm: INTERNAL_ERROR: [ Subprocess exited with unexpected code 1; stdout = [  ]; stderr = [ Traceback (most recent call last):\x0A\x0A  File "/opt/xensource/libexec/mail-alarm", line 1055, in <module>\x0A    rc = main()\x0A\x0A  File "/opt/xensource/libexec/mail-alarm", line 1027, in main\x0A    os.write(fd, config)\x0A\x0ATypeError: a bytes-like object is required, not 'str'\x0A\x0A ] ]
```
> Revert "update mail-alarm and usb_scan to python3"

- ocaml/idl/datamodel_common.ml
- ocaml/idl/datamodel_pool.ml
- ocaml/idl/schematest.ml
- ocaml/xapi-cli-server/record_util.ml
- ocaml/xapi/message_forwarding.ml
- ocaml/xapi/xapi_pool_helpers.ml
When a host is ejected from a pool, its certificate for pool-internal communication is removed from all remaining hosts. This is unlikely to work when we have multiple eject operations overlapping. Hence, introduce an eject operation and make sure ejects are serialised.
> CA-387456 serialise Pool.eject
