ocaml/xs-trace/test/test-xs-trace.sh
ocaml/xs-trace/test/test_xs_trace.ml

Bypass TIME_WAIT on the test socket in test-xs-trace, otherwise running the test in a loop would sometimes fail.
(TIME_WAIT can take a minute or more to clear on its own, and there is no point in waiting for that in test code)

CA-387588: Avoid EADDRINUSE in test code due to TIME_WAIT

---

ocaml/xenopsd/scripts/qemu-wrapper

QEMU complains during a migration:
```
qemu-dm-120: Expected vmdescription section, but got 0
```
This has been fixed upstream in 2020, but only for libxl: https://patchew.org/Xen/20201029190332.31161-1-jandryuk@gmail.com/
(And QEMU 5.2+ would do it automatically for machine=xenfv but we're still using machine=pc, and an older QEMU.)
Implement the equivalent fix for xenopsd: we use qemu 4.x, and this CLI flag first appeared in 2.3, so should be fine.
I did a quick test on my XenServer box and a localhost migrate has succeeded and didn't log this message anymore.

xenopsd: avoid log message about vmdesc

---

Makefile
ocaml/forkexecd/test/fe_test.ml

We have some non-deterministic timeouts on github actions. Introduce some shorter timeouts that is under our control,
and print more information about what is stuck.
GH actions take <2m to run the tests, so add 5m as a timeout for the children, and twice that for the parent.
This is like https://github.com/xapi-project/xen-api/pull/5355 but without the hacks to disable unreliable tests.
If the CI passes on this one then we should probably merge this to make diagnosing test failures in other PRs easier. I added the missing cleanup code so the ps output should only be printed if there is an actual timeout (if the tests fail or succeed sooner then the sleeping process is killed and ps tree is never dumped).

build: set a timeout for the tests and fix forkexecd unit test

---

ocaml/forkexecd/lib/fe_systemctl.ml
ocaml/forkexecd/lib/fe_systemctl.mli

We use systemd to start transient services. So far, we use the Simple type but would like to add oneshot and potentially more.

CA-387560 add support for more systemd execution types

---

ocaml/xapi/dbsync_slave.ml
ocaml/xapi/xapi_host_helpers.ml
ocaml/xapi/xapi_host_helpers.mli
ocaml/xapi/xapi_vm_lifecycle.ml
ocaml/xapi/xapi_vm_migrate.ml
ocaml/xapi/xapi_xenops.ml

This PR fixes issue about clearing RestartToolstack guidance and RestartDeviceModel guidance, and clear RestartVM guidance.
Please refer commit message of each commit for details.

CP-45570: Clear pending guidance when it got applied

---

Makefile

Setting this is useful for speeding up tests (by default my container has 1048576 as ulimit which makes the tests very slow), but there is something non-deterministic in the environment GitHub Actions run in:
* the tests pass on a PR, but fail when run as a scheduled CI job on master
We probably don't estimate correctly how many file descriptors the parent process uses in the test (GH actions seem to use more than locally).
Until we fully understand this revert the 'ulimit -n' part of this change.
Fixes: 954f3d337 ("build: set a timeout for the tests")

fix(ci): remove 1024 fd limit for now

---

scripts/usb_reset.py

PR#5350 contains the following changes:
- Shebang changed to python3,
- map() needs to be converted to list()
- Change `setup_cgroup()` to binary I/O:
Python3 does not support unbuffered Raw I/O in Text mode:
Fix "can't have unbuffered text I/O" by changing the code to use binary mode instead of text mode:
when executing `/opt/xensource/libexec/usb_reset.py attach 1-13.2 -d 16 -p 8470`. 
```py
Error code:
Traceback (most recent call last):
File "/opt/xensource/libexec/usb_reset.py", line 343, in <module>
attach(arg.device, arg.domid, arg.pid, arg.reset_only)
File "/opt/xensource/libexec/usb_reset.py", line 285, in attach
setup_cgroup(domid, pid)
File "/opt/xensource/libexec/usb_reset.py", line 215, in setup_cgroup
with open(cg_dir + "/tasks", "w", 0) as tasks, \
ValueError: can't have …
```

CP-47043: Port usb_reset.py to python3. 

---

ocaml/xenopsd/scripts/qemu-wrapper

The script is only used at specific points:
- Migrating a VM from an XS7.1 host to XS8.
- Resuming a VM suspended on an XS 7.1 host on XS8.
- Reverting to a disk+memory snapshot created on XS 7.1 on an XS8 host.
All of these are unlikely scenarios since the only way to get to XS8 is by upgrading from CH 8.2 which means the customer would need to do a multi hop upgrade to hit the issue. We don't have XenRT tests for this. After discussing with Alex, we thought it would be better to remove this code and document this as a known limitation.
This modification involves changes in two aspects, xen-api and qemu.spec.
Test passed with 192904 (Ring3 BVT+BST combined) and 192757 (QA Karma test)

CP-45970 remove qemu_trad_image.py

---

ocaml/idl/datamodel_cluster.ml
ocaml/idl/datamodel_cluster_host.ml
ocaml/idl/datamodel_common.ml
ocaml/idl/datamodel_lifecycle.ml
ocaml/idl/schematest.ml
ocaml/tests/common/test_common.ml
ocaml/tests/test_cluster.ml
ocaml/tests/test_cluster_host.ml
ocaml/xapi-cli-server/records.ml
ocaml/xapi-idl/cluster/cluster_interface.ml
ocaml/xapi/xapi_cluster.ml
ocaml/xapi/xapi_cluster_host.ml
ocaml/xapi/xapi_clustering.ml

Results look like this:
```bash
$ xe cluster-param-list uuid=690d6398-9f00-9ca9-497d-9ad5d700cdfd    
uuid ( RO)                         : 690d6398-9f00-9ca9-497d-9ad5d700cdfd
cluster-hosts (SRO): 190aff88-c954-4286-ead7-7c81b3a00bd3; 81efff95-1baa-2801-3397-2b5a4b8c7ec4; 160139e0
-4dc2-be55-3cc8-02812536cd9a
cluster-token ( RO): b03a7918-2ca7-4d9f-a1a1-5d5391eeaba1
cluster-stack ( RO): corosync
token-timeout ( RO): 20.000
token-timeout-coefficient ( RO): 1.000
allowed-operations (SRO): destroy; disable; enable; remove; add
current-operations (SRO):
pool-auto-join ( RO): true
cluster-config (MRO):
other-config (MRW):
+                   is_quorate ( RO): true
+               quorum_members (SRO): 10.62.49.47; 10.62.49.39; 10.62.49.35
+                       quorum ( RO): 2
+ …
```

CP-46323: Expose quorum and cluster membership through the API

---

ocaml/idl/datamodel.ml
ocaml/idl/datamodel_common.ml
ocaml/idl/datamodel_host.ml
ocaml/idl/datamodel_lifecycle.ml
ocaml/idl/datamodel_pool.ml
ocaml/idl/datamodel_repository.ml
ocaml/idl/datamodel_types.ml
ocaml/idl/datamodel_types.mli
ocaml/idl/datamodel_vm.ml
ocaml/idl/schematest.ml

Replace all occurances of `next_release` and `rel_next` with appropriate version numbers.

CA-387698: datamodel: eliminate next_release

---

ocaml/message-switch/async/protocol_async.ml
ocaml/message-switch/core/make.ml
ocaml/message-switch/core/s.ml
ocaml/message-switch/lwt/protocol_lwt.ml
ocaml/message-switch/switch/switch_main.ml

This reverts commit e9923e366112f1513f5dc864a0ce48e0c3dc79f9 and 1221764db2d37524f44fde255b25af9779a4b756.
Bugs seen in timeout of unplugging 2TB VBD. Reverting this concurrent processing until this is tested more extensively.

CA-388064: Revert "Protocol_{lwt,async}: process requests concurrently"

---

scripts/xapi.conf

When the `override-uefi-certs` setting was renamed to `allow-custom-uefi-certs`, we forgot to update xapi.conf.

xapi.conf: fix setting name for custom UEFI certs

---

ocaml/xapi/repository.ml

This aligns with the update guidance exposed in /updates endpoint.

CA-388351: Always apply livepatches even if host will reboot

---

scripts/usb_reset.py

Fixed byte issue ,rectified hash issue . 
Xenrt test was successful   XenRT job 3918886  and  Job 3918525
xapi-core has correct code ,tested on machine   xrtmia-10-11 and xrtmia-10-08
@edwintorok @acefei @liulinC @psafont @bernhardkaindl

CP-47043: Ported usb_reset.py to python3 ,fixed byte issue based on internal test CA-388318.

---

ocaml/tests/test_observer.ml
ocaml/xapi/xapi_globs.ml
ocaml/xapi/xapi_observer.ml

This option defaults to false as it is unsafe for customers to use http endpoints. This can be enabled for dev testing and XenRT.

CP-46939: Add config option observer_endpoint_http_enabled

---

.github/workflows/main.yml
.github/workflows/python-warning-matcher.json
.pre-commit-config.yaml
pyproject.toml
pytype_reporter.py
scripts/examples/python/XenAPIPlugin.py

- Gather code coverage results from pytest and upload to Codecov.
- Add minimal configuration file for pre-commit and run it in CI
- Appy an example pre-commit fix for [scripts/examples/python/XenAPIPlugin.py](https://github.com/xapi-project/xen-api/blob/private/bernhardk/python-add-code-coverage-reporting/scripts/examples/python/XenAPIPlugin.py):
- [As it is a module, not a script, remove the shebang and add a module docstring](https://github.com/xapi-project/xen-api/pull/5384/files#diff-84e65e4f2f2ea8d8f08e7cfd85b3f1f7ff0a045d492be09a29b78cba61bb11db)

CI/Python: Add reporting of code coverage from PyTest

---

ocaml/xapi-cli-protocol/cli_protocol.ml
ocaml/xapi-cli-server/cli_frontend.ml
ocaml/xapi-cli-server/cli_operations.ml
ocaml/xe-cli/newcli.ml
quality-gate.sh

To facilitate the users who use XE CLI to perform update, a new XE CLI "xe host-show-updates" is added in this series to show the available updates on a host. Prior to this change, the information can be get from XAPI HTTP /updates endpoint. In addition, the available updates will be printed out in existing "xe host-apply-updates".

Add "xe host-updates-show-available" CLI and update "xe host-apply-updates"

---

ocaml/squeezed/lib/squeeze.ml
ocaml/squeezed/lib/squeeze.mli
ocaml/squeezed/src/squeeze_xen.ml
ocaml/squeezed/test/squeeze_test.ml
quality-gate.sh

use `Set` instead of `List` because `set_difference` implemented using `List` is quadratic cost
The flame graph before refactoring:
The flame graph after refactoring:
Special thanks to @psafont and @edwintorok for guides.

CA-372059: refactor the type of host in `squeeze.ml`

---

Makefile
ocaml/xapi-storage-script/test/volume/org.xen.xapi.storage.dummy/plugin.py
ocaml/xapi-storage-script/test/volume/org.xen.xapi.storage.dummy/sr.py
ocaml/xapi-storage-script/test/volume/org.xen.xapi.storage.dummy/volume.py
ocaml/xapi-storage-script/test/volume/org.xen.xapi.storage.dummyv5/plugin.py
ocaml/xapi-storage-script/test/volume/org.xen.xapi.storage.dummyv5/sr.py
ocaml/xapi-storage-script/test/volume/org.xen.xapi.storage.dummyv5/volume.py
ocaml/xapi-storage/python/xapi/__init__.py
ocaml/xapi-storage/python/xapi/storage/api/datapath.py
ocaml/xapi-storage/python/xapi/storage/api/plugin.py

Running "make test" on a Debian12 fails because of the lack of python2, and switching those tests to python3 revealed problems.
It may be worth to have give "make test" the ability to run under python2 too (in which case the `urlparse` replacement must be kept py2-compatible), to ensure xs/xcp-ng 8.x do not regress.  I'm not sure how best to do achieve that, with the python tests run through `dune`.  Maybe they should be added to the py2/py3 tests jobs in Gitlab Actions, too.

Python3 fixes for storage api

---

ocaml/forkexecd/lib/forkhelpers.ml
ocaml/forkexecd/lib/forkhelpers.mli
ocaml/libs/tracing/tracing.ml
ocaml/libs/tracing/tracing.mli
ocaml/xapi-aux/env_record.ml
ocaml/xapi-aux/env_record.mli
ocaml/xapi-idl/lib/debuginfo.ml
ocaml/xapi-idl/lib/debuginfo.mli
ocaml/xapi/sm_exec.ml
ocaml/xapi/xapi_cluster_host.ml
ocaml/xapi/xapi_globs.ml
ocaml/xapi/xapi_observer.ml
ocaml/xapi/xapi_observer.mli
ocaml/xapi/xapi_observer_components.ml
ocaml/xapi/xapi_observer_components.mli

Sets up the necessary environment variables, `TRACEPARENT` and `OBSERVER_CONFIG_DIR`  for  SMAPI `observer.py` configuration.

CP-46377: Add env vars `TRACEPARENT` & `OBSERVER_CONFIG_DIR` to `exec_xmlrpc` calls

---

ocaml/libs/xapi-rrd/lib_test/dune

Otherwise dune runs them for all packages in the repository, failing if they don't depend on the xapi-rrd library. This happens when opam builds the packages individually, like in https://github.com/xapi-project/xs-opam/actions/runs/7735950831/job/21092466205

xapi-rrd: attach tests to package

---

.github/workflows/main.yml
ocaml/libs/vhd/vhd_format_lwt_test/parse_test.ml
ocaml/libs/vhd/vhd_format_lwt_test/patterns_lwt.ml

The VHD unit tests create a lot of files in /tmp and don't always clean it up.
Move the files elsewhere, although we should really fix the test to clean up too.

Try to avoid ENOSPC in CI

---

ocaml/xcp-rrdd/scripts/rrdd/rrdd.py

This avoid the possibility of the `open` truncating an existing shared memory block, which `open(<path>, 'wb')` would do. Should have only happened on domain id wrap so is probably extremely rare/unlikely.

CA-382640: open SHM with os.open to allow for RW/Creat

---

ocaml/idl/datamodel_lifecycle.ml

I manually set this, as these were missed when cutting 24.3.0: https://github.com/xapi-project/xen-api/releases/tag/v24.3.0

datamodel_lifecycle: update cluster forum introduction versions

---

ocaml/networkd/lib/network_utils.ml

The OVS command to query the state of a bond now uses the term "member" rather than "slave" for bond links. Adapt the code in networkd to expect this.

CA-388437: fix bond status reporting

---

ocaml/idl/datamodel_common.ml

So that the existing XenCenter will refuse to connect to the new XAPI. This aims to force users to use the new XenCenter since the old XenCenter can't work with the new XAPI with update guidance improvement.

CP-46946: Bumped API version to 2.21 for update guidance improvement

---

ocaml/idl/datamodel_common.ml
ocaml/xapi/xapi_db_upgrade.ml

Add update guidance DB upgrade rule: except reboot_host_on_livepatch_failure, move any guidance in
"host.pending_guidances" into "host.pending_guidances_recommended".

CP-47012: change pending guidance in old xapi to recommended ones in new xapi

---

.github/workflows/main.yml

It does not support linting actions, which blocks reusing code in github actions.
On top of that it hasn't been updated in months. There's a PR to add actions to it since october.
Since this is blocking #5433, remove it

ci: remove action lint

---

ocaml/idl/datamodel_cluster_host.ml
ocaml/idl/schematest.ml
ocaml/xapi-consts/api_messages.ml
ocaml/xapi/xapi_cluster_helpers.ml
ocaml/xapi/xapi_cluster_host.ml
ocaml/xapi/xapi_clustering.ml

Example message list
```
uuid ( RO)         : b6c6253f-f652-7aae-51b0-79cbf72479f1
name ( RO): CLUSTER_QUORUM_APPROACHING_LOST
priority ( RO): 2
class ( RO): Pool
obj-uuid ( RO): e33d8155-3066-76b4-4199-f306212f9478
timestamp ( RO): 20240131T17:20:00Z
body ( RO): The cluster is losing quorum: current 1 hosts, need 1 hosts for a quorum
uuid ( RO)         : 152af337-72ac-a38d-7a75-8a32fc69516a
name ( RO): CLUSTER_HOST_LEAVING
priority ( RO): 3
class ( RO): Host
obj-uuid ( RO): 8b33e8ea-70e1-474c-9d76-6a7902a709ac
timestamp ( RO): 20240131T17:20:00Z
body ( RO): Host xrtmia-05-13 has left the cluster, there are now 1 host(s) in cluster and 1 host(s) is required to form a quorum
```

CP-46324: Send alert when a host leaves/joins the cluster

---

.github/workflows/main.yml
ocaml/xcp-rrdd/scripts/rrdd/rrdd.py
ocaml/xcp-rrdd/scripts/rrdd/test_api_wait_until_next_reading.py

`2to3` failed to convert `xcp-rrdd/scripts/rrdd.py` properly (it chokes and just quits), so here is the manual Post-Python3-fixup for it:
```js
except socket.error:
msg = "Failed to contact xcp-rrdd. Sleeping for 5 seconds .."
-                print >> sys.stderr, msg
+                print(msg, file=sys.stderr)
```
This means, instead of sleeping and retrying in 5 seconds, the `xcp-rrdd/scripts/rrdd.py` would crash.
Commits:
1. The fix commit,
2. A unit test
3. A minimal plaster tapering over the other findings of the `pytype` static analysis checker that is now needed to pass CI with changed Python files.
- `xmlrpc.client.ServerProxy.__init__()` receives the flags `verbose` and `allow_none` as `bool`, so static analysis does not like it when you pass integers to it. They can just be …

Post-Python3-fixup for xcp-rrdd/scripts/rrdd.py: Fix crash on `socket.error` on connect() to xcp-rrdd

---

ocaml/xapi-consts/constants.ml
ocaml/xapi/xapi_globs.ml
ocaml/xapi/xapi_observer_components.ml

Adds a new variable in `Xapi_globs` that is a comma-separeted string of components. Components in this list will be considered experimental and therefore disabled by default. They can be enabled by adding an entry in `xapi.conf` without their name.
For instance, adding the line:
observer-experimental-components = ""
will enable all experimental copmponents.

CP:46157: Add `observer_experimental_components` flag

---

ocaml/xapi/context.ml
ocaml/xapi/context.mli
ocaml/xapi/taskHelper.ml

Adds:
- `xs.xapi.task.id`;
- `xs.xapi.task.name`;
- `xs.xapi.task.uuid`;
- `xs.xapi.session.track.id`;
- `xs.xapi.task.origin`
to the list of span attributes created by `Context.make`.
This improves the debuggability and makes spans more easily identifiable. 
Also combines `complete_tracing` and `complete_tracing_with_exn` in one function by making error a optional argument.

CP-46631: Improved list of span attributes.

---

ocaml/idl/datamodel_vm.ml

The default value of 'flags' is '[`Session; `Async]'. Explicit value '[`Session]' caused no async support on this API method.
The fix is to use the default value.

CA-388699: No async support on VM.restart_device_models

---

doc/content/toolstack/high-level/daemons.md
doc/content/xapi-guard/_index.md
ocaml/xapi-guard/lib/dorpc.ml
ocaml/xapi-guard/lib/dune
ocaml/xapi-guard/lib/server_interface.ml
ocaml/xapi-guard/lib/types.ml
ocaml/xapi-guard/lib/types.mli
ocaml/xapi-guard/src/main.ml

Currently, xapi-guard has a hard dependency on xapi being online to be able to start up and to be able to provide service to VMs (both varstore and swtpm).
This PR removes the first issue, and another PR will alleviate the second; of which the most problematic being stpm writes, which can happen at any time of the Vm lifetime.

CA-385323: Enable creating domain sockets while xapi isn't running

---

Makefile
ocaml/idl/datamodel_types.ml
ocaml/idl/schematest.ml

The Java SDK was failing to build due to 29f844cc6:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project xen-api: Compilation failure
[ERROR] /home/edvint/koji/toolstack-dev2/xapi.spec/scm/_build/install/default/xapi/sdk/java/xen-api/src/main/java/com/xensource/xenapi/APIVersion.java:[63,16] cannot find symbol
[ERROR]   symbol:   variable API_2_20
[ERROR]   location: class com.xensource.xenapi.APIVersion
[ERROR] -> [Help 1]
```
Draft PR, because I've only compile tested it, haven't tried whether the SDK actually works once built.

Xen-API Java SDK: fix the build (reintroduce 2.20 API version definition)

---

ocaml/networkd/bin/network_server.ml
ocaml/networkd/lib/network_utils.ml

Sysfs.list_drivers is returning the list of only PCI driver, so make it clear.
We want to support also USB cards so this change could avoid confusions in the future.

Make clear which drivers list we are getting

---

.codecov.yml

- It might need further tweaks, but it is a first step towards what I think we want Codecov to do.
- __Only add the Codecov comment to the PR when coverage changes__
-> You'll NOT see a Codecov comment in this PR!
-> The Codecov comment will be look like this:
https://github.com/xenserver-next/xen-api/pull/15#issuecomment-1937417257
- Removes not needed clutter from the Codecov PR comment:
- Details are collapsed, just click on the expand button to expand it.
- Give examples on how to configure how much code must be covered for Codecov to pass the coverage check of a PR.
- Disable adding coverage annotations to the code in the GitHub Code Review for now:
- The coverage can be visited using the Codecov link at all times:
https://app.codecov.io/gh/xapi-project/xen-api/pulls
- The …

Add .codecov.yml: It configures the Codecov PR comment and checks

---

.codecov.yml

This unblocks the latest PRs to xen-api

Adjust the codcov target for python unit tests

---

pyproject.toml
scripts/mail-alarm

- Format with black and isort
- Address the error raised by pytype
- Fix str.encode issue in python3
- Fix issue: json.load in python3 doesn't have 'encoding' paramteter
Auto Test Passed with ring3hostops.seq 3918348, ring3 bvt+bst 194002
Manual Test with three languages.

CP-47389 Porting mail-alarm to python3

---

ocaml/xapi-cli-protocol/cli_protocol.ml
ocaml/xapi-cli-server/cli_frontend.ml
ocaml/xapi-cli-server/cli_operations.ml
ocaml/xe-cli/newcli.ml

The commit is being reverted because:
1. It introduces a new CLI command "PrintUpdateGuidance" in an existing CLI interface "host-apply-updates". This breaks the use cases in which the old CLI clients are used.
2. The new CLI command "PrintUpdateGuidance" is a specific one. The commands used in CLI interfaces should be only for general purpose usage.
A comment is added around the type definition of CLI command for this as well.

Revert "CP-45572: Print update guidance in xe host-apply-updates"

---

ocaml/xapi-cli-protocol/cli_protocol.ml
ocaml/xapi-cli-server/cli_frontend.ml
ocaml/xapi-cli-server/cli_operations.ml
ocaml/xe-cli/newcli.ml
quality-gate.sh

There are more existing CLI clients using the current CLI protocol. It would be verbose to consider all of these CLI clients before adding backwards compatibility support in CLI server side.
So the current plan is revert all changes on the CLI protocol. In short term, the function will be implemented in server side completely.

CA-389206: Revert more changes in CLI protocol

---

.codecov.yml
.github/workflows/main.yml
pyproject.toml
python3/Makefile
python3/bin/hfx_filename
python3/unittest/import_file.py
python3/unittest/test_hfx_filename.py
scripts/Makefile

1. Create a new directory (python3/bin) for python3 scripts and move `hfx_filename` into it.
2. Migrate `hfx_filename` to python3.
3. Adjust CI check configurations to apply pytype check and unit test coverage to python3 scripts.
4. Added unit tests and covered all functions in hfx_filename.
5. Manually tested hfx_filename on XS8 to cover corner cases that not covered by unit tests:
- Use Flask to fake a HTTP server:
```
from flask import Flask, request
app = Flask(__name__)
@app.route('/remote_db_access', methods=['POST'])
def handle_request():
session_id = request.args.get('session_id')
data = "hotfix_filename"
prefix = "<value><array><data><value>success</value><value>"
suffix = "</value></data></array></value>"
response_body = f"{prefix}{data}{suffix}"
headers = {'Content-Type': …
```

py2->py3: hfx_filename

---

ocaml/tests/common/test_common.ml
ocaml/xapi-idl/xen/xenops_interface.ml
ocaml/xapi/cpuid_helpers.ml
ocaml/xapi/cpuid_helpers.mli
ocaml/xapi/create_misc.ml
ocaml/xenopsd/lib/xenops_server_skeleton.ml
ocaml/xenopsd/xc/xenops_server_xen.ml

Discussed here: https://github.com/xapi-project/xen-api/issues/5462

Add 'threads_per_core' in 'Host.cpu_info'

---

ocaml/networkd/lib/network_utils.ml

Different network card (like virtual ones or USB ones) do not have a vendor:product causing networkd daemon to report a lot of errors like
Error in read one line of file: /sys/class/net/eth0/device/device, exception Unix.Unix_error(Unix.ENOENT, "open", "/sys/class/net/eth0/device/device")
Raised by primitive operation at Xapi_stdext_unix__Unixext.with_file in file "lib/xapi-stdext-unix/unixext.ml", line 68, characters 11-40
Called from Xapi_stdext_unix__Unixext.buffer_of_file in file "lib/xapi-stdext-unix/unixext.ml" (inlined), line 155, characters 31-83
Called from Xapi_stdext_unix__Unixext.string_of_file in file "lib/xapi-stdext-unix/unixext.ml", line 157, characters 47-73
Called from Network_utils.Sysfs.read_one_line in file "ocaml/networkd/lib/network_utils.ml", line 156, characters …

CP-47754: Do not report errors attempting to read PCI vendor:product

---

scripts/xapi.service

:wave:
To give a little bit of context, I had a strange issue after building new RPMs (it was a new version of ZFS) and installing it. It appeared that `systemd` reported XAPI has failed. I looked more closely and the reason is because `/var/lock/subsys` directory is not present anymore (and the `touch /var/lock/subsys/xapi` command failed).  I didn't know exactly why this directory is not there but after discussing with several people it appears that it should be created by `systemd-tmpfiles-setup.service`. And in my case this service didn't start. To fix the issue one suggestion was to add `systemd-tmpfiles-setup.service` to be `Requires`+`After` in `xapi.service`. I think it makes sense and that is is the right way for fixing the issue but I was surprised that it wasn't already the …

Xapi service depends on systemd-tmpfiles-setup

---

Makefile
ocaml/sdk-gen/c/autogen/src/xen_common.c
ocaml/sdk-gen/c/gen_c_binding.ml

I was trying to build the XenAPI C SDK on master and it was failing like this on Fedora39:
```
src/xen_common.c: In function ‘xen_session_logout’:
src/xen_common.c:298:5: error: ‘xen_call_’ accessing 16 bytes in a region of size 0 [-Werror=stringop-overflow=]
298 |     xen_call_(session, "session.logout", params, 0, NULL, NULL);
|     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Although `params[]` there is a 0 sized array, AFAICT the code doesn't actually try to read from it (and `clang` is fine with compiling it as is). Could be a bug in GCC, or some corner case of the language (is a 0 sized array valid?).
To avoid any ambiguity replace it with NULL, if anything tries to access it then it will crash instead, and GCC doesn't raise any errors anymore and successfully …

Fix C SDK build on Fedora39

---

ocaml/xapi/locking_helpers.ml
ocaml/xapi/locking_helpers.mli
ocaml/xapi/xapi_session.ml
semaphore_vendored.ml

We are backporting a list of commits from master but drop the changes to the datamodel and instead use a hard-coded value.

Backport CP-43755 - rate limits for PAM logins

---

ocaml/xapi/xapi_host.ml
ocaml/xapi/xapi_pif_helpers.ml

- New pif helper: `get_non_link_ipv6` to get the 1st non link IPv6 of a PIF
- Use the helper in `migrate_receive` and `get_primary_address` used in host evacuation to have a valid IPv6 of the destination host

Filter out link IPv6 when migrating VMs

---

.github/workflows/main.yml
.github/workflows/shellcheck.yaml

It is not supported in scheduled runs, and fails: https://github.com/xapi-project/xen-api/actions/runs/8090127285/job/22107122716
I'm not sure how to define `on` for a given job, so move it to a separate workflow file instead.

fix(ci): Move differential shellcheck to its own workflow

---

.codecov.yml
.github/workflows/main.yml
Makefile
ocaml/libs/tracing/tracing.ml
ocaml/libs/tracing/tracing.mli
ocaml/tests/test_observer.ml
ocaml/xapi/xapi_observer.ml
pyproject.toml
python3/Makefile
python3/README.md
python3/packages/observer.py
python3/tests/test_observer.py
scripts/Makefile

Instead of being a noop, it will now automatically instrument the python
code given to it and create spans accordingly. The trace created will
link to the xapi code that called it. It will export to all endpoints
that it is given, which it reads from the observer.conf files created by
xapi.
This is built on top of https://github.com/xapi-project/xen-api/pull/5435 so please ignore the first two commits
For reviewers, by @bernhardkaindl:
- If you want to see the code (since Codecov adds annotations - it is not covered by a test at all), you've to press "a" to toggle the Codecov annotations off.
- I submitted #5455 to configure Codecov so you can see the code without togging the annotations off.
- It would be good to have some unit-test of course too, but this needs refactoring the code to …

CP-46151: Productise the observer.py

---

xapi.opam
xapi.opam.template

The latest xs-opam update seems to have removed the dependency since it's no longer an indirect one, adding it as a direct one should fix the build issues

opam: add hex to xapi dependencies

---

scripts/import-update-key

XS9 3943842
```
[08:13:19 04/03] SSH root@10.63.81.27 /opt/xensource/debug/import-update-key /opt/xenrt/keys/RPM-GPG-KEY-XS-Eng-Test.pub
gpg: key 7610CBCE078E581F: public key "XS Eng test key <XenServerEngineering@citrite.net>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: checking the trustdb
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   2  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 2u
pub  rsa2048/7610CBCE078E581F
created: 2024-01-08  expires: 2024-07-06  usage: SCEA
trust: unknown       validity: unknown
[ unknown] (1). XS Eng test key <XenServerEngineering@citrite.net>
pub  rsa2048/7610CBCE078E581F
created: 2024-01-08  expires: 2024-07-06  usage: SCEA
trust: unknown       validity: unknown
[ unknown] (1). XS Eng test …
```

CA-389241: import-update-key compat with xs8 and xs9

---

ocaml/sdk-gen/c/gen_c_binding.ml
ocaml/sdk-gen/c/gen_c_binding.mli
ocaml/sdk-gen/c/helper.mli
ocaml/sdk-gen/common/CommonFunctions.ml
ocaml/sdk-gen/common/CommonFunctions.mli
ocaml/sdk-gen/common/dune
ocaml/sdk-gen/common/license.mli
ocaml/sdk-gen/csharp/friendly_error_names.mli
ocaml/sdk-gen/csharp/gen_csharp_binding.ml
ocaml/sdk-gen/csharp/gen_csharp_binding.mli
ocaml/sdk-gen/java/autogen/xen-api/pom.xml
ocaml/sdk-gen/java/autogen/xen-api/src/main/java/com/xensource/xenapi/Connection.java
ocaml/sdk-gen/java/autogen/xen-api/src/main/java/com/xensource/xenapi/CustomDateDeserializer.java
ocaml/sdk-gen/java/autogen/xen-api/src/main/java/com/xensource/xenapi/EventBatch.java
ocaml/sdk-gen/java/autogen/xen-api/src/main/java/com/xensource/xenapi/JsonRpcClient.java
ocaml/sdk-gen/java/autogen/xen-api/src/main/java/com/xensource/xenapi/JsonRpcRequest.java
ocaml/sdk-gen/java/autogen/xen-api/src/main/java/com/xensource/xenapi/JsonRpcResponse.java
ocaml/sdk-gen/java/autogen/xen-api/src/main/java/com/xensource/xenapi/JsonRpcResponseError.java
ocaml/sdk-gen/java/autogen/xen-api/src/main/resources/README.txt
ocaml/sdk-gen/java/main.ml
ocaml/sdk-gen/java/main.mli
ocaml/sdk-gen/powershell/common_functions.ml
ocaml/sdk-gen/powershell/common_functions.mli
ocaml/sdk-gen/powershell/gen_powershell_binding.ml
ocaml/sdk-gen/powershell/gen_powershell_binding.mli
quality-gate.sh

I suggest reviewing commits one at a time.
I also suggest you check out and run the output, I have built it against my SDK tag, feel free to ask for info.
As discussed this makes use of Apache's client since the Java stdlib one was having issues with the connection pool.
I am however not exposing request configuration (except timeouts). This would be trivial-ish but I didn't want to add bloat.
I have only implemented sync calls for the HTTP client. We could add the option to pass callbacks to calls and make it fully async but it's out of scope and I didn't want to make reviews even longer. 
Other notable changes:
- Now using `HashSet` instead of the generic `Set` for relevant types
- Marshalling in `Types.java` and other places has mostly been replaced by type handling from Jackson's …

CP-45888: Replace XML-RPC client in Java SDK with JSON-RPC

---

ocaml/tests/test_sm_features.ml
ocaml/xapi/smint.ml

Backport of 2386ed7fee57380fadf949f9a8d1df8dbd376979
The association list SM.features frequently contains duplicate keys. This is problematic because they could bind to different values (which are versions in this case).
When parsing the features from a list of strings, eliminate duplicate keys. In addition, simplify the implementation and avoid duplicate work by using List.filter_map.

CA-368437 remove duplicate keys from SM.features

---

.github/workflows/1.249-lcm.yml
.github/workflows/docs.yml
.github/workflows/format.yml
.github/workflows/generate-and-build-sdks.yml
.github/workflows/hugo.yml
.github/workflows/main.yml
.github/workflows/release.yml

Update all `uses: actions/checkout@v3` to `@v4` (From Node 16 to Node 20)
All GitHub actions using Node 16 now issue a warning that they are deprecated. GitHub says:
> Node 16 has reached its [end of life](https://github.com/nodejs/Release/#end-of-life-releases), prompting us to initiate its deprecation process for GitHub Actions. Our plan is to transition all actions to run on Node 20 by Spring 2024.
Obviously, it will take much longer than the "Spring 2024", but we can fix the warnings by updating.
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

GitHub Actions: Update actions/checkout to v4 to fix Node 16 warnings

---

.github/workflows/generate-and-build-sdks.yml

This pull request updates the setup-dotnet actoin dependency from v3 (Node 16) to version v4 (Node 20) to fix Node 16 warnings.
----
All GitHub actions using Node 16 now issue a warning that they are deprecated. GitHub says:
> Node 16 has reached its [end of life](https://github.com/nodejs/Release/#end-of-life-releases), prompting us to initiate its deprecation process for GitHub Actions. Our plan is to transition all actions to run on Node 20 by Spring 2024.
Obviously, it will take much longer than "Spring 2024", but we can fix the warnings by updating.
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

GitHub Actions: Node 16 warning fixes: update setup-dotnet to v4

---

ocaml/sdk-gen/powershell/autogen/Initialize-Environment.ps1
ocaml/sdk-gen/powershell/autogen/src/CommonCmdletFunctions.cs
ocaml/sdk-gen/powershell/autogen/src/Connect-XenServer.cs
ocaml/sdk-gen/powershell/autogen/src/XenServerPowerShell.csproj

Before these changes, the `SaveCertificates` method relied on machines having a `SpecialFolder.MyDocuments` folder. This is true in Windows and GUI versions of some Linux distros, but it's an assumption that caused the save method to fail if the folder didn't exist.
With this commit, we're storing and reading from the path where `$PROFILE` is stored, which is platform agnostic from the point of view of the SDK.

CA-390109: Use `$PROFILE` path to store and read known cert list 

---

ocaml/quicktest/qt.ml
ocaml/quicktest/qt.mli
ocaml/quicktest/quicktest_vm_lifecycle.ml

As it stands this test uses the default SR even though user specifies one throught quicktest -sr, and fails when run on a pool with no default SR.
This makes it use the SR from command-line instead.
This is the master version of #5488.

Fix vm_lifecycle quicktest to use specified SR

---

ocaml/quicktest/qt.ml
ocaml/quicktest/qt.mli
ocaml/quicktest/quicktest_vm_lifecycle.ml

As it stands this test uses the default SR even though user specifies one throught `quicktest -sr`, and fails when run on a pool with no default SR.
This makes it use the SR from command-line instead.
This is the 1.249 version of #5489.

[1.249] Fix vm_lifecycle quicktest to use specified SR

---

ocaml/message-switch/cli/dune
ocaml/message-switch/cli/main.ml

Previously sub-second durations were printed as "ago", now they are pretty-printed using Mtime.Span's logic, for example "666ms ago".
If the point in time is unexpectedly in the future, print "0ns ago".
Durations lasting at least 1 seconds are printed as before.
These "ago" appear in the message_cli_diag.out from status reports, and are confusing to see, as they look like a bug. e.g.
```
- org.xen.xapi.xenops.classic
2999282: request from: xapi:2778 sent ago
- UPDATES.get
- {"last_id":2612584,"debug_info":"org.xen.xapi.xenops.classic events D:
- xapi:2778 is waiting for a response
```

message-switch: Print more complete time info in diagnostics

---

ocaml/libs/uuid/uuidx.ml
ocaml/libs/uuid/uuidx.mli
ocaml/xapi/sm.ml
ocaml/xapi/sm_exec.ml
ocaml/xapi/storage_smapiv1.ml
ocaml/xapi/xapi_vdi.ml
scripts/xe-backup-metadata
scripts/xe-restore-metadata

When creating a backup VDI on an SR we want to derive the VDI's UUID
from the SR. This way we can't be later tricked into accepting a
different VDI as a backup.
Implement a hash that derives the VDI UUID and pass this UUID to SM to
be used.
Currently the creation of this VDI in Xapi is detected based on its
name-label: "Pool Metadata Backup". The SM stack usually creates a new
random UUID but will use a given UUID passed as "vdi_uuid" for its
"vdi_create" command. The difficulty in the implementation is that
"vdi_uuid" is used in other commands as well and we have to make sure to
set it only in the intended context. It is not straight forward to pass
the UUID from Xapi_vdi.create down to Sm.
This will require an updated xapi.spec to package the changes.

CP-46179 Deterministic UUID for Back-Up VDI

---

.github/workflows/main.yml
python3/Makefile
python3/README.md
python3/dnf_plugins/accesstoken.py
python3/dnf_plugins/ptoken.py
python3/tests/stubs/dnf.py
python3/tests/test_dnf_plugins.py

XS9 does not have yum command, and yum plugin is used to add HTTP headers automatically for yum commands when
- access pool master repo. (ptoken)
- access remote repo for CDN udpate (accesstoken)
This is updating the yum plugins to corresponding DNF plugins, and enable dnf with the same functionality.
Test done:
- XenRT test
- XS9: 3961239.  (The suite cover sync updates from pool cordinator, thus covered the plugins)
- XS8: 3961239 (XS8 is not related, just run for sure)
Manul test:
- Add *print* in the plugins to make sure it is called.  For example.
`print("set ptoken: ", f'cookie:{secret}')`
`print("set accesstoken: ", access_token, "tokenid: ", referer)`
``` 
dnf --disablerepo=* --enablerepo=local-6192a1a6-cda9-4ba1-e4a6-e36148fcb239,local-e6445302-c68d-8154-647c-785d93e59307 …
```

CP-46944: Update yum plugins to dnf plugins

---

ocaml/forkexecd/lib/forkhelpers.ml
ocaml/forkexecd/lib/forkhelpers.mli

`waitpid_nohang` closes the socket by calling `waitpid` and then calls `clear_nonblock` on that socket, which fails.
`waitpid_nohang`'s policy around closing the socket is not obvious enough.  Make it more explicit by not calling waitpid but inlining this code and looking at the different cases. Also provide an option to never close the socket such that this resided with the caller - which is a cleaner protocol. The default behaviour is to still close the socket when the child process has terminated and not otherwise.

CA-378317 fix EBADF in waitpid_nohang

---

ocaml/xapi/stream_vdi.ml
ocaml/xapi/vhd_tool_wrapper.ml

With *hybrid source format in export, the following cases are supported:
1. nbdhybrid: QCOW2 -> NBD device in dom0 -> exported file
2. nbdhybrid: VHD -> NBD device in dom0 -> exported file
3. hybrid: VHD -> blktap device in dom0 -> exported file
The case 2 above can't support an optional parameter "base".
This parameter holds the ID of another VHD VDI. When it is passed, the
export will only write the differences between "source" and "base" to
the destination file.
As a short-term solution, in case 2 above, when the "base" is passed,
the source format is changed to "hybrid" in this commit.
This can work because:
1. the comparsion on blocks required by "base" is supported by "hybrid";
2. the raw data from NBD device and blktap (Frankentap) device are same;
3. the sparseness information of …

CA-384483: Can't export VDI to VHD file with base VDI

---

ocaml/tests/dune
ocaml/tests/suite_alcotest.ml
ocaml/tests/test_pkg_mgr.ml
ocaml/xapi/pkg_mgr.ml
ocaml/xapi/pkg_mgr.mli
ocaml/xapi/repository.ml
ocaml/xapi/repository_helpers.ml
ocaml/xapi/xapi_globs.ml
ocaml/xapi/xapi_pool.ml

Given XS9 has updated to dnf and no yum is available, xapi will choose package manager basing on following
- If dnf exists, use dnf
- otherwise, fallback to yum xapi just presume dnf or yum is available in the system.
Because xapi decides to use dnf or yum according to the running environment, this commit is compatible with yum/xs8 and dnf/xs9

CP-45921: Use dnf as package manager for XS9

---

ocaml/forkexecd/test/fe_test.ml
ocaml/forkexecd/test/fe_test.sh

Add some minor tests for forkexecd
- invalid path;
- input/output.
Make manual usage easier.

Minor forkexecd test changes

---

ocaml/xapi/gpg.ml

The default gpg public keyring database updated
- pubring.kbx for new gpg on XS9
- pubring.gpg for old gpg on XS8 Detect whether pubring.kbx exists and fallback to old one for XS8

CP-48221: Support new gpg for XS9 

---

scripts/varstored-guard.service

Domains using TPMs need to have SWTPM always available. Encode this information in the service file so the services are shut down at the correct time while powering off the hosts.
Some Xenserver internal tests were consistently failing without this change, I've verified this fixes it.
Prodding @rosslagerwall, he was interested in the fix

CA-390988: Prevent varstored-guard from shutting down while domains run

---

ocaml/xapi-aux/dune
ocaml/xapi-aux/uuidx.ml
ocaml/xapi-aux/uuidx.mli
ocaml/xapi/sm.ml
ocaml/xapi/sm_exec.ml
ocaml/xapi/storage_access.ml
ocaml/xapi/xapi_vdi.ml
scripts/xe-backup-metadata
scripts/xe-restore-metadata

We want to use a predictable VDI for metadata backup. This is the backport of that feature to Yangtze. 
* The existing shell scripts differ slightly between the branches and I've kept these changes.
* The UUIDX module does not exist in Yangtze; I created a minimal implementation for this backport to get UUIDv5.

CP-46179 backport for deterministic backup VDI

---

ocaml/message-switch/async/protocol_async.ml
ocaml/message-switch/core/dune
ocaml/message-switch/core/make.ml
ocaml/message-switch/core/s.ml
ocaml/message-switch/core_test/async/server_async_main.ml
ocaml/message-switch/core_test/basic-rpc-test.sh
ocaml/message-switch/core_test/concur-rpc-test.sh
ocaml/message-switch/core_test/dune
ocaml/message-switch/core_test/lwt/server_main.ml
ocaml/message-switch/lwt/protocol_lwt.ml
ocaml/message-switch/switch/switch_main.ml
ocaml/message-switch/unix/protocol_unix.ml

Reattempt of the revert #5388 of the original PR #5309, but be more conservative
make the previous concurrent processing of message switch optional. User has to use the `listen_p` method in order to use this feature. Didn't try to factor out the common code as the locking seems to be quite convoluted into the code itself, not easy to do. In the long run, we would want to remove the serial processing anyway.
Tested this on the vdi revert tests. The test seems to be happy now (after kicking off 30 of them), all I did in terms of the change was to add the `protect_connect` which disconnects the channel and returns an error. 
But still be a bit more conservative and not turning it on by default.

CP-47033: Make message switch concurrent processing optional

---

python3/packages/observer.py

OTEL_RESOURCE_ATTRIBUTES is in W3CBaggageFormat and thus uses %. ConfigParser attempts to interpolate these % signs but we want them to be left alone, so set interpolation=None

CA-391485: Avoid InterpolationSyntaxError by turning off interpolation

---

ocaml/forkexecd/lib/fe.ml
ocaml/forkexecd/lib/forkhelpers.ml
ocaml/forkexecd/lib/forkhelpers.mli
ocaml/forkexecd/src/child.ml

There's no need for suffix, Ocaml has different namespace for types. This was suggested as part of a code review.

Remove _t suffix for syslog_stdout_t type

---

ocaml/xapi/api_server.ml

Compile tested, draft because it needs some actual testing.

CA-381119: Use JsonRPC v2

---

ocaml/xenopsd/xc/domain.ml

Nested virt is not a supported feature yet, but when moving the setting from Xen to toolstack as part of the Xen-4.17 update I typoed the name of the setting.
It was platform/nested-virt in xenguest.patch before
Fixes: 664de7608d ("Xen-4.15+: CDF_NESTED_VIRT")
I'll also need to find another test to use that checks whether the feature works, the previous test that I used tested the feature by booting a guest, and checking that it has booted, without checking whether nested virt actually worked inside.

CA-389506: fix platform:nested_virt typo

---

ocaml/xenopsd/lib/xenops_utils.ml
ocaml/xenopsd/xc/xenops_server_xen.ml

Don't use string comparisons for versions, "17" < "2", but 17 > 2!
This setting prevents using `run_hotplug_scripts=true` (the default is still `false`, which says can lead to device timeouts, and indeed it does, I can't boot a single VM on this particular host).
I don't quite understand why udev won't run the xenopsd block script, but the fallback of having xenopsd run them doesn't work either.
This would've already affected 4.13 too (but not any versions between 4.3 and 4.9).

xenopsd: fix Xen version comparison. 4.17 is > 4.2, not lower!

---

ocaml/database/redo_log.ml

XAPI was just retrying endlessly in a loop saying "Could not find block device", but didn't raise any alerts that XenRT could detect.
Report the redo log broken the first time we fail due to the lack of a bloc k device (which would indicate something going wrong in SM).

redo_log: report redo log as broken if we cannot find the block device

---

ocaml/xapi-types/features.ml
ocaml/xapi-types/features.mli

Added the definition of VM anti-affinity feature, the anti-affinity feature ensures that specified virtual machines are not co-located on the same physical host within a virtualized environment, enhancing fault tolerance and availability.

CP-47660 define anti-affinity feature

---

scripts/extensions/pool_update.apply
scripts/extensions/pool_update.precheck

Testing done:
- Some manual test for `dnf install`, `xe update-apply`
- HfxBasic: 3981563
- SuppPackBasic: 3981564 (one failed with unrelated error)

Update update.precheck/apply to be compatible with yum and dnf

---

ocaml/message-switch/async/protocol_async.ml
ocaml/message-switch/async/protocol_async.mli
ocaml/message-switch/core/dune
ocaml/message-switch/core/mtest.ml
ocaml/message-switch/core/s.ml
ocaml/message-switch/core_test/dune
ocaml/message-switch/core_test/lock_test_async.ml
ocaml/message-switch/core_test/lock_test_lwt.ml
ocaml/message-switch/lwt/protocol_lwt.ml
ocaml/message-switch/lwt/protocol_lwt.mli
quality-gate.sh

The lock implementation for `protocol_async` was not correct, hence adding the test suggested by Edwin to trigger race.
Test works by trying to acquire a standard Ocaml mutex in a critical section provided by the `with_lock` implementation. This means that any failed attempt to acquire the lock implies the `with_lock` implementation does not provide mutual exclusion.

Add test for lock implementation in message_switch

---

ocaml/idl/datamodel.ml
ocaml/idl/datamodel_common.ml
ocaml/idl/datamodel_errors.ml
ocaml/idl/datamodel_vm.ml
ocaml/idl/datamodel_vm_group.ml
ocaml/idl/dune
ocaml/idl/schematest.ml
ocaml/tests/common/test_common.ml
ocaml/tests/suite_alcotest.ml
ocaml/tests/test_vm_group.ml
ocaml/xapi-cli-server/cli_frontend.ml
ocaml/xapi-cli-server/cli_operations.ml
ocaml/xapi-cli-server/record_util.ml
ocaml/xapi-cli-server/records.ml
ocaml/xapi-consts/api_errors.ml
ocaml/xapi/api_server.ml
ocaml/xapi/message_forwarding.ml
ocaml/xapi/xapi_vm.ml
ocaml/xapi/xapi_vm.mli
ocaml/xapi/xapi_vm_group.ml
ocaml/xapi/xapi_vm_group.mli
ocaml/xapi/xapi_vm_helpers.ml
ocaml/xe-cli/bash-completion
quality-gate.sh

CP-47304: [Toolstack] - Add data model for anti-affinity group
CP-47655: [Toolstack] - Associate/disassociate VM to/from anti-affinity group

CP-47304: Add anti-affinity groups to the datamodel

---

.github/workflows/1.249-lcm.yml
.github/workflows/format.yml

This needs updating the ocaml action, which might or might not need more disk space. I've added the disk-cleaning step just in case.
There's an equivalent PR for master branch, but it needs to change the scheduled run for yangtze, and it's easier to test it here/

ci: remove warnings about outdated node versions (yangtze)

---

ocaml/idl/datamodel.ml
ocaml/idl/datamodel_common.ml
ocaml/idl/schematest.ml
ocaml/xapi-cli-server/cli_frontend.ml
ocaml/xapi-cli-server/cli_operations.ml
ocaml/xapi-cli-server/record_util.ml
ocaml/xapi-cli-server/records.ml
ocaml/xapi/message_forwarding.ml
ocaml/xapi/xapi_pci.ml
ocaml/xapi/xapi_pci.mli
ocaml/xapi/xapi_pci_helpers.ml
ocaml/xapi/xapi_pgpu.ml
ocaml/xapi/xapi_pgpu.mli

As discussed here: https://github.com/xapi-project/xapi-project.github.io/pull/286
New methods:
- `PCI.disable_dom0_access`: Hide a PCI from dom0 kernel
- `PCI.enable_dom0_access`: Unhide a PCI from dom0 kernel
- `PCI.get_dom0_access_status`: Return a PCI device dom0 access status The answer is no longer based on a DB field but by comparing the `/proc/cmdline` and the xen cmdline.
Deprecated methods:
- `PGPU.disable_dom0_access`
- `PGPU.enable_dom0_access` The methods should be called on the PCI belonging to the PGPU instead
Deprecated field:
- `PGPU.dom0_access`
The deprecated methods still work since they now call the PCI methods. The PGPU field is kept up to date with the statuss returned by the PCI methods.
Corresponding xe CLI calls have been implemented.

PCI passthrough API

---

ocaml/libs/sexpr/sExpr.ml

It was allocating a string for each character, only to then immediately add it to a buffer. Instead add the character to the buffer directly.
The temporary string was probably created to factor out 'Buffer.add', but I'd rather copy Buffer.add 4x times than have the perf hit.
Further optimizations might be possible here as the comments says, but this is a low-risk, obvious optimization.
Before (see how Buffer.add_string and caml_alloc_string take up quite a bit of time):
After: (Buffer.add_string completely gone, no more alloc_string, and the Sexpr.escape is narrower)
In fact we can take this a bit further and check for the presence of escapable characters when escaping and for the presence of the escape character when unescaping. Notice how Sexpr.escape is a lot narrower now, and …

IH-553: Optimize Sexpr.{escape,unescape}

---

ocaml/xapi/xapi_vm_group.ml

In VM anti-affinity [datamodel PR](https://github.com/xapi-project/xen-api/pull/5546), there is many-many relation between VMs and VM groups. When changing the VM.groups manually, the VM_group.VMs will be updated automatically. But when removing a VM group, the VM.groups will not be updated automatically. This commit aims to update VM.groups for all VMs in a VM group when it is being removed.

CA-391880: Update related field 'groups' of VM when destroying VM group.

---

scripts/xe-toolstack-restart

varstord-guard has following configuration in the service file
After=message-switch.service syslog.target
This means varstored-guard needs to be stopped before message-switch, otherwise, it will hung and finally be killed by systemd during xe-toolstack-restart

CA-391859: Failed to stop varstord-guard

---

.github/workflows/1.249-lcm.yml
.github/workflows/docs.yml
.github/workflows/hugo.yml
.github/workflows/main.yml
.github/workflows/release.yml
pyproject.toml
python3/packages/observer.py
python3/tests/test_observer.py
pytype_reporter.py

Current CI setup generates a lot of messages for master branch which are not relevant: deprecation warnings regarding node, annotations produced for python2 code which is yet to be cleaned up, and comments with sometimes thousands of lines long after the PRs are merged.
This PR tries to remove all of them. This needs reviewing by the team doing the python3 porting to confirm this won't harm their efforts. I've adapted Bernhard's PR #5504 to include the current ignored issues to reduce friction, but it might need another pass. @liulinC @stephenchengCloud 
The changes in the LCM CI follow the ones in #5574
TODO:

ci: reduce noise generated for PRs

---

ocaml/tests/test_vm_helpers.ml
ocaml/xapi/xapi_vm_helpers.ml

VM in an anti-affinity group will choose a host based on the following steps:
1. If the VM is associated with an anti-affinity group, compute the amount
of VMs associated with this anti-affinity group for each host.
2. Group these hosts based on the VM's amount. The hosts with the same VM
amount are in the same group. Sort all the host groups ascending based on
the VM's amount.
3. If a host is an affinity host for this VM, it will be treated as a single
host group and be put on the head of the group list.
4. Choose a host which the VM can run on it from each group.

CP-47302: VM start with anti-affinity

---

Makefile
ocaml/xcp-rrdd/bin/rrdp-dcmi/dune
ocaml/xcp-rrdd/bin/rrdp-dcmi/rrdp_dcmi.ml
ocaml/xcp-rrdd/bin/rrdp-scripts/sysconfig-rrdd-plugins

Tested on Dell PowerEdge R750, and a few other systems seem to have this data too, e.g. SuperMicro.
Draft pull request, because there are occasional issues where ipmitool fails to report anything (usually happens if you query it too often in a row), but seems fine with the 5s interval:
```
DCMI request failed because: Unspecified error (ff)
```
Starting a workload on an otherwise idle system resulted in an increase from 309W to 489W, so it seems to be working.
We might want to do a bit more sanity testing, e.g. there are known buggy firmwares that always return 0 W or 65535 W, and we should stop running in that case if that happens right after we call 'discover'.
Also XenCenter doesn't recognize the units (W), so that might need some work.

IH-543: Add IPMI DCMI based power reading rrdd plugin

---

README.markdown

- Removes large package listing from build instructions.
- Adds explanation about tags when working from a clone of a fork of the repo.
- Includes miscellaneous changes to wording.

Update README with different build instructions

---

ocaml/xapi/xapi_vm_snapshot.ml

When reverting to a snapshot, "groups" needs to be in `do_not_copy` to reserve the latest value of the VM.

CA-392177: Keep current group after reverting from snapshot

---

Makefile

xapi-tracing-export is a new library separated from xapi-tracing. This library is needed by xapi-clusterd (and probably other components that require tracing as well). So install it as a library in the Makefile.

Install xapi-tracing-export library

---

ocaml/xapi/dbsync_master.ml

Clear all (stale) scheduled assignments for: VM, PCI, VGPU objects on startup. We were missing the latter two.

CA-392163 clear scheduled assignments on startup

---

ocaml/idl/datamodel_pool.ml
ocaml/idl/datamodel_types.ml
ocaml/idl/datamodel_types.mli
ocaml/idl/datamodel_values.ml
ocaml/idl/datamodel_vm.ml
ocaml/idl/json_backend/gen_json.ml
ocaml/idl/ocaml_backend/gen_api.ml
ocaml/idl/schematest.ml
ocaml/sdk-gen/csharp/gen_csharp_binding.ml
ocaml/xapi-cli-server/cli_operations.ml
ocaml/xapi/import.ml
ocaml/xapi/xapi_vm.ml
ocaml/xapi/xapi_vm.mli
ocaml/xapi/xapi_vm_clone.ml
ocaml/xapi/xapi_vm_helpers.ml
ocaml/xapi/xapi_vm_migrate.ml
ocaml/xapi/xapi_vm_snapshot.ml
quality-gate.sh

The API call VM.set-has-vendor-device used to be a lincensed feature but it no longer is. As a first step to simplify when Windows VMs automatically or not update device drivers, remove the license checks in the code. The feature flag still remains in place.

CA-371529 XSI-1329 remove license check for has-vendor-device

---

ocaml/forkexecd/lib/fecomms.ml
ocaml/forkexecd/lib/forkhelpers.ml
ocaml/forkexecd/lib/forkhelpers.mli
ocaml/libs/tracing/tracing.ml
ocaml/libs/tracing/tracing.mli
ocaml/xapi/sm_exec.ml
ocaml/xapi/xapi_observer_components.ml
ocaml/xapi/xapi_observer_components.mli

Instrument:
- `forkhelpers.ml`,
- `fecomms.ml`
to create spans around functions when a parent span is supplied as `tracing`.
As follow-up to https://github.com/xapi-project/xen-api/pull/5551

CP-48195: Instrument client side of `forkexecd`

---

ocaml/sdk-gen/common/CommonFunctions.ml
ocaml/sdk-gen/go/gen_go_binding.ml
ocaml/sdk-gen/go/gen_go_helper.ml
ocaml/sdk-gen/go/templates/APIErrors.mustache
ocaml/sdk-gen/go/templates/APIMessages.mustache
ocaml/sdk-gen/go/templates/APIVersions.mustache
ocaml/sdk-gen/go/templates/Option.mustache
ocaml/sdk-gen/go/templates/Record.mustache
ocaml/sdk-gen/go/test_data/api_errors.go
ocaml/sdk-gen/go/test_data/api_messages.go
ocaml/sdk-gen/go/test_data/api_versions.go
ocaml/sdk-gen/go/test_data/record.go
ocaml/sdk-gen/go/test_gen_go.ml

1. update templates (APIErrors, APIMessages, Record)
2. use right reserved words
1. add templates for options and APIVersion
2. render options and APIVersion

CP-48855: fix go lint var-name warnings

---

.codecov.yml

A small update of `.codecov.yml` (config file for Coverity):
Update the Coverity config to clean up obsolete python2 coverage components.

feature/py3: Cleanup obsolete python2 components in Coverity

---

ocaml/idl/datamodel_lifecycle.ml
ocaml/xcp-rrdd/bin/rrdp-iostat/rrdp_iostat.ml
xapi-idl.opam
xapi-idl.opam.template
xapi-xenopsd.opam
xapi-xenopsd.opam.template

Do not output loglines that are part of the normal operation. Use debug for them, they are not usually logged, but can be enabled if need be by changing the loglevel

CP-48969: Reduce amount of logspam created by iostat

---

ocaml/idl/datamodel_errors.ml
ocaml/xapi-consts/api_errors.ml
ocaml/xapi/xapi_pool_helpers.ml

The query on HTTP endpoint /updates will return the available updates in JSON format. Prior to the changes in this commit, if a query arrives when another query is being handled, a "GET_UPDATES_IN_PROGRESS" error will be returned immediately. This behaviour is not friendly to GUI client XenCenter.
In this commit, the behaviour is changed to wait and retry in handling the query in xapi since the "*_IN_PROGGRESS" error is a transient failure. Tolerating it in xapi (server) side avoids error handling in client side.

CA-389319: Wait and retry for GET_UPDATES_IN_PROGRESS

---

ocaml/xapi/message_forwarding.ml

As part of a start, resources are allocated for a VM in "scheduled_to.." fields. These need to be cleared if the start fails. It turned out that this was incomplete for PCI slots and those were leaking. This patch tries to be more systematical about it.

CA-392163 on start failure, clear a VM's resource allocations

---

ocaml/sdk-gen/java/autogen/xen-api/src/main/java/com/xensource/xenapi/Connection.java
ocaml/sdk-gen/java/main.ml

After the latest changes of the SDK, some of the API isn't matching ⬇️ 
- Use `Types.checkError` instead of throwing a generic `XenAPIException`. This ensures the `Types.XYZ` family of exceptions is being used
- Use `@JsonValue` to ensure base class objects are deserialised as a simple opaque_ref string, as opposed to a mapping of each field. This ensures the API's behaviour is unchanged.
- Parse the results of `task.getResult` calls. The jsonrpc method returns value payloads of the form `"value" : "<value>OpaqueRef:XYZ</value>"` so we need to strip the surrounding XML

[ASAP] CA-392453: Misc fixes to Java SDK

---

ocaml/xenopsd/scripts/pygrub-wrapper

From Xen 4.19 onwards the legacy paths disappeared and the only valid path for pygrub is /usr/libexec/xen/bin/pygrub. This path has always been preferred, but now it's mandatory.

xenopsd/scripts: Make pygrub wrapper use the libexec path

---

ocaml/xapi-consts/api_messages.ml
ocaml/xapi/message_forwarding.ml
ocaml/xapi/pool_features.ml
ocaml/xapi/pool_features_helpers.ml
ocaml/xapi/pool_features_helpers.mli
ocaml/xapi/xapi_host.ml
ocaml/xapi/xapi_pool.ml
ocaml/xapi/xapi_vm_group_helpers.ml
ocaml/xapi/xapi_vm_group_helpers.mli
ocaml/xapi/xapi_vm_lifecycle.ml
ocaml/xapi/xapi_vm_migrate.ml

This PR introduces the generation of breach alerts during operations on VMs or groups, triggered when all VMs within a group are breached (i.e., placed on the same host).
Test scenarios covered in this PR include:
- Starting and resuming a VM triggers a breach alert if it is breached.
- Stopping and suspending a VM dismisses the breach alert if it is no longer breached.
- Migrating a VM, whether causing or resolving a breach, generates or dismisses the alert respectively.
- Moving a VM from one group to another triggers a breach alert if either group is breached.
- Destroying a VM group dismisses all related breach alerts.
- Changing the license from Premium to Standard dismisses all breach alerts, while changing from Standard to Premium generates them.
Additionally, the `pool_feature` …

CP-47656 VM anti-affinity generate breach alert

---

ocaml/sdk-gen/go/gen_go_helper.ml
ocaml/sdk-gen/go/gen_go_helper.mli
ocaml/sdk-gen/go/test_gen_go.ml

fix variable naming, such as "uUID", "pIF", "vM"

CP-49350: fix variable naming in Go SDK

---

ocaml/xapi/xapi.ml
ocaml/xapi/xapi_globs.ml

New XAPI conf option: `disable-webserver` (default: false) 
If true, all requests for the fileserver will get a 403 response.

Add option to disable fileserver in XAPI conf

---

ocaml/libs/tracing/tracing.ml
ocaml/libs/tracing/tracing.mli
ocaml/xapi/context.ml
ocaml/xapi/context.mli
ocaml/xapi/xapi_session.ml

Instruments `xapi_session.ml` to create span around session logins.
Adds new attribute for spans:
- `xs.xapi.session.originator`
where available.

CP-49029: Instrument `xapi_session.ml`  with tracing

---

ocaml/xapi/import.ml

The VM power state should be preserved on a suspended VM import.
In commit ebb58a8, the power state and suspend VDI in `vm_record` were
reset on importing a suspended VM. This meant to facilitate the
following `Client.VM.create_from_record`. But this gets the restore of
power state and suspend VDI broken as it requires the data in
`vm_record`.
This commit preserves the data in `vm_record` and reset it just before
it being passed to `Client.VM.create_from_record`.

CA-392836,CA-392847: Lost the power state on suspended VM import

---

ocaml/libs/stunnel/stunnel.ml
ocaml/squeezed/src/squeeze_xen.ml
ocaml/xe-cli/newcli.ml
ocaml/xenopsd/cli/xn.ml
ocaml/xenopsd/xc/memory_breakdown.ml
ocaml/xenopsd/xc/memory_summary.ml

These do not convert to epoll, but instead:
* converts selects with a delay to Thread.delay / Unix.sleepf (depending on whether the module links `threads.posix` already or not)
* deletes one completely unnecessary select
There are a few more commits like this (e.g. replace one `proxy` function with another, or replace one `Delay` module with another, but I'd rather do more testing on those, even if they are seemingly low risk / correct).
For now `feature/perf` has already accumulated quite a few changes, that we should probably test + merge before putting more `epoll` content in (and then when we add epoll those same tests should still pass). 
Draft PR, waiting on a BVT just in case.

Low risk Unix.select changes

---

ocaml/forkexecd/lib/forkhelpers.ml
ocaml/forkexecd/test/fe_test.ml

Make sure we release the `sock` file descriptors in all cases.
Add test trying to reproduce the issue passing an invalid file descriptor; not a perfect reproduction but failure in this function can happen for instance if daemon is restarted.

Remove possible file descriptor leak if safe_close_and_exec fails

---

ocaml/xapi/xapi_clustering.ml
ocaml/xapi/xapi_fist.ml

This forces the failure on a host that is trying to perform corosync upgrade. There are ways to recover: if the failure happens early, before the cluster is created in the DB, then a recreate ought to fix the problem. This happens when the corosync upgrade fails on the coordinator.
If the failure happens after the cluster is created on a pool member, then a `pool-resync` should help retry this upgrade.
Hopefully this can simulate some of the failure paths, but is by no means exhaustive. Other more complicated failures are not easily recoverable and therefore not simulated for now.

CP-49635: Add FIST point for corosync upgrade

---

ocaml/idl/datamodel_pool.ml
ocaml/idl/schematest.ml
ocaml/tests/common/test_common.ml
ocaml/xapi-cli-server/records.ml
ocaml/xapi/dbsync_master.ml
ocaml/xapi/recommendations.ml
ocaml/xapi/recommendations.mli
ocaml/xapi/xapi_globs.ml

1. Add a field 'recommendations' in pool.
2. The recommendations are read from files `/etc/xapi.pool-recommendations.d/*` and exposed to clients. They are read-only and only for clients, hence they don't impact the behavior of Xapi directly but only indirectly as they inform a client's behavior.
3. When Xapi starts, it will read each file and update the recommendations into the database. 
4. If we need to add recommendations to other type objects e.g. host, VM, etc in the future, just add a similar `xapi.*-recommendations.d` directory and define the path in xapi_globs.

CP-48570: Load recommendations from config file when Xapi starts

---

ocaml/xapi-types/features.ml
ocaml/xapi-types/features.mli
ocaml/xapi/xapi_vm.ml
ocaml/xapi/xapi_vm_group.ml
ocaml/xapi/xapi_vm_group_helpers.ml
ocaml/xapi/xapi_vm_group_helpers.mli
ocaml/xapi/xapi_vm_helpers.ml

Check feature flag in these places:
1. VM start.
2. Host evacuation. When this PR is raised, the host evacuation PR is
still in review. So this PR doesn't include the checking for host
evacuation. **It will be included in another new PR.**
3. Create VM group.
4. VM.set_groups. Adding VMs to a group and removing VMs from a group
are all forbidden. If customers need to remove VMs from a group,
just destroy the group.
5. Send VM anti-affinity alerts.
Also, based on our discussion, the name of feature is changed from
`VM_anti_affinity` to `VM_group`.

CP-48011: XAPI Support anti-affinity feature check

---

ocaml/tests/test_host.ml
ocaml/tests/test_xapi_xenops.ml
ocaml/xapi/xapi_host.ml

CVM had been supported but not since long time ago.
This commit is to clean up the remanent code and test cases.

Remove CVM and relevant test cases

---

ocaml/xapi-types/features.ml
ocaml/xapi-types/features.mli

Based on the discussion, the feature name has been changed from `vm_anti_affinity `to `vm_group`. Therefore, the feature definition about `vm_anti_affinity `should be removed.
The new feature flag and its control logic will be developed based on the new feature name.

CP-49668: Revert definition of the old 'vm_anti_affinity' feature flag

---

ocaml/idl/datamodel_vm.ml
ocaml/xapi/xapi_vm.ml

Control domains, templates, and snapshots cannot be added to VM groups.

CA-393421: Special VMs cannot be added to VM groups

---

.golangci.yml
ocaml/sdk-gen/go/autogen/src/jsonrpc_client.go
ocaml/sdk-gen/go/gen_go_helper.ml
ocaml/sdk-gen/go/templates/ConvertTime.mustache
ocaml/sdk-gen/go/templates/Record.mustache
ocaml/sdk-gen/go/test_data/record.go
ocaml/sdk-gen/go/test_data/time_convert.go
ocaml/sdk-gen/go/test_gen_go.ml

CP-49707: Go SDK: Add JSON tag for structs
This aims to allow a Go SDK client to unmarshal JSON to Go structs with
the function in Go json pacakge instead of using Go SDK.
The unmarshalling in Go SDK contains two steps: JSON -> map -> struct.
This is because some special cases need to be handled explicitly.
But for sake of safety, this unmarshalling is not exposed to clients.
CP-49349: Go SDK: Append UTC timezone to unix timestamp
The date time in Go requires a date time with timezone info. But XAPI
may return a UNIX timestamp to clients.
This commit blindly adds a UTC timezone for UNIX timestamps returned
from XAPI server.
CP-49349: Go SDK: Allow spaces in special value of float type
Some special values of float standing in JSON are handled specifically.
This commit allows the special …

Go SDK: Misc fixes for on-going component tests

---

ocaml/idl/datamodel_pool.ml
ocaml/idl/datamodel_vm.ml
ocaml/xapi-cli-server/cli_frontend.ml
ocaml/xapi-cli-server/cli_operations.ml
ocaml/xapi-cli-server/record_util.ml
ocaml/xapi/helpers.ml
ocaml/xapi/message_forwarding.ml
ocaml/xapi/xapi_globs.ml
ocaml/xapi/xapi_pool.ml
ocaml/xapi/xapi_pool.mli
ocaml/xapi/xapi_vm.ml
ocaml/xapi/xapi_vm.mli

Implement what's discussed  here: https://github.com/xapi-project/xen-api/issues/5548
New API calls:
- `VM.set_uefi_mode`: calls `varstore-sb-state` to edit the uefi mode of a VM
Takes in input the uuid of a VM and a mode (`setup` or `user`)
Returns the output of the script calls
- `VM.get_secureboot_readiness` API call
Returns the SecureBoot status of a VM:
- `not_supported`: VM's firmware is not UEFI
- `disabled`: Secureboot is disabled on this VM
- `first_boot`: Secured boot is enabled on this VM and its NVRAM.EFI-variables is empty
- `ready`: Secured boot is enabled on this VM and PK, KEK, db and dbx are defined in its EFI variables
- `ready_no_dbx`: Secured boot is enabled on this VM and PK, KEK, db but not dbx are defined in its EFI variables
- `setup_mode`: Secured boot is enabled …

New API methods for status about SecureBoot and UEFI certs

---

ocaml/idl/datamodel.ml
ocaml/idl/datamodel_common.ml
ocaml/idl/schematest.ml
ocaml/xapi-cli-server/cli_operations.ml
ocaml/xapi-idl/storage/storage_interface.ml
ocaml/xapi/xapi_sr.ml

Currently, the storage layer tracks two extra SR health statuses that XAPI is unaware of. These are "unreachable" and "unavailable". At present, the storage side simply maps these to "recovering" when sending information to the toolstack. This change will allow XAPI to track more accurate SR health statuses.
See this excerpt from `xapi-storage-plugins` (`util.py`) which maps these new constructors to the extant "recovering" enum.
```py
def sr_status_to_xapi(sr_status):
"""
Convert the SR statuses we know internally into a String which XAPI understands.
This small layer of indirection allows us to experiment with more states than XAPI
knows of internally, until such time as XAPI is ready to learn of them.
"""
if sr_status == SR_STATUS_OK:
return "Healthy"
if sr_status == …
```

CP-49446: Update SR health to include new constructors

---

ocaml/tests/test_ha_vm_failover.ml
ocaml/xapi/dune
ocaml/xapi/xapi_ha_vm_failover.ml
ocaml/xapi/xapi_ha_vm_failover.mli
ocaml/xapi/xapi_vm_helpers.ml
xapi.opam
xapi.opam.template

Host evacuation plan with anti-affinity support will be carried out in 3 phases:
1. Try to get a "spread evenly" plan for anti-affinity VMs, done if
all the rest VMs got planned using binpack, otherwise continue.
2. Try to get a "no breach" plan for anti-affinity VMs, done if all the rest VMs
got planned using binpack, otherwise continue.
3. Carry out a binpack plan ignoring VM anti-affinity.

CP-49665: VM anti-affinity support for host evacuation - implemented with Psq

---

ocaml/xapi-types/features.ml
ocaml/xapi-types/features.mli
ocaml/xapi/xapi_ha_vm_failover.ml
ocaml/xapi/xapi_vm.ml
ocaml/xapi/xapi_vm_group.ml
ocaml/xapi/xapi_vm_group_helpers.ml
ocaml/xapi/xapi_vm_group_helpers.mli
ocaml/xapi/xapi_vm_helpers.ml

1. Rename feature flag VM_group to VM_groups.
2. Add feature check in host evacuation

CP-48011: Xapi Support anti-affinity feature flag

---

ocaml/libs/http-lib/http.ml
ocaml/libs/http-lib/http.mli
ocaml/xapi-cli-server/cli_operations.ml
ocaml/xapi-cli-server/cli_util.ml
ocaml/xapi/create_misc.ml
ocaml/xapi/dbsync_master.ml
ocaml/xapi/export.ml
ocaml/xapi/import.ml
ocaml/xapi/importexport.ml
ocaml/xapi/rrdd_proxy.ml
ocaml/xapi/sm_fs_ops.ml
ocaml/xapi/xapi_host.ml
ocaml/xapi/xapi_message.ml
ocaml/xapi/xapi_vm_migrate.ml
ocaml/xapi/xapi_xenops.ml

For improved IPv6 compatibility, use URI to build URIs. In particular, this will take care of bracketing IPv6 addresses in URIs.

CP-49647 use URI to build URIs

---

ocaml/xapi/extauth_plugin_ADpbis.ml

The domain information is cached by PBIS. Such cache can help to accelerate query of domain information.
However, the cache data should be cleaned during disable external auth to make sure
- release cache as the domain is left
- rejoin domain refresh all the domain information

CA-393199: Disable external auth should clean pbis cache

---

python3/packages/observer.py
scripts/examples/python/XenAPI/XenAPI.py

Instrument `XenAPI.py` to submit the current traceparent back into xapi if it can import `opentelemetry`.
Currently, we don't see the traces of `sm` calling back to `xapi` using `XenAPI.py`. This will instrument `XenAPI.py` to pass a traceparent into `xapi` when opentelemetry is available.

CP-48995: Instrument `XenAPI.py` to submit a `traceparent`

---

ocaml/xapi-cli-server/xapi_cli.ml
ocaml/xe-cli/newcli.ml

Adds the possibility of `xe` commands to pass a `traceparent`.
This can be done through the following ways:
- a command arg: `xe <cmd> --traceparent <traceparent>` (or `xe <cmd> traceparent=<traceparent>`);
- a environment variable: `TRACEPARENT=<traceparent>`:
- specifying `traceparent=<traceparent>` in `.xe`.
Priority is given in the same order as above.
This should enable creating a single trace from the `xe-cli` caller through `xapi`.

CP-45235: Support for `xe-cli` to transmit `traceparent`

---

ocaml/xapi-idl/cluster/cluster_interface.ml

Add a `@default` attribute to the `cluster_stack` field in the cluster config. This field was introduced in #c1bd0e31a but causes RPU to fail since it is not optional, and while xapi-clusterd was unmarshalling an old db (which contains cluster config), it cannot find this field, and throws an exception.
Adding `@default` can make the rpc library to fill this field in when it is missing, solving the above problem.
Manul test looks ok, waiting for xrt tests.

CA-393507: Default cluster_stack value

---

.pre-commit-config.yaml
pyproject.toml

To: @stephenchengCloud and @liulinC: for you to review.
Cc: @ashwin9390 pre-review results with Ashwin:
- Ashwin suggested an improvement to make the pytest report less verbose using `-ra` (applied!)
The motivation and purpose for this PR is to allow running `pytest` for a given file. Example:
```py
pytest python3/tests/test_hfx_filename.py
=================================== test session starts ===================================
platform linux -- Python 3.11.9, pytest-8.2.1, pluggy-1.5.0 -- /usr/bin/python3.11
[...]
python3/tests/test_hfx_filename.py::TestRpc::test_db_get_uuid PASSED                [ 20%]
[...]
python3/tests/test_hfx_filename.py::TestParse::test_parse_string PASSED             [100%]
========================================= PASSES …
```

CI/coverage: Fix addopts, migrate away from pytest-cov

---

ocaml/sdk-gen/java/autogen/xen-api/src/main/java/com/xensource/xenapi/JsonRpcClient.java

Example usage where `Infinity` is reported, corresponding to `Double.POSITIVE_INFINITY` 👇

CA-393866: Add support for Infinity in Java SDK parser

---

ocaml/xapi/xapi_vm_migrate.ml

This is unnecessary overhead for traffic that does not actually hit the network.

CA-393119: Don't use HTTPS for localhost migrations

---

.github/workflows/setup-xapi-environment/action.yml
doc/content/xapi/storage/_index.md
ocaml/doc/wire-protocol.md
ocaml/xapi-storage-script/examples/datapath/block/Datapath.activate
ocaml/xapi-storage-script/examples/datapath/block/Datapath.attach
ocaml/xapi-storage-script/examples/datapath/block/Datapath.deactivate
ocaml/xapi-storage-script/examples/datapath/block/Datapath.detach
ocaml/xapi-storage/python/Makefile
ocaml/xapi-storage/python/examples/datapath/loop+blkback/datapath.py
ocaml/xapi-storage/python/examples/datapath/loop+blkback/plugin.py
ocaml/xapi-storage/python/examples/volume/org.xen.xapi.storage.simple-file/plugin.py
ocaml/xapi-storage/python/examples/volume/org.xen.xapi.storage.simple-file/sr.py
ocaml/xapi-storage/python/examples/volume/org.xen.xapi.storage.simple-file/volume.py
ocaml/xapi-storage/python/xapi/__init__.py
ocaml/xapi-storage/python/xapi/storage/__init__.py
ocaml/xapi-storage/python/xapi/storage/api/__init__.py
ocaml/xapi-storage/python/xapi/storage/api/v5/__init__.py
ocaml/xapi-storage/python/xapi/storage/common.py
pyproject.toml
scripts/examples/python/mini-xenrt.py
scripts/examples/python/provision.py
scripts/examples/smapiv2.py

Main ticket:CP-47869 -Clean up XAPI code  
Sub task :CP-49681
- Convert the existing code to python3 in XAPI
Split2 from https://github.com/xapi-project/xen-api/pull/5662
Test done in PR 5662 holds good.
Test result -198930 (Dev Run)
Ring0 BST - 8.4.0-206415 (pbb-ashwinh-xapiclean) (repo) run 30 May 2024
Tests Executed (excludes blocked): 47
Tests Failed: 1
Tests Errored: 0
Tests Blocked: 0
Tests Not Executed: 0
Test failed due to production issues: 0
Pass rate (excluding failures due to non product issues): 100.0%
Pass rate (of testcases XenRT was able to resource): 97.9%
Pass rate (of all test cases): 97.9%
Percentage of nightly complete: 100.0%
Tests excluded from numbers: 0
@liulinC @stephenchengCloud @psafont

#PR2- CP-47869-Update XAPI code to python3.

---

dune-project
ocaml/database/dune
ocaml/libs/sexpr/dune
ocaml/libs/sexpr/sExpr_TS.ml
ocaml/libs/sexpr/test/dune
ocaml/libs/sexpr/test/test_sexpr.ml
ocaml/xenopsd/cli/dune
quality-gate.sh

Add @contificate unit test that demonstrates the limitations of  `ocamlyacc`'s concurrency.
Change from `ocamlyacc`  to `menhir`
Drop the global lock around `sexpr` parsing to improve performance.

CP-49129: Drop global lock around sexpr parsing

---

ocaml/libs/sexpr/test/dune
sexpr.opam.template
wsproxy.opam
wsproxy.opam.template

qcheck is in the wrong part of xs-opam currently, and although we're moving it this test really only needs qcheck-core, so link only that to fix an internal CI failure.

Link just qcheck-core, not qcheck

---

ocaml/sdk-gen/go/README.md
ocaml/sdk-gen/go/autogen/src/jsonrpc_client.go
ocaml/sdk-gen/go/gen_go_binding.ml
ocaml/sdk-gen/go/gen_go_helper.ml
ocaml/sdk-gen/go/gen_go_helper.mli
ocaml/sdk-gen/go/templates/FileHeader.mustache
ocaml/sdk-gen/go/templates/Methods.mustache
ocaml/sdk-gen/go/templates/SessionMethod.mustache
ocaml/sdk-gen/go/test_data/file_header.go
ocaml/sdk-gen/go/test_gen_go.ml

Based on the comments in https://github.com/xapi-project/xen-api/pull/5679, following changes are in this series:
1. Fix phrasing in readme
2. Add licence text on top of Go source files
3. Remove template variables 'first' and 'is_session_id'

Several fixes for XenServer SDK for Go

---

ocaml/libs/sexpr/dune
ocaml/libs/sexpr/test/dune
sexpr.opam

Remove `package` and `public_name` stanzas for `sexprpp` executable.

rpm: remove `sexprpp` from public_name

---

.github/workflows/other.yml

Main task : CP-49100- Move all scripts from scripts folder to python3 folder and modify Makefile to include these changes.
Subtask: CP-49934 -Remove python2.7 test upload coverage as we don't require this anymore for python3 code.
@psafont @liulinC @stephenchengCloud

CP-49934-Remove python2.7 test coverage.

---

doc/content/python/_index.md
pyproject.toml

Updated comments and documentation for the Python3 feature branch `feature/py3`:
- Add documentation for my last PR to https://xapi-project.github.io/new-docs/:
- Spell-checked and `markdownlint`-ed: [doc/content/python/_index.md](https://github.com/xapi-project/xen-api/blob/ab359a77da34e7f0a078497f545a238e6b7936d2/doc/content/python/_index.md) 
- Page for review at the preview site of the PR: https://xenserver-next.github.io/xen-api/python/index.html
- improve and clean-up the comments that I added for `pytest` and coverage to `pyproject.toml` recently with my last PR.
@stephenchengCloud @ashwin9390

CA390883: feature/py3:  Add pytest/coverage docs and improve pytest coverage comments

---

ocaml/libs/http-lib/http.ml
ocaml/xe-cli/newcli.ml
quality-gate.sh

We want to get away from string-based URL handling and delegate this to URI and get correct IPv6 handling along the way.

CP-49677 CP-49647 Use URI for improved IPv6 in http.ml, newcli.ml

---

.codecov.yml
doc/README.md

Hi @robhoes!
this PR tweaks the Quick start guide in `doc/README.md` to give some bits of information that I were helping me at getting started to add a new page to the new Hugo-based docs, because I had never used Hugo before.

doc/README.md: Improve the Hugo Quick start guide for an easier start

---

ocaml/xapi-cli-server/record_util.ml
ocaml/xapi/message_forwarding.ml

`VM.hard_shutdown` does not cancel `VM.shutdown` operations. 
In the case of losing the session during a failed `VM.shutdown`, we cannot recover with `VM.hard_shutdown` as it is not in the list of operations that are to be cancelled.
These results in VM hanging until the requests time out.
Moreover, `VM.shutdowm` is missing from the `vm_operation_table` resulting in it being incorrectly displayed as `(unknown operation)`.

CA-394444: `hard_shutdown` stuck behind a `pending` `shutdown`

---

.github/workflows/hugo.yml
doc/hugo.toml

Remark:
Same #5702 (closed), but for master (because it had nothing to do with py3 and had an unrelated CI failure)
Thanks everyone for all the reviews and tips for #5698!
In https://github.com/xapi-project/xen-api/pull/5698#issuecomment-2175713287 there was some doubt (or maybe just misunderstanding) on the second commit of #5698 for publishing a preview of the docs on the clone repo's GitHub pages (will only be published if the GitHub pages are configured to be published from GitHub actions, not from the `gh-pages` branch).
In any case, the two commits of #5698 are no dependent on each other, so this submits only the first commits of it for review.
- https://github.com/xapi-project/xen-api/pull/5698#issuecomment-2175397658 and 
- …

Hugo docs: Add dark mode support, theme variant selector and print

---

python3/Makefile
python3/poweron/wlan.py
scripts/Makefile

Subtask CP-49930:
- Modified  Makefile in python3 directory  to include wlan.py
- Fixed pytest error
- Removed wlan.py from scripts/Makefile
@liulinC

CP-49930: Moved wlan.py from scripts/poweron to python3/poweron

---

ocaml/database/master_connection.ml
ocaml/libs/xapi-stdext/lib/xapi-stdext-unix/test/unixext_test.ml
ocaml/libs/xapi-stdext/lib/xapi-stdext-unix/unixext.ml
ocaml/libs/xapi-stdext/lib/xapi-stdext-unix/unixext.mli
ocaml/xapi/xapi.ml
ocaml/xapi/xapi_globs.ml
ocaml/xenopsd/lib/xenopsd.ml

I think these are the only changes I have before we'd attempt a merge of feature/perf (with more epoll related content that I'll move to feature/epoll instead).

epoll: introduce test-open and improve logging on failure in xapi startup and database. code

---

python3/Makefile
python3/poweron/DRAC.py
scripts/Makefile

Sub task CP-49902:
- Modified Makefile in python3 directory to include DRAC.py
- Removed DRAC.PY from scripts/poweron
- Removed DRAC.py from scripts/Makefile
- Fixed pytlint issue by using sys.exit()

CP-49902: Moved DRAC.py from scripts/poweron to python3/poweron

---

python3/Makefile

Sub task 49975:
-Based on feedback provided in  https://github.com/xapi-project/xen-api/pull/5695 ,modified Makefile to use install -d -m instead of mkdir -p.
@liulinC

CP-49975: Replaced mkdir -p with \\\$(IPROG)  -d for directory creation in install target.

---

ocaml/xapi-cli-server/records.ml

This makes `cluster-stack-version` show up as a field of the cluster object in cli

Make `cluster-stack-version` show up in the CLI

---

dune-project
ocaml/forkexecd/src/dune
ocaml/forkexecd/src/fe_main.ml
ocaml/libs/xapi-stdext/lib/xapi-stdext-unix/dune
ocaml/libs/xapi-stdext/lib/xapi-stdext-unix/test/dune
ocaml/libs/xapi-stdext/lib/xapi-stdext-unix/test/test_systemd.ml
ocaml/libs/xapi-stdext/lib/xapi-stdext-unix/test/test_systemd.t
ocaml/libs/xapi-stdext/lib/xapi-stdext-unix/unixext.ml
ocaml/libs/xapi-stdext/lib/xapi-stdext-unix/unixext.mli
ocaml/networkd/bin/dune
ocaml/networkd/bin/networkd.ml
ocaml/networkd/lib/dune
ocaml/xcp-rrdd/bin/rrdd/dune
ocaml/xcp-rrdd/bin/rrdd/xcp_rrdd.ml
xapi-rrdd.opam
xapi-stdext-unix.opam

Replaced usages of `ocaml-systemd` (that acts as thin glue on top of `libsystemd`) with standalone implementations of `sd_notify` and `sd_booted` functions in a new module in `stdext-unix`. These are identical to their `libsystemd` implementations short for differences in system calls unavailable in OCaml's stdlib that were deemed unimportant, and the interface was narrowed down to what we already use it for.
The implementation, unlike `ocaml-systemd` one, does not raise exceptions. Unit tests currently do not cover the entirety of the implementation but could be extended if deemed necessary. These changes passed BST/BVT test suites.
Compared to master:
```bash
(master) $  ldd _build/install/default/bin/* | grep systemd -B 2
_build/install/default/bin/xapi-networkd:
linux-vdso.so.1 …
```

IH-583: Ensure OCaml binaries don't link against libsystemd

---

scripts/xe-enable-ipv6

When creating the bridge for virtual machines we don't want to set link-local address because it will give an access to the host for VMs. Required link-local are managed by XAPI directly.

Don't generate link-local address for interfaces

---

ocaml/libs/xapi-stdext/lib/xapi-stdext-unix/test/dune

xs-opam tests detected this failure: https://github.com/xapi-project/xs-opam/actions/runs/9645899485/job/26601099423

IH-583: Fix failing builds by attaching package to the cram test

---

ocaml/xapi/api_server.ml

For regular replies we look at the request and reply with a matching version. However when we fail to parse the JsonRPC request itself then we don't know what version to use.
XenCenter uses JsonRPC v2 by default, and JsonRPC v2 has been supported in XAPI for a long time.

CA-381119: use JsonRPC V2 for error replies

---

python3/Makefile
python3/libexec/print-custom-templates
scripts/Makefile

Sub task CP-49921:
- Moved print-custom-templates from scripts to python3/libexec directory
- Modified python3/Makefile to include these changes.
-  fixed bare-except error

CP-49921: Moved print-custom-templates from scripts to python3/libexec directory

---

python3/Makefile
python3/poweron/power-on.py
scripts/Makefile

Sub task CP-49920:
- Modified Makefile to include  power-on.py under python3 directory
- Removed  power-on.py from scripts/Makefile
- Fixed No exception type(s) specified (bare-except)

CP-49920: Moved power-on.py from scripts/poweron to python3/poweron directory.

---

ocaml/xapi-idl/lib/task_server.ml
ocaml/xapi/api_server.ml
ocaml/xenopsd/test/test.ml

This PR merges the latest `xen-api/master` branch into `xen-api/feature/py3` to fix race conditions in CI.
Merging these latest commits from `master` into `feature/py3` was recommended by @psafont and @edwintorok in #5733.
FYI: @ashwin9390 and @stephenchengCloud

Merge `master` into `feature/py3`: Fix races for CI

---

ocaml/xapi/taskHelper.ml

Do not check permissions of a task if it is acting on itself. In the case the session is lost, the task needs to be able to update itself.
If the session were to be lost, we would not able to retrieve back the correct `auth_user_id`. If the task ids match implies that we know we were already authorized.

CA-394169: Allow task to have permissions on itself

---

.codecov.yml
.github/workflows/other.yml

Testing, it's not clear whether this works, or needs some kind of setup in the github side, or codecov side
Upload works, it's the coverage that keeps being wonky

CI: use new version of codecov action

---

python3/Makefile
python3/plugins/echo.py
scripts/Makefile

Sub task CP-49903: 
- Moved echo.py from scripts/examples/python to python3/plugins directory
- Fixed unused-argument issue

CP-49903: mv echo plugin from `scripts/examples/python/echo.py` to `python3/plugins`

---

.github/workflows/other.yml

Supersedes https://github.com/xapi-project/xen-api/pull/5743
Results can be found here: https://coveralls.io/builds/68334246

CI: codecov is unstable, use coveralls

---

ocaml/xapi-storage-script/main.ml
ocaml/xapi-storage/generator/lib/control.ml

The previous change under this ticket (5ec4c2615c7a487f224bbcba90ea9c717ae594bf) was incomplete and did not propagate the changes to the Python binding as used by the implementation of the Storage API provider.

CP-49446: expose SR health values to Python

---

ocaml/sdk-gen/java/autogen/xen-api/src/main/java/com/xensource/xenapi/JsonRpcClient.java

Tested with custom xapi build.
```java
public class Main {
public static void main(String[] args) throws IOException {
var c = new Connection(new URL("https://<url>"));
try{
Session.loginWithPassword(c, "<USERNAME>", "<PASSWORD>");
System.out.println(VM.getAll(c).toArray().length);
}finally {
Session.logout(c);
}
}
}
````
Error before:
```log
Exception in thread "main" com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "recommendations" (class com.xensource.xenapi.Pool$Record), not marked as ignorable (57 known properties: "telemetry_uuid", "redo_log_enabled", "metadata_VDIs", "local_auth_max_threads", "ha_statefiles", "is_psr_pending", "ext_auth_max_threads", "wlb_verify_cert", "tags", "policy_no_vendor_device", "default_SR", …
```

[ASAP] CA-394921: Ignore unknown properties during Java SDK deserialisation

---

Makefile

This is needed in order to expose the package to other rpms

Make: install library clock

---

ocaml/forkexecd/lib/fe_argv.ml
ocaml/forkexecd/lib/forkhelpers.ml
ocaml/forkexecd/src/child.ml
ocaml/forkexecd/src/fe_debug.ml
ocaml/libs/log/debug.ml
ocaml/libs/xapi-stdext/lib/xapi-stdext-encodings/encodings.ml
ocaml/mpathalert/mpathalert.ml
ocaml/perftest/perfdebug.ml
ocaml/rrd2csv/src/rrd2csv.ml
ocaml/xapi/certificates_sync.ml
ocaml/xapi/import.ml
ocaml/xapi/importexport.ml
ocaml/xapi/xapi_xenops.ml
ocaml/xcp-rrdd/bin/rrdd/xcp_rrdd.ml
ocaml/xe-cli/newcli.ml
ocaml/xenopsd/lib/xenops_server.ml
ocaml/xenopsd/pvs/pvs_proxy_setup.ml
ocaml/xenopsd/xc/device.ml
ocaml/xenopsd/xc/domain.ml
ocaml/xenopsd/xc/xenops_server_xen.ml

This is still compatible with OCaml 4 too:
* `Printf.ksprintf` exists on OCaml 4
* OCaml 5 is more strict on where `inline` attributes can be placed, OCaml 4 also accepts the new (correct) placement
There is probably going to be more once I start testing @psafont 's xapi-storage-script changes.

Some OCaml 5 build fixes

---

ocaml/libs/http-lib/http.ml
ocaml/libs/http-lib/http.mli
ocaml/libs/http-lib/http_svr.ml

Removed unused function, replaced the only other usage of `parse_uri` with the
functions from the `Uri` module.
Suggested [here](https://github.com/xapi-project/xen-api/pull/5676#pullrequestreview-2122987981).
The original ticket also mentioned `authorization_of_string` as another
candidate to switch to Uri, but it parses headers, not Uris, so this
was not undertaken.
This change passed the BST/BVT test suites, and was also tested
manually by interacting with the host from XenCenter.

CP-49953: Remove parse_uri, switch to using Uri module instead'

---

ocaml/xapi-storage-script/main.ml

- Use cbt_enabled flag from plugin responses, to allow that a snapshot of a CBT-enabled VDI will itself be CBT-enabled.
- As part of vdi-data-destroy, record the VDI type as a custom key, so that on a subsequent sr-scan it still shows up as a metadata-only snapshot.

CP-50050 track CBT status for SMAPIv3 SRs

---

.github/workflows/other.yml

When uploading more than one coverage result to coveralls, it needs to be told when all of them are done

CI: Complete parallel Coveralls uploads

---

scripts/examples/python/XenAPI/XenAPI.py

Apparently some more checks got enabled on master for python that fail on the changes done to XenAPI.py on the feature branch (but these tests didn't fail at the time the changes were made, they probably weren't active yet).

Fix newly introduced python warnings in XenAPI.py

---

.github/workflows/other.yml

I believe that this update to `coverallsapp/github-action@v2` (the existing uses of `coverallsapp/github-action` also use `v2`) is expected to fix the CI failure @edwintorok saw in https://github.com/xapi-project/xen-api/pull/5761#issuecomment-2200502721.
Also added:
- Make the step use `continue-on-error: true` (already used in other steps before) to not fail 
CI.
- Added a `name:` to the new step to complete the coveralls upload so it shows in the GitHub workflow graph and on the "Checks:" with a proper name.
Checked: Fixed the builds to no longer be in status "pending completion" on https://coveralls.io/github/xapi-project/xen-api

CI: Update endcover step to v2 to fix CI

---

scripts/static-vdis

`static-vdis`: Fix `pyright` and `pylint` warnings before moving `static-vdis` to `python3/`.
For information: @ashwin9390

CP-49928/`static-vdis`: Fix pyright (3/3 of: prepare move to `python3/`)

---

pyproject.toml
python3/tests/test_static_vdis.py
scripts/static-vdis

Main ticket CP-49100: Move python3 scripts from scripts directory to python3 directory.
Subtask CP-49928:
- Add type hints for pyright 
Author: Signed-off-by: Bernhard Kaindl <bernhard.kaindl@cloud.com>
Committed by :Signed-off-by: Ashwinh <ashwin.h@cloud.com>

CP-49928 `static-vdis`: Fix `pyright`: Add type hints, `assert`, `var = ""`

---

ocaml/libs/http-lib/http.ml
ocaml/libs/http-lib/http.mli
ocaml/libs/http-lib/http_svr.ml

Reverts xapi-project/xen-api#5726, which has been found to fail quicktest.

Revert "CP-49953: Remove parse_uri, switch to using Uri module instead'"

---

ocaml/libs/http-lib/http.ml
ocaml/libs/http-lib/http.mli
ocaml/libs/http-lib/http_svr.ml

Follows on from #5726.
Introduces a fix to a bug noticed by a failing quicktest (CA-395184):
```diff
diff --git a/ocaml/libs/http-lib/http_svr.ml b/ocaml/libs/http-lib/http_svr.ml
index 2950bb3f7..c27f59a79 100644
--- a/ocaml/libs/http-lib/http_svr.ml
+++ b/ocaml/libs/http-lib/http_svr.ml
@@ -375,7 +375,7 @@ let request_of_bio_exn ~proxy_seen ~read_timeout ~total_timeout ~max_length bio
(* Request-Line   = Method SP Request-URI SP HTTP-Version CRLF *)
let uri_t = Uri.of_string uri in
if uri_t = Uri.empty then raise Http_parse_failure ;
-                 let uri = Uri.path uri_t in
+                 let uri = Uri.path uri_t |> Uri.pct_decode in
let query = Uri.query uri_t |> kvlist_flatten in
let m = Http.method_t_of_string meth in
let version =
```
Query doesn't need to be …

Remove parse_uri, switch to using Uri module instead

---

ocaml/idl/datamodel_lifecycle.ml

datamodel_lifecycle.ml needs to be bumped to 24.18.0-next for anti-affinity change.

CP-50135: Bump datamodel_lifecycle for anti-affinity

---

.github/workflows/other.yml
pyproject.toml
scripts/plugins/extauth-hook-AD.py
scripts/plugins/test_extauth_hook_AD.py

Main ticket and minimal preparation for:
> CP-49906: Move `extauth-hook-AD.py` to python3 directory 
To fix : https://github.com/ashwin9390/xen-api/actions/runs/9758441405 
This PR has two commits to fix the issues that prevent the move in the above build.
---
[PATCH 1/2] Stop testing scripts/plugins/extauth-hook-AD.py with Python2.7
Preparations for cleaning up the checker warnings in extauth-hook-AD.py:
1. The shebang of extauth-hook-AD.py has already been changed to Python3:
Thus, stop testing it with Python3.
2. This drops the Python2 code coverage to 28% (below 50%).
We need to allow further drops in coverage: Set the limit to 0.
---
[PATCH 2/2] extauth-hook-AD.py: Fix `pytype` warnings, clean-up `pylint`
suppressions
1. `pytype` warnings need to be fixed before it can be moved to …

CP-49906: Fix checker warnings for extauth-hook-AD

---

ocaml/forkexecd/test/fe_test.ml

2.0.2 introduced a breaking change (maybe it should've been 3.0): it no longer raises Fd_send_recv.Unix_error, but Unix.Unix_error.
The test code here was specifically catching just Fd_send_recv.Unix_error. Make it catch both.

fe_test: fix compatibility with fd-send-recv 2.0.2

---

ocaml/xenopsd/c_stubs/sockopt_stubs.c

Coherently use tabs instead of spaces.
Just style changes.

Fix indentation in C code - TRIVIAL

---

ocaml/xapi/xapi_cluster_host.ml

Previously xapi calls `set_tls_config` after the join call, which will restart the remote server of xapi-clusterd. In the meantime, another xapi-clusterd might also be joining, which causes `distribute_state` to be called while the remote server is restarting.
Now move the `set_tls_config` immediately after the cluster daemon is enabled to reduce the chance of race. Moreover, `join_internal` already creates a tls_config and passes it to xapi-clusterd, there is no point resetting the tls config immediately afterwards.
This does not, however, solve the whole problem. For that, we need to make sure that `distribute_state` and `set_tls_config` cannot happen at the same time. More generally, any remote calls cannot happen while `tls_config` is running. Hence we need them to hold the same lock. …

CA-392887: `set_tls_config` immediately after enabling clustering

---

python3/Makefile
python3/extensions/pool_update.apply
scripts/Makefile

Sub task CP-49918:
- Modified python3/Makefile to include  pool_update.apply
- Removed pool_update.apply from scripts/Makefile
- Fixed import order

CP-49918: Moved pool_update.apply from scripts/extensions to python3/extensions directory

---

python3/bin/perfmon
python3/libexec/nbd_client_manager.py
python3/packages/observer.py
python3/perfmon/perfmon
scripts/examples/python/XenAPIPlugin.py
scripts/plugins/extauth-hook-AD.py

Improve spelling and fix typos in comments of Python scripts
(found using the [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) plugin)

Improve spelling and fix typos in comments of Python scripts

---

scripts/xe-reset-networking

Sub task CP-49931:
-Fix tab and space indentation issues in  xe-reset-networking scripts
Author : Signed-off-by: Bernhard Kaindl <bernhard.kaindl@cloud.com>
Committed by: Signed-off-by: Ashwinh <ashwin.h@cloud.com>

CP-49931 - Convert tabs to spaces and fix whitespace for scripts/xe-reset-networking:

---

pyproject.toml
python3/stubs/XenAPI.pyi
scripts/backup-sr-metadata.py
scripts/restore-sr-metadata.py

Sub task  CP-50100:
2to3 and warning fixes to prepare its to move to python3 dirrectory:
Commit 1:
- apply 2to3 -w and update shebang
Commit 2:
- pyright:
- Add VDI to the XenAPI typing stub as we don't do type checking of VDI attributes yet.
- move `sys.exit()` from inside `usage()` to after to make pyright aware of the `exit`.
- apply isort to sort the imports
- update the logout() handler to:
- use `contextlib.suppress()`
- move it into main() to fix the undeclared session warning.
- remove the unused variable `vdis`: `vdis = session.xenapi.SR.get_all_records()`
- remove trailing whitespace
Author : Signed-off-by: Bernhard Kaindl <bernhard.kaindl@cloud.com>
Committed by: Signed-off-by: Ashwinh …

CP-50100: `backup-sr-metadata,restore-sr-metadata`: `2to3`, fix `pytype`, `pyright`

---

ocaml/idl/datamodel_cluster.ml
ocaml/tests/test_cluster.ml
ocaml/xapi/message_forwarding.ml
ocaml/xapi/xapi_cluster.ml
ocaml/xapi/xapi_cluster.mli
ocaml/xapi/xapi_cluster_helpers.ml
ocaml/xapi/xapi_cluster_host.ml
ocaml/xapi/xapi_clustering.ml

relatively large change, best reviewed by commit

CA-394109: Reduce number of alerts

---

ocaml/idl/datamodel_certificate.ml
ocaml/idl/datamodel_common.ml
ocaml/idl/datamodel_lifecycle.ml
ocaml/idl/schematest.ml
ocaml/xapi/certificates.ml
ocaml/xapi/certificates.mli
ocaml/xapi/certificates_sync.ml

The new fingerprint_sha256 and fingerprint_sha1 fields will be empty when upgrading from a version without the fields. This commit checks for this and fills them in, stopping the certificate from being needlessly reinstalled.

CP-50193: Update new fingerprint fields on DB upgrade

---

scripts/examples/python/XenAPIPlugin.py

When reviewing XAPIPlugin.py for warning fixes,
Bernhard found a superfluous `catch` and `raise` in `XenAPIPlugin.py`'s `dispatch()` function
that we can clean up:
Commmit message:
> `SystemExit` does not need to be caught and raised in this `try`:
> Both other exceptions are subclasses of Exception, so they don't catch `SystemExit(BaseException)`:
>
> By design, SystemExit is a subclass of BaseException and because we are not catching BaseException and also not use a bare `except:` here, we can cleanup catching and re-raising `SystemExit()` here.
> Reference: https://docs.python.org/3/library/exceptions.html#SystemExit
Author / Signed-off-by: Bernhard Kaindl <bernhard.kaindl@cloud.com>
Committed by: Signed-off-by: Ashwinh <ashwin.h@cloud.com>

XenAPIPlugin.py: Remove  the superflous catch & raise of SystemExit

---

python3/Makefile
python3/extensions/pool_update.precheck
python3/stubs/XenAPI.pyi
scripts/Makefile

Sub task CP-49919:
- Modified python3/Makefile to include  pool_update.precheck
- Removed pool_update.precheck from scripts/Makefile
- Added necessary methods in stubs/XenAPI.py to fix pyright issue
- Initialized variable to fix reportPossiblyUnboundVariable

CP-49919: mv scripts/extensions/pool_update.precheck to python3/extensions

---

ocaml/xapi-cli-server/record_util.ml

Use a function accepting printf-style arguments to raise an error and simplify all the call sites.

CP-50259 simplify raising error in record_util

---

ocaml/libs/xapi-stdext/lib/xapi-fdcaps/test/dune
ocaml/libs/xapi-stdext/lib/xapi-stdext-threads/dune
ocaml/libs/xapi-stdext/lib/xapi-stdext-unix/test/dune
ocaml/tests/record_util/dune

Otherwise the tests are run as part of every package when installing them using opam, leading to failures in xs-opam's CI

dune: fix tests to packages

---

python3/plugins/extauth-hook-AD.py
python3/plugins/test_extauth_hook_AD.py

Hi @psafont, 
For logging the output of `/usr/bin/systemctl reload-or-restart sshd` in `python3/plugins/extauth-hook-AD.py`, `mypy` found a minor regression:
- We should add `universal_newlines=True` there to fix the formatting of the logged output.
How this could be found:
- `mypy` is good at spotting changes in `str`/`bytes` from moving to Python3
- `mypy` wasn't fully usable yet, the config was not yet updated for `python3/*`.
- But with the moving of files to `python3/*` having made good process, I fixed the config for it.
In Python3, `subprocess.check_output(command)` returns `bytes` by default (unless it is switched to text mode).
- The original Python2 code assumes it returns `str` by default.
- This leads to slightly non-ideal logging in this case.
- Fix this by using …

`python3/plugins/test_extauth_hook_AD.py`: Fix logging in `run_cmd()`

---

ocaml/xapi-cli-server/record_util.ml

CP-50259 simplify parsing size with kib, mib, etc suffix

---

ocaml/xapi-cli-server/record_util.ml

To keep compatibility with the existing behavior, allow "1kib" and as well as "1 kib", that is, a space before the unit. This space is optional and it could be more than one.

fixup! CP-50259 simplify parsing size with kib, mib, etc suffix

---

doc/content/xapi/guides/howtos/add-field.md
ocaml/xapi-cli-server/cli_operations.ml
ocaml/xapi-cli-server/cli_util.ml
ocaml/xapi-cli-server/record_util.ml
ocaml/xapi-cli-server/records.ml
quality-gate.sh

Previously, users were forced to define how the elements were concatenated, allowing usage to
be inconsistent.
Fortunately this was not the case, but it's better to define the concatenation
in a single place and reduce possible mistakes.

xapi-cli-server: add functions to print maps

---

scripts/examples/python/XenAPI/XenAPI.py

Updates the correct parent span when we retrieve a cached connection.
Preveusly, we would call the instrumentation only when we make the connection for the first time. This resulted in seeing the same parent span for all subsequent calls of `make_connection`. Calling the instrumentation first ensures the correct parent is sent over the headers for all code branches.

CP-50270: Set the correct parent in `make_connection`

---

ocaml/libs/http-lib/http_svr.ml
ocaml/libs/http-lib/test_client.ml
ocaml/libs/http-lib/test_server.ml

Concatenates the query value back after Uri.query splits the string separated by commas.
`Uri.query` splits the value string into several if they are separated with commas. Like this: `"?k=v1,v2,v3" -> [("k", ["v1";"v2";"v3"])]` This function concatenates these back. (i.e. into `[("k", "v1,v2,v3")]`).
It will not concatenate values entered for duplicate keys, as these will be separate tuples: `"?k=v1,v2,v3&k=v4" ->  [("k", ["v1"; "v2"; "v3"]); ("k", ["v4"])]`
This was tested manually by issuing a host-get-system-status call:
```
$ xe host-get-system-status uuid=ed4342d9-eeaf-41a3-88d3-90c0d47c3f76   
output=tar filename=just.tar entries=xapi-debug,xen-info,xha-liveset,high-availability,cron,control-slice,firstboot,NVIDIA-logs,block-scheduler,xenserver-databases,multipath,disk-info,xenserve …
```

CA-395626: Fix (server status report generation report)

---

ocaml/quicktest/dune

Otherwise dune will try to run it when testing all the packags, but the quicktest binary won't be available

quicktest: associate unit-test with xapi package

---

ocaml/idl/dm_api.ml
ocaml/libs/xapi-stdext/lib/xapi-stdext-std/listext.ml
ocaml/libs/xapi-stdext/lib/xapi-stdext-std/listext.mli
ocaml/libs/xapi-stdext/lib/xapi-stdext-std/listext_test.ml

Add new check for new parameters' default value
Note we are only checking for default of new parameters in messages
that already have default parameters.
It lacks checks for new parameters added to messages with no default
parameters, but there is no easy way to achieve that because the generator
cannot tell what is new and what is not, moreover, there are existing
messages with non-default parameters introduced in different releases.

Add new check for new parameters' default value

---

python3/tests/test_mail-alarm.py

This PR contains the following changes,
- Update test_mail-alarm.py to test with Python3
- Move the test to the python3/tests directory
- Replace the old method of copying the script to a temp directory and importing it as a module with the import_helper module from python3/tests
- Remove the use of another temporary file to gather logged errors
- Remove the obsolete nottest decorator
- The test is now run against the Python3 version of mail-alarm
- The test was also run against the original Python2 mail-alarm during the update, but this PR only updates the test for Python3
- After this PR, there are no longer any Python2 tests left
Author :Bernhard Kaindl <bernhard.kaindl@cloud.com>
Committed by :Ashwinh <ashwin.h@cloud.com>

Py3: Cleanup `test_mail-alarm.py` to use python3 test helpers an move it

---

ocaml/idl/datamodel_types.ml
ocaml/idl/datamodel_types.mli
ocaml/idl/datamodel_utils.ml
ocaml/idl/ocaml_backend/gen_db_actions.ml
ocaml/idl/ocaml_backend/gen_empty_custom.ml
ocaml/xapi-cli-server/cli_operations.ml
ocaml/xapi/xapi_role.ml
quality-gate.sh

Using records in cross-pool migration code is dangerous, as the code interacts with potentially newer hosts. This means that fields in the record might be different from what's expected. In particular, adding an enum field can break the deserialization, and removing a field as well.
Instead, introduce and use a new call `get_all_where`: this calls allows the host to return a filtered list of object references.
With these changes, only SR records are used. This is done to minimize the number of calls done.

CA-390277: Reduce record usage on CLI cross-pool migrations 

---

ocaml/idl/datamodel_repository.ml
ocaml/idl/schematest.ml
ocaml/tests/test_repository.ml
ocaml/xapi-cli-server/cli_frontend.ml
ocaml/xapi-cli-server/cli_operations.ml
ocaml/xapi-cli-server/record_util.ml
ocaml/xapi-cli-server/records.ml
ocaml/xapi/message_forwarding.ml
ocaml/xapi/repository.ml
ocaml/xapi/repository.mli
ocaml/xapi/repository_helpers.ml
ocaml/xapi/xapi_globs.ml

Add a field "origin" in "repository" to indicate the origin of the repository.
It's an enum type with 2 values: "remote" and "bundle".

CP-49212: Update datamodel for non-CDN update 

---

ocaml/xapi/context.ml
ocaml/xapi/helpers.ml
ocaml/xapi/message_forwarding.ml
ocaml/xapi/taskHelper.ml
ocaml/xapi/xapi_task.ml

Instruments task related functions. 
Some other improvements:
- `Context.with_tracing` now records the error inside the span;
- `Context.complete_tracing` is now called with `finally`.

Instrument task related functionality

---

ocaml/sdk-gen/csharp/friendly_error_names.ml
ocaml/sdk-gen/csharp/gen_csharp_binding.ml
ocaml/sdk-gen/csharp/templates/HTTP_actions.mustache
ocaml/sdk-gen/powershell/gen_powershell_binding.ml
ocaml/sdk-gen/powershell/templates/Remove-XenObject.mustache

First installment of PS templatization.

[OIL] Templatization of PS Remove-Xen* cmdlets. Refactoring of HTTP_actions.mustache

---

python3/plugins/extauth-hook-AD.py

PR contains following improvement
Fixing per-method comments which are Obsolete:
- Disabled globally 
Author: Signed-off-by: Bernhard Kaindl <bernhard.kaindl@cloud.com>
Committed by :Signed-off-by: Ashwinh <ashwin.h@cloud.com>

plugins/extauth-hook-AD.py: Cleanup obsolete per-method pylint comments

---

python3/packages/observer.py

We already have method_name so printing the method itself doesn't add anything. It also makes searching in Jaeger more difficult as the method includes its id.
You can see this in action here: http://rage.uk.xensource.com:16686/trace/46e188b3e42c0b2cec83af26e1d60bd8 (note the "class.instrument" spans)

CP-49811: Remove redundant method object from span name

---

ocaml/libs/http-lib/bufio_test.ml
ocaml/libs/xapi-stdext/lib/xapi-fd-test/generate.ml
ocaml/libs/xapi-stdext/lib/xapi-fd-test/observations.ml
ocaml/libs/xapi-stdext/lib/xapi-fd-test/observations.mli

Noticed by @psafont in https://github.com/xapi-project/xen-api/actions/runs/9901545401/job/27354091939#step:7:149.
The bug is in the test code, I misinterpreted what the meaning of the timeout parameter in `Buf_io.really_input` means, it is not the overall timeout, but the timeout for each individual read call.
So if the other end decides to send 1 byte at a time, then the overall timeout will be number of bytes * timeout.
This may be an unintentional bug in `really_input`, however it is unknown whether any callers rely on the current semantics or not, so fix the test instead to check for the actual behaviour of `really_input`.
There is also a bug in the use of `setsockopt`. It gets converted to a `struct timeval`, and the microseconds value truncated.
So if we end up asking for a too …

Fix @stresstest failure

---

pyproject.toml

Update the configuration of `mypy` for `python3/`:
- Slash number of warnings dramatically by finding needed packages
- Allow using `mypy` to detect issues where functions now return bytes that other checkers don't find:
- #5812
- see below, `proc.communicate()` (by default returns bytes) and https://github.com/xapi-project/xen-api/blob/feature/py3/ocaml/xapi-storage/python/xapi/storage/common.py#L20 prints them as `b"bytearray-conent"` that was printed as a string using Python2.
```py
ocaml/xapi-storage/python/examples/datapath/loop+blkback/datapath.py:24: note: In module imported here:
ocaml/xapi-storage/python/xapi/storage/common.py: note: In function "call":
ocaml/xapi-storage/python/xapi/storage/common.py:22:19: error: If x = b'abc' then f"{x}" or "{}".format(x) produces "b'abc'", …
```

Update the `mypy` config for `python3/` (found #5812 with it)`

---

python3/plugins/extauth-hook-AD.py

`plugins/extauth-hook-AD.py`: Fix '`Stray abstractmethod`' `pytype` warning by adding missing inherit from `abc.ABC`:
Inheriting from `abc.ABC` is implemented since Python 3.4: https://bugs.python.org/issue16049
Details:
Inherit from ABC for `@abc.abstractmethod` is needed to require the decorated method to be implemented by subclasses
- Fixing this that fixes the `pytype` warning: Thus, we can the comment that suppresses it.
- While at it, modernise the abstract methods to use `...` instead of `pass`.
```py
--- a/python3/plugins/extauth-hook-AD.py
+++ b/python3/plugins/extauth-hook-AD.py
@@ -28,7 +28,6 @@ import XenAPIPlugin
-# pytype: disable=ignored-abstractmethod
HCP_USERS = "/etc/security/hcp_ad_users.conf"
@@ -77,7 +76,7 @@ class ADBackend(Enum):
BD_WINBIND = 1
-class ADConfig(): …
```

`plugins/extauth-hook-AD.py`: Fix 'Stray abstractmethod' pytype warning

---

python3/plugins/extauth_hook_ad.py
python3/plugins/test_extauth_hook_AD.py
python3/tests/import_helper.py

`python3/plugins/test_extauth_hook_ad.py`:
- Modernise testee import to not need a symlink for a valid module name to import
- Remove the obsolete symlink `python3/plugins/extauth_hook_ad.py` that was used to import the testee.
- Modernise mocking the imports within the testee to use the context manager `import_helper.mocked_modules()` to prevent global mocking of `XenAPI` and `XenAPIPlugin`.

`test_extauth_hook_ad.py`: Modernise testee import to not need a symlink

---

scripts/xe-backup-metadata
scripts/xe-restore-metadata

XSA-459 (https://xenbits.xen.org/xsa/advisory-459.html) covers a security issue with the Portable SR (also known as VM Metadata Backup/Restore) functionality.
Now the embargo has lifted, this PR includes the content of the XSA patch, and another bugfix to the vbd cleanup identified whilst working on the security issue (the bugfix was not published previously to avoid drawing interest in the functionality during the embargo period).

Updates to Portable SR Functionality (1.249-lcm)

---

ocaml/xapi-cli-server/cli_operations.ml

Host records have changed between CH8.2CU1 and XS8, this means that the
records produced from an new host cannot be serialized by this code.
Instead of making the remote host filter records, now the client tries
to fetch the correct reference, and if it can't, fetches all references
and fetches fields to find it.
Records from Networks, PBDs and SRs are still used.
I've manually verified that the cross-pool migrations now work

CA-390277: Fix cross-pool migration from CH8.2CU1 to XS8 when using xe 

---

ocaml/xapi-consts/api_messages.ml
ocaml/xapi/xapi_clustering.ml

Xapi will send alert when the user is running on a Corosync 2 cluster and prompting them to upgrade. This should only happen on XS 9 and is behind the corosync3 feature flag.
XenCenter can take advantage of this alert message, but should have its own warning message to tell the user why/how to perform the upgrade.

CP-49634: Add alerting for Corosync upgrade

---

.github/workflows/other.yml
ocaml/xapi-storage/python/xapi/__init__.py
ocaml/xapi-storage/python/xapi/storage/api/datapath.py
ocaml/xapi-storage/python/xapi/storage/api/plugin.py
ocaml/xapi-storage/python/xapi/storage/api/test_datapath.py
ocaml/xapi-storage/python/xapi/storage/api/volume.py
pyproject.toml

This PR contains the following changes for `ocaml/xapi-storage/python/xapi/storage/api/`
- Replace `if not isinstance(code, str) and not isinstance(code, unicode)` with `is_str(code)` to simplify the code for readability 
- Remove unused `is_long` and replace with `is_str` in `datapath.py`, `plugin.py` and `volume.py`
Author: Signed-off-by: Bernhard Kaindl <bernhard.kaindl@cloud.com>
Committed by :Signed-off-by: Ashwinh <ashwin.h@cloud.com>

storage-api: `__init__.py`: Use `is_str()` to check for string type

---

ocaml/forkexecd/src/child.ml
ocaml/xapi/xapi_globs.ml

Print timeout settings to full precision in logs instead of converting.
Avoid clipping command-line arguments in forkexecd logs, we need to see the full command-line for commands that fail.
This was split out of the epoll PR.

[epoll]: improve debugging for timers and forkexecd

---

ocaml/xapi-storage-script/main.ml

By default message-switch calls are serialized for backwards compatibility reasons in the Lwt and Async modes. (We tried enabling parallel actions by default but got some hard to debug failures in the CI).
This causes very long VM start times when multiple VBDs are plugged/unplugged concurrently: the operations are seen concurrently by message-switch, but xapi-storage-script only retrieves and dispatches them sequentially, so any opportunity for parallel execution is lost. Even though the actions themselves only take seconds, due to serialization, a VM start may take minutes.
Enable parallel processing explicitly here (instead of for all message-switch clients). SMAPIv3 should expect to be called concurrently (on different hosts even), so in theory this change should be safe and improve …

CA-395512: process SMAPIv3 API calls concurrently

---

message-switch-unix.opam
ocaml/message-switch/unix/dune
ocaml/message-switch/unix/protocol_unix_scheduler.ml
ocaml/xapi-idl/lib/scheduler.ml

Fewer calls to convert to epoll.

[epoll]: replace duplicate Delay modules with ThreadExt.Delay

---

.github/workflows/other.yml
.pre-commit-config.yaml
pyproject.toml
scripts/examples/python/setup.cfg

Hi @stephenchengCloud,
it turned out that the updates in this PR were not blocking for merging #5873.
These changes are therefore just updates that are nice to have, do not change the code and can be merged later (independent of your regression testing).
This PR is now just a collection of minor updates that just happen to be in one PR to update python3 testing and to no longer announce support for Python 2.7 at https://pypi.org/project/XenAPI
Collected updates:
- pytest config update for Python3:
- Run xenopsd tests
- remove pytest-cov requirement (was obsoleted a while ago)
- Update the minimum supported Python version for XenAPI.py to 3.6 (for XS8)
for https://pypi.org/project/XenAPI/ to `python_requires = >=3.6.*, <4`
- Remove ocaml/xapi-storage from the directories to test with …

py3: Config updates for removing and deprecating Python2 support

---

ocaml/xapi/db_gc.ml
ocaml/xapi/xapi_globs.ml
ocaml/xapi/xapi_ha.ml

Prior to this commit, the xapi on the coordinator host records the 'Unix.gettimeofday' as the timestamps of the heartbeat with other pool supporter hosts. When the system clock is updated with a huge jump forward, the timestamps would be far back into the past. This would cause the xapi assumes that the hosts are offline as long time no heartbeats.
In this commit, the timestamps are changed to get from a monotonic clock. In this way, the system clock changes will not impact the heartbeats' timestamps any more.
Additionally, Host_metrics.last_updated is only set when the object is created. It's useless in check_host_liveness at all.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

CA-394343: After clock jump the xapi assumed the host is HOST_OFFLINE

---

ocaml/xapi/xapi_xenops.ml

Previously the path was replaced by an empty string, when trying to start he vm. The only feedback was on the logs as a debug message, but not all users that start VMs have access to the logs.

IH-507: xapi_xenops: raise an error when the kernel isn't allowed

---

python3/Makefile

When testing the feature/py3 branch, xapi failed to restart due to perfmon.service not loaded.
The root cause is that:
In this PR: https://github.com/xapi-project/xen-api/pull/5767, we moved perfmon.service from `scripts/Makefile` to `python3/Makefile` 
In `scripts/Makefile`, `IPROG` is defined as:
```
IPROG=./install.sh 755
IDATA=./install.sh 644
```
While in `python3/Makefile`, `IPROG` is defined as: 
```
IPROG=install -m 755
IDATA=install -m 644
```
And the purpose of `install.sh` is to replace strings in *.service like: @OPTDIR@ -> ${OPTDIR}
So in python3/Makefile, we didn't replace these strings, and then led to the error.
Test passed:
201792 Ring3 BVT

CP-49148: perfmon.service is not loaded

---

ocaml/database/master_connection.ml
ocaml/idl/datamodel_lifecycle.ml
ocaml/idl/datamodel_values.ml
ocaml/libs/http-lib/buf_io.ml
ocaml/libs/http-lib/xmlrpc_client.ml
ocaml/libs/stunnel/stunnel_cache.ml
ocaml/libs/stunnel/stunnel_cache.mli
ocaml/libs/vhd/vhd_format/f.ml
ocaml/libs/vhd/vhd_format_lwt/block.ml
ocaml/libs/vhd/vhd_format_lwt/iO.ml
ocaml/libs/xapi-stdext/lib/xapi-stdext-threads/threadext.ml
ocaml/libs/xapi-stdext/lib/xapi-stdext-unix/unixext.ml
ocaml/libs/xml-light2/xml.ml
ocaml/message-switch/switch/logging.ml
ocaml/rrd2csv/src/rrd2csv.ml
ocaml/xapi-idl/lib/scheduler.ml
ocaml/xapi-idl/lib/task_server.ml
ocaml/xapi/vgpuops.ml
ocaml/xapi/xapi_dr_task.ml
ocaml/xapi/xapi_event.ml
ocaml/xcp-rrdd/bin/rrdd/rrdd_server.ml
ocaml/xen-api-client/lib_test/xen_api_test.ml
ocaml/xsh/xsh.ml

These are errors in dune 3.15 and don't seem to be problematic
The warnings in tracing have been left in the code, but need to be dealt with 
They are span links and description for the status. Currently they are unused. @GabrielBuica is there any work in the pipeline planned for this? I'd like to readd the warning as an error

maintenance: delete unused fields

---

configure.ml
ocaml/idl/api_version.ml
ocaml/idl/api_version.ml.in
ocaml/idl/api_version.mli
ocaml/idl/datamodel_common.ml
ocaml/idl/dune

The backwards compatibility info in xapi is the "api_version_major" and "api_version_minor". This info needs to be exposed to update packaging tooling so that it can add the backwards compatibility data into the update's metadata.
1. The defintions of api_version_major and api_version_minor are moved to xapi.spec, the file ocaml/idl/api_version.ml will be regenerated from api_version.ml.in with value of api_version_major and api_version_minor defined in xapi.spec by configure.ml during koji build.
2. Add ocaml/idl/api_version.ml only for buildng xapi with make.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xapi-project/xen-api/5852)

CP-47617:  Expose backwards compat info to update packaging tooling

---

ocaml/libs/clock/dune
ocaml/libs/clock/test_timer.ml
ocaml/libs/clock/test_timer.mli
ocaml/libs/clock/test_timer_run.ml
ocaml/libs/http-lib/bufio_test.ml
ocaml/libs/http-lib/bufio_test.mli
ocaml/libs/http-lib/bufio_test_run.ml
ocaml/libs/http-lib/dune
ocaml/libs/xapi-stdext/lib/xapi-stdext-unix/test/dune
ocaml/libs/xapi-stdext/lib/xapi-stdext-unix/test/unixext_test.ml
ocaml/libs/xapi-stdext/lib/xapi-stdext-unix/test/unixext_test.mli
ocaml/libs/xapi-stdext/lib/xapi-stdext-unix/test/unixext_test_run.ml
ocaml/quicktest/dune
ocaml/quicktest/quicktest.ml
ocaml/quicktest/quicktest_args.ml

Pending testing, draft PR.
Takes about 24s to run manually:
```
/opt/xensource/debug/quicktest -skip-xapi -- test bufio
/opt/xensource/debug/quicktest -skip-xapi -- test Timer
```

CP-50448: run quickcheck tests in XenRT

---

ocaml/idl/datamodel.ml
ocaml/idl/datamodel_errors.ml
ocaml/idl/datamodel_pool.ml
ocaml/idl/schematest.ml
ocaml/tests/dune
ocaml/tests/test_pool_repository.ml
ocaml/tests/test_repository.ml
ocaml/xapi-cli-server/cli_frontend.ml
ocaml/xapi-cli-server/cli_operations.ml
ocaml/xapi-cli-server/cli_util.ml
ocaml/xapi-cli-server/record_util.ml
ocaml/xapi-consts/api_errors.ml
ocaml/xapi-consts/constants.ml
ocaml/xapi/repository.ml
ocaml/xapi/tar_ext.ml
ocaml/xapi/xapi.ml
ocaml/xapi/xapi_globs.ml
ocaml/xapi/xapi_pool.ml
ocaml/xapi/xapi_pool.mli
ocaml/xapi/xapi_pool_helpers.ml
quality-gate.sh

Upload a bundle file and unpack it with module Tar_ext. After that, sync the bundle repository.

CP 49214: Upload and reposync from the bundle

---

scripts/xe-xentrace

To ensure consistency and simplicity for both XS9 and XS8, this change replaces bc command use to python.

CP-50121: Remove bc package from XS9 dom0

---

python3/libexec/restore-sr-metadata.py

When building xapi for XS9, ran into errors:
*** ERROR: ambiguous python shebang in /opt/xensource/libexec/restore-sr-metadata.py:
#!/usr/bin/python. Change it to python3 (or python2) explicitly.
Explicitly use python3.
Test: 
202187 Ring3:BST+BVT (failed case is not related to this PR)

CP-49148: Fix ambiguous python shebang for XS9

---

ocaml/libs/http-lib/http.ml
ocaml/libs/http-lib/http_svr.ml
ocaml/libs/open-uri/open_uri.ml
ocaml/message-switch/switch/switch_main.ml
ocaml/nbd/src/main.ml
ocaml/vhd-tool/src/impl.ml
ocaml/xapi-guard/lib/server_interface.ml
ocaml/xapi-idl/lib/xcp_service.ml
ocaml/xapi-storage-script/examples/volume/org.xen.xcp.storage.plainlvm/common.ml
ocaml/xapi-storage-script/main.ml
ocaml/xe-cli/newcli.ml
ocaml/xen-api-client/lwt/xen_api_lwt_unix.ml
ocaml/xenopsd/lib/xenops_server.ml

`Uri.path` returns percent-encoded output, therefore it can't be expected to behave correctly in cases where it's used to map to Unix files. Our PR upstream introduced `Uri.path_unencoded` function, use that instead.
There is one usage of  `Uri.path` left:
```ocaml
$ rg --pcre2 'Uri.path(?!_unencoded)' --no-heading -g 'ocaml/**/*.ml'
ocaml/xe-cli/newcli.ml:138:    let path = Uri.path_and_query uri |> Uri.pct_decode in
ocaml/vhd-tool/cli/sparse_dd.ml:403:          ?port:(Uri.port uri) ~path:(Uri.path uri) ~query:(Uri.query uri)
ocaml/libs/open-uri/open_uri.ml:77:      let filename = Uri.path_and_query uri |> Uri.pct_decode in
```
But this is not dangeous as it's used as an argument for Uri.make, which is fine without `pct_decode`:
```ocaml
utop # Uri.make ~path:("/get<>`&") ();;
- : Uri.t …
```

CP-50181: Percent decode all Uri paths before using them

---

scripts/examples/python/XenAPI/XenAPI.py

This `import errno` was added by feature/py3 branch to fix pytype issues. But in the master branch, there was also a change to fix pytype issues. Use master code and remove the import.

CP-49148: fix pylint warning

---

ocaml/libs/http-lib/dune
ocaml/libs/xapi-stdext/lib/xapi-stdext-unix/test/dune

This should fix the nightly CIs: https://github.com/xapi-project/xen-api/actions/runs/10155212107/job/28081595232

dune: declare stresstests dependencies

---

ocaml/sdk-gen/java/autogen/xen-api/src/main/java/com/xensource/xenapi/JsonRpcClient.java
ocaml/sdk-gen/java/main.ml

Default enum is `UNRECOGNIZED`

[ASAP] CA-396479: Use default value for unknown enums in Java

---

ocaml/xcp-rrdd/scripts/rrdd/rrdd-example.py

Since this is only an example file, no xenrt test.
This file is not installed on dom0, should do no harm.
- pylint and pytype check passed
- Manually tested the main logic works in python3:
```
Python 3.11.0 (main, Jun 21 2024, 03:47:37) [GCC 13.3.1 20240522 (Red Hat 13.3.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> cmd = "free -k | grep Mem | awk '{print $2, $3, $4}'"
>>> import os
>>> vs = os.popen(cmd).read().strip().split()
>>> vs
['16336416', '4351784', '1958616']
```

CP-49148: Convert rrdd-example.py to python3

---

ocaml/libs/http-lib/dune
ocaml/libs/xapi-stdext/lib/xapi-stdext-unix/test/dune

These were changed recently and the stresstest rules need to match the new name.
I've tested this locally by running `dune build @stresstest`

ci: use the names of binaries, not libraries in stresstests

---

ocaml/libs/xapi-stdext/lib/xapi-stdext-unix/test/test_systemd.t

Use tmpdir whenever possible.
This fixes testing under opam for xs-opam's CI, which is not done currently for the package

ci: Avoid breaking through the opam sandbox in tests

---

ocaml/xapi/xapi_clustering.ml

It was observed that the corosync-notifyd might send a notification when the data shown in corosync-quorumtool has not been updated. This causes xapi-clusterd to return the out-of-date cluster information to xapi. Xapi will not have a chance of updating these states again until there is a further change in the cluster (which may not happen for a long time).
Now add polling in xapi to update the cluster info every 5 minutes, making sure that in the worst case, we still get up-to-date information after a 5-minute delay.

CA-395789: Add polling to cluster health state update

---

.github/workflows/main.yml
.github/workflows/other.yml

The code has already been tested by python3.
Remove python2 test from the CI actions.
```
============================= test session starts ==============================
platform linux -- Python 3.11.9, pytest-8.3.2, pluggy-1.5.0 -- /home/runner/.cache/pre-commit/repom96bpdxe/py_env-**python3.11/bin/python**
cachedir: .pytest_cache
rootdir: /home/runner/work/xen-api/xen-api
configfile: pyproject.toml
testpaths: python3, **ocaml/xcp-rrdd, ocaml/xenopsd**
.....
ocaml/xcp-rrdd/scripts/rrdd/test_api_wait_until_next_reading.py::test_params[None-5-reading0-5] PASSED [ 87%]
ocaml/xcp-rrdd/scripts/rrdd/test_api_wait_until_next_reading.py::test_params[1-5-reading1-5] PASSED [ 88%]
ocaml/xcp-rrdd/scripts/rrdd/test_api_wait_until_next_reading.py::test_params[2.25-5-reading2-3.75] PASSED [ 89%] …
```

Remove python2 related CI

---

.github/workflows/generate-and-build-sdks.yml
.github/workflows/setup-xapi-environment/action.yml

Workaround for https://github.com/ocaml/setup-ocaml/issues/839.
Draft PR to check that it all works and creates correct cache keys.

Fix CI failures caused by setup-ocaml@v3

---

ocaml/idl/datamodel_errors.ml
ocaml/xapi-consts/api_errors.ml
ocaml/xapi/xapi_globs.ml
ocaml/xapi/xapi_pool.ml

Fix some non-CDN bugs/comments:
1. Change the max total bundle files size limit to 1G.
2. Change HTTP error code for the following error to 400:
bundle_repo_not_enabled.
no_repository_enabled.
multiple_update_repositories_enabled.
3. Add a new API error for bundle syncing failure "Syncing with bundle repository failed."

Non-CDN updates bug fix

---

ocaml/xenopsd/scripts/igmp_query_injector.py

even if turning igmp snooping on in ovs bridge, if there is no
external querier multicast traffic, ovs igmp snooping will not
work, so we need to inject igmp traffic

CA-389345: fix incorrect data type in python3

---

python3/packages/observer.py

Creates two spans for observer.py, one for the entire script and one for the opentelemetry import statements. This fixes the current discrepancy between the sm script span and the outer xapi span.
In an example, there's a time lag of 70ms between the Forkhelpers.safe_close_and_exec and the start of observer.py and another 90ms between the end of the sm script and the end of Forkhelpers.safe_close_and_exec . Taking this with the 0.5s of observer.py and the 1.11s of the sm script adds up perfectly to the duration of the Forkhelpers span: 1.77s. Most of the observer.py time is taken up by imports, I'm doing some further tests to see if this is improved by e.g. python 3.11

CP-49876: Create spans for observer.py itself

---

scripts/plugins/openvswitch-config-update

PR #5261 made the switch to python3 but missed a dict.itervalues() call, which causes a failure with python3.
Should also be backported for XS8.

Plugin `openvswitch-config-update`: fix python2ism in python3 migration

---

ocaml/tests/test_updateinfo.ml
ocaml/xapi/repository.ml
ocaml/xapi/updateinfo.ml
ocaml/xapi/updateinfo.mli

XAPI API version is exposed from updateinfo.xml, to expose it in the output of HTTP API /updates, a new json field "xapi-api-version" is added in the json output only when XAPI API version is exposed from updateinfo.xml successfully, otherwise the returned json data keeps the original format.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xapi-project/xen-api/5886)

CP-46933: Expose XAPI API version in the output of HTTP API /updates

---

ocaml/xenopsd/scripts/common.py
ocaml/xenopsd/scripts/test_common_class_vif.py

For @stephenchengCloud:
FYI: @ashwin9390
In https://github.com/xapi-project/xen-api/pull/5896#pullrequestreview-2223415175, changes were requested:
Before merging `feature/py3` into `master`, certain warnings in files that weren't checked so far should be fixed.
This PR fixes two of the mentioned `pytype` warnings:
```py
File "xen-api/ocaml/xenopsd/scripts/common.py", line 198, in get_words: Name 'string' is not defined [name-error]
File "xen-api/ocaml/xenopsd/scripts/common.py", line 201, in get_words: Name 'string' is not defined [name-error]
```
These uses of the not defined variable `string` are in an inner function of `VIF.get_locking_mode()`.
This inner function (`get_words`) isn't used by the method, see:
https://github.com/xapi-project/xen-api/blob/master/ocaml/xenopsd/scripts/comm …

`xenopsd`: Fix `pytype` warning on `get_words`: Name `string` is not defined

---

dune
dune-project
ocaml/libs/http-lib/dune
ocaml/libs/http-lib/http.ml
ocaml/libs/http-lib/http.mli
ocaml/libs/http-lib/http_svr.ml
ocaml/libs/http-lib/http_svr.mli
ocaml/libs/tracing/tracing.ml
ocaml/libs/tracing/tracing.mli
ocaml/xapi/api_server.ml
ocaml/xapi/dune
ocaml/xapi/server_helpers.ml
xapi-rrdd.opam

Instruments functions such as:
`handle_one`
`callback`
`callback1`
`dispatch`
`jsoncallback`
`response`
...
This should help us determine where the time is spent between receiving the request and sending back a response.
Latest BVT passed: 202675 (Dev Run)

CP-50444: Instrument http svr with dt

---

ocaml/idl/datamodel_lifecycle.ml
ocaml/xapi-cli-server/cli_operations.ml

1. Update the auto-generated changes in `datamodel_lifecycle.ml` before the code is merged into master.
2. Update `scheme` to `https` in `Cli_operations.pool_sync_bundle` as `http` can't be used in newcli and will be executed on slave.

CP-49217: Update datamodel_lifecycle

---

.github/dco.yml

This change would allow commits to retroactively sign off ("remediate") commits that are already in `master`, without rewriting history. Ideally, no commit would get into `master` without being signed off. However, we have found that it is possible for the DCO bot to confuse the author's chosen sign-off name + email combination with the name + email combination that GitHub creates on the author's behalf when producing a merge commit. Since the DCO bot doesn't only compare by email, it believes there is a discrepancy and sets the DCO to fail.

Allow remediation commits for DCO

---

ocaml/xcp-rrdd/scripts/rrdd/rrdd.py

Ensure that the updated data and metadata are written before the headers are updated otherwise xcp-rrdd might start reading the data block before all the data is populated and thus run off the end of the data.

CA-396751: write updated RRDD data before headers

---

ocaml/xenopsd/scripts/qemu-wrapper
scripts/xapi-nbd.service
scripts/xapi.service
scripts/xcp-networkd.service

jemalloc was updated to version 5.3.0:
- Provides libjemalloc.so.2 instead of libjemalloc.so.1
- No longer supported `lg_dirty_mult` option
Note that part of the change is in the .spec file.
Tested that all `.service` files have been replaced:
```
[root@xrtmia-11-09 ~]# find / -type f  -name "*.service" | xargs grep "libjemalloc.so.1"
find: ‘/proc/4079’: No such file or directory
[root@xrtmia-11-09 ~]# find / -type f  -name "*.service" | xargs grep "libjemalloc.so.2"
/usr/lib/systemd/system/xcp-rrdd.service:Environment="LD_PRELOAD=/usr/lib64/libjemalloc.so.2"
/usr/lib/systemd/system/xapi-nbd.service:Environment="LD_PRELOAD=/usr/lib64/libjemalloc.so.2"
/usr/lib/systemd/system/xenopsd-xc.service:Environment="LD_PRELOAD=/usr/lib64/libjemalloc.so.2" …
```

CA-397171: Replace libjemalloc.so.1 with libjemalloc.so.2

---

ocaml/xapi/xapi_globs.ml
scripts/xe-reset-networking

CA-392685 :/tmp is mounted with type tmpfs which cause the files to be cleaned after host reboot in XS rawhide 
Fix contains:
- Replace /tmp/network-reset  with /var/tmp/network-reset to persist tmp file after reboot
- Modified xapi_globs.ml to include this change.
XenRT test -Completed 
Test Results:
Test id :4073591(XS9)-Pass
Test id :4068756(XS8)-Pass 
@liulinC @psafont @rosslagerwall @bernhardkaindl

CA-392685:/tmp is mounted with type tmpfs which cause the files to be cleaned after host reboot in XS rawhide.

---

ocaml/tests/test_xapi_vbd_helpers.ml
ocaml/xapi/xapi_vbd_helpers.ml

In the commit 62db5cb, the device name validation was consolidated with
the function which converts name to device number. Particularly, the
function "Device_number.of_string" is used for both the validation and
the conversion.
But one issue was introduced in the validation is that the "None" value
returned from "Device_number.of_string" is considered as valid. This
causes the error "the device name is invalid".
This PR just fixes this issue. And meanwhile, a unit test is also added.

CA-397268: vbd.create failed: The device name is invalid

---

ocaml/xapi-cli-server/record_util.ml
ocaml/xapi/message_forwarding.ml
ocaml/xapi/rrdd_proxy.ml
ocaml/xapi/taskHelper.ml

* CA-395174: Try to unarchive VM's metrics when they aren..
* CA-395174: Try to unarchive VM's metrics when they aren..
* CA-394444: Update `vm_operation_table`                   
* CA-394444: Update task cancellation in `message_forward..
* CA-394169: Allow task to have permissions on itself - b..
* CA-394169: Allow task to have permissions on itself

Backports for UPD-1009 / CP-50580

---

ocaml/xapi-idl/storage/storage_interface.ml
ocaml/xapi/xapi_sr.ml

Previously sr-scan first performs an SR.ls followed by an SR.stat, which will fail when the SR is not healthy. Now that we included more health messages in SR.stat, we can give perform SR.stat first and fail the operation if SR.stat gives unhealthy state, and tell the user about the unhealthy state.

CP-51042: Raise error in sr-scan when SR.stat finds an unhealthy SR

---

ocaml/message-switch/core_test/interop-test.sh
scripts/generate-iscsi-iqn
scripts/xe-backup-metadata
scripts/xe-restore-metadata

- Update following embeded shellbang to python3
* generate-iscsi-iqn 
* xe-backup-metadata
* xe-restore-metadata
- Remove interop-test.sh as not used

CP-49148: More clean python2 code

---

doc/layouts/xenapi/class.html

Allows to copy the documentation, since clicking on the function details no longer hides the `<div>`
New docs were tested locally, confirming the behaviour

new-docs: Toggle hidden documentation only on header clicks

---

ocaml/sdk-gen/c/autogen/src/xen_common.c

We already have an internal ticket to address this but builds will start to fail once `ubuntu-latest` points to packages already in `24.10` or above.
The deprecation for `libxml2` was added in `2.11.0` (see [here on GitLab](https://gitlab.gnome.org/GNOME/libxml2/-/commit/b47ebf047e959f43ae34582101a37b26764b9be3))
Fedora 40 already switched to 2.11.0+, and Ubuntu 24.10 did, too. Ubuntu 22.04 and 24.04 haven't, hence why builds aren't failing just yet.
Tested locally on Fedora 40 with `libxml2-2.12.8-1.fc40.x86_64`

Add temporary exception for deprecation of `xmlStringDecodeEntities`

---

ocaml/libs/xapi-stdext/lib/xapi-fd-test/dune
ocaml/libs/xapi-stdext/lib/xapi-fd-test/generate.ml
ocaml/libs/xapi-stdext/lib/xapi-fd-test/generate.mli
ocaml/libs/xapi-stdext/lib/xapi-fd-test/observations.ml
ocaml/libs/xapi-stdext/lib/xapi-fd-test/observations.mli
ocaml/libs/xapi-stdext/lib/xapi-fdcaps/operations.ml
ocaml/libs/xapi-stdext/lib/xapi-fdcaps/operations.mli
ocaml/libs/xapi-stdext/lib/xapi-fdcaps/test/test_operations.ml
ocaml/libs/xapi-stdext/lib/xapi-stdext-threads/threadext.ml
ocaml/libs/xapi-stdext/lib/xapi-stdext-threads/threadext.mli
ocaml/libs/xapi-stdext/lib/xapi-stdext-unix/test/dune
ocaml/libs/xapi-stdext/lib/xapi-stdext-unix/test/unixext_test.ml
ocaml/libs/xapi-stdext/lib/xapi-stdext-unix/unixext.ml
ocaml/libs/xapi-stdext/lib/xapi-stdext-unix/unixext.mli
ocaml/quicktest/dune
ocaml/quicktest/quicktest
ocaml/quicktest/quicktest.ml

First write tests for the semantics of Unix.select.
Then introduce a Unixext.select implemented using epoll, and switch the tests to test this function: now we know that Unixext.select semantics matches Unix.select.
(we don't test error semantics, because XAPI only calls Unix.select with an empty list as the error list).
This doesn't yet switch the code to use Unixext.select, that will be done on feature/perf as it needs more testing.
Draft, needs testing in koji and some ticket numbers.
Also I don't know why the BLK tests haven't failed before on master, maybe they are not being run correctly, they were supposed to run as part of the Quicktests...

tests for Unix.select and introduce select-as-epoll

---

ocaml/idl/datamodel_lifecycle.ml
ocaml/tests/test_features.ml
ocaml/xapi-types/features.ml
ocaml/xapi-types/features.mli
ocaml/xapi/message_forwarding.ml

This should be released together with an update to v6d to enable the new flags by default.

Add feature flags to block starting VMs

---

ocaml/libs/xapi-stdext/lib/xapi-stdext-unix/test/unixext_test.ml

We've enabled running the unixext tests in quicktest. They open 1024 file descriptors on startup to check for the absence of select. And although that works for unixext (it is select-free), it doesn't yet work for the rest of quicktests on master (the required changes to make it work are on the epoll branch).
Temporarily disable this test and add a note to reenable it on the epoll branch.
Fixes: efcb7af9d9d2 ("CP-50448: run the QuickCheck tests in QuickTest")

quicktest: disable open 1024 fds on startup for now

---

ocaml/xapi-storage/generator/lib/data.ml

This is to be used as part of the inbound storage migration process and will make available a UNIX domain socket which can have an open file descriptor passed to it via SCM_RIGHTS. This takes the place of the /run/blktap-control/nbdserver<pid>.<minor> path used in SXM on SMAPIv1.
Implementations shall arrange to make available a mechanism whereby an open file descriptor can be passed and then used to connect to an active new-fixed NBD server providing access to the specified [uri]

CP-51278: define import_activate datapath operation

---

ocaml/xe-cli/bash-completion

Otherwise, these prefixes break autocompletion of common prefixes, like in:
```
$ xe pool-param-get <TAB>
OPTIONAL: database:    REQUIRED: param-name=
OPTIONAL: param-key=   REQUIRED: uuid=
$ xe pool-param-get p<TAB> <- gets autocompleted before showing further suggestions
$ xe pool-param-get param-
param-key=   param-name=
```
Without this fix, instead worked like this:
```
$ xe pool-param-get <TAB>
OPTIONAL: database:    REQUIRED: param-name=
OPTIONAL: param-key=   REQUIRED: uuid=
$ xe pool-param-get p<TAB> <-- no prefix autocompletion
OPTIONAL: param-key=   REQUIRED: param-name=
```
This is a temporary workaround, since upgrading bash would allow us to show prefixes as section headers without polluting suggested words themselves.

xe autocompletion: Only show required/optional prefixes when parameter name is empty

---

ocaml/xe-cli/bash-completion

Fixes the bug when optionality of parameters would be shown when all the remaining parameters were of the same category, autocompleting the noise:
```
$ xe vm-param-get <TAB>
OPTIONAL: database:    REQUIRED: param-name=
OPTIONAL: param-key=   REQUIRED: uuid=
$ xe vm-param-get param-name=SMTH uuid=SMTH <TAB> <- automatically completes to
$ xe vm-param-get param-name=SMTH uuid=SMTH OPTIONAL:
```
Now works as intended:
```
$ xe vm-param-get param-name=SMTH uuid=SMTH <TAB>
database:   param-key=
```
=====
Cmdliner might be getting some support for generating generic autocompletion scripts (https://github.com/dbuenzli/cmdliner/pull/187), and dune has been exploring this as well (https://github.com/ocaml/dune/pull/6377). Go and Python CLI tooling has had this for a long time …

xe autocompletion: Exclude previously entered parameters before deciding whether to show optionality of the parameters

---

.pre-commit-config.yaml
pyproject.toml

This causes problems with forks that don't have feature/py3. Although would it then compare with the fork's master branch which would still be out-of-date?

fix(CI): feature/py3 has been merged, refer to master now

---

ocaml/idl/ocaml_backend/gen_api.ml
ocaml/idl/ocaml_backend/gen_api_main.ml
ocaml/idl/ocaml_backend/ocaml_utils.ml
ocaml/tests/record_util/old_enum_all.ml
ocaml/tests/record_util/old_record_util.ml
ocaml/tests/record_util/test_record_util.ml
ocaml/xapi-cli-server/cli_operations.ml
ocaml/xapi-cli-server/dune
ocaml/xapi-cli-server/record_util.ml
ocaml/xapi-cli-server/records.ml
ocaml/xapi/import.ml
ocaml/xapi/message_forwarding.ml
ocaml/xapi/xapi_message.ml
ocaml/xapi/xapi_network_sriov_helpers.ml
ocaml/xapi/xapi_pool_helpers.ml
ocaml/xapi/xapi_vbd.ml
ocaml/xapi/xapi_vbd_helpers.ml
ocaml/xapi/xapi_vdi.ml
ocaml/xapi/xapi_vif_helpers.ml
ocaml/xapi/xapi_vm.ml
ocaml/xapi/xapi_vm_clone.ml
ocaml/xapi/xapi_vm_clone.mli
ocaml/xapi/xapi_vm_lifecycle.ml
ocaml/xapi/xapi_vm_migrate.ml
ocaml/xapi/xapi_vusb_helpers.ml
ocaml/xapi/xapi_xenops.ml

Best reviewed by commit - commit messages include the necessary context.
Changes can mostly be grouped into:
* Implementing autogeneration
* Removing manually-specified conversion functions that are identical to the automatically-generated ones
* Removing converters identical in function but not in form **(requires renaming usage sites)** - these are commit-per-function for ease of review, but can be squashed before merging
* Removing conversion functions that were not covered with tests **(requires also adding corresponding tests)** - these are commit-per-function
* Justifying the grim shadowing existence of the rest.
It might seem like a big patch, but most of it is removing and renaming things, with only a tiny bit of new code. Since Edwin's PR some time ago (#5349), we can now confirm …

IH-689: Autogenerate record_util.ml (where it's reasonable)

---

ocaml/xapi-idl/storage/dune
ocaml/xapi-idl/storage/storage_interface.ml
ocaml/xapi-idl/storage/storage_skeleton.ml
ocaml/xapi-storage-script/dune
ocaml/xapi-storage-script/main.ml
ocaml/xapi/storage_mux.ml
ocaml/xapi/storage_smapiv1_wrapper.ml
ocaml/xapi/xapi_sr.ml

Second attempt of the reverted PR, this time introduce a new SMAPIv2 API and let SMAPIv1 and v3 implementations to decide what to do

CP-51042: Introduce new SR.scan2 for SMAPI{v1,v2,v3}

---

ocaml/xenopsd/cli/dune
ocaml/xenopsd/cli/xn.ml

Previously, the output of `xenops-cli diagnostics` was ill-formed JSON, as keys weren't quoted strings and objects weren't separated by commas. Just use yojson.prettify instead.
Before:
```
$ xenops-cli diagnostics
{
vm_actions:  {} tasks:  [] updates:  {
updates:  [] barriers:  []
} scheduler:  [] workers:  [
{
state:  Idle
} {
state:  Idle
} {
state:  Idle
}
] queues:  []
}
```
After:
```json
$ xenops-cli diagnostics
{
"vm_actions": {},
"tasks": [],
"updates": { "updates": [], "barriers": [] },
"scheduler": [],
"workers": [
{ "state": "Idle" },
{ "state": "Idle" },
{ "state": "Idle" }
],
"queues": []
}
```
Nothing seems to rely on parsing the output of xenops-cli, so this should be safe.

CP-32625: xenops-cli - replace handwritten JSON prettifier with yojson

---

ocaml/idl/datamodel.ml
ocaml/idl/datamodel_lifecycle.ml
ocaml/idl/schematest.ml
ocaml/xapi-cli-server/records.ml
ocaml/xapi/import.ml
ocaml/xapi/xapi_guest_agent.ml
ocaml/xapi/xapi_vm_helpers.ml

Exposes one of the keys reported by the Windows Guest Agent through VM_guest_metrics. This is designed to make it easier for admins to match up the AD hostname to a VM object - and CVAD uses the FQDN (host name + domain) in their UI, so this is what's exposed.
```
$ xenstore-read /local/domain/10/data/domain
eng.citrite.net
$ xenstore-read /local/domain/10/data/host_name_dns
WINDOWS-3LIPCLJ
$ xe vm-param-get uuid=WIN_UUID param-name=host-name
host_name: WINDOWS-3LIPCLJ.eng.citrite.net
```

IH-666: Report guest AD domain name and host name in the API

---

ocaml/xapi/xapi_cluster.ml
ocaml/xapi/xapi_cluster_host.ml
ocaml/xapi/xapi_clustering.ml
ocaml/xapi/xapi_clustering.mli
ocaml/xapi/xapi_observer_components.ml
ocaml/xapi/xapi_pool_transition.ml
quality-gate.sh

This solves the problem where disabling and enabling clustering sometimes makes the thread not start, because it is still in the middle of processing, and by the time it reaches the end and reset the `cluster_change_watcher`, `create_as_necessary` has already be called with `cluster_change_watcher` equal to true. Therefore set `cluster_change_watcher` immediately to false as soon as the cluster is to be destroyed (or the master is to be changed).

CA-398438: Signal exit to the watcher thread

---

ocaml/libs/xapi-stdext/lib/xapi-fdcaps/test/test_operations.ml

This fails when running kojienv from WSL2, but works when running kojienv from an actual Linux. In a WSL2 kojienv /dev/loop0 is world writable (even though the user is not root), whereas in a real kojienv /dev/loop0 is not world writable.
This test was here just to test my assumptions that indeed non-root cannot create block devices, assumptions which are not true in WSL2, so remove this test.
In Dom0 we run as root always, so this has no effect on the product.

fix(WLS): disable non-root unit test

---

ocaml/xapi/xapi_network.ml
ocaml/xapi/xapi_pif.ml
ocaml/xapi/xapi_pif.mli

This'll make it more obvious if test code attempts to do the wrong thing (such as setting `ibft0` with NBD purpose and expecting that to work).
It'll also make it easier for test code to filter out these networks, so it doesn't touch them.
Unfortunately we do need to create the Network object, because the PIF object references it, and I wouldn't want to make the reference null (it'll likely cause failures elsewhere in XAPI where it assumes that PIFs always have a network).
And we probably want to keep the PIF with managed=false for reporting purposes (the interface does have an IP address, which is useful to be able to see in the API).
Draft, needs some actual testing, I've only compile tested this so far.

CA-396743: Don't allow NBD on boot from SAN devices, and fix Network.managed to reflect PIF.managed

---

ezxenstore.opam
ezxenstore.opam.template
ocaml/database/block_device_io.ml
ocaml/database/master_connection.ml
ocaml/forkexecd/src/child.ml
ocaml/libs/ezxenstore/core/dune
ocaml/libs/ezxenstore/core/watch.ml
ocaml/libs/http-lib/buf_io.ml
ocaml/libs/http-lib/http.ml
ocaml/libs/xapi-stdext/lib/xapi-stdext-unix/test/unixext_test.ml
ocaml/libs/xapi-stdext/lib/xapi-stdext-unix/unixext.ml
ocaml/libs/xapi-stdext/lib/xapi-stdext-unix/unixext.mli
ocaml/message-switch/unix/dune
ocaml/networkd/lib/jsonrpc_client.ml
ocaml/tests/common/suite_init.ml
ocaml/tests/dune
ocaml/tests/unix_select.gawk
ocaml/xapi-idl/lib/dune
ocaml/xapi-idl/lib_test/dune
ocaml/xapi-idl/lib_test/scheduler_test.ml
ocaml/xe-cli/newcli.ml
ocaml/xenopsd/cli/dune
ocaml/xenopsd/cli/xn.ml
ocaml/xsh/dune
ocaml/xsh/xsh.ml
scripts/xapi.service
xapi-idl.opam
xapi-idl.opam.template

One small commit on top of https://github.com/xapi-project/xen-api/pull/5910 that switches from select to epoll ~everywhere in xapi/xenopsd.
Draft because we need to merge that PR first, then have a PR to update feature/perf from master.
Will need to be rebased on https://github.com/xapi-project/xen-api/pull/5913 once the prerequisites for that PR get merged.

Switch to epoll

---

ocaml/xenopsd/xc/dune
ocaml/xenopsd/xc/mem_stats.ml
ocaml/xenopsd/xc/mem_stats.mli
ocaml/xenopsd/xc/xenops_xc_main.ml

Based on xapi_stats.ml, but heavily refactored.
This is https://github.com/xapi-project/xenopsd/pull/772, but I squashed and rebased the 2 commits on top of latest master, and ran `ocamlformat`, and fixed some dune warnings.
Original commits in xenopsd repo:
(cherry picked from commit 40d3aa7923c7a5c7654d9e83508e52b3b7c3840a)
(cherry picked from commit b30f2310e6087ef59c486410f079175bf36aa705)
So far I've only compile tested this change, hence a draft.

CP-38343: xenopsd: GC and memory RRD stats

---

.github/workflows/generate-and-build-sdks.yml
.github/workflows/release.yml
ocaml/sdk-gen/java/main.ml
ocaml/sdk-gen/java/templates/Class.mustache
ocaml/sdk-gen/java/templates/Types.mustache

Unfortunately, I couldn't come up with an easy way to keep the same order of types in `Types.java`. The issue here is that they were added as they were found, so there was no specified order.
A good way to check would probably be to compare class structures instead. I'm happy to assist if possible.
The SDK sources are present in the PR's artifacts so you don't have to build them yourself.
This PR also adds the JAR to the release files.
Note that I did keep the existing side-effect operations of updating `enums`, `types`, etc.. I found that they weren't _that_ much of an hassle to keep but feel free to weigh in. 
For result of a release with the changes here see https://github.com/danilo-delbusso/xen-api/releases/tag/v60.1.3

[OIL] Use mustache templates to build Java SDK + Add Java SDK build step to actions 

---

ocaml/doc/wire-protocol.md
ocaml/idl/templates/toc.mustache
ocaml/sdk-gen/c/templates/Makefile.mustache
ocaml/sdk-gen/csharp/FriendlyErrorNames.resx
ocaml/sdk-gen/csharp/autogen/src/Failure.cs

- C SDK: curl flags are not needed since the SDK does not depend on curl.
- Removed entries that don't correspond to API messages. Removed obsolete parsing for CSLG failures.
- Minor doc corrections.

Random small corrections in the SDK and docs.

---

ocaml/idl/datamodel_vm.ml
ocaml/idl/schematest.ml
ocaml/xapi/message_forwarding.ml
ocaml/xapi/xapi_vm.ml
ocaml/xapi/xapi_vm.mli

```
CA-397599 XSI-1704 implement setter for blocked ops manually
Currently the setter for field VM.blocked_operations is auto generated.
Implement this explicitly such that we can update allowed operations
which currently is not happening. Allowed operations are used by
XenCenter to disable operations; this has led to operations becoming
unavailable because allowed operations where not aligned with blocked
operations when blocked operations were updated.
```

CA-397599 XSI-1704 

---

.github/workflows/format.yml
.github/workflows/main.yml
.github/workflows/other.yml
.github/workflows/shellcheck.yaml

Required for merge queues, so we have some tests that run in the merge queue: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions

[ci]: enable merge queues

---

ocaml/libs/xapi-stdext/lib/xapi-stdext-unix/test/unixext_test.ml
ocaml/quicktest/quicktest

The following environment variables can now be used by tests:
* QCHECK_LONG_FACTOR (default 10): multiplies the default iteration count of 100
* QCHECK_SEED: an integer seed (the tests print their current seed on startup otherwise, can be used to reproduce a failure)
These environment variables are already supported by the QCheck framework, we just need to use them.

CP-51483: epoll tests: support QCHECK_LONG_FACTOR

---

ocaml/gencert/gencert.ml
ocaml/idl/datamodel_lifecycle.ml

Last year, an argument to determine the group id of the certificates created
was added. This broke test clients, and there's no need no make it compulsory
since there's a default value: -1.
Modify the binary so it can accept only 3 arguments like before, and change the
help output to mention the group id.
This makes quite a few internal certificate tests to pass compare the previous suite run 204647 to the new 204840

CA-399187: Allow gencert to be called without groupid

---

.ocamlformat

OCamlformat will correctly format new features only when it's aware the OCaml version it's outputting provides them. This allows to improve formatting for let-punning, punned labelled arguments, and more:
https://github.com/ocaml-ppx/ocamlformat/blob/main/CHANGES.md#added-8

Specify OCaml version for ocamlformat's output

---

clock.opam
dune-project

clock now uses xapi-log, so it needs to have the dependency declared in opam

opam: declare missing dependencies

---

.github/workflows/main.yml
.github/workflows/other.yml
.github/workflows/shellcheck.yaml

We notice that required CI checks cancel themselves even when attempting to merge a single PR at a time. That is probably because there are CI jobs run on both 'push' and 'merge_group'.
Try to make the concurrency group more unique by adding the github event name to the group key.

[ci]: make concurrency group more unique

---

ocaml/libs/tracing/tracing.ml
ocaml/libs/tracing/tracing.mli
ocaml/libs/tracing/tracing_export.ml
ocaml/tests/bench/bechamel_simple_cli.ml
ocaml/tests/bench/bench_tracing.ml
ocaml/tests/bench/dune
ocaml/tests/test_observer.ml
ocaml/xapi/xapi_globs.ml

We've noticed some delays when tracing is enabled, and suspected it is due to lock contention or GC activity created by the tracing module itself.
I've added some benchmarks to measure the overhead of tracing, and made some improvements (more improvements are possible).
The benchmarks test both a situation with no workload, and a situation with 2 other threads: one running the same workload as the function under test, and another that runs a very GC intensive workload.
Improved:
* when max spans limit is hit: don't spam syslog. Time goes down from  202 *milli*seconds to 14 *micro*seconds per span
* reduce lock contention: eliminate one global lock, replace with atomic ops
* reduce allocation
We are now at ~9µs/nested span on this particular machine, but further improvements are possible …

Tracing: optimize and reduce overhead

---

ocaml/xe-cli/bash-completion

Before, having an escape sequence as part of the parameter would break grep:
```
$ xe vdi-list name-label=CentOS\ 7\ \(1grep: Unmatched ( or \(
```
Move back to pure bash processing for the prefix, since it's the weirdness of variable escaping leaving the bash context causing this.

xe autocompletion: Fix prefix escaping bug

---

python3/bin/xe-reset-networking

Only exits script when an error occurs when
getting the static IPv6 config info

Fix network reset script in static IPv6

---

ocaml/sdk-gen/go/templates/ConvertEnum.mustache
ocaml/sdk-gen/go/templates/Enum.mustache
ocaml/sdk-gen/go/test_data/enum.go
ocaml/sdk-gen/go/test_data/enum_convert.go

Bug fix for Go SDK, add an default Enum value to replace raising error for unknown Enum value.
Build new SDK and samples,  test pass XenRT job: 4100718.

CA-398138: Handle enum value unknown error for Go SDK

---

ocaml/xapi/xapi_pool.ml

In pre-join check for pool.join, assert that there is no host pending mandatory guidance on the joining host or the pool coordinator.

CA-399229: Assert no host pending mandatory guidance for pool.join

---

ocaml/xapi/xapi_pif.ml

Do not assume IPv4 instead see what's in the inventory's
`MANAGEMENT_ADDRESS_TYPE`.

Determine IP address type from inventory when creating a PIF

---

ocaml/xapi/xapi_host.ml

Instead look at the inventory to decide the address type, this will avoid to override the value in the inventory when its rewritten

Do not assume IPv4 when disabling management

---

ocaml/xapi/xapi_pool.ml

Until now only the IPv4 config was written and an IPv6 ejected host would loose its config after restarting in its own pool.

Write IPv6 management config as well when ejecting an host

---

ocaml/tests/test_repository_helpers.ml
ocaml/xapi/repository_helpers.ml

When applying livepatches, for one component, only the latest one will
be applied. This is because the latest livepatch will always roll up all
the previous ones if they are of the same component and base build ID.
The bug to be fixed in this commit is that the previous livepatches with
the same build ID are not returned in the response of the query on
the /updates HTTP endpoint.

CA-399638: The livepatches are absent in the response of /updates

---

ocaml/xapi/xapi_pif.ml

Like for IPv4 bring up IPv6 configured virtual PIF when starting up an host.

Bring up IPv6 only virtual PIF as well on startup

---

ocaml/xapi/xapi_globs.ml
ocaml/xapi/xapi_session.ml

This PR allows pool sessions to be reused, rather than wasting time creating new ones each time to talk to the slaves.
The average time spent across 15 slave get_servertime xenapi calls on a virtual pool was 20.97ms with reuse-pool-sessions = false.
Compared to an average of 17.11ms with reuse-pool-sessions = true
In particular, the part of the request that has actually been changed, the login_no_password call has gone from about 2.41ms to 0.008ms, 300x faster than previously.
One part of why this speedup is possible is because we no longer have to do a pool.get_all for each session (to force the newly created session's time to update). If we were to validate the reusable pool session is valid before use, we would still need to do this pool.get_all. However, as we are now no longer …

CP-48676: Reuse pool sessions on slave logins

---

ocaml/cdrommon/cdrommon.ml
ocaml/libs/xapi-stdext/lib/xapi-stdext-unix/unixext.ml
ocaml/libs/xapi-stdext/lib/xapi-stdext-unix/unixext.mli
ocaml/networkd/bin/networkd.ml
ocaml/squeezed/src/squeezed.ml
ocaml/xapi-idl/lib/xcp_service.ml
ocaml/xapi-idl/lib/xcp_service.mli
ocaml/xapi-storage-script/main.ml
ocaml/xapi/xapi_main.ml
ocaml/xcp-rrdd/bin/rrdd/xcp_rrdd.ml
ocaml/xenopsd/lib/xenopsd.ml
ocaml/xenopsd/xc/xenops_xc_main.ml
quality-gate.sh
scripts/cdrommon@.service

Last usage of `Unixext.daemonize` was in `cdrommon`, drop it and move the daemon to be fully handled by systemd (instead of `type=forking`).
`cdrommon` service is only started by storage scripts, and I'm not sure if it's tested at all, but these changes pass BST+BVT.

CP-28369: Remove `Unixext.daemonize`

---

dune-project
ocaml/quicktest/dune
ocaml/xs-trace/test/dune
xapi-tools.opam
xapi.opam

They were misatributed to xapi, when the binaries are built for other packages

ocaml: fix packages for quicktest and xs-trace tests

---

ocaml/tests/test_xapi_helpers.ml
ocaml/xapi-idl/lib/xcp_service.ml
ocaml/xapi-idl/lib/xcp_service.mli
ocaml/xapi/xapi_globs.ml
quality-gate.sh

Fixes: 6635a00d68e5 ("CP-49136: Introduce PRNG for generating non-secret UUIDs")

fix(xapi)): cannot compare functional values

---

ocaml/xapi-idl/lib/xcp_service.ml
ocaml/xcp-rrdd/bin/rrdp-cpu/dune
ocaml/xcp-rrdd/bin/rrdp-iostat/dune
ocaml/xcp-rrdd/bin/rrdp-netdev/dune
ocaml/xcp-rrdd/lib/plugin/dune

ezxenstore wasn't being installed by the specfile, but a new dependency was added between the RRDD plugins and Ezxenstore.
We don't want to introduce new publicly installed packages in the specfile, so move ezxenstore to an existing package: the RRDD plugin one.

fix: do not expose new sublibrary of rrdd-plugin that depends on ezxenstore

---

ocaml/xe-cli/bash-completion

For unresolved reasons, `compgen -W` would not work as intended occasionally:
`xe host-param-get uuid=xxx param-na<TAB>`
would complete to:
`xe host-param-get uuid=xxx param-name=`
but typing:
`xe host-param-get uuid=xxx param-name=so<TAB>`
would not complete it to:
`xe host-param-get uuid=xxx param-name=software-version`
It's unlikely to be a bug in Bash since I couldn't find anything in the
changelog and upgrading the package did not fix it; nor could I reproduce it in
a different program with the same inputs - it is likely that something in the
environment breaks compgen. Switch to pure Bash string processing instead.

CA-399956 - xe autocompletion: Fix autocompletion for words with given prefix

---

ocaml/xapi-storage-script/dune

Otherwise opam + dune will try to run them as part of all the packages in the repository.

xapi-storage-script: attach tests to the package

---

ocaml/xapi/xapi_xenops.ml
ocaml/xenopsd/xc/xenops_server_xen.ml

This is probably overzealous, so please let me know if some of these logs are still helpful. I have kept the "migrating away" logs as Christian said these are rare.

CP-51714: Remove noisy xenopsd debug logs

---

ocaml/libs/xapi-stdext/lib/xapi-stdext-unix/test/test_systemd.ml

Setting up the server for the tests sometimes fails to write the new state to stdout. Catch an exceptions while binding the socket to print them and make the issue more visible.
Ironically, as soon as I started testing xs-opam with this patch, the issue magically disappeared, so I don't know what went wrong.

xapi-stdext-unix: catch exceptions in the test server

---

ocaml/idl/ocaml_backend/gen_rbac.ml
ocaml/libs/ezxenstore/watch/ez_xenctrl_uuid.ml
ocaml/libs/uuid/uuidx.ml
ocaml/libs/vhd/vhd_format/f.ml
ocaml/libs/xapi-inventory/lib/inventory.ml
ocaml/tests/test_ref.ml
ocaml/xapi-guard/test/cache_test.ml
ocaml/xapi-guard/test/xapi_guard_test.ml
ocaml/xapi-idl/lib/uuidm_rpc_type.ml

Unblocks the CI on all open PRs

maintenance: avoid deprecated bindings in uuidm 0.9.9

---

ocaml/xapi/certificates.ml
ocaml/xapi/xapi_globs.ml

`openssl rehash` sub command provides the same functionality for `c_rehash`, but quicker
We replace `c_rehash` with `openssl rehash` in XS9, However, we will keep `c_rehash` compatbilility for XS8 stream

CP-50603: Replace `c_rehash` with `openssl rehash` sub command

---

ocaml/libs/xapi-rrd/lib/rrd.ml
ocaml/libs/xapi-rrd/lib_test/crowbar_tests.ml
ocaml/libs/xapi-rrd/lib_test/unit_tests.ml
ocaml/xapi-idl/rrd/ds.ml
ocaml/xcp-rrdd/bin/rrdd/rrdd_monitor.ml
ocaml/xcp-rrdd/bin/rrdp-cpu/rrdp_cpu.ml
ocaml/xcp-rrdd/lib/transport/base/rrd_json.ml
ocaml/xcp-rrdd/lib/transport/base/rrd_protocol_v2.ml
ocaml/xcp-rrdd/lib/transport/base/rrd_rpc.ml
ocaml/xcp-rrdd/lib/transport/base/rrd_rpc.mli
ocaml/xenopsd/xc/mem_stats.ml

Previously, the transform function was not serialized in the plugin-server protocol (it was only used in xcp_rrdd itself, not in plugins). This issue was revealed by the previous work around splitting cpu metrics into a separate plugin.
Instead of allowing arbitrary functions (which would be difficult to serialize), for 'fun x' offer just two options:
* Inverse (1.0 - x), and
* Identity (x)
Default (if the parameter is not provided, either in OCaml or JSON), is Identity.

CA-400124 - rrd: Serialize transform parameter for data sources

---

ocaml/xapi/db_gc.ml

In XSI-1722 we notive that xapi does not detect a host beeing offline based on the heartbeat. The reason is a bug: we miss to store a new timer in the corresponding hashtable.

XSI-1722 fix timer for host heartbeat

---

python3/libexec/nbd_client_manager.py
python3/tests/test_nbd_client_manager.py

to connect to nbd devices, nbd_client_manager will
1. protect the operation with /var/run/nonpersistent/nbd_client_manager file lock
2. check whether nbd is being used by `nbd-client -check`
3. load nbd kernel module by `modprobe nbd`
4. call `nbd-client` to connect to nbd device
However, step 3 will trigger systemd-udevd run asyncly, which would open and lock the same nbd devices, run udev rules, etc. This introduce races with step 4, e.g. both process want to open and lock the nbd device.
Note: the file lock in step 1 does NOT resovle the issue here, as it only coordinate multiple nbd_client_manager processes.
To fix the issue,
- we patch nbd-client to report the device busy from kernel to nbd_client_manager
- nbd_client_manager should check nbd-client exit code, and retry on device …

CA-392674: nbd_client_manager retry connect on nbd device busy

---

ocaml/networkd/bin/network_monitor_thread.ml
ocaml/xapi-idl/network/network_stats.ml
ocaml/xcp-rrdd/bin/rrdp-netdev/dune
ocaml/xcp-rrdd/bin/rrdp-netdev/rrdp_netdev.ml

networkd generates metrics for two users simultaneously:
* xapi db
* rrdd Both of these read from the same shared file, but use non-overlapping stats.
Having moved network metrics collection from xcp-rrdd itself into a plugin, these metrics were serialized twice - moving from networkd to the plugin and from the plugin to the server.
Instead generate metrics in the plugin itself and drop this generation from networkd.

IH-715 - rrdp-netdev: Remove double (de)serialization

---

ocaml/libs/uuid/dune
ocaml/libs/uuid/uuid_test.ml
ocaml/libs/uuid/uuidx.ml
ocaml/libs/uuid/uuidx.mli

* New function Uuidx.make_v7_uuid, with the idea being that ordering v7 UUIDs alphabetically will also order them by creation time
* The values produced by Uuidx.make_uuid_urnd hadn't necessarily been valid UUIDs, since the variant and version fields were being filled in randomly - this is now fixed so that it returns v4 UUIDs.
* There are a couple of functions for generating v4 and v7 from known inputs, for the purpose of unit testing. (The v4 function is mainly there so I could check the setting of variant and version fields by comparing the output with that which Python's UUID module produces.)

IH-577 Implement v7 UUID generation

---

ocaml/doc/wire-protocol.md

The document was updated in f785993f244c0b2234f68338a3478d908bc4a9f4 to use Python 3, however the examples were left unchanged.
In Python 3, `xmlrpclib` does not exist, it has been replaced by the `xmlrpc` module (specifically in this case `xmlrpclib.Server` has been replaced by `xmlrpc.client.ServerProxy`).
Additionally, the `python-jsonrpc` package has not been ported to Python 3, and as such is unavailable. There is no direct replacement, however a combination of the `jsonrpcclient` package and the `requests` packages provide a reasonable solution.
This commit updates the examples appropriately so they function in Python 3.

Update wire-protocol.md to have working Python3 code examples

---

ocaml/networkd/bin/network_server.ml

The pvsproxy socket is available in both /opt/ and /run. Since /run is a more sensible location for a socket, use that one to allow the other to be removed in the future.

Access pvsproxy via a socket in /run

---

ocaml/tests/common/suite_init.ml
ocaml/xapi/xapi_hooks.ml

If you install the XAPI RPMs in your koji build environment (e.g. to build a package that depends on XAPI) then you couldn't build XAPI again anymore because its unit tests were failing. They were failing because they found some xapi hooks installed by the previous version of XAPI, whereas normally there'd be none when the unit tests are running.
Disable running XAPI hooks during unit test, even if present we are not expected to run them.
```
[exception] Unix.Unix_error(Unix.ENOENT, "connect", "")
Raised at Forkhelpers.execute_command_get_output_inner.(fun) in file "ocaml/forkexecd/lib/forkhelpers.ml", line 376, characters 10-19
Called from Xapi_stdext_pervasives__Pervasiveext.finally in file "ocaml/libs/xapi-stdext/lib/xapi-stdext-pervasives/pervasiveext.ml", line 24, characters 8-14 …
```

fix(test): avoid running XAPI hooks in unit tests

---

ocaml/xapi/xapi_cluster.ml
ocaml/xapi/xapi_cluster_helpers.ml
ocaml/xapi/xapi_cluster_host.ml
ocaml/xapi/xapi_clustering.ml

Remove all the gating on cluster_health enabled as an experimental feature now that it is enabled by default.

CP-51683: Make Cluster_health non-exp feature

---

ocaml/idl/datamodel_common.ml
ocaml/idl/datamodel_host.ml
ocaml/idl/datamodel_pool.ml
ocaml/xapi-cli-server/cli_frontend.ml
ocaml/xapi-cli-server/cli_operations.ml
ocaml/xapi/certificates.ml
ocaml/xapi/certificates.mli
ocaml/xapi/message_forwarding.ml
ocaml/xapi/xapi_db_upgrade.ml
ocaml/xapi/xapi_host.ml
ocaml/xapi/xapi_host.mli
ocaml/xapi/xapi_pool.ml
ocaml/xapi/xapi_pool.mli

Also CP-51527: Add --force option to pool-uninstall-ca-certificate.
Addresses the issues raised here by @stormi https://github.com/xapi-project/xen-api/issues/5955

CA-398341: Populate fingerprints of CA certificates on startup

---

ocaml/idl/datamodel_repository.ml
ocaml/idl/schematest.ml
ocaml/xapi-cli-server/cli_frontend.ml
ocaml/xapi-cli-server/cli_operations.ml
ocaml/xapi-cli-server/records.ml
ocaml/xapi/message_forwarding.ml
ocaml/xapi/repository.ml
ocaml/xapi/repository.mli
ocaml/xapi/repository_helpers.ml
ocaml/xapi/xapi_globs.ml
ocaml/xapi/xapi_pool.ml

- add a new type of origin: "remote_pool"
- add a new API: "introduce_remote_pool" to init a remote_pool repository
- add a new field: "certificate" for a remote_pool repository
- for a remote_pool repository, binary_url will be reused to hold the
base URL of binary packages of applied updates in the remote pool:
https://<coordinator-ip>/applied_updates

CP-51393: Datamodel: update Repository for syncing from a remote pool

---

ocaml/networkd/bin/network_monitor_thread.ml

Without it, stats for bond's interfaces are not identified correctly.
Fixes: bd4dda5c294aa51045bf3caccc48bb0870a7d428 (IH-715 - rrdp-netdev: Remove double (de)serialization)

CA-400924 - networkd: Add bonds to `devs` in network_monitor_thread

---

ocaml/xapi/repository.ml
ocaml/xapi/repository_helpers.ml

The HTTP /repository handler is guarded by a mutex `exposing_pool_repo_mutex` currently. Since now HTTP /repository is protected by `session_id` cookie, we can remove the mutex and keep the handler enabled all the time. Also, rename the mutex `exposing_pool_repo_mutex` to `pool_update_ops_mutex`.

CP-51835: Keep the HTTP /repository handler enabled

---

ocaml/xapi-consts/api_errors.ml

Reason:
API errors in go sdk are generated from Api_errors.errors. Error is filled in Api_errors.errors when defined using add_error function. Error too_many_groups is not defined using add_error function.
Fix:
Define too_many_groups using add_error function.

CA-400559: API Error too_many_groups is not in go SDK

---

ocaml/xapi/xapi.ml
ocaml/xapi/xapi_ha.ml
ocaml/xenopsd/cli/xn.ml

These become warnings in ocaml 5.0+

OCaml5: Annotate non-returning functions with types

---

ocaml/forkexecd/test/fe_test.ml
ocaml/libs/uuid/uuidx.ml
ocaml/libs/uuid/uuidx.mli
ocaml/tests/bench/bench_uuid.ml
ocaml/xapi/xapi_globs.ml
quality-gate.sh

This is an alternative to https://github.com/xapi-project/xen-api/pull/6077
2 recent optimizations have changed the Uuidx module to open
/dev/urandom once on startup, instead of every time a value was
requested.
However 'networkd_db' runs in the installer environment, inside a chroot where /dev/urandom is not available.
Open /dev/urandom on first use instead.
Simplify the code and use a single implementation for both fast and secure urandom generation:
* use a mutex to protect accesses to global urandom state
* use an input channel, rather than a Unix file descriptor, this allows us to read many bytes in one go, and then generate multiple random numbers without having to make syscalls that often
(syscalls are slow in this case because they require releasing the runtime mutex, which gives …

CA-400199: open /dev/urandom on first use and use an input channel to reduce number of syscalls

---

ocaml/xcp-rrdd/bin/rrdp-netdev/dune
ocaml/xcp-rrdd/bin/rrdp-netdev/rrdp_netdev.ml

Follow-up to the fix we had to rush, dropping xenctrl entirely.
Tested with a Windows VM, the domain creation is picked up and network metrics are present for it, with correct UUIDs determined.

CA-400860: rrdp-netdev - drop xenctrl, use xenstore to get UUIDs from domids instead

---

ocaml/xenopsd/lib/xenops_server.ml
ocaml/xenopsd/lib/xenops_task.ml
ocaml/xenopsd/lib/xenops_utils.ml

Operations on different devices should be independent and therefore can be
parallelized. This both means parallelizing operations on different device
types and on devices for the same type.
An atom to serialize action has been introduced because the operation regarding
a single device must be kept serialized.
Also removes some unneeded parallel atoms, which cause some overhead as well as polluting the traces
This makes VM_starts to run about ~1 second faster on some tests where VMs have 5 VIFs. I'm testing it further, but it doesn't look like it's breaking any tests. I want to push it through some bootstorms and measure improvements
Please do suggest some further parallelization if you can find it!
BVT+BST are all green

CP-50475: parallelize device ops during VM lifecycle ops

---

ocaml/libs/xapi-stdext/lib/xapi-stdext-unix/test/test_systemd.t

Instead of sleeping and hoping for the best, wait for the background job to finish.

xapi_stdext_unix/test: Fix intermittent systemd cram test failure

---

ocaml/libs/stunnel/stunnel.ml
ocaml/libs/stunnel/stunnel.mli
ocaml/libs/stunnel/stunnel_client.ml
ocaml/libs/stunnel/stunnel_client.mli
ocaml/xapi/helpers.ml

Now xapi supports setting up rpc to hosts in the pool and appliances, while for syncing updates from remote_pool type repository, we need to set up rpc to remote coordinator with its certificate verfieid.
Add util Helpers.make_external_host_verified_rpc, which will set up a secure connection to the external host(host outside the pool) with its host certificate verified.

CP-50789: Enable verified rpc to external host

---

python3/perfmon/perfmon.service
scripts/Makefile
scripts/toolstack.target
scripts/varstored-guard.service
scripts/xapi.service
scripts/xcp-networkd.service
scripts/xcp-rrdd-cpu.service
scripts/xcp-rrdd-dcmi.service
scripts/xcp-rrdd-iostat.service
scripts/xcp-rrdd-netdev.service
scripts/xcp-rrdd-squeezed.service
scripts/xcp-rrdd-xenpm.service
scripts/xcp-rrdd.service
scripts/xe-toolstack-restart

- varstored-guard Before: xenopsd.servcie->xenopsd-xc.service
- Remove unnecessary xenopsd services
* xenopsd
* xenopsd-xenlight
* xenopsd-simulator
* xenopsd-libvirt
- Reorder services to stop/start
* forkexecd: does not depends on others, move to last
* xenopsd-xc After xcp-rrdd. so it needs after xcp-rrdd-*
Note: the for loop reverse the TO_RESTART order

CP-51870: Refresh toolstack services

---

scripts/plugins/firewall-port
scripts/xe-syslog-reconfigure

initscripts family are legacy and want to be removed
`service iptables save` call
/usr/libexec/initscripts/legacy-actions/iptables/save, which call `exec /usr/libexec/iptables/iptables.init save`, to save iptables rules and remove initscripts, we call following directly `/usr/libexec/iptables/iptables.init save`
`service` command are also updated to `systemctl`

CP-50546: Remove initscripts family

---

scripts/toolstack.target

This service is not enabled and started by default, but used on-demand whenever it is needed for clustering. The current Wants= option in the toolstack.target is causing xapi-clusterd.service to be started by xe-toolstack-restart even if it is not enabled.
The fix is to replace Wants= in toolstack.target with WantedBy= in xapi-clusterd.service, as the latter only installs the dependency when enabling the service.

Do not include xapi-clusterd.service in toolstack.target

---

ocaml/tests/test_repository.ml
ocaml/xapi-consts/constants.ml
ocaml/xapi/repository.ml
ocaml/xapi/repository_helpers.ml

1. Add an assertion to restrict `binary_url` of remote_pool repository to be in the
format of `https://<coordinator-ip>/repository/enabled`.
2. Add UT for restrict/check `binary_url` of remote_pool repository.

CP-51836: Restrict/check binary_url of remote_pool repository

---

ocaml/networkd/bin/network_server.ml

A previous commit changed the socket location to /run/pvsproxy but this is problematic because the pvsproxy daemon runs as a deprivileged user and cannot create the socket.
Instead, update the path to a location that the daemon has permission to create. Add a fallback to the original path to cope with older pvsproxy daemons. This fallback can be removed in the future.

CA-401324: Update pvsproxy socket location

---

scripts/xe-toolstack-restart

`systemctl list-dependencies --plain --no-pager` list uncessary xapi-clusterd service when xapi-clusterd-shutdown is started.
Here instead of checking the status of all dependencies, we only check the status of previous acitve dependencies. This also complies with the behavior before toolstack.target

CA-401404: Only check previous active service status

---

ocaml/idl/datamodel.ml
ocaml/xapi/repository.ml
ocaml/xapi/repository.mli
ocaml/xapi/xapi.ml

Adding process logic for `/repository/enabled`. If there is `/enabled` after `/repository` in URI, then to find the current enabled repository. Otherwise, keep the existing process logic.

CP-51391: Implement handling for /repository/enabled

---

ocaml/idl/datamodel.ml
ocaml/idl/datamodel_common.ml
ocaml/idl/schematest.ml
ocaml/tests/record_util/old_record_util.ml
ocaml/tests/test_vdi_allowed_operations.ml
ocaml/xapi-cli-server/record_util.ml
ocaml/xapi/message_forwarding.ml
ocaml/xapi/xapi_vdi.ml
ocaml/xapi/xapi_vdi.mli

When a VDI.pool_migrate starts at a pool member, a connection between the
coordinator and that host remains open for the duration of the migration. This
connection is completely idle. If it's open for 12 hours, stunnel closes the
connection due to inactivity, which cancels the migration.
To avoid this use an internal API that uses short-running connection whenever
possible to avoid interrupting the migration.
Also change nested if-else flow in vdi handling to use Result with let binds, and add missing CDI operations to storage operations.
I've manually verified the fix by changing the stunnel timeout in the coordinator of a pool to 5 seconds and migrating a vdi used by a VM in another host:
```
270c3dc8-27bc-4ef2-982a-a6142f0ffce1
```
And after reverting the patch:
```
Cannot forward …
```

CA-401242: avoid long-running, idle connections on VDI.pool_migrate

---

ocaml/xapi/message_forwarding.ml

When a VDI.pool_migrate starts at a pool member, a connection between the coordinator and that host remains open for the duration of the migration. This connection is completely idle. If the migration lasts for more than 12 hours, stunnel closes the connection due to inactivity, which cancels the migration.
To avoid this use an internal API that uses short-running connection whenever possible to avoid interrupting the migration.
merged cherry-pick of 0149ee5c2433b8995d8b75f28c2037c9da4cba80

CA-401242: avoid long-running, idle connections on VDI.pool_migrate, backport

---

ocaml/libs/xapi-stdext/lib/xapi-stdext-unix/test/test_systemd.t

CI check "Run OCaml tests" on github failed occasionally. The cause is test_systemd timeout. Add sleep 1 between server start and client to fix it.

CA-401498: Fix test_systemd occasional timeout

---

ocaml/xenopsd/scripts/qemu-wrapper
scripts/xapi-nbd.service
scripts/xcp-networkd.service
scripts/xcp-rrdd.service

The new version (5.3.0) jemalloc caused a significant increase of memory usage compared to the version 3.6.0.
Adjust the parameters to fix the memory usage issue.
The modification has two parts, the other PR is in the spec repo.
- dom0mem test:
-- xenopsd-xc
-- qemu
-- xapi (the config is not changed for xapi service)

CA-399396: Adjust the jemalloc parameters for memory performance

---

ocaml/idl/datamodel.ml
ocaml/idl/datamodel_common.ml
ocaml/idl/datamodel_errors.ml
ocaml/idl/datamodel_lifecycle.ml
ocaml/idl/schematest.ml
ocaml/sdk-gen/csharp/gen_csharp_binding.ml
ocaml/tests/common/test_common.ml
ocaml/tests/test_sm_features.ml
ocaml/xapi-consts/api_errors.ml
ocaml/xapi/dbsync_master.ml
ocaml/xapi/dbsync_slave.ml
ocaml/xapi/smint.ml
ocaml/xapi/xapi_globs.ml
ocaml/xapi/xapi_pool.ml
ocaml/xapi/xapi_sm.ml

There are two parts to this PR:
1. only declare a feature as a public sm feature when it is advertised by all SMs in the pool
2. reject a host from joining the pool if it does not have a compatible set of SM features with the current pool
Now I did not create a new class just for SM features as I feel having a decidated class for something that is supposed to be quite a temporary state (as this is only supposed to happen during an upgrade) is an overkill. But I am open to suggestions.

CA-400060: Sm feature intersection

---

ocaml/license/daily_license_check.ml
ocaml/tests/alerts/test_daily_license_check.ml

The license field is not always a valid date, sometimes it contains a special
value to signify there's no expiry date.
(cherry picked from commit 6a66682)

CA-399629: make daily-license-check aware of never

---

ocaml/idl/datamodel_errors.ml
ocaml/tests/test_pool_repository.ml
ocaml/xapi-consts/api_errors.ml
ocaml/xapi/xapi_pool.ml

1. `remote_pool` repo doesn't support periodic sync updates.
2. Periodic sync updates should be auto-disabled when calling `set_repositories` and `add_repository` for `remote_pool` repo.
4. Update UT.

CP-51988: Fix functions not work for remote_pool repo

---

ocaml/xapi/xapi_host.ml

Now we got winbind as the Active Direcotry backend, the joined netbios name is persisted in smb.conf, thus can be compatible with hostname change
This commit just remove the set_hostname_live limitation

CA-401274: Remove external auth limitation during set_hostname_live

---

ocaml/libs/tracing/tracing.ml
ocaml/libs/tracing/tracing.mli
ocaml/tests/test_observer.ml
ocaml/xapi/context.ml
ocaml/xapi/context.mli
ocaml/xapi/taskHelper.ml
ocaml/xenopsd/lib/xenops_server.ml

Reraise with the original stacktrace, this requires using the raw backtrace instead of the string one.
I had this change sitting in a branch since around Apr 25 2024, although the branch itself might need more testing, this is a simple fix that we should probably get in sooner.

CP-49134: tracing: do not destroy stacktrace

---

dune-project
ocaml/xcp-rrdd/lib/transport/base/rrd_protocol_v1.ml
vhd-format-lwt.opam
vhd-format.opam
vhd-format.opam.template

Sync the metadata with upstream, which is not updated
This fixes the CI issue due to cstruct version in xs-opam being incompatible with the one requested by the opam metadata in this repository

opam: update vhd packages' opam metadata

---

ocaml/database/db_cache_types.ml
ocaml/database/schema.ml
ocaml/database/test_schemas.ml
ocaml/idl/datamodel_lifecycle.ml
ocaml/idl/datamodel_schema.ml
ocaml/idl/ocaml_backend/gen_api.ml
ocaml/idl/ocaml_backend/gen_db_actions.ml

Flame graphs indicate that, under load created by parallel "xe vm-list" commands, the DB action get_record is hit often. This function constructs an API-level record by marshalling an association list that maps field names to unmarshalled string values. To do this, it serially queries all the field names using `List.assoc`. This has rather large cost in doing lexicographical string comparisons (`caml_compare` on string keys).
To avoid this, regardless of record size, we preprocess the association lists `__regular_fields` and `__set_refs` into a (string, string) Hashtbl.t and query that to construct each record field.
---
This benefit of this change is most notable for large records (such as `VM` and `pool`). The cost of the previously generated code, which does a bunch of serial …

CP-49078: Preprocess fields into a Hashtbl within get_record

---

ocaml/tests/common/mock_rpc.ml
ocaml/xapi/helpers.ml
ocaml/xapi/xapi_globs.ml

XenCenter uses JSONRPC, and our SDK also prefers it.
Benchmarks have also shown that the OCaml implementation of xmlrpc is slower than jsonrpc.
In order of decreasing speed: CSexp > JsonRPC > Sexplib > XmlRPC
```
╭─────────────────────────┬───────────────────────────┬───────────────────────────┬───────────────────────────╮
│name                     │  major-allocated          │  minor-allocated          │  monotonic-clock          │
├─────────────────────────┼───────────────────────────┼───────────────────────────┼───────────────────────────┤
│  rpc/of_string/csexp    │          4190.9180 mjw/run│         10283.3264 mnw/run│          29749.2737 ns/run│
│  rpc/of_string/jsonrpc  │         16674.5459 mjw/run│          4635.7389 mnw/run│         170947.3848 ns/run│
│  rpc/of_string/sexplib …
```

CP-51693: introduce feature flag to use JSONRPC for internal pool communication

---

ocaml/tests/test_event.ml
ocaml/xapi/xapi_periodic_scheduler.ml

When XAPI's queue is empty the periodic scheduler would sleep for 10s, during which time newly added jobs would get ignored.
This is mostly noticeable during unit tests, but we cannot rely on the queue not being empty in production either.
It is better to wake up the scheduler on the soonest of these 2 events:
* after 10s
* when a new task gets added to the queue

CP-51690: fix timeouts shorter than 10s in the periodic scheduler

---

ocaml/xapi/xapi_pool.ml

Previously the SM feature check was done in two parts, fetch all the SM ref from the coordinator, and then fetch their information such as types and features from the coordinator basedon the refs. This can cause race conditions, where the previously fetched refs might have been deleted when we fetch the SM features. The deletion might happen due to the way SM registeration works for shared SRs such as GFS2, where each `PBD.plug` will trigger a deregister of existing SM and re-register (which will delete existing SMs), and create another (very likely) identical SM.
To avoid this race, instead of fetch SM refs and their features separately, do this in one go so we get a consistent snapshot of the db state.

CA-402326: Fetch SM records from the pool in one go to avoid race

---

ocaml/idl/datamodel.ml

Describe EVENTS_LOST in Event.next.
Remove EVENTS_LOST and SESSION_NOT_REGISTERED from Event.from: these are only raised by Event.next.
Document the actual errors that Event.from can raise.
As requested in https://github.com/xapi-project/xen-api/pull/6125#issuecomment-2485358344, based on https://github.com/xapi-project/xen-api/pull/6125#issuecomment-2485178648

CP-52707: Improve Event.from/next API documentation

---

ocaml/xapi/xapi_sr_operations.ml

Otherwise the allowed_operations field in SRs can contain newly added operations, which can break cross-pool migrations when using `xe`. This regression was introduced by e40b3fc95601abd99d16e2c405c1878467f446f7
Partially reverts 723a4983ab1555b24222b417350cddebbf6dc1f5
I've manually tested the migration from a host with xapi 24.36.0 to a host with xapi 24.37.0.23.g2e1274d56 ([this patch](https://github.com/xapi-project/xen-api/commit/2e1274d567b38a4adbc0edae85bb6be2bf0d046d) on top of master)
```
Performing a storage live migration. Your VM's VDIs will be migrated with the VM.
Will migrate to remote host: xseu-41-03, using remote network: Pool-wide network associated with eth0. Here is the VDI mapping:
VDI 9bffe7a3-410e-4e65-82f1-1db6794c18c2 -> SR 17df852a-9463-a591-6196-5f4af08bc888 …
```

CA-402263, xapi_sr_operatrions: don't include all API storage operations in all_ops

---

ocaml/xapi-storage-script/lib.ml
ocaml/xapi-storage-script/lib.mli
ocaml/xapi-storage-script/main.ml
ocaml/xapi-storage-script/test_lib.ml

Testing on a box shows that the new unique arguments for 'domain' work, but opening as a draft PR, because this needs wider testing in XenRT.

CA-388210: use unique datapaths for concurrent VDI copies

---

ocaml/tests/bench/bench_throttle2.ml
ocaml/tests/bench/dune
ocaml/xapi-cli-server/cli_operations.ml
ocaml/xapi-cli-server/cli_util.ml
ocaml/xapi-consts/constants.ml
ocaml/xapi-types/event_types.ml
ocaml/xapi/taskHelper.mli
ocaml/xapi/xapi_globs.ml

Event.next can lose events, and we try to encourage our API users to always use Event.from instead.
My understanding (which could be wrong) is that Event.from will give you the events since a given point in time (token), whereas Event.next only gives you even from when you called the API (missing events between API calls).
This PR introduces a feature flag that we can use to switch the interal users of Event.next to Event.from.
Doing so I've discovered a bug in ocaml-rpc, where `int32_of_rpc` doesn't accept Int32 as input, just Int.
There is a workaround here for now, but I intend to fix this upstream instead, hence the draft PR.

CP-51692: use Event.from instead of Event.next

---

ocaml/libs/http-lib/dune
ocaml/libs/http-lib/http.ml
ocaml/libs/http-lib/http.mli
ocaml/libs/http-lib/http_svr.ml
ocaml/libs/http-lib/xmlrpc_client.ml
ocaml/libs/http-lib/xmlrpc_client.mli
ocaml/libs/tracing/dune
ocaml/libs/tracing/propagator.ml
ocaml/libs/tracing/propagator.mli
ocaml/libs/tracing/tracing.ml
ocaml/libs/tracing/tracing.mli
ocaml/libs/tracing/tracing_export.ml
ocaml/xapi-cli-server/dune
ocaml/xapi-cli-server/xapi_cli.ml
ocaml/xapi/api_server.ml
ocaml/xapi/context.ml
ocaml/xapi/dune
ocaml/xapi/helpers.ml
ocaml/xapi/message_forwarding.ml
ocaml/xapi/server_helpers.ml
ocaml/xapi/system_domains.ml
ocaml/xapi/xapi_pool.ml
ocaml/xe-cli/newcli.ml

Removes dependency on `tracing` from `http-lib` and add baggage.
---
The introduction of it as a dependency was to support this style of code:
```ocaml
let@ req = Http.Request.with_tracing ~name req in
```
However, HTTP headers are just a carrier in the context of tracing. The library ought to be as inert as possible; providing enough to endow requests with tracing information, but not calling into the tracing library to export child spans (as is done above).
To this end, the notion of a [propagator](https://opentelemetry.io/docs/specs/otel/context/api-propagators/) is introduced that provides an interface for doing the above, but generalised to arbitrary carriers. If you can describe how to inject/extract a "trace context" into/from a carrier, you can conceivably propagate tracing across …

Remove tracing dependency from http-lib and add baggage

---

.github/workflows/generate-and-build-sdks.yml
.github/workflows/go-ci/action.yml
ocaml/sdk-gen/csharp/autogen/XenServerTest/DateTimeTests.cs
ocaml/sdk-gen/csharp/autogen/XenServerTest/XenServerTest.csproj
ocaml/sdk-gen/csharp/autogen/src/Converters.cs
ocaml/sdk-gen/go/autogen/src/convert_test.go
ocaml/sdk-gen/go/autogen/src/export_test.go
ocaml/sdk-gen/java/autogen/xen-api/pom.xml
ocaml/sdk-gen/java/autogen/xen-api/src/main/java/com/xensource/xenapi/CustomDateDeserializer.java
ocaml/sdk-gen/java/autogen/xen-api/src/test/java/CustomDateDeserializerTest.java

I didn't update C because it was out of scope for the CP. Also, we're likely to change it soon enough when moving to JSON-RPC so I saw little use in investing that time.
Note that the Java tests don't need an explicit step in the GitHub action since `surefire` plugin runs it at compile time.
I added the Go tests under `go/src` and not `component-test/` because they're unit tests, and don't _really_ belong in that series of test.

CP-51694: Add date deserialization unit tests for C#/Java/Go

---

ocaml/xcp-rrdd/bin/rrdp-netdev/rrdp_netdev.ml
ocaml/xenopsd/xc/xenops_helpers.ml

Bake in assumptions that have been constant ever since xenstore was created: getdomainpath always returns "/local/domain/domid", /local/domain/domid/vm returns "/vm/uuid", so there's no need to look up that path to get the uuid again
This reduces the number of xenstore accesses from 3 to 1 with no functional change.
As suggested in: https://github.com/xapi-project/xen-api/pull/6068#pullrequestreview-2446644349

Minimize xenstore accesses during domid-to-uuid lookups

---

ocaml/xapi-storage-script/lib.ml
ocaml/xapi-storage-script/lib.mli
ocaml/xapi-storage-script/main.ml
ocaml/xapi-storage-script/test_lib.ml

See https://github.com/xapi-project/xen-api/pull/6140 on feature/perf, this is the equivalent PR for master.

CA-388210: enable SMAPIv3 concurrent operations by default

---

ocaml/libs/xapi-stdext/lib/xapi-stdext-threads/dune
ocaml/libs/xapi-stdext/lib/xapi-stdext-threads/threadext_test.ml

Test was pretty minimal.
Add test for result from "wait" function.
Check that "signal" calls are collapsed as stated. Check using multiple threads.
Check timeout not calling "signal".
Old "test_wait" test done by "no_signal".

Improve Delay test

---

ocaml/xapi/xapi_message.ml

`get_since_for_events` checks if the cache contains entries older than the 'since' timepoint requested. If so, this means the cache contains all entries strictly after (`>`) 'since'. If not, this means the cache needs to be reconstructed, since some entries strictly after (`>`) 'since' might be just out of cache.
Previous code would reconstruct the cache when the oldest entry in the cache was equal to the 'since' timepoint requested, which is incorrect and caused a deluge of "x is older than x itself" in the logs.
So, change the check for 'entries older than the since timestamp' to be less-or-equal (as the opposite of 'strictly after'), and clarify the debug message.

xapi_message: Fix incorrect slow path invocation (and its logs)

---

ocaml/xapi-storage-script/main.ml

It is believed that the deadlocks in SMAPIv3 were caused by VDI.copy operations that attach the same disk RO multiple times in Dom0.
With the previous commits we now use a unique identifier and spawn a separate qemu-dp process in the SMAPIv3 plugins, which should prevent the deadlocks and IO errors due to lack of refcounting.
We have also identified the source of deadlocks in xapi-storage-plugins, as a missing _qmp_disconnect, so it should now be safe to enable this by default.

CA-388210: SMAPIv3 concurrency: turn on concurrent operations by default

---

ocaml/libs/stunnel/stunnel_cache.ml
ocaml/libs/stunnel/stunnel_cache.mli
ocaml/xapi/xapi.ml
ocaml/xapi/xapi_globs.ml
ocaml/xapi/xapi_periodic_scheduler_init.ml

The GC timers in the stunnel cache were ineffective because we hardly ever run this GC code, and also because the maximums were very large (70+).

CA-401650: reduce open connections between pool members and the coordinator

---

ocaml/xapi-consts/api_messages.ml
ocaml/xapi/dbsync_slave.ml
ocaml/xapi/xapi_host.ml
ocaml/xapi/xapi_host.mli
ocaml/xapi/xapi_periodic_scheduler_init.ml
ocaml/xenopsd/xc/domain.ml
quality-gate.sh

Issue an alert about a broken host kernel if bits 4, 5, 7, 9, or 14 are set in
`/proc/sys/kernel/tainted`, indicating some kind of error was encountered and the
future behaviour of the kernel might not be predictable or safe anymore (though
it generally should reasonably recover).
Only one alert per tainted bit per boot should be issued.
Distinguish between Major (4,5,7 - these are all things that might cause a
host crash, but are unlikely to corrupt whatever data has been written out) and
Warning (9, 14 - might be a concern and could be raised to Support but usually
are not severe enough to crash the host) levels of errors as
suggested by the Foundations team.
This should serve as an indicator during issue investigation to look for the
cause of the taint.

CP-52524: Generate an alert when various host kernel taints are set

---

ocaml/xapi/xapi_sr.ml

This is to reduce the chance of race between `SR.scan` and `VDI.db_introduce`. More details in the comment, but this won't fix the problem, but just makes it less likely to happen...
I have seen a few instances of this happening now in SXM tests, so need to prioritise fixing this
Trying to run some tests on this, but it's hard to know effective this is as storage migration tends to require lots of resources, and does not get run very often. Plus this issue is not very reproducible.

CA-399757: Add CAS style check for SR scan

---

ocaml/libs/xapi-stdext/lib/xapi-stdext-threads/dune

mtime.clock is not yet available on the xs-opam available when building xenserver

xapi-stdext-threads: use mtime.clock.os

---

ocaml/xenopsd/scripts/qemu-wrapper

This is a single line change to move qemu to the proper cgroup.
Qemu moves itself to the root cgroup, which makes it a sibling of control.slice. All toolstack processes are in control.slice, and even though control.slice gets 10x share of CPU, if we have 1000 qemu processes there is still a big imbalance (toolstack gets 10/1010 share of the CPU)
Qemu-wrapper already has the ability to move the process to another cgroup, so use it. tapdisk and qemu-datapath are already in vm.slice, so move qemu-dm there too.
Checked that qemu ends up in the correct slice:
```
cat /proc/$(pgrep qemu-dm\*|head -n1)/cgroup
8:memory:/vm.slice
7:blkio:/vm.slice
6:net_cls,net_prio:/
5:freezer:/
4:cpu,cpuacct:/vm.slice
3:cpuset:/
2:devices:/
1:name=systemd:/vm.slice/qemu-datapath@199.service
```
Tested with a …

CA-388564: move qemu-dm to vm.slice

---

ocaml/libs/http-lib/http_client.ml

Recent changes to Http_client were made to log errors and backtraces in case of unusual errors, in order to better diagnose problems. Unfortunately, this also led to benign exceptions being logged, which caused people to suspect problems where the exception was actually "expected". In particular the following error started appearing in the logs many times:
Raised Http_client.Parse_error("Expected initial header []")
The case here is that the client has sent an HTTP request, but the server disconnects before sending a response.
It turns out that this happens commonly when an external connection is received by xapi and handed over to another process, such as xcp-rrdd. The connection's file descriptor is passed to the other process, and the original HTTP request is forwarded over a local …

CA-401075: remove misleading logs from HTTP client

---

ocaml/xapi-consts/api_messages.ml
ocaml/xapi/xapi_clustering.ml

Previously a `CLUSTER_STACK_OUT_OF_DATE` is rasied when the user is running corosync 2 as the cluster stack, while corosync3  is available on the system. This is to nag people to upgrade their cluster stack to corosync 3, on XS 9.
As per the new design, we are no longer telling user that their cluster stack version is out of date, since the corosync upgrade will be part of the compulsory actions enforced by XC upgrade wizard and the host installer.

CP-52807: No more cluster stack alert

---

ocaml/xapi/repository.ml
ocaml/xapi/repository.mli
ocaml/xapi/xapi_pool.ml

The new version of yum-utils introduced to xenserver enhances the --download-metadata functionality to align with **dnf reposync** (refer to: https://dnf-plugins-core.readthedocs.io/en/latest/reposync.html) by fully downloading repository metadata. 
Consequently, _create_pool_repository_ is no longer required. 
The PR introduces a check to verify whether the **repodata** already exists before proceeding to create repository metadata.

CP-51429 Avoid redundant processing when full metadata already exists during sync_updates

---

ocaml/xapi/xapi_vbd_helpers.ml

Default empty `allowed_operations` on a cloned VBD means that XenCenter does not display the DVD option in the console tab for VMs cloned from templates, for example.
Follow the practice in `xapi_vbd`, and `update_allowed_operations` immediately after `Db.VBD.create`.
---
I've tested this fix and XC displays the ISO selection on the cloned VM now, and allowed operations on the cloned VBDs are correct as well.

CA-394851: Update allowed operations on the cloned VBD

---

ocaml/libs/xapi-stdext/lib/xapi-stdext-threads/delay_stubs.c
ocaml/libs/xapi-stdext/lib/xapi-stdext-threads/dune
ocaml/libs/xapi-stdext/lib/xapi-stdext-threads/threadext.ml
ocaml/libs/xapi-stdext/lib/xapi-stdext-threads/threadext.mli

Old implementation had different issues.
Just use mutexes and conditions using C stubs.
Current Ocaml Condition module does not have support for timeout waiting for conditions, so use C stubs.
This implementation does not require opening a pipe. This reduces the possibilities of errors calling "wait" to zero. Mostly of the times it does not require kernel calls.

Rewrite Delay module

---

scripts/xapi-wait-init-complete.service

When a host starts, the systemd service xapi-wait-init-complete waiting on the creation of the xapi init cookie file may fail on timeout for a matter of seconds. This patch adds 1 minute (300 seconds total) to the timeout passed to the script xapi-wait-init-complete.

Increase wait-init-complete timeout

---

ocaml/libs/xapi-stdext/lib/xapi-stdext-threads/threadext_test.ml

In some environments the time ranges checked are too strict causing test to fail.
Previously the maximum error accepted was 10 ms, increase to 50 ms.
Also increase timeouts to reduce error/value ratio.

Delay: wait a bit more testing the module

---

ocaml/xapi/xapi_globs.ml

…
This reverts commit af7b9c441158e6f4d5cbaf8da5e1879f0cbe51fd.
We found that the lower limits are too low for large pools and reverting this. We understand that this risks running out of file descriptors, which was the motivation to lower the limits and to introduce rate limits. The problem does not exist in XS8 and we hope to manage this problem until the end of support of this release.

Revert "XSI-1706/CP-51295: limit open TCP con's to 250 and increase socket backlog"

---

ocaml/xe-cli/bash-completion

**xe-cli completion: Use grep -E instead of egrep**
Otherwise newer packages in XS9 issue
"egrep: warning: egrep is obsolescent; using grep -E"
warnings all over the place
---
**xe-cli completion: Hide COMPREPLY manipulation behind functions**
Though the majority of completions were already using set_completions and the
like to add completion suggestions, there were two leftovers still needlessly
changing COMPREPLY themselves. This caused bugs, as in the case of
`xe vm-import filename=<TAB>`
autocompleting all of the filenames into the prompt instead of presenting
the choice. Let only these functions operate on COMPREPLY directly.

xe-cli completion bugfixes

---

ocaml/xapi/xapi_sr.ml

Some plugins may not store the client-set metadata, and return a static value
when replying to the update. This would override the values that a client
used when the SR was created, or set afterwards, which is unexpected.
Now name_label and name_description fields returned by the plugins are ignored
on update.
Current set_name_label and set_name_description rely on the update mechanism to
work. Instead, add database call at the end of the methods to ensure both xapi
and the SR backend are synchronized, even when the latter fails to update the
values.
Tested on GFS2 tests (JR 4175192), as well as ring3 bvt + bst (209177), and storage validation tests (SR 209180)

CA-390025: do not override SR's client-set metadata on update 

---

ocaml/xapi/storage_impl.ml

When add leaked datapath:
1. add leaked datapath to Sr.vdis
2. write to db file
3. log enhance
If there are storage exceptions raised when destroying datapath, the procedure fails and the state of VDI becomes incorrect, which leads to various abnormalresults in subsequent operations. To handle this, the leaked datapath is designed to redestroy the datapath and refresh the state before next storage operation via function remove_datapaths_andthen_nolock. But this mechanism doesn't take effect in current code.
This commit is to fix this bug. leaked datapath should be added to Sr.vdis to make the leaked datapath really work. And write to db file to avoid losing the leaked datapath if xapi restarts.

CA-402901: Update leaked dp to Sr

---

ocaml/libs/xapi-stdext/lib/xapi-stdext-threads/dune
ocaml/libs/xapi-stdext/lib/xapi-stdext-threads/scheduler.ml
ocaml/libs/xapi-stdext/lib/xapi-stdext-threads/scheduler.mli
ocaml/libs/xapi-stdext/lib/xapi-stdext-threads/scheduler_test.ml

There was some issue in the current code, from structure corruption to thread safety.
Add some test and fix discovered issues.
More details on commit messages.

Test and improve Xapi periodic scheduler

---

ocaml/xapi/xapi_sr.ml

For the scan retry, previously we were comparing the entire vdi data structure from the database using the (<>) operator. This is a bit wasteful and not very stable. Instead let us just compare the vdi refs, since the race here comes from `VDI.db_{introduce,forget}`, which would only add/remove vdis from the db, but not change its actual data structure.
Also add a bit more logging when retrying, since this should not happen very often.

Improve the scan comparison logic

---

ocaml/libs/xapi-stdext/lib/xapi-stdext-threads/dune
ocaml/libs/xapi-stdext/lib/xapi-stdext-threads/scheduler.ml
ocaml/libs/xapi-stdext/lib/xapi-stdext-threads/scheduler.mli
ocaml/libs/xapi-stdext/lib/xapi-stdext-threads/scheduler_test.ml
ocaml/xapi/storage_smapiv1_wrapper.ml
ocaml/xapi/xapi_sr.ml

Can't solve the conflicts on feature/perf due to branch restrictions, have to open PR from another branch.

Update feature/perf again

---

ocaml/libs/xapi-stdext/lib/xapi-stdext-threads/dune
ocaml/libs/xapi-stdext/lib/xapi-stdext-threads/ipq.ml
ocaml/libs/xapi-stdext/lib/xapi-stdext-threads/ipq.mli
ocaml/libs/xapi-stdext/lib/xapi-stdext-threads/ipq_test.ml
ocaml/libs/xapi-stdext/lib/xapi-stdext-threads/scheduler.ml
ocaml/libs/xapi-stdext/lib/xapi-stdext-threads/scheduler.mli
ocaml/xapi/xapi_event.ml

Target: feature/perf
Note that this conflicts with https://github.com/xapi-project/xen-api/pull/6155/commits/7e9310f110df2613229bbb236334aad706209a31?diff=unified&w=1, but is a pre-requisite of https://github.com/xapi-project/xen-api/pull/6126

CP-52821: use Mtime in Xapi_periodic_scheduler

---

ocaml/xenopsd/lib/xenops_server.ml

QEMU orders devices by the time of plugging. Parallelizing them introduces randomness, which breaks the assumption that devices are ordered in a deterministic way.
Serialize all PCI and VUSB plugs to restore behaviour.
This fix has been manually tested by @freddy77 against an affected VM relying on the ordering

CA-403633: Keep vPCI devices in the same order

---

dune-project
ocaml/xapi-aux/dune
ocaml/xapi-aux/throttle.ml
ocaml/xapi-aux/throttle.mli
ocaml/xapi/xapi_event.ml
ocaml/xapi/xapi_globs.ml
xapi.opam

We generate O(N^2) events when we update O(N) fields: each field update generates an event including the entire object, even if later we are going to change other fields of the same object.
Instead of returning the individual field update events immediately (and generating a storm of events whenever an API client watcher for VM power events), we batch these event updates by introducing a minimum amount of time that successive Event.from need to have between them.
(The client is working as expected here: when it gets an event and processes it, it immediately calls Event.from to get more events)
Although this doesn't guarantee to eliminate the O(N^2) problem, in practice it reduces the overhead significantly.
There is one case where we do want almost immediately notification of updates: …

CP-52526: rate limit event updates

---

ocaml/xapi/cpuid_helpers.ml
ocaml/xapi/cpuid_helpers.mli
ocaml/xapi/export.ml
ocaml/xapi/import.ml
ocaml/xapi/importexport.ml
ocaml/xapi/message_forwarding.ml
ocaml/xapi/xapi_dr.ml
ocaml/xapi/xapi_vm.ml
ocaml/xapi/xapi_vm_helpers.ml
ocaml/xapi/xapi_vm_migrate.ml

Rebased the work from 2023 merged in #5111 and #5132, that caused issues and was partially fixed in #5148, but was completely reverted in #5147. I've integrated the fix from #5148 and additionally the fix suggested by @minglumlu in CA-380715 that was not merged at the time due to time constraints.
This series passed the tests that were originally failing: sxm-unres (Job ID 4177739), vGPUSXMM60CrossPool (4177750), and also passed the Ring3 BST+BVT (209341). I can run more migration tests if needed - I've heard @Vincent-lau has requested for these to be separated into its own suite instead of being only in Core and Distribution regression tests.

CA-380580: cross-pool migration - no CPU checks for halted VMs, move CPU check to the target host

---

ocaml/idl/datamodel_errors.ml
ocaml/idl/datamodel_pool.ml
ocaml/idl/datamodel_repository.ml
ocaml/xapi-cli-server/cli_frontend.ml
ocaml/xapi-cli-server/cli_operations.ml
ocaml/xapi-consts/api_errors.ml
ocaml/xapi/helpers.ml
ocaml/xapi/pool_periodic_update_sync.ml
ocaml/xapi/repository.ml
ocaml/xapi/repository.mli
ocaml/xapi/repository_helpers.ml
ocaml/xapi/xapi_pool.ml
ocaml/xapi/xapi_pool.mli
python3/dnf_plugins/ptoken.py
python3/dnf_plugins/xapitoken.py
python3/tests/test_dnf_plugins.py
scripts/Makefile
scripts/yum-plugins/accesstoken.py
scripts/yum-plugins/ptoken.py
scripts/yum-plugins/xapitoken.conf
scripts/yum-plugins/xapitoken.py

CP-50787 CP-51347: Support pool.sync_updates from remote_pool repo
When a remote_pool type repository, which points to the enabled
repository in the remote pool coordinator, is set as the enabled
repository of the pool, updates can be synced from it with API
pool.sync_updates.
The username password of the remote pool coordinator is required as
parameters for pool.sync_updates to login the remote pool.
And the remote pool coordinator's host server certificate needs to be
configured in the remote_pool repository, it will be used to verify the
remote end when sending out username passwords.
A new yum/dnf plugin "xapitoken" is introduced to set xapi token as HTTP
cookie: "session_id" for each HTTP request which downloads files from the
remote_pool repository.
CP-52245: Temp disable …

Support pool.sync_updates from remote_pool repo

---

ocaml/libs/stunnel/stunnel.ml

It is expected to use root CA certficate to verify an appliance's server
certificate for a xapi outgoing TLS connection.
Prior to this change, the related stunnel configurations are:
"verifyPeer=yes", and "checkHost=<hostname>".
The 'verifyPeer' option of stunnel doesn't treat the CA bundle as root
CA certificates. The 'checkHost' option of stunnel only checks the
host name against the one in server certificate. In other words, the
issue is that the root CA based checking doesn't work for appliance.
This change adds 'verifyChain' for the appliance to ensure the outgoing
TLS connection from xapi will verify the appliance's server certificates
by real root CA certificate.

CA-403767: verifyPeer can't use root CA for appliance cert check

---

ocaml/database/db_cache_impl.ml
ocaml/database/db_interface.ml
ocaml/database/db_rpc_client_v1.ml
ocaml/database/db_rpc_client_v2.ml
ocaml/database/db_rpc_common_v1.ml
ocaml/database/db_rpc_common_v2.ml
ocaml/idl/ocaml_backend/gen_db_actions.ml
ocaml/xapi/import.ml

Best reviewed by commit - the first one does not depend on database changes, only the last one does.
In short, simplifies and clarifies migration logs from this:
```
[error|1141 |VM metadata import |import]
Found no VDI with location = dedeeb44-62b3-460e-b55c-6de45ba10cc0:
treating as fatal and abandoning import
[debug|1141 |VM metadata import |import]
Ignoring missing disk Ref:4 -
this will be mirrored during a real live migration.
```
to this:
```
[ warn|VM metadata import |import]
Ignoring missing disk Ref:16 -
this will be mirrored during a real live migration.
(Suppressed error: 'Found no VDI with location = c208b47c-cf87-495f-bd3c-a4bc8167ef83')
```
And from this:
```
[error|backtrace] SR.get_by_uuid D:8651cc0c9fb6 failed with exception Db_exn.Read_missing_uuid("SR", "", …
```

IH-747 - Reduce pollution in migration logs

---

ocaml/idl/datamodel.ml
ocaml/idl/ocaml_backend/gen_db_actions.ml
ocaml/xapi/eventgen.ml
ocaml/xapi/eventgen.mli
ocaml/xapi/xapi_event.ml
quality-gate.sh

This is a small effort to simplify the code within the `Eventgen` module. The previous style is very unwieldy and makes the file appear more complicated on the surface than it really is.
---
Passes BVT+BST (209475) but would appreciate review comments as I've dropped the potential for stdout logging in some places (easy to add back) and added commentary that may not be fully accurate.

Simplify Eventgen

---

ocaml/xenopsd/xc/service.ml

We have seen swtpm systemd service files not being removed. We now make Fe_systemctl.stop callable when the servive is potentially not running to ensure clean up is happening regardless.

XSI-1773 clean up swtpm service files

---

ocaml/xapi/repository.ml

This reverts commit c710e8fe13ce9ef55eb53e53cedc5440463aa98f.

Revert "CP-52245: Temp disable repo_gpgcheck when syncing from remote_pool repo"

---

ocaml/xenopsd/lib/xenops_server.ml

Historically parallel operations were run in tasks as part of serial
operations, and serial tasks were not run as part of parallel ones. This
changed recently, causing some timeouts that did not happen before. To
mitigate this issue, now the timeouts for tasks are 20 minutes per single
serialized operation, instead of 20 minutes per task.
Passed one of the VDI / VM scalibility tests that previously failed reliably: Job 4182581

CA-403422: lengthen the timeout for xenopsd's serialized tasks

---

ocaml/database/master_connection.ml

The xapi on a supporter host would restart when it received HTTP error
from the xapi on the coordinator host.
This breaks the pool.designate_new_master use case for a big pool, e.g.
64-host pool. In this case, some supporters may restart unexpectedly
within the phase of committing new coordinator due to the logic above.
Additionally, the purpose of this logic, explained by the error message,
is not correct also. Not all HTTP errors are caused by "our master
address is wrong".
On the other hand, if a use case requires to restart the xapi, an more
explicit logic should ensure that, instead of leveraging an implicit
HTTP error code. Furhtermore, if a supporter indeed is connecting to a
wrong coordinator, this should be a bug and can be recovered manually.
Based on above arguments, the …

CA-404062: Wrongly restart xapi when receiving HTTP errors

---

ocaml/xenopsd/xc/domain.ml

Minor style.
`uuid` is always converted to string, avoid doing it every time it's used.

xenopsd: Avoid calling to_string every time

---

ocaml/libs/xapi-rrd/lib/rrd.ml
ocaml/libs/xapi-rrd/lib/rrd_utils.ml
ocaml/xcp-rrdd/bin/rrdd/rrdd_monitor.ml
ocaml/xcp-rrdd/bin/rrdd/rrdd_server.ml
ocaml/xcp-rrdd/bin/rrdd/rrdd_shared.ml

The latest changes in the metrics daemon changes how archived and live metrics
are synchronised, and archived sources are created less often. This meant that
on some cases, like SR.forget, the operations failed because they could query
for existing sources, but the call to remove them failed, because the metrics
only exist in live form, not archived one.
(what happens with the live one, do they disappear when the SR is forgotten?)
Signed-off-by: Pau Ruiz Safont <pau.ruizsafont@cloud.com>

CA-404020: Do not fail when removing a non-existing datasource

---

ocaml/networkd/lib/network_utils.ml
ocaml/xapi/xapi_globs.ml
ocaml/xapi/xapi_pif.ml

FCoE support will be removed from XS9 and dom0 will no longer provide fcoe_driver. However, XS8 still actively support it.
Xapi checks the existence of fcoe_driver, and thinks all PIFs no longer support FCoE if fcoe_driver not found

CP-51895: Drop FCoE support when fcoe_driver does not exists

---

ocaml/libs/tgroup/dune
ocaml/libs/tgroup/test_tgroup.ml
ocaml/libs/tgroup/tgroup.ml
ocaml/libs/tgroup/tgroup.mli
ocaml/xapi/dune
ocaml/xapi/server_helpers.ml
ocaml/xapi/xapi_session.ml
ocaml/xe-cli/newcli.ml

Adds more granurality in the xapi thread classification. Now, an
individual thread can be mapped to the following:
- {xapi_cgroup}/internal/SM;
- {xapi_cgroup}/internal/cli;
- {xapi_cgroup}/external/intrapool;
- {xapi_cgroup}/external/unauthenticated;
- {xapi_cgroup}/external/authenticated/{identity};
where {identity} is a {auth_user_sid}/{user_agent}.
Both {auth_user_sid} and {user_agent} strings are sanitized when
making the identity through `Identity.make`, by allowing only
alphanumeric characters and a maximum length of 16 characters each.
This should allow for proper thread classification in xapi. 
Note: Threads calling back into xapi from xenopsd are yet to be classified.
e.g. Cgroup hierarchy based on the new classification 
BVT: 208947 & BST: 208972

Xapi thread classification - part 2

---

ocaml/xcp-rrdd/lib/plugin/reporter.ml
ocaml/xcp-rrdd/lib/plugin/reporter_local.ml

Reporter.cancel would be blocked for a long time by backoff delay when another thread is waiting for next reading, replace Thread.delay with Delay module so that Reporter.cancel will not be blocked.

CA-404013: replace Thread.delay with Delay module

---

ocaml/rrd2csv/src/rrd2csv.ml

rrd2csv itself prints out a list of comma-separated metrics names, but could't accept this list as command line arguments:
```
$ rrd2csv
.....memory_total_kib, memory_free_kib, ....
$ rrd2csv memory_total_kib, memory_free_kib
WARNING: Requested metric AVERAGE:host:05e817e2-3a65-484d-b0da-a7163f9ffc12:memory_total_kib,
is disabled or non-existant
timestamp, AVERAGE:host:05e817e2-3a65-484d-b0da-a7163f9ffc12:memory_free_kib
2025-01-07T14:06:45Z, 30042000
```
Now this works just fine:
```
$ rrd2csv memory_total_kib, memory_free_kib
timestamp, AVERAGE:host:92bc3b1e-e0a3-49ba-8994-fc305ff882b7:memory_total_kib, AVERAGE:host:92bc3b1e-e0a3-49ba-8994-fc305ff882b7:memory_free_kib
2025-01-07T15:04:50Z, 33350000, 30023000
```

rrd2csv: Accept a trailing comma in metrics names

---

ocaml/libs/xapi-stdext/lib/xapi-stdext-threads/scheduler.ml

Use Mtime.Span.to_float_ns instead of  Mtime.Span.to_uint64_ns+Int64.to_float

---

ocaml/database/db_xml.ml
ocaml/xcp-rrdd/bin/rrdd/rrdd_server.ml

The point of using try_lock is to not get lock while trying to hold the mutex.
Releasing it and blocking to lock it defeats the purpose of using try_lock.
Reorganise the sequence to read and copy all the rrds first while under the
locked mutex, release it, and then archive the copies.
This doesn't fix CA-404013 directly, so this can wait until the release is cut. I'm opening otherwise I'll forget to open it when things are unlocked.
I've run the smoke and validation tests, as well as checking that the rrd files in the bugtools are well formed for hosts and vms (they are created suing this function)

CA-404013: do not relock the mutex when backing up rrds

---

ocaml/libs/stunnel/stunnel.ml
ocaml/libs/stunnel/stunnel.mli
ocaml/xapi/repository_helpers.ml
ocaml/xapi/xapi_globs.ml

Two changes in the PR:
**Drop the usage of fuser in stunnel client proxy**
The drawback of fuser is that it gets too many things involved. E.g. it
is observed that it got stuck on cifs kernel module.
This change uses a cleaner way to remember the stunnel client proxy.
Even when the xapi restarted unexpectedly, it can stop the remnant
stunnel proxy and start a new one.
**Make the stunnel proxy local port configurable**
Making it configurable can avoid the situation when the port conflicts
with others, e.g. an external program from users.

CA-403620: Drop the usage of fuser in stunnel client proxy

---

ocaml/sdk-gen/csharp/autogen/src/Session.cs
ocaml/sdk-gen/csharp/templates/ApiVersion.mustache
ocaml/sdk-gen/powershell/autogen/src/CommonCmdletFunctions.cs
ocaml/sdk-gen/powershell/autogen/src/Connect-XenServer.cs

Commits best reviewed separately.
- CP-53003: Use JsonRpc v1.0 by default and switch to v2.0 once the API version is known.
- Removal of deprecated methods and unused internal methods.
- Refactoring to fix some inefficiencies when loading and saving certificates in PS.

SDK fixes including CP-53003

---

ocaml/libs/timeslice/dune
ocaml/libs/timeslice/recommended.ml
ocaml/libs/timeslice/recommended.mli
ocaml/libs/timeslice/simple_measure.ml
ocaml/libs/timeslice/simple_measure.mli
ocaml/libs/timeslice/timeslice.ml
ocaml/libs/timeslice/timeslice.mli
ocaml/tests/common/dune
ocaml/tests/common/suite_init.ml
ocaml/xapi-idl/lib/dune
ocaml/xapi-idl/lib/xcp_service.ml

The default OCaml 4.x timeslice for switching between threads is 50ms: if there is more than 1 active OCaml threads each one is let to run up to 50ms, and then (at various safepoints) it can switch to another running thread.
When the runtime lock is released (and C code or syscalls run) then another OCaml thread is immediately let to run if any.
However 50ms is too long, and it inserts large latencies into the handling of API calls. 
OTOH if a timeslice is too short then we waste CPU time:
* overhead of Thread.yield system call, and the cost of switching threads at the OS level
* potentially higher L1/L2 cache misses if we switch on the same CPU between multiple OCaml threads
* potentially losing branch predictor history
* potentially higher L3 cache misses (but on a hypervisor with VMs …

CP-52709: use timeslices shorter than 50ms

---

ocaml/xapi-types/features.ml
ocaml/xapi-types/features.mli
ocaml/xapi/xapi_cluster.ml
ocaml/xapi/xapi_cluster_helpers.ml
ocaml/xapi/xapi_cluster_host.ml
ocaml/xapi/xapi_cluster_host_helpers.ml

The new clustering interface uses a constructor `Extended` address when a cluster hots is trying to join a cluster. This causes problems during upgrades as a newly upgraded host might send out the new address format to old hosts, which do not understand this format, causing the new hosts not able to join.
The fix would be to use the cluster_health feature flag/pool restrictions to gate the use of the new clustering interface. This makes sure that the new interface would only be used if all of the hosts understand this new interface, i.e. have this feature enabled. The cluster_health feature is controlled by v6d and is pool-wide, therefore the new interface would only be enabled if all v6ds are updated to the correct level, which also implies that the accompanying xapi are updated to the …

CA-404512: Add feature flag to the new clustering interface

---

ocaml/xapi/xapi_pool_update.ml
ocaml/xenopsd/xc/xenops_server_xen.ml

Be explicit about the file system of an update ISO. Remove dead code.

CA-403700 use iso9660 file system for updates

---

ocaml/xapi/xapi_event.ml

This fixes a performance regression on `feature/perf` with all feature flags disabled.
By default Event.next is still used internally, so although this API is deprecated do not yet enable the throttling by default. Fixes: 3e1d8a27a7 ("CP-51692: Event.next: use same batching as Event.from") 
Fixes: 2b4e0db649 ("CP-49158: [prep] Event.{from,next}: make delays configurable and prepare for task specific delays")
It slows down all synchronous API calls that create tasks, like VM.start.
Only enable the throttling when Event.next is not used internally (`use-event-next = false` in xapi.conf), which will eventually become the default.
The code prior to the above changes used 0 delay between checking for events, so do the same here (although this lead to a lot of inefficient wakeups of all active …

CP-51692: Do not enable Event.next ratelimiting if Event.next is still used internally

---

ocaml/forkexecd/lib/dune
ocaml/forkexecd/lib/forkhelpers.ml
ocaml/forkexecd/lib/forkhelpers.mli
ocaml/forkexecd/test/dune
ocaml/forkexecd/test/fe_test.ml
ocaml/networkd/bin/dune
ocaml/networkd/bin/networkd.ml
ocaml/networkd/lib/network_utils.ml
ocaml/xapi/helpers.ml
ocaml/xapi/static_vdis.ml
ocaml/xapi/xapi_globs.ml
ocaml/xenopsd/lib/dune
ocaml/xenopsd/lib/xenopsd.ml
ocaml/xenopsd/xc/service.ml

This has two advantages:
1. Always non-negative: they represent absolute differences in time
2. Forces users to define the units of time, allowing to read the time in minutes, when appropriate
Passed the toolstack's smoke and validation tests: Job 209833

CA-364194: use timespans for script timeouts

---

ocaml/forkexecd/lib/fe_systemctl.ml
ocaml/forkexecd/lib/fe_systemctl.mli
ocaml/idl/datamodel_errors.ml
ocaml/idl/datamodel_host.ml
ocaml/idl/datamodel_pool.ml
ocaml/sdk-gen/go/gen_go_helper.ml
ocaml/xapi-cli-server/cli_frontend.ml
ocaml/xapi-cli-server/cli_operations.ml
ocaml/xapi-consts/api_errors.ml
ocaml/xapi/message_forwarding.ml
ocaml/xapi/xapi_host.ml
ocaml/xapi/xapi_host.mli
ocaml/xapi/xapi_pool.ml
ocaml/xapi/xapi_pool.mli
ocaml/xapi/xapi_systemctl.ml
ocaml/xapi/xapi_systemctl.mli

This PR is to add API and CLI which is used to enable and disable SSH on all hosts in a pool or on specified hosts within a pool.

CP-52074: Add API for start/stop systemd service sshd

---

.github/workflows/release.yml

The package dune has been replaced with ocaml-dune
> Package dune is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
ocaml-dune

github: update release for ubuntu 24.04

---

.github/workflows/release.yml

Ubuntu's dune is way too old for the version generally used. On top of that the command doesn't fail when this happens, making the setup brittle. Instead write the version variable to config.mk and run make.
You can see this change running as expected in this run: https://github.com/xapi-project/xen-api/actions/runs/12792091034/job/35661725368

github: remove dependency of python wheel's on dune

---

doc/content/design/coverage/index.md
ocaml/forkexecd/src/child.ml
ocaml/libs/log/debug.ml
ocaml/libs/log/debug.mli
ocaml/libs/xapi-compression/xapi_compression.ml
ocaml/libs/xapi-stdext/lib/xapi-stdext-unix/unixext.ml
ocaml/libs/xapi-stdext/lib/xapi-stdext-unix/unixext.mli
ocaml/nbd/src/cleanup.ml
ocaml/nbd/src/dune
ocaml/networkd/bin/network_server.ml
ocaml/xapi-guard/lib/server_interface.ml
ocaml/xapi/helpers.ml
ocaml/xapi/sm_exec.ml
ocaml/xapi/xapi_extensions.ml
ocaml/xapi/xapi_plugins.ml
ocaml/xcp-rrdd/bin/rrdd/dune
ocaml/xcp-rrdd/bin/rrdd/xcp_rrdd.ml
ocaml/xcp-rrdd/lib/plugin/utils.ml
ocaml/xenopsd/lib/cancellable_subprocess.ml
ocaml/xenopsd/lib/suspend_image.ml
ocaml/xenopsd/lib/xenopsd.ml

The integer values that OCaml uses for signals should never be printed as integers. They can cause confusion because they don't match the C POSIX values.
Change the unixext function that converts them to string to stop building a list and finding a value in the list to instead use pattern-matching. Also added some more values that got introduced in OCaml 4.03, and return a more compact value for unknown signals, following the same format as Fmt.Dump.signal.
Typically, engineers see signal -11 and assume it's SIGSEGV, when it's SIGTERM.
Fixes #6225

Log proper names for POSIX signals

---

ocaml/libs/xapi-rrd/lib/rrd.ml
ocaml/libs/xapi-rrd/lib_test/unit_tests.ml

Some recent changes related to RRDs likely exposed a long-standing latent issue
where the RRD library would process the passed-in values for Gauge and Absolute
data sources incorrectly leading to constant values changing from update to
update, for example:
```
$ rrd2csv memory_total_kib
timestamp, AVERAGE:host:8b533333-91e1-4698-bd17-95b9732ffbb6:memory_total_kib
2025-01-15T08:41:40Z, 33351000
2025-01-15T08:41:45Z, 33350000
2025-01-15T08:41:50Z, 33346000
2025-01-15T08:41:55Z, 33352000
```
Instead of treating Gauge and Absolute data sources as a
variation on the rate-based Derive data source type, expecting time-based
calculations to cancel each other out, do not undertake any calculations on
non-rate data sources at all.
First commit adds a failing unit test, second makes it pass.
=== …

CA-404597 - rrd: Fix incorrect processing of Gauge and Absolute data sources

---

ocaml/libs/xapi-rrd/lib/rrd_utils.ml

`lastupdate` field in the XML RRD blob file, in particular, was getting truncated floats representing the number of seconds, which loses A LOT of precision, meaning RRDs could not be checked to have been produced with the 5-second frequency.

CA-404591 - rrd: Do not lose precision when converting floats to strings

---

ocaml/idl/datamodel_errors.ml
ocaml/tests/test_pool_repository.ml
ocaml/xapi/xapi_pool.ml

When enabling pool's repositories, if enabling bundle repo and remoe_pool
repositories at the same time, it returns error message:
`If the bundle repository or remote_pool repository is enabled, it should be
the only one enabled repository of the pool.
repo_types: bundle`
The `repo_types` is confusing and tedious as only these 2 types of repository
can meet this error. So remove the parameter `repo_types`.

CA-404660: Refine repository enabling error message

---

ocaml/sdk-gen/csharp/FriendlyErrorNames.resx
ocaml/sdk-gen/csharp/autogen/src/Failure.cs

With regard to the error removal, these entries had been added to the SDK to account for specialised error messages needed by XenCenter, which was not the right thing to do; this should have been done on the implementing client side, not the SDK.

CA-403634: Corrected error text. Removed errors that are not issued by the API.

---

ocaml/forkexecd/test/dune
ocaml/forkexecd/test/fe_test.ml
ocaml/forkexecd/test/fe_test.sh
ocaml/forkexecd/test/syslog.c

The syslog feature allows to run a program and redirect its output/error stream to system log. It's triggered passing `syslog_stdout` argument to `Forkhelpers` functions like `execute_command_get_output`.
To test this feature use a small preload library to redirect syslog writing.
This allows to test program without changing it.
The log is redirected to `/tmp/xyz` instead of `/dev/log`. The name was chosen to allow for future static build redirection.
The C program is used only for the test, so the code style take into account this (specifically it does not try to handle all redirect situation and all error paths).

fe_test: add test for syslog feature

---

ocaml/idl/datamodel_errors.ml
ocaml/xapi-consts/api_errors.ml
ocaml/xapi/xapi_host_driver.ml

Introduce a new error and raise it if a host driver variant is selected for hardware that is not present.

CA-404693 prohibit selecting driver variant if h/w not present

---

dune-project
xapi-debug.opam
xapi.opam

These were added for the SMAPIv3-inbound VM migrations

opam: add missing dependencies

---

ocaml/networkd/lib/network_utils.ml
ocaml/xapi/xapi_globs.ml

On all platforms tested the canonical location for dracut is `/usr/bin/dracut`. Older platforms symlink to it from `/usr/sbin/dracut`, whilst newer ones do not, thus on these platforms xapi is unable to find dracut and fails to start.
Adjust the path to the canonical location to ensure it operates correctly on all platforms.
Also adjust a reference in network_utils.ml (whilst newer platforms also seem to have the symlink from `/sbin/dracut`, it would seem to make sense to point to the canonical location regardless).

CA-405404: Fix path to dracut

---

doc/README.md
doc/content/design/cpu-levelling-v2.md
doc/content/design/local-database.md
doc/content/design/multiple-cluster-managers.md
doc/content/design/ocfs2/index.md
doc/content/toolstack/features/DR/index.md
doc/content/toolstack/features/snapshots/index.md
doc/content/xapi/cli/_index.md
doc/content/xapi/guides/howtos/add-class.md
doc/content/xen-api/topics/snapshots.md
doc/content/xenopsd/architecture/_index.md
doc/go.mod

Minor updates of the Hugo documentation:
- The current Ubuntu `snap` package of Hugo is not supported by the docs.
We should take a first minor step towards fixing this.
- [`doc/README.md`](https://github.com/xapi-project/xen-api/blob/master/doc/README.md) is outdated and should be updated ([new version](https://github.com/xenserver-next/xen-api/blob/docs-update-README-and-hugo-relearn-to-5.23/doc/README.md)).
It says that the Ubuntu snap of Hugo works, but it does not anymore.
Fix this by updating the outdated information.
- An initial fix is to update the Relearn theme from 5.20.x to 5.23.0:
- It does not introduce breaking changes.
- It introduces more straightforward page links and deprecates older syntax.
- Fix the warnings by updating relative links accordingly.
A preview is …

docs: Update docs/README.md and Hugo Relearn to 5.23.0

---

doc/content/design/integrated-gpu-passthrough/index.md
doc/content/toolstack/features/VGPU/index.md

For links to internal pages, `{{site.baseurl}}` (without the leading `.`) does not
work in current Hugo, and it is better to replace it by using relative links:
`{{.Site.BaseURL}}` is replaced in the rendered output, but it doesn't work when
viewing and editing the files using Markdown editors and viewers like on GitHub/Lab
as well as IDEs with improved support for Markdown editing(in editor and preview).
As the relative links work in all cases like in the editors and previews,
fix those (currently broken) links to use the relative links instead.
While at those, also replace the link name "here" with a more specific link name.
PS: The only place were `{{.Site.BaseURL}}` or similar is needed is the link in
the `logo.html` template for `img="{{.Site.BaseURL}}/images/xapi-project.png"`

Hugo docs: Fix {{site.baseurl}} links to use relative internal links instead

---

ocaml/xapi/xapi_pool.ml

The call currently calls `network.attach` on all networks, but this fails for PIFs that are not managed by xapi. Simply skip those.

CA-400272: pool.set_igmp_snooping_enabled: ignore non-managed PIFs

---

.github/workflows/main.yml
.github/workflows/other.yml
.github/workflows/shellcheck.yaml

Optional improvement for fast CI completion when only Hugo docs change on push/PRs:
When only Hugo docs change on push and PRs, other workflows can be skipped using
`paths-ignore:` for `docs/**` and `.github/workflows/hugo.yml` to not trigger other
workflows if only these paths change when pushing to a branch / work on a PR.
This is completely optional, but would be nice to have when only working on Hugo docs.
It does not change scheduled CI runs. It changes only on-demand push/PR workflow runs.

CI: When only Hugo docs change, other workflows do not need to run

---

ocaml/xapi/storage_migrate.ml
ocaml/xapi/storage_smapiv1_wrapper.ml
ocaml/xenopsd/lib/xenops_server.ml

There are two parts to this PR:
1. Reverts the VM migration ordering change, which was previously thought to be necessary as I did not see `VM_save` would actually deactivate the source VM datapath. Thanks @edwintorok for pointing that out.
2. Change `post_detach_hook` to `post_deactivate_hook`, as this should have been called as soon as the datapath is deactivated, at which point all r/w using that datapath will be stopped.
More details in the commit message.

Revert VM migration shutdown order change + change post_detach to post_deactivate

---

ocaml/gencert/lib.ml
ocaml/gencert/lib.mli
ocaml/gencert/test_lib.ml

When installing host certificates, the parser used accepts string with random characters surrounding the PEM-encoded data. The ad-hoc parser used to read the host certificate file was unable to parse them.
Because the PEM-encoded objects are copied as-is after validating them, the ad-hoc parser fails to read the file correctly when xapi restarts.
This change fixes the issue by making sure that the written file's data has been sanitized, by using parsed datastructures instead of user-provided data.
Parse, don't validate
I've manually tested the fix on a host, before and after to validate that indeed now all the characters in between the PEM-encoded objects are stripped

CA-405593: Do not write extraneous data into the host certificate file

---

ocaml/xcp-rrdd/bin/rrdp-dcmi/dune
ocaml/xcp-rrdd/bin/rrdp-dcmi/rrdp_dcmi.ml
ocaml/xcp-rrdd/bin/rrdp-iostat/dune
ocaml/xcp-rrdd/bin/rrdp-iostat/rrdp_iostat.ml
ocaml/xcp-rrdd/bin/rrdp-xenpm/dune
ocaml/xcp-rrdd/bin/rrdp-xenpm/rrdp_xenpm.ml
ocaml/xcp-rrdd/lib/plugin/rrdd_plugin.mli
ocaml/xcp-rrdd/lib/plugin/utils.ml
ocaml/xcp-rrdd/lib/plugin/utils.mli

This error made toolstack restarts fail.
Because not all drivers have ipmi available, exit gracefully instead.
Also try to extract the reason from the command's output and log it. This means that now functions that use Utils.exec_cmd now red the stderr of the command as well.
Fixes #6252

CA-399669: Do not exit with error when IPMI readings aren't available

---

ocaml/xapi-storage-script/main.ml

The `bind` function in xapi-storage-script has lots of implementaions all over the place, making it hard to maintain. Use module abstractions to separate different storage functions.
The tricky bit of this is the need to pass `version` and `volume_script_dir` into each storage function calls, and these two variables are determined at runtime. Hence functors are used for this purpose, once the `volume_script_dir` is determined when `bind` is called, pass this as inside the `RuntimeMeta` module to the relevant implementations. The `version` global variable, however, is populated when `Query.query` is called, so create an alias in the `RuntimeMeta` module so that it can be used in the storage function implementations.

Refactor xapi-storage-script to use modules

---

ocaml/xapi/pvs_cache_vdi.ml
ocaml/xapi/xapi_globs.ml

The pvsproxy daemon normally unmounts and removes the locally attached VBD for the cache VDI when needed. We do it as well in `PVS_cache_storage.destroy`, just in case pvsproxy did not manage to, for whatever reason. This should avoid any VDI_IN_USE errors.

CA-405628: unmount/detach PVS cache VDI before destroying

---

ocaml/xenopsd/lib/topology.ml
ocaml/xenopsd/lib/topology.mli
ocaml/xenopsd/test/dune
ocaml/xenopsd/test/test.ml
ocaml/xenopsd/test/test_cpuid.ml
ocaml/xenopsd/test/test_topology.ml
ocaml/xenopsd/xc/domain.ml

Unreachable nodes do not contain any CPUs, and therefore VCPUs cannot be
scheduled on them. They marked with a value of (2ˆ32) - 1. Instead of failing
to produce a NUMA object that allows for scheduling, create an object that
contains only schedulable NUMA nodes. This means changing how the
datastructures node_cpus and candidates are created to ignore the unreachable
ones.
Fixes two minor potential issues (distances being NaN, and adding duplicates to candidates, which adds to running time); and separates the xenopsd unit tests into 3 binaries for ease of testing.
Fixes https://github.com/xapi-project/xen-api/issues/6240

CP-53335, topology: do not raise exception when loading invalid distance matrices (NUMA)

---

doc/content/xen-api/wire-protocol.md
ocaml/vhd-tool/src/tar.md
ocaml/xapi/xapi_vm.ml

doc, comment: Fix all spellings of omitted(from omit) from incorrect: "ommitted"
- Even if it may sound like "mm", English dictionaries and spelling sites say "omitted".

doc, comment: Fix spelling of ommitted (incorrect) to omitted

---

.github/workflows/shellcheck.yaml
doc/content/design/emulated-pci-spec.md
doc/content/design/user-certificates.md
doc/content/squeezed/architecture/index.md
doc/content/squeezed/squeezer.md
doc/content/toolstack/high-level/environment.md
doc/content/toolstack/responsibilities.md
doc/content/xen-api/topics/udhcp.md
doc/content/xen-api/wire-protocol.md
doc/content/xenopsd/design/Tasks.md
doc/content/xenopsd/design/pvs-proxy-ovs.md
doc/content/xenopsd/design/suspend-image-framing-format.md
doc/content/xenopsd/features.md
doc/layouts/partials/content.html

Apply a few trivial spelling fixes here and there for:
- Accidental typos
- Word repetitions
- Uppercase of "Markdown" and "JSON-RPC"

Hugo docs: Fix random typos and simple word repetitions here and there.

---

ocaml/database/db_cache_types.ml
ocaml/database/db_lock.ml

eBPF exitprobes do not work on OCaml functions that are tailcalls. Introduce some noop hooks that are forced to be non-tailcalls, by disabling inlining on them.
This enables `bpftrace` to be able to hook these functions for debugging and performance measurement purposes, and otherwise have negligible runtime impact (just a function call and a return).

CP-51209: hooks for bpftrace

---

ocaml/database/db_lock.ml
ocaml/database/dune

Builds on top of https://github.com/xapi-project/xen-api/pull/6177 and https://github.com/xapi-project/xen-api/pull/6179, the commit new in this PR is CP-49141.

CP-49141: mark the DB lock as high priority

---

ocaml/xapi-storage-script/main.ml

xapi-storage-script maintains a state.db which is loaded on startup every time. This state.db contains currently attached SRs, and this information can be used later on by xapi to decide whether to plug a PBD in.
This information is correctly updated when adding an attached SR in, but not when removing an SR. This will cause problems when an SR is detached, followed by a toolstack restart. As now xapi-storage-script still thinks that SR is attached, but in fact it is not.

CA-405754: Update xapi-storage-script state.db

---

ocaml/tests/bench/bench_cached_reads.ml
ocaml/tests/bench/dune
ocaml/xapi-aux/pool_role.ml

Before (measuring both unloaded, and loaded situation where other threads are accessing the mutex):
```
Running benchmarks (no workloads)
╭────────────────────────────────────┬───────────────────────────┬───────────────────────────┬───────────────────────────╮
│name                                │  major-allocated          │  minor-allocated          │  monotonic-clock          │
├────────────────────────────────────┼───────────────────────────┼───────────────────────────┼───────────────────────────┤
│  Cached reads/Pool_role.is_master  │             0.0000 mjw/run│             4.0000 mnw/run│             23.6039 ns/run│
╰────────────────────────────────────┴───────────────────────────┴───────────────────────────┴───────────────────────────╯
Cached reads/Pool_role.is_master (ns):
{ …
```

Optimize Pool_role fastpath

---

ocaml/xapi/server_helpers.ml

This breaks emergency mode commands.

CA-405971: avoid calling DB functions when in emergency mode

---

doc/hugo.toml

Enable the edit button next to the prev/next buttons in the topbar:
`editURL` enables to editing (using your fork+new PR) on GitHub.com

Hugo docs: Allow for quick doc updates using the edit button

---

doc/content/xenopsd/walkthroughs/VM.start.md

Update:
- No longer add the links to not "official" source repositories for xenguest.
Update and extend the walkthrough of `VM.start`:
- Update the links to `xenopsd` functions from [xapi-project/xenopsd.git](https://github.com/xapi-project/xenopsd) to the current [xenopsd](https://github.com/xapi-project/xen-api/blob/master/ocaml/xenopsd/) code in [xapi-project/xen-api.git](https://github.com/xapi-project/xen-api/blob/master/ocaml/xenopsd/)
- Add the step for storing the platform data (vCPUs, vCPU affinity, etc.) in the domain's Xenstore tree.` xenguest then uses this in the `build` phase to build the domain.
- Convert the paragraphs about `xenguest` into a dedicated chapter on `xenguest`.
- Add a summary of the data that `xenopsd` passes to `xenguest` for the domain build
- Add a …

doc: walkthroughs/VM.start: Update the xenguest chapter (domain build)

---

doc/content/xenopsd/design/_index.md
doc/content/xenopsd/walkthroughs/_index.md

The docs commonly use the children shortcode to list child pages,
we may use it for the xenopsd walk-throughs and designs as well.

docs/xenopsd: List the child pages using the children shortcode

---

README.markdown

The README.markdown contained two references to the disabled xen-api mailman list, see:
https://lists.xenproject.org/mailman/listinfo/xen-api.disabled
- Replace them with the currently used issues and discussions pages on GitHub.
- While at it, mention the DCO as requirement for merging patches.

README: Add DCO, issues & remove the disabled xen-api list

---

ocaml/idl/ocaml_backend/gen_server.ml

Cherry-picked from another branch.

Drop count_mandatory_message_parameters

---

ocaml/message-switch/unix/dune
ocaml/message-switch/unix/protocol_unix.ml
ocaml/message-switch/unix/protocol_unix_scheduler.ml
ocaml/message-switch/unix/protocol_unix_scheduler.mli
quality-gate.sh

There was duplicated and unused code, as well as unnecessarily-nested modules.

Simplify some parts of message-switch/unix

---

doc/content/xenopsd/walkthroughs/VM.build/Domain.build.md
doc/content/xenopsd/walkthroughs/VM.build/VM_build.md
doc/content/xenopsd/walkthroughs/VM.build/_index.md
doc/content/xenopsd/walkthroughs/VM.build/xenguest.md
doc/content/xenopsd/walkthroughs/VM.migrate.md
doc/content/xenopsd/walkthroughs/VM.start.md
doc/content/xenopsd/walkthroughs/_index.md
doc/content/xenopsd/walkthroughs/live-migration.md
doc/hugo.toml

Add walk-throughs for VM_build (split into 3 pages for improved focus):
The existing walk-though for VM_build as been uses as the basis and extended: The parts which are currently in [Chapter 3 of the VM.start workflow](https://xapi-project.github.io/new-docs/xenopsd/walkthroughs/VM.start/index.html#3-build-the-domain) have been extracted, moved to new files and extended.
A special improvement is that the deep nesting of lists is split into separate chapters and flattened, which fixes the deep nesting that I initially used.
The new extracted and improved walk-though contains flowcharts that show the execution flow and a call graph to visualise the content of the walk-through.
This PR has 3 commits, the 2nd commit is the big commit.
The 1st and 3rd commit are very small and only minor …

Hugo docs: Add dedicated walk-throughs for VM.build and xenguest

---

.github/workflows/other.yml

Follow the official recommendation from Coveralls:
> While our API is in maintenance mode, new coverage report uploads (POSTs to /api/v1/jobs) will fail with a 405 or other 4xx error.
> To keep this from breaking your CI builds and holding up your PRs, allow coveralls steps to "fail on error."
> If you are using one of our Official Integrations, add: 
> - `fail-on-error: false` if using Coveralls GitHub Action

fix(CI) Coveralls is down for maintenance: do not fail the CI if coveralls is down

---

python3/Makefile
python3/libexec/metrics.py
python3/libexec/metricsgraph.py
python3/stubs/XenAPI.pyi

Resurrects two previously deleted scripts: `metrics.py` and `metricsgraph.py`.
The first one dumps a human-readable list of all host, VM, VIF, PIF, VBD-related metrics for quick troubleshooting.
`metricsgraph.py` creates a textual representation of the graph below, representing relationships between and basic characteristics/metrics of objects:
These are both installed alongside other Python libexec tools. I haven't altered what the scripts do themselves beyond bringing Python and API usage up to date, if anyone feels like these tools could be changed in some way to better serve their purpose (quick diagnostics for support/potentially part of the bugtool), please let me know.

Resurrect RRD scripts

---

ocaml/database/parse_db_conf.ml
ocaml/idl/datamodel_utils.ml
ocaml/libs/xapi-stdext/lib/xapi-stdext-std/xstringext.ml
ocaml/libs/xapi-stdext/lib/xapi-stdext-std/xstringext.mli
ocaml/libs/xapi-stdext/lib/xapi-stdext-std/xstringext_test.ml
ocaml/mpathalert/mpathalert.ml
ocaml/quicktest/qt.ml
ocaml/rrd2csv/src/rrd2csv.ml
ocaml/xapi/extauth_plugin_ADpbis.ml
ocaml/xapi/fileserver.ml
ocaml/xapi/gpg.ml
ocaml/xapi/import.ml
ocaml/xapi/nm.ml
ocaml/xapi/workload_balancing.ml
ocaml/xapi/xapi_network.ml
ocaml/xapi/xapi_pif.ml
ocaml/xapi/xapi_pool.ml
ocaml/xapi/xapi_pool_update.ml
ocaml/xapi/xapi_secret.ml
ocaml/xapi/xapi_xenops.ml
ocaml/xe-cli/newcli.ml

These functions were introduced in OCaml 4.13.

Replace startswith and endswith with stdlib calls

---

.github/workflows/other.yml

`LizardByte/setup-python-action` was only needed for Python2.7, which is obsolete now

(CI) Use the default setup-python action again as Python 2.7 is obsoleted

---

doc/content/lib/_index.md
doc/content/lib/xenctrl/_index.md
doc/content/lib/xenctrl/xc_domain_node_setaffinity.md
doc/content/xenopsd/walkthroughs/VM.build/Domain.build.md

Improve the remarks on NUMA node_affinity and move them into a dedicated walk-though.
- Also add a diagram for xc_domain_node_setaffinity().

Domain.build docs: Improve notes on NUMA node_affinity, move to new page

---

ocaml/libs/http-lib/http.mli
ocaml/libs/http-lib/http_test.ml
ocaml/xcp-rrdd/bin/rrdd/rrdd_http_handler.ml

/update_rrds returned a 500 HTTP code in some cases where the accept header was
invalid. Now these cases are treated in the same way as a lack of Accept
header.

CA-406403: Do not return HTTP 500 when Accept header can't be parsed

---

doc/content/xenopsd/walkthroughs/VM.migrate.md
doc/content/xenopsd/walkthroughs/VM.start.md

Quick initial typo and spelling fixes.

(doc) xenopsd/walkthroughs/VM.migrate.md: Fix typos and spelling

---

doc/content/xenopsd/walkthroughs/VM.build/VM_build-chart.md
doc/content/xenopsd/walkthroughs/VM.build/VM_build.md
doc/content/xenopsd/walkthroughs/VM.build/_index.md

Merge a small, duplicated flowchart into one and include it where useful for context.

(doc) Update the VM.build flowchart, include it where useful for context

---

ocaml/xs-trace/xs_trace.ml

This allows an xs_trace.exe to be run on any linux machine, whereas previously the use of forkexecd meant that it had to be run on a XS host. It also allows the logic to be simplified (json and ndjson can be handled in the same way).

CP-45795: Decompress compressed trace files without Forkexecd

---

ocaml/xapi/xapi_event.ml

A code clarification effort, consisting of:
- Accumulate lists of event-related objects within a record, instead of a tuple. Using a record permits functional record update, which means we avoid citing lists we have not changed.
- Remove `last_generation`: this mutable variable is updated in a few places and complicates the code. Instead of relying it on being in scope (and mutated in other places), we explicitly pass it in and then thread the update to its value through the retry loop.
- Factor out a routine to convert  `(table, obj, time)` entries into event records, defining the accumulation of `add`, `mod`, and `del` events in terms of it: message events remain special cased because their contents are not in the database. This avoids duplicated code.

Refactor Xapi_event

---

ocaml/idl/datamodel.ml
ocaml/idl/datamodel_lifecycle.ml
ocaml/idl/schematest.ml
ocaml/xapi/rbac.ml
ocaml/xapi/rbac.mli
ocaml/xapi/xapi_task.ml

Currently, users with read-only permissions can freely manipulate their own tasks (create, cancel, destroy, etc.). However, they cannot easily manipulate the `other_config` field. Some keys are specified in the datamodel as being writeable by subjects with the VM operator role.
However, RBAC checking for keys was only ever implemented for the individual "add" and "remove" operations, not the `set_other_config` operation. This makes sense because the typical scenario is that the required writer role for an "other_config" field is more privileged than each of the individually-specified key-specific roles.
In the case of tasks, the desired role for the `set_other_config` operation is the read-only role. However, we cannot simply demote the required "writer role" for the `other_config` field, …

CA-403744: Implement other_config operations for task

---

doc/assets/css/xenapi.css
doc/assets/js/parse.js
doc/layouts/partials/content.html

Adds a simple parser for Xapi type expressions that is used to rewrite the types shown in the XenAPI class reference to include links to relevant documentation.
---
---
The parser is structured in the form of a Pratt parser. This may seem like overkill, but it keeps the door open to extension. Also, the parser must work with limited information (it has no knowledge of XenAPI object names). It works by noting that object types are always (?) suffixed by a type constructor, e.g. `VM ref` - therefore, it assumes any prefix form must be a valid class name, then subsequent left denotations take the left as a type parameter (for which all are unary, except `map` which has an alternative syntax that is special cased).
Currently, the only interesting parts of the "rendered" type are:
- Enum names …

Add internal links to XenAPI reference

---

python3/plugins/extauth-hook-AD.py
python3/tests/test_extauth_hook_AD.py

hcp_nss is a nss module to override the uid/gid of pooladmin when they ssh into dom0, as dom0 only support one single user
However, the name wants to be updated to nss_override_id to reflect its usage

CP-53362: Rename hcp_nss to nss_override_id

---

doc/content/xenopsd/walkthroughs/VM.build/Domain.build.md

Minor improvement - more detail about `wait_xen_free_mem` (called for waiting for scrubbing):
Mention that it terminates in case free memory is smaller than required memory
and `physinfo.scrub_pages = 0` (will never have enough memory for this VM).

(docs) Mention that wait_xen_free_mem terminates on physinfo.scrub_pages = 0

---

ocaml/tests/test_pkg_mgr.ml
ocaml/xapi/pkg_mgr.ml
ocaml/xapi/pkg_mgr.mli
ocaml/xapi/repository.ml
ocaml/xapi/repository_helpers.ml

dnf has been updated to dnf5 during clean rebuild event for XS9, The command line interface changed and we need to update accordingly https://dnf5.readthedocs.io/en/latest/changes_from_dnf4.7.html
Following commands update are necessary for DNF5 update
- updateinfo -> advisory
- config-manager "--save --setopt" -> "setopt"
- reposync removed "--downloadcomps" as it is the default behavior
- repoquery format output no longer has line breaker, add `\n` in format argument to bring it back and align with YUM
- repoquery drop "-a" option as it is default behavior Also improve the code with strong type checking
- Available|Updates for two kinds of updateinfo instead of string

CA-405643: Update DNF to DNF5

---

ocaml/xapi/xapi_globs.ml
ocaml/xapi/xapi_host_driver.ml
ocaml/xapi/xapi_host_driver_tool.ml

* We currently have a mock implementation for driver-tool from the dmv-utils package. Adjust the command line argument structure to the real implementation to make the switch over easy.
* Install the mock implementation if the real implementation is not in place. We might want to remove this later. Currently xapi.spec does not list the dependency.

CP-52365 adjust interface to dmv-utils

---

ocaml/xapi/storage_migrate.ml

`Remote.receive_finalize2` is called at the end of SXM to clean things up and compose the base and leaf images together. The compose operation should only be called while the VDI is deactivated. Currently a thread is created to call `receive_finalize2`, which could caused problems where the VM itself gets started while the
`receive_finalize2`/`VDI.compose` is still in progress. This is not a safe operation to do.
The fix here is simply to wait for the thread to finish.

CA-407033: Call `receive_finalize2` synchronously

---

dune-project
ocaml/libs/tracing/dune
ocaml/libs/tracing/tracing.ml
ocaml/libs/tracing/tracing.mli
ocaml/xapi-idl/lib/debug_info.ml
ocaml/xapi/context.ml
xapi-tracing.opam

Adds functionality to marshal and unmarshal `TraceContext` in the tracing library.
Instead of passing only the `traceparent` in `debug_info`, the entire `TraceContext` is now passed as JSON.
This change enables the transfer of baggage across xenopsd boundaries, improving tracing propagation and debugging capabilities. This should also enable later use of `baggage` as means of passing the thread classification between components.
Latest BVT+BST:211567

CP-52744: Thread `TraceContext` as JSON inside `debug_info`

---

ocaml/libs/xapi-rrd/lib/rrd.ml

Instead of waiting for a complicated fix on XC side, switch back to outputting integers when dumping XMLs.
Implementations that already switched to float should be good, since converting int to float is fine, but not the other way around.
XML is an outdated format, JSON should be preferrably used, and it will keep using floats with larger precision.
Fixes: a897b53 ("CA-391651: Use per-datasource last_updated timestamp during updating and archiving")

CA-407322 - libs/rrd: Keep lastupdate XML field as int, XenCenter relies on it

---

ocaml/xapi/xapi_pool_helpers.ml

In an effort to make the logic clearer, we restructure the part(s) of `Xapi_pool_helpers` responsible for determining which operations are "valid" (i.e. become members of `allowed_operations`).
The previous code is somewhat tedious to understand because it is unconditionally ineffective - the logical delineation of parts of the code is implicit, as the code computes the valid operation table in order, but many of the operations will have no effect (as later code to populate an operation's entry in the validity table do nothing).
This change makes the precedence of blocking and waiting operations more apparent by explicitly casing on them (in decreasing order of precedence). The differences are somewhat subtle and explained in the commit message.
---
BVT+BST (211251) all green except for a …

Restructure valid allowed_operations computation

---

ocaml/xapi/message_forwarding.ml
ocaml/xapi/xapi_host.ml
ocaml/xapi/xapi_pool.ml

These functions were calling remote functions with rpc and session_id as unnamed parameters. Because the remote functions always gave these two parameters named, it required closures throughout the file to fix this inconsistency.
This creates a lot of unnecessary code. Change the situation by making call_slave_... functions to call the functions using named parameters, and group the local and remote functions whenever a chain to_call_slave_... is initiated so it's easy to verify that the calls are correct.
Most of the callers use the same name for both local and remote functions, but there are some interesting cases that can be easily seen now: pool_eject always uses the same remote function for 3 different types of members in the pool, previously 3 different closures were created and the …

message_forwarding: Change call_slave_... functions to reduce repetition

---

doc/content/design/add-qcow-tool-for-vdi-import-export.md

At XCP-ng, we are working on overcoming the 2TiB limitation for VM disks while preserving essential features.
However, we currently cannot export a VDI to a Qcow2 file, nor import one. The purpose of this design proposal is to outline a solution for implementing VDI import/export in Qcow2 format.

Design proposal to support import/export of Qcow2 VDI

---

ocaml/idl/datamodel.ml
ocaml/idl/schematest.ml

To facilitate the telemetry purpose, change "*_id" fields in PCI objects from internal_only:true to internal_only:false in xapi.
class_id
vendor_id
device_id
subsystem_vendor_id
subsystem_device_id

CP-53708: Expose the existing PCI vendor/device IDs

---

ocaml/tests/test_guest_agent.ml
ocaml/xapi/xapi_guest_agent.ml
ocaml/xenopsd/xc/xenops_server_xen.ml

The field `VM_guest_metrics.services` added previously (#6309) is used to store VM service information reported by guest tools.
Xapi does not use this data but just holds it for outside consumers.
This PR reads the xenstore path `data/service` and converts to `[("service_name/key", "value")]` pair list and then store to VM_guest_metrics.services.
The path to read is like:
`/local/domain/<id>/data/service/<service_name>/<key> = <value>`

CP-53314: Read and watch <domain>/data/service in xenstore to DB

---

ocaml/xcp-rrdd/bugtool-plugin/rrdd-plugins.xml

The size is not enough in xs9, xen-bugtool.log:
> Omitting /dev/shm/metrics/xcp-rrdd-squeezed, size constraint of xcp-rrdd-plugins exceeded 
Omitting /dev/shm/metrics/xcp-rrdd-iostat, size constraint of xcp-rrdd-plugins exceeded 
Omitting /dev/shm/metrics/mem-stats, size constraint of xcp-rrdd-plugins exceeded
...
- Tested: 4243304 NRPE
Modifying the max_size to 13107200 (1638400 * 8) solved this issue.
1638400 * 2 and 1638400 * 4 are not enough.

CA-399631: Increase the max size of xcp-rrdd-plugins for bug-tool

---

ocaml/idl/datamodel_errors.ml
ocaml/idl/datamodel_host.ml
ocaml/xapi-cli-server/cli_frontend.ml
ocaml/xapi-consts/api_errors.ml
ocaml/xapi/xapi_host.ml

host.emergency_reenable_tls_verification can only be used after TLS
verification is enabled in pool, raise an error if otherwise.

XSI-1821: Add pre-condition for host.emergency_reenable_tls_verification

---

ocaml/xapi/xapi_vm_migrate.ml

The vm parameter passed to SMAPIv2 calls is needed for the storage backend to know which domain slice it should operate on. For SXM, since there is no specific VM, we use the convention "MIR<vm-prefix>", where the <vm-prefix> is the first five characters of the hash of the vm uuid. This is not sufficient for VMs with multiple VDIs attached to it as they would result in the same vm parameter.
So use a new convention "MIR<vm-prefix><vdi-prefix>" so we distinguish VDIs during migration. These vm parameters cannot be too long though as otherwise the storage backend will not accept them.

CA-407328: Change vm parameter names of SXM calls

---

.github/workflows/1.249-lcm.yml
.github/workflows/docs.yml
.github/workflows/format.yml
.github/workflows/generate-and-build-sdks.yml
.github/workflows/hugo.yml
.github/workflows/main.yml
.github/workflows/other.yml
.github/workflows/release.yml
.github/workflows/shellcheck.yaml

Removes all default permissions, and only adds needed permissions to the workflows that need it.
- read contents: allows reading the repository, most workflows need this
- write contents: allows to write to the repository. Needed to create releases
- write pull-requests: allows to manipulate pull requests. Unfortunately this is needed to comment on PRs
- read actions: allows reading the state of actions
Note that because all workflows remove all permissions at the top level the current default permissions don't take any effect.

github: restrict workflow permissions

---

doc/content/xapi/internals/certificates.md

Add documention for the various PEM files found in a XenServer installation.

CP-53747 document PEM/Certificate relation

---

.codechecker.json
.github/workflows/codechecker.yml
Makefile
ocaml/auth/xa_auth.h
ocaml/libs/log/syslog_stubs.c
ocaml/libs/vhd/vhd_format_lwt/blkgetsize64_stubs.c
unixpwd/c/unixpwd.c

Similar to the static analyzer introduced in xha, but for OCaml C stubs.
This uses my https://ocaml.org/p/dune-compiledb/latest to product a `compile_commands.json` for the C stubs out of the `dune` rules (which can also be useful if you want to use `clangd` and get some editor integration about compiler warnings). This requires installing enough of the build dependencies to be able to run `dune` successfully (perhaps in the future that restriction can be removed). Caching is used though, and we only need to install the build deps when `dune` files change, otherwise we can reuse a cached `compile_commands.json`.
Static analyzers, like CodeChecker support reading `compile_commands.json` and invoking static analyzers with the appropriate flags to preprocess, and analyze the C source code. …

Run static analysis on OCaml C stubs in the CI

---

ocaml/auth/xa_auth_stubs.c

The runtime lock is not being held when `String_val(...)` is used on OCaml values. Instead, we duplicate the strings whilst holding the lock, then use (and free) the values without the lock.
---
Thanks to @last-genius for spotting this. It's a bad pattern used in other places with less consequence (e.g. `Int_val` is unboxed and cannot be relocated), but they should all be changed - I just wanted to quickly address this in particular, since it's my mistake.

Hoist value access outside section without lock

---

ocaml/xapi/extauth.ml
ocaml/xapi/xapi_auth.ml
ocaml/xapi/xapi_pool.ml
ocaml/xapi/xapi_subject.ml

query xapi db, then fallback to query domain DC
get_subject_information_from_identifier query subject details from subject id. It triggers some DNS query to do kerberos query, this causes the problem that authenticating to XAPI with an AD account causes large amounts of Kerberos / DNS traffic
The subject details are actually cached in xapi db and refreshed default in every 10 minutes. get_subject_information_from_identifier should query subject details from xapi DB and only fallback to DC when xapi DB does not have it.

CA-407687/XSI-1834: get_subject_information_from_identifier should

---

ocaml/libs/xapi-rrd/lib/rrd.ml
ocaml/libs/xapi-rrd/lib_test/crowbar_tests.ml
ocaml/libs/xapi-rrd/lib_test/unit_tests.ml
ocaml/xcp-rrdd/bin/rrdd/rrdd_monitor.ml
ocaml/xcp-rrdd/bin/rrdd/rrdd_server.ml

Rrd.ds_create has optional min and max arguments (defaulting to neg_infinity and infinity respectively). Several callers would omit these parameters, resulting in ds_min and ds_max being lost during the conversion from Ds.ds to Rrd.ds. Without these, metrics couldn't be kept in range, which would result in some (such as CPU usage numbers) going negative when a domain would change its domid (over a reboot), for example.
Make these parameters required, not optional. Requires adjusting unit tests as well.
This latent behaviour was exposed during the major timestamp and plugin refactoring last year.
Previously, the entire RRD was created at once by calling create_fresh_rrd. Now create_fresh_rrd is only called for the first chunk, and other chunks of the RRD call merge_new_dss, which omitted …

CA-408126 - rrd: Do not lose ds_min/max when adding to the RRD

---

README.markdown

Change Ocaml version of the example in readme to `4.14.2` as the same as the version in `xs-opam-ci.env`.

Change Ocaml version in readme

---

doc/content/design/sm-supported-image-formats.md

Proposing a new field field to get information about supported image formats for a given SR. This information is retrieved from SMAPIv1 plugins.

Design proposal for supported image formats

---

doc/content/lib/xenctrl/xc_domain_claim_pages.md

(doc) Describe how xc_domain_claim_pages() is used to claim pages

(doc) Describe how xc_domain_claim_pages() is used to claim pages

---

doc/content/lib/xenctrl/xc_domain_node_setaffinity.md
doc/content/lib/xenctrl/xc_vcpu_setaffinity-simplified.md
doc/content/lib/xenctrl/xc_vcpu_setaffinity-xenopsd-notes.md
doc/content/lib/xenctrl/xc_vcpu_setaffinity-xenopsd.md
doc/content/lib/xenctrl/xc_vcpu_setaffinity.md

Describe `xc_vcpu_setaffinity()` and document its use by `xenguest` and `xenopsd`.
This PR is my third iteration of documenting how `xenopsd` and `xenguest`
interact, configure, and set the vCPU affinity. With the clarifications from
@edwintorok, I now have confidence that I finally got this right.

(docs) Describe the flows of setting NUMA node affinity in Xen by xenopsd

---

ocaml/xapi/xapi_pool.ml

We are stopping the management server at the end of the API call. This avoids clients connecting to this host before it has rebooted and become a pool master.
Tested manually; running a BST now.

CA-403851 stop management server in Pool.eject ()

---

.github/workflows/codechecker.yml

When the cache for compile_commands.json got reused we didn't install the OCaml compiler, which caused failures in the static analyzer, because it couldn't locate the compiler runtime headers.
Do not skip setup-xapi-environment when the cache is reused.
This could be optimized to skip installing dune packages (install just the compiler), but for now just install everything to avoid the error.
Now when the cache is used we only skip installing/running dune-compiledb.

CI: fix compile_commands.json caching

---

doc/content/xapi/storage/_index.md

The storage layer code in xapi has undergone some changes: storage_impl.ml is no longer in the repo and is replaced by `storage_smapiv1_wrapper.ml` and `storage_smapiv1.ml`. Update the relevant docs to reflect this change.

doc: xapi storage layer doc update

---

ocaml/xenopsd/c_stubs/xenctrlext_stubs.c
ocaml/xenopsd/xc/domain.ml
ocaml/xenopsd/xc/xenctrlext.ml
ocaml/xenopsd/xc/xenctrlext.mli

This way xen can track the memory intended to be used for each domain and fail
early, if necessary.
This is done on numa_placement because the code is intended to change and do
per-numa-node memory claims in the near future.
Testing is in progress

CP-53827, xenopsd: claim pages for domain on pre_build phase

---

ocaml/libs/tracing/dune
ocaml/libs/tracing/propagator.ml
ocaml/libs/tracing/tracing.ml
ocaml/libs/tracing/tracing.mli
python3/examples/XenAPI/XenAPI.py
python3/packages/observer.py

It continues the path of threading the `trace_context` across different components. Specifically, from `xapi` to `smapi` and back to `xapi`. 
Additional improvement: the tracecontext is passed even when `smapi` component is experimental and it does not create spans. Therefore, it is not creating orphaned spans from http requests made to xapi.
BVT+BST: 213297

CP-53161: `Baggage` threaded through `smapi` and back into `xapi`

---

ocaml/libs/xapi-rrd/lib/rrd.ml

When reading RRD archives from XML, make sure ds_min is (almost never) negative, this will convert negative values to NaNs as well.

CA-408126 follow-up: Fix negative ds_min and RRD values in historical archives

---

.gitignore

When using an opam local switch, ignoring the _opam directory prevents git from searching within it, reducing noise in search results.

Add opam local switch in gitignore

---

Makefile
ocaml/forkexecd/dune
ocaml/forkexecd/helper/Makefile
ocaml/forkexecd/helper/algo_fuzzer.c
ocaml/forkexecd/helper/close_from.c
ocaml/forkexecd/helper/close_from.h
ocaml/forkexecd/helper/logs.c
ocaml/forkexecd/helper/logs.h
ocaml/forkexecd/helper/redirect_algo.h
ocaml/forkexecd/helper/syslog.c
ocaml/forkexecd/helper/syslog.h
ocaml/forkexecd/helper/vfork_helper.c
ocaml/forkexecd/helper/vfork_helper.h
ocaml/forkexecd/lib/dune
ocaml/forkexecd/lib/fe_stubs.c
ocaml/forkexecd/lib/forkhelpers.ml
ocaml/forkexecd/test/dune
ocaml/forkexecd/test/fe_test.sh
ocaml/forkexecd/test/syslog.c
ocaml/libs/stunnel/stunnel.ml

Forkexecd was written to avoid some issues with Ocaml and multi-threading.
Instead use C code to launch processes and avoid these issues.
Interface remains unchanged from Ocaml side but implementation rely entirely on C code.
vfork() is used to avoid performance memory issue.
Reap of the processes are done directly.
Code automatically reap child processes to avoid zombies.
One small helper is used to better separate Ocaml and C code and handling syslog redirection. This allows to better debug in case of issues.
Syslog handling is done in a separate process allowing to restart the toolstack and keep launched programs running; note that even with forkexecd daemon one process was used for this purpose.
Code tries to keep compatibility with forkexecd, in particular:
- SIGPIPE is ignored in …

IH-533: Remove usage of forkexecd daemon to execute processes

---

ocaml/xapi/xapi_host_driver.ml

Not all driver-tool invocations have been properly adjusted to an updated command line syntax; do it here.

CP-52365 fix up driver-tool invocations

---

ocaml/xenopsd/c_stubs/xenctrlext_stubs.c

Int_val truncates values to a 32-bit int. Instead use Long_val, which does not suffer from this.
This is a problem when claiming more than ≈ 9706GiBs for a domain.
Found after reading this PR https://github.com/ocaml/ocaml/pull/13852

xenctrlext: do not truncate the amount of memory in claims to 32 bits

---

dune-project
ocaml/forkexecd/dune
xapi-debug.opam
xapi-stdext-threads.opam
xapi-tools.opam

- forkexecd: do not tie vfork_helper to the forkexec package
- opam: add missing dependencies to packages

Fix building of all opam packages for xs-opam's CI

---

ocaml/xapi/xapi_event.ml

Same as https://github.com/xapi-project/xen-api/pull/6306 but retaining the suppression of potential snapshot-related exceptions. Now, there is commentary, a citation of the internal CA ticket (from 2012), and a commit hash citing the introduction of the `try`-`with`.
---
Clean BVT+BST (214804) and works as expected under the internal error reproduction script.
These commits were cherry picked back to the top, but I am happy to squash them.

Refactor Xapi_event (redux)

---

ocaml/xenopsd/scripts/swtpm-wrapper

The default crypto policy in XS9 disables use of SHA1. However, swtpm needs to use it since it advertises SHA1 support to guests. On XS9, swtpm will ship with a custom openssl configuration file for this purpose so set the appropriate environment variable to use it if the file exists.

CA-407177: Fix swtpm's use of SHA1 on XS9

---

ocaml/libs/stunnel/stunnel.ml
ocaml/xapi/repository.ml

Pls refer to commit msg for details

CA-404460: Expose Stunnel_verify_error for mismatched or corrupted certificate, and expose ssl_verify_error during update syncing

---

ocaml/idl/datamodel_common.ml
ocaml/idl/datamodel_errors.ml
ocaml/idl/datamodel_host.ml
ocaml/idl/datamodel_pool.ml
ocaml/idl/schematest.ml
ocaml/tests/common/test_common.ml
ocaml/xapi-consts/api_errors.ml
ocaml/xapi/message_forwarding.ml
ocaml/xapi/xapi_host.ml
ocaml/xapi/xapi_host.mli
ocaml/xapi/xapi_pool.ml
ocaml/xapi/xapi_pool.mli

This PR introduces support for Dom0 SSH control, providing the following capabilities:
Query the SSH status.
Configure a temporary SSH enable timeout  for a specific host or all hosts in the pool.
Configure the console idle timeout for a specific host or all hosts in the pool.
Changes
New Host Object Fields:
- `ssh_enabled`: Indicates whether SSH is enabled.
- `ssh_enabled_timeout`: Specifies the timeout for temporary SSH enablement.
- `ssh_expiry`: Tracks the expiration time for temporary SSH enablement.
- `console_idle_timeout`: Configures the idle timeout for the console.
New Host/Pool APIs (This PR only include the change of data model, the implementation of this API will be include in the next PR):
- `set_ssh_enabled_timeout`: Allows setting a temporary timeout for enabling the SSH …

CP-53477 Update Host/Pool Data model to Support Dom0 SSH Control

---

python3/packages/observer.py

This keeps them contained, allowing them to easily be hidden in Jaeger. Below is a screenshot of it in action:

CP-53472: Create parent for add_module spans

---

ocaml/libs/xapi-rrd/lib/rrd.ml

Several assumptions in the `ds_update` function expect at least one element to be present in the array, and will raise `Invalid_argument("index out of bounds")` otherwise. This could be triggered by disabling all datasources for a particular plugin/owner combination, for example.

CA-408841 rrd: don't call ds_update with an empty datasource array

---

ocaml/xapi-client/event_helper.ml
ocaml/xenopsd/c_stubs/xenctrlext_stubs.c
ocaml/xenopsd/lib/softaffinity.ml
ocaml/xenopsd/lib/softaffinity.mli
ocaml/xenopsd/lib/topology.ml
ocaml/xenopsd/lib/topology.mli
ocaml/xenopsd/test/test_topology.ml
ocaml/xenopsd/xc/domain.ml
ocaml/xenopsd/xc/dune
ocaml/xenopsd/xc/numa.ml
ocaml/xenopsd/xc/xenctrlext.ml
ocaml/xenopsd/xc/xenctrlext.mli
ocaml/xenopsd/xc/xenops_server_xen.ml

This PR allows xenopsd to launch domains that are using memory allocated in a single NUMA node in a reliable way. (when restarting a VM in a host with most of the memory in use)
Since this is only supported by Xen with this patchqueue: https://lists.xen.org/archives/html/xen-devel/2025-03/msg01127.html, and it needs support from xenguest and emu-manager, there are two commits that revert the changes to just claim memory pages without a NUMA memory node. These are easily revertable by patches to enable this functionality in cutting edge builds.
Revertable patches:
-  xenctrl: Don't use numa_node in domain_claim_pages calls
- xenopsd/xc: Do not try to allocate pages to a particular NUMA node

CP-53658: Claim memory on a single NUMA node

---

ocaml/xapi/xapi_pool.ml

This is a follow up for https://github.com/xapi-project/xen-api/pull/6395#discussion_r2024851382

CP-53711: Apply SSH settings in joiner before update_non_vm_metadata

---

ocaml/idl/datamodel_host.ml
ocaml/xapi-consts/constants.ml
ocaml/xapi/dbsync_slave.ml
ocaml/xapi/xapi_pool.ml

After being ejected from a pool, a new host obj will be created with default settings in DB.
This commit configures SSH service in the ejected host to default state during pool eject.

CP-53802: Restore SSH service to default state in pool eject

---

ocaml/idl/datamodel_errors.ml
ocaml/xapi-cli-server/records.ml
ocaml/xapi-consts/api_errors.ml
ocaml/xapi/xapi_globs.ml
ocaml/xapi/xapi_host.ml
ocaml/xapi/xapi_pool.ml

Implemented XAPI APIs:
- `set_ssh_enabled_timeout`
- `set_console_idle_timeout`
These APIs allow XAPI to configure timeouts for the SSH service and idle console sessions from both host and pool level.
Updated `records.ml` to support `host-param-set/get/list` and `pool-param-set/get/list` for SSH-related fields.

CP-53478: Implement SSH-related APIs for Dom0 SSH control

---

ocaml/xapi/xapi_vm_migrate.ml

There is already a call to `assert_can_migrate_vdis` present in `assert_can_migrate`, which checks that none of the VDIs that *are going to be moved* have CBT enabled. There is no need to additionally check that none of the VDIs *in general* have CBT enabled.
Some clients, like XenOrchestra, will turn off CBT on VDIs and retry migration after getting the `VDI_CBT_ENABLED` error on live migration. Dropping this overly strict check allows not stripping CBT when VDI will not be moved (when it's on a shared SR).
In addition, during rolling pool upgrades, disabling CBT is not allowed, hence the live migration operation wouldn't be able to continue. Avoiding the strict check fixes that as well.
Closes #6400

xapi_vm_migrate: Avoid duplicate, overly-strict CBT check on VDIs

---

ocaml/libs/tracing/tracing.ml
ocaml/libs/tracing/tracing_export.ml
ocaml/xenopsd/lib/xenops_server.ml
ocaml/xenopsd/xc/xenops_server_xen.ml

Also simplify two tracing functions which could just use Span.get_trace_context directly

CP-50836: Add VM_migrate_downtime and request_shutdown spans to help visualise potential optimisations

---

ocaml/xapi/xapi_observer.ml

If smapi observer was previously enabled and then added to observer_experimental_components, when the toolstack is restarted the smapi observer will no longer exist. The observer will therefore not be "destroyed" by normal means so we must remove the config manually.
This is important for xapi-storage-script as it cannot read the DB and so relies on this config file to know whether to trace SMAPIv3 or not.

CA-401023: Remove smapi observer config if smapi is set as experimental

---

ocaml/idl/datamodel.ml
ocaml/xapi/xapi_message.ml

Messages are not stored in the database, so their handling is done through Custom_actions. The custom implementation of get_all_records_where, in particular, used to ignore the query expression altogether (as if expr = true).
Expand the existing handler to evaluate the query and match against the messages retrieved and parsed from disk.
An alternative approach would have instead special cased filtering code in the database itself, but in my attempts this was awkward and duplicated quite a lot of code.
With this it is possible to filter messages properly now:
```
>>> session.xenapi.message.get_all_records_where('field "name" = "VM_STARTED"')
<list of messages with name = VM_STARTED>
>>> session.xenapi.message.get_all_records_where('field "name" = "VM_STARTED" and field "obj_uuid" = …
```

xapi_message: Implement proper expression handling in get_all_records_where

---

ocaml/xapi/check-no-lwtssl.sh
ocaml/xapi/dune
ocaml/xapi/sparse_dd_wrapper.ml
ocaml/xapi/storage_migrate.ml

It usually uses `stunnel` for that purpose, and we don't want XAPI to be affected by OpenSSL bugs directly.
We can't completely drop openssl because sparse_dd relies on it, but that is a separate executable.

CP-53951: XAPI should not depend on libssl

---

ocaml/quicktest/quicktest.ml
ocaml/quicktest/quicktest_message.ml
quality-gate.sh

Also adjust the number of List.hd expected by the quality gate.

quicktest: Add a test verifying Message.get_all_records_where filtering

---

ocaml/xapi/check-no-lwtssl.sh

It sneaks in via xenstore_transport and tar.unix, fixing that requires patching those 2 libraries first.
For now partially revert this test: only test for linking with OpenSSL, not Lwt.
Fixes: 0832ae517 ("CP-53951: Drop SSL and Lwt dependency from XAPI")

CI: allow XAPI linking with Lwt for now

---

ocaml/xapi-aux/kerberos_encryption_types.ml
ocaml/xapi-aux/kerberos_encryption_types.mli
ocaml/xapi/extauth_plugin_ADwinbind.ml
ocaml/xapi/xapi_globs.ml

According to https://techcommunity.microsoft.com/blog/coreinfrastructureandsecurityblog/decrypting-the-selection-of-supported-kerberos-encryption-types/1628797 msDS-SupportedEncryptionTypes of machine account help to decide Service Ticket encryption type
Some customer IT teams have strict encryption types limitation in their domains
This commit add winbind_set_machine_account_kerberos_encryption_type and default to false. When enabled, xapi set the machine account encryption types consistent with the samba client

CA-408843: XSI-1852: Set encryption type of machine account

---

dune-project
ocaml/libs/tgroup/tgroup.ml
ocaml/libs/tgroup/tgroup.mli
ocaml/libs/xapi-stdext/lib/xapi-stdext-threads/dune
ocaml/libs/xapi-stdext/lib/xapi-stdext-threads/threadext.ml
ocaml/libs/xapi-stdext/lib/xapi-stdext-threads/threadext.mli
ocaml/libs/xapi-stdext/lib/xapi-stdext-threads/threadext_test.ml
opam/xapi-stdext-threads.opam

Adds a `ThreadLocalStorage` module under `Threadext`. Currently, it
uses `Ambient_local.Thread_local` as the underlying implementation.
Following the thread classification PRs, https://github.com/xapi-project/xen-api/pull/6154, this will enable
accessing the current thread group for each thread. The current data
structure contains the following:
1. ocaml_tid
2. thread_name
3. time_running
4. tepoch
5. tgroup
Field 1: `ocaml_tid` is equivalent to `Thread.self () |> Thread.id.`
Field 2: `thread_name` is to associet threads with human readable
string.
Fields 3-5:
- `time_runinng` - the amount of time the thread has been running in
the current OCaml runtime timeslice,
- `tepoch` - the current timeslice the thread has been scheduled for,
- `tgroup` - current thread classification.
Fields 3-5 …

CP-52745: Add `ThreadLocalStorage` in `Threadext`

---

ocaml/xapi-idl/storage/storage_interface.ml
ocaml/xapi-idl/storage/storage_skeleton.ml
ocaml/xapi-storage-cli/dune
ocaml/xapi-storage-cli/main.ml
ocaml/xapi-storage-script/main.ml
ocaml/xapi/storage_access.ml
ocaml/xapi/storage_migrate.ml
ocaml/xapi/storage_migrate_helper.ml
ocaml/xapi/storage_migrate_helper.mli
ocaml/xapi/storage_mux.ml
ocaml/xapi/storage_smapiv1.ml
ocaml/xapi/storage_smapiv1_migrate.ml
ocaml/xapi/storage_smapiv1_migrate.mli
ocaml/xapi/storage_smapiv1_wrapper.ml
ocaml/xapi/storage_smapiv3_migrate.ml
ocaml/xapi/storage_smapiv3_migrate.mli
ocaml/xapi/xapi_vm_migrate.ml

This is a continuation of #6378: the refactoring effort of SXM code.
To be continued...

CP-540722: Define the `MIRROR` interface to be implemented by Storage_smapi{v1,v3}_migrate.ml

---

ocaml/xapi-idl/rrd/rrd_interface.ml
ocaml/xcp-rrdd/bin/rrdd/xcp_rrdd.ml
ocaml/xcp-rrdd/bin/rrdp-cpu/rrdp_cpu.ml

Draft, because I still need to test it.

Make xcp-rrdp-cpu more robust

---

ocaml/xapi/xapi_sr.ml

Currently, we are only checking that no VDIs have been removed during the SR scan performed by the SM plugin. However, there are situations where a VDI has been added, and if this VDI is not present in the list obtained from SR.scan, it will be forgotten. The checks only prevent this in the case where the VDI was added during the scan. There is still a TOCTOU situation if the issue happens after the scan, and there is room for that.

Check that there are no changes during SR.scan

---

ocaml/xapi/dbsync_slave.ml
ocaml/xapi/xapi_globs.ml
ocaml/xapi/xapi_host.mli
ocaml/xapi/xapi_periodic_scheduler_init.ml

- Ensure `host.ssh_enabled ` reflects the actual SSH service state on startup, in case it was manually changed by the user.
- Reschedule the "disable SSH" job if:
- `host.ssh_enabled_timeout` is set to a positive value, and
- `host.ssh_expiry` is in the future.

CP-54138: Sync SSH status during XAPI startup

---

ocaml/xcp-rrdd/bin/rrdp-cpu/rrdp_cpu.ml

Adding a new metric 'runnable' as % of time that at least one vCPU of the domain
is in the runnable state. It is the sum of the following 3 metrics:
- runstate_full_contention
- runstate_concurrency_hazard
- runstate_partial_contention

CP-53858: Domain CPU ready RRD metric

---

ocaml/tests/test_guest_agent.ml
ocaml/xapi/xapi_guest_agent.ml

Windows PV drivers do not store their version information into `drivers/{xeneventchn,xenvbd,xennet}` xenstore keys since 2015, see:
* PV drivers commit `784af16810d705ba2bc02bab6ac93b24119f886c (Publish distribution information to xenstore)` https://xenbits.xen.org/gitweb/?p=pvdrivers/win/xenbus.git;a=commit;h=784af16810d705ba2bc02bab6ac93b24119f886c
* Xen commit `71e64e163b2dae7d08f7d77ee942749663f484d5 (docs: Introduce xenstore paths for PV driver information)` https://xenbits.xen.org/gitweb/?p=xen.git;a=commit;h=71e64e163b2dae7d08f7d77ee942749663f484d5
Instead it is stored like this:
```
drivers/0 = "XenServer XENBUS 9.1.9.105 "
drivers/1 = "XenServer XENVBD 9.1.8.79 "
drivers/2 = "XenServer XENVIF 9.1.12.101 "
drivers/3 = "XenServer XENIFACE 9.1.10.87 "
drivers/4 = "XenServer XENNET …
```

xapi_guest_agent: Update xenstore keys for Windows PV drivers versions

---

ocaml/idl/datamodel_cluster.ml
ocaml/idl/datamodel_common.ml
ocaml/idl/datamodel_lifecycle.ml
ocaml/idl/schematest.ml
ocaml/tests/common/test_common.ml
ocaml/tests/test_cluster.ml
ocaml/tests/test_cluster_host.ml
ocaml/xapi-cli-server/records.ml
ocaml/xapi-idl/cluster/cluster_interface.ml
ocaml/xapi/xapi_cluster.ml
ocaml/xapi/xapi_clustering.ml

The `expected_votes` field in corosync represents the number of hosts that is expected by the cluster stack. In the context of corosync, this is the same as the number of hosts as in the corosync.conf file*. This is a useful field to expose to the user so that they can see how many nodes actually are expected.
We also have `Cluster_host` object, which represents xapi's view of what nodes should be in the cluster, but that might not be identical to corosync's view, especially when a host is disabled, but is still left in the list of Cluster_host objects.
Although one could argue that we could infer this `expected_votes` field from the number of enabled Cluster_hosts, it might still be useful to get this information directly from corosync.
*: there are ways in corosync to make one host cast …

CP-54034: Expose `expected_votes` in Cluster object

---

ocaml/xapi/storage_migrate.ml
ocaml/xapi/storage_migrate_helper.ml
ocaml/xapi/storage_migrate_helper.mli
ocaml/xapi/storage_mux.ml
ocaml/xapi/storage_smapiv1.ml
ocaml/xapi/storage_smapiv1.mli
ocaml/xapi/storage_smapiv1_migrate.ml
ocaml/xapi/storage_utils.ml
ocaml/xapi/storage_utils.mli
ocaml/xapi/xapi_services.ml

Move the update_snapshot_info_dest to storage mux as this function just does db operations.
Also rescan the SR after updaing the content_id during SXM, so that the latest content_id can be reflected in the returned vdi_info, which gets used later on in `update_snapshot_info`

Move the `update_snapshot_info_dest` to storage mux

---

ocaml/xcp-rrdd/bin/rrdp-iostat/rrdp_iostat.ml

Since XCP-ng is now supporting qcow files `tap-ctl list` can return string like:
- "1564848    0    0      qcow2 /var/run/sr-mount/..."
Without this patch the type "qcow2" is unknown and xcp-rrdd-iostat generates an
error like: `returned a line that could not be parsed. Ignoring`
This patch fixes the issue by allowing qcow2 type.

Add qcow2 as supported format by xcp-rrdd-iostat

---

ocaml/tests/bench/bench_vdi_allowed_operations.ml
ocaml/tests/bench/dune
ocaml/xapi/cancel_tasks.ml
ocaml/xapi/xapi_globs.ml
ocaml/xapi/xapi_vdi.ml
ocaml/xapi/xapi_vdi.mli

Activate old xapi_vdi.update_allowed_operations optimization:  get_internal_records_where does a linear scan currently, so operating on N VDIs is O(N^2).
Look at the VBD records directly, like before this 2013 commit which regressed it: 5097475ded2cdd90d879833ad9efea33e1bc29eb
(We are going to optimize get_record separately so it doesn't go through serialization)
This still requires validation and measurements (e.g. using @contificate 's benchmark)

CP-52880: Avoid O(N^2) behaviour in Xapi_vdi.update_allowed_operations

---

python3/libexec/nbd_client_manager.py

This was found during a previous stress test.
Without a persistent connection the kernel might disconnect from the backing qemu/tapdisk in Dom0 when I/O takes too long, and that prevents all future I/O to that device from working, not just the one that had the speed hickup.
Since our NBD connection is local, mark it as persistent, so that it tries to reconnect on timeout.

CA-404946: NBD: increase timeout to match iSCSI timeout and use persistent connections

---

README.markdown

XAPI website deadlink updated.
Closes #6447

XAPI website link updated in README

---

ocaml/networkd/lib/dune
ocaml/networkd/lib/network_config.ml
ocaml/networkd/lib/network_device_order.ml
ocaml/networkd/lib/network_device_order.mli
ocaml/networkd/test/dune
ocaml/networkd/test/test_network_device_order.ml
ocaml/networkd/test/test_network_device_order.mli
ocaml/networkd/test/test_network_device_order_inherited.ml
ocaml/networkd/test/test_network_device_order_inherited.mli
ocaml/xapi-idl/network/dune
ocaml/xapi-idl/network/network_interface.ml

This part sorts host network devices in xcp-networkd. Previously, the
ordering was handled by the interface-rename functionality. This will
now be replaced by an equivalent function in xcp-networkd, but without
renaming the network devices. The renmaing performed by the
interface-rename was used to record the sorting result as the name of
the NICs like "eth<N>". Now the sorting result will be recorded as
internal files.

CP-44103: Ordering network devices

---

ocaml/libs/log/test/dune

This should fix the current xs-opam failure with xapi master, see for example the failure here: https://github.com/last-genius/xs-opam/tree/master
Fixes: bfea6f33240a ("CA-409628: Add backtrace logging test")

xapi-log/test: Package the cram test in xapi-log

---

scripts/xe-backup-metadata

The current default count of metadata backup files is 25. This number is too
many. For the customer in XSI-1873, the backup disk is 500 MB, and each backup
file is about 35 MB. So it can't keep 25 backup files.
A quick solution is to modify the backup parameters, including:
1. Reduce the default count of metadata backup files to 12.
2. Increase the backup VDI size to 1 GiB so it can keep more backup files.

CA-409710: Modify the default backup parameters

---

ocaml/xapi-idl/xen/xenops_interface.ml
ocaml/xapi/xapi_vm_migrate.ml
ocaml/xenopsd/lib/xenops_server.ml

When the VM (and its memory) isn't actually going to be moved anywhere (like in VDI migration to another SR), there's no point in ballooning down, it's actually likely to make VDI migration take longer if swap is engaged.

xenopsd: Don't balloon down memory on same-host migration

---

ocaml/xcp-rrdd/bin/rrdd/rrdd_monitor.ml

CA-391651 replaced the function `rrd_add_ds` with an unsafe function
`rrd_add_ds_unsafe` in `rrdd_monitor.ml`. Although it has checked if the new
ds exists in `rrdi.dss`, if a ds exists in `rrdi.rrd` but not in `rrdi.dss`, it
leads the ds duplicates twice in `rrdi.rrd` (E.g. when rrdd plugin starts,
it loads local rrdd backup file into `rrdi.rrd` but leaves `rrdi.dss` empty).
Solution:
Filter out `new_enabled_dss` based on `rrdi.rrd` instead of `rrdi.dss`.

CA-410001: Check rrdi.rrd to avoid ds duplicate

---

ocaml/xapi/xapi_xenops.ml

As described in [#6451](https://github.com/xapi-project/xen-api/issues/6451), a xapi event could prevent update_vm from pulling the latest Xenopsd metadata, overwriting it with stale information. In case of suspend, this would make the snapshot unresumable, raising an assert in xenopsd due to incongruities in memory values.
Instead pull the xenopsd metadata right before updating DB.power_state in`Xapi_vm_lifecycle.force_state_reset_keep_current_operations`, eliminating the window for the race.
Closes #6451

xapi_xenops: Avoid a race during suspend

---

ocaml/networkd/lib/network_device_order.ml

These IBFT devices are not managed by Toolstack and therefore are not involved in the ordering process.

CP-54445: Filter out ibft devices which are for boot from iSCSI SAN

---

ocaml/libs/xapi-stdext/lib/xapi-stdext-unix/unixext_stubs.c

This would eventually lead to compilation errors with newer versions of GCC, best fix it now by renaming the parameter.

[maintenance]: bool is a keyword in newer C versions, cannot be a parameter

---

ocaml/xapi-idl/storage/storage_interface.ml
ocaml/xapi-idl/storage/storage_skeleton.ml
ocaml/xapi-storage-cli/main.ml
ocaml/xapi-storage-script/main.ml
ocaml/xapi/storage_access.ml
ocaml/xapi/storage_migrate.ml
ocaml/xapi/storage_mux.ml
ocaml/xapi/storage_smapiv1.ml
ocaml/xapi/storage_smapiv1_migrate.ml
ocaml/xapi/storage_smapiv1_wrapper.ml
ocaml/xapi/storage_smapiv3_migrate.ml
ocaml/xapi/xapi_vm_migrate.ml

Continuation of #6434, more mutiplexing for SXM, this time the mirror status checking logic.
No functional change.
More to come...

Mux mirror failure check for SXM

---

ocaml/xapi-idl/storage/storage_interface.ml
ocaml/xapi-idl/storage/storage_skeleton.ml
ocaml/xapi-storage-script/main.ml
ocaml/xapi/storage_migrate.ml
ocaml/xapi/storage_mux.ml
ocaml/xapi/storage_smapiv1.ml
ocaml/xapi/storage_smapiv1_migrate.ml
ocaml/xapi/storage_smapiv1_wrapper.ml
ocaml/xapi/storage_smapiv3_migrate.ml

This otherwise breaks migration from xapi-25.3.0 -- xapi-25.17.0 to newer versions of xapi (25.18.0)

CA-408492: Add back receive_start2 for backwards compat

---

ocaml/database/db_backend.ml
ocaml/database/db_connections.ml
ocaml/database/db_lock.ml
ocaml/database/db_ref.ml
ocaml/database/db_ref.mli
ocaml/database/db_remote_cache_access_v1.ml
ocaml/database/redo_log.ml
ocaml/tests/bench/bench_pool_field.ml
ocaml/tests/bench/dune
ocaml/xapi-types/event_types.ml
ocaml/xapi/pool_db_backup.ml
ocaml/xapi/xapi_session.ml
ocaml/xapi/xapi_vdi_helpers.ml

We were converting events to RPC.t twice: first using the internal OCaml names, and then mapping them back to some "wire" names. This can be done a lot more simply by generating the wire names in the first place (the ppx support overriding the wire name of fields).
`ministat` confirms an improvement on `rpc_of_event`:
```
N           Min           Max        Median           Avg        Stddev
x  922     440.79126     46094.975     467.83727     563.79259     1676.0843
+ 1131     51.346821     33407.866     58.715393     115.98006     1105.4178
Difference at 95.0% confidence
-447.813 +/- 120.966
-79.4286% +/- 13.1488%
(Student's t, pooled s = 1390.95)
```
Atomic is also faster than an integer wrapped with a mutex:
```
Mutex+incr (ns):
{ monotonic-clock per run = 32.272091 (confidence: …
```

CP-307958: small DB improvements and benchmarks

---

ocaml/xapi/storage_access.ml

On XS9 a previiously available SM type might become unavailable. Make sure we remove it on upgrade. The previius fix in CA-408048 did not work.

CA-409949 CA-408048 remove unavailable SM types at startup

---

ocaml/gencert/lib.ml
ocaml/gencert/test_lib.ml
ocaml/idl/datamodel_errors.ml

A user can install server certificates to secure the connection between xapi and their API clients. So far we demanded SHA256 certificates. Accept SHA512 in addition.
The patch renames the predicate to no longer imply that we only accept SHA256.
Tested this:
```
openssl req -x509 -sha512 -nodes -days 365 -newkey rsa:2048 -keyout mycert.key -out mycert.crt -subj "/CN=localhost"
xe host-server-certificate-install certificate=mycert.crt private-key=mycert.key
```

CP-307865 accept SHA512 for custom server certs

---

.github/python-nosetests-3.sh
.github/python-nosetests.sh
.github/workflows/1.249-lcm.yml
.github/workflows/format.yml
scripts/test_usb_scan.py

github: keep yangtze's runs working

---

ocaml/xapi/xapi_host.ml
ocaml/xapi/xapi_host_helpers.ml

Back in 2018 a4a94b38c66203c9f02752f181d1c01f73bf52a1 rejected empty IQNs in set_iscsi_iqn API calls. However hosts are created with an empty IQN, and if this code runs too early then it will attempt to call `set-iscsi-initiator` with an empty string for the IQN:
```
/opt/xensource/libexec/set-iscsi-initiator  myhost
```
About a second later the script is called again with the correct value. This could potentially result in the iscsid service being restarted multiple times (and if a restart is still pending when restart is called a 2nd time I'm not sure it'll take effect, so we might be left with an empty initiator, I have also seen a GFS2 SR plug failure following this).
It is best to avoid setting empty initiators. The exception would be raised and ignore due to the log_and_ignore in …

CA-411122: do not call set-iscsi-initiator with an empty string for IQN

---

ocaml/idl/datamodel_common.ml
ocaml/idl/datamodel_errors.ml
ocaml/idl/datamodel_host.ml
ocaml/idl/datamodel_pool.ml
ocaml/idl/schematest.ml
ocaml/tests/common/test_common.ml
ocaml/tests/test_host.ml
ocaml/xapi-cli-server/records.ml
ocaml/xapi-consts/api_errors.ml
ocaml/xapi-consts/constants.ml
ocaml/xapi/dbsync_slave.ml
ocaml/xapi/message_forwarding.ml
ocaml/xapi/xapi_globs.ml
ocaml/xapi/xapi_host.ml
ocaml/xapi/xapi_host.mli
ocaml/xapi/xapi_periodic_scheduler_init.ml
ocaml/xapi/xapi_pool.ml
ocaml/xapi/xapi_pool.mli

This PR introduces support for Dom0 SSH control, providing the capability to configure the auto mode for a specific host or all hosts in the pool.
New Host Object Fields and Host/Pool API:
- `ssh_auto_mode`:  Indicates whether SSH auto mode is enabled. configure to true means startup SSH when the XAPI service is down; stop SSH when the XAPI service is up. configure to false means SSH service status is independent and not effected by the XAPI service status.
- `set_ssh_auto_mode`: Allows setting auto mode for specific host or all hosts in the pool.
(Note: Default value for XS8/XS9, pool join/eject operations, and XAPI startup scenarios will be addressed in the next PR, this PR only include the change of data_mode/API/cli )

CP-53721 Enable XAPI to configure SSH auto mode

---

ocaml/xenopsd/lib/xenops_server.ml
quality-gate.sh

Each Parallel atom takes up a worker thread whilst its children do the actual work, so we have parallel_queues to prevent a deadlock. However, nested Parallel atoms take up an additional worker, meaning they can still cause a deadlock. This commit adds a new Nested_parallel atomic with matching nested_parallel_queues to remove the possibility of this deadlock.
This increases the total number of workers, but these workers are just to hold the Nested_parallel Atomics and will not be doing any actual work

CA-409510: Make xenopsd nested Parallel atoms explicit

---

ocaml/xapi/helpers.ml
ocaml/xapi/xapi_vm.ml
ocaml/xapi/xapi_vm.mli

`Helpers.progress`' only user was `Xapi_vm.immediate_complete`, which wasn't used anywhere. Remove both. No functional changes.

xapi: Cleanup unused functions

---

scripts/xapi.conf

The paths to SM plugins in XS9 is about to change. This will be implemented with a conf file in /etc/xapi.conf.d/ and will be easy to overlook when just looking at xapi.conf. Update the comment there.

CP-308075 document changing paths for SM plugins in XS9

---

ocaml/networkd/bin/network_server.ml
ocaml/networkd/bin/networkd.ml
ocaml/networkd/lib/network_config.ml
ocaml/networkd/lib/network_device_order.ml
ocaml/networkd/lib/network_device_order.mli
ocaml/xapi-idl/network/network_interface.ml
ocaml/xapi/helpers.ml
ocaml/xapi/xapi_pif.ml
ocaml/xapi/xapi_pif.mli

This PR is the adaption of #6381 in networkd and xapi.
XS8: Keep the legacy behaviour, use host-installer, sort-script to sort and rename the network interfaces to `ethx`.
XS9: Use `Network_device_order.sort` to sort the interfaces, store the result in networkd `config.interface_order`.
Compatibility is offered by check the sort-script `interface-rename-data` dir.
Add new interface [Interface.get_interface_positions](https://github.com/xapi-project/xen-api/commit/a5e2cee10f1c51e9ad68147db67a3747e186c0b9) to pass interfaces and positions from networkd to xapi.

Adapt network interfaces sorting

---

ocaml/idl/datamodel_errors.ml
ocaml/tests/test_repository_helpers.ml
ocaml/xapi-consts/api_errors.ml
ocaml/xapi/repository.ml
ocaml/xapi/repository_helpers.ml
ocaml/xapi/xapi.ml
ocaml/xapi/xapi_globs.ml

This change introduces a new `repository_domain_name_blocklist` that lists repo URL patterns to be blocked.
On XAPI startup, any exsiting pool repository whose URLs matches an entry in this blocklist will be automatically removed. This ensures that, for example, when upgrading from XS8 to XS9, any XS8 repos are purged.
Additionally, repository creating now check the same blocklist and rejects any attempt to add a blocked repo.
- On startup: read blocklist, delete matching blocked repos
- On repository creation: validate against blocklist and abort if matched
Tests:
- Create repo with the blocklist configured
- Create repo without the blocklist configured
- With the blocklist, restart xapi and the repo was removed
`[root@eu1-dt013 yum.repos.d]# xe repository-list`

CP-54275: Add a blocklist mechanism to avoid incorrect/old repo config.

---

ocaml/xenopsd/lib/xenops_server.ml
ocaml/xenopsd/lib/xenopsd.ml
ocaml/xenopsd/xc/xenops_server_xen.ml

We've seen that using the policy can be up to 10% faster than using any is some
workflows, while not observing workflows that were negatively affected. The
policy per VM can always be change if need be.
Note that currently sometime the best-effort falls back to the same behaviour,
especially when restarting on starting more than one VM at a time. This needs
xen patches to be fixed:
https://lore.kernel.org/xen-devel/20250314172502.53498-1-alejandro.vallejo@cloud.com/
Also fix the legacy numa-placement configuration option for xenopsd. It was
always deciding the setting, even when not used, not it only takes effect when
it's present, otherwise it leaves the default option untouched.

CP-53642: change default NUMA placement policy to best-effort

---

ocaml/networkd/bin/network_server.ml
ocaml/xapi/xapi_pif.ml
ocaml/xapi/xapi_pool.ml

As pool.eject_self calls interface-rename script to rename the network interfaces, this behaviour should be done compatibly.
So, move the interface-rename to networkd with compatibility check.
When reset networkd state
legacy: use interface-rename script to sort and rename
new: use networkd network_device_order with initial empty order to sort

CP-44105: Adjust Net.reset_state for pool.eject_self

---

ocaml/networkd/bin/network_monitor_thread.ml
ocaml/xcp-rrdd/bin/rrdp-netdev/rrdp_netdev.ml

With interface-rename functionality, the host network devices are ordered and renamed like "eth<N>". So they can be filtered by hard-coded "eth" and added into the networkd monitor list and rrdd collecting list.
While the interface-rename is being replaced by the ordering function in networkd. Unlike the interface-rename, the networkd will not rename the host network devices anymore. Instead, the naming of them are left to the built-in systemd and Kernel.
In both cases, the networkd's Interface.get_interface_position can return the managed (ordered) host network devices: when the interface-rename functionality is still working, it returns the list of "eth<N>"; when networkd takes the place to perform the ordering, it returns the names generated by systemd and Kernel.

CP-53719: Update monitor and collecting list for host network devices

---

ocaml/xcp-rrdd/bin/rrdd/dune
ocaml/xcp-rrdd/bin/rrdd/rrdd_server.ml
ocaml/xcp-rrdd/bin/rrdd/rrdd_shared.ml
ocaml/xcp-rrdd/bin/rrdd/xcp_rrdd.ml

RRD loop is executed each 5 seconds. It delays fixed 5 seconds between each loop. But the loop self also consumes time (The time consuming depends on CPU's count. If there are many CPUs, the time consuming may be hundreds milliseconds). This implementation leads RRD will take an offset after several loops. Then one of RRD data lose and a gap can be observed on XenCenter performance graph.
The solution is to use computed delay (timeslice - loop time consuming) instead of fixed delay.

CA-409482: Using computed delay for RRD loop

---

ocaml/xapi/xapi_services.ml

Sorry folks, looks like we need an epilogue of #6457 forget about this backwards compatability issue. Backwards compatability is hard...

SXM: Keep previous http handler for back-compat

---

ocaml/xapi/storage_access.ml

When we have multiple SM plugins in XAPI for the same type (which happens only because of past problems) and want to remove the obsolete one, do this iby  reference. The code so far was assuming only one per type and looked up the reference by name which was not unique and hence could end up removing the wrong SM entry.

CA-409949 CA-408048 XSI-1912 remove unavailable SM plugin by ref

---

ocaml/xapi-idl/xen/xenops_interface.ml
ocaml/xapi-types/dune
ocaml/xapi-types/features.ml
ocaml/xapi/xapi_xenops.ml
ocaml/xenopsd/c_stubs/xenctrlext_stubs.c
ocaml/xenopsd/lib/xenops_server.ml
ocaml/xenopsd/xc/domain.ml
ocaml/xenopsd/xc/domain.mli
ocaml/xenopsd/xc/xenctrlext.ml
ocaml/xenopsd/xc/xenctrlext.mli
ocaml/xenopsd/xc/xenops_server_xen.ml

This needed:
- Changes in the C bindings to be able to set the hard affinity for each vcpu. This needed change in the basic call to be able to set hard and soft affinities, at the same time.
- Stop feeding xenguest the hard affinities when user did not set any in particular. Prior to the all->all priorities were set instead, with the misfortune of setting them after the NUMA code had decided the affinities and set them, overriding the desired values. Fortunately xenguest is able to cope with the missing values. (edwin found this strange behaviour)
I took time to fix the exhaustivity issue when defining features, and now xenopsd sets the hard affinities when the user has hardcoded them for a VM, instead of sending them for xenguest to read them.
Tests:
- manually tested that soft-pinning …

Add experimental feature to use hard affinities when using best-effort (CP-54234)

---

ocaml/xapi/xapi_host.ml

- Refine the exception when `host.enable_ssh/host.disable_ssh` failed
- Reset the `host.ssh_expiry` to default when `host.enabl_ssh` with no timeout

CA-410948 Refine the Exception when disable/enable SSH failed

---

ocaml/xapi-cli-server/cli_frontend.ml
ocaml/xapi-cli-server/cli_operations.ml

To pass file content to a plugin, vm-call-plugin supports passing the content of a client-side file as a parameter. This is missing for host-call-plugin - this patch adds it. Otherwise it is difficult to pass anything beyond a short string to a plugin.

Add file-upload support to xe host-call-plugin

---

ocaml/libs/xapi-rrd/lib/rrd.ml
ocaml/xcp-rrdd/bin/rrdp-cpu/rrdp_cpu.ml

To handle deviations in CPU rates, Derive values exceeding the maximum by up to 5% are capped at the maximum; others are marked as unknown. This logic is specific to Derive data sources because they represent rates derived from differences over time, which can occasionally exceed expected bounds due to measurement inaccuracies.

CA-411679: Runstate metrics return data over 100%

---

ocaml/xapi/xapi_vm_lifecycle.ml

In XSI-1915, MCS shutdowned a VM and tried to destroy VBD right after MCS received the event which came from power_state's change and failed. The failure reason is below:
1. The update for VM's power_state and the update for VBDs is not a transaction, so the client may receive the event from the update for power_state and operate VBDs before the update for VBDs.
2. The VM's running on supporter. The DB operation needs to send RPC to the coordinator. This needs time.
3. Between the update for VM's power_state and the update for VBD, xapi also updates the field pending_guildencs which needs at least 8 DB operation. This also delays the update for VBDs. 
It's not straightforward to add transactions for these DB operations. The workaround is to move the update for pending_guildencs to the end …

CA-411766: Detach VBDs right after VM Halted

---

CONTRIBUTING.md
README.markdown

Some rough guidelines on the contribution process for the project. Intended more as a starting point for a discussion.

CONTRIBUTING: add some initial guidelines

---

dune-project
ocaml/xcp-rrdd/bin/rrdview/dune
ocaml/xcp-rrdd/bin/rrdview/rrdgraph.ml
ocaml/xcp-rrdd/bin/rrdview/rrdgraph.mli
ocaml/xcp-rrdd/bin/rrdview/rrdview.ml
opam/xapi-tools.opam

I wrote this in ~2022, so I don't fully remember how it all works, but I tried to document what I know in the commit message, in the CLI flag docs and here:
```
scp -r root@$YOURBOX:/var/lib/xcp/blobs/rrds /tmp/rrds
dune exec ./rrdview.exe -- /tmp/rrds
bash /tmp/rrds/16db833b-7cd6-4b69-9037-144076c71033.cpu_avg.DERIVE.sh
```
Viewing RRDs produced by xcp-rrdd is difficult, because the format is incompatible with rrdtool. rrdtool has a hardcoded limit of 20 char for RRD names for backward compat with its binary format.
Steps:
* given a directory of xml .gz files containing xcp-rrdd produced rrds
* invokes itself recursively with each file in turn using xargs -P (easy way to parallelize on OCaml 4)
* load all RRDs, and split them into separate files, allowing us to shorten many of their …

CP-308049: rrdview tool

---

ocaml/idl/datamodel_lifecycle.ml
ocaml/idl/datamodel_vm.ml
ocaml/xapi-cli-server/cli_frontend.ml
ocaml/xapi-cli-server/cli_operations.ml
ocaml/xapi/message_forwarding.ml
ocaml/xapi/xapi_vm.ml
ocaml/xapi/xapi_vm.mli

This API call and corresponding XE implementation calls a host plugin on the host where a VM is running. It thus takes care of finding the right host, compared to Host.call_plugin where this would be left to the user.

CP-308252 add VM.call_host_plugin

---

.github/workflows/1.249-lcm.yml

at least for a while longer...
Mirrors the changes in the 1.249 LCM branch: #6473

github: keep scheduled yangtze's runs working

---

ocaml/gencert/dune
ocaml/gencert/lib.ml
ocaml/gencert/selfcert.ml
ocaml/gencert/selfcert.mli
ocaml/gencert/test_lib.ml
ocaml/tests/dune
ocaml/tests/test_certificates.ml
ocaml/xapi-aux/networking_info.ml
ocaml/xapi-aux/networking_info.mli
ocaml/xapi/cert_refresh.ml
ocaml/xapi/certificates.ml
ocaml/xapi/certificates.mli
ocaml/xapi/certificates_sync.ml
ocaml/xapi/dune
ocaml/xapi/helpers.ml
ocaml/xapi/xapi_db_upgrade.ml
ocaml/xapi/xapi_session.ml

Unfortunately mirage-crypto has accumulated breaking changes:
- Cstructs have been replaced with strings
- The digestif library has replaced ad-hoc hash implementation
A deprecation has happened as well:
- RNG initialization has changed
Because there are breaking changes, xs-opam changes need to be introduced at the same time: https://github.com/xapi-project/xs-opam/pull/731
Only xapi is affected by the breaking builds, so no other toolstack repositories have incoming PRs.
I've tested builds with  Smoke and validation tests: SR 218740
This means that the merge will be done as such:
- Both PRs are approved
- First I will merge xs-opam will be emrged (with failing CI)
- Then this PR will be merged with the merge train that runs tests before actually merging.
- CI is rerun manually on …

Adapt code to new mirage-crypto (CP-308222) 

---

ocaml/libs/xapi-stdext/lib/xapi-stdext-unix/unixext.ml
ocaml/libs/xapi-stdext/lib/xapi-stdext-unix/unixext.mli
ocaml/networkd/lib/network_utils.ml
ocaml/xapi/xapi_vgpu_type.ml
ocaml/xenopsd/xc/xenguestHelper.ml

It's an in-house joke that most of `xapi`'s errors are "expected" (either because they're handled by the caller after being logged or because they are frequent and benign) and knowing which ones are unusual and actually critical takes a lot of learning. Try to remove at least some of the most obvious ones from the toolstack startup/VM resume, either removing the logs completely or downgrading it to `debug` when appropriate.
Manually tested in the appropriate scenarios.

Don't pollute the logs with some errors

---

ocaml/xe-cli/bash-completion

Handle a few more cases, fix logging, reduce slowdown

Improve `xe-cli` completion

---

ocaml/xapi/dbsync_slave.ml
ocaml/xapi/xapi_globs.ml
ocaml/xapi/xapi_pool.ml

This PR aim to add following change for auto-mode:
Copy the auto-mode setting from the pool coordinator during a pool join. and restore the auto-mode setting to default value when a pool eject occurs.
- In XS8, the auto-mode is set to false by loading the config file `/etc/xapi.conf.d/ssh-auto-mode.conf`.
- In XS9, default value is set to true.

CP-54384 Update Auto-Mode Configuration for Pool Operations and Default Values

---

ocaml/networkd/bin/network_server.ml

In the upgrade scenario, net devices order has been converted to initial rule and pass to new system. See https://github.com/xenserver/host-installer/pull/249
This PR is to handle the remaining things in networkd:
- Recognize upgrade scenario to run sort for upgrade
- Generate changed interfaces list to update networkd db
- Get management interface and address type from `/var/tmp/.previousInventory` and write to inventory

CP-308260: Handle networkd upgrade

---

ocaml/libs/tracing/tracing_export.ml
ocaml/libs/tracing/tracing_export.mli
ocaml/tests/bench/bench_tracing.ml
ocaml/xapi/xapi_fuse.ml
ocaml/xs-trace/dune
ocaml/xs-trace/xs_trace.ml

Soon after Host.evacuate XAPI could be restarted (e.g. on coordinator promotion).
But we only export traces every 30s, so we lose the spans from the last 30s, including the toplevel Host.evacuate span (which although long running is only emitted on completion).
After this change I'm now able to see Host.evacuate and all the migrate calls in the exported distributed trace.

CA-412313: don't lose distributed tracing spans when XAPI is shut down

---

ocaml/tests/test_xapi_xenops.ml
ocaml/tests/test_xenopsd_metadata.ml
ocaml/xapi-cli-server/cli_frontend.ml
ocaml/xapi-cli-server/cli_operations.ml
ocaml/xapi-consts/constants.ml
ocaml/xapi/cpuid_helpers.ml
ocaml/xapi/create_misc.ml
ocaml/xapi/xapi_globs.ml
ocaml/xapi/xapi_xenops.ml

`Host.cpu_info` list no longer contains a value associated with
a "features" key, but the CLI implementation was hardcoded to expect it.
As a result, it would show an unhelpful error like:
```
The server failed to handle your request, due to an internal error.
The given message may give details useful for debugging the problem.
message: INTERNAL_ERROR: [ Not_found ]
```
Instead use the `cpu_info_features` keys from xapi-consts (after moving these keys from xapi-globs first).
Add the pool version of the command.
Additionally document their output format:
```
command name            : host-get-cpu-features
reqd params     :
optional params : uuid
description     : Prints a hexadecimal representation of the host's physical-CPU
features for PV and HVM VMs. features_{hvm,pv} are "maximum" …
```

Fix `xe host-get-cpu-features` command, add `pool-get-cpu-features`

---

ocaml/networkd/lib/network_utils.ml

SR-IOV (Single Root I/O Virtualization) is a technology that allows a single physical PCI Express (PCIe) device, such as a network adapter, to be shared efficiently among multiple virtual machines (VMs) or containers. It achieves this by creating Virtual Functions (VFs) that act as lightweight PCIe functions, each assigned to a VM, while the Physical Function (PF) remains responsible for managing the device.
Add check in Sysfs.is_physical - check if there is "physfn" in the device dir to filter out VF, then XAPI will not create PIF object for VF during scan.

CA-412146 Filter out VF when scan

---

ocaml/xapi/context.ml
ocaml/xapi/context.mli
ocaml/xapi/server_helpers.ml

Simplifies the logic of `exec_with_context` by letting the caller decide when the task is destroyed from the database.
Adds helper function in `context.ml` to destroy and trace the destroy op correctly.

CP-308253: `Task.destroy` spans should no longer be orphaned

---

ocaml/xapi/xapi_vdi.ml
ocaml/xapi/xapi_vm_lifecycle.ml

events_from_xenopsd thread is critical as it sync up VM status in case of bootstorm, this thread is flood as lots of events comes from xenopsd waiting for process.
During processing of the events, VM/VDI/VBD update_allowed_operations will be called to refresh the allowed operations.
However, for each ops (start/suspend,etc) for the same object(VM), the object info is always the same no matter what the ops is. Thus, it is not necessary to query the object information over and over again.
Disclosure is used to resovle the issue. Query once and the disclosure will just remember the query result.
The performance test for starting 500 VM on 4 hosts improve around 10% performance for both XS8 and XS9

CA-408552: Improve bootstrom performance by save db ops

---

ocaml/xapi/message_forwarding.ml
ocaml/xapi/workload_balancing.ml

1. WLB request will raise `wlb_authentication_failed` when catching `Http_client.Http_error`. But actually only error code 401 and 403 should raise this type exception. For other error code, raise `wlb_connection_reset`. Also print the detail error code and message.
2. `message_forwarding` raises same error for `Http_request_rejected` and `Connection_reset` so we don't know which exception actually be raised. Print detailed logs for these 2 exceptions.

CA-406770: Improve error message

---

python3/bin/xe-reset-networking

If interface-rename script doesn't exist, networkd will
- handle the interfaces sorting
- write inventory when first boot
So, when interface-rename doesn't exist, xe-reset-networking should:
- NOT call interface-rename script
- Delete MANAGEMENT_INTERFACE value in inventory.
BTW, the current bridge name conversion method rely on hardcode 'eth' which is correct only when interface-rename script exists.

CP-54441 Adapt interface ordering in xe-reset-networking

---

doc/content/design/sm-supported-image-formats.md

Add details on specifying image format for VDI and VM migration. In particular This revision explains how to choose the destination image format during VDI creation and migration, including VM migration scenarios.
Also fixes minor typos in the document.

Design proposal for supported image formats (v3)

---

ocaml/xapi/create_misc.ml

The `ref` parameter within the `location` attribute of the console can refer to either the VM's ref or the console's own ref. Currently, the console's location uses the VM's ref by default.
This causes an issue: when executing xe console, the requested location contains the VM's ref. If the ref points to the VM, xapi will attempt to use the RFB console (which is graphical) by default, rather than the VT100 console (which is text-based). As a result, the xs console command fails to open the console and hangs.
**Solution:**
Update the default ref in the console's `location` to the console's own ref. With this change, whether accessing the RFB or the VT100 console, the ref in the `location` will always point to the respective console itself.

CA-410965: Modify default ref of console

---

ocaml/xapi/extauth_plugin_ADwinbind.ml

According to
https://www.freedesktop.org/software/systemd/man/latest/hostname.html Systemd set hostname with following sequence
- kernel parameter, systemd.hostname
- static hostname in /etc/hostname
- transient hostname like DHCP
- localhost at systemd compile time
Once the host is configured with static IP and reboot, it would just lost its hostname as no DHCP or static IP available.
However, the hostname is critical to AD function as it construct the machine account.
The hostname should be persisted as static name during joining AD, this is also what PBIS does.
Note: the static hostname is not cleaned during domain leave. This is by intention to avoid losing hostname after reboot with static IP
cba2f1d5e4340b352f32effeacb023a0315d671b tried to resovle the issue and update …

CA-412636: hostname changed to localhost with static IP and reboot

---

ocaml/idl/datamodel_errors.ml
ocaml/xapi-consts/api_errors.ml
ocaml/xapi/xapi_vm_lifecycle.ml

Don't assume the presence of PV drivers magically solves everything, actually honour `feature-suspend` and make `data/cant_suspend_reason` critical.
----
Manually tested to not break the following cases (thanks to @dinhngtu):

`xapi_vm_lifecycle`: Improve feature handling, avoid crashes

---

ocaml/networkd/lib/network_device_order.ml

The bus-info of a USB-based network device follows the format `usb-<PCI address of USB controller>-<USB port path>`. To determine the device's order when sorting, use the PCI address of the USB controller.

CP-54468 Handle USB network devices in network devices sort

---

ocaml/xenopsd/lib/xenops_server.ml
ocaml/xenopsd/lib/xenops_server_plugin.ml
ocaml/xenopsd/lib/xenops_server_simulator.ml
ocaml/xenopsd/lib/xenops_server_skeleton.ml
ocaml/xenopsd/xc/xenops_server_xen.ml

This is a partial revert of 1a46f33be768. It retains the deactivate and detach functions introduced but restores the original unplug function so that the VBD_unplug atom is completely unchanged when xenops_vbd_plug_unplug_legacy=true instead of running deactivate followed by detach.
This will fix the S(Does_not_exist) Xenopsd errors we are seeing in some VBD_unplug calls, until a fix for the split functions is found (I have created CA-413304 to track that issue)

CA-413304: Restore VBD.unplug function to keep old functionality

---

ocaml/libs/xapi-stdext/lib/xapi-stdext-threads/scheduler_test.ml

On very busy systems, the wait may take much longer than expected. Instead of hard-coding the expected value, wait once to estimate the time aded to the delays, and then use it to compare the times.
Also change to use Mtime.Spans instead of using integers.
I've tested this locally on unit-tests, and @ydirson has tested this on his system that usually needs a patch to disable these tests because they run on an cpu-overprovisioned xen system

xapi-stdext-threads: calibrate ratio for delay times

---

python3/libexec/usb_reset.py
python3/tests/import_helper.py
python3/tests/test_usb_reset.py
python3/tests/test_usb_scan.py

The approach work for both XS8 and XS9
- 4357061 for xs9
- 4357062 for xs8
```
Date:   Fri Jul 4 15:40:00 2025 +0800
CA-393417: Bind mount /proc/<pid> into chroot
From strace/gdb, XS9 qemu requires /proc/self/fd/<fd> to work well
This is due to systemd/libudev update.
Just bind mount /proc/self/ to the chroot to permit qemu access
```
1047 openat(AT_FDCWD, "/proc/self/fd/46", O_RDONLY|O_NOCTTY|O_CLOEXEC|O_PATH) = -1 ENOENT (No such file or directory)
1048 openat(AT_FDCWD, "/proc/", O_RDONLY|O_NOCTTY|O_CLOEXEC|O_PATH) = -1 ENOENT (No such file or directory)
../sysdeps/unix/sysv/linux/fstatfs64.c:30
out>, dir_fd=<optimized out>) at ../src/basic/stat-util.c:566
magic_value=1650812274) at ../src/basic/stat-util.c:369
fd=<optimized out>) at ../src/basic/stat-util.h:66
verify=<optimized out>) …

CA-393417: Drop device controller of cgroup v1 and fix USB passthrough for XS9

---

ocaml/xapi/xapi_periodic_scheduler_init.ml

When XAPI fails for an extended period that exceeds the timeout duration, it loses the original auto-mode setting that was configured before the timeout. After XAPI restarts, the auto-mode should be reset to true for security purposes.

CA-413328 Enable auto-mode when XAPI failed for a extend period that exceeds the timeout duration

---

ocaml/rrd2csv/src/rrd2csv.ml
ocaml/tests/binpack_test.ml
ocaml/xapi-cli-server/cli_util.ml
ocaml/xapi-idl/storage/storage_test.ml
ocaml/xapi-idl/storage/vdi_automaton.ml
ocaml/xapi/helpers.ml
ocaml/xapi/pool_features_helpers.ml
ocaml/xapi/xapi_bond.ml
ocaml/xapi/xapi_globs.ml
ocaml/xapi/xapi_host.ml

It's an equivalent, but much cleaner construct, which in addition avoids needlessly iterating over the list after the first match is found.

Replace `List.fold_left (||) false (List.map f lst)` with `List.exists f lst`

---

ocaml/idl/datamodel_errors.ml
ocaml/xapi-cli-server/cli_operations.ml
ocaml/xapi-idl/v6/v6_interface.ml
ocaml/xapi/xapi_host.ml

The first argument of this API error is used for error codes as defined by v6d. These product-specific error codes can be matched on by clients who know about them (e.g. XenCenter for XenServer).
The new, second argument allows v6d to return an error message in English that xe can print directly, while xe remains product agnostic and does not need to know v6d's error definitions. This replaces some awkward API-message handling code in cli_operations.

Add message argument to LICENSE_CHECKOUT_ERROR

---

ocaml/idl/datamodel_errors.ml
ocaml/tests/test_clustering.ml
ocaml/xapi/helpers.ml
ocaml/xapi/message_forwarding.ml
ocaml/xapi/xapi_cluster_helpers.ml
ocaml/xapi/xapi_cluster_host_helpers.ml
ocaml/xapi/xapi_host_helpers.ml
ocaml/xapi/xapi_pif.ml
ocaml/xapi/xapi_pool_helpers.ml
ocaml/xapi/xapi_sr_operations.ml
ocaml/xapi/xapi_vbd.ml
ocaml/xapi/xapi_vbd_helpers.ml
ocaml/xapi/xapi_vdi.ml
ocaml/xapi/xapi_vif_helpers.ml
ocaml/xapi/xapi_vm_appliance_lifecycle.ml
ocaml/xapi/xapi_vm_lifecycle.ml
ocaml/xapi/xapi_vusb_helpers.ml
quality-gate.sh

`other_operation_in_progress` is reported inconsistently, with some users only specifying `[class; class_ref]`, and others also `op_type`. Make it consistent, changing all users to report `[class; class_ref; op_type; op_ref]`. This makes it much easier to navigate the logs, since the operation blocking progress is clearly referenced. 
Compare before, where it's unclear which operation is precluding progress:
```
Caught exception while marking SR for VDI.clone in message forwarder:
OTHER_OPERATION_IN_PROGRESS:
[ SR; OpaqueRef:d019f26a-b2e8-529b-bb66-fd4f008d4f82; VDI.clone ]
```
And after, with the ID of the operation present:
```
Caught exception while marking SR for VDI.clone in message forwarder:
OTHER_OPERATION_IN_PROGRESS:
[ SR; OpaqueRef:b0f54a40-485f-f48f-fdc7-6db28a64d3fd;
scan; …
```

Improve `other_operation_in_progress` error users, fix handling of its delays

---

ocaml/xapi-storage-script/main.ml

During the SMAPIv3 migration prepare step, it will create the VDI on the destination based on the source. The source retrieves vdi_info via `copy_into_sr` → `find_vdi` → `SR.scan2` → `sr_scan2_impl` → `COWVolume.ls`, and `sr_ls` extracts all vdi_info from the database.
However, when creating a snapshot with `COWVolume.snapshot` on V3, the vdi-type is not stored in the database, which causes getting an empty vdi-type and the migration prepare step to fail and result the folllowing error:
`\'INTERNAL_ERROR\', \'Failure("Unknown tag/contents")\']]);S()]]]))]))]))])`
This change adds a step to set vdi-type from the original VDI to the snapshot VDI to prevent this issue.

CA-412420: Set vdi-type When Create snapshot on SMAPIv3 SR

---

doc/content/toolstack/features/Tracing/index.md

It is a quick overview of tracing and how to enable it in XAPI. This PR follows up on this issue #6281 .

[doc] add documentation about tracing

---

.github/workflows/codechecker.yml

See https://github.blog/changelog/2025-07-21-code-scanning-will-stop-combining-multiple-sarif-runs-uploaded-in-the-same-sarif-file/
We are using https://github.com/whisperity/CodeChecker-Action, so likely need to work with upstream to fix this.
For now run the check, but disable SARIF uploads.

Disable SARIF upload for now: they are rejected

---

ocaml/xapi-cli-server/cli_frontend.ml
ocaml/xe-cli/newcli.ml

The previous `xe` help is as below:
```
Usage: xe <cmd> [-s server] [-p port] ([-u username] [-pw password] or [-pwf <password file>]) [--traceparent traceparent] <other arguments>
A full list of commands can be obtained by running
xe help -s <server> -p <port>
```
The previous `xe` help output lacked debug-related options and did not provide detailed parameter description.
The new `xe` help output is as follows:
```
Usage:
xe <command>
[ -s <server> ]            XenServer host
[ -p <port> ]              XenServer port number
[ -u <username> -pw <password> | -pwf <password file> ]
User authentication (password or file)
[ --nossl ]                Disable SSL/TLS
[ --debug ]                Enable debug output
[ --debug-on-fail ]        Enable debug output only on failure
[ --traceparent …
```

CA-413424: Enhance xe help output

---

ocaml/xapi/vm_sysprep.ml
ocaml/xapi/vm_sysprep.mli
ocaml/xapi/xapi_vm.ml

We have seen failures to eject the CD at the end; catch exceptions when failing to eject the ISO/CD from the VM.

CP-308455 VM.sysprep CA-414158 wait for "action" key to disappear

---

ocaml/xapi/xapi_session.ml

```
commit 92377bfe2fffd762ab922a015a93afa314ae000f (HEAD -> private/linl/CA-414418, origin/private/linl/CA-414418)
Author: Lin Liu <Lin.Liu01@cloud.com>
Date:   Thu Jul 31 07:25:30 2025 +0000
CA-414418: Perf: save user validate result and apply to sessions
For all sessions created by external/AD users, session revalidate
will check whether the users are still acitve, and kick off the
session accordingly.
However, xapi check the user for every session. The problem here
is lots of session are created by only a few users. (for the case
of CVAD and ControlUP). This would cause lot of duplicated check
for the same user again and again, which is slow and waste lots
of resources.
To fix the issue, [(user_sid, check_result)] is defined for every
round of check. The check result is saved so later …
```

CA-414418: Sessions do not got destroyed after domain  user been removed and performance improvement

---

ocaml/tests/common/test_common.ml
ocaml/xapi-idl/xen/xenops_interface.ml
ocaml/xapi/cpuid_helpers.ml
ocaml/xapi/cpuid_helpers.mli
ocaml/xapi/create_misc.ml
ocaml/xenopsd/lib/xenops_server_skeleton.ml
ocaml/xenopsd/xc/xenctrlext.ml
ocaml/xenopsd/xc/xenctrlext.mli
ocaml/xenopsd/xc/xenops_server_xen.ml

`host.cpu_info` is a map that contains details about the physical CPUs on this host. This PR adds a key of nr_nodes in the field to expose numa nodes count.
Use `Xenctrlext.numainfo` to get the array size of numainfo.memory, see https://github.com/xapi-project/xen-api/blob/v25.26.0/ocaml/xenopsd/c_stubs/xenctrlext_stubs.c#L395

CP-308927 Add nr_nodes in host.cpu_info to expose numa nodes count

---

ocaml/xapi/xapi_globs.ml
scripts/xapi.conf

Polling mode is a performance optimization in tapdisk, where it would busy poll the PV ring for the next request, instead of going to sleep and waiting for an event channel to wake it up when the next request arrives. When the guest supplies us with a steady sequence of IO requests this is quicker (it avoids a lot of syscalls), at the expense of consuming more Dom0 CPU.
Once polling mode is entered if there are no requests for polling-duration microseconds, then polling mode is exited.
The wakeup granularity is 4ms on the 4.19 kernel (which also matches CONFIG_HZ=250).
The default polling duration is 1ms, but we may not be able to reliably handle such low timeouts.
On newer kernels we seem to hit the 1ms polling duration timeout all the time, which results in tapdisk entering and exiting …

CA-414627: increase polling duration for tapdisk

---

ocaml/xcp-rrdd/bin/rrdp-cpu/rrdp_cpu.ml

Squashed the history in PR https://github.com/xapi-project/xen-api/pull/6612 together with the history in feature/vcpu-runnable.

RRD metrics: "runnable_any" and "runnable_vcpus"

---

ocaml/xapi/xapi_vm_helpers.ml
ocaml/xenopsd/lib/xenops_server.ml
ocaml/xenopsd/lib/xenops_server_plugin.ml
ocaml/xenopsd/lib/xenops_server_simulator.ml
ocaml/xenopsd/lib/xenops_utils.ml
ocaml/xenopsd/xc/domain.ml
ocaml/xenopsd/xc/domain.mli
ocaml/xenopsd/xc/xenops_server_xen.ml

xenopsd currently hardcodes 64 as the value for `max_grant_frames` for all domains. This limits how many grants a domain can allocate, thus limiting the number of VIFs and VBDs a domain can have. `max_grant_frames` can be changed for individual VMs through specifying a particular value in `platform`, but it's much better to be able to estimate how many grant frames a VM would need based on the number of VBDs and VIFs.
Implement this and add some notes on the difficulties and imprecisions of such an estimation.
This allows raising the number of supported VIFs from the current limit of 7 - we've picked 16 as a sweet spot, though this could be discussed further. (note that it's the `allowed_vifs` limit that's changed, VIFs can be created in arbitrary numbers on the CLI and by clients not …

Raise VIF limit from 7 to 16 by calculating `max_grant_frames` on domain creation

---

.github/workflows/generate-and-build-sdks.yml
ocaml/sdk-gen/go/gen_go_binding.ml

Now `VM.sysprep`'s XML content can be declared as `SecretString` again.

CA-413254: Types `String` and `SecretString` were generating duplicates of method serializeString in convert.go.

---

ocaml/xapi/xha_interface.ml

https://github.com/xenserver/xha/commit/7ed46d6a871422837aae6a8d62eead0fa362585e
Add a new field *HostIndex* into the ha_query_liveset result, Xapi needs to update accordingly to parse the result, Otherwise, xapi can not parse the result and understand the liveset thus cause pool-ha-enable always failed
This commit fix the issue and intend to be compatible with old/new xha, to update smoothly

CA-415952: HA can not be enabled

---

ocaml/networkd/bin/network_server.ml
ocaml/networkd/bin_db/networkd_db.ml
ocaml/networkd/lib/network_config.ml
ocaml/xapi-idl/network/network_interface.ml
ocaml/xapi/nm.ml

Because Autoconf is not DHCP, networkd uses the dns value to write to
resolv.conf. This is done on ocaml/networkd/bin/network_server.ml line 745
This allows to have non-empty resolv.conf when using IPv6 autoconf.
This mismatch was caused byt technical debt that cause this check to be duplicated, the second removes it so 
xapi decides the instances where these values are written and networkd follows that decision.
I've tested new isntallations using IPv4 and couldn't see any regression, two users have tested the patch and now the DNS entries don't get overriden when using IPv6 in Autoconf mode: https://github.com/xcp-ng/xcp/issues/641#issuecomment-3094208413
I'd like Rob to review this approach in any case

xapi/nm: Send non-empty dns to networkd when using IPv6 autoconf

---

ocaml/xapi/xapi_globs.ml
ocaml/xapi/xapi_ha.ml
ocaml/xapi/xapi_ha_vm_failover.ml
ocaml/xapi/xapi_ha_vm_failover.mli

The issue occurs in a scenario involving a HA-enabled pool. A VM with its VM.ha_restart_priority set to best-effort is running on a host. The VM's disk resides on the host's local storage. When the host goes down, the VM cannot be restarted on other hosts due to the disk's local storage dependency. However, after the host recovers and comes back online, the VM still does not automatically start on the original host.
Expected behavior: The VM should automatically start on the original host once it has recovered. Generally, this behavior should be applied to all non-agile VMs.

CA-412983: HA doesn't keep trying to start best-effort VM

---

.github/workflows/generate-and-build-sdks.yml
ocaml/sdk-gen/csharp/autogen/src/Event.cs
ocaml/sdk-gen/csharp/autogen/src/Failure.cs
ocaml/sdk-gen/csharp/autogen/src/HTTP.cs
ocaml/sdk-gen/csharp/autogen/src/JsonRpc.cs
ocaml/sdk-gen/csharp/autogen/src/Session.cs
ocaml/sdk-gen/csharp/autogen/src/XenObject.cs
ocaml/sdk-gen/csharp/autogen/src/XenServer.csproj
ocaml/sdk-gen/csharp/gen_csharp_binding.ml
ocaml/sdk-gen/powershell/autogen/src/XenServerPowerShell.csproj

The commit authored by Edwin is porting the changes from https://github.com/xapi-project/xen-api/pull/5929.

Support for .NET8 and Tracing information

---

ocaml/xapi/dbsync_slave.ml
ocaml/xapi/firewall.ml
ocaml/xapi/firewall.mli
ocaml/xapi/xapi_globs.ml
ocaml/xapi/xapi_host.ml

Implement dynamic control of firewalld service.
The first PR defines dynamic firewall control function, variable, and the http service's dynamic control.
The other services's dynamic control will be in the later PR.

CP-308800: Dynamic control of firewalld service - part 1

---

.github/workflows/main.yml

This allows to see any regressions happening while not blocking any merges.
This is useful to have as a base to make xapi work on arm-based hosts, which is an objective for xcp-ng.
Depends on https://github.com/xapi-project/xs-opam/pull/737 being merged first, and needs to tweak the required workflows to add the runner and experimental mode. I'll do the latter before merging

ci: enable experimental ocaml workflow on aarch64

---

ocaml/idl/datamodel_vm.ml
ocaml/xapi-cli-server/cli_operations.ml
ocaml/xapi-types/secretString.ml
ocaml/xapi-types/secretString.mli
ocaml/xapi/vm_sysprep.ml
ocaml/xapi/vm_sysprep.mli
ocaml/xapi/xapi_vm.mli

This is simply a cherry pick of @lindig 's commit from https://github.com/xapi-project/xen-api/pull/6547 now that we have fixed https://github.com/xapi-project/xen-api/pull/6622. Let me know if anything more is needed.
> CP-308455 VM.sysprep declare XML content as SecretString
> Desclare the string parameter holding unattend.xml as secret to avoid logging it.
> 
> Signed-off-by: Christian Lindig <christian.lindig@cloud.com>
Conflicts:
- ocaml/idl/datamodel_vm.ml
- ocaml/xapi/vm_sysprep.mli
- ocaml/xapi/xapi_vm.mli

Restored type SecretString for sysprep's parameter unattend

---

ocaml/xapi/dbsync_slave.ml
ocaml/xapi/firewall.ml
ocaml/xapi/firewall.mli
ocaml/xapi/nm.ml
ocaml/xapi/xapi_clustering.ml
ocaml/xapi/xapi_ha.ml
ocaml/xapi/xapi_host.ml
ocaml/xapi/xapi_periodic_scheduler_init.ml

Dynamic control other firewalld services, including:
- VxLan
- Xha
- Cluster
- SSH
Besides, adding the following compatibility for iptables and firewalld:
1. For legacy iptables, some ports need dynamic control but some don't. So add a flag to decide if the port needs dynamic control.
2. Revert https_only update logic.

CP-308800: Dynamic control of firewalld service - part 2

---

ocaml/networkd/bin_db/networkd_db.ml

This is a simplified version of commit 846ce82ba3. The feature introduced that commit is to remove the network device renaming functionality. When the feature is merged, there will be 3 states of releases:
1. without the feature.
2. with the feature but renaming is still working.
3. with the feature and renaming has been removed.
Originally, the upgrade path was intended to support transitions from state 2 to state 3 only. However, it has become necessary to also support upgrades directly from state 1 to state 3.
This commit is to enable the release in state 1 to upgrade to state 3. The change is kept extremely small so it can be merged independently without waiting for the full feature to be merged.
In details, during the upgrade, the host-installer can't know the management interface as …

CP-309523: Make networkd_db utility return bridge MAC address

---

ocaml/libs/xapi-rrd/lib/rrd.ml
ocaml/libs/xapi-rrd/lib_test/unit_tests.ml

Absolute metric should work as follows:
Timestamp    = 300, 600, 900, 1200
Step         = 300 seconds
ABSOLUTE DS  =    1,  2,   3,    4
But they do not seem to have ever worked correctly - they were previously divided by the interval but incorrectly handled NaNs, resulting in wrong behaviour. Then the refactoring (including 73ca3cc ("CA-404597: rrd - Pass Gauge and Absolute data source values as-is")) broke them further.
Divide absolute metrics by the interval in process_ds_value. Fix the unit test to expect the right behaviour - it passes with this fix.
---
This means  absolute metrics are now correctly calculated as unit/s, changing the behaviour in https://github.com/xapi-project/xen-api/pull/6640 
I am not 100% sure this fix goes all the way either - unit tests should cover expected …

rrd: Fix absolute rate calculations

---

ocaml/xapi/xapi_vm_migrate.ml

Cross-pool migrations set `scheduled_to_be_resident_on` to the destination host, reserving memory and vGPUs. If the VM is still halted when migration is finished, the field is not cleared on the destination, preserving the reservations even though they're not necessarily going to be used anytime soon.
Call `force_state_reset_keep_current_operations` in `pool_migrate_complete` on the destination to clear the reservations among other things at the end of the migration.
This fixes an issue when VMs migrated across pools in a halted state would take up memory in xapi's view (but not in RRD's view), which is not intuitive and could prevent further migrations from claiming enough free memory on the host.
---
I've tested this manually, confirming that migrating halted and running VMs works as …

xapi_vm_migrate: Fix reservations not being cleared on halted VMs

---

ocaml/xapi/xapi_pif.ml
ocaml/xapi/xapi_pif.mli

For pif which is vlan-master or sriov-logic-pif, its pif.device comes from its vlan-slave or sriov-physical-pif pif.device.
For example:
```
uuid ( RO)                     : 00bfb6be-041b-2d16-4118-e98d4f4758a1
device ( RO): eth1
physical ( RO): false
currently-attached ( RO): false
VLAN ( RO): 12
vlan-master-of ( RO): 7efb4476-95d7-e27e-6646-983e33ef9a67
vlan-slave-of ( RO):
uuid ( RO)                     : 32073526-d992-3a2f-9653-f5f5b368680f
device ( RO): eth1
physical ( RO): true
currently-attached ( RO): true
VLAN ( RO): -1
vlan-master-of ( RO): <not in database>
vlan-slave-of ( RO): 7efb4476-95d7-e27e-6646-983e33ef9a67
```
Their names are both eth1. In this feature branch, the interface name may change after RPU. The physical pif.device is synced in
refresh_internal. But the vlan or …

CA-416692 Sync vlan or sriov pif.device

---

ocaml/xapi/message_forwarding.ml
ocaml/xapi/xapi_stats.ml
ocaml/xapi/xapi_stats.mli

This metric represents the rate of VM migrations with vGPUs per second.
The total count can be calculated as AVERAGE * seconds. For example,
for one-day data granularity, the total count for one day is
AVERAGE * 86400, in which 86400 is the seconds of one day.

CP-308863: Count vGPU migrations

---

ocaml/xenopsd/scripts/qemu-wrapper

see cgroups v2 "no internal processes" rule
if cgroup.subtree_control is not empty, and we attach a pid
to cgroup.procs, kernel would return EBUSY

CA-416516: vm.slice/cgroup.procs write operation gets EBUSY

---

ocaml/xapi/dbsync_slave.ml
ocaml/xapi/firewall.ml
ocaml/xapi/firewall.mli
ocaml/xapi/network_event_loop.ml
ocaml/xapi/nm.ml
ocaml/xapi/xapi_clustering.ml
ocaml/xapi/xapi_ha.ml
ocaml/xapi/xapi_host.ml
ocaml/xapi/xapi_periodic_scheduler_init.ml

This PR is for dynamic control NBD firewalld service.
Also, changed labeled arguments to fixed arguments for the function `update_firewall_status` to support the optional argument `interfaces`.

CP-308798: Dynamic control of firewalld service - part 3

---

ocaml/idl/datamodel_lifecycle.ml
ocaml/idl/datamodel_pool.ml
ocaml/idl/schematest.ml
ocaml/tests/common/test_common.ml
ocaml/xapi-cli-server/records.ml
ocaml/xapi/console.ml
ocaml/xapi/dbsync_master.ml

- First commit:
Introduces a new pool-level parameter that restricts VNC console access
to a single active session per VM/host.
This prevents multiple users from simultaneously connecting to the same VM console,
preventing one user 'watching' another user operating a session.
- Second commit:
When the `limit_console_sessions` is true.
- Enforced a single active VNC console connection per VM/host
- Disable connection to websocket
Tested:
- [root@eu1-dt094 bin]# xe pool-param-get  uuid=de76d8c9-2e1b-f868-39fe-5768bf8c3c0d param-name=limit-console-sessions
true
Only one console can be connected:
- [root@eu1-dt094 bin]# xe pool-param-get  uuid=de76d8c9-2e1b-f868-39fe-5768bf8c3c0d param-name=limit-console-sessions
false
Both consoles can be connected:

Add pool-level field to limit VNC console access to one session per VM/host

---

ocaml/xenopsd/xc/domain.ml
ocaml/xenopsd/xc/domain.mli
ocaml/xenopsd/xc/xenops_server_xen.ml

Some of these were passed through several layers of functions only to be unused in the end. Drop them, improving the legibility of the code.

xenopsd: Drop unused variables in `domain.ml`

---

ocaml/xapi/sync_networking.ml
ocaml/xapi/xapi_pif.ml
ocaml/xapi/xapi_pif_helpers.ml

For pool join procedure, the slave host will go through
1 pre_join_check
2 update_non_vm_metadata: in this step, create pif objects for physical pifs of slave host on master host db.
3 on slave xapi start: copy_bonds_from_master, copy_network_sriovs_from_master, copy_vlans_from_master, copy_tunnels_from_master
This issue happens on step 3 when copy bonds from master.
for every bond on master
- get the bond master pif on master
- get the bond slave pifs on master
- confirm the primary bond slaves via comparing the bond master pif mac
- find the corresponding pifs on slave host
- decide if create bond on slave host
In `find the corresponding pifs on slave host`, the previous method is to compare the pif.device on master and slave hosts. Now we should compare the position of pif device. …

CA-416959 Copy bonds and sriov from master using device position

---

ocaml/xapi/create_misc.ml

The current `make_xen_livepatch_list` function expects exactly 2 parts after splitting, but the output has 3 parts: ID, status, and metadata. When split with ~limit:2, it creates [ID; "status | metadata"], which doesn't match the pattern [key; "APPLIED"], and prevents it from correctly parsing the latest output of `xen-livepatch list `: ~xen-livepatch list
```
ID                                     | status     | metadata
----------------------------------------+------------+---------------
hp_1_1                                  | CHECKED    |
hp_2_1                                  | APPLIED    |
hp_3_2                                  | APPLIED    |
```

CA-417366 make_xen_livepatch_list can not Parse the Output of xen-livepatch

---

ocaml/idl/datamodel.ml
ocaml/idl/datamodel_host.ml
ocaml/idl/datamodel_lifecycle.ml
ocaml/xapi-cli-server/cli_frontend.ml
ocaml/xapi-cli-server/cli_operations.ml
ocaml/xapi/dune
ocaml/xapi/firewall.ml
ocaml/xapi/firewall.mli
ocaml/xapi/message_forwarding.ml
ocaml/xapi/network_event_loop.ml
ocaml/xapi/xapi.ml
ocaml/xapi/xapi_host.ml
ocaml/xapi/xapi_host.mli
scripts/Makefile
scripts/update-xapi-firewalld.service

Update the status of all the firewalld services to match the state of the corresponding services. There are 2 scenarios:
1. When xapi starts, to ensure that all the firewalld services are in the correct state.
2. When the firewalld restarts, all firewalld services are reset to the default status. This function should be called to update these firewalld services to the correct status. Xapi will expose an xe command line for this scenario.

CP-309535: Dynamic control of firewalld service - part 4

---

ocaml/tests/test_helpers.ml
ocaml/xapi/db_gc.ml
ocaml/xapi/helpers.ml
ocaml/xapi/xapi_globs.ml
ocaml/xapi/xapi_host.ml
ocaml/xapi/xapi_vm.ml
ocaml/xapi/xapi_vm_lifecycle.ml

Rolling pool upgrades should only allow VMs to be evacuated to hosts that have the same or higher versions of xapi build or xen.
Previously, the check was done only for platform vision.
I will run a BST again after I squash the fixup to be sure. Otherwise, I think this is ready.

XSI-1987 & CA-416462: Fix RPU host evacuation version check

---

ocaml/tests/suite_alcotest.ml
ocaml/tests/test_rfb_client_msgtype_parser.ml
ocaml/xapi/dune
ocaml/xapi/rfb_client_msgtype_parser.ml
ocaml/xapi/rfb_client_msgtype_parser.mli

The parser only parses the message types for client-to-server messsages, aiming to identify message types from clients.

CP-54393: A simple RFB protocol parser for VNC console connections

---

ocaml/idl/datamodel_host.ml
ocaml/idl/schematest.ml
ocaml/tests/common/test_common.ml
ocaml/xapi-cli-server/records.ml
ocaml/xapi/dbsync_slave.ml
ocaml/xapi/message_forwarding.ml
ocaml/xapi/xapi_globs.ml
ocaml/xapi/xapi_host.ml
ocaml/xapi/xapi_host.mli
ocaml/xapi/xapi_host_max_cstate.ml
ocaml/xapi/xapi_host_max_cstate.mli

C-states are power management states for CPUs where higher numbered states represent deeper sleep modes with lower power consumption but higher wake-up latency. The max_cstate parameter controls the deepest C-state that CPUs are allowed to enter.
Common C-state values:
- C0: CPU is active (not a sleep state)
- C1: CPU is halted but can wake up almost instantly
- C2: CPU caches are flushed, slightly longer wake-up time
- C3+: Deeper sleep states with progressively longer wake-up times
To set max_cstate on dom0 host, two commands are used: `xenpm` to set at runtime and `xen-cmdline` to set it in grub conf file to take effect after reboot.
xenpm examples:
```
max C-state set to C0
max C-substate set to 0 succeeded
max C-state set to C0
max C-substate set to unlimited succeeded
max C-state …
```

CP-54473 Configure max-cstate by XAPI

---

ocaml/xapi/xapi_vm_lifecycle.ml

In XSI-1969 we deal with an inconsistent Xapi DB and fail to recognise a PCI as SRIOV. Be more lenient and recognise stale PCI refs as SRIOV. Also remove a VM from a VGPU explictly on resouce cleanup.

XSI-1969 more thorough resource cleanup

---

ocaml/libs/http-lib/http_svr.ml
ocaml/libs/http-lib/http_svr.mli
ocaml/xapi/system_status.ml
ocaml/xapi/system_status.mli
ocaml/xapi/xapi_vncsnapshot.ml
quality-gate.sh

Now there's no failure when called without parameters, suggests a nice filename with the correct extension, advertises the content-type of the file served, and adds an option to list all the allowed entries supported by xen-bugtool in an xml format.

system_status: enhance useability of the API call

---

ocaml/xapi/xapi_vm_lifecycle.ml

Fixing fabb45e2fb
"Also remove a VM from a VGPU explictly on resouce cleanup."
That part was wrong - we must not remove the VM as we would lose it permanently.

XSI-1969 CA-418141 more thorough resource cleanup
